### ISSUE TITLE
Erreur 500 : Ajout de données régionale 

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#1002]
https://transport.data.gouv.fr/backoffice/datasets

https://www.data.gouv.fr/fr/datasets/arrets-horaires-et-parcours-theoriques-gtfs-du-reseau-routier-regional-de-transport-43/#_

Nom du réseau : réseau routier régional de transport interurbain (60 – Oise)

Le lien de data.gouv de cette région a été copié sur le backoffice, champs rempli (cf.screen ci dessous)

![image](https://user-images.githubusercontent.com/59559301/72730465-b7e8b780-3b91-11ea-9e6c-66999d22ae46.png)

Une fois qu'on clique sur "Ajouter " --> Erreur 500 qui apparaît

**Comment by Tristramg** [comment]
C’est corrigé : https://transport.data.gouv.fr/datasets/arrets-horaires-et-parcours-theoriques-gtfs-du-reseau-routier-regional-de-transport-43/

Il y avait eu un soucis avec une indexation par le passé des mêmes ressources.

L’ancien dataset a été supprimé à la main de la base de données :speak_no_evil:
