### ISSUE TITLE
Ajouter une carte de stats sur les jdd de velos

### ISSUE THREAD

**Issue by antoine-de** [etalab/transport-site#1014]
maintenant qu'on peut associer les jdd de velos à des villes (et non plus à des AO), on peut se lancer dans le rajout d'une carte dans la page `/stats`.

une simple carte avec les zones couvertes par nos données de type `bike-sharing` me parait pas mal (avec un lien pointant vers le dataset quand on clique sur une zone)

**Comment by fchabouis** [comment]
Je vois qu'on a les tables dataset avec les jdd type bike-sharing, la table commune et la table dataset_communes qui fait le lien entre les id des jdd et celui des communes. C'est bien ça ?

Par curiosité, pourquoi on n'a pas plutôt mis une colonne commune_id dans la table dataset ?

**Comment by antoine-de** [comment]
en fait un dataset peut être lié à :
* une région
* une AO
* au pays (mais c'est une feinte, c'est juste une région spécifique)
* une liste de communes (d’où la table d'association, c'est un lien `many_to_many`

Pour abstraire un peu les choses, on a fait une view postgres `dataset_geographic_view` qui permet de récupérer "facilement" la région liée au dataset (soit la région direct, soit la région de l'ao ou des communes), ainsi que la géométrie associée.

Pour la carte des vls je vois 2 approches possibles :
* soit tu récup simplement la liste des datasets de types VLS et tu affiches leur géométrie
  - c'est simple et vu qu'on a pas bcp de dataset et qu'on doit en avoir au max 1 / territoire ca doit le faire
* soit un fait une API `/stats/communes` sur le même modèle que (`/stats/regions` et `/stats/` (qui devrait être renommée `/stats/aoms` d'ailleurs)
  - c'est plus compliqué, faut surement paginer cette api, et la plupart des communes vont être vide, mais c'est plus générique, et on pourra la réutiliser dans les autres cartes de la page `/stats`

tu en penses quoi @Tristramg ?
