### ISSUE TITLE
Afficher les metadata d'une ressource sur la page ressource

### ISSUE THREAD

**Issue by antoine-de** [etalab/transport-site#1018]
Il faudrait afficher les metadata d'une ressource (techniquement contenu dans `resource.metadata` sur le site.

On n'a pas pour le moment de page de ressource en tant que tel, plus une page de validation (exemple pour [ce dataset](https://transport.data.gouv.fr/datasets/reseau-de-transport-du-grand-dole/), en cliquant sur "Voir le rapport de validation", on arrive sur [la page de la ressource / validation](https://transport.data.gouv.fr/resources/8567)). Techniquement [voici le template utilisé](https://github.com/etalab/transport-site/blob/master/apps/transport/lib/transport_web/templates/resource/details.html.eex#).

Je pense qu'au début on peut faire le service minimum en terme de présentation et mettre juste un bloc au dessus avec une présentation de la ressource et ces metadata.
Ca serait aussi bien soit de changer l'intitulé du lien "Voir le rapport de validation", soit mettre un 2eme lien plus explicite pour tomber sur la page de la ressource.

Note: Il faut faire un peu attention, cette page de validation est aussi utilisée quand on fait une [validation manuelle](https://transport.data.gouv.fr/validation) il me semble (mais je ne suis pas certain).

**Comment by fchabouis** [comment]
Hello @antoine-de 
J'ai commencé à travailler sur cette issue. Avant que je n'aille trop loin, est-ce que tu peux me confirmer que c'est bien quelque chose du genre que tu avais en tête ? La pour le moment il y a des valeurs en dur et je n'ai pas encore récupéré les vraies métadata, mais ça permet de se faire une idée.

![image](https://user-images.githubusercontent.com/15341118/73939412-af121880-48e9-11ea-949a-dc79344c5563.png)

**Comment by antoine-de** [comment]
:heart: :+1: 

(pour la partie validation faut bien penser à voir ce que ca donne si on a tous les types d'erreur (Fatal Error Warning Information Irrelevant)

**Comment by fchabouis** [comment]
ok cool, je continue alors :)
Je ferai un test avec toutes les erreurs :+1:
