### ISSUE TITLE
Doublon des données des collectivités (données non à jour) faisant partie d'un agrégat (données à jour) : fausse les statistiques 

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#1023]
https://transport.data.gouv.fr/aoms

[Départements_Région agrégat_MAJ différentes.xlsx](https://github.com/etalab/transport-site/files/4128357/Departements_Region.agregat_MAJ.differentes.xlsx)

Les départements qui font partie d'un agrégat (les données fournies par la région) ont un statut de données non mises à jour alors que l'agrégat a les données à jour (cf. tableau ci dessus). Ce qui fausse les statistiques de ce lien : https://transport.data.gouv.fr/aoms

Possibilité de supprimer les département sur la liste pour ne garder que l'agrégat ?

**Comment by Tristramg** [comment]
C’est traité dans https://github.com/etalab/transport-site/pull/1086

On est d’accord qu’on ne parle pas de départements, qu’il s’agit d’un lapsus ?

Le correctif est le suivant :
* Si l’AOM n’a pas publié en propre, on regarde maintenant la validité du jeu de donné agrégé
* Si l’AOM publie en propre, on regarde que ses resources et pas le l’agrégé. Il sera toujours marqué comme pas à jour, car il y a une action à faire
  * Cas 1 : l’AOM n’a pas fait son travail de mise à jour et il faut le lui rappeler
  * Cas 2 : l’AOM ne souhaite plus publier en propre. Dans ce cas il faut supprimer la fiche (dans le backoffice) et inviter l’AOM à supprimer le jeu de données de data.gouv.fr

**Comment by Tristramg** [comment]
N’hésite pas rouvrir si jamais on s’était mal compris.
