### ISSUE TITLE
Référencer les données de passage à niveaux (SNCF)

### ISSUE THREAD

**Issue by be-mercier** [etalab/transport-site#1024]
La SNCF nous demande de référencer les données de passage à niveau sur transport.data.gouv.fr : https://ressources.data.sncf.com/explore/dataset/liste-des-passages-a-niveau/table/ 

Où peut-on les référencer ? Je peux les cataloguer comme données routières ?

**Comment by antoine-de** [comment]
oui données routières ca me semble pas si mal
