### ISSUE TITLE
Gérer les ftp

### ISSUE THREAD

**Issue by antoine-de** [etalab/transport-site#1033]
Les ressources des pays de la loire (ex [les Sables d'Olonnes](https://transport.data.gouv.fr/datasets/lignes-arrets-et-horaires-theorique-du-reseau-de-transport-gtfs-les-sables-dolonne-agglomeration/) ne remontent pas car elles sont marquée en non disponible ([ca se passe ici](https://github.com/etalab/transport-site/blob/5e5e9821314524456abf4cae149bf4af051e/apps/db/lib/db/dataset.ex#L85:L85) et [ici](https://github.com/etalab/transport-site/blob/5e5e9821314524456abf4cae149bf4af051e9ebc/apps/transport/lib/transport/import_data.ex#L214:L214))

Elles sont marquées en non disponibles car elles sont hebergées sur du ftp et qu'on ne le gère pas :stuck_out_tongue_winking_eye: 

Il faut qu'on gère le ftp, et à pleins d'endroit :cry: 

il faut au moins qu'on le gère [à l'import](https://github.com/etalab/transport-site/blob/5e5e9821314524456abf4cae149bf4af051e9ebc/apps/transport/lib/transport/import_data.ex#L214:L214), sûrement au [backup](https://github.com/etalab/transport-site/blob/5e5e9821314524456abf4cae149bf4af051e/apps/transport/lib/transport/history.ex#L115:L115), et aussi dans le validateur (`reqwest` ne le gère pas), et peut être ailleurs :cry:

**Comment by Tristramg** [comment]
si on faisait un pré-service qui prend le ftp pour le mettre sur le cellar,
puis on repart comme si rien n’était ?

**Comment by antoine-de** [comment]
wai c'est pas con, on pourrait faire ce proxy cheap en cas de ftp.
je creuse un peu la question

**Comment by antoine-de** [comment]
hum le soucis c'est que l'historique est fait de manière asynchrone faut peut etre revoir un peu la mécanique

**Comment by Tristramg** [comment]
https://www.ghacks.net/2020/03/19/mozilla-will-remove-ftp-support-in-the-firefox-web-browser/

Peut-être qu’il faudrait être plus durs et dire que le ftp n’est juste pas accepté

**Comment by thbar** [comment]
Si on doit l'implémenter j'aime bien l'approche que décrit @Tristramg, et je l'ai fait plusieurs fois ; un FTP ou SFTP intermédiaire, qui fait du write-only vers un bucket S3. Ce pattern peut être généralisé, ex: envoi par email qui atterrissent dans un bucket, pour avoir un "tuyau standardisé".

**Comment by thbar** [comment]
J'ai fait une petite spike pour vérifier comment télécharger en FTP, ça se fait bien car dans Erlang la stdlib inclut directement le support FTP. Par contre il y a un piège au niveau du fait que les strings Elixir doivent être converties en strings Erlang.

Voici le snippet (en mettant dans url le lien FTP des [Sables d'Olonnes](https://transport.data.gouv.fr/datasets/lignes-arrets-et-horaires-theorique-du-reseau-de-transport-gtfs-les-sables-dolonne-agglomeration/)):

```elixir
defmodule FTPTest do
  use ExUnit.Case

  test "FTP download" do
    # http://erlang.org/doc/apps/ftp/ftp_client.html

    (a = %{
       host: host,
       scheme: "ftp",
       port: port,
       userinfo: userinfo,
       path: path
     }) = URI.parse(url)

    :ftp.start()
    {:ok, pid} = :ftp.start_service(host: host |> String.to_char_list())

    if userinfo do
      [user, pass] = userinfo |> String.split(":")
      :ftp.user(pid, user |> String.to_char_list(), pass |> String.to_char_list())
    end

    target_filename = Path.basename(path)
    IO.puts("Downloading #{target_filename}...")
    :ok = :ftp.recv(pid, path |> String.to_char_list(), "../../" <> target_filename)

    :ftp.stop_service(pid)
    :ftp.stop()
  end
end
```

**Comment by thbar** [comment]
@NicolasBerthelot @Miryad3108 est-ce qu'il serait possible de demander au producteur de fournir un autre moyen (HTTPS), pour pouvoir fermer ce point ? Sinon on peut également voir avec Data Gouv (je sais qu'ils ont mis en place quelque chose de similaire pour du SFTP, mais il faut chercher à éviter idéalement).

**Comment by thbar** [comment]
@NicolasBerthelot est-ce qu'on peut fermer ce besoin à ton avis, par rapport aux retours éventuels que tu aurais pu avoir ?
