### ISSUE TITLE
Erreur 500 des derniers référencements jdd Zenbus sur transport.data.gouv.fr 

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#1038]
Erreur 500 pour les réseaux suivants sur transport.data.gouv.fr

 - Fontenay-le-Comte - Fontélys 
Data.gouv:  https://www.data.gouv.fr/fr/datasets/horaires-theoriques-et-temps-reel-du-reseau-fontelys-fontenay-le-comte-gtfs-gtfs-rt/  
Transport : https://transport.data.gouv.fr/datasets/horaires-theoriques-et-temps-reel-du-reseau-fontelys-fontenay-le-comte-gtfs-gtfs-rt/

 - Honfleur - Hobus 
Data.gouv :  https://www.data.gouv.fr/fr/datasets/horaires-theoriques-et-temps-reel-du-reseau-hobus-de-honfleur-gtfs-gtfs-rt/
Transport : https://transport.data.gouv.fr/datasets/horaires-theoriques-et-temps-reel-du-reseau-hobus-de-honfleur-gtfs-gtfs-rt/

 - Saint-Avold - Transavold : 
Data.gouv: https://www.data.gouv.fr/fr/datasets/horaires-theoriques-et-temps-reel-du-reseau-transavold-saint-avold-gtfs-gtfs-rt/
Transport : https://transport.data.gouv.fr/datasets/horaires-theoriques-et-temps-reel-du-reseau-transavold-saint-avold-gtfs-gtfs-rt/

 - Sel et Vermois - La Navette: 
Data.gouv : https://www.data.gouv.fr/fr/datasets/horaires-theoriques-et-temps-reel-de-la-navette-de-sel-et-vermois-gtfs-gtfs-rt/
Transport : https://transport.data.gouv.fr/datasets/horaires-theoriques-et-temps-reel-de-la-navette-de-sel-et-vermois-gtfs-gtfs-rt/

 - Valmorel - Navettes station : 
Data.gouv : https://www.data.gouv.fr/fr/datasets/horaires-theoriques-et-temps-reel-de-la-station-de-ski-valmorel-gtfs-gtfs-rt/
Transport : https://transport.data.gouv.fr/datasets/horaires-theoriques-et-temps-reel-de-la-station-de-ski-valmorel-gtfs-gtfs-rt/

**Comment by antoine-de** [comment]
c'est le champ "nom du territoire" qui n'était pas rempli et qui visiblement n'était pas checké à la création :roll_eyes: 

J'ai corrigé en base les noms, et je vais mettre un check dans le formulaire du backoffice pour obliger le remplissage de ce champs quand on choisit les zones data.gouv

**Comment by antoine-de** [comment]
les tests ont été ajoutés à #1039 , je ferme, merci pour la remontée d'anomalie !
