### ISSUE TITLE
Faire une carte des données de aire de covoiturage

### ISSUE THREAD

**Issue by antoine-de** [etalab/transport-site#1047]
C'est un besoin récurent d'avoir une carte à montrer sur les données de covoiturage, je me dis que ca veut dire que ca manque sur le site.

Je sais pas trop ou mettre ca par contre.

On peut soit (c'est pas exclusif):
1/ mettre ca sur la page `/stats` 
2/ la mettre sur la page `ressource` des jdd covoit
3/ la mettre sur la page de recherche [covoit](https://transport.data.gouv.fr/datasets?type=carsharing-areas)

### page /stats
Comment on fait techniquement pour afficher ca ?
On lit la ressource la plus récente de [notre base](https://transport.data.gouv.fr/datasets/base-nationale-consolidee-des-lieux-de-covoiturage/) pour l'afficher à la volée ? il y a ~2000 points ca va pas trop charger la page /stats ? ou on index tout cas en base ? autre ?

### page ressource
avec #1037 on a maintenant une page plus sympa de ressource qu'on peut peut etre étendre aux ressource autre TC non ? 

Ca nous permettrait de faire des visualisations custom, on pourrait commencer par la [base consolidées des aires de covoit](https://transport.data.gouv.fr/datasets/base-nationale-consolidee-des-lieux-de-covoiturage/).

c'est pas super visible, mais du coup on risque moins d'avoir une page lourde à charger (et c'est moins grave).
et j'ai l'impression que dans ce cas la ca a du sens de faire une visualisation 'à la volée' du fichier.

### page [recherche covoit](https://transport.data.gouv.fr/datasets?type=carsharing-areas)
Ca fait un moment qu'on se dit que ca pourrait etre cool d'éditoriaser certaines pages de recherche (au moins celles des tuiles je pense).

Ca nous permettrait de donner les spécificités des différents jeux de données qu'on trouve avec  la recherche et d'afficher une petite carte ? il reste les même questions technique pour pour les autres solution (avec peut etre en plus une contrainte sur le temps de chargement de la page)

## Conclusion
Vous en pensez quoi ? j'ai l'impression qu'on peut commencer avec la solution 2, c'est celle qui a le moins d'impact, et on pourra potentiellement la combiner avec les autres si on est content du résultat.

**Comment by fchabouis** [comment]
Je vais faire un petit test de la solution 2, voir ce que ça donne de charger le csv et de l'afficher dans une carte niveau réactivité. Avec ma connexion pourrie Corse, si c'est bon chez moi ça devrait le faire ailleurs :P

**Comment by be-mercier** [comment]
Hello, je pense que l'option 3 est la plus séduisante pour un réutilisateur. 
Ca lui permet de voir d'un premier coup d'oeil ce que contient la base nationale. 
La page /stats a la base devait servir aux gens de la DGITM pour monitorer nos avancées, beaucoup de réutilisateurs s'en servent maintenant pour voir l'étendue des données dispo sur la plateforme, mais la page est difficilement découvrable pour qqn qui visite le site pour la première fois. 
Je pense que ce serait cool d'intégrer une carte dans le parcours type du réutilisateur (tu arrives sur la landing page, tu cliques sur la tuile co-voit, t'as une carte des aires de co-voit dispo...)
