### ISSUE TITLE
Erreur technique dans le Validateur lieux de stationnements 

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#1050]
Quand on charge un fichier (xls) sur :
https://validata.etalab.studio/table-schema?schema_name=schema-datagouv-fr.etalab%2Fschema-stationnement&schema_ref=

ça affiche "erreur technique" 
![image](https://user-images.githubusercontent.com/59559301/74352280-8cd03d00-4db8-11ea-8c15-38529599877c.png)

**(Le validateur fonctionnait lundi)**

**Comment by antoine-de** [comment]
c'est plus une question datagouv (qui à répondu directement), je ferme
