### ISSUE TITLE
Améliorer le titre des jeux de données nationaux

### ISSUE THREAD

**Issue by antoine-de** [etalab/transport-site#1059]
Les titres (`long_title`) des jeux de données sont construit sur le modèle `Territoire` - `Type`.

Ca fonctionne bien pour les jdd des AO, mais assez mal pour le reste de nos données.

Par exemple sur le routier on a :

![image](https://user-images.githubusercontent.com/3987698/74816395-fab5c080-52f2-11ea-919a-71d8373bc3ea.png)

Il faut qu'on réfléchisse au meilleur titre pour ces jdd (juste utiliser le champ `spatial` ou juste le `titre` ?

**Comment by fchabouis** [comment]
J'ai peut-être été un peu vite en besogne, mais j'ai mis juste "spatial".
Le gros avantage, c'est que si on est pas content avec un titre spatial, on peut le changer puisque c'est nous qui avons la main dessus !
Faudra peut-être réfléchir à une sorte de nomenclature de titres pour que ce soit bien homogène.

**Comment by fchabouis** [comment]
Du coup je ferme l'issue
