### ISSUE TITLE
Error 500 pour accéder aux JDD du réseau Citéline, Thionville-Fensch, Grand Est. sur transport.data.gouv.fr

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#1073]
Une nouvelle SIM a été rajouté sur data.gouv du réseau Citéline de Thionville-Fensch (associé à la région Grand Est): 

https://www.data.gouv.fr/fr/datasets/horaires-theoriques-du-reseau-citeline-syndicat-mixte-des-transports-urbains-thionville-fensch-gtfs/#resource-407845b5-dd60-4540-9292-5a2ba50d6d65

J'ai voulu faire remonter les données de data.gouv vers transport. Le JDD a été importé mais la validation ne se fait pas.

**URL utilisé dans le backoffice** : 
https://www.data.gouv.fr/fr/datasets/horaires-theoriques-du-reseau-citeline-syndicat-mixte-des-transports-urbains-thionville-fensch-gtfs/#resource-407845b5-dd60-4540-9292-5a2ba50d6d65

**Nom du réseau** : Citelis 

**JDD associé à** la région Grand-Est

**JDD disponibles** : Syndicat Mixte des Transports Urbains Thionville-Fensch

Le JDD Citéline apparaît pourtant sur transport mais on ne peut pas ouvrir la page (Error 500) : 

https://transport.data.gouv.fr/datasets/horaires-theoriques-du-reseau-citeline-syndicat-mixte-des-transports-urbains-thionville-fensch-gtfs/

![image](https://user-images.githubusercontent.com/59559301/75162188-6944b500-571d-11ea-89e4-2dcc98c2e4d2.png)

**Comment by antoine-de** [comment]
la 500 n'est pas normale, il faut que je corrige ca, mais le soucis arrive car le jdd est deja référencé (sous un autre nom):
https://transport.data.gouv.fr/backoffice?_utf8=%E2%9C%93&q=thionville
