### ISSUE TITLE
Améliorer la présentation des pags aom, commune, région

### ISSUE THREAD

**Issue by Tristramg** [etalab/transport-site#1088]
Il faudrait qu’on comprenne qu’il s’agit d’une page de territoire (le début des PAT ;) )

- [x] la barre de recherche devrait être réduite (ne pas être le point d’attention principal)
- [x] meilleur titre
- [ ] optionnel : illustres ça joliment selon la catégorie de territoire ;)

**Comment by antoine-de** [comment]
une petite carte pour montrer où est l'AO 😍

**Comment by antoine-de** [comment]
les 2 premiers points sont maintenant ok.

On veut afficher un picto / une carte ou on peut fermer ca ?

**Comment by antoine-de** [comment]
bon je pense qu’on peut fermer cette issue non? @NicolasBerthelot @Miryad3108 vous pensez que ca a de la valeur d’améliorer l’affichage de la page territoire ? (genre https://transport.data.gouv.fr/datasets/aom/194)

**Comment by Miryad3108** [comment]
Je pense également qu'on peut fermer ça 
La petite carte de couverture spatiale qu'il y a dans le dataset me semble suffisante
