### ISSUE TITLE
Définir une catégorie « Autour des transport »

### ISSUE THREAD

**Issue by Tristramg** [etalab/transport-site#1090]
Ce serait un peu fourre-tout. Il faut

* [x] Trouver un meilleur titre
* [x] Une icone

Et on mettrait dedans les isues :

* #1083 
* #930 
* #1025

**Comment by be-mercier** [comment]
Comme icône, j'imaginerais bien une icône "information" de ce genre : https://images.app.goo.gl/R3fvUJWrR7vQRg5k6 

Et comme titre, "informations d'accès / de navigation " ?

**Comment by antoine-de** [comment]
le pathway tu veux pas le mettre dans la catégorie `public-transit` ?

**Comment by Tristramg** [comment]
en prod :tada:
