### ISSUE TITLE
Correction couverture du territoire AOM Valenciennes

### ISSUE THREAD

**Issue by be-mercier** [etalab/transport-site#1092]
Une micro-correction exigée par un producteur de données sur sa fiche transport.data.gouv.fr : 

l'AOM de Valenciennes (SIMOUV) voudrait qu'on ajoute la commune d'Emerchicourt à la liste des territoires couverts (nouveauté 2019).

**Comment by Tristramg** [comment]
C’est amusant, avant la commune était gérée par l’AOM de douais :)

Fixé en base de prod, à la main `update commune set aom_res_id = 99 where nom = 'Émerchicourt';`

https://transport.data.gouv.fr/datasets/commune/59192
