### ISSUE TITLE
Customiser "Autres jeux de données de (insert region)" en bas de chaque fiche de jdd

### ISSUE THREAD

**Issue by be-mercier** [etalab/transport-site#1093]
La région Centre Val de Loire voudrait savoir si la mention 

"Autres jeux de données de Centre Val de Loire" qui apparaît en bas de la fiche pour leur jdd interubain (https://transport.data.gouv.fr/datasets/remi-offre-theorique-mobilite-reseau-interurbain-regional/) est customisable. Aujourd'hui, on trouve un hyperlien vers le jdd aggrégé de la région : 

<img width="726" alt="Capture d’écran 2020-03-10 à 16 33 35" src="https://user-images.githubusercontent.com/47319124/76329673-2a9e2580-62ed-11ea-9147-fadbe270a4f6.png">

La région voudrait savoir si on peut lister d'autres jeux de données, particulièrement les données des réseaux urbains opérant dans la région, à cet endroit ?

**Comment by antoine-de** [comment]
hum c'est pas bete, mais le plus simple serait pas simplement de rediriger vers la page de la région ? (pour centre val de loire ca donnerait https://transport.data.gouv.fr/datasets/region/3 )

comme ca on surcharge pas la page et on est sur d'avoir tous les jdd  (et ca fonctionne pour les région, les AO et les villes)

**Comment by NicolasBerthelot** [comment]
Super compliqué
