### ISSUE TITLE
Améliorer la page transport.data.gouv.fr/aoms ?

### ISSUE THREAD

**Issue by be-mercier** [etalab/transport-site#1101]
Lors d'un entretien utilisateur avec Transit, ils nous ont remonté la demande suivante (dans la catégorie, liste au Père Noël/souhait le plus fou): 

- une liste de tous les réseaux qui ont publié sur data.gouv.fr avec des liens vers les données statiques, lien vers les données TR si elles sont en licence ouverte.
et  un lien vers le site pour les développeurs sur le domaine de l’agence (ou à défaut un lien vers le site de l’agence).

Serait-ce pertinent d'ajouter ces champs à : transport.data.gouv.fr/aoms ? 

Le risque que j'y vois, serait de sur-charger cette page.

**Comment by Tristramg** [comment]
Une grosse partie est dans https://transport.data.gouv.fr/api/datasets

Ce qui manque c’est le lien vers le temps réel et le lien vers l’agence.

**Comment by antoine-de** [comment]
le lien vers l'agence ca va être relou à remplir non ?

**Comment by be-mercier** [comment]
Retour DGITM : le tableau des AOM leur indique quels AOM urbaines ont ouvert leurs données, et quelles ne l'ont pas fait. 
Ils aimeraient également pouvoir accéder à une liste MAJ en continu des régions qui ont ouvert leurs données, ou non. (Claudine ne comprend pas notre carte).

**Comment by antoine-de** [comment]
la dessus du coup on fait quelque chose ou on se dit qu'il faut plutot améliorer notre carte ?

**Comment by antoine-de** [comment]
Ca serait intéressant de demander à Claudine (ou à Benoit) si maintenant la carte des régions est plus compréhensible, car la j'ai l'impression qu'on peut fermer cette issue

**Comment by NicolasBerthelot** [comment]
A revisiter, fermeture temporaire
