### ISSUE TITLE
Faire une recette du convertisseur gtfs2netex

### ISSUE THREAD

**Issue by antoine-de** [etalab/transport-site#1104]
kisio a mis à dispo un convertisseur [gtfs2netex](https://github.com/CanalTP/tartare-tools/blob/master/src/bin/gtfs2netexfr.rs).

Il faut qu'on le recette.

Cette issue va servir à tracer les actions.

Note: les benchmarks sont simplement indicatifs et ont été effectués sur mon PC (`Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz`)

## général
l'outil est un outil en cli, et l'ergonomie est bien.

Il serait peut etre plus simple que l'outil puisse accepter une url en paramétre à la place d'un répertoire, et puisse générer un zip mais ce sont des développements que nous pourrons proposer vu que l'outil est open source.

### conversion d'un petit jdd
La conversion du jeu de données de [toutenbus](https://transport.data.gouv.fr/datasets/topologie-horaires-theoriques-formats-gtfs/) (petit jeu, 37 stops).
génération du netex en moins de 1s :heavy_check_mark: 

### conversion du fichier d'idfm
la conversion du plus gros fichier de la plateforme (63k stops) se passe aussi bien, la génération prend 20mn et utilise au pic 3.7G de ram :heavy_check_mark: 

Le gtfs initial fait 750M et les fichiers netex générés (~2000) pèsent 3G (cela semble cohérent avec le fait que le format est très verbeux).

## qualité du fichier généré
Pour le fichier de toutenbus le netex généré est valide d’après le [validateur de chouette](https://github.com/enroute-mobi/netex-cli-validator). :heavy_check_mark: 

Pour le fichier d'idf, le temps de validation est rédhibitoire. l'outil utilisé a validé le premier fichier (`arrets.xml`) 

l'outil de validation a trouvé une erreur que j'ai [remonté à kisio](https://github.com/CanalTP/tartare-tools/issues/59).

## TODO
On va lancer  la génération des netex pour tous les GTFS histoire de voir si on a des plantages.
niveau qualité du fichier généré je vois pas trop ce que je peux checker de plus, je pense donc m’arrêter la.

**Comment by Tristramg** [comment]
On a fait tourner le validateur sur l’ensemble de nos données (environ 380 ressources).

Le temps total de conversion a été de 6800 secondes (uniquement conversion, sans temps de téléchargement)

Lorsque la conversion a échoué, c’est qu’il y a une erreur légitime dans nos GTFS, quasiment toujours remontés par le validateur.

On créé les issues dans https://github.com/etalab/transport-validator-rust pour quelques erreur qui devraient être remontées plus tôt.

Selon moi on peut dire GO à kisio et l’intégrer complètement dans notre plateforme.

**Comment by antoine-de** [comment]
ok top, je ferme du coup
