### ISSUE TITLE
Editorialiser les pages de catégories

### ISSUE THREAD

**Issue by antoine-de** [etalab/transport-site#1115]
Depuis #1075 on peut éditorialiser les pages de catégories.

Il faut qu'on rédige ce qu'on veut marquer pour toutes les catégories.

On peut répondre à l'issue et synthétiser ici.

On peut aussi complétement parler du design existant :
![image](https://user-images.githubusercontent.com/3987698/78050307-9400d980-736b-11ea-9f22-b4a56850a6e1.png)
![image](https://user-images.githubusercontent.com/3987698/78050542-e510cd80-736b-11ea-862e-b7ccadcf05cd.png)

Si vous avez des idées pour l'améliorer

J'initialise la synthèse avec l'existant

### Temps réel transports en commun

"Plus d'informations et d'autres jeux de données temps réel ici"

### Adresses

Les données d’adresses françaises sont disponibles dans le jeu de données de la BAN, produit par l’Institut géographique national (IGN), La Poste, Etalab et diverses administrations

### Autres informations

**Comment by antoine-de** [comment]
Ca pourrait aussi etre super cool de mettre certaines carte de la page stats dans ce bloc

**Comment by antoine-de** [comment]
travail commencé à #1211

**Comment by NicolasBerthelot** [comment]
On peut aller plus loin dans la mise en page adapté à chaque thème, pourquoi pas y réfléchir particulièrement sur les données vélo !

**Comment by AntoineAugusti** [comment]
@NicolasBerthelot Tu as commencé à noter des descriptions quelque part ?

**Comment by NicolasBerthelot** [comment]
Yes, le document est ici : https://docs.google.com/document/d/1vwnme8QH_wdNtGz3rvZ0o91Nb3ve6UALIBCxf8H1GP0/edit#heading=h.picnrad7w4uw
C'est pas du tout fini ^^
