### ISSUE TITLE
Ajouter plus de contexte pour les tuiles

### ISSUE THREAD

**Issue by antoine-de** [etalab/transport-site#1116]
Il serait peut etre pas mal de rajouter un sous titre sur les tuiles pour mieux expliquer la catégorie.

Ca permettrait notamment d'expliquer un peu ce que contiennent les données TC (pas que des horaires).

Faut par contre que ca reste concis (et si c'est trop long on peut le mettre dans la page de la catégorie elle même cf #1115 )

Si ca vous convient on peut lister ici les propositions pour les catégories.

### Autres informations

**Comment by NicolasBerthelot** [comment]
ça va être chargé désolé
