### ISSUE TITLE
Traduire 100% du site en anglais

### ISSUE THREAD

**Issue by antoine-de** [etalab/transport-site#1117]
Il faudrait que le site soit 100% traduit en francais et en anglais.

Il faut tracker l'usage de texte sans `dgettext`. il y en a au moins sur la page `/stats`

**Comment by Tristramg** [comment]
cf #663

**Comment by antoine-de** [comment]
les 2 issues sont liées, mais j'ai l'impression que ca vaut le coup d'en avoir 2 différentes vu que ce ne sont pas les mêmes actions à mener

**Comment by NicolasBerthelot** [comment]
En attente du bouton, l'issue sera réouverte lorsque le bouton langue sera mis en place
