### ISSUE TITLE
Clarifier la relation "a propos" / doc

### ISSUE THREAD

**Issue by antoine-de** [etalab/transport-site#1118]
Il ne semble pas optimal que le lien "A propos" du header pointe vers la doc.

une proposition de l'atelir UI était il me semble d'avoir 2 liens : 
* "A propos" qui pointe vers une section de la home où on explique ce qu'on fait (la partie "1 plate-forme, 1 licence, 1 format, 1 interlocuteur identifié" ? ca manque peut etre d'un peu de contexte non ?)
* "Doc" qui pointe vers la doc

**Comment by fchabouis** [comment]
on va s'en occuper avec #1257

**Comment by fchabouis** [comment]
C'est fait avec la refonte de la home.
