### ISSUE TITLE
JDD mis à jour mais apparaissent comme périmés sur transport.data.gouv.fr

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#1123]
JDD qui apparaissent comme étant périmés sur https://transport.data.gouv.fr/ 
Une fois que relance de MAJ faite : opérateur renvoie un lien vers leur JDD mis à jour sur transportdatagouv depuis quelques jours

**Comment by fchabouis** [comment]
Devrait être résolu par #1127.

**Comment by antoine-de** [comment]
Ca a l'air d'être bon
