### ISSUE TITLE
Afficher les méta données demandées par le réglement européen

### ISSUE THREAD

**Issue by antoine-de** [etalab/transport-site#1124]
La liste des meta données n'est pas super clair, mais on sait qu'on doit afficher des méta données :stuck_out_tongue_winking_eye: 

Pour le moment on en affiche déjà sur la page de ressource (comme [la](https://transport.data.gouv.fr/resources/8361)).

Si on veut compléter, on pourrait peut etre repartir de la liste de meta donnée du PAN belge ([ici](https://www.transportdata.be/dataset/tec-gtfs) par exemple) ?
On a pratiquement tout je pense (avec peut etre des info à récupérer de data.gouv).

Si on fait ca, ca pourrait être pratique d'aussi les caler dans l'api.

**Comment by antoine-de** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Gestion des metadonnées](https://trello.com/c/QCJXPYcw/356-gestion-des-metadonn%C3%A9es)

**Comment by antoine-de** [comment]
| metadata                         | Déja la ? | commentaire                                        |
| -------------------------------- | --------------- | ---------------------------------------------- |
| ID                               | ✓               |                                                |
| Metadata date                    | ✘               | On peut juste mettre la date de validation ?         |
| Metadata language                | ✘               |                                                |
| Resource type                    | ?               | Je ne sais pas ce que c'est                     |
| -------------------------------- | --------------- | ---------------------------------------------- |
| Name [contact point]             | ✘               | On n'affiche pas d'info `publisher`,           |
| Organisation name [publisher]    | ✘               | Mais sur la plateforme il est possible          |
| Name [publisher]                 | ✘               | de contacter le producteur de données          |
| Address [publisher]              | ✘               | via les conversations                          |
| E-mail [publisher]               | ✘               |                                                |
| Website [publisher]              | ✘               |                                                |
| Telephone number [publisher]     | ✘               |                                                |
| -------------------------------- | --------------- | ---------------------------------------------- |
| Start date of publication        | ✓               |                                                |
| End date of publication          | ✓               |                                                |
| Countries covered by publication | ✘               | On peut toujours mettre la France non ?        |
| Area covered by publication      | ✓               |                                                |
| Dataset extent                   | ?               |                                                |
| Contract or licence              | ✓               |                                                |
| Update frequency                 | ✘               | À recupérer de datagouv                        |
| Quality assessment               | ✓               |                                                |
| Dataset theme                    | ✘               |                                                |

Donc en fait il ne nous manque à mon sens que peu d'info, simple à récupérer :
* Update frequency
* Metadata date
* Countries covered by publication

Il reste à se mettre d'accord comment on veut afficher ces metadata ?
- juste sur la page ressource ?
- dans l'api ?

Aprés pour le moment on n'affiche ca que pour les GTFS, il faut voir si on veut aussi afficher des trucs pour les autres types de ressources ?

**Comment by fchabouis** [comment]
On peut les mettre sur la page du dataset aussi, c'est plus facile à trouver.

Je suis pas contre les rajouter dans l'API, j'ai du mal à savoir si c'est utile ou non...mais ça garde la page et l'API alignées.

**Comment by NicolasBerthelot** [comment]
Yes effectivement ce serait cool qu'elles soient aussi dans l'API. D'ailleurs au sujet de l'API ça pourrait être cool pour les frileux des API de leur proposer un bouton qui permet de télécharger un CSV complet de nos métadonnées, ce sera utile pour les personnes qui veulent se promener dans notre catalogue sans passer par l'interface de la plateforme.

**Comment by antoine-de** [comment]
hum pourquoi pas, mais du coup faut trouver un format pour tout caler, et c'est vite relou le CSV quand tu veux des infos imbriquées

**Comment by NicolasBerthelot** [comment]
En attente d'un échange avec l'organisation qui s'occupera de rassembler les métadonnées des NAP européens
