### ISSUE TITLE
Ajout de l'info transport "interurbain" en base

### ISSUE THREAD

**Issue by fchabouis** [etalab/transport-site#1130]
Afin de pouvoir rajouter cet aspect dans la page de stats.
@be-mercier aimerait tout particulièrement y voir cette info ;)

**Comment by NicolasBerthelot** [comment]
La distinction interurbain et urbain n'est pas forcément claire. Les réseaux interurbains sont déjà attachés à des AOMs régionales.  Le problème aujourd'hui est surtout la confusion qu'il peut y avoir entre région et départements
