### ISSUE TITLE
Rebrancher le temps réel des VCub bordelais.

### ISSUE THREAD

**Issue by fchabouis** [etalab/transport-site#1143]
![image](https://user-images.githubusercontent.com/15341118/81060493-da010e00-8ed2-11ea-91c6-11dabbcdb35b.png)

**Comment by antoine-de** [comment]
roh relou les logs sans aucun contexte :(

**Comment by fchabouis** [comment]
J'ai regardé cette histoire de 500, elle vient des VCUB bordelais.

La ville de Bordeaux a lancé le 20 janvier 2020 une nouvelle plateforme open data, et les urls pour récupérer les données ont changé. Et j'ai l'impression que les formats de fichiers mis à disposition aussi.

La nouvelle adresse du JDD : https://opendata.bordeaux-metropole.fr/explore/dataset/ci_vcub_p/information/

L'info a l'air d'être disponible librement pour une mise à jour toutes les minutes. Et si on veut l'avoir toutes les 30 secondes, il y a un webservice WFS dispo pour lequel il faut demander une clé.

Pour le VCUB, on avait pas de fallback en cas d'erreur de récupération de la donnée, d'où l'erreur 500.

A discuter :
- on renvoie quoi en cas de problème sur le service ? Une 200 avec un JSON qui contient un message d'erreur, une 503 ? On a décidé quoi pour les autres ?
- ça vaut le coup de brancher sentry la-dessus non ? Là on a mis  5 mois à s'en rendre compte :grimacing: 
- on veut quelle fréquence de rafraîchissement ?
- puis faut refaire le branchement avec leur nouvelle API.

**Comment by antoine-de** [comment]
on renvoie quoi en cas de problème sur le service ? Une 200 avec un JSON qui contient un message d'erreur, une 503 ? On a décidé quoi pour les autres ?
hum une 503 pourquoi pas. On peut aussi voir si ca vaut le coup de faire un chtit peu de cache

    ça vaut le coup de brancher sentry la-dessus non ? Là on a mis 5 mois à s'en rendre compte :grimacing:
grave !

    on veut quelle fréquence de rafraîchissement ?
On peut demander un token pour pouvoir taper plus souvent sur leur API. Pour le moment de mémoire il n'y a pas de cache, on fait 1 appel pour 1 appel chez nous non ? Faut peut etre changer ca.

    puis faut refaire le branchement avec leur nouvelle API.
yep, j'ai l'impression que c'est pas super difficile.

**Comment by antoine-de** [comment]
en meme temps aprés reflexion est ce qu'on veut faire de la conversion sur un api fermée ?
C'est peut etre notre role de dire non dans ce genre de cas non ?

**Comment by fchabouis** [comment]
Je ne sais pas ou j'avais vu cette histoire de fréquence de rafraîchissement, mais si j'en crois ce que j'ai écrit précédemment, on peut utiliser l'api ouverte et rafraîchir toutes les minutes.
