### ISSUE TITLE
Associer un jdd régional à plusieurs AO dans le backoffice

### ISSUE THREAD

**Issue by antoine-de** [etalab/transport-site#1148]
pour le moment le champ `paraent_dataset_id` d'une `AOM` est rempli à la main en sql quand les données de l'aom sont dispo dans un jdd agrégée.

Dans une optique d'ouverture du backoffice à des tiers (et pour simplifier le process) ca serait cool de le mettre dans le backoffice.

Peut être directement dans la page quand on référence un jdd, une section (avec de l'autocomplétion) quand on sélectionne "Jeu de données régional",  "Ajouter une AOM couverte par ce jdd" ?

**Comment by NicolasBerthelot** [comment]
Ah c'est ça l'issue pour gérer le cas du STMCO dans l'Oise ? https://www.data.gouv.fr/fr/datasets/arrets-horaires-et-parcours-theoriques-gtfs-des-differents-reseaux-de-transport-membres-du-synd1/#_

**Comment by antoine-de** [comment]
yep, pour le moment c'est fait à la mano en base.

tiens je vais le faire d'ailleurs pour le STMCO de l'oise

**Comment by NicolasBerthelot** [comment]
Besoin moins important car la situation est relativement rare
