### ISSUE TITLE
Intégrer les ressources communautaires dans la base

### ISSUE THREAD

**Issue by antoine-de** [etalab/transport-site#1151]
Pour le moment les ressources communautaires (RC) sont uniquement récupérées quand on affiche la page d'un jeu de données. Ca permettait de les intégrer facilement avant, mais maintenant qu'il y a pas mal de ressources communautaires intéressantes (notamment les NeTEx générés, les SIRI converti, des GBFS (ca je suis pas certain), potentiellement des GTFS modifés, ...), j'ai l'impression qu'il faut qu'on les intègre mieux au site.
 
les limites de la solution actuelle :
* on ne considère pas les RC dans les formats dispo du jdd:
![image](https://user-images.githubusercontent.com/3987698/81675324-2c47af00-943e-11ea-98ae-57b0e30d1fb8.png)
=> la en vrai on a aussi du NeTEx ,du SIRI-lite et du GTFS-RT (qu'il faut qu'on référence... :flushed: )

* on ne considère pas les RC dans les stats
* on ne valide pas les RC
* on ne les affiche po dans l'api

### Proposition
J'ai l'impression qu'on pourrait simplement les récupérer à l'import quotidien, les caler dans la table `Resource` avec un flag pour pouvoir les afficher dans un bloc séparé (du coup il faut aussi récupérer le champ description qu'on a pas dans les ressources classiques).

Il faudra faire un peu gaff au fait de ne pas les considérer dans certaines requetes (j'ai pas trop d'idée en tête la, tu vois des trucs auxquels il faudrait faire attention @Tristramg ?)

#### Questions ?
* comment on les présente dans l'api ?
un bloc séparé, ou juste on affiche le flag ?
* on importe toutes les RC ou on filtre ? (sur quel critère du coup ?)
 j'ai l'impression qu'il faut qu'on prenne le même critère que [l'import de données](https://github.com/etalab/transport-site/blob/master/apps/transport/lib/transport/import_data.ex#L283:L283) auquel il faudrait du coup rajouter le siri-lite

closes #853 et #852

**Comment by antoine-de** [comment]
ah en regardant l'exemple du réseau TAG, me rend compte que si on filtre les RC comme les autres, on va perdre les fiches PDF d'horaire. c'est peut etre un peu dommage. un avis la dessus ?

**Comment by Tristramg** [comment]
Hrm, je ne sais pas si je suis complètemnet convaincu.

Il y a différents cas :
* Dans https://www.data.gouv.fr/fr/datasets/horaires-theoriques-du-reseau-tag/ faudrait surtout demander à grenoble de les mettre en resource principales. Les resources communautaires, c’est dans mon esprit fait par des tiers
* Les données qu’on produit nous (siri-lite, netex, geojson) : peut-être qu’on peut se servir de ce critère-là pour décider d’importer ?
* Est-ce qu’il y a d’autres cas de ressources communautaires pertinentes ?

Du coup je ne sais pas si le côté « validation » est vraiment nécessaire. Je vois surtout afficher des tags des formats alternatifs.

Pour l’API je garderais bien explicitement ressources communautaires, pour qu’on différencie celles qui ne sont pas produites par le producteur original.

Sur les stats, faudra faire une passe, mais de mémoire on ne compte pas les resources, si ?

**Comment by antoine-de** [comment]
pour TAG, ils pourraient mettre en RC le json et le PDF, mais je pensais surtout au siri-lite + NeTEx (+ gtfs-rt qu'il faudrait qu'on rajoute).

Effectivement on peut du coup n'importer que les RC qu'on produit nous (je vois d'interessant que des jdd reversé via la clause de repartage, mais je ne sais pas si on en a bcp de pertinants), mais j'ai l'impression que si on filtre les RC, il faut qu'on "réconcilie" les RC pour les afficher toutes quand meme quand on charge la page.

le coté validation est pas obligatoire en effet, mais ca permettrait d'afficher des dates de validité des GTFS (ca avait été demandé par un réutilisateur de l'api à un moment, mais je ne me souviens plus pour quel JDD), et des NeTEx quand on sera en mesure de les calculer (bon c'est pas essentiel, vu que ca devrait etre la meme validité que le GTFS c'est vrai)

pour les stats, on prend en compte les ressources pour les stats sur les formats, et sur la qualité des données

**Comment by antoine-de** [comment]
hum en fait en important simplement l'id datagouv de la ressource, on peut n'importer que nos RC, et continuer à afficher les autre RC à l'affichage de la page.

pis si on veut on fera bouger le curseur de ce qu'on importe plus tard.

Ca te semble bien @Tristramg ?

**Comment by Tristramg** [comment]
Quitte à importer, autant tout importer :) ça sert à rien de filtrer.
Ensuite à voir comment on expose, par petits pas
