### ISSUE TITLE
Rajouter de nouveaux chantiers dans "À venir dans les prochains mois"

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#1163]
Rajouter dans "À venir dans les prochains mois" de la page d'accueil : 

- Aménagements cyclables 
- Travaux sur voirie

**Comment by antoine-de** [comment]
le plus dur va etre de trouver des pictos :stuck_out_tongue_winking_eye:

**Comment by fchabouis** [comment]
@thimy peut-être que tu aurais un peu de temps si on a des petites commandes pour toi ?

**Comment by thimy** [comment]
Oui bien sûr, j'ai pas grand chose à faire en ce moment donc ce sera avec plaisir (et puis vous me manquez un peu).
