### ISSUE TITLE
Ajouter l'analyse du calendar dans la validateur GTFS manuel

### ISSUE THREAD

**Issue by NicolasBerthelot** [etalab/transport-site#1179]
Il serait pratique de présenter les dates limites du GTFS dans le validateur GTFS (https://transport.data.gouv.fr/validation) . Ce sera utile pour les biz dev quand on leur dit qu'un fichier est censé couvrir une certaine période. Ce sera sans doute également utile pour certains utilisateurs de la plateforme

**Comment by antoine-de** [comment]
ca a été fait dans dans la PR #1188
