### ISSUE TITLE
changer le compte du bot qui poste des commentaires 

### ISSUE THREAD

**Issue by antoine-de** [etalab/transport-site#1180]
Pour le moment c'est avec le compte de @l-vincent-l , c'est pas ouf.

![image](https://user-images.githubusercontent.com/3987698/83501075-24b07e80-a4af-11ea-87dc-12e410375d1d.png)

**Comment by NicolasBerthelot** [comment]
Le bot dort, il faudra bien le changer lorsqu'on le réveillera cf. #1461
