### ISSUE TITLE
Afficher le geojson d'un GTFS

### ISSUE THREAD

**Issue by antoine-de** [etalab/transport-site#1182]
Maintenant qu'on a une [première version](https://gitlab.com/CodeursEnLiberte/gtfs-to-geojson/) pour calculer le geojson d'un GTFS, ca serait sympa de s'en servir.

Ca pourrait permettre de faire un visualisateur simple de GTFS (voir de tous les GTFS de la plateforme :star_struck: )

Je vois plusieurs solutions pour faire ca :

### Ressources communautaires
un peu sur le même principe que [ce qu'on fait](https://github.com/etalab/gtfs_converter/) pour les NeTEx, toutes les nuits, on calcul le geojson associé au GTFS, et on le pousse en ressource communautaires.

Pis sur la page d'un dataset, on se fait une visualisation de ce geojson (directement sur la page ou sur demande pour ne pas ralentir le chargement de la page).

:heavy_plus_sign: c'est simple
:heavy_plus_sign: le geojson est accessible à ceux qui veulent s'en servir
:heavy_minus_sign: on peut pas trop afficher une carte avec toutes les géométries de la plateforme
:heavy_minus_sign: l'affichage risque d’être super lent pour genre le geojson de l'idf, il faudrait surement qu'on mette une limite au geojson affiché

### Importer les geojson en base
On pourrait aussi faire tourner toutes les nuits le convertisseurs et stocker dans notre base (ou une autre bdd) les géométries en POSTGIS.
pis on fait une api qui file les geom pour une bounding box données, et sur la page des datasets on affiche ca
:heavy_plus_sign: ca devrait etre plus fluide (on ne va afficher qu'une partie des geom, et on peut bloquer le truc/agréger aux haut niveaux de zoom)
:heavy_plus_sign: on peut faire la carte au niveau national
:heavy_minus_sign: ca va alourdir bcp la base, faut voir si on veut mettre ca dans une base à part pour pas que ca saoule au niveau des backup/restore
:heavy_minus_sign: c'est plus compliqué et peut etre overkill

### faire des convertions à la volée
Un peu le même principe que la premiere solution, mais on ne publie pas le geojson en ressource communautaire, on le calcul à la volée. En optimisant un peu, la création du geojson pour l'idf c'est <2s + le téléchargement ca devrait prendre ~10s. on peut imaginer le faire à la demande coté serveur (ou en webassembly niveau du navigateur :heart_eyes: ).

:heavy_plus_sign: c'est encore plus simple
:heavy_minus_sign: on peut pas trop afficher une carte avec toutes les géométries de la plateforme
:heavy_minus_sign: l'affichage risque d’être encore plus lent pour les gros jdd, faudra peut etre bloquer l'affichage

## Conclusion
Vous voyez d'autre facon de faire ? Vous pensez que ca vaut le coup ? une préférence sur la solution ?

**Comment by fchabouis** [comment]
Après discussion, on partirait sur la création systématique de ressource communautaire, qu'on pourrait afficher si de taille raisonnable. Parce que ça pourrait servir à d'autres personnes.

Dans un second temps, on pourrait stocker ces ressources en base, indexées par Postgis pour pouvoir afficher n'importe quel réseau, voire tous.
