### ISSUE TITLE
Lier 2 GTFS décrivant le même réseau, mais produit par différents producteurs

### ISSUE THREAD

**Issue by be-mercier** [etalab/transport-site#1186]
La plateforme transport.data.gouv.fr commence à comptabiliser un certains cas de GTFS "doublons", par exemple lorsqu'une région publie des fichiers GTFS pour chacune des AOM urbaine sur sur territoire, mais que l'AOM continue elle aussi à publier directement sur transport.data.gouv.fr un GTFS pour décrire son réseau. 

Par exemple, à Poitiers il y a un GTFS qui a été publié par l'agglo de Poitier : https://transport.data.gouv.fr/datasets/mobilite-arrets-services-et-horaires-theoriques-bus-fichier-gtfs/ 

et un autre GTFS publié par le syndicat régional Nouvelle Aquitaine Mobilités : https://transport.data.gouv.fr/datasets/arrets-horaires-et-parcours-theoriques-des-reseaux-naq-vit-nva-m/ 

**Idéalement, il faudrait éditorialiser ces deux jdd pour qu'un réutilisateur 1) comprennent qu'il s'agit de 2 GTFS équivalents (décrivant le même réseau), et 2) qu'à partir de la fiche d'un de ces GTFS, on retrouve un lien vers la fiche du deuxième GTFS**.

**Comment by antoine-de** [comment]
hum et tu ne penses pas qu'on peut se servir des pages de listes de données liées à une ville pour ca ?

On pourrait mettre sur la page du jdd ce qu'on avait avant, genre "Retrouvez les x autres jeux de données d'horaires théoriques de transport public de Poitier [ici](https://transport.data.gouv.fr/datasets/commune/86194?type=public-transit)"

On perd par contre un peu la notion de doublons, car on pourrait renvoyer vers des jdd interurbain, ou agrégés au niveau régional :thinking: 

(Après l'exemple de poitier est vraiment pas ouf, vu qu'on associe tous les jdd départementaux à toute la région, on a l'impression qu'il y a vraiment bcp de jeux. Faudrait peut etre qu'on voit pour pouvoir associer des jdd à des départements, ou des zones arbitraires, mais c'est un peu compliqué niveau tech)

**Comment by NicolasBerthelot** [comment]
c'est trop compliqué à mettre en place, le regroupement des données par AOMs est trop complexe. En revanche il faudrait clarifier la présence de "doublons" pour les réutilisateurs.
