### ISSUE TITLE
Problèmes d'affichage moteur de recherche

### ISSUE THREAD

**Issue by NicolasBerthelot** [etalab/transport-site#1199]
Quelques petits bugs d'affichage apparaissent sur mon écran : MacBook 2304 x 1440

Par exemple là il saute des lignes alors qu’il n’atteint pas le titre n’atteint pas le bout de la ligne. Peut-être que c’est parce qu’il y pas de logos sur le thème stationnement parce que ce truc n’arrive qu’à ces datasets... Et du coup ça fait sauter la couverture spatiale
![image](https://user-images.githubusercontent.com/61453166/84162267-76897380-aa70-11ea-8717-8a4bec7f153c.png)

Sinon quand la couverture spatiale est un peu longue on coupe au milieu
![image](https://user-images.githubusercontent.com/61453166/84162351-91f47e80-aa70-11ea-8bb4-ec0c0116c2d0.png)

**Comment by fchabouis** [comment]
Ouais puis t'as vu les logos à gauche sont tout petits.

**Comment by fchabouis** [comment]
@NicolasBerthelot j'ai pushé sur https://prochainement-transport.cleverapps.io/, tu peux me dire si c'est bien corrigé chez toi ? Chez moi aussi c'était moche, mais moche différent, alors je veux bien une confirmation que c'est corrigé chez toi. Merci !
