### ISSUE TITLE
Erreur 500 sur les pages inexistantes

### ISSUE THREAD

**Issue by jdauphant** [etalab/transport-site#1228]
Ces pages sont référencé dans l'index google :
https://transport.beta.gouv.fr/blog/2019_04_26_interview_my_bus
https://transport.beta.gouv.fr/blog/2019_10_24_itw-gueret

Sur toutes les pages inexistantes, il y a une erreur 500 au lieu de 404
https://transport.beta.gouv.fr/hhh

**Comment by antoine-de** [comment]
merci, on va corriger ca !
