### ISSUE TITLE
Snapshot Articles de blog

### ISSUE THREAD

**Issue by NicolasBerthelot** [etalab/transport-site#1234]
Le blog ne renvoie pas d'images dans le snapshot sur Twitter : https://twitter.com/transportdatafr/status/1273167242176409601 
Y aurait moyen de lui faire sortir l'image principale de l'article ?

**Comment by fchabouis** [comment]
ah oui bien vu

**Comment by fchabouis** [comment]
Tu peux tester un partage @NicolasBerthelot ?
