### ISSUE TITLE
JDD avec mauvaise date de validité des données

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#1243]
Il y a plusieurs jeux de données avec des métadonnées indiquant que le JDD est périmé mais il est encore à jour. 

- Soit je n'arrive pas à faire l'import et ai ça en message d'erreur : %{region: ["Vous devez remplir soit une région soit une AOM soit utiliser les zones data.gouv"]}
Bien que j'affilie le JDD à la région 
                                                          AOM concernées : 
- Charlevilles Mezieres
https://transport.data.gouv.fr/datasets/horaires-theoriques-du-reseau-tac-communaute-dagglomeration-ardenne-metropole-gtfs
https://www.data.gouv.fr/fr/datasets/horaires-theoriques-du-reseau-tac-communaute-dagglomeration-ardenne-metropole-gtfs/

- Bordeaux 
https://transport.data.gouv.fr/datasets/arrets-horaires-et-parcours-theoriques-des-reseaux-naq-bme-nva-m/
https://www.data.gouv.fr/fr/datasets/arrets-horaires-et-parcours-theoriques-des-reseaux-naq-bme-nva-m/

- Soit on m'indique que le dataset a été ajouté mais il n'y a aucun changement 
                                                           AOM concernées : 

- Grand Avignon 
https://transport.data.gouv.fr/datasets/gtfs-des-transports-urbains-du-grand-avignon-tcra/
https://www.data.gouv.fr/fr/datasets/gtfs-des-transports-urbains-du-grand-avignon-tcra/

- Strasbourg 
https://transport.data.gouv.fr/datasets/horaires-theoriques-du-reseau-de-transport-cts
https://www.data.gouv.fr/fr/datasets/horaires-theoriques-du-reseau-de-transport-cts/

- Centre-Val de Loire 
https://transport.data.gouv.fr/datasets/arrets-itineraires-et-horaires-theoriques-des-reseaux-de-transport-des-membres-de-jvmalin/
https://www.data.gouv.fr/fr/datasets/arrets-itineraires-et-horaires-theoriques-des-reseaux-de-transport-des-membres-de-jvmalin/
             JDD publiés par la région Centre-Val de Loire : 
- Issoudun 
https://transport.data.gouv.fr/datasets/issoudun-offre-theorique-mobilite-reseau-urbain/
https://www.data.gouv.fr/fr/datasets/issoudun-offre-theorique-mobilite-reseau-urbain/
- Bourges
https://transport.data.gouv.fr/datasets/agglobus-offre-theorique-mobilite-reseau-urbain-de-bourges/
https://www.data.gouv.fr/fr/datasets/agglobus-offre-theorique-mobilite-reseau-urbain-de-bourges/
-Interurbain Centre-Val de Loire 
https://transport.data.gouv.fr/datasets/remi-offre-theorique-mobilite-reseau-interurbain-regional/
https://www.data.gouv.fr/fr/datasets/remi-offre-theorique-mobilite-reseau-interurbain-regional/

**Comment by antoine-de** [comment]
closed by #1244 

il faut réimport et revalider tous les jdd, ca devrait être bon d'ici ~2h @Miryad3108 , merci de la remontée de bug :raised_hands:
