### ISSUE TITLE
Erreur dans le backoffice pour l'import du JDD du réseau urbain Oléane

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#1249]
Il n'y a pas de ressource principale dans la fiche transport.data.gouv.fr du Réseau urbain Oléane (JDD publié par la région Pays de la Loire) : https://transport.data.gouv.fr/datasets/lignes-arrets-et-horaires-theorique-du-reseau-de-transport-gtfs-les-sables-dolonne-agglomeration/

Ils ont deux fiches data.gouv : 
1/ Une fiche qu'ils n'entretiennent plus : https://www.data.gouv.fr/fr/datasets/arrets-horaires-et-circuits-des-lignes-oleane-gtfs-les-sables-dolonne-agglomeration/
2/  Une fiche avec un JDD à jour (MAJ automatique) : https://www.data.gouv.fr/fr/datasets/lignes-arrets-et-horaires-theorique-du-reseau-de-transport-gtfs-les-sables-dolonne-agglomeration/

Leur fiche transportdatagouv tient compte de l'ancienne fiche qui contient un CSV et un JSON. 
J'ai essayé d'importer le JDD en mettant le lien vers la bonne fiche datagouv à plusieurs reprises mais j'ai ce message d'erreur alors que j'affilie la ressource à la région (cf. capture d'écran) 

![image](https://user-images.githubusercontent.com/59559301/87672080-aa903c80-c772-11ea-920c-a5bbaf6a1a4c.png)

**Comment by antoine-de** [comment]
linked to #1033 
la ressource est servie par un ftp, et on ne sait pas gérer, je suis en train de regarder comment faire, mais ca va prendre un peu de temps :roll_eyes:

**Comment by NicolasBerthelot** [comment]
Ce problème sera géré par la résolution du bug : https://github.com/etalab/transport-site/issues/1033
