### ISSUE TITLE
Refonte de la home

### ISSUE THREAD

**Issue by antoine-de** [etalab/transport-site#1257]
Après un atelier sur les landing page on s'est dit que ca serait bien d'avoir plusieurs landing page, par type d'utilisateur.

L'idée serait que la home soit pensée pour les réutilisateurs de données, et qu'une page spécifique pour les producteurs soit crée.
lié à #971 

En dessous, tout le monde va mettre des propositions de refonte.

**Comment by fchabouis** [comment]
![Untitled-2020-07-22-1503(1)](https://user-images.githubusercontent.com/15341118/88188305-f2fa9f00-cc37-11ea-9773-ac41e9936a0d.png)

https://excalidraw.com/#json=5646641042292736,Zr_DqhSIlA4yktAKiYCPEA

**Comment by NicolasBerthelot** [comment]
![image](https://user-images.githubusercontent.com/61453166/88188382-10c80400-cc38-11ea-9497-58ca1e4d90e6.png)

https://excalidraw.com/#json=5761137303879680,fMkvDMckmaiWieQaMWRCnQ

**Comment by fchabouis** [comment]
proposition de @antoine-de 

![Untitled-2020-07-22-1626](https://user-images.githubusercontent.com/15341118/88188462-2dfcd280-cc38-11ea-9afa-4e034ace8efa.png)

https://excalidraw.com/#json=5987617506066432,-S3l6s0Y4W2e42yA2HmMNQ

**Comment by JeanneAstier** [comment]
![landing-page-Jeanne](https://user-images.githubusercontent.com/66944516/88188968-cf842400-cc38-11ea-8f12-e09c1a48fd55.png)

**Comment by fchabouis** [comment]
Avec @JeanneAstier nous avons essayé de fusionner toutes les bonnes idées des 4 documents précédents, pour en arriver à ce resultat.
https://excalidraw.com/#json=5689042586828800,z6FTvZgBDUO4r5n76FdU5g

![Untitled-2020-07-22-1503(3)](https://user-images.githubusercontent.com/15341118/88384147-28c09480-cdac-11ea-82ab-61aa3498b772.png)


Quelques explications...on trouve de haut en bas
- titre + catch phrase avec barre de recherche + CTA "explorer les données" (peut importe le layout horizontal ou vertical)
- notre proposition de valeur qui se résumerait en 3 points : gratuité / libre acces de la plateforme, qualité et praticité des données qu'on y trouve, les à côtés qui simplifient la vie (outils, visualisation,...)
- bandeau adressé aux producteurs de données
- les tuiles des modes de transport, mais en moins imposant qu'avant.
- stats clés
- une partie sur la "communauté" transport (nous sommes pluuuus qu'une plateforme technique) qui peut rediriger vers une page qui contiendrait l'inscription à la newletter, le slack, la liste des events organisés ou à venir, le mail, etc
- réutilisateurs

**Comment by antoine-de** [comment]
top ! J’ai l’impression que toutes les infos de la home actuelle peuvent trouver une section où être rangées.

je mets des remarques un peu en vrac :
* vous pensez pas que la partie "réutilisateurs" arrive un peu tôt ?
* on garde quand même de la place pour la superbe illustration ? (moi je l’aime vraiment bien :stuck_out_tongue_winking_eye: )
* j’ai l’impression qu’il faut qu’on itère un peu sur notre proposition de valeur, mais la section est top.
* Les 2 layout sont pas mal, j’ai l’impression que j’ai une petite préférence pour le premier, mais c’est peut être par réaction au changement.

Sur le gitbook, il ne faut pas oublier qu’a la base on avait mis ça en place pour éviter d’alourdir sa rédaction en obligeant des contributions sur le site, du coup je suis partagé sur le fait de le scinder en 2. Qu'est ce qui vous dérange avec le gitbook actuel ?

On peut attendre un retour du reste de l'équipe, mais si on part là-dessus, on pourra peut-être créer des issues sur les différentes sections (+ page explorer les données) pour itérer dessus en parallèle.

**Comment by JeanneAstier** [comment]
pour l'illustration (clairement l'élément le plus important de la landing page)  : oui on s'était dit que ce serait bien de la garder (je l'adore aussi ❤️ ), on ne sait juste pas encore exactement sous quelle forme, du coup on avait pensé voir avec Thimy comment on pourrait l'intégrer / l'adapter à la nouvelle landing page

**Comment by fchabouis** [comment]
@antoine-de merci pour ton retour.

* vous pensez pas que la partie "réutilisateurs" arrive un peu tôt ?
=> elle arrive en dernier justement....ou bien tu voulais dire tard / bas ?
* illustration, je crois que tout le monde y est attaché :) Mais on s'est dit qu'on se concentre sur quel contenu dans quel ordre sur cette home, et qu'après on verrait avec @thimy la partie design.
* j’ai l’impression qu’il faut qu’on itère un peu sur notre proposition de valeur, mais la section est top.
=> complètement, je crois que @NicolasBerthelot était chaud pour y réfléchir d'ailleurs
* le gitbook, de part son adresse à part (doc.transport...), sa typo et son organisation fait tout de suite doc technique. Je trouve qu'une page de présentation du projet sur le site principal serait plus logique, la doc restant alors un document purement technique... à discuter !

**Comment by antoine-de** [comment]
>    vous pensez pas que la partie "réutilisateurs" arrive un peu tôt ?
    => elle arrive en dernier justement....ou bien tu voulais dire tard / bas ?

Ah je parlais de la partie "Producteurs de données", my bad :dizzy_face: 

> => complètement, je crois que @NicolasBerthelot était chaud pour y réfléchir d'ailleurs
le gitbook, de part son adresse à part (doc.transport...), sa typo et son organisation fait tout de suite doc technique. Je trouve qu'une page de présentation du projet sur le site principal serait plus logique, la doc restant alors un document purement technique... à discuter !

Ah marrant j'ai pas trop ce sentiment. Tu penses pas que c'est une question de travailler un peu le style ?
Par exemple la [doc de l'incubateur](https://doc.incubateur.net/communaute/) est aussi un gitbook, tu trouves qu'elle fait tech ?
Hum sinon il faut qu'on trouve un moyen facile de pouvoir maintenir une page de présentation du projet.

**Comment by fchabouis** [comment]
A Faire :
- ajouter un fil d'Ariane dans la partie espace producteurs, pour l'ajout et la mise à jour de ressources.
- déplacer le lien "voir le jeu de données" en amont (dans la page producteurs directement ?)

**Comment by fchabouis** [comment]
C'est fait :heart:

**Comment by thbar** [comment]
Bravo super boulot !
