### ISSUE TITLE
problème pour revenir sur le site depuis la documentation

### ISSUE THREAD

**Issue by JeanneAstier** [etalab/transport-site#1261]
sur le site transport.data.gouv.fr, quand on clique sur "à propos" cela renvoie dans doc.transport.data.gouv.fr et une fois sur cette page il n'y a pas de bouton pour revenir au site du PAN (même quand on clique sur transport.data.gouv en haut à gauche de la page de doc, on reste bloqué dans la doc).

**Comment by fchabouis** [comment]
C'est une contrainte de gitbook que le titre en haut à gauche de la page envoit vers la home du gitbook.

Par contre j'ai modifié le titre en doc.transport.data.gouv.fr pour que ce soit clair, et j'ai pu ajouter dans le header un lien vers le site et vers le blog.

Ça te parait plus clair ?

**Comment by JeanneAstier** [comment]
Je trouve ça super clair, c'est magnifique, merci beaucoup Francis !
