### ISSUE TITLE
Refonte de la mise en valeur des resources d'un jeu de données

### ISSUE THREAD

**Issue by antoine-de** [etalab/transport-site#1263]
Pour le moment je trouve que la liste des ressources / ressources communautaires pourrait être plus claire.

Ca donne ca (pour le jdd de nouméa):

![image](https://user-images.githubusercontent.com/3987698/88568671-da6bf980-d028-11ea-9386-b8c2eef27504.png)

J'ai l'impression qu'on pourrait améliorer:

1. le lien vers le détail de la ressource
pour le moment c'est que sur le lien de validation. j'ai l'impression qu'on pourrait mieux le mettre en évidence
2. lien entre le GTFS et les NeTEx/geojson généré.
Je pense qu'on gagnerait à rendre plus explicite que certaines ressources communautaires sont liées à des ressources.
On pourrait soit mettre un lien vers une ancre dans la liste des ressources communautaires, soit juste un lien de dl (et voir virer ces ressources des ressources communautaires), je sais pas trop ce qui est le mieux 
3. Je pense qu'on pourrait aussi afficher plus d'info sur les ressources communautaires (genre au moins le format)

J'ai pas trop d'idées sur la tête que ca pourrait avoir par contre :roll_eyes:

**Comment by antoine-de** [comment]
Un truc sympa serait aussi de mieux mettre en valeur qu'on peut avoir une prévisualisation du GTFS si on clique sur "Voir plus de détail sur la ressource GTFS et sa validation", ce qui est loin d'être évident

**Comment by fchabouis** [comment]
brainstorming :)

![image](https://user-images.githubusercontent.com/15341118/92712245-abe87a80-f359-11ea-9970-c65cfb59177d.png)

**Comment by antoine-de** [comment]
une question sur ce design est de voir si on traite les réseaux qui ont eux même publié leur données en NeTEx (genre [eux](https://transport.data.gouv.fr/datasets/arrets-horaires-et-parcours-theoriques-des-reseaux-naq-bri-nva-m/) de la même manière ou si on continue à mettre plusieurs ressources.

J'ai l'impression qu'une premiere version où on propose juste de télécharger le GTFS en geojson, et une ressource à part pour le NeTEx est pas si mal (surtout que les ressources peuvent avoir des dates de validité / qualité différentes (même si on n'affiche pas ca pour le moment))

**Comment by antoine-de** [comment]
on peut fermer grace au super travail sur #1305 :raised_hands:
