### ISSUE TITLE
0 arrêt dans les détails de la ressource (GTFS) 

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#1281]
Dans certains JDD il y a 0 zone d'arrêt dans les détails de la ressource alors qu'on les voit dans "l'aperçu des arrêts et lignes". 
Exemple : 
https://transport.data.gouv.fr/resources/10965

https://transport.data.gouv.fr/resources/11115

**Comment by antoine-de** [comment]
En fait ca vient de la différence entre zone d’arrêt (chatelêt) et point d’arrêt (le poteau de bus de la ligne 76 à Chatelêt).
Dans le jdd il y a 0 zones d'arrêts, que des points d’arrêts.
Aprés on pourrait peut être considérer les points sans zones dans ce décompte. T'as un avis la dessus @Tristramg ?
