### ISSUE TITLE
Mauvaise date de validité dans métadonnées - Grenoble : https://transport.data.gouv.fr/datasets/horaires-theoriques-du-reseau-tag/

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#1283]
Le jeu de données est valable jusqu'en octobre 2020 lorsqu'on regarde le fichier calendar du JDD mais sur les métadonnées le JDD apparaît comme étant périmé : 

https://transport.data.gouv.fr/datasets/horaires-theoriques-du-reseau-tag/

**Comment by fchabouis** [comment]
corrigé
