### ISSUE TITLE
Bug extracteur de géométries

### ISSUE THREAD

**Issue by NicolasBerthelot** [etalab/transport-site#1284]
Le convertisseur GTFS to geojson semble ne pas fonctionner sur ce le réseau Star de Rennes : 
https://transport.data.gouv.fr/resources/11133

![image](https://user-images.githubusercontent.com/61453166/91983104-7fb27580-ed2b-11ea-9b03-d85294d9d606.png)

**Comment by antoine-de** [comment]
hop c'est réparé, c'est tout zouli maintenant: 
![image](https://user-images.githubusercontent.com/3987698/92281445-285b0380-eeeb-11ea-9b6e-09ef0a23911e.png)
