### ISSUE TITLE
Suppression de datasets impossible

### ISSUE THREAD

**Issue by NicolasBerthelot** [etalab/transport-site#1287]
Je rencontre depuis pas mal de temps ce problème : je ne parviens pas à supprimer ce jeu de données https://transport.data.gouv.fr/backoffice/datasets/430/

J'obtiens une erreur 500 : 
![image](https://user-images.githubusercontent.com/61453166/91995502-2f8de000-ed38-11ea-995b-dfeb78ae9fbe.png)

**Comment by fchabouis** [comment]
@NicolasBerthelot d'ici 10 minutes je te laisse re tester une suppression de ce dataset et me confirmer que ça a bien marché ?
Merci !

**Comment by NicolasBerthelot** [comment]
C'est bon !
