### ISSUE TITLE
Erreur dans les métadonnées de Lyon (JDD à jour mais apparaît comme périmé) : https://transport.data.gouv.fr/datasets/horaires-theoriques-du-reseau-transports-en-commun-lyonnais-1/

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#1290]
Le jeu de données de Lyon apparaissent comme étant périmé depuis le 28.04.2020 mais il est à jour jusqu'au 10.10.2020
https://transport.data.gouv.fr/datasets/horaires-theoriques-du-reseau-transports-en-commun-lyonnais-1/

**Comment by fchabouis** [comment]
Une validation lancée depuis le backoffice manuellement règle le problème...on va continuer à essayer de comprendre pourquoi ça ne se fait pas tout seul, mais au moins ça vous permet de débloquer facilement le soucis.
