### ISSUE TITLE
Passer la région Bourgogne-Franche-Comté en vert !

### ISSUE THREAD

**Issue by NicolasBerthelot** [etalab/transport-site#1296]
La Bourgogne France Comté a publié un jeu de données qui contient toutes les données des réseaux interurbains régionaux : https://transport.data.gouv.fr/datasets/reseau-de-transport-interurbain-mobigo-en-bourgogne-franche-comte/

Ils méritent bien de passer en vert sur la page stats !

**Comment by antoine-de** [comment]
done !
![image](https://user-images.githubusercontent.com/3987698/92477510-42893000-f1d0-11ea-9554-ba1b70313689.png)
