### ISSUE TITLE
FAQ producteur de données et mises à jour

### ISSUE THREAD

**Issue by fchabouis** [etalab/transport-site#1301]
Un message de Sophie Raspail qui nous montre que ce point n'est pas évident à comprendre...

Bonjour,
J’espère que votre été s’est bien passé
Merci pour tous ces éléments que j’ai transmis à la collectivité de corse.
J’aurais une question à vous poser : est-ce que transport.data.gouv.fr est alimenté automatiquement via API depuis les open-data locaux ? Car je constate que les données corses sont loin d’être à jour (ajout en 2018 ou 2019, et rien en 2020).
Merci pour votre retour
Bien cordialement

**Comment by NicolasBerthelot** [comment]
1. Compréhension générale du rapport data.gouv.fr <> transport.data.gouv.fr
2.  Publication manuelle
3.  Publication distante
4.  Publication sur OpenDataSoft

**Comment by thbar** [comment]
Vu avec @Miryad3108, on peut a priori fermer (voir https://doc.transport.data.gouv.fr/foire-aux-questions-1/generalites#quel-est-le-lien-entre-transport.data.gouv.fr-et-data.gouv.fr).
