### ISSUE TITLE
Mettre un cache pour les flux GBFS

### ISSUE THREAD

**Issue by fchabouis** [etalab/transport-site#1317]
Pour le moment, chaque requête chez nous occasionne une requête sur le flux initial. On pourrait envisager de mettre un cache en place pour éviter de surcharger inutilement les API des producteurs.

**Comment by fchabouis** [comment]
Et rajouter une clé pour les vlilles, pour le moment on est limités a 1000 appels par jour...
Il faut se créer un compte, aller chercher sa clé dans son espace perso, et faire des appels en rajoutant &key=<clé> à l'url.

**Comment by antoine-de** [comment]
le plus simple c'est peut etre juste de [demander à clever](https://www.clever-cloud.com/doc/tools/varnish/) de mettre un [varnish](https://varnish-cache.org/intro/index.html#intro) et de l'activer pour les routes en `/gbfs` non ?
https://github.com/CleverCloud/varnish-examples

**Comment by antoine-de** [comment]
done by #1380
