### ISSUE TITLE
Limiter le spam depuis le formulaire de contact

### ISSUE THREAD

**Issue by antoine-de** [etalab/transport-site#1323]
On a notre stock de gel hydroalcoolique et de viagra, on peut peut être regarder pour limiter le spam sur l'adresse de transport :stuck_out_tongue_winking_eye: 

Pour le formulaire, visiblement une technique super simple c'est de mettre un honey pot, un champs que tu caches une fois la page chargé grâce à du JS. Les bots n’exécutant pas le JS ils vont remplir ce champ, ainsi tu sais que si le champ est rempli c'est que c'est un bot qui l'a rempli, tu peux donc ne pas prendre en compte cette réponse.

Voici un exemple gentiment mis à dispo par @l-vincent-l https://gist.github.com/andrewlimaza/958826feac907114a57462bfc8d535ff

Aprés j'ai aucune idée de la proportion de spam qu'on a qui vient de la, mais ca a l'air simple à mettre en place

**Comment by fchabouis** [comment]
:honey_pot:
