### ISSUE TITLE
Bug dataset Bretagne

### ISSUE THREAD

**Issue by NicolasBerthelot** [etalab/transport-site#1328]
La Bretagne est rouge sur la page stats : 
![image](https://user-images.githubusercontent.com/61453166/96108096-7ea16600-0edd-11eb-937c-cb37253b8e71.png)

Effectivement l'une des ressources a une erreur irrécupérable mais une autre semble ok. https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-transports-publics-en-bretagne-mobibreizh/
![image](https://user-images.githubusercontent.com/61453166/96108306-b3adb880-0edd-11eb-87be-3adfb982979e.png)

Il faudrait peut-être faire le ménage ?

**Comment by antoine-de** [comment]
c'est pas à eux de supprimer l'ancien dataset invalide ?

**Comment by NicolasBerthelot** [comment]
J'ai l'impression que c'est plutôt la faute au moissonneur qui ne supprime jamais les pièces jointes passées (ils utilisent le système de la pièce jointe opendatasoft en Bretagne) https://breizh.opendatasoft.com/explore/dataset/base-de-donnees-multimodale-transports-publics-en-bretagne-mobibreizh/information/

**Comment by antoine-de** [comment]
ca a l'air d'être corrigé de leur côté, je ferme

**Comment by thbar** [comment]
Est-ce le même souci que nous venons de corriger ici #1361 #1355 ? (pour savoir si on peut clôturer).

**Comment by antoine-de** [comment]
hum oui, mais du coup il faudrait peut etre voir si on peut faire quelque chose au niveau du moissonneur data.gouv :thinking:

**Comment by antoine-de** [comment]
je pense qu'on peut fermer quand meme je ne sais pas trop ce qu'on peut faire pour le moissonneur (@NicolasBerthelot une idée ?)
