### ISSUE TITLE
Rendre correctement le markdown dans les ressources communautaires

### ISSUE THREAD

**Issue by antoine-de** [etalab/transport-site#1334]
Le markdown de la description des ressources communautaires est tout naze:
https://transport.data.gouv.fr/datasets/horaires-theoriques-et-temps-reel-du-reseau-luneo-gtfs-gtfs-rt/#dataset-resources
![image](https://user-images.githubusercontent.com/3987698/97424686-fd989480-1908-11eb-9f1d-d0e11d66ec97.png)

(ca ne posait pas de soucis avant qu'on mette du markdown pour les ressources siri lite)
Il faudrait peut être qu'on fasse [la même chose](https://github.com/etalab/transport-site/blob/master/apps/transport/lib/transport_web/views/dataset_view.ex#L261-L267) que pour la description du dataset.

**Comment by thbar** [comment]
J'ai vérifié visuellement sur https://transport.data.gouv.fr/datasets/horaires-theoriques-et-temps-reel-du-reseau-luneo-gtfs-gtfs-rt/#dataset-resources et ça semble bon.
