### ISSUE TITLE
Associer dataset de réseau agrégés à différentes AOMs

### ISSUE THREAD

**Issue by NicolasBerthelot** [etalab/transport-site#1342]
Ce [dataset ](https://transport.data.gouv.fr/datasets/arrets-horaires-et-circuits-des-lignes-de-transports-en-commun-en-pays-de-la-loire-gtfs/) peut être associé à plusieurs AOMs : 
- Région Pays de la Loire
- Nantes
- Angers
- La Roche-sur-Yon
- Saint-Nazaire
- Le Mans
- Cholet
- Presqu'île de Guérande
- Sables d’Olonne Agglomération
- Saumur
- Sablé-sur-Sarthe
- Ile d’Yeu
- Laval

**Comment by antoine-de** [comment]
done, désolé pour le retard.

Pour tracer ce que j'ai fait:
J'ai récuperé à l'arrache l'id des AOM à coup de :

```sql
select aom.id, aom.nom, c.nom from aom join commune c on c.insee = aom.insee_commune_principale where aom.nom ilike '%sable%';
```

pis j'ai mis à jour le `parent_dataset_id` de ces jdd:
```sql
UPDATE aom set parent_dataset_id = 579 where id in (5, 65, 110, 106, 15, 38, 224, 122, 105, 137, 203, 22);
```
(il y a sûrement moyen de faire mieux :rofl: )

Et on peut voir ce que ca change dans la page [stats](https://transport.data.gouv.fr/stats)
Avant: 
![image](https://user-images.githubusercontent.com/3987698/100631968-3242a600-3324-11eb-8870-8dc74dc34c54.png)
(les jdd d'Angers et Nantes sont publiés par l'AO spécifiquement)

Aprés:
![image](https://user-images.githubusercontent.com/3987698/100632090-51d9ce80-3324-11eb-92c9-3f1efa14933b.png)
Angers et Nantes sont publiés par l'AO et la région, et saumur, cholet,... sont dans un JDD aggregé.

**Comment by thbar** [comment]
@antoine-de merci d'avoir pris le temps de documenter c'est top et ça resservira !
