### ISSUE TITLE
Cluster de données "non conformes" sur la Bretagne 

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#1355]
(remonté par @NicolasBerthelot)

Sur le [zoom qualité des données](https://transport.data.gouv.fr/stats#public-transport-quality) de la page stats, on voit que la Bretagne est toute en rouge:

<img width="253" alt="CleanShot 2020-11-12 at 11 13 22@2x" src="https://user-images.githubusercontent.com/10141/98926846-1ba0f000-24d8-11eb-98a8-477cbdfb68e5.png">

ce qui correspond à "non conforme" dans la légende.

C'est un bon ticket d'onboarding data pour que j'aille creuser cette partie de l'application, je vais enquêter.

### Enquête

* Les zones rouges sont cliquables
* On arrive sur différentes "AOM", exemple:
  * https://transport.data.gouv.fr/datasets/aom/113
  * https://transport.data.gouv.fr/datasets/aom/175
  * https://transport.data.gouv.fr/datasets/aom/148
* Ces AOMs référencent 1 ou N datasets
* À chaque fois, le dataset [Agrégat de réseaux urbains et interurbains de Bretagne](https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-transports-publics-en-bretagne-mobibreizh/) est présent
* Je vais creuser en local le code de la carte pour voir d'où est tiré la couleur rouge
  * La section de carte est définie [ici](https://github.com/etalab/transport-site/blob/d53bd6fa0d397f1dca01f329bd29233c6db91f56/apps/transport/lib/transport_web/templates/stats/index.html.eex#L139)
  * Juste au dessus, il y a un include de "maps", et en bas, un include de [map.js](https://github.com/etalab/transport-site/blob/master/apps/transport/client/javascripts/map.js)
  * Tout en bas j'ai pu filtrer les logs dans [cette boucle](https://github.com/etalab/transport-site/blob/d53bd6fa0d397f1dca01f329bd29233c6db91f56/apps/transport/client/javascripts/map.js#L643-L651), ne garder que ceci:

```javascript
for (const [drom, view] of Object.entries(droms)) {
    if (drom == "metropole") {
        // addStaticPTMapRegions(`map_regions_${drom}`, view)
        // addStaticPTUpToDate(`pt_up_to_date_${drom}`, view)
        // addStaticPTMapAOMS(`map_aoms_${drom}`, view)
        addStaticPTQuality(`pt_quality_${drom}`, view)
        // addPtFormatMap(`pt_format_map_${drom}`, view)
        // addRealTimePTMap(`rt_map_${drom}`, view)
        // addBikesMap(`bikes_map_${drom}`, view)
    }
}
```

  * De fil en aiguille on tombe sur la [partie chargée de récupérer les données de qualité](https://github.com/etalab/transport-site/blob/e63ae0b0df9ed9d30f5681dd148616ce81ba9b2e/apps/transport/client/javascripts/map.js#L360)
  * La méthode [`displayQuality`](https://github.com/etalab/transport-site/blob/e63ae0b0df9ed9d30f5681dd148616ce81ba9b2e/apps/transport/client/javascripts/map.js#L120) fait le chargement et le rendu pour la zone zoom qualité de données
  * Et du coup je tombe sur le bon endpoint [`qualityUrl = "/api/stats/quality"`](https://github.com/etalab/transport-site/blob/e63ae0b0df9ed9d30f5681dd148616ce81ba9b2e/apps/transport/client/javascripts/map.js#L18)
  * La route correspondante est [ici](https://github.com/etalab/transport-site/blob/master/apps/transport/lib/transport_web/api/router.ex#L27)
  * L'action précise est [quality ici](https://github.com/etalab/transport-site/blob/d53bd6fa0d397f1dca01f329bd29233c6db91f56/apps/transport/lib/transport_web/api/controllers/stats_controller.ex#L195)
  * J'active le pretty-printing JSON que j'ai ajouté sur https://github.com/etalab/transport-site/pull/1356/files
  * Je vois que la méthode [`features`](https://github.com/etalab/transport-site/blob/d53bd6fa0d397f1dca01f329bd29233c6db91f56/apps/transport/lib/transport_web/api/controllers/stats_controller.ex#L87-L102) va me permettre de "nettoyer" en commentant "geometry", puis en filtrant sur une seule AOM:

```elixir
    |> Enum.filter(fn aom -> !is_nil(aom.geometry) end)
    |> Enum.filter(fn aom -> aom.id == 310 end)
```
* Le code couleur rouge est lié (voir map.js "fatal") au champ `quality.error_level == "Fatal"`
* Ce champ est généré ici:

https://github.com/etalab/transport-site/blob/d53bd6fa0d397f1dca01f329bd29233c6db91f56/apps/transport/lib/transport_web/api/controllers/stats_controller.ex#L131

* Il n'est pas porté directement par la base (voir [définition du schema](https://github.com/etalab/transport-site/blob/master/apps/db/lib/db/aom.ex))
* Le champ provient de la méthode [`quality_features`](https://github.com/etalab/transport-site/blob/d53bd6fa0d397f1dca01f329bd29233c6db91f56/apps/transport/lib/transport_web/api/controllers/stats_controller.ex#L307)

**Comment by fchabouis** [comment]
j'aime bien l'enquête publique c'est cool :+1:
