### ISSUE TITLE
Downtime ce week-end sur dépassement de disque DB Postgres

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#1360]
Le site était down ; CleverCloud nous a alerté par email, et on a pu upgrader la DB à une taille supérieur après quelques échanges.

J'ai mis en place un monitoring via UpDown à titre personnel pour être prévenu plus tôt.

On creusera lundi sur ce qui s'est passé.

**Comment by antoine-de** [comment]
ahhh a vu de nez, on leak des validations :

la table des validation fait 76M

```sql
select octet_length(t.*::text) as l, t.id, t.resource_id  from validations as t order by l DESC limit 100;
```
ca donne :
```
   l     |   id   | resource_id 
----------+--------+-------------
 25284259 | 101846 |            
 16918237 | 102514 |       10391
 16132760 | 103076 |            
 13915914 |  61846 |            
 13566996 |  61845 |            
 13482643 |  61844 |            
 13413970 | 107815 |            
 13412061 |  61843 |            
 11888341 | 110330 |       12714
 11385510 | 101849 |            
 11114498 | 104949 |       10987
 10740469 | 101524 |       10248
 10723999 | 107822 |            
  9878487 | 113066 |       16189
  9670544 | 113647 |       16188
  8370257 | 109876 |            
  8201090 |  75460 |            
  6949182 | 106932 |            
  6913143 | 102608 |            
  6908337 | 106933 |            
  6810083 | 102530 |            
  6732949 | 102527 |            
  6670938 |  72665 |            
  6652518 | 102529 |            
  6522935 | 102797 |            
  6411146 | 102794 |            
  6174487 | 102528 |            
  5983435 | 106955 |            
  5869238 | 106957 |            
  5847598 | 106958 |            
  5759012 |  71657 |            
  5683323 | 106956 |            
  5592970 | 106564 |            
  5536588 | 106967 |            
  5433972 | 102795 |            
  5337764 | 106966 |            

```

**Comment by antoine-de** [comment]
ah non c'est peut etre juste les validation manuelles qui ne sont jamais effacées :thinking:

**Comment by antoine-de** [comment]
et a mon avis les validations prennent beaucoup trop de places pour être honnêtes, à mon avis on a du quadratique sur les validations d'arrêts proches

**Comment by antoine-de** [comment]
il faut qu'on cale un cron pour ne garder les validations qu'un certain temps (1 mois ?)

on a aussi des soucis au niveau du validateur qui est trop verbeu (je cale une requete sql, je suis trop fier d'avoir réussi à l'écrire :rocket: )

```sql
select close_stops->>'object_id', close_stops->>'details', json_array_length(close_stops->'related_objects') from ( select * from validations limit 1) as validations, json_array_elements(validations.details->'CloseStops') as close_stops;
```
```
-[ RECORD 1 ]-----+-----------------------------------------
?column?          | ORLEANS:StopArea:00046103
?column?          | distance between the stops is 7 meter(s)
json_array_length | 830
```

on a 830 objets reliés à l'erreur ca fait trop :stuck_out_tongue_winking_eye: 
je vais créer les issues sur les différents soucis

**Comment by thbar** [comment]
Il faut qu'on trouve aussi comment être prévenu (via Slack ou similaire) par la DB quand + de disons 70% de l'espace est occupé.

**Comment by thbar** [comment]
J'ai contacté CleverCloud pour leur demander si quelque chose chez eux permettrait d'être prévenu (par un push slack ou autre) lorsque la base dépasse un certain % d'occupation.

Au pire on pourra toujours implémenter ce que je fais souvent quand on n'a pas d'outillage: un endpoint HTTP (forme de healthcheck) avec du code custom pour calculer quelques métriques, et retourner un 500 (surveillé par Updown ou UptimeRobot) lorsqu'un check important ne passe pas.

**Comment by thbar** [comment]
Je clôture pour l'instant, pas de souci récent.
