### ISSUE TITLE
Mise en place de métriques ops minimales

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#1366]
On souhaite en premier lieu surveiller facilement (évolution dans le temps, et aussi alertes push avec un moyen ou un autre) l'occupation disque de la DB (voir #1360) ; pas simplement la taille des données, mais l'espace disque restant sur le volume DB également.

Je crée ce ticket pour lister des possibilités et commencer à réfléchir.

### Notes en vrac

* https://www.clever-cloud.com/doc/tools/metrics/#monitoring-metrics - métriques (en beta) chez CleverCloud
* [DataDog](https://www.datadoghq.com) est évoqué dans la doc [CleverCloud](https://www.clever-cloud.com/doc/clever-tools/lifecycle/)
* Une technique toute bête: un endpoint HTTP dans l'application, qui réalise quelques checks (quitte à aller lire les métriques CC par API, ou utiliser des fonctions comme `pg_database_size`), et qu'on surveille via des outils tiers comme [Updown](https://updown.io) ou [UptimeRobot](https://uptimerobot.com)
* Possibilité de hooker éventuellement telemetry et [Phoenix Live Dashboard](https://github.com/phoenixframework/phoenix_live_dashboard)

**Comment by NicolasBerthelot** [comment]
Fermeture temporaire
