### ISSUE TITLE
Mise à jour de plug_cowboy bloquante

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#1386]
J'étudie la mise en place de [new_relic_agent](https://hex.pm/packages/new_relic_agent) et je suis coincé par les mises à jour en attente (voir #1363):

```
$ mix deps.get
Failed to use "plug_cowboy" because
  apps/transport/mix.exs requires ~> 1.0
  new_relic_agent (versions 1.22.0 to 1.22.2) requires ~> 2.0
  phoenix (version 1.4.10) requires ~> 1.0 or ~> 2.0
  mix.lock specifies 1.0.0
```

Je vais voir comment faire, car il ne faut pas utiliser une version ancienne de l'agent, ce n'est jamais terrible pour ce type d'intégration.

**Comment by thbar** [comment]
Idem avec ecto.

**Comment by antoine-de** [comment]
arf, on peut avancer sur les mises à jour de lib du coup

**Comment by thbar** [comment]
Corrigé dans #1457
