### ISSUE TITLE
Erreurs remontées par la partie GBFS

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#1397]
Depuis #1390, nous recevons des alertes (assez nombreuses) rapportées par Sentry sur la partie GBFS:

https://sentry.data.gouv.fr/etalab/site/issues/1891760/

<img src="https://user-images.githubusercontent.com/10141/101334389-19804600-3878-11eb-8179-e1c25cf7e4b8.gif" width="350">

Si on regarde les [events](https://sentry.data.gouv.fr/etalab/site/issues/1891760/events/), à première vue les erreurs sont largement "Unable to read source file" (mais je pourrais en rater, Sentry ne fournit pas de vue pratique pour détailler tout ça, alors que Rollbar le permet, on verra si AppSignal est plus pratique):

En faisant une recherche dans le code on voit que ça arrive à deux endroits:

https://github.com/etalab/transport-site/blob/764559200a061096a0111d79ecfcd2e9ac66518c/apps/gbfs/lib/gbfs/controllers/jcdecaux_controller.ex#L73

qui correspond à `station_information` pour JC Decaux, et :

https://github.com/etalab/transport-site/blob/764559200a061096a0111d79ecfcd2e9ac66518c/apps/gbfs/lib/gbfs/controllers/jcdecaux_controller.ex#L101

qui correspond à `station_status` pour JC Decaux également.

La structuration du code ici:

https://github.com/etalab/transport-site/blob/764559200a061096a0111d79ecfcd2e9ac66518c/apps/gbfs/lib/gbfs/controllers/jcdecaux_controller.ex#L50-L54

fait qu'on perd en fait la cause originale (qui pourrait être un retour non 200, ou un JSON mal formaté, on ne peut pas statuer en l'état).

Quelques idées:
* Il serait pratique de logger davantage d'informations
* Peut-être qu'une levée d'erreur plus brute (sans chercher à la contrôler), et avoir un catch all derrière géré par plug ou phoenix, serait préférable, comme ça on aurait des erreurs bien différenciées, un stack trace etc

**Comment by antoine-de** [comment]
je suis partagé, l'idée de juste faire 

```elixir
    {:ok, %{status_code: 200, body: body}} = HTTPoison.get(rt_url(contract))
    {:ok, json} = Jason.decode(body)
```
et de catcher ca dans un plug est séduisant, mais je me demande si on améliore un poil le truc et qu'on chercher à retourner une 502, il faudrait commencer à surcharger la fonction`handle_error` et j'ai l'impression que ca couple des trucs assez éloignés

```elixir
  def handle_errors(conn, %{kind: _kind, reason: %MatchError{term: {:error, %HTTPoison.Error{}}}, stack: _stack} =p) do
    conn
    |> put_status(502)
    |> put_view(GBFS.ErrorView)
    |> render("error.json")
  end
  def handle_errors(conn, %{kind: _kind, reason: %MatchError{term: {:error, %Jason.DecodeError{}}}, stack: _stack} =p) do
    conn
    |> put_status(502)
    |> put_view(GBFS.ErrorView)
    |> render("error.json")
  end
  def handle_errors(conn, %{kind: _kind, reason: _, stack: _stack} =p) do
    IO.inspect(p)
    conn
    |> put_status(500)
    |> put_view(GBFS.ErrorView)
    |> render("error.json")
  end
```

(et faut gérer le XML vu que certaines app appellent du XLM)

En meme temps ca permet d'avoir à gérer ca qu'a un endroit.
T'as un avis @thbar ?

(Note: et sinon me suis rendu compte qu'on ne cachait pas les code retours, donc les 500 deviennent des 200 au 2eme appel, je vais corriger ca)
