### ISSUE TITLE
Bug identification temps-réel Grenoble

### ISSUE THREAD

**Issue by NicolasBerthelot** [etalab/transport-site#1417]
Un petit problème pour le dataset de Grenoble : 
https://transport.data.gouv.fr/datasets/horaires-theoriques-du-reseau-tag/

Le fichier .pbf du GTFS-RT a bien été intégré dans les ressources communautaires, il est bien identifié dans les formats contenus dans le fichier mais il n'est pas classé dans les fichiers temps-réel. Peut-être que ce problème affecte d'autres datasets.

**Comment by fchabouis** [comment]
Les ressources communautaires sont toujours dans la partie ressource communautaire sur notre site. Même si ce sont des GTFS ou des GTFS-RT. Je me demande surtout pourquoi le SMMAG a publié le temps réel en ressource communautaire plutôt qu'en ressource "officielle", ce qui lui permettrait d'apparaitre dans la bonne catégorie sur le PAN. Une idée @NicolasBerthelot ?

**Comment by NicolasBerthelot** [comment]
Parce qu'ils ont un autre dataset sur le temps-réel : https://data.metropolegrenoble.fr/ckan/ro/dataset/horaires-temps-reel-du-reseau-tag 
C'est un peu étrange parce qu'évidemment le GTFS-RT ne peut pas s'utiliser sans le GTFS. Je pense qu'ils considèrent que c'est plus clair de séparer. Le truc c'est que j'ai l'impression que c'est nous qui leur avions demandé de mettre le temps-réel en ressource communautaire. Mais bon ça fait beaucoup d'hypothèses tout ça... je vais contacter Frédérick Petit sur le sujet.

**Comment by NicolasBerthelot** [comment]
De toute manière le fichier de Grenoble n'est pas de bonne qualité selon Frédérick Petit
