### ISSUE TITLE
Pas de conversion GTFS > Netex dans le jeu de données de Mende 

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#1419]
Il n'y a pas la ressource communautaire Netex sur le jeu de données de Mende : Aucune erreur sur le GTFS qui est à jour

https://transport.data.gouv.fr/datasets/horaires-theoriques-et-temps-reel-du-reseau-transports-urbains-mendois-mende-gtfs-gtfs-rt/

**Comment by thbar** [comment]
Poke @antoine-de peut-être à faire en pairing ça, et que je récupère du coup les accès nécessaires.

**Comment by antoine-de** [comment]
en fait le GTFS n'a pas d'horaires de fin sur certaines courses, ce qui empeche les convertisseurs de faire leurs jobs.

On remonte ca en warning dans le validateur https://transport.data.gouv.fr/resources/8487#issues il faut qu'on augmente la sévérité de l'erreur vu que ca va bloquer les conversions.

**Comment by antoine-de** [comment]
corrigé avec https://github.com/etalab/transport-validator/pull/106

**Comment by fchabouis** [comment]
Je ferme l'issue du coup, il est normal que l'on ne puisse pas convertir.
