### ISSUE TITLE
La Marianne n'est plus à jour

### ISSUE THREAD

**Issue by IshanB** [etalab/transport-site#1420]
Dans le logo transport.data.gouv.fr, le logo Marianne n'est plus à jour : 
![image](https://user-images.githubusercontent.com/28890473/102889809-99eb9d00-445b-11eb-9bf0-76a56b30c360.png)

https://www.gouvernement.fr/charte/charte-graphique-les-fondamentaux/le-bloc-marque

**Comment by fchabouis** [comment]
Oh my goodness je préférais la version précédente, la nouvelle prend une place énoooorme pour un header. Je me demandais ce que venait faire ce gros logo avec sa devise républicaine sur 3 lignes sur le site mobile de météo france, je comprends mieux :)

**Comment by IshanB** [comment]
A titre d'inspiration, covoiturage a fait le move récemment :
https://covoiturage.beta.gouv.fr/
Et je ne sais pas si vous avez vu le nouveau template du design system de
l'Etat : un exemple <https://volontaires.fonction-publique.gouv.fr/>

*Ishan Bhojwani*



Le mar. 29 déc. 2020 à 10:57, Francis Chabouis <notifications@github.com> a
écrit :

**Comment by fchabouis** [comment]
Covoiturage n'a pas mis la devise républicaine d'ailleurs :)

Oui nous avons en tête que le design system a changé et que nous allons devoir le mettre à jour. Ce sera le prochain dossier une fois que la home sera réorganisée.

**Comment by IshanB** [comment]
Vous pouvez soit utiliser Liberté, égalité, fraternité, soit utilisé le
logo du ministère de la Transition soit le logo du ministère chargé des
transports (je pense qu'il faudrait voir avec Benoit pour déterminer lequel
est le plus pertinent)

*Ishan Bhojwani*



Le mer. 30 déc. 2020 à 10:38, Francis Chabouis <notifications@github.com> a
écrit :

**Comment by fchabouis** [comment]
Ca y est on est up-to-date.
