### ISSUE TITLE
Nouméa n'apparaît sur aucune carte de la page stats

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#1433]
Nouméa n'apparaît sur aucune carte de la page stat et il n'y a pas de couverture spatiale sur le jeu de données. 
Possibilité de faire apparaître dans la page des stats ? 

https://transport.data.gouv.fr/datasets/reseau-taneo-1/

**Comment by NicolasBerthelot** [comment]
Potentiellement remplacer Mayotte par Nouméa

**Comment by NicolasBerthelot** [comment]
Réglé par https://github.com/etalab/transport-site/pull/1682
