### ISSUE TITLE
Préciser les informations contenues dans les flux TR lorsqu'un flux en contient plusieurs

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#1435]
Peut on préciser les informations contenues dans les flux TR lorsqu'un flux en contient plusieurs comme on le fait pour le GTFS ? 
(avoir la possibilité de taper "avance/retard" dans la barre de recherche et tomber sur tous les JDD qui fournissent cette information par exemple)

**Comment by fchabouis** [comment]
On pourrait lors de l'import journalier aller voir le contenu du flux et mettre à jour des tags associés à la ressource.

**Comment by NicolasBerthelot** [comment]
Cf. #1852

**Comment by thbar** [comment]
Sujet à nouveau d'actualité car @AntoineAugusti et moi travaillons à décoder du GTFS-RT actuellement.

En tant que réutilisateur, je cherchais quels sont les flux qui contiennent des "vehicle positions". J'ai utilisé du code et donc pas de souci, mais pour un utilisateur plus final ça peut être embêtant en terme de découvrabilité je pense, surtout vu que c'est un format binaire.

On pourrait avoir le fonctionnement suivant:
- quelques fois par jour, on passe sur tous les flux GTFS-RT, et on compte combien d'entité il y a de chaque type (vehicle positions, service alerts etc)
- on note en base cette stat (très simple: id de la ressource, et un tableau JSON avec la liste des types, ou avec les counts en plus éventuellement si on veut de la donnée un peu plus riche)
- au moment de l'affichage de la page détail, il suffit de piocher dans cette liste sur disons les 7 derniers jours, et de voir ce qui apparaît
- on peut ainsi auto-tagger la ressource (en expliquant au public comment on calcule ça)
- si on veut, on peut même effacer la donnée après quelques temps (mais ça sera minuscule comme data, donc on pourrait même tout garder)

**Comment by thbar** [comment]
C'est fait à présent pour le GTFS-RT.
