### ISSUE TITLE
Améliorer la gestion des permissions sur le blog

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#1448]
Comme vu dans #1447, il y a une interface d'admin pour faciliter le travail sur le blog (review etc).

Je vois que ce dashboard admin (https://blog.transport.data.gouv.fr/admin/#/) est directement géré par Netlify.

Voici ce qui est affiché si on tente de se connecter:

<img width="553" alt="CleanShot 2021-01-05 at 10 17 45@2x" src="https://user-images.githubusercontent.com/10141/103628427-47bc7880-4f3f-11eb-844a-74f2a996d941.png">

Deux points sont à noter :
- La demande d'accès aux "repositories private" n'est pas motivée par un besoin réel, et en tout cas trop large. Dans mon cas par ailleurs, cela poserait problème car j'ai des repository private "sensibles".
- Le fait d'utiliser un compte personnel comme propriétaire de l'application créera du travail au moment du départ de la personne (quel que soit le sujet d'ailleurs)

J'ai l'impression aussi (à vérifier) que toute la donnée nécessaire est déjà publique (branche `blog`, répertoire `/blog`).

Pour terminer, si je regarde la documentation Netlify [Repository permissions and linking](https://docs.netlify.com/configure-builds/repo-permissions-linking/), j'ai l'impression qu'on devrait être en mesure de ne connecter qu'un seul repository avec des droits "scopés", mais c'est à vérifier, et je ne sais pas si le fait d'utiliser un compte personnel Netlify bloque peut-être ce point !

Pour prise de note, à revisiter.

**Comment by fchabouis** [comment]
Il y a l'app Netlify qui a besoin d'accéder au repo pour déployer le site. C'est ce dont parle la doc que tu indiques. Sur ce point, la demande d'accès est bien scopée au repo transport-site uniquement :+1: 

Ensuite il y a l'oauth Github de la partie admin du site qui demande elle d'avoir accès à la terre entière. Je n'ai pas trouvé pour le moment comment réduire le scope des demandes. J'ai posé la question [ici](https://answers.netlify.com/t/netlify-cms-requests-excessive-github-access-rights/48529).

**Comment by thbar** [comment]
Merci d’avoir enquêté !

On a eu une réponse ; il faut suivre https://github.com/netlify/netlify-cms/issues/4329

— Thibaut

**Comment by fchabouis** [comment]
J'ai commencé à regarder la semaine dernière pour changer completement de méthode d'identification, et passer du compte github à mail + mdp, ce qui devrait résoudre le problème. Parce qu'en l'état, il semble que le Oauth Github ne permette pas de scoper les demandes de droits (pb côté Github, pas côté Netlify).

**Comment by thbar** [comment]
J'ai fait un test, ça reste d'actualité ; je ne peux pas autoriser du fait de l'usage des repo privés. J'ai remis une couche de l'autre côté.

En l'état on s'en sort toutefois (il "suffit" que je ne me connecte pas, je crois être le seul à être dans un cas problématique recensé), je pense qu'on peut clôturer pour diminuer notre charge cognitive, et attendre que ça évolue naturellement.
