### ISSUE TITLE
Cacher les ressources communautaires générées par le PAN

### ISSUE THREAD

**Issue by antoine-de** [etalab/transport-site#1452]
Les ressources communautaires sont mélangées avec les ressources générées par le PAN.
L'idée serait de mieux mettre en valeur les Geojson / NeTEx / Siri lite tout en allégeant la page.

* On n'affiche plus les ressources communautaires qui ont un `community_resource_publisher` == "Point d'Accès National transport.data.gouv.fr"
* On filtre complètement les ressources générées (en se basant sur la présence de `original_resource_url` ?)
  - et on améliore l'encart de la ressource pour mieux mettre en valeur qu'il y a d'autres format dispo
  
![image](https://user-images.githubusercontent.com/3987698/103910143-66b43980-50fc-11eb-8a81-4d81a475078a.png)

(il faut trouver la bonne manière de faire ca)

* pour les autres ressources du PAN (genre les SIRI Lite, ou si un jour on cale à la main des ressources communautaires), on les traite comme les ressources 'officielles' (avec un encart dédié dans la section appropriée) mais peut être avec une icône du PAN pour les différencier un peu ?

Il faudra aussi améliorer les encarts des données autre que GTFS (qui sont assez vides pour le moment), et notamment celle du SIRI-Lite, mais il me semble que c'est une autre issue.

**Comment by NicolasBerthelot** [comment]
Cette solution n'a pas été retenue par l'équipe, on conservera l'espace "ressources communautaires"
