### ISSUE TITLE
Amélioration de la barre de navigation à gauche de la page /dataset

### ISSUE THREAD

**Issue by antoine-de** [etalab/transport-site#1453]
On pourrait un peu améliorer la barre de navigation de la page /dataset

![image](https://user-images.githubusercontent.com/3987698/103907434-2d2dff00-50f9-11eb-82df-cd815c5e4cc7.png)

Il faut ajouter 
* des sous sections à `Ressources` avec pour chaque section (#1451) (théoriques, temps réel, ...), un décompte du nombre de ressources. 
* le nombre de messages dans l'espace commentaires
* le nombre de fichiers dans l'historique

**Comment by fchabouis** [comment]
une bonne première à laquelle se frotter @andlio

**Comment by thbar** [comment]
@fchabouis j'ai fait un label "good-first-issue" pour info ! On verra si ça sert longtemps ou pas, mais ça permet de trier, si on en fait d'autres.
