### ISSUE TITLE
Rendre la Recherche sur le PAN plus flexible : permettre des erreurs dans le noms des AOM/réseaux

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#1464]
Rendre la barre de recherche sur le PAN plus "flexible" en permettant des marges d'erreur dans les noms des AOM/réseaux

ex : si j'ai écrit Auxxerois au lieu d'Auxerrois, je tombe quand même sur le jeu de données
Actuellement ça renvoie vers : "0 résultat pour "auxxerois"

**Comment by thbar** [comment]
Eléments techniques:
- Voilà un article de "fuzzy matching" dont on pourra s'inspirer https://info.crunchydata.com/blog/fuzzy-name-matching-in-postgresql
- La recherche est actuellement un peu coûteuse (voir #1520)
- Le code de la recherche est ici:

https://github.com/etalab/transport-site/blob/1b55ee9843fc1eaacbf09096d798b7eea1574a59/apps/transport/lib/transport_web/api/controllers/places_controller.ex#L23

**Comment by thbar** [comment]
Liens intéressants:
- https://elixirstream.dev/tips/32e059eb-038c-4cb8-8e0b-ce8ffbdaae8a
- https://github.com/etalab/transport-site/issues/1490
- https://github.com/etalab/transport-site/issues/1535

**Comment by NicolasBerthelot** [comment]
ça vaudrait le coup d'être relancé !
