### ISSUE TITLE
Import de données stoppé à mi-parcours

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#1465]
En enquêtant sur #1459 avec @antoine-de, nous nous sommes rendu compte de différents soucis sur l'import.

Je crée ce ticket pour tout regrouper pour l'instant:

### Crash import Pays de la loire

Il semblerait que l'import du dataset [Pays de la loire](https://transport.data.gouv.fr/datasets/arrets-horaires-et-circuits-des-lignes-de-transports-en-commun-en-pays-de-la-loire-gtfs) plante.

En paginant sur les logs CleverCloud (TODO: publier le script), on voit que les imports ne terminent pas et s'arrêtent à ces datasets:

```
2021-01-21T10:19:22.069Z: 10:19:09.389 [info] Importing dataset 5fe368d417a49c5d305bd291 (url = https://www.data.gouv.fr/api/1/datasets/5fe368d417a49c5d305bd291/)
2021-01-21T10:19:22.069Z: 10:19:09.353 [info] Importing dataset 5ddf87a06f44412ad1c3b8b9 (url = https://www.data.gouv.fr/api/1/datasets/5ddf87a06f44412ad1c3b8b9/)
2021-01-21T10:19:22.070Z: 10:19:13.751 [info] Importing dataset 5530fbacc751df5ff937dddb (url = https://www.data.gouv.fr/api/1/datasets/5530fbacc751df5ff937dddb/)
2021-01-21T10:19:22.070Z: 10:19:15.221 [info] Importing dataset 5e32227c06e3e70513320bbd (url = https://www.data.gouv.fr/api/1/datasets/5e32227c06e3e70513320bbd/)
2021-01-21T10:19:22.070Z: 10:19:15.164 [info] Importing dataset 5d92106b6f44410c30fee9ca (url = https://www.data.gouv.fr/api/1/datasets/5d92106b6f44410c30fee9ca/)
```

On a retrouvé le suivant en base, il s'agit des pays de la loire (5e32227c06e3e70513320bbd).

En relançant en local on voit effectivement des erreurs qui font a priori planter le pool de DB Ecto.

### Arrêt de la chaîne de traitement

On ne vois plus de log après ce moment, et nous pensons que la chaîne de traitement est interrompue:

https://github.com/etalab/transport-site/blob/bd2adc5441669f49e7bb033f4d4c89185432642c/apps/transport/lib/transport/import_data.ex#L21-L27

Wrapper l'appel à `import_dataset` avec une notification Sentry devrait permettre d'être prévenu et aussi de continuer les traitements.

### Chaîne de validation à améliorer

A priori la validation est soumise au même souci potentiel:

https://github.com/etalab/transport-site/blob/bd2adc5441669f49e7bb033f4d4c89185432642c/apps/transport/lib/transport/import_data.ex#L47-L55

### Configuration Sentry

Sentry est normalement configuré pour remonter les crashs de processes:

https://github.com/etalab/transport-site/blob/bd2adc5441669f49e7bb033f4d4c89185432642c/config/config.exs#L50-L53

comme recommandé dans la doc https://docs.sentry.io/platforms/elixir/

Toutefois ça semble inopérant, peut-être en lien avec #1375.

**Comment by antoine-de** [comment]
pour donner un peu plus de détail, l'erreur est:
```
[error] ** (DBConnection.ConnectionError) tcp recv: closed (the connection was closed by the pool, possibly due to a timeout or because the pool has been terminated)
```

lancée par https://github.com/etalab/transport-site/blob/master/apps/transport/lib/transport/import_data.ex#L91:L91

**Comment by thbar** [comment]
J'ai requêté en base et on voit que 113 datasets ont eu leur dernier import le 19, 309 le 20:

```sql
with latest_logs as (
	select distinct on (dataset.id)
	/*	dataset.id, dataset.title, log.id, date(log.timestamp), log.is_success*/
		date(log.timestamp)
	from
		dataset
		inner join
		logs_import as log on log.dataset_id = dataset.id
	order by dataset.id, log.timestamp desc
)

select date, count(*) from latest_logs group by date
```

Result is:

| date       | count |
|------------|-------|
| 2021-01-19 |   113 |
| 2021-01-20 |   309 |

**Comment by thbar** [comment]
J'ajouterai plus tard une requête pour tracer le nombre de datasets importés par jour.

**Comment by thbar** [comment]
Sur un test unitaire avec `async_stream_nolink`, une exception en milieu de traitement ne stoppe pas le traitement, en pratique. Peut-être que le crash du pool affecte le process du dessus, il faudra que j'enquête.

**Comment by thbar** [comment]
Pour le commentaire du dessus, voir demo:

```elixir
  def some_function(item) do
    IO.puts("Yes #{item}")

    if item == 5 do
      IO.puts("Raising...")
      raise "STOP"
    end
  end

  @tag :focus
  test "stuff" do
    ImportTaskSupervisor
    |> Task.Supervisor.async_stream_nolink(1..10, &some_function/1,
      max_concurrency: 1,
      timeout: 180_000
    )
    |> Enum.to_list()
  end
```

Qui donne en sortie:

```
Yes 1
Yes 2
Yes 3
Yes 4
Yes 5
Raising...
Yes 6
Yes 7
Yes 8
Yes 9
Yes 10
```

**Comment by thbar** [comment]
J'ai implémenté un outil d'extraction de logs dans #1470, et ça me permet ce matin de relancer une analyse de logs:

```
$ mix clever.logs --since "2021-01-26T04:00:00Z" --before "2021-01-26T06:00:00Z" --alias "transport-site" | tee import.log
```

La commande `$ cat import.log | cut -c1-18 | uniq -c` me permet de vérifier qu'il n'y a pas de "trous" dans les logs comme précédemment.

Je vois du coup que cette nuit, l'import n'a pas crashé en plein vol:

```
$ cat import.log | grep "reimported"
2021-01-26T04:35:34.977Z: 04:35:34.632 [info] all datasets have been reimported (55 failures / 423)

$ cat import.log | grep "Importing" | grep -v "request_id" | wc -l
     427
```

Le problème reste à traiter toutefois, mais on voit qu'on a quand même du temps.

**Comment by thbar** [comment]
On reste sur 55 datasets qui ne s'importe pas, le reste semble stable ; il va falloir enquêter:

```
2021-02-21T04:00:00.429Z: 04:00:00.003 [info] reimporting all datasets
2021-02-21T04:29:49.886Z: 04:29:49.587 [info] all datasets have been reimported (55 failures / 428)
```

```
$ cat import-2021-02-21.log | grep "Unable to import data of dataset" | wc -l
      55
```

Je vois aussi quelque chose de similaire sur les validations:

```
$ cat import-2021-02-21.log | grep "Unable to validate resource" | wc -l
      54
```

Pour info @fchabouis

**Comment by thbar** [comment]
Avec #1595, ça donne un meilleur suivi, et le crash général ne se produit plus, donc je clôture.
