### ISSUE TITLE
Erreurs d'imports marquées en "success"

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#1471]
Le code d'import réalisé ici se fait sans `!`:

https://github.com/etalab/transport-site/blob/b39aa6463e29d30e63594dac338dff33a8cbdee8/apps/transport/lib/transport/import_data.ex#L91

Du coup si l'opération échoue (et c'est le cas comme je l'ai vu sur #1465 avec un jeu de données), un rollback est réalisé.

Pour autant, le log de succès est créé malgré tout (avant ce call).

Je note pour que nous pensions à corriger ce point.

**Comment by thbar** [comment]
Un exemple de souci de ce type est je pense le point remonté par @Miryad3108 aujourd'hui:

![Uploading CleanShot 2021-02-08 at 17.22.56@2x.png…]()

**Comment by NicolasBerthelot** [comment]
Est-ce toujours le cas @fchabouis ?

**Comment by fchabouis** [comment]
C'est bon c'est corrigé depuis le refactoring de l'import. L'update se fait bien avec un !, et en cas d'erreur, on logue un échec :+1: 

https://github.com/etalab/transport-site/blob/d73662ffe5ddd5492d41b6a0ad12b1c6f3b43118/apps/transport/lib/transport/import_data.ex#L135-L135
