### ISSUE TITLE
Petite régression LiveView ?

### ISSUE THREAD

**Issue by fchabouis** [etalab/transport-site#1475]
Je mets ça là pour ne pas oublier, à confirmer, mais il me semble qu'auparavant, dans le backoffice, lorsque l'on cliquait sur "valider" un dataset, nous avions un loader qui s'affichait dans le bouton avec LiveView et qui arretait de tourner une fois la validation faite. 

Ca n'a plus l'air de marcher.

Peut-être lié aux mises à jour récentes des versions de Elixir/Phoenix/LiveView ?

![image](https://user-images.githubusercontent.com/15341118/105973885-8dc3b280-608d-11eb-9412-c17b11f200df.png)

**Comment by thbar** [comment]
Merci pour le signalement ! J'avais testé cette partie durant la dernière upgrade (https://github.com/etalab/transport-site/pull/1431) mais il y a peut-être des trous dans la raquette.

Je regarderai jeudi.

**Comment by thbar** [comment]
@fchabouis chez moi ça a l'air de marcher :

![CleanShot 2021-01-28 at 15 58 14](https://user-images.githubusercontent.com/10141/106156321-ab724400-6181-11eb-85a6-68db5b757edc.gif)

Peux-tu vérifier si tes assets npm sont bien à jour ? L'upgrade de LiveView comporte une mise à jour d'un package npm associé, voilà les versions chez moi:

```
$ yarn --cwd apps/transport/client/ list | grep phoenix
├─ phoenix_html@2.14.3
├─ phoenix_live_view@0.14.0
├─ phoenix@1.4.17
```

Il y a un test unitaire en place pour vérifier ce point également:

```
mix test apps/transport/test/build_test.exs:37
```

https://github.com/etalab/transport-site/blob/dcd5f027cfb50710bf33c062decd123c7a8de18c/apps/transport/test/build_test.exs#L36-L47

Si ça ne marche toujours pas après ces vérifications, on enquêtera !

**Comment by fchabouis** [comment]
J'ai les mêmes versions que toi, j'ai relancé un `mix yarn install`, mais j'ai toujours le problème.

Faudra que je prenne le temps de creuser un peu plus.

**Comment by thbar** [comment]
Ok on pourra regarder ensemble à un moment si tu veux. Peut-être que la console javascript indique quelque chose ?

**Comment by thbar** [comment]
On a testé hier sur #1457 et on ne retrouve pas le problème. Je ferme pour l'instant.
