### ISSUE TITLE
Le changeset AOM n'est disponible que dans une tâche mix (?)

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#1478]
En travaillant sur #1477 et #1465, j'ai remarqué qu'un changeset pour les AOM est déclaré ici:

https://github.com/etalab/transport-site/blob/dcd5f027cfb50710bf33c062decd123c7a8de18c/apps/transport/lib/mix/tasks/transport/import_aom.ex#L45-L46

Du coup cela explique peut-être pourquoi je ne parviens pas à faire d'insert d'un dataset avec son AOM à la volée.

J'ouvre le ticket pour penser à voir s'il faut refactorer ce point.

**Comment by antoine-de** [comment]
hum les AOM sont un référentiel un peu figé, la c'est la tache Mix pour les importer quand elles changent (une fois par an ou tout les 2 ans). Normalement tu ne dois jamais rajouter d'AOM, juste te rattacher à une AOM existante

**Comment by thbar** [comment]
Merci pour la réponse ! Pour ajouter un peu de contexte, mon but est de créer une AOM en test facilement, et qu'elle soit bien valide au niveau des différents champs.
