### ISSUE TITLE
Changer logo Kisio dans Réutilisateurs 

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#1481]
![KISIO_DIGITAL](https://user-images.githubusercontent.com/59559301/106571294-429b1b00-6537-11eb-83c6-b61f32287713.png)

**Comment by thbar** [comment]
Traité via https://github.com/etalab/transport-site/pull/1483. @Miryad3108 pourras-tu jeter un oeil et valider ?

Je ferme ici du coup. Merci !
