### ISSUE TITLE
Quelques textes en français sur la nouvelle home version anglaise

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#1486]
Suite au déploiement de la nouvelle home (#1467) @NicolasBerthelot remonte quelques textes non traduits.

![image (2)](https://user-images.githubusercontent.com/10141/106869620-6fcf0100-66d0-11eb-8450-bb3b1e99eb5f.png)

![image (3)](https://user-images.githubusercontent.com/10141/106869629-72c9f180-66d0-11eb-9e7b-3d0a4cb615a0.png)

**Comment by thbar** [comment]
Le code correspondant est ici:

https://github.com/etalab/transport-site/blob/de72bf362d1162fd1b919c87d8d09e0460f642d2/apps/transport/lib/transport_web/templates/page/index.html.eex#L58-L76

**Comment by NicolasBerthelot** [comment]
Issue réglée par : https://github.com/etalab/transport-site/pull/1672
