### ISSUE TITLE
Nouveau réutilisateur : Les Voitures.fr

### ISSUE THREAD

**Issue by NicolasBerthelot** [etalab/transport-site#1488]
Un nouveau réutilisateur à ajouter à notre liste : 

https://lesvoitures.fr/

![Logo HD](https://user-images.githubusercontent.com/61453166/106916298-49788800-6707-11eb-8a55-2fad2a7a2eb6.png)

**Comment by NicolasBerthelot** [comment]
Et c'est notable de voir que le logo ne correspond pas à l'URL

**Comment by thbar** [comment]
Ah oui effectivement https://lesvoitures.com redirige vers https://lesvoitures.fr. Je vais voir pour l'ajouter.

**Comment by thbar** [comment]
@NicolasBerthelot c'est bon j'ai géré après retaillage et compression du logo.

<img width="541" alt="CleanShot 2021-02-04 at 17 36 13@2x" src="https://user-images.githubusercontent.com/10141/106924579-7cbf1500-670f-11eb-9b4f-85f835ea29af.png">
