### ISSUE TITLE
Une recherche sur la ville de Niort ramène des datasets sans relation avec la recherche (?)

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#1490]
Si on cherche par ville "Niort", on tombe sur:

https://transport.data.gouv.fr/datasets/commune/79191

qui contient:

<img width="1229" alt="CleanShot 2021-02-04 at 18 26 44@2x" src="https://user-images.githubusercontent.com/10141/106931147-8c8e2780-6716-11eb-80f6-fd5312d49163.png">

Ca paraît incorrect.

**Comment by NicolasBerthelot** [comment]
C'est lié au fait que lorsqu'on recherche une commune on obtient des résultats sur la commune et sa région. Ce n'est pas absurde en soit mais il faudrait envisager une priorisation des datasets qui ferait remonter d'abord les datasets de la commune. Un autre problème vient du fait que souvent les données de transports régionaux sont publiés par département et du coup dans la nouvelle aquitaine et ses nombreux départements ça fait beaucoup de datasets qui n'ont rien à voir avec la commune...
