### ISSUE TITLE
Étudier comment remettre en place + de sanitisation HTML

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#1493]
Détecté par @fchabouis (https://github.com/etalab/transport-site/pull/1492#pullrequestreview-585359920) - la PR https://github.com/etalab/transport-site/pull/1348 corrigeait des erreurs 500 en production en mode hot-fix (les sanitisations échouaient).

Il faudra étudier l'historique du fichier https://github.com/etalab/transport-site/commits/b90f47661199c2e09447ead8f60b3d1c85ad3344/apps/transport/lib/transport_web/views/dataset_view.ex.

On devrait sûrement faire un "scan de masse" (j'ai déjà eu à faire ça sur ce type de sujet) pour détecter ce qui ne va pas avec les données en local.

**Comment by fchabouis** [comment]
fermé par #1659
