### ISSUE TITLE
Download datasets

### ISSUE THREAD

**Issue by maukoquiroga** [etalab/transport-site#152]
[Check this theme in the roadmap](https://trello.com/c/6ElVjoST/11-reusers-quickly-download-datasets)

**Definition of done**

- [x] I can see a prominent link or button to download a dataset in datasets list
- [x] I can see a prominent link or button to download a dataset in dataset details

**Mockup**

![img_8685](https://user-images.githubusercontent.com/329236/33212923-6fc9b842-d125-11e7-98ef-3504b8b5ba2c.jpg)

**Comment by Tristramg** [comment]
Closing as already implemented.
