### ISSUE TITLE
Requêtes à optimiser

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#1520]
Durant un test de charge (#1502 et en particulier https://github.com/etalab/transport-site/issues/1502#issuecomment-783504607) j'ai vu que certains points de l'application pouvaient "chauffer" davantage que d'autres, je les note donc pour optimisation plus tard:

- [ ] Recherche full text https://transport.data.gouv.fr/api/places?q=l (SQL à optimiser)
- [x] Statistiques carte https://transport.data.gouv.fr/api/stats/quality (cache à 30 secondes)
- [x] Statistiques carte https://transport.data.gouv.fr/api/stats/regions (cache à 30 secondes)
- [x] La home page est gourmande (19 queries SQL) sur le chargement des tuiles (qui pourraient être mis en cache facilement)

**Comment by thbar** [comment]
L'essentiel a été traité dans #1530. La partie recherche full-text sera couverte dans #1464 plus tard.

**Comment by fchabouis** [comment]
Je ferme car j'ai l'impression que la partie full-text ne pose pas de problème (c'était la dernière case à cocher de l'issue).

Avec des résultats exacts :
![image](https://user-images.githubusercontent.com/15341118/129541706-237fdfc6-30ab-4a09-a91e-51394f56a630.png)

Avec des résultats approximatifs :
![image](https://user-images.githubusercontent.com/15341118/129541774-d7c36893-8640-40f6-9f1d-9d087bdefb9c.png)
