### ISSUE TITLE
Erreurs JDD de Cluses détecté par notre validateur et pas sur celui de Google 

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#1521]
Notre validateur détecte des erreurs sur ces 4 arrêts 
https://transport.data.gouv.fr/resources/11610?issue_type=InvalidReference#issues

ça peut être dû au fait que dans le fichier stop_times il y a un espace entre la fin du nom de l'arrêt et la virgule alors qu'il n'y a pas d'espace dans le fichier stop et inversement ?

**Comment by fchabouis** [comment]
Hello, tout à fait, les chaînes de caractères entre les virgules sont comparées, et si d'un côté il y a un espace en plus ça ne colle pas. Je ne trouve pas ça choquant que le validateur refuse cela, un espace en plus c'est un espace en plus :P
