### ISSUE TITLE
Nouvelle fonctionnalité "admin" - Transvaser historique 

### ISSUE THREAD

**Issue by NicolasBerthelot** [etalab/transport-site#1523]
Il arrive régulièrement qu'un producteur de données change sa méthode de publication qui a pour conséquence d'utiliser un nouveau jeu de données sur data.gouv.fr. Dans ce cas là nous nous référençons le nouveau jeu de données et déréférençons l'ancien pour éviter de référencer des données périmées. Cela a pour principal désavantage de perdre l'éventuel historique de fichiers GTFS qui avait été collecté durant l'existence de l'ancien mode de publication.

Il serait très intéressant de pouvoir faire "hériter" à un jeu de données l'historique des fichiers publiés à nouveau jeu de données.

**Comment by thbar** [comment]
(voir #1522 qui documente le fonctionnement actuel de l'historisation)

**Comment by thbar** [comment]
Vu avec @Miryad3108, pourrait être utile.

Sujet un peu compliqué : par exemple si on imagine qu'un producteur passe d'un jeu de données hébergé chez data gouv à un lien auto-porté chez eux, ça crée un nouveau jeu, et le lien peut être compliqué à faire.

Note @thbar : je pense qu'il faudrait tracer dans le temps les créations et suppressions d'un jeu de données, puis il faudrait gérer également le fait que l'ancienne page sera parfois archivée.

Pas mal de questions sous-jacentes, on garde ouvert pour le moment.

**Comment by thbar** [comment]
@Miryad3108 si la prochaine fois qu'un producteur change de méthode, tu peux partager ici les éléments (avant/après), on pourra aller faire un peu de recherche R&D pour comprendre ce qu'on pourrait faire pour améliorer la situation sur un cas concret.

Peut-être qu'avoir une info à la création d'une ressource, qui précise que ça va remplacer une autre, nous permettrait d'aller chercher les éléments d'historique de l'ancienne ressource, même si cette dernière n'est plus dispo / 404 etc.

**Comment by fchabouis** [comment]
(On peut maintenant si besoin rapatrier un historique à la main )

**Comment by fchabouis** [comment]
J'ai l'impression qu'un bon angle pour résoudre le problème est en fait d'autoriser dans le BO de modifier l'URL data.gouv d'un dataset existant et de faire en sorte que notre dataset_id interne ne change pas lors de l'opération. On garde alors naturellement l'historique du dataset, tandis que tout le reste (discussions, ressources communautaires) est mis à jour.

**Comment by fchabouis** [comment]
fait avec #2913
