### ISSUE TITLE
Page dataset : mieux gérer l'affiche (ou non) de la visu

### ISSUE THREAD

**Issue by fchabouis** [etalab/transport-site#1524]
Par exemple https://transport.data.gouv.fr/datasets/parkings-lyon-parc-auto-de-la-metropole-de-lyon-donnee-obsolete/ a un format a lui, et l'affichage de la carte plante.

Il faudrait que si on n'arrive pas à lire le fichier, rien ne s'affiche.

**Comment by thbar** [comment]
Idée: afficher une note comme quoi on a cherché à afficher quelque chose, mais qu'on n'y parvient pas ? Peut-être que ça facilitera la remontée de problèmes si on veut enrichir mieux ces zones petit à petit.

**Comment by fchabouis** [comment]
J'ai fait ça il y a quelques temps, normalement c'est reglé
