### ISSUE TITLE
Say I'm reusing a dataset

### ISSUE THREAD

**Issue by maukoquiroga** [etalab/transport-site#153]
[Check this theme in the roadmap](https://trello.com/c/JFNUjseO/9-reusers-say-theyre-reusing-data)

**Definition of done**

- [ ] I can click somewhere to say we're using the dataset
- [ ] I understand why I need to log in / create a data.gouv.fr account
- [ ] I can see my company's logo in landing page

**Mockup**

![img_8685](https://user-images.githubusercontent.com/329236/33212923-6fc9b842-d125-11e7-98ef-3504b8b5ba2c.jpg)

**Comment by sabinesafi** [comment]
Pour l'instant le fonctionnement actuel via data.gouv.fr me semble suffisant. On aura plus de retours sur ça dans quelques jours quand nos réutilisateurs auront commencé à déclarer des réutilisations.

**Comment by Tristramg** [comment]
Je propose de fermer cette issue. Quitte à revenir avec des issues plus spécifiques selon les retours.
