### ISSUE TITLE
Mise en place de backups hors-site

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#1548]
Lors de nos réflexions portant sur le plan de continuité, il est apparu qu'il serait peu coûteux et utile d'avoir des backups chiffrés hors-site (chez un autre hébergeur), pour éviter le type de problème qui est remonté suite à l'incendie de Strasbourg (rien qu'autour de moi, j'ai des cas portant sur l'impossibilité pratique d'accéder aux backups suite à des soucis de panel, ou encore la perte pure et simple de backups malgré la mise en place d'une offre de backup spécifique).

Je vais donc mettre en place des backups hors-site, probablement chez Scaleway.

Un collègue (@paduc) m'a indiqué:

> je suis en train de voir avec Clever Cloud pour avoir accès aux backups de bases de données de manière programmatique (actuellement elles sont dispo dans l'interface admin), afin de les envoyer périodiquement sur un hébergement distant. C'est une feature qui n'est pas publique mais qui est disponible sur demande !

#### Option 1 (<- option retenue au final, peu de développement)

L'option 1 consiste à activer (pour 50€ réglé une fois) une option qui copie les backups vers un Cellar (S3). À partir de là il suffit de créer un cron et un upload vers la destination.

J'ai échangé avec CleverCloud et voici quelques informations:
- coût de mise en place 50€ pour les deux add-ons (production et staging)
- les backups seront déposées dans un cellar dédié qui vous sera bien entendu accessible. Mais toutes les backups arriveront dans un seul cellar de destination.

#### Option 2

L'option 2 consiste à activer chez CC un accès programmatique, qui donnera lieu à une authentification OAuth (https://www.clever-cloud.com/doc/extend/cc-api/#authentication).

À partir de là il faudra utiliser la route `/v2/backups/<user_id|orga_id>/<addonid>` via la méthode GET.

### Tâches prévues

- [x] Demander à Clever Cloud ce qui est disponible en terme d'outillage automatisé
- [ ] Voir comment procéder à un dump chiffré automatique depuis CC
- [ ] Voir comment créer un bucket S3 privé écriture seule sur le nouveau compte Scaleway
- [ ] Tester sur le staging
- [ ] Tester sur la production
- [ ] Activer un petit outil de suivi (voir https://updown.uservoice.com/forums/177972-general/suggestions/5586072-periodic-task-cron-monitoring pour les options)
- [ ] Faire une restauration à partir de zéro pour vérifier le round-trip
- [ ] Voir comment on peut restaurer régulièrement (cela pourrait passer par une restauration automatique sur le staging)

**Comment by thbar** [comment]
Le backup réalisé dans le bucket ne garde que les 7 derniers jours, je viens de le constater.

**Comment by AntoineAugusti** [comment]
@thbar On a déjà des credentials côté Scaleway ? Tu pourrais me transmettre ça ?

J'arrive déjà à accéder aux backups sur le Cellar dédié. Je me suis sauvegardé les credentials dans mon password manager pour accéder aux backups en cas d'indisponibilité du panel.

```
$ s3cmd -c /tmp/s3cfg ls                                                                                                  
2021-03-16 10:23  s3://ccbackups-postgresql-4a305f24-8a31-4815-b2bb-23f4711303ee
2021-03-16 10:24  s3://ccbackups-postgresql-a4f9fbc8-1a10-4acb-934b-b52e4986e1cf

$ s3cmd -c /tmp/s3cfg get s3://ccbackups-postgresql-4a305f24-8a31-4815-b2bb-23f4711303ee/postgresql_4a305f24-8a31-4815-b2bb-23f4711303ee-20211109022621.dump .
download: 's3://ccbackups-postgresql-4a305f24-8a31-4815-b2bb-23f4711303ee/postgresql_4a305f24-8a31-4815-b2bb-23f4711303ee-20211109022621.dump' -> './postgresql_4a305f24-8a31-4815-b2bb-23f4711303ee-20211109022621.dump'  [1 of 1]
 22628039 of 22628039   100% in    1s    13.02 MB/s  done
 ```

**Comment by thbar** [comment]
> On a déjà des credentials côté Scaleway ? Tu pourrais me transmettre ça ?

@AntoineAugusti je n'ai qu'un compte perso pour l'instant. Il faudrait voir comment on gère, et comment on met la carte bleue (et laquelle) là dedans, pour se créer un vrai "compte de groupe".

> J'arrive déjà à accéder aux backups sur le Cellar dédié. Je me suis sauvegardé les credentials dans mon password manager pour accéder aux backups en cas d'indisponibilité du panel.

Super ; j'ai fait pareil il y a quelques temps pour les mêmes raisons :-)

**Comment by AntoineAugusti** [comment]
Posé la question suivante à Clever.

---
Je vous contacte à propos de sauvegardes de bases de données. Actuellement, nous avons des sauvegardes de notre base de données PostgreSQL dans un addon Cellar.

Je me pose les questions suivantes :

• quelle est la disponibilité, durabilité de Cellar ?
• le stockage est-il sur plusieurs zones de disponibilité ?
• répliqué de quelle façon ?
• est-il possible de choisir plusieurs zones de déploiement de sauvegardes ?
• la meilleure solution est-elle de répliquer les objets sur un autre hébergeur (Scaleway, OVH etc) ?

L’objectif étant de pouvoir accéder aux sauvegardes de bases de données en cas d’indisponibilité d’un centre de données, d’un hébergeur.

Merci.

**Comment by thbar** [comment]
Je ré-évalue la question chez Scaleway.

**Comment by thbar** [comment]
Notes collectées sur Mattermost:

> Avec OVH, tu peux avoir des accès S3 par bucket
(et tu es autonome pour créé les accès) 

> Chez Outscale, tu peux gérer les ACLs par bucket mais tu dois demander au support de créé des comptes manuellement pour chaque pair de clé que tu souhaites

> tout ce fait en ligne de commande chez Outscale 

> Pour OVH, ce n'est pas totalement compatible S3 (les tailles de chemins sont plus limité par exemple)

**Comment by thbar** [comment]
https://console.scaleway.com/support/tickets/IKFZ-2862-GVRM

**Comment by AntoineAugusti** [comment]
@thbar Je pense aller faire un tour sur Scaleway dans les jours à venir et tenter de :
- créer un bucket
- créer des policies write-only
- ajouter une lifecycle rule pour supprimer des objets après 15 jours
- upload quelques objets

Ça te convient si je fais ça ?
D'où/comment penses-tu que l'on doit lancer le processus de Cellar -> Scaleway à terme ?

**Comment by AntoineAugusti** [comment]
@thbar As-tu pu regarder mon précédent commentaire ?

**Comment by thbar** [comment]
@AntoineAugusti j'avais raté ça! Merci pour le rappel.

Quelques points que j'avais en tête, à voir si on fait ou pas selon comment tu le sens:
- séparer bucket dev/staging/production (idem pour les policies)
- j'aime bien avoir un chiffrement GPG avant envoi sur la destination (mais ça peut attendre dans notre cas je pense)
- bien versionner les policies dans notre codebase ou quelque part, en tout cas

> D'où/comment penses-tu que l'on doit lancer le processus de Cellar -> Scaleway à terme ?

Je suis pas sûr que ça soit une bonne idée à court terme, je serais d'avis de juste tester avec les backups dans un premier temps. Pourquoi je suis pas sûr : avec le cellar là bas, et nos applications chez Clever, la bande passante entre les deux va devenir payante, et potentiellement c'est moins "proche" en terme de réseau aussi.

Donc je me disais que tester le terrain "juste" avec les backups ça sera déjà bien, avec en premier "juste" la DB (cf ci-dessus), et dans un second temps une synchro (à réfléchir comment) sur la partie S3 aussi, mais en mode incrémental malin, qui ne permet pas d'effacer ce qui est dispo avant (comme le fait Arq).

Ca te convient ?

**Comment by thbar** [comment]
@AntoineAugusti autres notes:
- il faut passer l'identifiant de la société sur Pathtech (voir les réfs dans CleverCloud), et voir si on peut après ajouter Boris en contact billing uniquement
- avoir un compte "orga" et obligation de 2FA pour chacun des dévs

**Comment by AntoineAugusti** [comment]
@thbar 

> D'où/comment penses-tu que l'on doit lancer le processus de Cellar -> Scaleway à terme ?

J'avais bien en tête uniquement les backups de base de données en écrivant ceci. Je notais "Cellar" car les backups sont stockées dans un Cellar sur CleverCloud.

**Comment by thbar** [comment]
@AntoineAugusti ahh pardon, merci pour la clarification ; j'avais compris Cellar = tout le stockage S3 chez CleverCloud.

**Comment by AntoineAugusti** [comment]
Ok, j'ai testé un peu et j'envisage le montage suivant.

## Contraintes
- Dans un même projet, on ne peut pas restreindre les actions. C'est-à-dire que chaque clé d'API a tous les droits sur les buckets dans ce projet
- Il n'y a pas de permission qui permet du "write-once" (`PutObject` permet d'écrire dessus à nouveau)
- Scaleway ne supporte pas [toutes les actions S3](https://www.scaleway.com/en/docs/storage/object/api-cli/bucket-policy/#supported-actions)
- Il y a des bucket policies et des lifecycle rules

## Montage
- 1 projet qui contient 2 buckets, 1 prod et 1 staging. 0 clés d'API
- Bucket policy qui permet uniquement de faire `PutObject` sur ces 2 buckets en déléguant à un autre projet dans notre même organisation

```json
{
   "Version":"2012-10-17",
   "Id":"default-project-allow-write",
   "Statement":[
      {
         "Sid":"Delegate access",
         "Effect":"Allow",
         "Principal":{
            "SCW":"project_id:48833e60-251c-452a-bd1d-9bfd28f6d84a"
         },
         "Action":"s3:PutObject",
         "Resource":[
            "transport-staging-backups/*"
         ]
      }
   ]
}
```
- On utilise une clé d'API sur cet autre projet, qui ne peut que écrire. On doit faire attention à écrire des noms d'objets qu'on ne peut pas devenir (par exemple `backup-YYYYMMDDHHMMSS-<UUID>`)
- Si la clé d'API de se projet leak, il est impossible de supprimer des objets car on ne peut pas lister les objets pour réécrire et on a pas les permissions pour supprimer des objets/buckets
- On utilise une _lifecycle rule_ pour garder _n_ jours de données.

---

J'ai créé buckets et clés pour les projets et j'ai mis en place les policies. Testé le bon fonctionnement des permissions avec 2 profils.

**Comment by AntoineAugusti** [comment]
J'ai ajouté des lifecycle rules. Suppression à 30 jours en staging et suppression à 90 jours en production, de tous les objets.

```
aws --endpoint-url "https://s3.fr-par.scw.cloud" --region fr-par s3api get-bucket-lifecycle-configuration --bucket transport-staging-backups
aws --endpoint-url "https://s3.fr-par.scw.cloud" --region fr-par s3api get-bucket-lifecycle-configuration --bucket transport-prod-backups
```

**Comment by AntoineAugusti** [comment]
J'ai demandé [des clarifications](https://console.scaleway.com/support/tickets/ZOCI-7837-XYGY) concernant le multi AZ à Paris.

**Comment by AntoineAugusti** [comment]
Les buckets policies et lifecycle configurations ont été ajoutés dans `docs/scaleway` dans la PR
