### ISSUE TITLE
Des colonnes DateTime utilisent un champ texte

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#1550]
Découvert par @fchabouis durant le travail initial sur #1536 (qui a mené à #1546), plusieurs colonnes en base utilisent (pour des raisons sûrement historiques) un champ texte.

On mettra d'abord sous tests les opérations d'import, avant de retoucher cette partie sereinement, et voir si on comprend pourquoi ça a été fait comme ça (peut-être une contrainte à un moment).

**Comment by thbar** [comment]
Petite requête du jour pour lister les champs (et on filtrera après pour voir où on en est):

```sql
SELECT
	table_name, column_name, data_type
FROM
	information_schema.columns
WHERE table_schema = 'public'
ORDER by table_name, ordinal_position
```

**Comment by thbar** [comment]
Vu que c'est pas la première fois que je cherche, j'ai un peu scripté l'opération (https://gist.github.com/thbar/411a0a2ba2db4a6605853e572a125469). Il y a des faux positifs mais ça donne ceci, on retrouve bien des champs problématiques, sur 3 tables:

```elixir
[
  %{
    column_name: "created_at",
    data_type: "character varying",
    sample_value: "2020-08-26",
    table_name: "dataset"
  },
  %{
    column_name: "last_update",
    data_type: "character varying",
    sample_value: "2021-12-23",
    table_name: "dataset"
  },
  %{
    column_name: "last_import",
    data_type: "character varying",
    sample_value: "2019-03-04 07:00:00.536778Z",
    table_name: "resource"
  },
  %{
    column_name: "last_update",
    data_type: "character varying",
    sample_value: "2018-08-29T12:20:03",
    table_name: "resource"
  },
  %{
    column_name: "original_resource_url",
    data_type: "character varying",
    sample_value: "https://static.data.gouv.fr/resources/offre-ete-2019-reseau-periurbain-filibus/20200511-141226/ete-peri.zip",
    table_name: "resource"
  },
  %{
    column_name: "datagouv_id",
    data_type: "character varying",
    sample_value: "cf9e898c-9ba6-4820-a51a-93709c07f891",
    table_name: "resource"
  },
  %{
    column_name: "date",
    data_type: "character varying",
    sample_value: "2022-07-20 14:39:45.240204Z",
    table_name: "validations"
  }
]
```

**Comment by AntoineAugusti** [comment]
J'ai traité `dataset.created_at` et `dataset.last_update` dans #3044

**Comment by AntoineAugusti** [comment]
J'ai traité `resource.last_import` et `resource.last_update` dans #3059

**Comment by thbar** [comment]
@AntoineAugusti j'ai relancé mon script (https://gist.github.com/thbar/411a0a2ba2db4a6605853e572a125469) et relu les commentaires que tu as laissé, j'ai l'impression qu'il ne reste plus!

Si tu n'en vois pas non plus on peut clôturer.

**Comment by AntoineAugusti** [comment]
Ça me parait bon aussi, on peut fermer et se féliciter d'avoir géré ça 🍾
