### ISSUE TITLE
La drop-down logout est invisible!

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#1551]
J'essayais de trouver le lien pour me délogger durant des tests, et au final j'ai compris que c'était invisible dans mon cas:

![CleanShot 2021-03-19 at 13 52 17](https://user-images.githubusercontent.com/10141/111783279-57025f80-88ba-11eb-8d9f-57a1332419b7.gif)

Il manque peut-être un petit picto suite au redesign #676?

**Comment by fchabouis** [comment]
c'est si tu n'as ni photo de profil, ni nom dans demo.data.gouv, du coup rien ne s'affiche. Il faudrait mettre un contenu par défaut dans ce cas :+1:
