### ISSUE TITLE
Dashboard de visualisation des licences non spécifiées

### ISSUE THREAD

**Issue by NicolasBerthelot** [etalab/transport-site#1556]
Il serait trèsintéressant qu'en tant que biz dev nous puissions facilement avoir la liste des datasets qui sont actuellement associées à une licence non spécifiée. Le fait qu'une licence soit non spécifiée peut être lié à un bug lors du référencement ou du moissonnage (cf https://github.com/etalab/transport-site/issues/1555) mais cela peut-être dû à l'absence d'indications de la part du producteur. 
Cela serait utile que nous ayons cette liste pour faire des relances et s'assurer que toutes les données sur transport sont associées à une licence.

**Comment by NicolasBerthelot** [comment]
Cette issue peut être mise en lien avec les problématiques de traçage des licences associées à un jeu de données. En effet il serait utile d'avoir de la visibilité sur l'historique des licences associées à un jeu de données en cas de litige entre un réutilisateur et un producteur de données.

**Comment by thbar** [comment]
Sur le premier point: je pense qu'il serait utile d'étudier la mise en place de quelque chose qui vous permettrait de faire des requêtes en base (en lecture seule, sans risque de modifier la donnée), du type https://redash.io ou https://www.metabase.com/pricing/ (qu'on pourrait dans les deux cas "auto-hoster" éventuellement, selon le prix), et d'obtenir ce type d'informations.

Ca ou apprendre à faire un peu de SQL également (ça peut aussi se faire).

On en rediscute!

**Comment by NicolasBerthelot** [comment]
C'est vrai qu'une petite formation d'une heure à l'utilisation des bons outils pour faire un peu de SQL ce serait le top ! J'avais l'habitude d'utiliser Dataiku qui propose une interface plutôt sympa, j'imagine qu'il y a des équivalent gratuits pour faire des choses basiques !
