### ISSUE TITLE
Audit de mise en conformité

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#1558]
Comme vu avec l'équipe, voici le récapitulatif des éléments pour l'audit de mise en conformité (Startups d'Etat en phase d'accélération), communiqué par @IshanB et modifié ici.

### Obligations légales

- [x] Code open-source
- [x] Mentions légales nécessaires apparentes:
  - [x] Votre lien "Mentions légales" du pied-de-page renvoie vers la [page des conditions juridiques (ODbL)](https://doc.transport.data.gouv.fr/presentation-et-mode-demploi-du-pan/cadre-juridique-harmonise)
  - [x] Il faut impérativement faire apparaître une [page de ce type](https://aides-territoires.beta.gouv.fr/mentions-légales/) en mentionnant : 
    - [x] Marc Papinutti en tant que responsable de la publication
    - [x] En spécifiant que les utilisateurs sont suivis par votre outil de suivi d'audience, Matomo. Il est recommandé d'indiquer dans votre pied de page un lien direct vers le paragraphe des mentions légales concernant le suivi d'audience, ou d'en faire une page dédiée ([exemple](https://santepsy.etudiant.gouv.fr/donnees-personnelles-et-gestion-des-cookies))
    - [x] Depuis septembre 2020, il est obligatoire de faire apparaître l'état d'accessibilité de votre site internet dès la page d'accueil. En l'occurrence, vous pouvez indiquer "Accessibilité : non conforme" dans votre pied de page, comme sur https://santepsy.etudiant.gouv.fr/ et indiquer en toute transparence que l'[audit d'accessibilité n'a pas encore été effectué](https://santepsy.etudiant.gouv.fr/mentions-legales#accessibilite).
- [x] Obligations RGPD - sont-elles respectées ?
  - [ ] Données personnelles (PipeDrive, Google Drive etc)
  - [x] Bandeau (TODO - voir si nécessaire avec Tristan)
  - [x] Voir https://www.cnil.fr/fr/cookies-et-autres-traceurs-la-cnil-publie-des-lignes-directrices-modificatives-et-sa-recommandation
  - [x] Voir https://www.cnil.fr/fr/cookies-et-traceurs-comment-mettre-mon-site-web-en-conformite
- [x] Homologation de sécurité a-t-elle été réalisée? "C'est une formalité dans le cas de transport.data.gouv.fr qui n'a pas des enjeux de sécurité considérables, mais je vous encourage à reprendre les discussions avec le RSSI du ministère de la transition écologique. 
Pour plus d'information, vous avez un paragraphe sur le sujet de l'homologation [dans cette FAQ](https://docs.google.com/document/d/1OtSWStJ19GMYZ9gHtyyW_C_PfxbfvnvJSRqLwKSApxA/edit?usp=sharing) préparée par Thomas Menant"
- [ ] L'audit d'accessibilité
  - [ ] Vous pouvez commencer par réaliser [ces 10 tests vous-mêmes](https://doc.incubateur.net/design/ressources-design/kit-accessibilite/accessibilite/10-choses-faciles-a-verifier-pour-un-site-plus-accessible)
  - [ ] Et plus globalement par lire notre [kit accessibilité](https://doc.incubateur.net/design/ressources-design/kit-accessibilite)
  - [ ] Ensuite nous pourrons réaliser un audit en passant par le marché DINUM. Ce n'est pas obligatoire que toutes les pages soient accessibles à 100% si vous le justifiez correctement (exemple de [Startup d'Etat ayant réalisé ses tests d'accessibilité](https://signal.conso.gouv.fr/accessibilite))

### Obligations liées aux standards beta.gouv.fr

- [x] Les utilisateurs peuvent contacter facilement l'équipe. contact@transport.beta.gouv.fr est bien présent sur la page d'accueil.
- [x] Je vous recommande de créer à présent contact@transport.data.gouv.fr et de mettre en place une redirection étant donné que votre phase beta est terminée
- [x] Les statistiques d'impact sont visibles sur le site. https://transport.data.gouv.fr/stats est visible. 
- [ ] Je recommande cependant d'historiciser les mesures d'impact, notamment le taux de qualité des données et le taux de mise à jour, pour que dans le temps on puisse analyser 

Vous pouvez consulter les autres standards beta.gouv.fr sur [cette page](https://doc.incubateur.net/communaute/gerer-sa-startup-detat-ou-de-territoires-au-quotidien/la-vie-dune-se/construction/kit-de-demarrage).

**Comment by thbar** [comment]
En attente retour, tous les éléments ont été envoyés de notre côté.

**Comment by fchabouis** [comment]
Faire l'auto-test d'accessibilité à l'occasion.

**Comment by thbar** [comment]
La soutenance a été passée avec succès, une homologation de 3 ans a été proposée.

On garde ce ticket ouvert en attendant le résultat officiel, et on gagnera sûrement à afficher l'info quelque part sur le site à un moment.

**Comment by thbar** [comment]
Le résultat officiel a été publié on est bon.

Il faut voir où on affiche ça éventuellement sur le site. À discuter en point d'équipe.

**Comment by thbar** [comment]
Pas de besoin strict de l'afficher pour le moment, je clôture, mais on revisitera ça.
