### ISSUE TITLE
Bug de moissonnage des données de la région SUD

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#1564]
Remonté par @NicolasBerthelot:

> Pour tous les datasets on arrive bien à télécharger le GTFS, on en fait la validation, mais on indique qu'il n'est pas disponible. Je ne comprends vraiment pas quelle peut être l'origine du problème. Les datasets concernés :

* https://transport.data.gouv.fr/datasets/ligne-des-chemins-de-fer-de-provence-de-la-region-sud-provence-alpes-cote-dazur/
* https://transport.data.gouv.fr/datasets/trains-express-regionaux-points-darrets-et-horaires-des-lignes
* https://transport.data.gouv.fr/datasets/lignes-autocars-interurbains-regionsud
* https://transport.data.gouv.fr/datasets/lignes-expresses-regionales-et-chemins-de-fer-de-provence-points-darrets-et-horaires-des-lignes/

**Comment by thbar** [comment]
En visuel cela donne:

<img width="662" alt="CleanShot 2021-03-30 at 09 33 15@2x" src="https://user-images.githubusercontent.com/10141/112950807-f76a4680-913a-11eb-8cbc-13be8a34b468.png">

**Comment by thbar** [comment]
@fchabouis a suggéré qu'on considère temporairement que "tout est disponible", car globalement c'est le cas, et l'évaluation de la disponibilité n'est pas fiable et donne une fausse impression d'indisponibilité.

Et on retravaillera ensuite sur une v2 de disponibilité plus fiable comme évoqué ensemble.

Qu'en pensez-vous ?

**Comment by Miryad3108** [comment]
Je suis d'avis de le garder car parfois c'est "non disponible" parce que la ressource a été supprimée soit sur data.gouv.fr soit sur le portail OpenData (ou l'URL a changé). Quand la ressource a été supprimée sur data.gouv.fr on peut le savoir via les mails automatiques qu'on reçoit. Par contre, quand la ressource a été supprimée sur le portail de la collectivité, on a que cette étiquette pour nous alerter.

**Comment by thbar** [comment]
@NicolasBerthelot je vais aller débugger ce cas là, c'est vrai que ça fait plusieurs cas.

**Comment by thbar** [comment]
Reproduction:

```elixir
$ hex -S mix

iex(2)> url = "https://trouver.datasud.fr/dataset/e8c44069-1822-4778-908d-05d699bfe826/resource/195f6924-ffb9-4704-9975-0c98abc7aa0c/download/gtfs_cp.zip"

iex(3)> HTTPoison.get(url)
[info] TLS :client: In state :certify at ssl_handshake.erl:1783 generated CLIENT ALERT: Fatal - Handshake Failure
 - {:bad_cert, :invalid_key_usage}
{:error,
 %HTTPoison.Error{
   id: nil,
   reason: {:tls_alert,
    {:handshake_failure,
     'TLS client: In state certify at ssl_handshake.erl:1783 generated CLIENT ALERT: Fatal - Handshake Failure\n {bad_cert,invalid_key_usage}'}}
 }}
```

**Comment by thbar** [comment]
Je tente différents trucs, je ferai un rapport ici quand j'aurai trouvé.

**Comment by thbar** [comment]
Statistiques pour voir combien de ressources sont impactés (avant fix) - c'est la ligne `tls_alert`:


result | Count - url
-- | --
200 | 1801
301 | 61
302 | 7
307 | 1
404 | 266
405 | 58
503 | 1
:timeout | 10
{:tls_alert, {:handshake_failure, 'TLS client: In state certify at ssl_handshake.erl:1783 generated CLIENT ALERT: Fatal - Handshake Failure\n {bad_cert,invalid_key_usage}'}} | 15
Total Result | 2220

**Comment by thbar** [comment]
Code utilisé pour créer le fichier CSV (après j'ai fait un tableau croisé dynamique):

```elixir
{:ok, _} = Application.ensure_all_started(:hackney)
{:ok, _} = Application.ensure_all_started(:ecto)
{:ok, _} = Application.ensure_all_started(:db)

import Ecto.Query

DB.Resource
#|> limit(2)
|> DB.Repo.all
|> Enum.map(&(&1.url))
|> Enum.reject(&(URI.parse(&1).scheme == "ftp"))
|> Task.async_stream(
  fn(url) ->
    result = case r = HTTPoison.head(url) do
      {:error, e} -> e.reason
      {:ok, e} -> e.status_code
    end
    {url, result}
  end,
  timeout: 15_000,
  on_timeout: :kill_task,
  max_concurrency: 50
)
|> Enum.to_list()
|> Enum.map(fn({:ok, {url, res}}) -> [url, res |> inspect] end)
|> CSV.encode
|> Enum.to_list()
|> IO.puts
```

**Comment by thbar** [comment]
La solution propre serait de mettre à jour OTP comme je l'ai constaté (#1584), mais c'est un trop gros changement. Je vais préparer un hotfix, toutefois il faudra voir si il faut l'ajouter à d'autres endroits, car le code fait appel à HTTPoison ailleurs.

**Comment by thbar** [comment]
En remplaçant l'appel:

```elixir
HTTPoison.head(url)
```

par:

```elixir
HTTPoison.head(url, [], ssl: [versions: [ :'tlsv1.2' ]] )
```

J'obtiens les statistiques suivantes:


result | Count - url
-- | --
200 | 1815
301 | 61
302 | 7
307 | 1
404 | 267
405 | 58
503 | 1
:timeout | 10
Total Result | 2220

**Comment by thbar** [comment]
@NicolasBerthelot j'ai implémenté un fix temporaire dans #1585. Ca semble fonctionner, la plupart des ressources passent en vert, sauf une que j'ai vu passer en "illisible" mais ça sera un autre souci.

Je te laisse vérifier si tu peux et fermer ce ticket si c'est bon pour toi.

**Comment by thbar** [comment]
@NicolasBerthelot je ferme le ticket à présent, ça semble OK.
