### ISSUE TITLE
Préparation bandeau information + page RGPD

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#1570]
Suite à discussion avec l'équipe et dans le but de vérifier #1558, nous avons acté:
- qu'il fallait un bandeau (en haut de page ?) pour alerter le visiteur
- ce bandeau contiendra notamment un lien vers une page spécifique qui liste les données concernées et les usages

### Tâches prévues

- [x] Identifier une startup qui utiliserait un bandeau qu'on peut reprendre
- [ ] Préparer un registre de données (voir plus bas données et usage)
- [ ] Créer une page spécifique
- [ ] Implémenter le système de bandeau avec cookie
 
### Données et usage

- [ ] PipeDrive et Google Drive pour le suivi
- [ ] Calendrier ?
- [ ] Matomo stats (anonymisées ?)
- [ ] Cookies d'authentification
- [ ] Logs d'accès et IP chez l'hébergeur
- [ ] Autres ?

### Ressources pour vérifier notre conformité

- https://www.cnil.fr/fr/questions-reponses-lignes-directrices-modificatives-et-recommandation-cookies-traceurs
- https://www.cnil.fr/fr/cookies-et-autres-traceurs-la-cnil-publie-des-lignes-directrices-modificatives-et-sa-recommandation
- https://www.cnil.fr/fr/cookies-et-traceurs-comment-mettre-mon-site-web-en-conformite

**Comment by thbar** [comment]
@Miryad3108 @NicolasBerthelot @fchabouis voilà la fiche de départ, à compléter avec ce dont on a connaissance

**Comment by NicolasBerthelot** [comment]
A priori cette issue est résolue grâce à la page "Mentions légales" : https://doc.transport.data.gouv.fr/presentation-et-mode-demploi-du-pan/mentions-legales-et-conditions-generales-dutilisation
