### ISSUE TITLE
Évènement Sentry GBFS (1k par semaine)

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#1575]
Cet évènement https://sentry.io/organizations/betagouv-f7/issues/2305419985/?environment=prod&project=5687467&query=is%3Aunresolved&statsPeriod=7d se produit à hauteur de 1k par semaine (4k par mois).

C'est le dernier "gros event" niveau consommation, il va falloir comprendre à quoi il est lié et/ou le muter d'une façon ou d'une autre.

Voir #1567.

**Comment by fchabouis** [comment]
ça a disparu on dirait
