### ISSUE TITLE
Configuration DNS à nettoyer

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#1588]
En faisant un test SSL je me suis rendu compte que notre nom de domaine est peut-être configuré dans un ancien mode, présent pour gérer les cas où le CNAME n'est pas disponible sur le fournisseur DNS (mais dans notre cas ce n'est pas le cas):

```
@	300	IN	A	185.42.117.108
@	300	IN	A	185.42.117.109
@	300	IN	A	46.252.181.103
@	300	IN	A	46.252.181.104
```

La [documentation CleverCloud](https://www.clever-cloud.com/doc/administrate/domain-names/#using-personal-domain-names) indique:

> The use of a CNAME record is highly recommended.

Il y a également des choses anciennes (voir le "dev-nono" dans la configuration, que je ne partagerai pas ici en détail).

**Comment by AntoineAugusti** [comment]
![image](https://user-images.githubusercontent.com/295709/140893758-1ef574db-6b93-417d-9986-0e065d78efda.png)

AlwaysData ne supporte pas un CNAME à la racine donc j'ai laissé comme tel. J'ai supprimé quelques enregistrements qui ne sont plus utilisés.
