### ISSUE TITLE
Mettre en place des Alertes si un utilisateur de data.gouv.fr commente un jeu de données du PAN 

### ISSUE THREAD

**Issue by NicolasBerthelot** [etalab/transport-site#1596]
En tant que biz dev, il serait très utile de savoir lorsque qu'un utilisateur écrit un commentaire dans l'espace communautaire d'un jeu de données qui est référencé sur le PAN. Aujourd'hui nous n'avons des alertes que pour les jeux de données dont nous sommes nous même producteurs.

**Comment by fchabouis** [comment]
Après avoir demandé à l'équipe data.gouv.fr, il apparait que le fait de s'abonner a un jeu de donnée sur leur plateforme ne permet pas de recevoir ce genre d'alertes. Exit donc la solution qui aurait consisté à abonner notre adresse mail d'équipe par exemple à tous les jeux référencés sur le PAN.

Il faudra donc passer par une solution faite par nous.

Il est possible, à chaque import de comparer la date du dernier commentaire avec celle que nous avions stocké en base, et de déclencher l'envoi d'un mail à l'équipe.

Peut-être que par la suite, l'équipe transport sera juste un réutilisateur comme les autres, que nous aurons dans notre espace réutilisateur tous les jeux de données cochés, et que nous recevrons des notifs comme tous les réutilisateurs qui souhaitent en avoir, mais ça c'est le futur :D
