### ISSUE TITLE
Passer la région Auvergne-Rhône-Alpes en vert

### ISSUE THREAD

**Issue by NicolasBerthelot** [etalab/transport-site#1597]
C'est parti, la région AuRA publie des données sur les réseaux interurbains de la Région. Plus de raison de les indiquer en vert pâle, on peut les passer en vert foncé comme les autres régions métropolitaines !

**Comment by thbar** [comment]
J'ai répéré l'endroit où cela est affiché (sur http://transport.data.gouv.fr/stats):

![2021-04-16 at 17 22](https://user-images.githubusercontent.com/10141/115047158-8ff11c80-9ed8-11eb-84a7-a2bb433a7948.png)

**Comment by thbar** [comment]
J'ai trouvé où ça se gérait. J'ai lancé la query SQL suivante en local, puis en production après avoir vu que ça fonctionnait:

```sql
select * from region where nom = 'Auvergne-Rhône-Alpes'

update region set is_completed = true where nom = 'Auvergne-Rhône-Alpes'
```

**Comment by thbar** [comment]
Ca semble avoir fonctionné.

![2021-04-16 at 17 58](https://user-images.githubusercontent.com/10141/115051639-54a51c80-9edd-11eb-839b-0922090226a3.png)

Je clôture.
