### ISSUE TITLE
Le fonctionnement d'OpenDataSoft fait que "last-modified" est incorrect

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#1604]
Voir enquête initiale #1592, je remets au propre ici, car il y avait eu une fausse piste (#1593), qui a été traitée par ailleurs.

### Liens utiles

* [FAQ OpenDataSoft](https://help.opendatasoft.com/faq-glossary/fr/faq_index.html) (voir "Quels sont les formats de fichiers pris en charge par Opendatasoft ?")

### Constat de départ

@NicolasBerthelot remontait:

"Google soulève que le jeu de données sur le TER (https://transport.data.gouv.fr/datasets/horaires-des-lignes-ter-sncf/) n'est pas mis à jour depuis février. Or nous avons calculé un nouveau hash chaque jour jusqu'au 30 mars."

Le fait de dire que la donnée n'est pas à jour s'appuie sur la date de dernière modification affichée ici, qui est le 4 février 2021:

<img width="483" alt="CleanShot 2021-04-20 at 14 49 13@2x" src="https://user-images.githubusercontent.com/10141/115398576-9688d800-a1e7-11eb-9a74-11dd5d18eeec.png">

Si on va sur Data Gouv pour ce dataset, on voit bien une partie CSV avec une date de modification du 4 février:

https://www.data.gouv.fr/fr/datasets/horaires-des-lignes-ter-sncf/#resource-28a42d49-e9a8-4c6c-a999-b2b7ea8ce977

<img width="590" alt="CleanShot 2021-04-20 at 15 24 02@2x" src="https://user-images.githubusercontent.com/10141/115403153-73acf280-a1ec-11eb-95d3-85ecbed09065.png">

Le contenu du fichier actuel peut être prévisualisé, et on voit alors:

<img width="904" alt="CleanShot 2021-04-20 at 15 24 53@2x" src="https://user-images.githubusercontent.com/10141/115403291-90e1c100-a1ec-11eb-8a65-94177a0f384f.png">

**Ce fichier n'a pas changé depuis le 4 février, car il est stocké sous forme de CSV qui contient une url, qui elle contient un contenu qui change**.

Pour contourner ce problème, le site Transport fait une extraction spécifique pour aller chercher l'url à l'intérieur, dans un [code spécifique à OpenDataSoft](https://github.com/etalab/transport-site/blob/master/apps/transport/lib/opendatasoft/url_extractor.ex).

Ce travail n'est pas mutualisé avec Data Gouv.

Pour autant, [en backoffice](https://transport.data.gouv.fr/backoffice/datasets/239/edit), on voit que le "content hash" (qui calcule une somme de contrôle sur la donnée réellement téléchargée), lui, a bien changé après le 4 février 2021:

<img width="718" alt="CleanShot 2021-04-20 at 14 50 29@2x" src="https://user-images.githubusercontent.com/10141/115398842-dc45a080-a1e7-11eb-8072-443e2420283b.png">

J'ai vérifié ce point à la main et je confirme que les données changent réellement.

Cette date est tirée du code suivant:

https://github.com/etalab/transport-site/blob/a6939f7c1398f0e22299e49fff937701d9b89ee6/apps/transport/lib/transport/import_data.ex#L316

La donnée vient de Data Gouv, et est plus globalement requêtée ici:

https://github.com/etalab/transport-site/blob/a6939f7c1398f0e22299e49fff937701d9b89ee6/apps/transport/lib/transport/import_data.ex#L145-L154

### Historique

Contacté, @l-vincent-l indique que ce point a donné lieu à des échanges avec OpenDataSoft il y a environ 3 ans. Mais rien n'a bougé depuis.

### Conclusion

Au vu des soucis de clarté de mise à jour de la donnée, du code "custom" créé, et des impacts sur finalement tous les réutilisateurs possibles (chez nous ou ailleurs), je pense qu'il serait souhaitable de nous rapprocher d'OpenDataSoft pour avoir une "update" sur ce point, qui est au final impactant au quotidien depuis plusieurs années, et avoir un vrai support pour les données qui ne sont pas des formats fixes, mais plutôt API ou flux, car ces besoins s'accroissent.

**Comment by thbar** [comment]
Voir #1645

**Comment by thbar** [comment]
Important dès lors qu'il y a un cycle de vie sur la donnée qui est utile au réutilisateur (changements mensuels/trimestriels etc).

**Comment by AntoineAugusti** [comment]
Géré depuis que l'historisation se repose sur les identifiants de ressources du PAN
