### ISSUE TITLE
Import des JDD dans le backoffice : décalage de -2h

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#1606]
Lorsque je fais l'import d'un JDD de données, l'heure qui apparaît dans "Historique des imports" est de -2h
Dans l'exemple ci-dessous, l'import a été fait à 5h47 et ça apparaît comme étant à 3h47
![image](https://user-images.githubusercontent.com/59559301/115816081-83008b80-a3f8-11eb-8377-bec9d07cda3f.png)

J'en ai fais un autre dans un autre JDD à 5h52 et c'est apparu comme étant à 5h52

**Comment by thbar** [comment]
Merci pour tes remarques et les copies d'écran !

Alors il y a deux choses:

1/ Les heures affichées sont normalement affichées en fuseau horaire UTC (GMT+0), ce qu'on peut reconnaître (c'est un peu cryptique!) au `Z` qui est derrière l'horaire.

3h47 en "timezone" UTC ou GMT+0 (alias "Z"), correspond, quand nous sommes en heure d'hiver (l'heure d'hiver française est du GMT+1) à 4h47, et en heure d'été (GMT+2) à 5h47.

Donc pour les imports nocturnes, c'est "normal" ; je note qu'on pourrai à terme (là c'est compliqué) afficher en heure locale pour que ça soit plus clair.

2/ Et sur ce deuxième point qui lui n'est pas normal:

> J'en ai fais un autre dans un autre JDD à 5h52 et c'est apparu comme étant à 5h52

Je n'ai pas été voir mais je parie que quand les imports sont lancés en global la nuit, l'heure est notée d'une certaine façon, là où quand on le lance de façon individuelle, ça réagit différemment.

@Miryad3108 peux-tu me donner le lien vers le JDD que j'aille voir plus facilement? Merci!

**Comment by Miryad3108** [comment]
Merci, je comprends mieux 
Pour la dernière phrase c'était une faute de frappe : J'en ai fais un autre dans un autre JDD à 5h52 et c'est apparu comme étant à 3h52

Les JDD concernés 
5h47 : https://transport.data.gouv.fr/datasets/horaires-theoriques-et-temps-reel-de-la-station-de-ski-les-saisies-gtfs-gtfs-rt/
5h52 : https://transport.data.gouv.fr/datasets/agen-gtfs-urbain-decembre-2020/

**Comment by thbar** [comment]
Ahh ok alors il n'y a pas de deuxième point, c'est tout en UTC.

Je ne sais pas à quel point tu es familière avec ces notions, au cas où un outil de conversion comme celui-ci pourra aider:

https://www.timeanddate.com/worldclock/converted.html?p1=195&p2=0

On va laisser comme ça pour l'instant si ça ne t'embête pas trop (maintenant que tu le sais), mais je garde en tête ce point pour quand on retouchera cette partie.

Ok pour toi ?

**Comment by thbar** [comment]
@Miryad3108 dans l'immédiat je clôture, on pourra en reparler, la question va se reposer avec les séries temporelles de façon générale.
