### ISSUE TITLE
Préciser les formats supportés par type de données sur les tuiles ou en haut de la liste des jeux de données 

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#1618]
Peut-on préciser les formats de données qu'on accepte par type de données : 
sur les tuiles 
![image](https://user-images.githubusercontent.com/59559301/116661421-b4e39600-a994-11eb-8ba6-84d32f8ec78a.png)

ou
au dessus de la liste des JDD une fois qu'on clique sur la tuile ?
![image](https://user-images.githubusercontent.com/59559301/116661503-d0e73780-a994-11eb-8264-4bff7b70b807.png)

ça rendra cette information plus visible parce que pour l'instant c'est seulement dans la doc et les producteurs/réutilisateurs ne fouillent pas forcément. On nous pose souvent la question "quels sont les formats que vous supportez pour : théoriques et TR TC, VLS etc."

**Comment by fchabouis** [comment]
On va pouvoir indiquer cette information dans le paragraphe d'éditorialisation qu'on vient de mettre en place.
