### ISSUE TITLE
Ajout de l'option "fichier_a_telecharger" pour le "GTFS extractor"

### ISSUE THREAD

**Issue by NicolasBerthelot** [etalab/transport-site#1639]
Lorsqu'on référence un jeu de données de transports publics qui contient un CSV avec une colonne intitulée "url" "lien" "lien_GTFS" etc., on télécharge automatiquement ce GTFS et celui-ci remplace le CSV et les autres fichiers dans l'interface de transport.data.gouv.fr.

Le [CSV de la CARENE](https://data.agglo-carene.fr/explore/dataset/24400644_stran_telechargement_gtfs/table/) ne contient pas de termes que l'extracteur de GTFS connaît. La colonne est appelée `fichier_a_telecharger`. Il faudrait ajouter cette expression à celles qui sont déjà utilisées pour repérer un GTFS.

**Comment by thbar** [comment]
J'ai regardé de plus près. Voilà ce que j'observe.

Si je suis [le lien](https://data.agglo-carene.fr/explore/dataset/24400644_stran_telechargement_gtfs/table/), puis que je clique sur l'onglet Export, et que je récupère le fichier CSV en local, j'ai ceci:

```
Description;url
Lignes, arrêts et horaires du réseau de transport urbain pour la CARENE (STRAN);http://app.mecatran.com/utw/ws/gtfsfeed/static/stran?apiKey=117f5d553876703633280e0e664c227e2a082153
```

@NicolasBerthelot est-ce que je regarde bien au bon endroit du coup ?

Par ailleurs j'ai fait des tests et j'ai remarqué que l'outil d'extraction des liens CSV Opendatasoft chez nous donne le résultat suivant:

```elixir
20:34:34.306 [error] error while parsing urlfrom row: "Row has length 2 - expected length 1 on line 2"
["http://app.mecatran.com/utw/ws/gtfsfeed/static/stran?apiKey=117f5d553876703633280e0e664c227e2a082153"]
```

Si on voit initialement une erreur, car l'extracteur tente différentes stratégies, et la virgule au milieu de la data lui pose problème, le lien est au final bien digéré à première vue.

**Comment by NicolasBerthelot** [comment]
Alors le problème est très subtil. Le nom "littéraire" de la colonne est bien 'url' mais son nom technique dans OpenDataSoft est resté encodé 'fichier_a_telecharger'. Cela a pour conséquence d'être bien exporté sur l'interface de téléchargement sur la page OpenDataSoft comme tu viens de le faire mais ne fonctionne pas du côté de data.gouv.fr car le moissonneur récupère les noms techniques et pas les noms littéraires.

**Comment by thbar** [comment]
@NicolasBerthelot ok merci ; il faut que je comprenne mieux le principe du moissonneur ; as-tu déjà enregistré la ressource dans transport, ou dans data.gouv.fr ? Il faut que je mette la main sur la bonne url pour pouvoir modifier le code de façon solide.

**Comment by NicolasBerthelot** [comment]
Pour le fichier du moissonneur de data.gouv.fr qu'on peut télcharger [ici](https://www.data.gouv.fr/fr/datasets/lignes-arrets-et-horaires-du-reseau-de-transport-urbain-pour-la-carene-stran-gtfs/#resource-df474ae2-964a-4246-8ccb-694b09cfbcec) ça donne ça : 
```
description;fichier_a_telecharger
Lignes, arrêts et horaires du réseau de transport urbain pour la CARENE (STRAN);http://app.mecatran.com/utw/ws/gtfsfeed/static/stran?apiKey=117f5d553876703633280e0e664c227e2a082153
```
Côté transport data.gouv.fr (https://transport.data.gouv.fr/datasets/lignes-arrets-et-horaires-du-reseau-de-transport-urbain-pour-la-carene-stran-gtfs/) il semble que notre outil "élimine" le CSV de la liste, je ne sais pas selon quel mécanisme exactement.

**Comment by thbar** [comment]
@NicolasBerthelot merci pour les informations supplémentaires, ce qui m'a permis de préparer un fix en testant sur la vraie donnée pour être sûr du résultat, et d'écrire des tests autour. Voir #1640, que j'ai envoyé pour review à @fchabouis vu que je repasse off!

> il semble que notre outil "élimine" le CSV de la liste, je ne sais pas selon quel mécanisme exactement.

Je propose de déployer le fix précédent et de voir si il réapparaît, et de garder ce ticket ouvert pour suivre ce point.
