### ISSUE TITLE
Problème moissonnage Licence

### ISSUE THREAD

**Issue by NicolasBerthelot** [etalab/transport-site#1643]
Nous avons un problème de récupération de la licence pour ce dataset : 
https://transport.data.gouv.fr/datasets/horaires-des-bacs-de-loire-en-loire-atlantique-gtfs/

La page indique "Licence non spécifiée" alors qu'elle est Licence Ouverte/Open Licence v2 sur data.gouv.fr

**Comment by thbar** [comment]
Je prends la main, je vais aller fouiller.

**Comment by NicolasBerthelot** [comment]
Un autre exemple 
https://transport.data.gouv.fr/datasets/localisation-des-arrets-ilevia-bus-metro-et-tram-gtfs-pictogrammes-du-reseau-ilevia/

**Comment by fchabouis** [comment]
je vais le faire c'est une correction rapide.
Data.gouv a changé son appelation interne de la licence ouverte. Avant c'était "fr-lo", maintenant c'est "lov2".
