### ISSUE TITLE
Librairies ExAWS et ex-aws-s3 à mettre à jour

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#1650]
Voir #1649, je n'ai pas pu mettre à jour complètement dans #1616, donc je crée un ticket.

Je pense que faire cela après #1649, mais en même temps que https://github.com/etalab/transport_deploy/issues/31, serait une bonne idée.

**Comment by AntoineAugusti** [comment]
Je prends celle-ci comme je vais travailler sur https://github.com/etalab/transport_deploy/issues/31 en même temps

**Comment by AntoineAugusti** [comment]
La situation n'a pas changé pour le moment, on est toujours bloqué par un conflit de versions de dépendances, comme décrit dans https://github.com/parroty/exvcr/issues/153#issuecomment-874864317. À voir si https://github.com/parroty/exvcr/pull/179 sera mergé dans pas longtemps ?

Le commentaire dans le code reste d'actualité https://github.com/etalab/transport-site/blob/d18d2135ee019e1646bfacb2d3d8dcad7d09ca54/apps/transport/mix.exs#L81-L84

Faudra attendre quelques semaines et repasser sur ce ticket

**Comment by thbar** [comment]
Top, merci pour l'update.

Une solution (potentiellement plus "investie" mais avec des bénéfices) à laquelle j'avais songé, c'est de convertir l'usage de exvcr par Moi graduellement. 

Je n'ai pas fait le compte de combien de tests utilisent les cassettes.

Voilà juste pour info !

**Comment by thbar** [comment]
On est actuellement sur les dernières versions (voir #2074). Je clôture.
