### ISSUE TITLE
Message reçu : probleme pour répondre aux commentaires depuis le site

### ISSUE THREAD

**Issue by fchabouis** [etalab/transport-site#1652]
Mail reçu sur l'adresse contact le 18 mai :

Bonjour,

Pour info, j'ai tenté de répondre à un commentaire sur un jeu de données (https://transport.data.gouv.fr/datasets/6082bcd3f3187a37252532bd/discussions/609944fd24faf162f0db6998) et j'ai une erreur 500 lorsque je valide ma réponse.

Cordialement,

On a pas mal d'erreurs 500 sur le site en ce moment,  c'est peut être lié à ça, il faut aller voir.

**Comment by fchabouis** [comment]
J'ai posté un commentaire pour ce dataset, qui a fonctionné correctement : https://transport.data.gouv.fr/datasets/reseau-interurbain-cars-region-cantal-15#dataset-discussions.

J'ai demandé à l'utilisateur de bien vouloir reposter son commentaire pour voir s'il s'agissait d'un problème ponctuel.

**Comment by mhicauber** [comment]
Je suis l'utilisateur :) 
Problème ponctuel, c'est OK désormais.

**Comment by thbar** [comment]
Merci @mhicauber pour le retour!

@fchabouis est-ce qu'on a un rapport Sentry quelque part du coup pour comprendre ce qui a pu amener l'erreur ?

**Comment by fchabouis** [comment]
Oui je l'ai retrouvé, ainsi que le message perdu du 18 mai :)
Pour notre enquête interne, le numéro de l'issue sur Sentry est 2404491725.
Merci beaucoup @mhicauber nous allons pouvoir régler le soucis :+1:
