### ISSUE TITLE
Le logo transport se fait écraser quand on change de largeur de fenêtre

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#1655]
https://user-images.githubusercontent.com/10141/120167706-5a8d5d80-c1fe-11eb-98ee-71d00b135ced.mp4

**Comment by fchabouis** [comment]
Tu as quel navigateur ?
Sur mon FF ça fonctionne bien.


https://user-images.githubusercontent.com/15341118/120172595-83642180-c203-11eb-9fdd-c8ea3e7a8511.mp4

**Comment by thbar** [comment]
Le problème se produit sur Safari, mais pas sur Chrome.

**Comment by thbar** [comment]
Je regardera de mon côté du coup, vu que c'est spécifique à Safari.

**Comment by AntoineAugusti** [comment]
Pas d'activité depuis longtemps, je ferme

**Comment by thbar** [comment]
C'est toujours d'actualité, mais on peut garder fermer et attendre le redesign.
