### ISSUE TITLE
Ajouter le taux de raffraîchissement dans les métadonnées d'un flux GBFS

### ISSUE THREAD

**Issue by NicolasBerthelot** [etalab/transport-site#1661]
On peut connaître le temps de raffraîchissement de certains flux GBFS grâce au champs "ttl" (time to live) expirmé en secondes. 
Cela permet à l'utilisateur de savoir à quel rythme il peut requêter le flux. 

On pourrait l'intégrer de cette manière : 
![image](https://user-images.githubusercontent.com/61453166/120442101-8f77ec80-c385-11eb-9015-7c716b78cef3.png)

Personne ne sera vexé si ce design n'est pas rigoureusement respecté...

**Comment by fchabouis** [comment]
En même temps j'imagine que si quelqu'un veut intégrer un flux GBFS, il va aller lire le TTL directement dans la donnée du flux... Après ça ne mange pas de pain d'avoir l'info en visuel aussi.

**Comment by AntoineAugusti** [comment]
@fchabouis Je me demande comment tu approcherais cette feature. J'ai vu que les resources GBFS n'ont pas de `metadata` donc il faudrait lire le JSON en chargeant l'`url`.

Je pencherai pour mettre ça dans https://github.com/etalab/transport-site/blob/master/apps/db/lib/db/resource.ex.

Je me demande si :
- faire une requête HTTP à chaque chargement de page dataset est acceptable (avec un timeout bas et en faisant attention de gérer les erreurs)
- s'il faut un mécanisme de cache de la réponse HTTP du JSON
- si on chercherait à renseigner le ttl dans `metadata` de la ressource (je ne sais pas comment les ressources GBFS ont été ajoutées pour le moment)

**Comment by fchabouis** [comment]
Quand on visite la page dataset d'un flux GBFS, on essaye de montrer l'info en direct. Ca marche pas toujours, notamment à cause des CORS. Ca donne deux infos :
- si on veut aller lire le TTL ça ne rajoute pas de requete
- ce n'est pas toujours possible de le lire depuis le page web en js.

Si on veut que ça marche a chaque fois, il faudrait le faire côté serveur, par exemple une fois par jour. On pourrait imaginer un job qui tournerait une fois par jour sur toutes les ressources GBFS et qui irait lire le TTL et le stockerait au niveau de la ressource dans ses metadatas par exemple.
