### ISSUE TITLE
Fausse indisponibilité si le serveur distant ne supporte pas la méthode HEAD

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#1665]
Les ressources sur [ce jeu de données](https://transport.data.gouv.fr/datasets/donnees-temps-reels-sur-les-veliverts-velo-en-libre-service-de-saint-etienne-metropole/) sont considérées indisponibles:

![2021-06-03 at 16 30](https://user-images.githubusercontent.com/10141/120661977-09dd6500-c489-11eb-8ba6-84fc3531a9b8.png)

Les urls (ex: [lien](https://saint-etienne-gbfs.klervi.net/gbfs/en/station_information.json)) fonctionnent bien dans un navigateur, mais pas le code de vérification de disponibilité de l'application ne considère pas la donnée comme disponible.

J'ai pu reproduire facilement le souci ; le code qui pose problème est ici:

https://github.com/etalab/transport-site/blob/d58e83cfe993b409bc0886c295cb68225e7aa067/apps/transport/lib/transport/import_data.ex#L332-L339

Dans une console `iex`, on peut lancer:

```elixir
$ iex -S mix
> url = "https://saint-etienne-gbfs.klervi.net/gbfs/en/station_information.json"
> Transport.ImportData.available?(%{"url" => url})
false
```

En recollant le code de requêtage, on voit que la requête `HEAD` retourne une code `405`:

```elixir
> HTTPoison.head(url)                                   
{:ok,
 %HTTPoison.Response{
   body: "",
   headers: [
     {"Date", "Thu, 03 Jun 2021 14:33:42 GMT"},
     {"Cache-Control", "no-store, must-revalidate"},
     {"Expires", "Sat, 01 Dec 1990 00:00:00 GMT"},
     {"Last-Modified", "Thu, 03 Jun 2021 14:33:42 GMT"},
     {"Content-Length", "30"},
     {"Content-Type", "application/json; charset=utf-8"}
   ],
   request: %HTTPoison.Request{
     body: "",
     headers: [], 
     method: :head,
     options: [],
     params: %{},
     url: "https://saint-etienne-gbfs.klervi.net/gbfs/en/station_information.json"
   },
   request_url: "https://saint-etienne-gbfs.klervi.net/gbfs/en/station_information.json",
   status_code: 405
 }}
```

Le code HTTP 405 indique que la méthode (`HEAD`) n'est pas supportée (https://developer.mozilla.org/fr/docs/Web/HTTP/Status/405).

L'API ne supporte que le `GET` (ce que fait un navigateur par défaut).

Il faut faire évoluer la fonction de vérification de disponibilité, pour détecter ce cas `405`, et basculer vers une méthode `GET`.

**Comment by thbar** [comment]
Ping @fchabouis ça fait écho à ce que tu travailles actuellement !

**Comment by fchabouis** [comment]
elles sont dispo ce matin :+1:
