### ISSUE TITLE
GTFS Kicéo apparaît comme étant illisible alors qu'il n'y a aucune erreur détecté par le validateur

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#1667]
Le GTFS de ce réseau était déposé manuellement sur data.gouv.fr par RATPdev
RATPdev aimerait se baser sur une URL distante pour automatiser leur MAJ
Ils ont référencé l'URL sans supprimer le GTFS déposé au cas où. Le GTFS (avec URL distante) apparaît comme étant illisible alors que je peux télécharger le fichier en cliquant sur "télécharger" et le rapport d'erreur ne détecte aucune erreur mais seulement des avertissements

https://transport.data.gouv.fr/datasets/offre-de-transport-du-reseau-de-vannes-kiceo-donnees-theoriques-et-temps-reel/

**Comment by fchabouis** [comment]
J'ai l'impression que le problème a disparu. Tu confirmes @Miryad3108 ?

**Comment by fchabouis** [comment]
je ferme j'ai l'impression que c'est résolu.
