### ISSUE TITLE
Crash RAM sur validation GTFS

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#1670]
Remonté par @fchabouis aujourd'hui, je crée le ticket uniquement pour copier-coller un graphique qui vient du dashboard CleverCloud.

[Lien précis](https://console.clever-cloud.com/organisations/orga_f33ebcbc-4403-4e4c-82f5-12305e0ecb1b/applications/app_04f647ef-4a10-4021-a04b-fe510e6cd003/metrics/advanced)

Si j'affiche sur 1 jour la "used memory" on voit:

<img width="1469" alt="CleanShot 2021-06-09 at 13 45 06@2x" src="https://user-images.githubusercontent.com/10141/121348672-eb63e780-c928-11eb-8440-9d8bd8ae0d2e.png">

On remarque plusieurs séries en parallèle, il faudra voir si on n'a pas des containers "qui trainent". 

Il va falloir identifier l'endroit précis et mettre des métriques ; je me demande si on n'a pas un peu de leak aussi, à creuser, d'autant plus qu'on va ajouter un proxy qui stocke en RAM.

**Comment by fchabouis** [comment]
Ah oui intéressant comme remarque, parce que le streamer avec le throw au milieu pourrait être un bon candidat pour leaker.
J'ai fait un petit test d'appel de la fonction HTTPStreamV2.fetch_status(u) et à creuser mais j'ai bien l'impression que la mémoire n'est pas libérée...

**Comment by fchabouis** [comment]
ça expliquerait la belle montée à partie de minuit qui ne redescend pas après

**Comment by thbar** [comment]
Il faudra vérifier si la mesure de mémoire est fiable (il y a différents outils pour ça), ça devrait pouvoir se reproduire en local si on a un bon leak. Peut-être que le throw laisse le processus en marche et ne clôture pas un buffer, par exemple. Reste plus qu'à creuser !

**Comment by thbar** [comment]
@fchabouis je crois que ça ne s'est pas reproduit. Je suis d'avis de fermer pour l'instant, sauf si tu as davantage d'informations ?

**Comment by AntoineAugusti** [comment]
Pas d'occurrences depuis longtemps et on a bougé des validations sur le worker.
