### ISSUE TITLE
Lien mentions légales 

### ISSUE THREAD

**Issue by margot-sanchez** [etalab/transport-site#1680]
Résumé : la section mentions légales ne semblent pas diriger vers des mentions légales au sens stricte du terme.

Site : https://transport.data.gouv.fr/

## Etape pour reproduire le bug :
1) Dans le footer, cliquer sur mentions légales
![image](https://user-images.githubusercontent.com/15428433/123078302-1e26d900-d41b-11eb-9011-ebdca05e6452.png)

## Comportement attendu : 
Arriver sur une page indiquant l'hébergement, le nom du directeur de la publication, etc.

## Comportement actuel : 
Arriver sur la page du [cadre juridique harmonisé](https://doc.transport.data.gouv.fr/presentation-et-mode-demploi-du-pan/cadre-juridique-harmonise), qui ne correspond pas aux mentions légales.

**Comment by thbar** [comment]
Merci @margot-sanchez! C'est un problème connu, on a une grosse liste de choses à faire là dessus, voir #1558, on est un peu au four et au moulin là dessus.

**Comment by NicolasBerthelot** [comment]
Le problème a été résolu cf : https://doc.transport.data.gouv.fr/presentation-et-mode-demploi-du-pan/mentions-legales-et-conditions-generales-dutilisation
