### ISSUE TITLE
Hébergement du profil Netex France

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#1684]
Discuté avec Benoit Queyron aujourd'hui, je prends quelques notes pour qu'on avance dessus.

### Contexte

Le profil Netex France est actuellement hébergé sur http://www.normes-donnees-tc.org/profils, généreusement géré par Christophe Duquesne (aka @Aurige sur GitHub).

Nous cherchons à proposer un hébergement plus officiel, en particulier pour les raisons suivantes:
- Il est nécessaire d'avoir une "url stable" qui pourra être intégrée dans l'arrêté relatif à ce profil
- Avoir un hébergement sur GitHub permet de conserver les versions successives plus facilement, et de donner une visibilité à un public de développeurs

### Stabilité de l'url dans le temps

On pourrait imaginer des liens du type `https://transport.data.gouv.fr/permalink/xyz`, qui seraient référençables dans des arrêtés, et qui feraient simplement une redirection (cela, ou un autre type de permalink).

C'est une implémentation simple à faire. 

- [ ] Implémentation à faire sur une simple redirection (facile)

### Cible de l'url

Il serait souhaitable d'avoir (vu avec Benoit) une page de documentation, qui ensuite référencerait le repository GitHub qu'on créerait.

- [ ] Il faudra rédiger cette page et voir où on la stocke (doc.transport.data.gouv.fr ?)

### Adaptation des documents Profil

Actuellement, les documents sont au format Word. Pour une intégration dans Git, une conversion en Markdown serait préférable.

- [ ] Voir avec @Aurige ce qu'il en pense
- [ ] Si faisable, voir comment convertir au plus simple

### Autres notes

On pourrait imaginer des ajouts de fichiers d'exemple de données, des pointeurs variés etc.

**Comment by thbar** [comment]
cc @benoit-MINT

**Comment by thbar** [comment]
@fchabouis on devrait pouvoir fermer ce ticket, mais peut-être avant mettre un lien dans notre repo vers là-bas ?

**Comment by Aurige** [comment]
Ok pour moi

**Comment by fchabouis** [comment]
Les profils sont maintenant hébergés sur https://normes.transport.data.gouv.fr/, et nous allons rajouter un lien depuis notre home vers le site #2100
