### ISSUE TITLE
Intégrer les liens des schémas et expliciter les relations entre V1 & V2

### ISSUE THREAD

**Issue by CharlesHutPer** [etalab/transport-site#1686]
Bonjour ! 
Petite _issue_ rapide : je pense qu'il pourrait être intéressant de mettre le lien des schémas dans la page de présentation des datasets, par exemple au niveau des ressources. Si on ne sait pas les chercher sur schema.data.gouv.fr (ou qu'on ne pense pas à aller sur data.gouv.fr), cela peut rendre l'exploration ardue. 

Autre chose, pour les IRVE cela peut être bien d'indiquer clairement si les données de la V2 remplacent ou s’additionnent avec celles de la V1. Cela se repérera facilement avec une exploration des fichiers, mais cela pourrait également être mis directement dans l'indication de description des ressources.

Merci ! 
Charles Hutin-Persillon

**Comment by thbar** [comment]
@CharlesHutPer merci pour le retour ! On va en discuter en équipe.

**Comment by NicolasBerthelot** [comment]
Désormais les fichiers associés à un schéma renvoient bien vers le schéma et la bonne version cf : https://transport.data.gouv.fr/datasets/fichier-consolide-des-bornes-de-recharge-pour-vehicules-electriques/
