### ISSUE TITLE
Reprendre en main le readme + learning track avant arrivée développeur

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#1687]
Suite aux différentes simplifications réalisées dans les semaines passées, une bonne partie de ces docs est obsolète.

Je vais faire une passe de ménage rapide avant que notre nouveau collègue n'arrive.

**Comment by AntoineAugusti** [comment]
Tu as fait beaucoup de boulot et c'est assez _smooth_ maintenant. Je vais relire et ajuster une dernière fois étant le dernier arrivé

**Comment by thbar** [comment]
Je clôture pour l'instant, on revisitera si l'équipe évolue, ou petit à petit.
