### ISSUE TITLE
Dé-référencer les urls de "prochainement"

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#1701]
Si on fait la recherche suivante `site:https://prochainement-transport.cleverapps.io` dans google, on tombe sur de nombreux résultats.

Cela peut amener à de la confusion (email d'une personne de Trainline par exemple, qui est tombé sur ce site).

Solutions possibles à discuter:
- Modifier robots.txt pour déclasser uniquement le site de test, et déréférencer les urls avec une requête à Google en particulier 
- Bloquer l'accès à prochainement derrière une simple authentification supplémentaire du type http basic

**Comment by thbar** [comment]
Ping @Miryad3108

**Comment by thbar** [comment]
@fchabouis j'ai vu passer ton email de ce matin, si tu ne l'as pas déjà vue j'ai créé ce ticket pour réduire ce type de confusion

**Comment by AntoineAugusti** [comment]
Voir aussi #1688

**Comment by thbar** [comment]
On ne tombe pas sur des liens problématiques actuellement, mais à terme ça serait bien de dé-référencer quand même ; donc pas urgent, mais utile à terme.

**Comment by thbar** [comment]
Quelques notes:
- Le fichier est là https://github.com/etalab/transport-site/blob/7fd8cbdf80e34b51c537df0443384d8054e6034c/apps/transport/priv/static/robots.txt
- Servi de façon inconditionnelle ici:

https://github.com/etalab/transport-site/blob/1acd7920f7c054319f837f5c93a0b283ec43f403/apps/transport/lib/transport_web/endpoint.ex#L14-L24

- Il faudrait avoir la version suivante:

```
# See http://www.robotstxt.org/wc/norobots.html for documentation on how to use the robots.txt file
#
# To ban all spiders from the entire site uncomment the next two lines:
User-Agent: *
Disallow: /
```

**Comment by AntoineAugusti** [comment]
Je veux bien m'en charger 😄

**Comment by thbar** [comment]
@AntoineAugusti vas-y go! J'ai noté parce que je traitais un sujet analogue.

Je note aussi:
- `APP_ENV=production` vs `APP_ENV=staging` permettraient de distinguer ça
- une fois que c'est déployé, un déréférencement de `prochainement.transport.data.gouv.fr` peut être fait via les outils Google (https://developers.google.com/search/docs/crawling-indexing/remove-information)
- on peut recetter après (déjà fait dans le passé avec une recherche en `site:prochainement.transport.data.gouv.fr` sur Google)

**Comment by thbar** [comment]
@AntoineAugusti je vois que tu as clôturé, est-ce que tu as fait les démarches chez Google ? Sinon on peut ré-ouvrir pour y penser.

**Comment by AntoineAugusti** [comment]
C'est fait dans [Search Console](https://search.google.com/search-console/removals?resource_id=sc-domain%3Atransport.data.gouv.fr) et je vous ai invité
