### ISSUE TITLE
Gérer la pagination de l'API data.gouv.fr

### ISSUE THREAD

**Issue by fchabouis** [etalab/transport-site#1707]
Il y a sur l'API de data.gouv.fr un parametre de pagination par défaut fixé à 20 élements.

Pour le moment et à ma connaissance, on ne gère pas cette pagination. Je m'en suis rendu compte en essayant de supprimer les ressources communautaires de https://transport.data.gouv.fr/datasets/export-quotidien-au-format-gtfs-du-reseau-de-transport-lignes-d-azur, qui en affiche 20. Il y en a en réalité plus de 500. (Faire un appel sur https://www.data.gouv.fr/api/1/datasets/community_resources/?dataset=59aea7b3b595087a239169d7&page_size=1000 et lire le champ `total` pour s'en convaincre.)

Un autre endroit auquel je pense est le module CommentChecker (qui va vérifier la présence de nouvelle discussion sur data.gouv.fr) et qui pourrait avoir le même problème.

### Liens utiles

* [Section pagination de l'API data gouv](https://doc.data.gouv.fr/api/intro/#pagination)

**Comment by thbar** [comment]
Note d'Alexandre Bulté:

> Ce qu'oOn utilise en dog fooding chez nous c'est de stocker la date du dernier run et de récupérer ce qui s'est passé depuis
> https://github.com/etalab/notebooks/blob/master/moderation/moderation_fn.ipynb

**Comment by fchabouis** [comment]
Ça pourrait être un sujet intéressant à creuser en juillet @andlio

**Comment by thbar** [comment]
Vu qu'on en a discuté, si je devais creuser (idées de pistes pour @andlio pendant nos congés à Francis et moi), j'irais voir grosso modo les points suivants:

1. Bien comprendre l'import des données. Vu que Francis a indiqué que le premier souci portait sur le fait qu'on n'importe (si j'ai bien suivi) qu'une seule "page" de ressources par dataset (et donc pas plus de 20 items), et que c'est ce qui fait que le nettoyage après n'efface "pas assez" (le nettoyage des ressources communautaires est défini ici https://github.com/etalab/transport-site/blob/master/apps/transport/lib/transport/community_resource_cleaner.ex, et s'appuie sur ce qui est en base chez nous), il faut préalablement comprendre la façon dont l'import fonctionne. Il faut aller voir ici https://github.com/etalab/transport-site/blob/d73662ffe5ddd5492d41b6a0ad12b1c6f3b43118/apps/transport/lib/transport/import_data.ex#L142, où a priori le dataset est (à vérifier) ramené avec ses ressources, mais sûrement juste avec la première page.
2. Dans un second temps, voir comment fonctionne [Stream.resource/3](https://hexdocs.pm/elixir/1.12/Stream.html#resource/3), qui est une abstraction très pratique pour créer un stream de données à partir par exemple d'une pagination (voir [ici](https://medium.com/@gottfrois/stream-paginated-graphql-api-in-elixir-11b3b5fdf8fe) pour un exemple d'article là dessus).
3. Refactorer le module d'import pour utiliser cette pagination, dans un premier temps en faisant quelque chose qui va utiliser le stream mais tout importer d'un coup comme c'est fait actuellement (ce qui va faire une grosse transaction avec 400 éléments dans un premier temps...). Dans un second temps, il serait probablement bon de regarder si on peut fonctionner autrement pour avoir quelque chose de plus scalable, qui ne charge pas toutes les définitions de ressources d'un coup en RAM (gros changeset Ecto), mais ça sera plus de travail.

Pour les discussions, de la même façon, je tenterais déjà un petit proto qui va faire un `Stream.resource/3` dans un coin sur les commentaires (CommentChecker), mais qui sait tout paginer.

Voilà à la grosse maille !
