### ISSUE TITLE
Documenter comment fonctionne la recherche

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#1713]
Aujourd'hui durant le point d'équipe, on s'est rendu compte qu'on n'était pas au clair sur le fonctionnement de la recherche.

Par exemple:
- en tapant "transdev", on ne trouve pas les jeux correspondants, alors qu'en tapant d'autres noms, on aura des réponses (via @Miryad3108)
- les codes postaux marchent certaines fois mais pas d'autres (via @andlio)
- taper "gtfs" ne remonte pas tous les 

L'explication sera probablement évidente en regardant le code (ex: seule la description est indexée ?), il suffit d'aller voir et de partager cette information.

**Comment by fchabouis** [comment]
J'ai bien en tête comment la recherche fonctionne, tu penses à quel endroit pour documenter son fonctionnement ?

**Comment by thbar** [comment]
@fchabouis dans l'idée je trouverais ça bien que ça soit clair directement pour l'usager lui-même. On peut imaginer différentes stratégies pour ça, du type petite popup qui explique le tout, ou bien un output visuel de la recherche qui explique un peu, ou un lien vers une doc sur le site lui-même.

À réfléchir mais clairement sauf à regarder le code, ce n'est pas clair aujourd'hui.

**Comment by andlio** [comment]
En faisant plus attention on voit que c'est documenté dans les suggestions de résultats (cf. capture d'écran).

Ce qui est dommage c'est que si on va vite (comme dans mon cas jusqu'à présent), on tape sur "Entrée" et on recherche dans la description alors que dans l'exemple ci-dessus je recherchais une ville. Or les résultats sont différents suivant le type de recherche.

Une recherche "full text" pourrait corriger le problème et simplifier les recherches -> lorsque je recherche "grans", je n'ai pas besoin de sélectionner "par lieu" ou "par description", les résultats les plus pertinents ressortiront en 1er. 

<img width="678" alt="Capture d’écran 2021-08-31 à 18 32 43" src="https://user-images.githubusercontent.com/6974621/131541764-bf7f3e1e-62ae-4ea1-9946-48e76cae5387.png">

**Comment by AntoineAugusti** [comment]
La recherche full text ne marche pas uniquement dans les "descriptions des jeux de données" comme indiqué sur le site web.

Il y a un `search_vector` pour chaque `Dataset`, qui est construit de manière complexe, voir par exemple [la version actuelle](https://github.com/etalab/transport-site/blob/master/apps/db/priv/repo/migrations/20200114101848_change_search_conf.exs). Ceci prend en compte titre, tags, region, commun, AOM, population totale estimée etc.

Il y a aussi un sujet de l'amélioration des filtres appliqués. Par exemple [le jeu de données Réseau urbain Trans'CoVe
](https://transport.data.gouv.fr/datasets/reseau-de-transport-en-commun-de-la-communaute-agglomeration-ventoux-comtat-venaissin/), impossible de le trouver en cherchant [transcove](https://transport.data.gouv.fr/datasets?q=transcove).

L'absence de suggestion d'un département donne certains résultats étonnants. Une recherche sur "Oise" (impossible de sélectionner le département "Oise") donne [des résultats mal triés](https://transport.data.gouv.fr/datasets?q=oise) où les premiers résultats ne font pas apparaître le mot "Oise" pour l'utilisateur (c'est en réalité parce que le Val-d'Oise est en Île-de-France...)

**Comment by fchabouis** [comment]
Le fonctionnement actuel de la barre de recherche est obscur. Il faudrait surement en faire une V2 plus simple et peut être abandonner l'idée de la barre de recherche unique qui fait tout.
Plutôt que de documenter, on pourrait lister les features actuelles qu'on aimerait conserver.

**Comment by AntoineAugusti** [comment]
@thbar On pourrait fermer cette issue étant donné que tu travailles sur #3640 ?

**Comment by thbar** [comment]
Oui tout à fait, merci ! (j'avais linké vers ici donc on ne perdra pas les infos).
