### ISSUE TITLE
Faire un prototype de calcul de date de modification améliorée

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#1714]
La date de modification d'une ressource (voir #1645 #1604) peut être incorrecte.

Suite aux discussions dans #1645, on va faire un premier prototype, visant à:
- créer de nouvelles colonnes (sans toucher aux colonnes pré-existantes)
- les remplir avec une donnée "candidate", avec un calcul basé sur le changement du SHA

Je crée un ticket car dans cette issue, aucun changement pour le public ne sera présent, c'est simplement pour lancer la balle avec une petite PR.

**Comment by thbar** [comment]
Voir #1722

**Comment by AntoineAugusti** [comment]
@fchabouis a nettement amélioré la situation dans https://github.com/etalab/transport-site/pull/2164
