### ISSUE TITLE
Différence entre rapport validation public GTFS et quand on passe le GTFS dans le validateur - Reims 

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#1741]
GTFS de Reims : https://transport.data.gouv.fr/datasets/parcours-arrets-et-horaires-theoriques-du-reseau-de-transport-citura-de-la-communaute-urbaine-du-grand-reims-gtfs/

Le rapport public annonce qu'il y a une erreur irrécupérable 
![image](https://user-images.githubusercontent.com/59559301/129700136-ac3029c0-5129-4f8b-96d7-b06a4ee12508.png)
![image](https://user-images.githubusercontent.com/59559301/129700221-45ad848b-dc22-4481-9105-ee64969fac3a.png)
https://transport.data.gouv.fr/resources/45644#issues

Mais quand je télécharge le GTFS et le passe manuellement dans le Validateur (du PAN), il n'y a aucune erreur qui apparaît 
https://transport.data.gouv.fr/validation/143429

**Comment by fchabouis** [comment]
L'erreur a disparu après avoir lancé une validation forcée depuis le backoffice.
