### ISSUE TITLE
Pour des GTFS qui ont la même couverture géographique/du même réseau : pouvoir passer d'un GTFS à un autre à partir d'un des jeux de données  

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#1747]
Il y a des GTFS pour un même réseau qui sont publiés à la fois par la collectivité ET par la région.
- Parfois leur durée de validité n'est pas la même : l'un des deux peut être périmé alors que l'autre est à jour 
Pour Reims, par exemple, le GTFS publié par Reims n'est plus à jour : https://transport.data.gouv.fr/datasets/parcours-arrets-et-horaires-theoriques-du-reseau-de-transport-citura-de-la-communaute-urbaine-du-grand-reims-gtfs/
alors que celui publié par la région est à jour : https://transport.data.gouv.fr/datasets/horaires-theoriques-du-reseau-citura-communaute-urbaine-du-grand-reims/

- La qualité peut être différente aussi : pour Reims, la qualité des GTFS n'est pas la même non plus. Celui publié par la collectivité est de meilleure qualité. 

Peut on donner la possibilité à un réutilisateur de voir qu'il y a d'autres GTFS pour un même réseau en étant sur un des jeux de données du réseau ? 
C'est déjà possible depuis la page stat 
![image](https://user-images.githubusercontent.com/59559301/130400838-751efe07-eb69-4bef-b8c4-a0429bbfbda3.png)

**Comment by thbar** [comment]
Ca sera aidé par le travail réalisé dans #2105

**Comment by thbar** [comment]
Ca a fait des progrès (dixit @Miryad3108 qui peut commenter) sur la partie utilisateur. Je propose de garder ouvert pour l'instant car ça sera un sujet long terme.

**Comment by Miryad3108** [comment]
Pour des données ayant la même couverture géographique (même AOM/région/communes data.gouv.fr), on peut passer d'un jeu de données à un autre depuis le site grâce à la section "Autres jeux de données" 
<img width="587" alt="image" src="https://user-images.githubusercontent.com/59559301/182610326-7fee3a49-ec9e-436c-91f4-6531a1cf6647.png">

**Comment by Miryad3108** [comment]
On pourrait améliorer la section "Autres jeux de données" pour inclure les données nationales avec des mots clés en plus ? 

Par exemple, les données TER de Région Sud sont inclus dans le jeu de données national TER de la SNCF mais le jeu de données SNCF n'apparaît pas la section "Autres jeux de données de Région Sud — Provence-Alpes-Côte d’Azur" car ce n'est pas la même emprise géographique. Ce qui est dommage car le jeu de donnée TER région Sud n'est plus disponible et les réutilisateurs pourraient récupérer ces données dans le jeu de données national.

**Comment by AntoineAugusti** [comment]
@Miryad3108 Pour ton dernier commentaire, tu t'attends à ne trouver que le JDD SNCF national dans cette section ? Comment on pourrait identifier ça ?

Actuellement on a que l'info que le JDD est dans la catégorie des "transports public collectif", et l'emprise géographique nationale [comporte plusieurs JDD](https://transport.data.gouv.fr/datasets/region/14?type=public-transit).

Tu envisages qu'on recommande à chaque fois l'ensemble des JDD au niveau National pour tous les niveaux géographiques inférieurs ?

**Comment by Miryad3108** [comment]
@AntoineAugusti je ne m'attends pas à trouver que ça mais à le trouver au moins dans la liste (ce qui n'est pas le cas actuellement)

> Tu envisages qu'on recommande à chaque fois l'ensemble des JDD au niveau National pour tous les niveaux géographiques inférieurs ?
est ce qu'on peut ajouter des mots clés ? Par exemple si il y a` TER` dans le titre du jeu de données alors inclure le jeu de données TER national dans la section "Autres jeux de données". Si il y a `TGV` dans le titre du jeu de données alors inclure le jeu de données TGV national dans la section "Autres jeux de données". 
Sinon on risque d'avoir de mauvaises redirections

**Comment by fchabouis** [comment]
Ce sujet a été résolu par le discussion qui a eu lieu sur la "gouvernance des données" : on ne veut plus de doublons sur le site et ce cas ne devrait plus avoir lieu.
