### ISSUE TITLE
Pas d'accès au flux GTFS-RT de Dijon 

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#1755]
Le producteur de données nous a contacté parce qu'il ne comprend pas pourquoi on affiche une erreur lorsqu'on veut accéder à leur GTFS-RT : https://transport.data.gouv.fr/datasets/gtfs-diviamobilites/
De leur côté, cela fonctionne bien 

On fait proxy sur ce flux

**Comment by thbar** [comment]
Le fournisseur nous a répondu et les certificats ont été corrigés.

On a à présent:

```
curl -i https://proxy.transport.data.gouv.fr/resource/divia-dijon-gtfs-rt-trip-update
HTTP/1.1 200 OK

curl -i https://proxy.transport.data.gouv.fr/resource/divia-dijon-gtfs-rt-vehicle-position
HTTP/1.1 200 OK
```

Par ailleurs sur https://transport.data.gouv.fr/datasets/gtfs-diviamobilites/#dataset-resources la ressource GTFS-RT n'est plus marqué indisponible:

<img width="457" alt="CleanShot 2021-08-31 at 12 02 19@2x" src="https://user-images.githubusercontent.com/10141/131483455-045d5975-bcba-47fc-bf4f-fa0158ae8765.png">

Tout est OK, je clôture et je préviens.
