### ISSUE TITLE
Erreur intermittente sur les tests UrlExtractor Opendatasoft

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#1757]
Un nouvel exemple de cas pour #1706, que je vois arriver souvent, donc je vais le traquer séparément:

```
1) doctest Opendatasoft.UrlExtractor.get_resources_with_url_from_csv/1 (6) (Transport.UrlExtractorDocTest)
     apps/transport/test/transport/url_extractor_doc_test.exs:4
     ** (EXIT from #PID<0.6152.0>) killed
```

J'ai vérifié dans un premier temps qu'aucune requête externe n'était émise, et en fait si aucun serveur n'est contacté, on fait quand même un `HTTPoison.head` sur une fausse URL. Je me demande s'il n'y a pas un souci de sync/async par rapport au fait que `HTTPoison` est modifié via `with_mock`.

On gagnera à utiliser le "shared impl" généralisé par @fchabouis dans #1745 sur cet extracteur.

Je crée le ticket pour qu'on revisite ça plus tard.

**Comment by AntoineAugusti** [comment]
J'ai eu une erreur lié à ce test récemment. Ce n'était pas lié à une requête externe qui échouait, mais quand je référençais un asset (image dans mon cas) que je n'avais pas commit dans ma branche, et qui donc n'était pas trouvé à l'étape CI.

Fin mot de l'histoire ou rien à voir, à voir :)

**Comment by AntoineAugusti** [comment]
En lançant **sans réseau**

```sh
mix test apps/transport/test/transport/import_data_service_test.exs
```

je constate que les tests échouent. Les cassettes ne semblent donc pas utilisées ici. Je n'ai pas trouvé pourquoi, mais j'ai vérifié que [TransportWeb.ExternalCase](https://github.com/etalab/transport-site/blob/master/apps/transport/test/support/external_case.ex) était bien chargé.

Un exemple d'erreur décrit dans https://github.com/etalab/transport-site/issues/1757#issuecomment-906321570 sur [CircleCI](https://app.circleci.com/pipelines/github/etalab/transport-site/2148/workflows/f83cf156-7229-47c1-b78a-a204f463e06b/jobs/29057)

**Comment by thbar** [comment]
Nouvelle occurrence https://app.circleci.com/pipelines/github/etalab/transport-site/2154/workflows/b65368d2-05e1-4b9b-ab7c-db9d8f9082f9/jobs/29098/parallel-runs/0/steps/0-102

**Comment by AntoineAugusti** [comment]
La PR #1863 semble résoudre le problème ! Je ferme, en espérant ne pas avoir à ouvrir à nouveau cette issue.
