### ISSUE TITLE
Programmer des mails de rappel de mise à jour des GTFS 1j, 3j et 7j après expiration pour les GTFS affiliés à une région ou une commune sur data.gouv.fr

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#1758]
On envoyait jusqu'à l'été dernier des mails de rappel avant que le GTFS ne soit périmé (14j, 7j et la veille), ce qui embêtait certains producteurs : les régions, par exemple, ne pouvaient pas mettre à jour les GTFS tant que les collectivités n'envoyaient pas leurs fichiers. Envoyer un mail aux régions n'étaient donc pas utile 

Peut-on remettre en place les mails de rappel de mise à jour après expiration des données seulement pour les GTFS affiliés à une AOM ou à une commune data.gouv.fr ? 
![image](https://user-images.githubusercontent.com/59559301/131074830-85d98a63-5cd0-41b6-820c-b463cb57c1e9.png)

**Comment by AntoineAugusti** [comment]
C'était bien un doublon et c'est implémenté.
