### ISSUE TITLE
[proxy] Permettre de tester une configuration avant le merge de sa PR

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#1761]
Quand on modifie la configuration du proxy Elixir, le processus recommandé pour l'instant est le suivant:

1. Faire une PR (bien à jour de `master`) ([exemple](https://github.com/etalab/transport-proxy-config/pull/16)
2. La vérifier visuellement puis la merger
3. Aller sur prochainement dans le backoffice, puis recharger la configuration proxy
4. Tester sur prochainement (attention le lien est cassé voir #1760)
5. Si c'est bon, aller sur prochainement dans le backoffice, et recharger la configuration proxy
6. Faire un test sur le lien en proxy

Je crée ce ticket pour penser à mettre en place une stratégie qui permettra de valider avant le merge (ex: configuration backoffice qui supporte la notion de branche, ou vérification du format via une GitHub action dans le merge).

**Comment by AntoineAugusti** [comment]
Ce commit https://github.com/etalab/transport-proxy-config/commit/8695afb7a541dad0deb8bdb3bcf81f88bcd3a5b2 vérifie la configuration dans le YAML et vérifie que ça retourne bien un 200 OK. C'est exécuté sur les PRs. On pourrait faire mieux plus tard, mais c'est une amélioration pour le moment !
