### ISSUE TITLE
Ajout de la catégorie stationnement vélo

### ISSUE THREAD

**Issue by NicolasBerthelot** [etalab/transport-site#1764]
Nous avons un premier jeu de données à référencer dans la catégorie stationnement vélo : https://www.data.gouv.fr/fr/datasets/stationnement-velo-ouest-cornouaille/
Il faudrait passer de "A venir dans les prochains mois" à "Les données disponibles" cette catégorie.

**Comment by AntoineAugusti** [comment]
Fait dans https://github.com/etalab/transport-site/pull/1781. Il manque une petite traduction mais ce sera intégré dans https://github.com/etalab/transport-site/pull/1793
