### ISSUE TITLE
Evaluer la qualité du flux GBFS v2.2 de Tier 

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#1776]
Données Grenoble : 

 https://data-sharing.tier-services.io/tier_grenoble/gbfs/2.2

**Comment by thbar** [comment]
Je partage quelques liens que j'ai glané sur le sujet :

- https://github.com/NABSA/gbfs/wiki/Roadmap#gbfs-validator roadmap NABSA pour leur validateur GBFS
- https://github.com/fluctuo/gbfs-validator le validateur de Fluctuo (version hébergée ici https://gbfs-validator.netlify.app je crois)
- https://github.com/MobilityData/gbfs-json-schema

On pourrait utiliser les outils disponibles, en plus d'une analyse manuelle, pour regarder la qualité.

**Comment by Miryad3108** [comment]
Merci pour ces premiers retour @fchabouis : 
pour l'endpoint free_bike_status, l'idéal serait d'avoir un TTL inférieur ou égal à 2min ?
