### ISSUE TITLE
Ajout nouveau réutilisateur :  Communauté d'agglomération Le Cotentin

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#1778]
Page datagouv : https://www.data.gouv.fr/fr/reuses/cap-cotentin/

Première collectivité qui déclare une réutilisation 🎉

![CapCotentin-logo-rose](https://user-images.githubusercontent.com/59559301/133141269-60542b0a-dde6-40fd-81d5-dbc0bbcc7631.png)

**Comment by AntoineAugusti** [comment]
Ça part en production 🚀
