### ISSUE TITLE
Avoir une section "Zoom sur les formats de données" pour le temps-réel des transports en commun - Page stat

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#1779]
Peut on ajouter une section "Zoom sur les formats de données" pour le temps-réel des transports en commun comme celle pour le temps théorique des transports en commun dans la page stat ? 

![image](https://user-images.githubusercontent.com/59559301/133200081-519fb425-8331-4867-b9d8-373a27b8c6d2.png)

Pour l'instant on a que du GTFS-RT mais on a espoir d'avoir du SIRI d'ici la fin de l'année

**Comment by andlio** [comment]
@Miryad3108,

1. Quels sont les formats qui doivent apparaître ? J'ai identifié "GTFS RT", "SIRI", "SIRI Lite" et "Non standard". Correct ?
2. Pour la partie de droite, on reste sur le même modèle ? description + répartition entre les différents formats ?

**Comment by NicolasBerthelot** [comment]
- Yes parfait pour les formats. 
- Oui c'est très bien pour la description. 
- Pour les multiples formats on compte 1 par format (comme c'est le cas pour le GTFS et le NeTEx)

**Comment by andlio** [comment]
> * Pour les multiples formats on compte 1 par format (comme c'est le cas pour le GTFS et le NeTEx)

Qu'entends-tu par là ?

Pour le théorique, si plusieurs formats sont disponibles pour un dataset donné, on les affiche en orange sous le libellé "GTFS et Netex".
<img width="240" alt="Capture d’écran 2021-09-21 à 14 23 40" src="https://user-images.githubusercontent.com/6974621/134169790-cbda5aa1-f089-4b6c-b6c2-379b2f27c36a.png">

Comment reproduire ce cas avec 3 types de formats possibles ?

**Comment by NicolasBerthelot** [comment]
Ah yes t'as raison... effectivement multiple semble être la bonne solution (je pensais à la barre à droite où on décompte la part de GTFS et NeTEx)

**Comment by andlio** [comment]
Exemple :

<img width="715" alt="Capture d’écran 2021-09-21 à 15 42 39" src="https://user-images.githubusercontent.com/6974621/134181803-857625db-e8c8-4d79-86b4-1804211433aa.png">

**Comment by Miryad3108** [comment]
C'est possible de changer les couleurs de la légende ? 
Mettre GTFS-RT en bleu, SIRI-Lite en vert clair, SIRI en vert foncé, Non standard toujours en rouge et multiple en orange ? 

Quand je vois du vert ça me fait penser à quelque chose de "valide"/"correct" donc je me dis que c'est mieux de mettre le SIRI en vert 

(et faire le changement sur la carte du théorique pour garder une cohérence entre la couleur du GTFS et du GTFS-RT : que le GTFS soit bleu également dans la carte des horaires théoriques. Le Netex sera vert du coup)

**Comment by andlio** [comment]
> @andlio C'est possible de changer les couleurs de la légende ?

Oui c'est possible ! Je vais te faire ça.

Concernant la partie de droite avec les chiffres.


Pour le théorique on a  actuellement une jauge de répartition 👇
<img width="1131" alt="Capture d’écran 2021-09-24 à 15 19 21" src="https://user-images.githubusercontent.com/6974621/134681449-04ddafdc-b888-45a4-97f2-aaa63711a492.png">

C'est cohérent parce qu'il n'y a que 2 formats : GTFS à gauche et Netex à droite.

Avec plus de 4 formats ça devient illisible.
Alors voici plusieurs propositions:

1. Uniquement des chiffres (Comme c'est le cas actuellement pour la répartition par AOM)
<img width="1165" alt="Capture d’écran 2021-09-24 à 14 45 47" src="https://user-images.githubusercontent.com/6974621/134681714-ec274a80-cf3a-4e98-9cef-d4e2ea5702c6.png">
2. Uniquement des chiffres (comme le théorique sans la jauge)
<img width="1113" alt="Capture d’écran 2021-09-24 à 14 48 21" src="https://user-images.githubusercontent.com/6974621/134682091-c6443f27-85f7-4792-908e-c982b0d801ba.png">
3. Une jauge avec des couleurs correspondants à la légende
<img width="1118" alt="Capture d’écran 2021-09-24 à 15 18 17" src="https://user-images.githubusercontent.com/6974621/134682252-1972f4f7-3a5b-4072-84a1-7c59957a7159.png">

**Comment by fchabouis** [comment]
Je crois que j'aime bien la proposition 1. qui me semble mettre moins visuellement les formats en concurrence les uns avec les autres.

**Comment by andlio** [comment]
Je n'ai pas trouvé de solution satisfaisante pour compter le nombre de ressources RT non standard.
Donc pour le moment j'ai tout simplement supprimé le compteur.
J'ai également supprimé la description qui était redondante avec la stat du dessus :

![image](https://user-images.githubusercontent.com/6974621/135099161-ba61bf05-4014-4797-92bc-23ceb30cfce5.png)

**Comment by andlio** [comment]
Avec le changement de couleurs :
![image](https://user-images.githubusercontent.com/6974621/135113949-5a5d9bf2-af96-4287-a911-baf2d1fd0b4b.png)

J'ai également modifié les couleurs du théorique pour plus de cohérence
![image](https://user-images.githubusercontent.com/6974621/135114206-790689ac-7d48-4430-87f1-dc09b0336dc4.png)

**Comment by fchabouis** [comment]
cool !
