### ISSUE TITLE
Mise à jour OTP à prévoir avant fin septembre (gestion SSL)

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#1786]
Fin septembre, un ["root certificate" associé à lets encrypt va périmer](https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/).

Ce point est expliqué en détail sur les articles suivants:
- https://blog.voltone.net/post/29
- https://blog.voltone.net/post/30

Pour éviter des perturbations sur tous les systèmes de l'application (imports, installations éventuelles, et de façon générale tous les systèmes utilisant des échanges HTTPS), il est préférable de traiter ce point en avance de phase.

Les actions requises sont (d'après ma lecture de https://blog.voltone.net/post/30):
- [x] Migrer à OTP 24.0.4 (ou +). Nous sommes (au moment où j'écris ceci) sur 24.0.3 ([voir ici](https://github.com/etalab/transport-site/blob/15a357986bd6b1c3b2c0bac632fb5e74655f68a6/Dockerfile#L1)). Pour réaliser cela il est nécessaire de créer une nouvelle release sur https://github.com/etalab/transport-ops et de publier l'image de base sur Docker Hub (actuellement ; on discute d'une migration vers GitHub container registry)
- [ ] Idéalement upgrader à Mint 1.4.0 (https://hex.pm/packages/mint/1.4.0)

**Comment by thbar** [comment]
Au passage, Elixir 1.12.2 a été publié ; vu que la mise à jour de OTP passe par une reconstruction de l'image Docker de base, on peut éventuellement en profiter pour mettre à jour également Elixir, ce qui apportera quelques correctifs

https://github.com/elixir-lang/elixir/releases

**Comment by fchabouis** [comment]
la partie OTP va être traitée via https://github.com/etalab/transport-ops/pull/28 et #1785

**Comment by AntoineAugusti** [comment]
Cette issue devrait pouvoir être fermée avec le changement vers Ubuntu en production il me semble ?

**Comment by thbar** [comment]
@AntoineAugusti la partie OTP a bien été mise à jour effectivement dans #1785. J'ai coché la case correspondante.

Il restera idéalement à mettre à jour Mint (même si je n'ai pas vu de souci associé pour l'instant de mon côté).
