### ISSUE TITLE
L'import des datasets bike sharing semble cassé

### ISSUE THREAD

**Issue by fchabouis** [etalab/transport-site#1790]
https://transport.data.gouv.fr/backoffice/dashboard

![image](https://user-images.githubusercontent.com/15341118/134005131-ab46891c-9481-4184-9d07-cf3e270d093f.png)

On a des messages d'erreur du type "%MatchError{term: {:error, "%{region: [\"You need to fill either aom, region or use datagouv's zone\"]}"}}"

**Comment by thbar** [comment]
Bien vu ! Les carrés rouges apparaissent le 2 septembre.

J'ai regardé la timeline, je ne vois rien d'associé autour de ces dates (https://github.com/etalab/transport-site/commits/master).

On a peut-être une cause externe, à vérifier !
