### ISSUE TITLE
Changer le logo mariane sur le blog

### ISSUE THREAD

**Issue by fchabouis** [etalab/transport-site#1792]
![image](https://user-images.githubusercontent.com/15341118/134151106-9fc6d102-ed36-49c5-853f-ffee9ddbcd58.png)

Il faudrait mettre le même que sur le site principal.

**Comment by AntoineAugusti** [comment]
![image](https://user-images.githubusercontent.com/295709/134302499-9a266b3d-1441-4aa9-9d38-a313cd8323f8.png)

L'issue ne mentionne que le header mais j'imagine qu'il faut changer aussi le footer.

Que faire ?

- Supprimer Marianne + logo transport
- Mettre uniquement la Marianne
- Mettre Marianne + transport
