### ISSUE TITLE
Page non existante retourne une 500

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#1794]
Une URL qui n'existe pas, par exemple https://transport.data.gouv.fr/notfound, retourne une erreur HTTP 500 actuellement https://transport.data.gouv.fr/notfound

Est-ce un comportement voulu ?

**Comment by thbar** [comment]
@AntoineAugusti non c'est involontaire ! Ca sent le souci lors d'une upgrade du système de routage.

**Comment by fchabouis** [comment]
En plus avant pour les 500 on avait une image de train qui sortait de la gare par sa facade :crying_cat_face:

**Comment by AntoineAugusti** [comment]
J'ai tenté de corriger ça, sans succès.

La stacktrace
```
[debug] Converted error Phoenix.Router.NoRouteError to 404 response
[error] #PID<0.3262.0> running TransportWeb.Endpoint (connection #PID<0.2912.0>, stream id 20) terminated
Server: localhost:5000 (http)
Request: GET /dzqd
** (exit) an exception was raised:
    ** (ArgumentError) session not fetched, call fetch_session/2
        (plug 1.12.1) lib/plug/conn.ex:1567: Plug.Conn.get_session/1
        (plug 1.12.1) lib/plug/conn.ex:1550: Plug.Conn.get_session/2
        (transport 0.0.1) lib/transport_web/templates/layout/app.html.eex:2: TransportWeb.LayoutView."app.html"/1
        (phoenix 1.5.9) lib/phoenix/view.ex:472: Phoenix.View.render_to_iodata/3
        (phoenix 1.5.9) lib/phoenix/controller.ex:776: Phoenix.Controller.render_and_send/4
        (phoenix 1.5.9) lib/phoenix/endpoint/render_errors.ex:78: Phoenix.Endpoint.RenderErrors.instrument_render_and_send/5
```

Le problème semble venir du fait que le layout "app" a besoin de la session pour la langue HTML et pour le header si on est connecté (photo de profil etc). [`ErrorView`](https://github.com/etalab/transport-site/blob/master/apps/transport/lib/transport_web/views/error_view.ex) ne semble pas passer par la pipeline `browser`.

Je n'ai pas réussi à faire en sorte que la pipeline `browser` soit utilisée sur `ErrorView` ou appeler `fetch_session/2` au bon endroit.

**Comment by fchabouis** [comment]
J'ai regardé ce matin, je partage avec toi ce que j'ai compris.

On voit dans apps/transport/lib/transport_web/router.ex que toutes les requêtes qui arrivent passent dans le pipeline "browser", qui à son tour appelle la fonction `put_locale`. Ce qui fait qu'ensuite on peut appeler les fonctions get_session dans nos templates.

En cas de route non trouvée, c'est automatiquement les views du fichier "error_view.ex" qui sont invoquées.

Les templates sous jacents appelent la fonction `get_session`.

Ca fonctionne si tu  fais `https://transport.data.gouv.fr/datasets/dfsfdfd`, on a bien une 404.

Mais si tu appelles `https://transport.data.gouv.fr/dfsfdfd`, il semble que la requête ne passe pas dans le pipeline et du coup l'appel à `get_session` dans les templates plante.

J'ai posé une question [ici](https://elixirforum.com/t/phoenix-router-no-pipelines-invoked-for-404/42563), parce que je vois pas comment gérer ce problème simplement alors que c'est assez basique comme situation.
