### ISSUE TITLE
HTTPoison ne gère pas les réponses 308

### ISSUE THREAD

**Issue by fchabouis** [etalab/transport-site#1801]
HTTPoison s'appuie sur Hackney et ne gère pas les réponses 308 ([permanent redirect](https://http.cat/308)).

Il faudrait réfléchir à comment on veut gérer ça (changer de lib ? faire une sorte de wrapper pour les requêtes http, et y ajouter du code pour gérer les 308 ?).

J'ai quick fixé le problème d'import qui en résultait (#1800) mais ça peut peter ailleurs.

**Comment by AntoineAugusti** [comment]
La PR n'a pas été encore review malheureusement. Patience !

**Comment by thbar** [comment]
J'ai tenté une relance pour voir si on peut aider. À suivre !

**Comment by AntoineAugusti** [comment]
Hackney a fait des releases mais ce n'est pas encore présent dans HTTPoison https://github.com/edgurgel/httpoison/blob/b562a286617e055a6793a6f6e82050d77eeebec0/mix.lock#L12

**Comment by AntoineAugusti** [comment]
Le mainteneur de HTTPoison avait indiqué que ça devrait fonctionner désormais mais je n'observe pas ça 🤔 

https://github.com/edgurgel/httpoison/issues/447#issuecomment-1812033848

**Comment by thbar** [comment]
> Le mainteneur de HTTPoison avait indiqué que ça devrait fonctionner désormais mais je n'observe pas ça 🤔

Merci pour le retour. Ce type d'élément renforce ma position "long terme" (sans urgence) de plutôt aller vers le pack req/finch/mint.

Il est encore un peu tôt cela dit, ce ticket sera intéressant à suivre:

- https://github.com/wojtekmach/req/issues/269

**Comment by AntoineAugusti** [comment]
Il est possible que j'ai fait une erreur mais je ne vois pas où.

**Comment by AntoineAugusti** [comment]
@thbar Oh mon dieu 😬 🙈 https://github.com/edgurgel/httpoison/issues/447#issuecomment-1829113965

Bon, je regarderai prochainement si on peut supprimer du code chez nous du coup !

**Comment by thbar** [comment]
@AntoineAugusti oué j'ai vu ! Bon et bien la bonne nouvelle c'est que c'est vraiment corrigé 😄
