### ISSUE TITLE
Investigation : pourquoi CC restart l'appli tous les matins

### ISSUE THREAD

**Issue by fchabouis** [etalab/transport-site#1803]
à ~6h30.

![image](https://user-images.githubusercontent.com/15341118/134865271-bb9baa3c-c1ad-424d-ab26-9e621b222b11.png)

**Comment by thbar** [comment]
Indices supplémentaires:
- ça se produit sur les deux applications grosso modo dans la même tranche horaire
- j'ai contacté CC et il n'y a rien de leur côté
- en fait quand on regarde l'heure, c'est 6h25-6h35, mais (Tadam) UTC+2, soit 4h25-4h35 GMT.

C'est donc très probablement lié au cron d'import qui tourne à 4h00 UTC (soit 6h00 UTC+2) et dure un moment:

https://github.com/etalab/transport-site/blob/af026fd3df7d262ef9a09ccb7e799c7712bdf41f/config/prod.exs#L15-L19

Je vais aller fouiller dans les logs.

**Comment by thbar** [comment]
J'ai regardé rapidement les logs via l'interface ; je cherche à présent quelque chose de plus précis.

On peut utiliser la commande d'extraction de logs suivante pour contourner la limite de CleverCloud sur ce point (https://github.com/CleverCloud/clever-tools/issues/403):

```
mix clever.logs --since "2021-09-27T04:15:00Z" --before "2021-09-27T04:45:00Z" --alias "transport-site" | tee thelogs.log
```

**Comment by thbar** [comment]
Le redémarrage semble se produire (pour le 27 et le 26) durant la phase de validation.

Pour le 27 je vois 215 logs "Validating http", et pour le 26 septembre, 161.

Je suis tenté de croire qu'on a quelque chose comme un leak mémoire, qui s'empilerait jusqu'à faire planter la machine.

J'essaie d'obtenir les métriques de mémoire, mais la plateforme CC semble avoir du mal. Je vais les contacter.

**Comment by thbar** [comment]
Pour référence, le log en question est ici:

https://github.com/etalab/transport-site/blob/0b3e6fb60605548d495c46fcf1159b389ec6ad7c/apps/db/lib/db/resource.ex#L134

@fchabouis se demande si il y a un lien avec les nouvelles méthodes de streaming HTTP et l'utilisation de "throw" ici https://github.com/etalab/transport-site/blob/0b3e6fb60605548d495c46fcf1159b389ec6ad7c/apps/shared/lib/http_stream_v2.ex#L64.

Je vais aller enquêter et recouper ça avec les graphiques que CleverCloud va m'envoyer.

**Comment by thbar** [comment]
J'ai eu des échanges avec CleverCloud qui ont fait bouger les lignes:
- les métriques sont normalement débuggés
- on a un accès beta à Grafana via http://grafana.services.clever-cloud.com/

Toutefois depuis l'ouverture à Grafana, le problème ne s'est pas posé à nouveau. 

Je garde ouvert et je retournerai voir.

**Comment by thbar** [comment]
Le phénomène s'est arrêté de lui-même. Je clôture, on ré-ouvrira si ça se reproduit.
