### ISSUE TITLE
Génération incomplète des ressources communautaires des GTFS du jeu de données "Agrégats de réseaux urbains et interurbains de la Métropole Aix-Marseille"

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#1804]
https://transport.data.gouv.fr/datasets/reseaux-de-transports-en-commun-de-la-metropole-daix-marseille-provence-et-des-bouches-du-rhone/

- 10 ressources sur 16 ont été converties en geojson et Netex
- les titres des ressources communautaires ne sont pas les mêmes que ceux des GTFS

J'ai fais "générer les ressources communautaires" dans le backoffice mais pour l'instant, pas de changement

**Comment by thbar** [comment]
@fchabouis tu sais où aller voir pour comprendre ce qui se passe là dessus je crois ?

**Comment by fchabouis** [comment]
Sur le nombre, c'est normal car comme on ne gère pas la pagination et qu'on a 20 ressources par page de requete sur data.gouv.fr, et que chaque GTFS génère 2 ressources communautaires, on retombe bien sur le 10 ressources GTFS sur 16 ont des ressources communautaires

par contre hum il y a 534 ressources communautaires générées pour ce dataset sur data.gouv.Fr

![image](https://user-images.githubusercontent.com/15341118/134874808-c4bb10d5-768a-4a5c-a60f-e8ac3417207c.png)


A mon avis c'est le coup du zip généré à la volée coté producteur, avec un hash qui change a chaque fois. Du coup tous les jours on créé 16 * 2 = 32 ressources communautaires et on n'en supprime que 20 (à cause du bug sur la pagination). Donc il y en a 12 de plus chaque jour


Bonne nouvelle ça va être normalement résolu très vite par @Lionel ANDRÉ et sa PR en cours sur la pagination :thumbsup:
