### ISSUE TITLE
Jouer avec le validateur GTFS de MobilityData

### ISSUE THREAD

**Issue by fchabouis** [etalab/transport-site#1805]
### Contexte

Pour nourrir l'issue, voilà les billes dont je (@thbar) dispose:
- Le validateur GTFS dont on parle et qu'on souhaite intégrer est https://github.com/MobilityData/gtfs-validator.
- Au moment où j'écris ces lignes, il est disponible en v2.0.0
- La v3.0.0 est en développement (j'ai posé la question de sa date de publication [ici](https://mobilitydata-io.slack.com/archives/C3FFFKX9C/p1632733342003900))
- L'intégrer fournit une grosse valeur car c'est le "validateur canonique", et il fournira de la valeur autant pour la qualité des petits acteurs que des plus gros (par exemple, on sait à présent que Google se sert de ce validateur en interne)

Suite aux premiers échanges dans l'équipe transport, l'intérêt pour ce validateur a été détecté et confirmé, ce qui a donné lieu de notre côté à la création d'un projet qui crée une image Docker comprenant cet outil (ainsi que d'autres):

https://github.com/etalab/transport-tools

L'image Docker est automatiquement publiée ici https://github.com/etalab/transport-tools/pkgs/container/transport-tools

### Idées

Pour faire un test assez proche de ce qu'on fera en production plus tard, on peut s'appuyer sur l'image Docker, quitte à monter un répertoire comme volume (ex: https://github.com/livebook-dev/livebook#docker).

Il sera utile de vérifier:
- l'exit code après l'exécution (voir notes sur Rambo dans https://github.com/etalab/transport-site/pull/1802/files)
- si on peut récupérer une sortie structurée type JSON
- comment on le configure de façon générale

Et de partager ça avec les autres dévs !

**Comment by thbar** [comment]
J'ai ajouté des notes pour partager ce que j'avais en tête jusque là, directement en description là haut.

**Comment by thbar** [comment]
J'ai oublié un petit point: on peut lancer le programme avec :

```
docker run -a stdout -t ghcr.io/etalab/transport-tools:master java -jar gtfs-validator-v2.0.0_cli.jar
```

(il manque le volume à partager entre le host et le container)

**Comment by isabelle-dr** [comment]
Si vous avez des questions, n'hésitez pas à nous contacter! 🙂
Nous avons la release 3.0 [en beta](https://github.com/MobilityData/gtfs-validator/releases) qui contient d'avantage de règles et où plusieurs bugs ont été réglés. 
La documentation est à jour dans la [branche v3.0.0 beta](https://github.com/MobilityData/gtfs-validator/tree/v3.0.0-beta).

**Comment by thbar** [comment]
Merci @isabelle-dr pour le "ping" !

Nous sommes en train de refondre notre architecture pour intégrer des outils tiers, donc ça tombe à pic. Merci !

**Comment by fchabouis** [comment]
@ChristinaLaumond propose dans un premier temps de mentionner le validateur de MD dans la doc à cet [endroit](https://doc.transport.data.gouv.fr/reutilisateurs/qualite-de-donnee#le-validateur-gtfs)

**Comment by thbar** [comment]
On n'en a pas parlé depuis un moment, est-ce qu'on clôture, ou est-ce qu'on garde ouvert pour y repenser à l'occasion ?

/cc @etalab/transport-bizdev @etalab/transport-tech

**Comment by thbar** [comment]
On va fermer pour l'instant, mais ça reviendra peut-être sur la table à un moment.
