### ISSUE TITLE
Certains GTFS (zip) incluent un sous-répertoire avec les fichiers (au lieu des fichiers directement)

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#1815]
Je suis tombé sur des fichiers (je les retrouverai et je noterai ici les références) zip GTFS qui ne contiennent pas directement les fichiers CSV, mais un sous-répertoire qui lui-même contient les fichiers CSV.

Le validateur MobilityData (voir #1805) considère cela comme une erreur.

La spécification (https://github.com/google/transit/blob/master/gtfs/spec/en/reference.md) indique:

> All dataset files must be zipped together.

Voir aussi https://gtfs.org/getting-started/

On ne voit pas explicitement de demande de ne pas inclure un sous-répertoire, toutefois je pense que c'est plus une coquille, et que la spécification sous-entend ce point.

On gagnera à vérifier combien de GTFS sont dans ce cas et à alerter les producteurs concernés.

Je remonterai cette imprécision aux mainteneurs.

**Comment by thbar** [comment]
@fchabouis je me demande quel est le comportement du validateur maison là-dessus, tu as une idée ?

Si ça pouvait être intercepté, on pourrait clôturer ce ticket.

**Comment by thbar** [comment]
Je clôture pour le moment, on pourra ouvrir à nouveau si besoin.

**Comment by fchabouis** [comment]
Je viens de tester. Notre validateur valide le GTFS quand même, mais sort une "information" de fichier superflu.
