### ISSUE TITLE
Bug lien schémas

### ISSUE THREAD

**Issue by NicolasBerthelot** [etalab/transport-site#1816]
La mise à jour de schema.data.gouv.fr a dû rendre caduque nos liens vers les schémas présents dans les fiches ressources : 
![image](https://user-images.githubusercontent.com/61453166/135632834-5ed6b106-d333-4c75-a844-ba952d2f5a86.png)
Le lien actuel renvoie vers une 404 : https://schema.data.gouv.fr/etalab/schema-irve/2.0.0.html

Il faudrait fixer ce bug et renvoyer vers de bonnes URL.

**Comment by AntoineAugusti** [comment]
Ce bug est dû à un changement côté schema.data.gouv.fr récent. https://github.com/etalab/schema.data.gouv.fr/issues/195 On va voir comment corriger ça rapidement mais aussi de manière durable pour d'autres personnes

**Comment by AntoineAugusti** [comment]
@NicolasBerthelot C'est réparé et déployé en production ! Merci d'avoir ouvert un ticket. N'hésitez pas à tenir aux courants les utilisateurs @Miryad3108 @NicolasBerthelot
