### ISSUE TITLE
Rendre la façon de configurer compatible avec les "releases Elixir"

### ISSUE THREAD

**Issue by fchabouis** [etalab/transport-site#1817]
Actuellement, l'application est compilée, puis démarrée, directement dans un container Docker qui dispose de toutes les variables d'environnement sous le coude.

Pour pouvoir à terme utiliser des releases Elixir, il est nécessaire de mettre au propre un peu plus la configuration, et faire en sorte que:
1. la compilation puisse se faire sans aucune variable d'environnement (autre que `MIX_ENV=prod`) ; on pourra ainsi compiler n'importe où sans problème (ex: GitHub actions) et sans credentials sous le coude (RGPD/conformité/défense par couches)
2. la configuration dont les éléments s'appuient sur une variable ENV ne soit plus dans les fichiers compilés (à savoir `config/*.exs` sauf `runtime.exs` qui est le seul lu au runtime), mais dans `runtime.exs`

### Solidité de runtime.exs

Il faut également gérer le fait que la configuration `runtime.exs` peut être fragile, car non vérifiée pendant le développement.

L'idée pour traiter ce point est de créer plutôt un module "configuration", qui lui sera sous test, et prendra en entrée un ENV simulé, et permettra d'asserter le retour derrière. Ensuite `runtime.exs` n'aura plus qu'à utiliser ce module pour avoir quelque chose de solide (à vérifier, c'est une idée).

### Verrouiller le fonctionnement pour ne pas avoir de régression

On pourrait également avoir un check credo ou similaire, qui empêche de retrouver les points problématiques dès le développement.

Exemples d'endroits qui posent problème:

https://github.com/etalab/transport-site/blob/517adfceadf31b01e4acbe322ef550f0e3d64163/apps/transport/lib/transport_web/router.ex#L159-L162

https://github.com/etalab/transport-site/blob/927383cc2157f5f56b7383cf8d34e530ede95889/config/mailjet.exs#L6-L7

https://github.com/etalab/transport-site/blob/927383cc2157f5f56b7383cf8d34e530ede95889/config/mailchimp.exs#L4

Tout le `config/config.exs`, `config/datagouvfr.exs`, `config/prod.exs`, `config/gtfs_validator.ex`, `config/gbfs_validator.exs`, bref tous les fichiers sous `config/*.exs` hormis `runtime.exs`

**Comment by thbar** [comment]
Quelques informations pertinentes que j'ai glané petit à petit sur ce sujet :
- le déploiement actuel sur Clever prend environ 11 minutes (à la louche)
- une compilation en release sur GitHub sera bien plus rapide (avec ou sans cache) sur la base de ce que j'ai vu pour l'instant
- il y aurait encore quelques adaptations de code et des verrous à mettre en place
- un chaînon manquant serait une GitHub action comme https://github.com/47ng/actions-clever-cloud, qui permettrait (à vérifier dans la réalité) de déclencher le déploiement sur commande côté GH
- il resterait à gérer le stockage des releases

Je ne me précipite pas sur cette tâche, mais je note ces différents points pour le futur.
