### ISSUE TITLE
Ressource GTFS-RT détecté comme un GTFS : Niort 

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#1824]
Le GTFS-RT de Niort a été détecté comme étant un GTFS 
https://transport.data.gouv.fr/datasets/donnees-gtfs/

**Comment by fchabouis** [comment]
Il faut que le producteur renseigne gtfs-rt dans le champ format sur data.gouv.fr et non pas "url"
![Image Pasted at 2021-10-5 13-40](https://user-images.githubusercontent.com/15341118/136016268-13e3e48e-7258-43f7-bb82-e2bb8f5ac39b.png)

**Comment by Miryad3108** [comment]
La valeur du champ "format" a été modifiée : ce n'est plus "URL" mais "gtfs-rt". Les données sont désormais identifiées comme étant du GTFS-RT. Merci 🙂
