### ISSUE TITLE
Site accessible sur 2 domaines

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#1826]
La production est accessible depuis 2 domaines :

- http://transport.data.gouv.fr
- http://transport.beta.gouv.fr

Est-ce voulu ?

J'imagine que ceci pourrait causer des problèmes de SEO ou des confusions. Prévoir une redirection sur le domaine beta ?

**Comment by thbar** [comment]
@AntoineAugusti peu probable que ça soit voulu effectivement, bien vu ! Il faudra un redirect permanent, pour les raisons que tu évoques.

En problèmes connectés à celui-là, j'en profite pour faire un brain dump comme ça tu as du contexte :
- On a fait le ménage dans le DNS (AlwaysData) mais il faudra qu'on t'ajoute dedans (il y a sûrement des choses à purger encore) et qu'on passe en revue
- Il y a ce truc #1588 que j'ai découvert en fouillant comme toi, qui laisse à penser qu'on a un mode un peu legacy de configuration du DNS etc
- Il faudrait avoir une variable d'ENV qui fixe le nom de domaine canonique (qui serait `transport.data.gouv.fr` sur la production, et `prochainement.transport.data.gouv.fr` pour le staging). Ca permettrait de faire facilement du redirect permanent, voire des urls canoniques en meta.
- Voir #1688
- Voir #1760, on gagnerait aussi à avoir une variable explicite pour le nom de domaine du proxy (mais ça sera peut-être même pas nécessaire si on a le système décrit plus haut)

**Comment by thbar** [comment]
Toujours valable:

```
curl -I https://transport.beta.gouv.fr/
HTTP/1.1 200 OK
```

Il vaudrait mieux avoir un 301.

**Comment by AntoineAugusti** [comment]
J'ai dans l'idée de gérer ça dans un plug, faut que je m'en occupe

**Comment by thbar** [comment]
Suggestion -> verrouiller ça à l'aide d'un test ops ici https://github.com/etalab/transport-site/blob/master/ops_tests/ops_tests.exs, ça aide dans le temps.
