### ISSUE TITLE
Création de la Base Nationale des Zones à Faibles Emission

### ISSUE THREAD

**Issue by NicolasBerthelot** [etalab/transport-site#1845]
Il serait utile de rassembler les données des Zones à Faibles à Emission dans un seul jeu de données. 
3 jeux de données sont déjà publiés sur data.gouv.fr : 
- Métropole de Grenoble https://transport.data.gouv.fr/datasets/zfe-zone-a-faibles-emissions/
- Grand Reims https://transport.data.gouv.fr/datasets/zones-a-faibles-emissions-cugr/
- Ville de Paris https://transport.data.gouv.fr/datasets/zone-a-faibles-emissions-zfe/

Chacun des jeux de données peut contenir un ou deux fichiers : 
- un fichier GeoJSON décrivant la ou les zones concernées par la ZFE
- un fichier GeoJSON décrivant les tronçons couverts par la zone qui ont une réglementation différente

La Base Nationale reprendra la même structure : 
- un fichier GeoJSON représentant l'ensemble des zones concernées par une ZFE en France
- un fichier GeoJSON décrivant les tronçons couverts par la zone qui ont une réglementation différente

La question qui est à résoudre est le mode d'agragation des données. On peut tout d'abord produire cette base de données "manuellement", en rassemblant dans un même fichier GeoJSON les données des aires dans un autre fichier GeoJSON les données des tronçons routiers. 
Pour une version automatique, il sera nécessaire de : 
- détecter les fichiers associés à un schéma ZFE
- vérifier la validité des données
- distinguer un fichier concernant des tronçons et un fichier concernant des aires 
- assembler les données dans un fichier unique
- publier les données à chaque mise à jour au sein du jeu de données qui contiendra les fichiers

**Comment by AntoineAugusti** [comment]
J'ai regardé les premiers fichiers ZFE publiés sur le PAN. Voici ce que je remarque.

⚠️ Je poste au fur et à mesure, je vais éditer ce message

## Reims
Les données sont publiées à l'adresse https://transport.data.gouv.fr/datasets/zones-a-faibles-emissions-cugr/

- L'identifiant `id` est invalide par rapport au schéma. `200067213 00013-ZFE-001` devrait comporter un `-` au début et utiliser un SIREN au lieu d'un SIRET
- Les données géographiques sont publiées en EPSG::3857 et il me semble qu'on attend du EPSG::4326 (WSG84)
- Le validateur GeoJSON remonte des erreurs pour
   - `deux_rm_horaires` : Invalid type. Expected String but got Null.
   - `deux_rm_critair` : Invalid type. Expected String but got Null.
   
Le schéma actuel impose d'avoir des valeurs `string` pour ces champs et [n'accepte pas le champ null](https://github.com/etalab/schema-zfe/blob/1587c86d8b5d30f60bb522f00be28b8728a96eb4/schema.json#L141-L164). En lisant rapidement l'arrêté, les rm ne sont pas concernés par la ZFE, l'utilisation de `null` parait justifiée. Il faudrait penser à faire évoluer le schéma ?
- Certaines valeurs sont échappées alors qu'il semble que ce ne soit pas nécessaire comme `"url_site_information": "https:\/\/www.grandreims.fr\/les-competences\/developpement-durable\/zone-a-faibles-emissions-mobilite-zfem-du-grand-reims-14426.html"` ou les horaires notés `24\/7`.
- Le fichier est nommé `zfe-zone-cugr.geojson` et ne respecte pas la recommendation de nommage `zfe_zone_nom.geojson`

Le JDD a bien le tag `zfe` et est associé au schéma ZFE 👌

**Comment by AntoineAugusti** [comment]
## Comment consolider

Pour consolider de manière automatiquement, il faut pouvoir distinguer les ressources décrivant les zones et les tronçons pour chaque jeu de données dans la catégorie `low-emission-zones`. Ces ressources doivent être conformes au schéma.

Dans un monde parfait :
- le JDD est tagué `zfe` sur la plateforme
- les ressources ont le schéma ` etalab/schema-zfe` renseigné (x2 car le schéma décrit 2 fichiers)
- le fichier est nommé `zfe_zone_nom.geojson` ou `zfe_voie_speciale_nom.geojson`
- le type des ressources est bien identifié comme `geojson`

@NicolasBerthelot La [doc du PAN](https://doc.transport.data.gouv.fr/producteurs/zones-a-faibles-emissions) n'indique pas le nommage des fichiers contrairement à la [doc du schéma](https://schema.data.gouv.fr/etalab/schema-zfe/).

Actuellement,
- Pour [le JDD de Grenoble](https://transport.data.gouv.fr/api/datasets/5eab66a565c27001ac5f11ed), il n'est pas possible d'identifier le fichier de la zone automatiquement car l'URL distante est `https://data.mobilites-m.fr/api/normes/zfeaires` et il n'y a pas d'indication de schéma. 5 ressources sont au format `geojson`
- Pour [le JDD de Reims](https://transport.data.gouv.fr/api/datasets/61653a7c0f6c41710dd809eb), le fichier de zone est légèrement mal nommé (`zfe-zone-cugr.geojson`) mais il n'y a qu'une seule ressource, de type `geojson`. Le schéma ZFE est bien renseigné.
- Pour [le JDD de Paris](https://transport.data.gouv.fr/api/datasets/5eeae71835cd2e8a524fc1c2), il y a 2 fichiers au format `json` et une ressource intitulée "Export au format GeoJSON". L'export GeoJSON comporte bien `format=geojson` dans l'URL de la ressource ODS mais le format est indiqué comme `json`. Il n'est pas possible de savoir si les ressources concernent des aires ou des tronçons.

**Comment by AntoineAugusti** [comment]
Les données de Reims et Paris sont valides. J'ai contacté Grenoble pour déclarer quelques erreurs.

**Comment by AntoineAugusti** [comment]
Une idée de @fchabouis pour identifier aires VS voies, regarder la présence de `LineString`.

En regardant l'existant, 6 aires et 3 voies, si on regarde `LineString` + `MultiLinestring` c'est bien disjoint (présence de ces éléments uniquement dans les voies).

**Comment by AntoineAugusti** [comment]
Fait dans https://github.com/etalab/transport-site/pull/2311 ! Il y aura des améliorations possibles #2310
