### ISSUE TITLE
Créer tableau de suivi déploiement transport interurbain et scolaire

### ISSUE THREAD

**Issue by NicolasBerthelot** [etalab/transport-site#1847]
On a du mal à suivre à suivre l'ouverture des données à l'échelle intercommunale. En théorie il y a un réseau par région néanmoins l'ancienne structuration des transports publics a pour conséquence que les données sont généralement produites à l'échelle départementale. 
De la même manière pour le transport scolaire, il serait utile de mieux comprendre quelles données sont ouvertes et quelles données restent à ouvrir.

**Comment by Miryad3108** [comment]
@ChristinaLaumond il faudrait qu'on voit ensemble comment mettre en place ce suivi

**Comment by AntoineAugusti** [comment]
@etalab/transport-bizdev Je ferme cette issue, indiquez si on doit faire quelque chose.
