### ISSUE TITLE
Lister les ressources disponibles uniquement en HTTP

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#1854]
Suite de https://github.com/etalab/transport-site/issues/1709

Prévoir de lister les producteurs/domaines qui ont des ressources disponibles en HTTP voir s'il est possible de remplacer par du HTTPS

**Comment by AntoineAugusti** [comment]
@Miryad3108 ou @NicolasBerthelot, serait-il possible de sensibiliser les producteurs ci-dessus pour essayer de référencer des ressources avec des liens en `https://` au lieu de `http://` ? C'est important d'un point de vue sécurité et le HTTP seul est de plus en plus déprécié.

Il semble même que certaines ressources soient disponibles déjà en HTTP et HTTPS. Dans ce cas il faudrait "simplement" remplacer l'URL référencée.

**Comment by Miryad3108** [comment]
Je contacterai soit la collectivité soit le producteur des données (Cityway par exemple) cette semaine, merci 
Je ferai le suivi dans cette issue

**Comment by thbar** [comment]
Reste d'actualité, on gagnera à reprendre un suivi et refaire un petit calcul pour rafraîchir la situation.

**Comment by Miryad3108** [comment]
AMP https://transport.data.gouv.fr/datasets/146 : en cours de résolution avec Cityway - Relance le 9.08.2022
SMTCO https://transport.data.gouv.fr/datasets/506 : Partiellement résolu - Relance le 9.08.2022
Haute Garonne https://transport.data.gouv.fr/datasets/151 : en cours de résolution entre le département et opendatasoft - Relance le 9.08.2022
Nice https://transport.data.gouv.fr/datasets/13 :  Relance le 9.08.2022
Flixbus https://transport.data.gouv.fr/datasets/155 : Relance le 9.08.2022
Dracénie https://transport.data.gouv.fr/datasets/610 : Relance le 9.08.2022
Rennes https://transport.data.gouv.fr/datasets/507 et https://transport.data.gouv.fr/datasets/3 : résolu ✅​
Bretagne https://transport.data.gouv.fr/datasets/38 : résolu ✅​
La Roche-sur-Yon Agglomération https://transport.data.gouv.fr/datasets/492 : Résolu ✅​
Bourgogne-Franche-Comté https://transport.data.gouv.fr/datasets/505 : Résolu ✅​
Saint Malo https://transport.data.gouv.fr/datasets/607 :  Résolu ✅​
Ondéa https://transport.data.gouv.fr/datasets/612 : Résolu ✅​
Montpellier https://transport.data.gouv.fr/datasets/114 : Résolu ✅​
Hérault https://transport.data.gouv.fr/datasets/648 : Résolu ✅​
Vannes https://transport.data.gouv.fr/datasets/12 : Résolu ✅​
Rouen https://transport.data.gouv.fr/datasets/170 : Résolu ✅​
IGN https://transport.data.gouv.fr/datasets/314 : Résolu ✅​
Strasbourg https://transport.data.gouv.fr/datasets/20 : Résolu ✅​

**Comment by hugoguignardchab** [comment]
**UPDATE**
## Nombre de ressources disponibles en HTTP par AOMs

Avec > 1 ressource
![image](https://user-images.githubusercontent.com/85080846/183704747-cb963c29-642f-40cb-996b-ef78673e6872.png)

## Nombre de ressources disponibles en HTTP par nom de domaine
![image](https://user-images.githubusercontent.com/85080846/183705087-26467cd2-5741-4570-85a1-707b2e9bfb87.png)


## Nombre de ressources en HTTP par JDD

url                                                                   count
https://transport.data.gouv.fr/datasets/506  17
https://transport.data.gouv.fr/datasets/146  14
https://transport.data.gouv.fr/datasets/151  10
https://transport.data.gouv.fr/datasets/752  10
https://transport.data.gouv.fr/datasets/751    7
https://transport.data.gouv.fr/datasets/589    7
https://transport.data.gouv.fr/datasets/26      5
https://transport.data.gouv.fr/datasets/504    2
https://transport.data.gouv.fr/datasets/474    1
https://transport.data.gouv.fr/datasets/247    1
https://transport.data.gouv.fr/datasets/13      1
https://transport.data.gouv.fr/datasets/518    1
https://transport.data.gouv.fr/datasets/610    1
https://transport.data.gouv.fr/datasets/155    1
https://transport.data.gouv.fr/datasets/314    1

**Comment by Miryad3108** [comment]
Nice https://transport.data.gouv.fr/datasets/13 : Relance le 16.09.2022
Flixbus https://transport.data.gouv.fr/datasets/155 : Relance le 16.09.2022
SMTCO https://transport.data.gouv.fr/datasets/506 : en cours de résolution, échange avec eux en septembre 2022
AMP https://transport.data.gouv.fr/datasets/146 : résolu ✅​
Dracénie https://transport.data.gouv.fr/datasets/610 : résolu ✅​
Rennes https://transport.data.gouv.fr/datasets/507 et https://transport.data.gouv.fr/datasets/3 : résolu ✅​
Bretagne https://transport.data.gouv.fr/datasets/38 : résolu ✅​
La Roche-sur-Yon Agglomération https://transport.data.gouv.fr/datasets/492 : Résolu ✅​
Bourgogne-Franche-Comté https://transport.data.gouv.fr/datasets/505 : Résolu ✅​
Saint Malo https://transport.data.gouv.fr/datasets/607 : Résolu ✅​
Ondéa https://transport.data.gouv.fr/datasets/612 : Résolu ✅​
Montpellier https://transport.data.gouv.fr/datasets/114 : Résolu ✅​
Hérault https://transport.data.gouv.fr/datasets/648 : Résolu ✅​
Vannes https://transport.data.gouv.fr/datasets/12 : Résolu ✅​
Rouen https://transport.data.gouv.fr/datasets/170 : Résolu ✅​
IGN https://transport.data.gouv.fr/datasets/314 : Résolu ✅​
Strasbourg https://transport.data.gouv.fr/datasets/20 : Résolu ✅
Haute Garonne https://transport.data.gouv.fr/datasets/151 : le GTFS ne sera plus mis à jour. Les données seront intégrées dans [l'agrégat de l'Occitanie](https://transport.data.gouv.fr/datasets/fichiers-gtfs-de-la-region-occitanie).

**Comment by AntoineAugusti** [comment]
Les données actuelles

|domaine|nb|
|--- | ---|
|tipi.bison-fute.gouv.fr | 9|
|trafic-routier.data.cerema.fr | 8|
|www.pacamobilite.fr | 5|
|files.opendatarchives.fr | 1|
|opendata.nicecotedazur.org | 1|
|gieactiv.locbusspec.com:9404 | 1|
|gtfs.gis.flix.tech | 1|

|JDD|nb|
|--- | ---|
|https://transport.data.gouv.fr/datasets/752 | 10|
|https://transport.data.gouv.fr/datasets/751 | 7|
|https://transport.data.gouv.fr/datasets/26 | 5|
|https://transport.data.gouv.fr/datasets/518 | 1|
|https://transport.data.gouv.fr/datasets/314 | 1|
|https://transport.data.gouv.fr/datasets/155 | 1|
|https://transport.data.gouv.fr/datasets/13 | 1|

**Comment by fchabouis** [comment]
@ChristinaLaumond est au courant et va relancer les derniers.

**Comment by AntoineAugusti** [comment]
|dataset|nb|
|--- | ---|
|https://transport.data.gouv.fr/datasets/evenements-routiers-sur-le-reseau-routier-national-non-concede | 5|
|https://transport.data.gouv.fr/datasets/etat-de-circulation-en-temps-reel-sur-le-reseau-national-routier-non-concede | 2|
|https://transport.data.gouv.fr/datasets/export-quotidien-au-format-gtfs-du-reseau-de-transport-lignes-d-azur | 1|
|https://transport.data.gouv.fr/datasets/flixbus-horaires-theoriques-du-reseau-europeen-1 | 1|
|https://transport.data.gouv.fr/datasets/route-500 | 1|

|nom de domaine|nb|
|--- | ---|
|tipi.bison-fute.gouv.fr | 7|
|files.opendatarchives.fr | 1|
|gtfs.gis.flix.tech | 1|
|opendata.nicecotedazur.org | 1|
