### ISSUE TITLE
Documenter l'accompagnement proxy réalisé (doctrine actuelle etc)

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#1856]
Je travaille sur les supports pour l'atelier temps réel de jeudi 21 octobre. Il faudra prendre le temps de mettre à jour la documentation après l'atelier.

Du coup je reprends les éléments de langage qu'on a utilisé dans la dernière newsletter : nous avions indiqué "Nous publierons prochainement une documentation sur notre site qui développera ce sujet", et je les colle ici (voir en bas).

Par ailleurs je note les liens en relation ici:
- etalab/transport-private#7 - premier ticket interne qui décrivait la situation d'il y a quelques mois, avec point de situation
- https://doc.transport.data.gouv.fr/producteurs/operateurs-de-transport-regulier-de-personnes/temps-reel-des-transports-en-commun#le-pan-comme-serveur-proxy-pour-assumer-la-charge-serveurs (documentation partiellement à jour)
- https://doc.transport.data.gouv.fr/foire-aux-questions-1/donnees-temps-reel-des-transports-en-commun#formats évocation du proxy

## Contenu newsletter

(ce contenu servira de matière première pour la rédaction de la documentation)

#### 🤝 Un appui humain

L’ouverture et la mise à disposition des données temps-réel pour les transports en communs constituent une étape cruciale dans l'**amélioration de l’information voyageur**. Nos nombreux échanges avec les producteurs de données nous ont conduit à prendre conscience du défi que constitue l’accomplissement de ce chantier.

Nous nous tenons ainsi à disposition pour accompagner les acteurs, comprendre les points de friction et réfléchir aux solutions.

La **diffusion de ces données directement par les producteurs** doit rester un objectif, non seulement de façon à minimiser les maillons sur la chaîne de diffusion, réduire les délais de propagation de la donnée (notamment sur le cas du GTFS-RT), mais aussi afin que chaque acteur monte en compétence.

#### 🚀 Notre proxy temps-réel fait peau neuve

L’ouverture d’un flux temps-réel directement diffusé par le producteur peut être source d’incertitude et de craintes, et nous le comprenons !

Dans ce contexte, pour appuyer les acteurs dans la mise à disposition de leurs données en temps-réel, **nous avons modernisé notre proxy**.

Le but du proxy est que **le PAN assure la diffusion des données** (uniquement en GTFS-RT pour l’heure), en attendant que le producteur soit en mesure de les diffuser directement lui-même.

**Le mode d’emploi :**

1. Nous vous transmettons une URL suivant le modèle :
2. Nous fournir une URL nous permettant d’accéder à des données au format GTFS-RT : https://proxy.transport.data.gouv.fr/resource/nom_aom_gtfs-rt
3. Cette URL est référencée en tant que ressource temps-réel en complément des données statiques GTFS

Néanmoins la mise en place d’un proxy ajoute une étape dans la chaîne de distribution des données. Pour cette raison, **nous encourageons vivement les acteurs** qui le peuvent à diffuser leurs données temps-réel sans solliciter la mise-en-place d’un proxy.

#### 📲 Qu’en est-il du SIRI ?

Nous avons récemment suivi **une formation autour des normes européennes de données** (NeTEx et SIRI notamment). Celle-ci s’inscrit dans une phase de **montée en compétence de notre équipe** afin d’être en mesure d’accompagner au mieux les acteurs dans la prise en main de ces standards.

**Concernant notre proxy**, sa création pour les données au format SIRI est plus complexe, selon les modalités implémentées. Nous recueillons ainsi actuellement les besoins pour bien comprendre si un proxy SIRI serait réellement utile, et le cas échéant sur quels axes (gestion de charge via un cache, authentification, abonnements, relais vers des machines non exposées sur internet, etc).

Aussi, pour l’heure, nous ne proposons pas de service de proxy pour ce format d’échange de données, bien que notre équipe étudie actuellement sa faisabilité.

**Nous publierons prochainement une documentation sur notre site qui développera ce sujet !**

**Comment by thbar** [comment]
@Miryad3108 est-ce qu'on est à jour sur la doc de ce point de vue là à ton avis ? C'est pour voir si je peux fermer ce ticket. Merci !

**Comment by Miryad3108** [comment]
On est à jour oui, j'ai retranscris les informations dans la doc. Je ferme donc l'issue, merci d'avoir soulevé ce point.
