### ISSUE TITLE
Supprimer postgres_map_type: "json" (pour débloquer l'usage d'Oban)

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#1861]
À l'installation d'Oban (via les migrations) on obtient actuellement une erreur (que je copierai ici plus tard).

Je me suis aperçu en enquêtant que si on commente cette ligne, l'erreur disparaît:

https://github.com/etalab/transport-site/blob/74222d253f0dd3eaa71445d49e25c999fb562a73/config/database.exs#L12

Je vais aller prévenir l'auteur d'Oban de ce point, toutefois il faut aussi comprendre à quoi cela sert, et voir si c'est toujours d'actualité.

Discussion sur Slack: https://elixir-lang.slack.com/archives/CRDGH1XCM/p1634561500272400

**Comment by thbar** [comment]
J'ai compris, je vais documenter un peu ça.

**Comment by AntoineAugusti** [comment]
Devrait pouvoir être fermée désormais ?

**Comment by thbar** [comment]
@AntoineAugusti tout à fait ! merci, je clôture.
