### ISSUE TITLE
Homogénéiser nom des tuiles

### ISSUE THREAD

**Issue by NicolasBerthelot** [etalab/transport-site#1862]

**Comment by Benoit-MINT** [comment]
Horaires transports en commun --> Transport public collectif - horaires théoriques
Temps réel transports en commun --> Transport public collectif - horaires temps réel
Lieux de covoiturage --> Aires de covoiturage
Données aériennes --> Transport aérien
Données ferroviaires --> Transport ferroviaire
Aménagements cyclables --> Réseaux cyclables
Stationnement vélo --> Stationnement cyclable

Par ailleurs, nous pourrions réagencer plus pertinemment l'ordre des tuiles. Voici une proposition :
- Transport public collectif - horaires théoriques
- Transport public collectif - horaires temps réel
- Autocars longue distance
- Transport ferroviaire
- Transport maritime et fluvial
- Transport aérien
- Vélo et trottinettes en libre-service
- Réseaux cyclables
- Stationnement cyclable
- Réseaux routiers
- Zones à faibles émissions
- Aires de covoiturage
- Stations de réapprovisionnement de véhicules
- Stationnement hors voirie
- Adresse
- Autres informations

**Comment by NicolasBerthelot** [comment]
Bon bah ça arrive mais je suis à 100% d'accord avec tout ce que tu proposes que ce soit les nouveaux noms et l'ordre. 
Ce que j'ajouterai c'est qu'il faudrait normaliser les noms des schémas associés : 
- réseaux cyclable (@Miryad3108 t'en penses quoi ? =
- stationnement hors voirie 
- aires de covoiturage

**Comment by Miryad3108** [comment]
Réseaux cyclables je me méfie un peu de ce nom parce que j'ai l'impression que ça inclut aménagements cyclables et itinéraires cyclables alors qu'on ne fournira que les aménagements. On pourrait éventuellement référencer les itinéraires car les collectivités fournissent déjà ces données à V&T en respectant le schéma de V&T (certifié CNIG)

Aires de covoiturages : je laisserai plutôt "Lieux de covoiturage" parce qu'il n'y a pas que des aires de covoiturage dans le fichier. On retrouve aussi des délaissé routiers, sortie d'autoroute, arrêt auto-stop qui ne sont pas des aires de covoiturages mais sont utilisés comme des lieux de covoiturage. 

Pour le reste : entièrement d'accord

**Comment by Benoit-MINT** [comment]
Sur les aménagements cyclables, l'idée était d'homogénéiser avec la tuile relative aux données routières, et également en raison que c'est le terme juridique retenu. Mais je te rejoins ce n'est pas parfaitement limpide, tout comme d'ailleurs "aménagement" qui peut laisser sous entendre que cela correspond finalement aux aménagements parallèles aux infra cyclables ... mais comme le terme "réseau" permet d'intégrer à la fois "aménagement" et éventuellement "itinéraire", alors justement nommons la tuile "réseau" pour nous permettre d'y intégrer dedans les aménagements (en employant d'ailleurs ce terme pour le nom de la BD), et si l'opportunité est vérifiée, y intégrer les itinéraires.

ok pour le covoit

**Comment by Miryad3108** [comment]
D'acc 

Question pour les dev' aussi : si on référence les itinéraires cyclables (à voir en équipe et avec Vélo & Territoires si c'est ok), on pourra les mettre dans le même jeu de données que les aménagements et en faire un couple comme GTFS/GTFS-RT avec la ressource aménagement au dessus (position du GTFS dans le JDD) et la ressource itinéraire en dessous (position du GTFS-RT dans le JDD) ? 
cc @fchabouis

**Comment by Benoit-MINT** [comment]
Exact pour les changements.

Voici une proposition de traduction : 
Horaires transports en commun --> Transport public collectif - horaires théoriques --> Public transport - static shedules
Temps réel transports en commun --> Transport public collectif - horaires temps réel --> Public transport - realtime trafic
Données aériennes --> Transport aérien --> Air transport
Données ferroviaires --> Transport ferroviaire --> Rail transport
Aménagements cyclables --> Réseaux cyclables --> Bike networks
Stationnement vélo --> Stationnement cyclable --> same ...
