### ISSUE TITLE
[Bug] Conversion NeTEx Rennes Métropole

### ISSUE THREAD

**Issue by NicolasBerthelot** [etalab/transport-site#1864]
On nous rapporte de Rennes un problème de génération du fichier NeTEx : 

> Je vous contacte car la conversion GTFS en NeTEx ne semble pas complète et correcte sur  nôtre GTFS du STAR actuel.
> Je constate que seule la ligne de métro est traitée. Par ailleurs, le XML sur les horaires présentent des sauts de lignes un peu étrange.

Le dataset en question : https://transport.data.gouv.fr/datasets/versions-des-horaires-theoriques-des-lignes-du-reseau-star-au-format-gtfs/

**Comment by thbar** [comment]
@fchabouis si tu as l'énergie de creuser à un moment avec un outil tiers, ça serait top (sinon je remonterai ça en base à un moment).

**Comment by thbar** [comment]
Non élucidé pour le moment.
