### ISSUE TITLE
Mise en place d'un traitement tâches de fond isolé du site

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#1872]
En lien avec #1806, la prochaine itération consiste à faire évoluer l'architecture actuelle (tout sur un seul noeud CleverCloud) vers une architecture où un "worker" exécutera les traitements de fond, tandis que le "site" (front) sera protégé des éventuels crashs sur ces traitements de fond (surconsommation de RAM ou CPU, disque trop plein etc), de façon à garantir la disponibilité du site.

Nous allons faire un test avec [Oban](https://github.com/sorentwo/oban), qui est la solution de référence dans le monde Elixir, et qui est une queue de traitement s'appuyant sur Postgres.

Le scope de cette issue est :
- avoir la capacité à lancer la totalité des conversions GTFS vers GeoJSON (mais en mode "muté", sans utiliser la conversion ni les publier, pour cette première passe), en utilisant l'outil Rust déjà packagé dans l'image Docker, en toute isolation du front-end
- générer un crash artificiellement et observer ce qui se passe (comportement par rapport aux jobs en cours, comportement du front-end)

### Comment est lancée l'application aujourd'hui, et ce qui va devoir changer

Aujourd'hui, le site est lancé via cette commande:

https://github.com/etalab/transport-site/blob/390f8873dbbcafa0f9f22769a3e7bd49d17f8125/Dockerfile#L23

C'est une tâche qui est définie chez nous, et qui appelle en fait:

https://github.com/etalab/transport-site/blob/390f8873dbbcafa0f9f22769a3e7bd49d17f8125/mix.exs#L30

On aurait pu utiliser la fonctionnalité de "workers" de CleverCloud (https://www.clever-cloud.com/doc/develop/workers/), toutefois ça ne paraît pas nécessaire:

>  Those are especially useful for environments where you can’t have long-running processes such as PHP, Ruby or Python.

car on peut parfaitement lancer l'application "normalement" en Elixir, et la configurer pour ne traiter que la partie "jobs".

On va souhaiter disposer d'une commande unique (qui apparaîtra dans `ENTRYPOINT` à la place de `mix phx.migrate_phx.server` (du type `mix run --no-halt`), et que l'application se configure au runtime (via des flags qu'on met en place du type "WORKER=1").

Ceci permettra d'aller vers des builds sans configuration (releases Elixir configurées au runtime).

La tâche `mix phx.server`, elle, est fournie par Phoenix directement:

https://github.com/phoenixframework/phoenix/blob/master/lib/mix/tasks/phx.server.ex

On aurait pu souhaiter contourner cette tâche, comme indiqué dans la doc:

> Note: to start the endpoint without using this mix task you must set
  `server: true` in your `Phoenix.Endpoint` configuration.

Toutefois pour conserver un endpoint utile au monitoring HTTP de CleverCloud et à notre bonne compréhension, on va conserver le lancement de Phoenix, et le court-circuiter via un plug.

### Configuration serveur actuelle

Actuellement, par convention le port 8080 est configuré ici:

https://github.com/etalab/transport-site/blob/390f8873dbbcafa0f9f22769a3e7bd49d17f8125/Dockerfile#L21

8080 est le port de référence pour les services HTTP chez CleverCloud.

Notre application est configurée comme suit pour servir tout ce qui arrive sur ce port:

https://github.com/etalab/transport-site/blob/390f8873dbbcafa0f9f22769a3e7bd49d17f8125/config/prod.exs#L3-L11

La partie "url" est là uniquement pour le rewriting d'url, et faire en sorte que nos pages n'affichent pas de lien en HTTP 8080.

### Tâches identifiées

- [x] Traiter la dette technique portant sur l'usage des JSON via Ecto https://github.com/etalab/transport-site/issues/1861
- [x] Installer Oban
- [x] Faire en sorte de pouvoir lancer Oban uniquement (par configuration), mais avec un endpoint HTTP pour montrer le côté "UP" à CleverCloud ou même en local. Il faudra alors comprendre comment est faite la requête de monitoring de CleverCloud, et aussi statuer sur le domaine à utiliser.
- [x] En mode "worker", mettre en place un bypass du routing pour ne servir qu'une "home" vide (hello UP) qui servira pour le monitoring et nos vérifications
- [x] Faire en sorte de pouvoir lancer Phoenix uniquement (par configuration) sans "Oban worker"
- [x] Faire en sorte de ne lancer les migrations Ecto que sur la partie Phoenix (et que sur le noeud 1 idéalement, pour gérer le passage à 2 noeud facilement plus tard)
- [x] Configurer une deuxième instance prochainement CleverCloud (worker ou http, à définir)
- [ ] Faire en sorte de pouvoir utiliser une commande Docker en local (#1820) pour les conversions (avec mapping des volumes et gestion d'un tmp compatible)
- [x] Faire en sorte que les jobs Quantum ne soient schédulés que sur un seul noeud (sinon on aura des doublons)
- [ ] Vérifier le comportement d'un crash en local en faisant tourner sur 2 noeuds en local et en faisant un "SIGKILL"
- [x] Isoler Rambo sous une behaviour/wrapper qui permet d'asserter que le lancement a été "demandé" via Mox
- [ ] Garanties d'isolation: purger l'environnement transmis au processus de conversion, utiliser un working directory précis etc

**Comment by fchabouis** [comment]
Il semble qu'on puisse se passer de gymnastique pour gérer les migrations, car selon la doc de Ecto.migrate :

    :migration_lock - By default, Ecto will lock the migration table. This allows multiple nodes to attempt to run migrations at the same time but only one will succeed. You can disable the migration_lock by setting it to false

https://hexdocs.pm/ecto_sql/Ecto.Migration.html

**Comment by thbar** [comment]
Une grosse partie est implémentée dans #1875. Je propose de garder le ticket ouvert pour revisiter les quelques todos qui méritent de l'être.

**Comment by thbar** [comment]
On traitera les petites todos séparément quand elles reviendront.
