### ISSUE TITLE
Améliorer et référencer plus de JDD vélos et trottinettes en libre-service

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#1882]
Hello,

Dans le but d'améliorer et référencer plus de JDD vélos et trottinettes en libre-service, je propose de faire plusieurs actions.

Pour [les JDD actuellement publiés](https://transport.data.gouv.fr/datasets?locale=fr&type=bike-scooter-sharing) :
- **vérifier qu'une ressource contenant le `gbfs.json` existe bien.** Ce fichier permet de trouver les différents flux ensuite (stations, disponibilités etc). C'est donc le plus important. Par exemple il faudrait mettre à jour [ce JDD](https://transport.data.gouv.fr/datasets/optymo-velo-en-libre-service/).
- **avoir plus de cartes**. Si le JDD comporte une ressource gbfs.json mais qu'aucune carte n'est affichée, demander au producteur d'autoriser les CORS pour transport.data.gouv.fr. Ceci permettra d'afficher une carte des stations. Concrètement, il faut ajouter `Access-Control-Allow-Origin: https://transport.data.gouv.fr` aux réponses de l'API.
- **contacter les producteurs avec des URLs mortes**.

Pour lister de nouvelles ressources :
- rentrer en contact avec les gros acteurs comme JC Decaux ou Smoove pour ajouter des réseaux
- contacter les principales métropoles. Si certains acteurs n'ont pas la possibilité de diffuser les données (problème d'API) ou ont peur de quotas, on a du code déjà en place pour relayer leur flux ou le fournir en GBFS. Organiser des réunions/échanger avec moi.
- voir la liste des acteurs https://github.com/NABSA/gbfs/blob/master/systems.csv
- regarder ce qui est disponible sur Citymapper/Google Maps/autre et prendre contact avec les acteurs pour les référencer

**Comment by AntoineAugusti** [comment]
On a des nouvelles sur ce sujet ? Je crois que @NicolasBerthelot faisait un tour de son carnet d'adresses récemment aussi.

**Comment by Miryad3108** [comment]
@AntoineAugusti 
- Montpellier aimerait qu'on diffuse leurs données pour les VLS Smoove 
- Bordeaux ils publieront les données des différents opérateurs de free floating au second semestre de l’année
- Lille : je les ai contacté et te ferai un retour dès que possible

**Comment by Miryad3108** [comment]
@AntoineAugusti 
- Montpellier aimerait qu'on diffuse leurs données pour les VLS Smoove 
- Bordeaux : ils publieront les données des différents opérateurs de free floating au second semestre de l’année sur leur portail opendata
- Lille : je les ai contacté et te ferai un retour dès que possible

**Comment by AntoineAugusti** [comment]
> Les données Smoove sont souvent diffusées par Klervi. Est-ce que ceci est possible pour toutes les villes où Smoove opère ? Dans ce cas on pourrait supprimer notre code.

https://github.com/etalab/transport-site/issues/1882#issuecomment-951852442

@etalab/transport-bizdev C'est d'actualité avec #2292, on avait pas connaissance du flux de Klervi. Pourriez-vous prendre contact avec Smoove/Klervi pour discuter de la diffusion de leur GBFS ?

**Comment by AntoineAugusti** [comment]
En URL Klervi sur le PAN actuellement on a Vannes, Belfort, Avignon, Clermont-Ferrand, Saint-Etienne.

Manque potentiellement [Landerneau](https://www.smoove.fr/landerneau), [Epinal](https://www.smoove.fr/epinal) et [Carcassonne](https://www.smoove.fr/carcassonne) en regardant rapidement [leur carte](https://www.smoove.fr/realisations)

**Comment by Miryad3108** [comment]
Smoove : Je les ai eu en janvier. Ils sont déployés sur 5 villes Françaises pour lesquelles ils publieront des données au format GBFS v2.3 (RC) d'ici l'été 2022. Il n'y aura pas de rotation du bike_id pour le flux free_bike_status. Je leur avais envoyé le [fichier de MobilityData qui explique les conséquence de l'absence de rotation du bike_id](https://docs.google.com/document/d/1v8QhHGoTAhyOspoRhzOPDRVal9ue8AGfEXfB7VXA0oU/edit) (retracer les trajets de vos véhicules).
je vais leur envoyer leur carte parce qu'il y a plus de villes que ce qu'ils avaient annoncé :stuck_out_tongue: 

Mais du coup pour Belfort et Avignon je me tâte à contacter Blefort et relancer Avignon (je leur avais envoyé un mail sur ce sujet en décembre) parce que Smoove a dit qu'ils allaient gérer la relation avec les collectivités et publier les données

**Comment by AntoineAugusti** [comment]
Pour Montpellier actuellement on a [un flux diffusé par le PAN](https://transport.data.gouv.fr/gbfs/montpellier/gbfs.json) mais celui-ci n'est pas référencé sur le PAN. Il faudra que Montpellier ou Smoove crée un jeu de données sur data.gouv.fr

**Comment by AntoineAugusti** [comment]
@Miryad3108 Il semble y avoir un flux GBFS [pour Strasbourg](https://strasbourg-fr-smoove.klervi.net/gbfs/gbfs.json) mais il n'est pas accessible

**Comment by Miryad3108** [comment]
Les données de Montpellier ont été référencées par l'AOM : https://transport.data.gouv.fr/datasets/disponibilite-en-temps-reel-des-velos-en-libre-service-velomagg-de-montpellier/

Le flux contient 2 erreurs et une station avec des coordonnées nulles. J'ai envoyé un mail à Smoove en mettant Montpellier en copie
