### ISSUE TITLE
Référencer flux GBFS Valence et Besançon

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#1887]
- https://transport.data.gouv.fr/gbfs/valence/gbfs.json
- https://transport.data.gouv.fr/gbfs/besancon/gbfs.json

Ajoutés dans #1886. Ces 2 flux ne sont pas référencés sur le PAN. Prendre contact avec les collectivités ou créer des fiches pour eux ?

**Comment by AntoineAugusti** [comment]
@Miryad3108 Tu as des nouvelles de Valence ?

**Comment by AntoineAugusti** [comment]
@Miryad3108 On a des retours concernant Valence ?

**Comment by Miryad3108** [comment]
@AntoineAugusti Pas de retour de Valence, je viens de faire une relance

**Comment by AntoineAugusti** [comment]
@Miryad3108 On a des nouvelles ? On ferme ?

**Comment by Miryad3108** [comment]
Toujours pas de nouvelles pour Valence mais je veux bien qu'on laisse le ticket ouvert : je vais faire une relance et les contacterai par téléphone en fin de semaine si je n'ai toujours pas de retours.

**Comment by AntoineAugusti** [comment]
Alors, ils répondent au téléphone ? 📞

**Comment by AntoineAugusti** [comment]
Il n'y a aucun JDD pour cette AOM, je pense que là c'est du ressort de l'ART https://transport.data.gouv.fr/datasets/aom/95

**Comment by AntoineAugusti** [comment]
Le flux de Valence était en fait en Espagne https://github.com/etalab/transport-site/pull/2522 et le JDD existe pour Besançon https://transport.data.gouv.fr/datasets/besancon-velos-en-libre-service
