### ISSUE TITLE
Modes de transport non traduits

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#1904]
Visible sur https://transport.data.gouv.fr/datasets/reseau-de-transport-en-commun-lia-gtfs-1/?locale=fr

**Comment by AntoineAugusti** [comment]
En fait il semblerait que aucun mode GTFS n'est traduit actuellement, à voir si c'est souhaitable

**Comment by AntoineAugusti** [comment]
Il y a aussi la description du contenu des GTFS https://github.com/etalab/transport-site/pull/2426#discussion_r885247271

**Comment by ChristinaLaumond** [comment]
Pour les modes "principaux" à traduire en français on peut partir sur  :  
-  rail = ferré,  
-  subway = métro,
-  funicular =funiculaire 
- gondola = téléphérique (exemple [bibus](https://transport.data.gouv.fr/resources/43286))
- ferry = maritime
Pour le bus et tramway on est ok en français et en anglais.

**Comment by AntoineAugusti** [comment]
Le besoin n'a pas été exprimé depuis tout ce temps, je ferme
