### ISSUE TITLE
Mesurer la consommation du flux TR d'Angers

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#1919]
D'autres producteurs ont des questions, et du coup ce sujet déjà prévu revient sur la table.

Plusieurs solutions possibles:
- en très rapide, on peut simplement analyser les logs
- en un peu plus impliqué, on pourrait faire un système simple dans la base, avec un bucket par minute, et un upsert qui incrémente (c'est facile à faire à cette échelle), quitte à bouger sur un système plus élaboré plus tard (type timescaledb, ou prometheus etc)

**Comment by AntoineAugusti** [comment]
CleverCloud ne donne pas de statistiques qui proviennent du load balancer ? Comme [un LB sur AWS](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-cloudwatch-metrics.html)

**Comment by thbar** [comment]
Les métriques ne sont pas très accessibles ni très rapides sur nos derniers tests. Par ailleurs il y aura un métrique important qu'ils ne peuvent pas donner, c'est le nombre de requêtes vers le système externe (demandé idéalement par Nicolas, en + du nombre de requêtes entrantes sur le LB).

**Comment by thbar** [comment]
@NicolasBerthelot c'est implémenté et en cours de déploiement.
