### ISSUE TITLE
Idées pour l'implémentation de l'historisation améliorée

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#1921]
### Structuration du bucket

Je pensais profiter de l'occasion pour commencer à utiliser un nouveau bucket unique (pour toutes les ressources à la fois, soit l'inverse de ce qui est fait actuellement cf https://github.com/etalab/transport_deploy/issues/31).

On pourrait avoir une structure du type `/history/:resource_id`, en utilisant l'identifiant beta gouv plutôt que la clé primaire.

Dans le "sous-répertoire", chaque fichier gagnerait à être nommé d'une façon qui fait en sorte qu'un tri lexicographique sera également chronologique (en mettant dans le nom du fichier le moment du téléchargement), car les serveurs S3 vont retourner les fichiers dans l'ordre binaire UTF-8 (https://docs.aws.amazon.com/AmazonS3/latest/userguide/ListingKeysUsingAPIs.html).

Recommandation: utiliser des timestamps UTC formattés comme suit: `resource.YYYYMMDD-HHMMSS.SSS.zip`. On peut ainsi trier facilement par préfixe et aussi dans l'ordre chronologique. Les millisecondes aident à débugger.

Il faudra faire attention à bien paginer quand on va lire dans le bucket, et à verrouiller le fait qu'un upload ne soit pas partiel (normalement traité par les librairies mais à vérifier).

### Idées d'algorithme

Je ferais simplement, à intervalles réguliers (ça pourrait être toutes les 6 heures si on veut commencer simple)
- Télécharger la ressource en local en `/tmp` (avec un nom fixé par le job, et avec une routine pour effacer en sortie et aussi gros ménage en cas de crash, car on ne monitore pas l'espace disque et ça pourrait se remplir vite)
- Calculer le checksum à l'aide de #1918
- Récupérer le nom et la méta-donnée du fichier le plus récent dans S3
- Déterminer si un des fichiers du GTFS a vraiment changé
- Persister le fichier sur S3 en upload si c'est le cas

Dans un second temps on pourrait  aussi optimiser et éviter des téléchargements, en début de pipeline, avec une requête type head et vérification/capture du etag ou utilisation If-Modified-Since, pour réduire la charge sur les serveurs distants.

De la même façon on pourrait avoir une forme de cache local en DB pour les méta-données, mais attention on est vite désynchro dans ces cas.

### Stockage des méta-données

On pourrait sauver les informations suivantes:
- liste des fichiers et sha associé par fichier
- sha externe
- quelques headers https (type etag, if-modified-since)

On pourrait les stocker de différentes manières:
- Directement sur le fichier S3 (on a droit à 2KB de méta-données https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingMetadata.html, donc on peut stocker un JSON relativement copieux)
- En fichier associé (du type "même nom mais `.metadata.json` à la fin", ou préfixé par quelque chose de précis) ; ça pollue un peu plus mais on a davantage de place
- En base de données (pratique pour l'application, moins pour des scripts tiers, et attention c'est un cache en pratique, donc le risque d'avoir des données invalides existe davantage)

#### Détection du changement

On a vu plusieurs fois (chez Zenbus mais aussi Pigma au minimum, de mémoire) que les zips peuvent contenir la même donnée, mais pas avoir le même checksum.

Je crois que c'est essentiellement lié aux méta-données embarquées dedans (le zip contient un "last updated at"), mais je n'en suis pas sûr, si on compare en binaire (`diff <(xxd fichier1.zip) <(xxd fichier2.zip)`) on retrouve des changements à plusieurs endroits.

Il est dommage de capturer un fichier qui n'a en fait pas changé réellement sémantiquement. Dans #1918 j'ai pu vérifier que calculer un checksum par fichier dans le zip est simple à réaliser, tant qu'on travaille avec un fichier sur le disque.

On pourra peut-être aussi capturer des headers HTTP dans de la méta-donnée.

### Structuration au niveau du job Oban

Ou bien on fait un "méta-job", qui prend en paramètre un filtre sur les ressources qui nous intéressent, ou bien on fait 1 job par ressource (avantage: on peut gérer le retry un peu plus finement ; inconvénient: ça fait davantage de bruit).

Il faut voir si on veut activer les retries: peut-être que simplement avoir une tentative toutes les 6 heures avec le scheduler, mais pas de retry, pourrait être largement suffisant pour commencer.

### Points d'attention

- Attention aux race-conditions au niveau de l'exécution du job pour une ressource donnée ; il faudrait éviter de traiter la même ressource en parallèle deux fois, sinon on aura probablement un double stockage inutile (on pourrait utiliser https://github.com/sorentwo/oban#unique-jobs pour régler une partie du problème)
- Vérifier comment on va configurer les données (`acl-read` sur la totalité ?) en terme de droits
- Comment ça va se comporter dans le futur avec des formats multi-ressources mais n'ayant qu'une seule ressource "transport" déclarée (ex: GBFS sauf erreur, SIRI) ? Faudra-t-il des sous-répertoires ou un autre schéma etc ?
- Pourra-t-on "gz"-ipper les fichiers uniques d'autres formats (type Netex etc, pour gagner de la place de façon importante ?)

**Comment by thbar** [comment]
Ca serait aussi bien d'avoir une forme d'observabilité ; un petit event en base, ou simplement un champ "last_historised_at" pourrait aider à voir ce qui a raté dans le temps et à avoir une vue un peu "batch".

**Comment by AntoineAugusti** [comment]
Un problème à avoir en tête pour les ressources provenant de CSV ODS https://github.com/etalab/transport-site/issues/1930

**Comment by thbar** [comment]
Tip: on pourrait avoir une utilité à générer un UUID (avec `Ecto.UUID.generate`) au moment du téléchargement et à stocker cette info en méta-data S3. Ce genre d'astuce ne coûte pas cher et permet de restructurer plus tard les buckets (déplacer les répertoires au fur et à mesure qu'on affine notre besoin), tout en retrouvant ses petits.

**Comment by thbar** [comment]
Je clôture, #1937 est déployé et la limitation connue a son ticket ici #1964.
