### ISSUE TITLE
Améliorer ressources extraites depuis des CSV sur Opendatasoft

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#1930]
[`Opendatasoft.UrlExtractor`](https://github.com/etalab/transport-site/blob/master/apps/transport/lib/opendatasoft/url_extractor.ex) permet de "générer des ressources virtuelles" lorsque des producteurs publient un CSV contenant des liens vers des ressources distantes. À partir d'une ressource CSV publiée sur datagouv, on lit le fichier CSV pour créer des nouvelles ressources lorsque l'on trouve des URLs.

Les problèmes rencontrés sont les suivants :
- les noms des [colonnes à utiliser sont bancals](https://github.com/etalab/transport-site/blob/a9d91912b7d5bdfd5b53ebec23e16a92de0c86b0/apps/transport/lib/opendatasoft/url_extractor.ex#L14-L24)
- l'identifiant des ressources créées n'est pas unique, on utilise le `datagouv_id` de la ressource CSV originale pour toutes les ressources trouvées dans le fichier
- seul le lien est utilisé, les producteurs n'ont pas moyen d'indiquer titre, description ou format https://github.com/etalab/transport-site/issues/1855
- la détection du format d'une ressource se fait uniquement par le biais de mots clés présents dans le lien vers les ressources

Exemple d'un tel JDD : https://transport.data.gouv.fr/datasets/agglobus-offre-theorique-mobilite-reseau-urbain-de-bourges

Voir comment améliorer la situation, qui concerne environ ~5 JDD et ~20 ressources référencées sur le PAN pour le moment.

- ODS développe une fonctionnalité pour référencer convenablement des ressources à l'aide d'URLs distantes
- formaliser plus le format de CSV attendu pour les producteurs (`titre,description,format,url` ?)
- autre

**Comment by thbar** [comment]
Voir plus ou moins en lien:
- #1645
- #1604

**Comment by AntoineAugusti** [comment]
Voir aussi ce Google Doc https://docs.google.com/document/d/1Y7IKJ5P6i785Gc45QmEmeOo6ax5VfCUKhoJ7GEwWhBI/edit

**Comment by thbar** [comment]
Deux soucis en un rencontrés aujourd'hui en lien avec ce sujet:
- Le fait que le format n'est pas intégré comme colonne a encore posé problème avec https://github.com/etalab/transport-site/issues/2089
- Le fait qu'une ligne ne donne pas lieu à une correspondance finit par un échec silencieux, ce qui n'est pas bon non plus

**Comment by thbar** [comment]
Je découvre au passage que les fichiers GTFS-RT indiquent qu'ils sont en "CSV", ce qui est cohérent avec ce qui est écrit dans le ticket:

<img width="478" alt="CleanShot 2022-02-03 at 18 13 40@2x" src="https://user-images.githubusercontent.com/10141/152393775-c06490d8-5b7e-4e8e-8219-f546e13a9a49.png">

**Comment by AntoineAugusti** [comment]
Je ferme cette issue. Il y a un changement de moissonneur qui va intervenir côté ODS #3647 début 2024.

On pourra retirer en T1/T2 2024 la fonctionnalité de lecture des CSV ODS qui crée des ressources chez nous car on peut désormais ajouter des liens distants sur OpenDataSoft. Il n'y a donc pas lieu de l'améliorer d'ici là.
