### ISSUE TITLE
GTFS de la CACL apparaît comme étant indisponible mais on peut le télécharger 

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#1934]
Le GTFS du réseau péri urbain Agglobus de la CACL apparaît comme étant indisponible mais on peut le télécharger à partir du PAN : https://transport.data.gouv.fr/datasets/agence-agglobus/

**Comment by AntoineAugusti** [comment]
Hello,

L'URL de la ressource, https://api-data.cacl-guyane.fr/v1/gtfs-agglobus-agency/!sourcefiles, ne supporte pas la méthode HTTP `HEAD`.

```
$ curl -I 'https://api-data.cacl-guyane.fr/v1/gtfs-agglobus-agency/!sourcefiles'
HTTP/2 500 
content-type: application/json; charset=utf-8
content-length: 122
date: Thu, 25 Nov 2021 07:46:14 GMT
x-powered-by: Express
access-control-allow-origin: *
access-control-expose-headers: Elements-Count,Elements-Total-Count,results-count,total-results-count
etag: W/"7a-4w5b1T9Q9JTjEumKkV9ql/R+JXU"
vary: Accept-Encoding
x-cache: Error from cloudfront
via: 1.1 127aaaaca740f298a4c887357ec047b5.cloudfront.net (CloudFront)
x-amz-cf-pop: CDG52-P2
x-amz-cf-id: OVqWu4K0TyvTQxnxMCCX3gCSzrf5AT9LBLlcXDZt1QRPefULpdxmOw==
```

Pourrais-tu contacter un interlocuteur technique là-bas et leur demander :
- de faire le nécessaire pour gérer les requêtes HEAD en plus de GET
- renvoyer le code HTTP 405 lorsqu'on envoie une requête HEAD (on essaiera alors en GET)

**Comment by AntoineAugusti** [comment]
@Miryad3108 Tu as pu les contacter ?

**Comment by Miryad3108** [comment]
@AntoineAugusti je les avais contacté il y a deux semaines mais je viens de voir que le mail n'a pas été distribué. Je viens de renvoyer, merci pour le rappel

**Comment by Miryad3108** [comment]
Le problème semble réglé, je ferme l'issue : https://transport.data.gouv.fr/datasets/agence-agglobus/
