### ISSUE TITLE
Le test pour les assets Yarn non à jour ne protège pas

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#1938]
Quand on met à jour `phoenix`, `phoenix_live_view`, ou `phoenix_html`, sans mettre à jour les assets avec yarn, au moins en dév, plus rien ne marche côté LiveView, et ça peut être compliqué à débugger.

Voir:

https://github.com/etalab/transport-site/blob/baa0a54b004e1735de5109736c9b6c68e54ff9ff/apps/transport/client/yarn.lock#L3628-L3636

Ca peut donner une belle perte de temps quand on ne connait pas le souci.

J'avais mis en place un test vite fait ici:

https://github.com/etalab/transport-site/blob/baa0a54b004e1735de5109736c9b6c68e54ff9ff/apps/transport/test/build_test.exs#L65-L76

Toutefois il ne semble plus intercepter correctement le souci (j'avais vu ça précédemment).

Je pense le remplacer par une lecture rapide du `yarn.lock`,  plus basique mais plus fiable.

J'ouvre le ticket pour traiter ça à une prochaine upgrade, pour ne pas ralentir mon travail sur #1929

**Comment by AntoineAugusti** [comment]
J'ai eu ce problème hier :)

**Comment by Matsa59** [comment]
Le js de `phoenix_live_view` est dans sa lib (`../../deps/phoenix_live_view/`. Le package.json fait bien reference vers ce path donc normalement en mettant a jour phoenix ou tout autre lib, le js doit egalement ce mettre a jour. La reference faite dans `yarn.lock` ne sert par consequent pas a grand chose.

Est-ce que le probleme ne serait pas plus webpack ?

**Comment by thbar** [comment]
Clôturé via #2074.
