### ISSUE TITLE
Différencier "prochainement" de la "production"

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#1945]
Il va être utile pour différentes raisons de pouvoir solidement différencier le staging de la production. 

Dans les deux cas, `MIX_ENV` est à `prod`.

Il y a un embryon de cela avec `SENTRY_ENV=staging`.

Je propose:
- [x] Ajouter un `APP_ENV`, obligatoire quand `MIX_ENV=prod`, et qui sera égal à `production` ou à `staging`, comme variable d'environnement
- [ ] Prendre en compte cette variable au runtime pour différencier les comportements souhaités

Je crée ce ticket pour pointer dessus depuis d'autres tickets.

Ca aidera aussi pour des choses comme:
- #1760
- #1688

**Comment by thbar** [comment]
@AntoineAugusti j'ai l'impression qu'avec #1949 on est suffisamment bon pour l'instant, qu'en penses-tu ?

**Comment by AntoineAugusti** [comment]
Tout à fait, je ferme
