### ISSUE TITLE
Mieux différencier les "community resources"

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#1947]
Dans les ressources notées "community resources", il y a deux sous-catégories:
- les ressources créées par le PAN, et republiées sous ce statut
- les autres ressources (aka les "vraies community resources")

Dans notre base c'est un peu mélangé, et avec les travaux à venir (reprise en main conversion GTFS -> GeoJSON, historisation), ça mériterait d'être mis au clair, autant pour simplifier le code que la partie web.

Côté communication pour le public, c'est je trouve aussi confus: il faudrait mieux séparer les éléments de conversions de ceux émis par le reste de la communauté (copie d'écran ci-dessous):

<img width="438" alt="CleanShot 2021-12-02 at 09 51 14@2x" src="https://user-images.githubusercontent.com/10141/144388921-a8f9ac4a-be02-446f-943f-b3280ad0c713.png">

**Comment by AntoineAugusti** [comment]
@thbar Est-ce encore d'actualité maintenant ? On a arrêté les conversions et publications en tant que ressources communautaires. Ces ressources pourraient faire leur retour si jamais des producteurs repartagent des données.

cc @etalab/transport-bizdev

**Comment by Miryad3108** [comment]
Je ferme l'issue, on ne publie plus en ressource communautaire
