### ISSUE TITLE
Ajouter worker dans dashboard suivi des jobs

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#1954]
Le dashboard /backoffice/jobs ajouté dans https://github.com/etalab/transport-site/pull/1875 permis de suivre l'exécution de tâches, il est très utile.

Prévoir d'ajouter la classe utilisée pour savoir quel job tourne actuellement (colonne `worker`). Actuellement on a seulement les arguments passés.

**Comment by thbar** [comment]
Liste de courses : je trouverai ça pratique aussi d'avoir tout en haut de page un petit récapitulatif plus direct de tous les status avec les counts (plutôt que de l'avoir uniquement en tout petit en bas de chaque section, ce qui est utile aussi). C'est pratique pour suivre l'activité d'un coup d'oeil, voir pouvoir faire une petite copie d'écran pour pouvoir comparer.
