### ISSUE TITLE
Rendre le "worker" plus facile d'accès via le web

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#1956]
Autant pour notre suivi rapide que pour l'ajout de fonctions spécifiques (type LiveDashboard) directement hébergées par le "worker", il va être pratique d'avoir un accès web simplifié (aujourd'hui il faut aller chercher un nom de domaine généré par CleverCloud dans un coin).

Je propose:
- [x] `workers.prochainement.transport.data.gouv.fr` pour le staging (sur le modèle de `proxy.prochainement` qui existe déjà)
- [x] `workers.transport.data.gouv.fr` pour la production

@AntoineAugusti @fchabouis ok pour vous ?

Je tracerai les opérations réalisées ici.

**Comment by AntoineAugusti** [comment]
Plutôt au pluriel ? C'est en vrai un load balancer vers potentiellement plusieurs workers

**Comment by thbar** [comment]
> Plutôt au pluriel ?

Oui bonne idée, je pars là dessus.

Au passage, ça me fait penser que si on passe à > 1 noeud horizontal, et qu'on veut utiliser LiveDashboard sur N noeuds à l'horizontale, on sera contraints de mettre en place un cluster Erlang, sinon chaque requête va aller vers un noeud donné au hasard.

**Comment by thbar** [comment]
Voir [documentation CleverCloud](https://www.clever-cloud.com/doc/administrate/domain-names/#using-personal-domain-names). Je mets en place:

- `CNAME` de `workers.prochainement` vers `domain.par.clever-cloud.com`

**Comment by thbar** [comment]
J'ai ajouté le domaine ici:

<img width="911" alt="CleanShot 2021-12-06 at 11 56 23@2x" src="https://user-images.githubusercontent.com/10141/144834346-55a87a90-3fd6-4819-81e0-57a71c7ec33e.png">

Puis fait un restart (peut-être pas nécessaire en fait).

Ca fonctionne: 

```
❯ curl https://workers.prochainement.transport.data.gouv.fr 
UP (WORKER-ONLY)
```

**Comment by thbar** [comment]
Je fais pareil pour la production:

- `CNAME` de `workers` vers `domain.par.clever-cloud.com`
- ajout du domaine dans CleverCloud (`workers.transport.data.gouv.fr`)
- redémarrage

```
curl https://workers.transport.data.gouv.fr
```

Attention le SSL est obligatoire, sinon le plug redirige vers la home du site et non du worker actuellement.

**Comment by thbar** [comment]
J'ai également ajouté:

- `CNAME` de `prochainement vers `domain.par.clever-cloud.com` (en lien avec #1688)

**Comment by thbar** [comment]
Je laisse ouvert pour écrire une PR de doc là dessus.
