### ISSUE TITLE
Update curated list of datasets

### ISSUE THREAD

**Issue by maukoquiroga** [etalab/transport-site#196]
Relates to #183

- [Brest](https://www.data.gouv.fr/fr/datasets/liste-des-arrets-horaires-et-parcours-de-tous-les-bus-et-tramways-circulant-sur-le-territoire-de-brest-metropole/)
- [Toulouse](https://www.data.gouv.fr/fr/datasets/tisseo-offre-de-transport-gtfs/)
- [Rennes](https://www.data.gouv.fr/fr/datasets/versions-des-horaires-theoriques-des-lignes-du-reseau-star-au-format-gtfs/)
- [Angers](https://www.data.gouv.fr/fr/datasets/horaires-et-arrets-du-reseau-irigo-format-gtfs/)
- [Lille (cerema)](https://www.data.gouv.fr/fr/datasets/horaires-theoriques-du-reseau-de-transport-transpole/)
- [Boulogne-sur-Mer (cerema)](https://www.data.gouv.fr/fr/datasets/horaires-theoriques-du-reseau-de-transport-marineo/)
- [Nancy (cerema)](https://www.data.gouv.fr/fr/datasets/horaires-theoriques-du-reseau-de-transport-stan/)
- [Royan (cerema)](https://www.data.gouv.fr/fr/datasets/horaires-theoriques-du-reseau-de-transport-carabus/)

**Comment by IshanB** [comment]
Rennes : https://www.data.gouv.fr/fr/datasets/versions-des-horaires-theoriques-des-lignes-du-reseau-star-au-format-gtfs/

Angers : https://www.data.gouv.fr/fr/datasets/horaires-et-arrets-du-reseau-irigo-format-gtfs/

Lille : https://www.data.gouv.fr/fr/datasets/gtfs-et-visualisation-du-reseau-transpole/
