### ISSUE TITLE
Limitation: historisation v2 non traitée pour les ressources CSV OpenDataSoft avec + d'un item

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#1964]
Je clôture #1921 qui est traité via #1937 et je note, pour ne pas qu'on le laisse de côté, le trou dans la raquette suivant, qui mérite qu'on crée un ticket spécifique.

### Situation actuelle

Les ressources "à indirection" (CSV qui donne une url) en provenance d'ODS avec plus d'une ligne ne seront pas historisées aujourd'hui. Celles avec une ligne qui passent à plus d'une ligne verront leur historisation stoppée également.

https://github.com/etalab/transport-site/blob/02271223b663b9e454fe9580a8474dea012ba007/apps/transport/lib/jobs/resource_history_job.ex#L27-L45

### Pré-requis

Avant de pouvoir traiter ça proprement, il faut mettre en place un mécanisme d'assignation d'id stable pour chacune de ces lignes, sous une forme ou une autre (voir #1930, #1946).

**Comment by AntoineAugusti** [comment]
Fait depuis que l'historisation ne se repose plus sur le `datagouv_id`
