### ISSUE TITLE
Utilisation de l' "historisation v2" pour le site (migration des données + adaptation visuelle)

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#1965]
Maintenant que #1937 est déployé, une historisation régulière des GTFS (sauf #1964) est réalisée, ceci de façon à ne capturer que les ZIP dont le contenu interne a réellement changé (cf R&D faite dans https://github.com/etalab/transport-site/pull/1918).

Il faut à présent prévoir d'utiliser ce système, et ça comprend deux étapes:

### Evolution de l'affichage sur le site pour aller prendre la donnée dans le nouvel historique

La solution naturelle à présent est de taper dans `DB.ResourceHistory`:

https://github.com/etalab/transport-site/blob/master/apps/db/lib/db/resource_history.ex 

Il faut trier par `inserted_at: :desc` vu que c'est la convention qu'on a retenu, et filtrer simplement par `datagouv_id` (quand c'est possible, donc hors #1964).

Pas forcément besoin d'ajouter un lien en dur (foreign key) vers une ressource dans la table à ce stade, pour rester simple.

### Script de migration des anciennes données vers les nouvelles

(en lien avec https://github.com/etalab/transport_deploy/issues/31)

C'est un peu plus coton, si on cherche à rapatrier l'ancien historique (à discuter en point d'équipe mais je pense que ça sera pertinent à titre personnel), il va falloir backfiller le contenu associé.

Je suggère:
- l'écriture d'un script one-off (voir sous `scripts`) qui va prendre en paramètre les bons éléments, qu'on pourra rajouter plusieurs fois en local pour bien vérifier le fonctionnement.
- idéalement le script sera idempotent pour éviter toute grosse boulette ; on peut obtenir ça en stockant dans `payload` un "legacy_s3_file" et en demandant à la base si elle a déjà vu le fichier qu'on traite (avec son nom de bucket complet, vu que chaque ressource avait un nom de bucket spécifique)
- dans tous les cas, il est impératif de noter une petite info qui va permettre de reconnaître ce qu'on a backporté, car en cas de pépin on pourra effacer facilement
- l'écriture d'une manipulation (autre script ou commande) qui va auditer le résultat de la précédente ; typiquement quelque chose qui liste tout des deux côtés, trie par un id stable (data gouv resource id ?), génère un JSON pretty-printé avec le checksum externe du fichier de part et d'autre, permet de faire ensuite un `diff` qui donne une vue d'ensemble robuste
- bien travailler en dév (ne pas hésiter à rejouer), en utilisant un bucket dédié pour la cible (sur Clever ou dans MinIO)
- on n'efface rien dans l'ancien historique pour l'instant

Points d'attention évident:
- Il faudra bien vérifier qu'au moment de l'insertion, on définit `inserted_at` nous-même pour ne pas laisser Ecto y coller la valeur "now", sinon vu qu'on trie là dessus, notre historique sera faux (dates incorrectes)

**Comment by AntoineAugusti** [comment]
À avoir en tête, l'environnement staging/prochainement utilisait le bucket de production pour backup des ressources, qui se trouvent sur demo. Il ne faut pas prendre en compte ces ressources lors de la migration !

```
$ s3cmd info s3://dataset-5defcb1c634f413ad267d96d/test_upload_velov_20211202T000349
s3://dataset-5defcb1c634f413ad267d96d/test_upload_velov_20211202T000349 (object):
   File size: 29597
   Last mod:  Thu, 02 Dec 2021 00:03:49 GMT
   MIME type: application/octet-stream
   Storage:   STANDARD
   MD5 sum:   69271ab83f82a444a08cae767f66a4ab
   SSE:       none
   Policy:    none
   CORS:      none
   ACL:       *anon*: READ
   ACL:       cellar_97470731-85e7-47ab-bf64-75b7ea40790b@orga_f33ebcbc-4403-4e4c-82f5-12305e0ecb1b: FULL_CONTROL
   URL:       http://dataset-5defcb1c634f413ad267d96d.cellar-c2.services.clever-cloud.com/test_upload_velov_20211202T000349
   x-amz-meta-content-hash: 956d964e76b030986c5704abf7f623b6deb043feabc52c163d0bfe074c3d02bc
   x-amz-meta-end: 2021-12-17
   x-amz-meta-format: GTFS
   x-amz-meta-start: 2021-09-06
   x-amz-meta-title: test_upload_velov
   x-amz-meta-updated-at: 2021-12-01 04:17:41.800967
   x-amz-meta-url: https://demo-static.data.gouv.fr/resources/velos-libre-service-lyon-velov-disponibilite-en-temps-reel/20211026-142809/gtfs-1-.zip
```

**Comment by fchabouis** [comment]
En fait le code #1616 n'est pas buggé, c'est juste qu'il aurait fallu que l'instance prochainement utilise bien le cellar de staging alors que jusqu'à récemment, il utilisait le cellar de prod. En supprimant le CELLAR_NAMESPACE tout le monde a écrit au même endroit.

Pour note, je me suis rendu compte le 15 décembre que staging utlilisait le cellar de prod et j'ai fait le changement ce jour là (https://mattermost.incubateur.net/betagouv/pl/1dag9ttc7f8xjccbbhd7aqomhy)

**Comment by AntoineAugusti** [comment]
Voir #2060 #2077  #2081 #2082

**Comment by AntoineAugusti** [comment]
À voir une fois qu'on aura fini de migrer les anciennes ressources pour dupliquer des objets, à l'aide du hash à l'intérieur du ZIP.

Je regarde les doublons avec

```sql

select datagouv_id, hash, count(1)
from (
  select
    datagouv_id,
    id, 
    array_agg(sha256 order by sha256), 
    md5(array_agg(sha256 order by sha256)::varchar) hash
  from (
    select rh.datagouv_id, rh.id, t->>'sha256' sha256
    from resource_history rh, jsonb_array_elements(payload->'zip_metadata') t
  ) t
  group by 1, 2
) t
group by 1, 2;
```

**Comment by AntoineAugusti** [comment]
Ça se discute aussi d'avoir une nouvelle colonne `zip_hash` qui reprend les différents hashs des fichiers à l'intérieur d'un ZIP. Là en SQL je suis obligé de rassembler les hashs et de hasher à nouveau pour avoir une valeur unique par ligne.

La nouvelle historisation ne devrait pas historiser des ressources qui ont des hashs qui ne changent pas (et qui se suivent)
https://github.com/etalab/transport-site/blob/1a1dd37a88aec78c4efc1818db266bf62f41e2fc/apps/transport/lib/jobs/resource_history_job.ex#L154-L161

mais c'est intéressant de vérifier que c'est bien le cas aussi.

**Comment by AntoineAugusti** [comment]
Je vais clore cette issue, on a migré les anciennes ressources, supprimé les doublons et supprimé les anciens fichiers.
