### ISSUE TITLE
Ressources non disponibles (Réseau Oise 60) - URLs incorrectes

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#1967]
Sur https://transport.data.gouv.fr/datasets/arrets-horaires-et-parcours-theoriques-gtfs-du-reseau-routier-regional-de-transport-18/, tout est en rouge.

Quand on suit vers "data gouv", on arrive sur: https://www.data.gouv.fr/fr/datasets/arrets-horaires-et-parcours-theoriques-gtfs-du-reseau-routier-regional-de-transport-18/

Le premier lien indique ici une resource type "HTML":

<img width="1115" alt="CleanShot 2021-12-07 at 11 57 38@2x" src="https://user-images.githubusercontent.com/10141/145016872-48b5c11a-55b4-4411-99f7-66fe05ca2a25.png">

L'url correspondante (https://www.data.gouv.fr/fr/datasets/r/667740a7-f07f-423e-b55d-c490723751ea) donne actuellement une erreur 500:

<img width="764" alt="CleanShot 2021-12-07 at 11 58 23@2x" src="https://user-images.githubusercontent.com/10141/145017004-04b1f07e-5238-4cc5-a8ad-b0cf7b283438.png">

Mais elle nous donne un indice précieux (`operatorCode`).

L'url data gouv redirige vers une url erronée: https://exs.sismo2.cityway.fr/GTFS.aspx?key=SISMO&amp;OperatorCode=CG60L1

Si on corrige le `&amp;` en `&`, on obtient bien un GTFS: https://exs.sismo2.cityway.fr/GTFS.aspx?key=SISMO&OperatorCode=CG60L1

On peut vérifier cela comme suit:

```
❯ curl -I --silent "https://www.data.gouv.fr/fr/datasets/r/667740a7-f07f-423e-b55d-c490723751ea" | grep "HTTP\|Location"
HTTP/1.1 302 FOUND
Location: http://exs.sismo2.cityway.fr/GTFS.aspx?key=SISMO&amp;OperatorCode=CG60L1
```

Et:

```
❯ curl -I "https://exs.sismo2.cityway.fr/GTFS.aspx?key=SISMO&amp;OperatorCode=CG60L1"
HTTP/1.1 500 Erreur dans les param&#232;tres. Sp&#233;cifier une valeur pour &#39;operatorCode&#39;.
```

Tandis qu'avec une correction sur l'encodage, on a bien:

```
❯ curl -I "https://exs.sismo2.cityway.fr/GTFS.aspx?key=SISMO&OperatorCode=CG60L1" 
HTTP/1.1 200 OK
```

**Comment by thbar** [comment]
@Miryad3108 @NicolasBerthelot il faudrait contacter le producteur de donner et nous assurer qu'ils corrigent les urls de ce dataset pour ne plus fournir ex: `http://exs.sismo2.cityway.fr/GTFS.aspx?key=SISMO&amp;OperatorCode=CG60L1` mais `http://exs.sismo2.cityway.fr/GTFS.aspx?key=SISMO&OperatorCode=CG60L1` (à savoir remplacer `&amp;` par juste `&`).

**Comment by AntoineAugusti** [comment]
@thbar Tu peux même mettre une URL en https dans ton dernier message !

**Comment by AntoineAugusti** [comment]
Hello @NicolasBerthelot @Miryad3108 c'est toujours d'actualité

https://transport.data.gouv.fr/datasets/arrets-horaires-et-parcours-theoriques-gtfs-du-reseau-routier-regional-de-transport-18/

**Comment by Miryad3108** [comment]
J'ai contacté la région Hauts-de-France 

En parallèle j'ai aussi contacté l'Oise pour qu'ils passent en https ici : https://transport.data.gouv.fr/datasets/arrets-horaires-et-parcours-theoriques-gtfs-des-differents-reseaux-de-transport-membres-du-synd3-1/
