### ISSUE TITLE
Conversion GTFS -> GeoJSON "v2"

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#1970]
(BROUILLON! Premier jet avec des idées)

Préambule : je ne décris pas dans cette issue les idées que je peux avoir concernant la partie publication sous forme de ressources communautaires, car il y a déjà assez de grain à moudre juste sur la partie conversion elle même.

La conversion GTFS -> GeoJSON actuelle n'est pas suffisamment sous contrôle (manque d'observabilité, plateforme pas assez bien maintenue etc) et pas franchement fiable en l'état actuel.

On va la rapatrier sous forme de jobs Oban maintenant qu'on dispose de cet outil (voir #1937, #1806 etc).

### Question : combien de conversions pour une ressource donnée ?

Jusque là (à vérifier), je crois qu'on ne publie sous GeoJSON que la dernière version d'une ressource GTFS donnée.

Faut-il conserver un historique, notamment par rapport aux "périodes de validité" (un GTFS sera souvent publié, idéalement, avant son début de validité, et on conserve l'ancien sous le coude etc).

Je me rends compte que je ne sais pas s'il existe une notion de version d'une ressource (qu'on pourrait mettre à jour et tracer) côté data gouv. 

De la même façon je me demande si l'historisation (voir #1965) apparaît dans notre API et si ça ne mériterait pas d'être le cas.

En résumé et en immédiat, la question est : l'apparition d'un `DB.ResourceHistory` doit-elle donner lieu à une conversion qui correspondra à celle-ci et restera en place (historisée), ou pas ?

J'aurais tendance à dire que c'est mieux : ça augmente la taille mais ça permet de fournir ce service de façon assez stateless et idempotente (lire plus bas).

### Traçage de l'origine / idempotence / lineage de la donnée

Tous ces points sont importants pour savoir quand on doit convertir ou pas, ne pas convertir pour quelque chose qu'on a déjà converti, et aussi (!) pour savoir quand re-publier sous forme de ressource communautaire plus tard.

Grâce au travail effectué dans #1937, chaque GTFS est snapshotté toutes les 6 heures, et cela uniquement quand le contenu interne a changé.

Pour avoir une idempotence/caching du job (ce qui facilite les retries), on a plusieurs options:
- S'appuyer sur le UUID du téléchargement lui-même (https://github.com/etalab/transport-site/blob/d0f3b6d252de291cf4f7c2166743db8b3d3383b9/apps/transport/lib/jobs/resource_history_job.ex#L106), pour identifier en fait l'opération de téléchargement (c'est simple, mais ça ne marche que si on passe par `DB.ResourceHistory`
- S'appuyer sur le checksum externe du fichier (simple, et utilisable facilement pour convertir des fichiers tiers via une interface web aussi, sans forcément aller lire dans notre historique)
- S'appuyer sur le checksum interne du fichier (plus fin, mais aussi potentiellement un peu plus error-prone)

### Ma première proposition (ce qui me paraît le plus naturel)

Je n'ai pas encore décanté mes cogitations, mais voilà ce que je serais tenté de faire pour commencer (je peux revisiter ça plus tard, c'est une première idée):

- Dans un premier temps je ne stockerais que les conversions liées aux ressources qu'on historise, pour ne pas mélanger les torchons et les serviettes
- Je stockerais en première passe directement dans le bucket "history" mais avec un schéma de nommage comme suit: `/conversions/gtfs-to-geojson/SHA256-EXTERNE-DU-FICHIER.geojson` ; ça permettra de traiter d'autres conversions plus tard (externes et sans historisations), à moins qu'on veuille les traiter séparément
- EDIT: en pratique il y a des limites d'efficience sur le nombre de fichiers (https://docs.ceph.com/en/latest/cephfs/app-best-practices/#very-large-directories) donc on pourrait avoir un schéma un peu plus fragmenté (avec N sous-répertoires pour "sharder" comme on peut le faire classiquement sur un disque, avec `20211104/...` transformé en `2021/11/04/...`
- On gagnera à avoir des méta-données sur le fichier (ou bien en base, ou bien sur le fichier)

Dans ce schéma là, un job est assez facilement idempotent et "retriable":
- On crée un job avec en paramètre l'id du `DB.ResourceHistory` (ou peut-être mieux pour la suite et plus découplé, avec le chemin de source dans S3 simplement)
- Le job télécharge le fichier S3 en local en temporaire (attention à nettoyer derrière)
- Le job calcule le SHA256 externe du fichier (on a déjà des outils pour ça)
- Le job évalue où le fichier devrait être et vérifie sa présence
- S'il existe, il quitte
- S'il n'existe pas, il le traite et le stocke

Fonctionner ainsi permettrait même de faire une génération à la volée (quelqu'un demande la ressource, elle n'existe pas, on fait attendre le client, on génère puis on récupère l'adresse, connue de l'appelant).

Avoir un schéma de nommage qui donne un nom stable en cible dans le temps est une astuce pratique.

### Calage de la suite (publication)

Juste pour réfléchir un peu en avance à ce sujet même si j'ai écrit que je le laissais en dehors, pour vérifier la vue d'ensemble il est utile de penser à ça.

Une vérification idempotente de publication sous forme de données communautaires pourrait prendre la forme suivante:
- Le job de publication va aller chercher l'état actuel de l'history chez nous, et trouver la version la plus récente (avec son UUID de téléchargement)
- Il faut que la conversion publiée de l'autre côté dispose d'une méta-donnée type clé pour nous permettre de comprendre à quelle version de l'historique elle fait référence. C'est là que l'UUID mentionné plus haut pourrait servir, entre autres choses
- Le job va regarder l'état distant, compare, et décide en fonction
- Ce job pourrait être déclenché dès que la conversion d'un GTFS historisé chez nous est lancé (à la fin du job)
- On gagnera à écrire quelques "screens data" qui iront vérifier en masse l'état des deux côtés (chez nous et chez data gouv) pour détecter ce qui a cassé quelque part

Je pense qu'éviter un stockage en base, chez nous, de l'état supposé du serveur distant (data gouv), sera plus fiable (cad l'inverse de ce qu'on a fait sur l'historisation, où on considère que S3 est "distant", mais sous contrôle). Je préconiserais d'utiliser des identifiants type UUID pour retrouver les petits. S'appuyer sur la base dans ce cas risque d'amener des désynchros qui seront difficiles à tracer (même si c'est plus tentant).
 
### Nettoyage

On pourrait dès à présent prévoir une forme de nettoyage ; la conversion GeoJSON d'un GTFS datant d'il y a 3 ans (si on décidait de garder l'historique) a une utilité pour certains cas, mais pas forcément pour beaucoup.

**Comment by fchabouis** [comment]
Merci pour ces reflexions Thibaut !

Les questions que je me pose en les lisant :
- A-t-on besoin de stocker les geojsons chez nous ? Pour le moment ils ne sont pas stockés, juste générés puis publiés sur data.gouv.fr en ressource communautaire. Serait-il envisageable de publier un geojson dont le nom de fichier contient de informations nous permettant de savoir à coup sûr à quelle ressource il correspond ? type : {ressource_id}-{sha-de-la-ressource}-{nom de la ressource}.geojson. Et de ne pas avoir à le stocker sur S3.

Si on choisit de quand même stocker les geojsons sur S3 :
- comme l'historisation des ressources ne se fait que côté transport.data.gouv, on ne peut pas publier de ressources communautaires correspondant à des versions passées d'une ressource GTFS, sous peine d'avoir un très grand nombre de ressources communautaires orphelines sur data.gouv.fr (la ressource GTFS qui a servi à générer le geojson n'existe plus). Du coup à quoi servirait l'historique des geojsons ?

Pour la question du tuilage temporel des GTFS, on a en général un GTFS1. Puis quand la date de péremption approche, le producteur publie un GTFS2 à côté. Puis une fois que la date de péremption est passée, GTFS1 est supprimé. Normalement ça ne pose pas de problème vis a vis des GeoJSONs. Il y en d'abord 1 (celui de GTFS1), puis 2 (GTFS1 + GTFS2), puis à nouveau 1 (GTFS2).

**Comment by thbar** [comment]
Hum ça fait cogiter :-)

Je me demande même si on a vraiment besoin de les stocker quelque part tout court (de façon permanente).

On pourrait avoir un endpoint qui prend en paramètre les références d'une version historiée, et qui génère à la volée le GeoJSON, avec un système de cache type LRU qui finit par effacer la payload.

Les stocker uniquement sur data gouv effectivement ça va nous empêcher d'être capable d'afficher par exemple la version N-1 sous forme de carte facilement etc.

En tout cas il faut qu'on active sur ce sujet, j'aimerais bien qu'on puisse décommissionner dès que possible le convertisseur legacy.

**Comment by thbar** [comment]
État de ma réflexion suite au point d'équipe :
- Il faut aller vite
- Je serai tenté de gérer 1 conversion par `ResourceHistory`
- Stocker dans S3 avec un nom construit directement sur le checksum externe du fichier, permettrait de découpler et de le retrouver très facilement, quitte à ajouter des méta-données en plus
- Dans un premier temps, ne pas chercher à publier sous forme de ressource communautaire (mais le faire un peu après)

@AntoineAugusti @fchabouis est-ce que ça peut être inclut dans le "nettoyage dette technique" de la période de Noël en priorité ? :smile:

**Comment by thbar** [comment]
Traité dans #1991.
