### ISSUE TITLE
Régression sur l'historisation v2 (le filtre r.is_active est incorrect)

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#1972]
Le filtre introduit par #1957 ici semble ne pas être le bon:

https://github.com/etalab/transport-site/blob/1c2d5c415a22012b236b8204127a882c2f0b8b8b/apps/transport/lib/jobs/resource_history_job.ex#L46

Ce champ `resource.is_active` n'est que peu utilisé (voire, c'est peut-être pas utilisé du tout, on avait déjà remarqué ça et il faudra le supprimer si c'est le cas):

```sql
select count(*), r.is_active from resource as r group by r.is_active
```

| count | is_active |
|-------|-----------|
|  3914 |           |
|     1 | t         |

Je crois qu'il faut utiliser `d.is_active` à la place, en faisant une jointure. Je ne me lance pas dans un correctif à cette heure là, mais comme ça vous aurez les éléments pour demain.

J'ai remarqué ça en essayant de faire des imports en local pour la remontée des GTFS en base.

On voit bien sur la base de prod que les jobs n'ont pas tourné à 12:00 et 18:00:

```sql
select count(*), worker, date_trunc('hour', completed_at) as completed_at_hour from oban_jobs where state = 'completed' group by completed_at_hour, worker  order by completed_at_hour desc
```

| count | worker                                      | completed_at_hour   |
|-------|---------------------------------------------|---------------------|
|     1 | Transport.Jobs.ResourceHistoryDispatcherJob | 2021-12-07 12:00:00 |
|     1 | Transport.Jobs.ResourceHistoryDispatcherJob | 2021-12-07 06:00:00 |
|   612 | Transport.Jobs.ResourceHistoryJob           | 2021-12-07 06:00:00 |
|     1 | Transport.Jobs.ResourceHistoryDispatcherJob | 2021-12-07 00:00:00 |
|   612 | Transport.Jobs.ResourceHistoryJob           | 2021-12-07 00:00:00 |
|     1 | Transport.Jobs.ResourceHistoryDispatcherJob | 2021-12-06 18:00:00 |
|   612 | Transport.Jobs.ResourceHistoryJob           | 2021-12-06 18:00:00 |

Ca se voit dans le dashboard ici :

<img width="1074" alt="CleanShot 2021-12-07 at 17 57 24@2x" src="https://user-images.githubusercontent.com/10141/145072631-c3e69696-6707-4336-b07c-c27425769c2a.png">

### Comment détecter plus facilement ce type de bug dans le futur

On peut avoir un pattern classique "SRE" qui consiste à avoir un endpoint HTTP, qui va compter le nombre de jobs d'un type donné sur une plage donnée, et retourner un 500 quand on n'est pas dans la bonne zone, le tout monitoré par updown.io ou similaire avec un hook dans Mattermost.

À ce stade c'est overkill, mais le temps viendra où ça le sera moins (ça ou une autre contre-mesure indépendante).

**Comment by fchabouis** [comment]
Oui tout a fait c'est le dataset.is_active qu'il faut utiliser. Mes excuses pour avoir laissé passer l'erreur !

**Comment by thbar** [comment]
@fchabouis aucun souci ! Merci pour la confirmation
