### ISSUE TITLE
Fouiller un peu les GBFS de Bird

### ISSUE THREAD

**Issue by fchabouis** [etalab/transport-site#1990]
On a souvent sur la carte des zones de geofencing des villes ou il est interdit de garer sa trotinette ... partout.
Par exemple https://transport.data.gouv.fr/datasets/trottinettes-castres/
![image](https://user-images.githubusercontent.com/15341118/146050949-fc9e48d8-07be-40b7-aaa2-c8530e1dee86.png)
C'est tout à fait possible que ce soit une erreur de notre carto, ce code est assez récent. Ou sinon c'est une erreur côté Bird et on pourra leur signaler.
Hypothèse : nous manquons de finesse sur les listes de règles et nous affichons des règles qui s'appliquent à différents types de véhicules.

**Comment by AntoineAugusti** [comment]
Pour le cas de Castres, ils semblent avoir une zone autorisée en verte "tout en bas" puis une zone `ride_allowed: false` en orange qui marque l'extérieur de la zone verte.

**Comment by fchabouis** [comment]
@Miryad3108 et @NicolasBerthelot si vous souhaitez faire remonter l'info à Bird, il y a des éléments dans la PR https://github.com/etalab/transport-site/pull/2034

**Comment by Miryad3108** [comment]
J'ai remonté l'information à l'équipe technique de Bird, merci. Je leur ai également demandé de renseigner les aires de stationnement (cf. @AntoineAugusti)

**Comment by AntoineAugusti** [comment]
Est-ce encore pertinent ? @Miryad3108 @fchabouis

**Comment by fchabouis** [comment]
On dirait que c'est toujours d'actualité, le dessin des zones a changé entre temps !
![image](https://user-images.githubusercontent.com/15341118/188927444-cbb07ac7-ac55-4f63-8122-baefc24a27bd.png)
Mais ça m'a toujours l'air faux.

@Miryad3108 si tu arrives à faire venir Bird sur cette issue, on peut en discuter avec eux ?

**Comment by Miryad3108** [comment]
Les derniers échanges avec eux à ce sujet était en janvier. Notre interlocuteur devait transmettre notre demande à leur équipe technique (sûrement anglophone). 
Je vais les relancer en mettant le lien vers l'issue, merci @fchabouis

**Comment by AntoineAugusti** [comment]
[Discuté sur Mattermost](https://mattermost.incubateur.net/betagouv/pl/m9hkanbhujbt3mdr1ry97puf3w) : le problème ne semble plus d'actualité. Si Bird diffusait de manière inadéquate il est probable que ceci ait été corrigé entre temps.
