### ISSUE TITLE
Ajouter une section "Ressources historisées" pour les aménagements cyclables 

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#2005]
Ajouter cette section pour que Géovélo puisse mettre à jour sa ressource plutôt que d'ajouter une nouvelle ressource tous les mois et que les réutilisateurs puissent accéder aux anciennes BNAC.  

https://transport.data.gouv.fr/datasets/amenagements-cyclables-france-metropolitaine/

**Comment by AntoineAugusti** [comment]
Fait depuis
