### ISSUE TITLE
Proxy trip_update Brest renvoie à une erreur 502 

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#2006]
Laurent Mear de Brest vient de nous contacter pour nous signaler que l'URL proxy de leur GTFS-RT pour le flux trip_update renvoie à une erreur  : https://proxy.transport.data.gouv.fr/resource/bibus-brest-gtfs-rt-trip-update
C'est une erreur 502
L'URL d'origine ne renvoie pas à une erreur (voir dans l'espace admini du PAN > configuration proxy) 

L'URL proxy pour le flux alerts de ce même réseau semble fonctionner 

Producteur de ces données : RATPdev

**Comment by AntoineAugusti** [comment]
Symptome en production dans les logs : on retourne une valeur du cache et la valeur n'est jamais rafraîchie (pas d'appel au producteur), pas de nouveau stockage dans le cache avec un TTL.

J'ai tenté d'aller voir les clés dans le cache en faisant SSH + iex, mais sans succès. Ça m'intéresse que quelqu'un d'autre essaie.

```elixir
Cachex.keys(Unlock.Cachex)
```

La date est la veille au soir

```
$ curl -I "https://proxy.transport.data.gouv.fr/resource/bibus-brest-gtfs-rt-trip-update"
HTTP/1.1 502 Bad Gateway
access-control-allow-credentials: true
access-control-allow-origin: *
access-control-expose-headers: *
cache-control: max-age=0, private, must-revalidate
content-disposition: attachment
content-length: 332
content-type: text/html; charset=UTF-8
date: Sun, 19 Dec 2021 21:04:01 GMT
server: Cowboy
strict-transport-security: max-age=31536000
x-request-id: FsJsh7eg-890o20ApVKS
Sozu-Id: 01FQBJRK3F655YV6MTK11YSYGY
```

Résolution du problème en faisant un redémarrage de l'application sur Clever.

**Comment by AntoineAugusti** [comment]
Voir aussi https://github.com/etalab/transport-proxy-config/issues/24

**Comment by AntoineAugusti** [comment]
Voir #2011 et #2012 pour avoir plus de visibilité sur le problème

**Comment by AntoineAugusti** [comment]
#2013, une façon pas très élégante de corriger le problème automatiquement s'il survient
