### ISSUE TITLE
Prévenir le producteur des données temps réel de VLille d'un problème récurrent

### ISSUE THREAD

**Issue by fchabouis** [etalab/transport-site#2022]
Nous avons de temps en temps une erreur sur notre flux GBFS des VLille. Nous ne pouvons pas remplir le champ `last_reported` du fichier `station_status.json`, alors qu'il est [obligatoire](https://github.com/NABSA/gbfs/blob/v2.2/gbfs.md#station_statusjson). Pour le remplir, nous nous basons sur le champ `datemiseajour` de l'API fournie. Et de temps en temps, ce champ est absent.

Nous nous en sommes rendus comptes via la PR #2014 et avons eu dans les logs Sentry le message suivant : ` r["fields"] value is %{"geo" => [50.629044, 3.058288]}`, ou la date de mise à jour est effectivement manquante.

Un de nos bizdevs @NicolasBerthelot ou @Miryad3108 pourrait peut-être leur faire remonter l'information ?

**Comment by AntoineAugusti** [comment]
Avez-vous pu contacter le producteur ?

**Comment by Miryad3108** [comment]
@NicolasBerthelot avait contacté l'AOM le mois dernier. L'AOM a remarqué des problèmes de latence des données et aimerait corriger cela. L'AOM devait prendre contact avec le producteur mais on a pas encore eu de retours.

**Comment by fchabouis** [comment]
Actuellement nous ne pouvons fournir une réponse en GBFS que ~70% du temps. L'adresse du check si vous voulez leur transmettre. 

https://stats.uptimerobot.com/q7nqyiO9yQ/786046975

**Comment by Miryad3108** [comment]
Le problème semble réglé ? 
Je vois que la disponibilité est passé à 100% : https://transport.data.gouv.fr/datasets/velos-libre-service-lille-vlille-disponibilite-en-temps-reel/ et que le champ `last_reported` est rempli

**Comment by AntoineAugusti** [comment]
Pas d'après le monitoring https://stats.uptimerobot.com/q7nqyiO9yQ/786046975, je ne sais pas quelle est l'URL qui est derrière mais j'imagine que la source de Lille est assez instable et que la conversion du PAN est plus stable car on cache pendant plusieurs dizaines de secondes. Il n'empêche que la qualité/disponibilité du flux source n'est pas adéquate.

**Comment by Miryad3108** [comment]
On avait contacté l'AOM en janvier : elle devait voir avec Keolis pour avoir des données GBFS directement mais on a pas eu de retours depuis mars. Je les ai relancé

**Comment by Miryad3108** [comment]
Keolis n'est pas encore prêt à produire/diffuser du GBFS 
lls ont bien pris en compte le sujet mais ils ne peuvent pas encore donner de délai de publication. L'AOM reviendra vers nous.

Je ferme l'issue en attendant le retour de l'AOM
