### ISSUE TITLE
Mieux comprendre le souci de TTL sur Cachex

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#2028]
Je re-crée une méta-issue car le problème pourra nous affecter non seulement sur le proxy mais ailleurs.

### Éléments relatifs directement sur le proxy

- https://github.com/etalab/transport-site/issues/2006 (ticket d'origine ; sur la partie proxy)
- https://github.com/etalab/transport-site/pull/2009
- https://github.com/etalab/transport-proxy-config/issues/24
- https://github.com/etalab/transport-site/pull/2011
- https://github.com/etalab/transport-site/pull/2012
- https://github.com/etalab/transport-site/pull/2013
- https://github.com/whitfin/cachex/issues/281

### Eléments qui pourraient nous impacter ailleurs
 
- code erroné ("si :error est retourné, ça sera considéré comme :commit") https://github.com/etalab/transport-site/blob/2adb7f8bde5531bd42af4c8053415ceab19a20cc/apps/transport/lib/transport/cache.ex#L34-L48
- commentaire que j'ai écrit et qui me paraît partiellement faux https://github.com/etalab/transport-site/blob/4e91846fa1d121f66f01ce2343adb4e293cfc704/apps/unlock/lib/controller.ex#L142-L144 (on peut avoir une race condition non pas sur la récupération HTTP, mais sur l'appel à expire pour sûr)

### Solutions alternatives

- https://github.com/cabol/nebulex qui supporte plusieurs stores (dont Cachex et Redis)

**Comment by thbar** [comment]
Une idée est d'aller faire du "fuzzing" en local, en enlevant le correctif, pour essayer de reproduire le souci.

**Comment by thbar** [comment]
Petite tentative de reproduction en local avec le code de l'application, mais pour l'instant je n'aboutis pas à une situation où le TTL serait de façon permanente à nil. Je conserve toutefois le code (à démarrer avec `mix run scripts/repro.exs` ça servira sûrement !

```elixir
# scripts/repro.exs
Logger.configure(level: :info)

defmodule Report do
  def test do
    {:ok, ttl} = Cachex.ttl(:transport, "home-index-stats")

    if is_nil(ttl) do
      IO.inspect("#{self() |> inspect} TTL=#{ttl |> inspect}")
    else
      IO.puts("TTL=#{ttl |> inspect}")
    end
  end
end

1..2_000_000
|> Task.async_stream(
  fn _ ->
    Transport.Cache.API.fetch(
      "home-index-stats",
      fn ->
        TransportWeb.PageController.compute_home_index_stats()
      end,
      :timer.seconds(1)
    )

    Report.test()
  end,
  max_concurrency: 1_0_000,
  timeout: :infinity
)
|> Enum.each(fn _ -> :ok end)
```

**Comment by thbar** [comment]
En ayant travaillé sur #2960, je retrouve bien le souci via iex, ce qui est "rassurant":

```
❯ clever ssh --alias prod-site   
# SNIP
iex(node@XYZ)1> Cachex.keys(:transport)
{:ok,
 ["unavailabilities_dataset_12", "home-index-stats",
  "unavailabilities_dataset_347"]}
iex(node@XYZ)2> Cachex.ttl(
ttl(cache, key, options \\ [])    
iex(node@XYZ)2> Cachex.ttl(:transport, "home-index-stats")
{:ok, nil}
```

Pour le déclencher en pratique il m'a "suffit" de faire un refresh de la home page plusieurs fois.

**Comment by AntoineAugusti** [comment]
Devrait être résolu par https://github.com/etalab/transport-site/pull/2961
