### ISSUE TITLE
Ajout échelle spatiale départementale

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#2044]
Dans le backoffice on a la possibilité d'associer un jeu de données à : 
- une AOM
- une région 
- une commune sur data.gouv.fr

La logique de référencer par AOM/région est pertinente pour les transports en commun mais pour les aménagements (et peut être stationnements) cyclables ça l'est moins. L'option communes data.gouv.fr exclue les départements. 

Il y aura des données publiées par des départements comme la Charente Maritime qui a publié une ressource pour les aménagements cyclables : https://www.data.gouv.fr/fr/datasets/amenagements-cyclables-sous-maitrise-douvrage-du-departement-de-la-charente-maritime/#resources

Peut on ajouter l'échelle départementale dans les options "territoire associé" du backoffice ?

**Comment by AntoineAugusti** [comment]
Voir sur Mattermost https://mattermost.incubateur.net/betagouv/pl/hkb6a9yoytrq8yzecq9moeuxja

**Comment by Miryad3108** [comment]
Retour de la Charente-Maritime : 

"Même si actuellement les métropoles, CdA et communes urbaines sont les principaux maitres d'ouvrage en termes d'aménagements cyclables, avec l'essor actuel du vélo de plus en plus de départements vont être amené à en créer, notamment en milieu péri-urbain ou rural le long des départementales. Beaucoup ont lancé des schémas vélo dans ce sens (en cours en Charente-Maritime) et possèdent déjà des aménagements assez disparates, mais aussi des voies vertes qui représentent de nombreux kilomètres.
Ainsi l'échelon Départemental parait incoutournable"

**Comment by AntoineAugusti** [comment]
https://github.com/etalab/transport-site/pull/2665 ajoute les données pour les départements, sans avoir de code dédié à l'affichage sur la partie web

**Comment by AntoineAugusti** [comment]
@etalab/transport-bizdev je ferme pour le moment, n'étant pas revenu sur la table. À aborder de nouveau si le besoin se fait sentir.
