### ISSUE TITLE
Données Aix Marseille indisponibles : ressources apparaissent comme étant à jour et non "indisponibles/illisibles"

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#2046]
Les données d'Aix-Marseille ne sont plus accessibles depuis le PAN depuis au moins lundi : https://transport.data.gouv.fr/datasets/reseaux-de-transports-en-commun-de-la-metropole-daix-marseille-provence-et-des-bouches-du-rhone/

(Problème remonté par Google Maps) 

C'est en cours de résolution, c'est un soucis côté Cityway

Je me demande juste pourquoi les ressources apparaissent comme étant "à jour" et pas  "indisponibles/illisibles" 
<img width="578" alt="image" src="https://user-images.githubusercontent.com/59559301/149299277-49e0efba-d1e6-4879-924f-e5933eb99d9a.png">

**Comment by AntoineAugusti** [comment]
Pour ce cas il me semble que les métadonnées du GTFS sont à jour mais que la ressource distante n'est pas disponible

**Comment by AntoineAugusti** [comment]
Le message d'erreur de la validation est 

> error while calling the validator: "Validation failed."

**Comment by AntoineAugusti** [comment]
J'ai regardé à nouveau le code, le bandeau change en fonction de la valeur de `is_available` pour la ressource, actuellement c'est changé une seule fois par jour lors de l'import quotidien.

https://github.com/etalab/transport-site/blob/b1330c71dbf1e8a196be0f4b70fdbb1e7b69d8f6/apps/transport/lib/transport/import_data.ex#L320

Ce serait bien de changer ce statut à l'aide du job vérifiant la disponibilité pour avoir une plus grande disponibilité.
