### ISSUE TITLE
Modifier la page de redirection quand on s'abonne à la Newsletter 

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#2052]
Quand on s'abonne à la NL à partir de la page d'accueil on tombe sur cette page 

On peut supprimer la partie DINSIC avec l'adresse et mettre notre logo ou celui du ministère de la transition écologique ? 

<img width="434" alt="image" src="https://user-images.githubusercontent.com/59559301/149784513-1c56b302-0602-4134-90f2-1e2b81a0394e.png">

**Comment by thbar** [comment]
Ca peut s'arranger oui, il y a plusieurs possibilités techniques d'intégration chez Mailchimp (plus ou moins clés en main), clairement on peut revoir ça facilement !

**Comment by AntoineAugusti** [comment]
Quelqu'un avec un accès à Mailchimp devrait déjà pouvoir mettre à jour le texte et afficher quelques images

**Comment by AntoineAugusti** [comment]
@etalab/transport-bizdev À voir si vous souhaitez vous occuper de ceci/si vous avez besoin d'aide.

**Comment by Miryad3108** [comment]
Merci @AntoineAugusti , je m'en occuperai la semaine prochaine et reviendrai vers vous si besoin

**Comment by AntoineAugusti** [comment]
Je ferme, dites-nous sur Mattermost si besoin d'aide.
