### ISSUE TITLE
Fusionner catégories addresses et stops-ref

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#2057]
Il n'y a pas de tuiles pour [`stops-ref`](https://transport.data.gouv.fr/datasets?type=stops-ref)

L'idée serait de : 
- mettre les JDD `stops-ref` dans `addresses`.
- renommer `addresses` en `locations`
- traduction EN "Locations" et FR "Lieux d'intérêts" (**à valider**)
- garder l'icône actuelle pour addresses

@NicolasBerthelot tu valides tout ça ? On pourrait avoir une nouvelle description pour ce qui apparait sur la recherche en FR et EN sur https://transport.data.gouv.fr/datasets?type=addresses ?

**Comment by AntoineAugusti** [comment]
@NicolasBerthelot Peux-tu compléter les specs quand tu auras un instant ?

**Comment by NicolasBerthelot** [comment]
D'accord avec tout ce qui est mis plus haut. 
Concernant la description de la catégorie _Locations_. Voilà le texte que je pense adapté : 

Cette catégorie regroupe des jeux de données décrivant des lieux d'intérêts relatifs à la mobilité comme les adresses ou la position des arrêts de transports et gares.

Les données d’adresses françaises sont disponibles dans le jeu de données de la [Base Adresse Nationale (BAN)](https://transport.data.gouv.fr/datasets/base-adresse-nationale/) qui a vocation à réunir l’ensemble des adresses géolocalisées du territoire national.

EN : 
This category includes datasets describing places of interest relating to mobility such as addresses or positions of transport stops and stations.

French address data is available in the [National Address Base (BAN) dataset](https://transport.data.gouv.fr/datasets/base-adresse-nationale/), which aims to bring together all the geolocated addresses of the national territory.
