### ISSUE TITLE
Pruning des jobs en "executing"

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#2075]
Sur le backoffice, on va avoir après un crash du worker des jobs coincés en "executing".

Les jobs en attente (available) s'empilent apparemment à hauteur de la concurrence autorisée sur la queue.

Ca va finir par se purger mais uniquement à la vitesse du cron qui ré-empile le tout.

Il va nous falloir un "pruner" comme celui d'Oban Pro.

**Comment by thbar** [comment]
J'ai vérifié, c'est à présent disponible dans la version gratuite:
- https://github.com/sorentwo/oban/issues/603
- https://github.com/sorentwo/oban/commit/e8d0fbe56d4cad6a995b503de21c71385fa4bbd2

**Comment by thbar** [comment]
Correction, cf @fchabouis les jobs avancent quand même

**Comment by AntoineAugusti** [comment]
À noter qu'il faut attendre une release d'Oban et upgrade mais ensuite on devrait pouvoir ajouter ce plugin

```elixir
{Oban.Plugins.Lifeline, rescue_after: :timer.minutes(60)}
```

**Comment by AntoineAugusti** [comment]
Oban a sorti une nouvelle version intégrant cette amélioration https://github.com/sorentwo/oban/releases/tag/v2.11.0

**Comment by thbar** [comment]
En attente d'un correctif chez Oban, car la dernière version pose des problèmes à certaines personnes. Notre branche est prête.

**Comment by AntoineAugusti** [comment]
@thbar On devrait pouvoir maintenant ? https://github.com/sorentwo/oban/issues/652#issuecomment-1125126322

**Comment by thbar** [comment]
@AntoineAugusti une upgrade peut se tenter yes, bien vu !
