### ISSUE TITLE
"RangeError: Out of memory" sur un appel API via Swagger

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#2083]
Si je vais ici:

https://transport.data.gouv.fr/swaggerui#/datasets/API.DatasetController.datasets

et que je clique sur "execute", j'obtiens :

![CleanShot 2022-01-31 at 10 05 10@2x](https://user-images.githubusercontent.com/10141/151766082-09af9ef0-7b41-463c-b172-c262abdd8eca.png)

Le site n'a pas l'air d'être tombé pour autant.

**Comment by thbar** [comment]
Si je fais une query, je vois que le retour d'API fait 17 mégas. Certaines ressources prennent beaucoup de place en terme de JSON, et ça semble lié à l'output des validations qui est intégré directement. Je vais essayer de regrouper quelques stats.

**Comment by thbar** [comment]
Plutôt que `jq`, j'ai utilisé un script Elixir et c'était drôlement plus pratique pour filtrer ça:

```elixir
Mix.install([:jason])

"data.json"
|> File.read!()
|> Jason.decode!()
|> Enum.map(&(&1["resources"]))
|> List.flatten
|> Enum.map(fn(x) -> {x["datagouv_id"], x |> get_in(["metadata", "validation", "errors_count"]) } end)
|> Enum.filter(fn({_d, c}) -> c != nil && c > 10 end)
|> IO.inspect(IEx.inspect_opts)
```

Le retour est le suivant:

```elixir
[
  {"65988d54-1ba2-4ea5-86c8-2ba30162e211", 97441},
  {"aba5743e-230f-49dd-8270-39efc5a72460", 6663},
  {"8218f747-8c53-49d3-8470-24c0afef3dfb", 13594},
  {"50625621-18bd-43cb-8fde-6b8c24bdabb3", 1000},
  {"d732ee90-83df-4161-af71-9aa2cf23952e", 1576},
  {"b11dffe1-dcf9-438e-99bb-23cca0a6761a", 20056},
  {"9ca17d67-3ba3-410b-9e32-6ac7948c3e06", 27660},
  {"ffbd75ac-8e9b-45c2-984d-97599d33d00d", 4441},
  {"da69c1d8-68ff-4068-8e5a-b9bd201f8988", 32},
  {"1da34e46-dca1-4ace-be79-41c1116c9530", 40},
  {"cb26e169-b319-42fd-8d98-be61b94c27a6", 1074},
  {"8ed8a6e7-0385-4a87-b0cc-15e4a24fcd26", 28},
  {"4eb730eb-34e3-4456-a42c-75b36e7a6a55", 13},
  {"a6a84a04-5c1d-4a5b-aa5d-a0734cdac810", 17336}
]
```

**Comment by thbar** [comment]
En googlant un peu, je vois que `RangeError: Out of memory` est un message typiquement Javascript. Je pense que la payload est peut-être digérée côté client (si j'ai compris comment cette implémentation Swagger fonctionne), et que la taille pourrait bien être le point bloquant.

**Comment by thbar** [comment]
Ca pourrait également expliquer le souci d'erreur 500 côté Zapier dans le test réalisé par @NicolasBerthelot (17M c'est vraiment inhabituel pour une payload JSON d'API simple).

**Comment by thbar** [comment]
En affinant je vois que ces grosses payloads sont toutes liées à de la validation jsonschema:

```elixir
Mix.install([:jason])

"data.json"
|> File.read!()
|> Jason.decode!()
|> Enum.map(&(&1["resources"]))
|> List.flatten
|> Enum.filter(fn(d) ->
  c = get_in(d, ["metadata", "validation", "errors_count"])
  c != nil && c > 10
end)
|> Enum.map(&(&1["metadata"]["validation"]["schema_type"]))
|> IO.inspect(IEx.inspect_opts)
```

```elixir
["jsonschema", "jsonschema", "jsonschema", "tableschema", "jsonschema",
 "jsonschema", "jsonschema", "jsonschema", "jsonschema", "jsonschema",
 "jsonschema", "jsonschema", nil, "jsonschema"]
```

https://github.com/etalab/transport-site/issues/1850 aurait permis d'avoir un peu plus de précisions, donc un nouveau vote pour implémenter cet ajout de champs dans l'API.

Je crée un ticket séparé et clair pour indiquer qu'il faudra "trimmer" la payload par défaut.

**Comment by AntoineAugusti** [comment]
Fixed by #2097

**Comment by AntoineAugusti** [comment]
Je vous laisserai fermer cette issue une fois que vous aurez vérifié qu'il n'y a pas de problème à appeler l'API via un logiciel tiers/Swagger UI

**Comment by AntoineAugusti** [comment]
Je suis à 3.1MB avec l'onglet "Network" de Chrome

**Comment by thbar** [comment]
J'ai pareil à présent en fait ; j'ai peut-être pretty printé au passage.

**Comment by thbar** [comment]
Les choses que j'ai pu vérifier jusque là sont les suivantes:

### Analyse de la structure

J'ai lancé une première analyse avec https://www.debugbear.com/json-size-analyzer sur l'output de `https://transport.data.gouv.fr/api/datasets`, et j'ai expandé un peu le résultat, ça donne ceci:

<img width="806" alt="CleanShot 2022-02-07 at 15 39 39@2x" src="https://user-images.githubusercontent.com/10141/152809099-e6acf128-039d-4cad-a376-e60bd9fbd3b6.png">

### Dette technique associée à Swagger

Voir https://github.com/open-api-spex/open_api_spex/issues/421, on est sur une version EOL (depuis peu) servie par un plug. J'ai regardé car j'essayais de comprendre si en mettant à jour, et avec le fix #2097, ça aurait pu suffire.

### Utilisation d'un SwaggerUI plus récent en local

Avec la commande suivante:

```
docker pull swaggerapi/swagger-ui 
docker run -p 80:8080 swaggerapi/swagger-ui 
```

On peut ensuite saisir l'url de notre JSON Swagger dispo ici https://transport.data.gouv.fr/api/openapi.

J'obtiens les résultats suivants:
- Crash sur safari
- Très long sous Chrome

### Conclusions pour le moment

Notre API est trop verbeuse. Il faudra:
- Ou bien paginer
- Ou bien faire de records plus légers, et des sous-requêtes

**Comment by thbar** [comment]
Le test sous Zapier est toujours non concluant ; je pense que 3 MB ça reste bien trop gros pour un retour d'API JSON "classique", il va falloir voir si on fait fondre davantage, quitte à ensuite permettre d'autres opérations.

**Comment by thbar** [comment]
Il semblerait que #2098 n'aie pas suffi à nettoyer pour les deux gros datasets, car j'ai le même résultat:

```elixir
[
  %{
    id: "5eab66a565c27001ac5f11ed",
    page_url: "https://transport.data.gouv.fr/datasets/zfe-zone-a-faibles-emissions",
    reencoded_byte_size: 21693
  },
  %{
    id: "5f3c6c44cadb68fa4c58be26",
    page_url: "https://transport.data.gouv.fr/datasets/arrets-horaires-et-parcours-theoriques-gtfs-des-differents-reseaux-de-transport-membres-du-synd3-1",
    reencoded_byte_size: 988827
  },
  %{
    id: "5b3b3de988ee38708ada1789",
    page_url: "https://transport.data.gouv.fr/datasets/reseaux-de-transports-en-commun-de-la-metropole-daix-marseille-provence-et-des-bouches-du-rhone",
    reencoded_byte_size: 714734
  }
]
```

Il va falloir enquêter.

**Comment by thbar** [comment]
Je me suis appuyé sur l'API qui retourne la donnée d'un dataset donné, pour afficher cela plus facilement:
- https://transport.data.gouv.fr/api/datasets/5f3c6c44cadb68fa4c58be26
- https://transport.data.gouv.fr/api/datasets/5b3b3de988ee38708ada1789

Si je pipe ça dans `jq`, j'ai:

```
❯ curl --silent https://transport.data.gouv.fr/api/datasets/5f3c6c44cadb68fa4c58be26 | jq ".community_resources | length" 
1418

transport-site on  master [$!?⇣] via 💧 v1.12.2 (OTP 24) took 3s 
❯ curl --silent https://transport.data.gouv.fr/api/datasets/5b3b3de988ee38708ada1789 | jq ".community_resources | length"
938
```

Donc sauf erreur on a encore 1418+938 ressources communautaires à purger ici.

**Comment by fchabouis** [comment]
Si je vais sur la page data.gouv.fr du premier : 
https://www.data.gouv.fr/fr/datasets/arrets-horaires-et-parcours-theoriques-gtfs-des-differents-reseaux-de-transport-membres-du-synd3-1/#community-resources
Il en reste 13.

Et le 2ème, il en reste 0.
https://www.data.gouv.fr/fr/datasets/reseaux-de-transports-en-commun-de-la-metropole-daix-marseille-provence-et-des-bouches-du-rhone/#community-resources

C'est plus un problème lors de l'import data.gouv => transport visiblement.

**Comment by fchabouis** [comment]
Effectivement, j'ai essayé d'importer à la main, et ça échoue, probablement à cause de la taille de la transaction. Je vais supprimer les ressources communautaires à la main.

le dataset 146 :
![image](https://user-images.githubusercontent.com/15341118/152942046-95de81e8-4108-4006-aa48-d7af44961d85.png)

et le 506 :
![image](https://user-images.githubusercontent.com/15341118/152942109-b3c0ead7-0e2f-41dd-8f79-4f3b486b6b8b.png)

**Comment by thbar** [comment]
Super merci @fchabouis d'avoir été voir de l'autre côté !

**Comment by thbar** [comment]
Les payloads sont bien allégées de leurs ressources communautaires :

```
❯ curl --silent https://transport.data.gouv.fr/api/datasets/5f3c6c44cadb68fa4c58be26 | jq ".community_resources | length" 
13

❯ curl --silent https://transport.data.gouv.fr/api/datasets/5b3b3de988ee38708ada1789 | jq ".community_resources | length"
0
```

Par contre il reste un souci de taille malgré tout, je regarde de plus près.

**Comment by thbar** [comment]
Les datasets ont fondu, les plus gros sont à présent:

```elixir

  %{
    id: "5eab66a565c27001ac5f11ed",
    page_url: "https://transport.data.gouv.fr/datasets/zfe-zone-a-faibles-emissions",
    reencoded_byte_size: 21693
  },
  %{
    id: "5f3c6c44cadb68fa4c58be26",
    page_url: "https://transport.data.gouv.fr/datasets/arrets-horaires-et-parcours-theoriques-gtfs-des-differents-reseaux-de-transport-membres-du-synd3-1",
    reencoded_byte_size: 22778
  }
]
```

**Comment by thbar** [comment]
On est passé de 3.1 MB à 900k à présent (en partant de 17 MB à l'origine):

```
$ curl -I https://transport.data.gouv.fr/api/datasets | grep content-length
content-length: 923898
```

Safari met super longtemps (plusieurs minutes) à digérer l'appel Swagger pour https://transport.data.gouv.fr/swaggerui#/datasets/API.DatasetController.datasets, mais à présent ça fonctionne.

Idem de l'autre côté avec Chrome.

Je vais avoir avec @NicolasBerthelot si ça suffit pour avancer dans Zapier, puis je clôturerai ici.

Ma conclusion est quand même qu'il faudrait alléger le retour principal de l'API, avec moins de choses dedans par défaut, et probablement une forme de pagination (même si pour les outils comme Zapier après ça complique un peu la donne), si on ne peut pas alléger, car en l'état pas mal d'outils vont avoir un peu de mal !

**Comment by thbar** [comment]
J'ai créé un ticket spécifique (#2101) pour le problème de Zapier, dont @NicolasBerthelot a confirmé qu'il continuait à se produire malgré les optimisations (mais qui ne sont pas perdues, elles étaient nécessaires je pense).
