### ISSUE TITLE
Ergonomie de notre portail API (Swagger) 

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#2084]
Aujourd'hui durant un test @NicolasBerthelot était sur https://transport.data.gouv.fr/swaggerui#/datasets/API.DatasetController.datasets, et cherchait l'url à utiliser pour un service.

On peut être tenté de croire que https://transport.data.gouv.fr/swaggerui#/datasets/API.DatasetController.datasets est l'URL de l'API, mais ce n'est pas le cas et elle ne saute pas aux yeux si on ne connait pas le système.

On ne dispose par défaut que d'une url relative (`/api/datasets`), et pour avoir une url complète il faut faire "execute" sauf erreur, ce qui dans certains cas lève même une erreur (#2083).

Il serait bien de trouver comment configurer cela si possible, pour avoir des urls plus "friendly" et utilisables telles quelles.

À mettre au regard de notre enquête vers l'écosystème (poke @Miryad3108 également) concernant l'usage (ou pas) de l'API.

**Comment by AntoineAugusti** [comment]
@thbar Fermer ?

**Comment by thbar** [comment]
Yes !
