### ISSUE TITLE
Documenter comment on peut valider une requête ou une réponse SIRI (via XSD)

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#2086]
Dans le cadre d'un échange avec un producteur de donnée, j'ai fait une "spike" pour essayer de valider une requête SIRI via les schémas XSD (https://github.com/SIRI-CEN/SIRI/tree/integration/xsd).

Ce n'est pas encore concluant:
- j'avais initialement des erreurs du type `parsing_external_schema_failed`
- en finissant par les régler j'ai des `not_uniquely_defined_in_schema`
- à la fin, le script semble coincé et ne retourne jamais (ou pas assez vite)

J'en reste là, je préfère coller ça dans une issue pour l'instant vu le niveau de maturité de la chose.

Il me paraît clair qu'avoir une validation même partielle directement en Elixir aura une utilité (ex: pour pouvoir cabler ça directement dans un éventuel proxy d'une forme ou une autre), toutefois on pourra aussi faire un pas de côté et passer par un autre langage pour commencer (quitte à revenir solidifier plus tard dans la techno principale).

J'ai cloné au même niveau que le repo principal le repo SIRI (https://github.com/SIRI-CEN/SIRI/tree/integration/xsd), puis:

```elixir
{content, _} = :xmerl_scan.file("distribus-check-status-query.xml")
# https://www.erlang.org/doc/man/xmerl_xsd.html#process_validate-3
data =
  :xmerl_xsd.process_validate("../SIRI/xsd/siri.xsd" |> Path.expand(), content, [
    {:fetch_path,
     [
        "../SIRI/xsd/siri_utility",
        "../SIRI/xsd/siri",
        "../SIRI/xsd/xml/2009/01",
        "../SIRI/xsd/gml",
        "../SIRI/xsd/siri_model"
     ]}
  ])

case data do
  {:error, {:schema_failure, stuff}} ->
    stuff
    |> Enum.reject(fn {_, :xmerl_xsd, d} ->
      case d do
        {:type_not_uniquely_defined_in_schema, _} -> true
        {:parsing_external_schema_failed, _path, :enoent} -> true
        _ -> false
      end
    end)
    |> IO.inspect(IEx.inspect_opts())
end
```

**Comment by thbar** [comment]
Lors du travail sur le proxy SIRI, je suis (re)tombé sur le code de la Norvège sur ces points là, je note le lien ici, ça servira de point de comparaison quand je revisiterai cela.

https://github.com/entur/siri-java-model/blob/master/src/main/java/org/entur/siri/validator/SiriValidator.java

**Comment by AntoineAugusti** [comment]
Je ferme, je pense que le travail sur le proxy SIRI va amener pas mal d'éléments dans notre codebase pour bien gérer ça. Ça reste dans les archives de GitHub.
