### ISSUE TITLE
Petit problème catégories de données fiche dataset

### ISSUE THREAD

**Issue by NicolasBerthelot** [etalab/transport-site#2093]
Hello, 

Je constate qu'on a un petit problème sur les catégories de données qu'on affiche pour les jeux de données temps-réel: 
https://transport.data.gouv.fr/datasets/horaires-theoriques-et-temps-reel-du-reseau-lr-11-lalouvesc-tournon-st-felicien-gtfs-gtfs-rt/
On dit que le jeux de données appartient à la catégorie "Transport public collectif - horaires théoriques"alors qu'il s'agit de données sur les horaires théoriques et statiques. Cela vient du renommage de la catégorie. Il faudrait voir comment régler ça pour n'indiquer que "Transport public collectif"

**Comment by fchabouis** [comment]
Faut voir ce qu'on veut avoir dans la home pour rester cohérents.

![image](https://user-images.githubusercontent.com/15341118/152962997-082bcc9b-b8e7-4c48-9c68-cb50dd9a0367.png)

On fait 2 filtres sur les datasets différents :
* les datasets de type "public-transit"
* les datasets de type "public-transit" ayant du temps réel.

Ce ne sont pas des catégories distinctes, vu que tous les datasets real time sont aussi dans la première catégorie !

On pourrait avoir "Transport public collectif" et "Transport public collectif, horaires temps réel".

**Comment by AntoineAugusti** [comment]
À noter aussi que quand on a la liste des données pour les horaires temps réel, le titre est simplement "Jeux de données".

https://transport.data.gouv.fr/datasets?type=public-transit&filter=has_realtime

Mais on a un "custom search message" cohérent avec le temps réel.

Bref, quel est le comportement attendu sur la fiche et sur la liste des JDD ?

**Comment by AntoineAugusti** [comment]
@NicolasBerthelot N'hésite pas à clarifier le comportement attendu

**Comment by AntoineAugusti** [comment]
@Miryad3108 @ChristinaLaumond @NicolasBerthelot Si vous avez un avis sur ce ticket

**Comment by Miryad3108** [comment]
ça ne serait pas plus simple de faire apparaître les deux catégories : 
- transports collectifs - horaires théoriques 
- transports collectifs - horaires temps-réel 
? 

Si c'est possible de ne mettre que "transports collectifs" dans la section "Catégorie" quand il y a à la fois du théorique et du temps-réel sans avoir à modifier le nom des tuiles, c'est encore mieux mais je serai d'avis à garder les noms de tuile actuels (ne pas passer de transports collectifs - horaires théoriques à transports collectifs sur la tuile)

**Comment by ChristinaLaumond** [comment]
hello, 
je suis du même avis que Miryad, 
Si au niveau de type de données on pouvait avoir les 2 catégories affichées (l'une sous l'autre) ce serait probablement le + lisible pour le réutilisateur pour savoir rapidement le contenu du jdd   
<img width="208" alt="image" src="https://user-images.githubusercontent.com/101095139/169478475-e7b84f40-8958-447f-9b5f-8f9efdcaead1.png">

On aurait donc ici : 
transport public collectif - horaires théoriques
transport public collectif - horaires temps réel

**Comment by AntoineAugusti** [comment]
@etalab/transport-bizdev J'ai fait une modification dans la PR
