### ISSUE TITLE
Débrancher définitivement l'ancien convertisseur GTFS => GeoJSON et NeTEx

### ISSUE THREAD

**Issue by fchabouis** [etalab/transport-site#2096]
Je fais cette issue pour noter ce qu'il reste à faire :

- [x] arrêter le CRON en prod et supprimer le code correspondant #2095 
- [x] supprimer l'instance Hetzner
- [x] Archiver le repo https://github.com/etalab/gtfs_converter
- [x] Mettre note la confif de gtfs_converter concernant la mise hors service => https://github.com/etalab/transport_deploy/tree/master/converter
- [x] Supprimer l'entrée DNS de convertisseur.transport.data.gouv.fr
- [x] Supprimer DNS `dashboard.convertisseur.transport.data.gouv.fr` (si différent ?)
- [x] Supprimer les ressources communautaires résiduelles https://github.com/etalab/transport-site/pull/2098
- [ ] Communiquer le fait qu'il n'y ait plus de ressources communautaires associées pour le moment ? Ou bien les remettre, à discuter.

**Comment by thbar** [comment]
J'ai ajouté un item, et j'ai songé à proposer de faire une rotation de l'API Key, présente ici:
- Sur le serveur Hetzner
- Dans le code https://github.com/etalab/transport_deploy/blob/master/converter/docker-compose.yml

Toutefois si on fait ça il faudra aussi le modifier ici:
- https://github.com/etalab/transport_deploy/blob/master/transpo_rt/scripts/scripts/publish_resources.py
- et peut-être attendre d'avoir fait le point https://github.com/etalab/transport-site/issues/2066

Donc au final je suis plutôt d'avis de temporiser là dessus.

**Comment by thbar** [comment]
Point remplacé par https://github.com/etalab/transport_deploy/issues/54
