### ISSUE TITLE
Mettre en place un système d'audit de "ce qui aurait du être traité" (aka "data screens")

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#2099]
Pas mal de jobs tournent actuellement, et dans certains cas, on sait qu'on va très probablement épuiser les "retries" (on voit cela apparaître dans le dashboard, et on voit aussi des redémarrages intempestifs #2087).

Une astuce qui va servir c'est de considérer que les jobs sont un "détail d'implémentation", et d'aller écrire des contre-vérifications, qui vérifient non pas comment le travail a été fait, mais que l'outcome est bien là.

Ralph Kimball (auteur classique en ETL, datawarehouse et modélisation dimensionnelle) appelle cela (voir [The Data Warehouse ETL Toolkit: Practical Techniques for Extracting, Cleaning, Conforming, and Delivering Data](https://www.amazon.fr/Data-Warehouse-ETL-Toolkit-Techniques/dp/0764567578)) des "data screens".

On peut commencer assez simple, et écrire sous forme de tests `ExUnit` des assertions un peu globales pour vérifier l'état de ce qui est attendu et la réalité constatée.

Utiliser un framework déjà existant permet de faciliter la création de nouveaux tests dans le futur.

Il faut faire attention à ne pas perturber la production avec ces screens, et ça passe généralement par un peu de prudence et l'écriture de tests performants, et dans un second temps ça peut passer par l'utilisation de systèmes secondaires (replicas), ou du "throttling".

On pourra mettre ça en place sous forme d'un module simple, qui pourra être déclenché depuis Oban de façon régulière, et nous permettra de faire un reporting dessus dans le temps.

**Comment by AntoineAugusti** [comment]
Une idée potentielle de vérification / checker, vérifier que le bucket Cellar `transport-data-gouv-fr-on-demand-validation-prod` contient bien 0 objets, ou pas d'objets anciens.

**Comment by thbar** [comment]
@AntoineAugusti merci, ça fait partie des bons premiers candidats, je vais commencer ça en fin de semaine, top !

**Comment by AntoineAugusti** [comment]
Regarder les flux GBFS où la validation n'a pas été effectuée, actuellement à `null`. Ou envoyer une erreur dans Sentry.

```sql
select id, metadata->'validation'
from resource r
where format = 'gbfs' and r.metadata ? 'validation'
```

[Voir Mattermost](https://mattermost.incubateur.net/betagouv/pl/61h4b3ridtbzmc94fsfdy7kmdy)

**Comment by AntoineAugusti** [comment]
@thbar Yep
