### ISSUE TITLE
Ajouter un lien depuis notre Home vers https://normes.transport.data.gouv.fr/

### ISSUE THREAD

**Issue by fchabouis** [etalab/transport-site#2100]

**Comment by AntoineAugusti** [comment]
@fchabouis Tu t'en charges ? Il faut attendre quelque chose ?

**Comment by thbar** [comment]
Ajout d'un deuxième lien vers la doc déclaration de conformité à prévoir (poke @Benoit-MINT @Miryad3108).

**Comment by Benoit-MINT** [comment]
Création d’un nouvel onglet "Réglementation", avec pour sous onglets : “Normes”, “Déclaration de conformité”

Le sous onglet “Normes” renvoie vers : https://normes.transport.data.gouv.fr/
Le sous onglet “Déclaration de conformité” renvoie vers : page de la doc (à créer) relative à la déclaration de conformité
