### ISSUE TITLE
Ressource GTFS-RT Car Jaune marquée comme non disponible

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#2106]
Les données GTFS-RT sont marquées comme indisponibles sur le PAN : https://transport.data.gouv.fr/datasets/horaires-theoriques-au-format-gtfs-et-horaires-temps-reel-au-format-gtfs-rt-du-reseau-car-jaune-a-la-reunion/ mais le producteur affirme qu'elles sont toujours accessibles et valides à travers ce lien

**Comment by AntoineAugusti** [comment]
Similaire à #1934.

Pour vérifier la disponibilité d'une ressource, on fait tout d'abord une requête `HEAD` en HTTP.

```
$ curl -I http://gieactiv.locbusspec.com:9404/api/GtfsRt/GetTripUpdates
HTTP/1.1 404 Not Found
Content-Length: 0
Server: Kestrel
X-Powered-By: ASP.NET
Access-Control-Allow-Origin: *
Date: Wed, 09 Feb 2022 08:03:22 GMT
```

Il faudrait contacter le producteur pour que le serveur gère correctement la méthode `HEAD`.

Tu peux tenter de faire des requêtes HEAD avec ta machine ou un site comme https://reqbin.com/

**Comment by AntoineAugusti** [comment]
C'était pas dit explicitement dans mon premier message, mais le problème est que le serveur répond une 404 au HEAD. Il pourrait répondre une 200 ou alors `405 Method Not Allowed` et on testerait un GET.

**Comment by AntoineAugusti** [comment]
@Miryad3108 on a des nouvelles ?

**Comment by Miryad3108** [comment]
@AntoineAugusti je les ai relancé ce matin. Aux dernières nouvelles, ils devaient remonter le problème au producteur. Je te tiens au courant

**Comment by Miryad3108** [comment]
@AntoineAugusti Le problème a bien été remonté au producteur (SPEC): l'AOM a fait une relance hier

**Comment by Miryad3108** [comment]
@AntoineAugusti le producteur nous signale que c'est réglé : tu peux me le confirmer ?

**Comment by AntoineAugusti** [comment]
@Miryad3108 C'est réparé depuis le 2022-06-14 09:30:05 UTC !

Tu peux vérifier avec les instructions données sur https://github.com/etalab/transport-site/issues/2106#issuecomment-1033464895 et le taux de disponibilité remonte sur https://transport.data.gouv.fr/resources/36515
