### ISSUE TITLE
Retrouver une capacité à suivre les exceptions

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#2108]
Nos exceptions sont "droppées" car le quota général Beta Gouv (transverse) est atteint.

C'est vraiment embêtant car on n'est pas prévenu des soucis du type https://github.com/etalab/transport-site/pull/2107.

Solutions envisageables:
- Aller voir si le quota peut être amélioré (c'est du mutualisé)
- Vérifier si la partie API est couverte par Sentry (c'est pas 100% sûr)
- Prendre notre propre Sentry
- Passer à https://appsignal.com/  qu'on avait évoqué à un moment

**Comment by thbar** [comment]
Le quota va être difficile à améliorer. Je suis en train de me renseigner sur les options (UGAP, paiement direct).

**Comment by AntoineAugusti** [comment]
Nous avons migré vers [une nouvelle organisation Sentry](https://sentry.io/organizations/transport-data-gouv-fr) pour notre équipe et on a obtenu un plan gratuit, car projet open source.

Donc problème résolu, jusqu'à la prochaine fois !
