### ISSUE TITLE
Ajout nouveau réutilisateur : Moovibreizh

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#2113]
https://www.data.gouv.fr/fr/organizations/moovibreizh/

![MooviBreizh](https://user-images.githubusercontent.com/59559301/153819705-83daee8e-00ee-43fa-bdb3-9e14ae363b76.svg)

![logo_detail_black](https://user-images.githubusercontent.com/59559301/154016154-99c43fda-c3aa-4022-88e7-704734d33314.png)

**Comment by AntoineAugusti** [comment]
Quel logo il faut utiliser ?

**Comment by Miryad3108** [comment]
Celui que tu veux : il a envoyé sous deux formats (PNG et SVG)
