### ISSUE TITLE
Retour Réutilisateurs : Les données "trip update" d'Annemasse diffusées avec proxy sont vides 

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#2119]
La Région Auvergne-Rhône-Alpes réutilise certaines données temps-réel avec lien proxy 
Nicolas, de la région, a remonté que les données "trip update" d'Annemasse sur lesquelles on fait proxy sont vides mais j'ai un retour HTTP 200 et une taille RAM 18.28 KB dans l'espace admin' pour ces données : https://proxy.transport.data.gouv.fr/resource/tac-annemasse-gtfs-rt-trip-update

L'un d'entre vous peut me faire un retour dessus ?

**Comment by AntoineAugusti** [comment]
J'ai utilisé https://github.com/kurtraschke/gtfs-rt-dump pour regarder.

```
java -jar gtfs-rt-dump-1.0-withAllDependencies.jar -u https://proxy.transport.data.gouv.fr/resource/tac-annemasse-gtfs-rt-trip-update
```

donne le contenu suivant à l'instant https://pastebin.com/j36cy1CG

**Comment by Miryad3108** [comment]
Le réutilisateur (Okina) arrive à accéder aux données 
"Je vous confirme que nous avons bien récupéré des données valides depuis le flux temps-réel TripUpdate d’Annemasse aujourd’hui"
