### ISSUE TITLE
Soucis de délivrabilité email ?

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#2131]
J'ai remarqué plusieurs symptômes qui peuvent être liés à des soucis de délivrabilité des emails (newsletter ou pas). Du coup je prends des notes, car on peut être amené à mal délivrer la newsletter sans le savoir, ou avoir des contacts via nos emails classiques qu'on ne recevrait potentiellement pas (point de vigilance).

### Soucis constatés

Chez moi la newsletter "de test" commence à arriver marquée en spam dans le titre :

![CleanShot 2022-02-21 at 10 18 50@2x](https://user-images.githubusercontent.com/10141/154925231-79b1c66a-aca5-407a-acd1-d42b03cb2dc0.png)

Je commence même à observer des arrivées directement dans le répertoire spam:

<img width="991" alt="CleanShot 2022-02-21 at 10 23 06@2x" src="https://user-images.githubusercontent.com/10141/154926185-ab403b6b-e681-4ca2-ab94-844b3205fefd.png">

### Points à vérifier

- [x] Récupérer les credentials pour accéder à Mailchimp
- [ ] Noter les mesures de délivrabilité passées en mode newletter
- [ ] Récupérer les credentials Mailjet
- [ ] Noter les mesures de délivrabilité sur le transactionnel (Mailjet normalement)
- [ ] ...

**Comment by NicolasBerthelot** [comment]
Apparemment cette page pourrait répondre à certains de nos problèmes : https://mailchimp.com/fr/help/limitations-of-free-email-addresses/

**Comment by thbar** [comment]
@NicolasBerthelot ah super info, je ne réalisais pas qu'on était en gratuit déjà...

**Comment by thbar** [comment]
Points en lien:
- https://mattermost.incubateur.net/betagouv/pl/1ciygztsytdxiyqpejgrxnow3w
- https://beta.gouv.fr/startups/notifications.html pour le futur
- recos: ne pas utiliser notre propre domaine pour envoyer les emails ; IP dédiée ; https://mattermost.incubateur.net/betagouv/pl/1qhrsgdce3n3b8hohh4itusd5c

**Comment by thbar** [comment]
Notes via @jdauphant que je remercie (via https://mattermost.incubateur.net/betagouv/pl/cj7cwhxjopy4mbeu3ajkwxgbpr):

> Je pense qu'il faut lancer une information général sur les emails, ça arrive pas mal en spam en ce moment, un truc du genre :
>
> :warning: Les emails beta.gouv.fr commencent à arriver fortement en spam.
Nous devons collectivement appliquer une meilleure hygiène sur l'envoi d'email pour améliorer la situation.
>
> * Avec votre adresse personnel jean.dupont@beta.gouv.fr, n'envoyait pas d'email à + de 15 destinataires.
> * Utilisez des mailings listes pour vos messages d'équipes
>
> Pour vos applications ou envoi de newsletter (de startup 
>
> * Utiliser une adresse en @mastartup.beta.gouv.fr ( ne surtout pas utiliser @beta.gouv.fr )
> * Activer SPF et DKIM pour tous ces envois d'emails et utiliser un service comme SendInblue, Tipimail, Dolist et dans une moindre mesure Mailjet
> * Si vous ne savez pas comment faire, demandez de l'aide et tenez informer de vos travaux sur [~domaine-dns-et-email](https://mattermost.incubateur.net/betagouv/channels/domaine-dns-et-email)

**Comment by thbar** [comment]
Résumé pour aujourd'hui:
- Avec @AntoineAugusti nous avons réalisé une vérification de domaine qui manquait dans mailchimp
- Un test d'envoi a permis de voir qu'après ce changement, DMARC était détecté comme validé, et les emails de tests ne passaient plus en spam
- On suit déjà la recommendation de @mastartup.beta.gouv.Fr
- On préconise de faire un partage du lien de l'ancienne newsletter via les réseaux sociaux, mais de ne pas renvoyer
- On va faire un export de la zone et peut-être un peu de test
- On va atteindre les limites du plan en terme de nombre d'abonnés

**Comment by AntoineAugusti** [comment]
Je pense qu'on est bons. Avant de cloturer, peux-tu vérifier les chiffres de la dernière newsletter pour identifier toute surprise ?

Et si rien de bizarre, on ferme ? Merci !

**Comment by thbar** [comment]
J'ai été voir, voilà nos stats sur juillet:
- 25% d'open environ, 1 pour 16 de click

Ca a l'air en ordre, toutefois je vais prévenir qu'il faut qu'on supprime les hard-bounces.

Je clôture.
