### ISSUE TITLE
Notes sur le fonctionnement d'Oban en lien avec le déploiement

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#2147]
J'ai posé la question suivante sur le Slack Elixir:

> Hi! I wonder what are the Oban (& even Phoenix as an aside) best practices to handle shutdown in a blue-green deployment environment, where 2 instances can co-exist at a time.
I have seen shutdown and shutdown_grace_period  ; are there specific tweaks to put in place to handle SIGTERM then SIGKILL like sidekiq does, etc?
Any feedback is most welcome :slightly_smiling_face:

La réponse de l'auteur est:

> The SIGTERM signal will start graceful shutdown and all queues pause. Executing jobs can run for shutdown_grace_period, then they get hard killed. You’ll need to coordinate when the blue/green cycle sends SIGKILL and tweak the grace period to match.

Il faudra vérifier le fonctionnement de CleverCloud par rapport à ça, c'est une info intéressante pour améliorer la gestion des jobs au déploiement.

**Comment by AntoineAugusti** [comment]
Ça fait un bon moment que cette issue est ouverte et il ne me semble pas qu'on ait eu de problèmes particuliers avec Oban étant donné qu'on est bien au fait du fonctionnement.

On ferme ?

**Comment by thbar** [comment]
À ce stade oui on ferme, on n'a pas encore en tout cas le niveau de finesse pour gérer ça correctement si ça posait problème (drains etc).

Merci !
