### ISSUE TITLE
Mettre à jour l'URL vers le validateur GTFS-RT

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#2152]
Le répertoire va changer de mainteneur et donc d'URL prochainement.

---

Attention l'url va changer, on peut se noter un ticket quelque part pour penser à mettre à jour ?

_Originally posted by @thbar in https://github.com/etalab/transport-site/pull/2150#discussion_r813887130_

**Comment by thbar** [comment]
Points connexes à traiter:
- [ ] Adapter `transport-tools` pour pointer sur https://github.com/MobilityData/gtfs-realtime-validator
- [ ] Faire une release de `transport-tools`
- [ ] Faire une release de `transport-ops` (à partir de la branche de maintenance https://github.com/etalab/transport-ops/branches si on n'est pas déjà passé à Elixir 1.13)
- [ ] Modifier l'URL dans le validateur

**Comment by thbar** [comment]
J'ai été voir, je crois comprendre que le processus de release n'est pas bouclé pour l'instant, il faut attendre.

**Comment by AntoineAugusti** [comment]
https://github.com/MobilityData/gtfs-realtime-validator/issues/105 pour un lien vers un .jar

**Comment by AntoineAugusti** [comment]
Déplacé dans l'autre dépôt.
