### ISSUE TITLE
Urls incorrectes dans les emails envoyés par le worker

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#2154]
En mettant à plat `DOMAIN_NAME` pour le worker (voir https://github.com/etalab/transport-site/issues/2140#issuecomment-1047776491), j'ai introduit un problème: les emails envoyés par les jobs nocturnes contiennent des urls qui pointent vers worker (et sont donc incorrectes):

![CleanShot 2022-02-25 at 09 47 41@2x](https://user-images.githubusercontent.com/10141/155684297-0aa70ec6-fac5-47ed-a93c-ab73d685146f.png)

**Comment by thbar** [comment]
Poke @Miryad3108 on va traiter ça rapidement.

**Comment by thbar** [comment]
Le code concerné est ici :

https://github.com/etalab/transport-site/blob/97ddf995774d349c4f5dbce72346f548db42b313/apps/transport/lib/transport/data_checker.ex#L109-L120

Toutefois il existe d'autres occurrences :

https://github.com/etalab/transport-site/search?q=Client.send_mail

**Comment by AntoineAugusti** [comment]
Est-ce qu'il y a encore du travail à faire ou on peut clore ?

**Comment by thbar** [comment]
J'attends le prochain mail pour vérifier et après oui !

**Comment by AntoineAugusti** [comment]
On en a eu un ce matin à 1h du mat'

**Comment by thbar** [comment]
> On en a eu un ce matin à 1h du mat'

Merci @AntoineAugusti!

C'est bon, #2157 a bien corrigé le souci:

<img width="554" alt="CleanShot 2022-02-28 at 11 22 49@2x" src="https://user-images.githubusercontent.com/10141/155966516-cd67b7c9-1755-43dd-aa08-cd49981c1494.png">

Les liens fonctionnent à nouveau.
