### ISSUE TITLE
Home page à optimiser / alléger ?

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#2189]
Suite à un ajout de logo aujourd'hui sur la home, j'ai ré-observer que la taille totale des logos commence à être grosse. J'ai été faire tourner l'outil de Google "PageSpeed Insights" sur la home page, avec Chrome, et ça confirme ce point (et d'autres).

Je crée le ticket pour qu'on pense à aller traiter à un moment, ou en tout cas pour en discuter et voir ce qui sera pertinent (et puis fermer si on estime que c'est "good enough").

Si on fait quelque chose, il faudra aussi voir si ça doit se faire avant ou après le redesign (design system, accessibilité) à venir.

Voilà un extract (https://pagespeed.web.dev/report?url=https%3A%2F%2Ftransport.data.gouv.fr%2F&hl=fr):

### Sur mobile

![CleanShot 2022-03-04 at 17 25 19@2x](https://user-images.githubusercontent.com/10141/156800912-4b86ce2f-0545-4a1e-a091-62b80f5e6873.png)

### Sur desktop

![CleanShot 2022-03-04 at 17 26 03@2x](https://user-images.githubusercontent.com/10141/156801002-7d8885ad-5442-46d8-92fc-f338ac836b22.png)

**Comment by fchabouis** [comment]
Bonne remarque !
Je ne sais pas si on pourrait charger et afficher le haut de la page vite, puis loader le reste.
Sur mobile c'est vraiment limite actuellement.

**Comment by thbar** [comment]
Je clôture pour l'instant, on revisitera si ça revient sur le devant de la scène.
