### ISSUE TITLE
Problème import de données réseau Metz

### ISSUE THREAD

**Issue by NicolasBerthelot** [etalab/transport-site#2195]
Hello, 
La ressource GTFS du réseau de Metz ne semble pas être importée depuis plusieurs jours pourtant j'arrive à la télécharger de mon côté. https://transport.data.gouv.fr/datasets/transport-donnees-gtfs/
A investiguer !

**Comment by AntoineAugusti** [comment]
Problème avec le certificat depuis une machine de prod

```
$ curl --insecure -vvI https://si.metzmetropole.fr 2>&1 | awk 'BEGIN { cert=0 } /^\* SSL connection/ { cert=1 } /^\*/ { if (cert) print }'
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=FR; ST=Grand-Est; L=Metz; O=METZ METROPOLE; CN=*.metzmetropole.fr
*  start date: Nov 16 00:00:00 2021 GMT
*  expire date: Nov 16 23:59:59 2022 GMT
*  issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=Thawte RSA CA 2018
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
* Mark bundle as not supporting multiuse
* Connection #0 to host si.metzmetropole.fr left intact
```

**Comment by AntoineAugusti** [comment]
`ca-certificates` est à jour

```
$ apt install ca-certificates
Reading package lists... Done
Building dependency tree       
Reading state information... Done
ca-certificates is already the newest version (20210119~20.04.2)
```

**Comment by AntoineAugusti** [comment]
@thbar Si t'as des idées, c'est pas mon dada les certificats étranges

**Comment by AntoineAugusti** [comment]
Il semble qu'il manque un certificat intermédiaire https://www.ssllabs.com/ssltest/analyze.html?d=si.metzmetropole.fr

> This server's certificate chain is incomplete. Grade capped to B.

**Comment by AntoineAugusti** [comment]
@NicolasBerthelot Je pense qu'il vaudrait mieux contacter un responsable technique pour vérifier la bonne mise en place de leur certificat. Tu pourras me DM un contact sur Mattermost ?

**Comment by AntoineAugusti** [comment]
@NicolasBerthelot @Miryad3108 vous auriez un contact technique ?

**Comment by Miryad3108** [comment]
Oui @AntoineAugusti, je te l'envoie sur Mattermost

**Comment by AntoineAugusti** [comment]
Mail envoyé, en attente d'un retour

**Comment by AntoineAugusti** [comment]
@etalab/transport-bizdev On a répondu à mon courriel après relance en indiquant que l'interlocuteur n'était pas le bon. Je vous laisse continuer à partir de là.

**Comment by Miryad3108** [comment]
@AntoineAugusti l'AOM a dit que c'était réglé mais de vérifier si ça nous convenait : tu peux vérifier ?

**Comment by AntoineAugusti** [comment]
@Miryad3108 Le problème n'est pas résolu, il manque toujours un certificat intermédiaire. [Voir rapport](https://www.ssllabs.com/ssltest/analyze.html?d=si.metzmetropole.fr).

> This server's certificate chain is incomplete. Grade capped to B.

Voir la section
> Certification Paths > Thawte RSA CA 2018 (extra download)

**Comment by AntoineAugusti** [comment]
Après échange par mail (Objet "Certificat intermédiaire manquant si.metzmetropole.fr") les données sont diffusées depuis si.eurometropolemetz.eu qui a une chaîne de certificats valide.

Il n'y a plus de données en production diffusées depuis si.metzmetropole.fr.

Je clos donc le ticket.
