### ISSUE TITLE
Un GTFS-RT peut être publié à la fois en JSON et en PB

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#2208]
En explorant les données en tant que réutilisateur, je suis tombé sur une ressource dont le format indiqué est `gtfs-rt`, mais qui est en fait du GTFS-RT retranscrit en JSON. Du coup la notion de format n'est pas solide pour déterminer comment décoder la donnée.

Voir https://transport.data.gouv.fr/datasets/reseau-lva, avec deux ressources:
- https://www.itinisere.fr/ftp/GtfsRT/GtfsRT.VIENNE.pb
- https://www.itinisere.fr/ftp/GtfsRT/GtfsRT.VIENNE.json

Cela va se reproduire probablement dans le futur, car il y a une recommendation en cours de discussion sur les best practices GTFS-RT ici dans ce sens, et c'est déjà une pratique courante au moins chez des fournisseurs étrangers.

https://github.com/MobilityData/GTFS_Realtime_Best-Practices/pull/17

Avoir le même format déclaré pose différents problèmes:
- l'utilisateur doit détecter ça et mettre de côté, ou faire un traitement spécifique
- nos validateurs ne tourneront pas dessus

Il faudra sûrement arriver à dissocier le "schéma de départ" (GTFS-RT fournit un schéma) et le format physique de transport, et cette discussion aura également lieu sur d'autres domaines, donc je note ça pour en discuter quand ça reviendra sur le tapis.

**Comment by AntoineAugusti** [comment]
La spec dit que c'est utile de fournir des flux dans d'autres formats dans une optique de debug mais que pour autant le format GTFS-RT est bien du Protobuf. Je pense que le format de ces flux n'est pas bon voire qu'ils ne devraient pas être référencés.

**Comment by AntoineAugusti** [comment]
Traiter #2244 en même temps

**Comment by AntoineAugusti** [comment]
@fchabouis suggère

> je pense que le mieux, ce serait de faire à l'image de ce qu'on fait pour les GTFS, dire que la ressource est disponible dans d'autres format, et ajouter un lien sur la page ressource vers la version json du flux. La traduction vers le json serait faite à la volée par nous, avec du cache, et ça n'apparaitrait pas comme une nouvelle ressource, mais comme un format alternatif de la même ressource.

![image](https://user-images.githubusercontent.com/295709/160802627-5678c4f6-a9a3-43f5-a3d8-2f35f2368650.png)

**Comment by AntoineAugusti** [comment]
La recommendation d'avoir des flux en txt/JSON est une _best practice_ pratiquement adoptée https://github.com/MobilityData/GTFS_Realtime_Best-Practices/pull/17

**Comment by AntoineAugusti** [comment]
@etalab/transport-bizdev Chère équipe bizdev, je souhaite vérifier avec vous qu'il est envisageable de ne pas référencer les ressources avec un format `gtfs-rt` qui ne respectent pas la spécification car :
- elles ne sont pas diffusées en Protobuf (mais en JSON/texte brut)
- le flux GTFS-RT est publié derrière une authentification

L'idée serait de ne référencer sur le PAN que des ressources de qualité/pertinente. Avoir des flux en txt/JSON est utile pour du debug et le PAN générerait ceci dynamiquement à partir des ressources `gtfs-rt`, à la manière des ressources GTFS qui sont déclinées en NeTEx et GeoJSON.

---

## Les flux publiés en JSON
Les ressources concernées sont celles sans informations sur le contenu du flux/pas de validation.

- https://transport.data.gouv.fr/datasets/reseau-cars-region-isere-38
- https://transport.data.gouv.fr/datasets/reseau-ruban
- https://transport.data.gouv.fr/datasets/reseau-lva

Ces URLs viennent du [réseau Itinisère](https://www.itinisere.fr/).

## Flux en JSON + authentification
- https://transport.data.gouv.fr/datasets/reseau-de-transports-en-commun-de-la-communaute-dagglomeration-de-lauxerrois

Prendre compte avec eux pour indiquer que le format attendu est Protobuf et indiquer l'existence d'un cache/proxy qui pourrait aider.

**Comment by AntoineAugusti** [comment]
@Miryad3108 C'est déclaré comme du format `gtfs-rt`, c'est pour ça que ça apparait dans la section "Ressources temps-réel". Pourtant, ce n'est pas du véritable GTFS-RT en Protobuf, mais des flux en JSON.

Peut-être que ce n'est pas si dérangeant et que ça doit être gardé à l'esprit de notre équipe comme une erreur potentielle : un flux peut ne pas être disponible ou ne peut pas être décodé en Protobuf car le format est mauvais.

**Comment by Miryad3108** [comment]
Je ferme le ticket : c'est bien noté du côté bizdev et on relance les AOM quand le format n'est respecte pas la spécification

**Comment by thbar** [comment]
C'est revenu par un autre côté !

- https://github.com/etalab/transport-site/issues/3491
