### ISSUE TITLE
Grouper les credentials Mapbox (mineur)

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#2214]
Un point que j'ai trouvé un peu confusant en travaillant sur le javascript aujourd'hui est la configuration Mapbox, qui apparaît à différents endroits (https://github.com/etalab/transport-site/search?q=mapbox).

Ca peut être le symptôme qu'on a des améliorations à faire sur le packaging du javascript au passage, ou quelque chose comme ça.

C'est un ticket mineur, si on peut trouver comment gérer ça dans webpack ça pourrait être pas mal pour donner d'autres idées (en lien avec:
- #1941
- #2103

**Comment by fchabouis** [comment]
Il suffit en fait de créer un fichier .js, de faire un `export` des credentials, puis d'en faire un `import` partout où on en a besoin.
