### ISSUE TITLE
Étudier la mise à jour de Leaflet

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#2216]
Leaflet v1.7.1, sur lequel on s'appuie pour nos cartes, date de septembre 2020.

La bonne nouvelle c'est qu'ils n'ont pas chômé, et qu'une release 1.8.0 se prépare (https://github.com/Leaflet/Leaflet/issues/7810).

Quand elle sera publiée, ça sera bien d'aller se frotter à un test de mise à jour, voir si on a beaucoup de casse, ou pas trop.

Peut-être le bon moment aussi pour zieuter ce que fait MapLibre, comparativement (point évoqué par @fchabouis).

Je pense qu'on gagnera peut-être à "modulariser" et DRYer nos références à la librairie de carte au passage.

**Comment by fchabouis** [comment]
La version est ancienne mais c'est toujours la version officielle actuelle !
Mes expériences passées de maj de Leafjet ont toujours été bonnes, ça devrait pas être trop compliqué :crossed_fingers:

**Comment by thbar** [comment]
Ok top! On verra ce que ça donne, la liste des breaking changes pour l'instant côté 1.8 est ici https://github.com/Leaflet/Leaflet/blob/main/CHANGELOG.md#%EF%B8%8F-breaking-changes

**Comment by thbar** [comment]
Je regardais un truc dans `yarn.lock` et j'ai vu qu'on référence deux versions actuellement:

https://github.com/etalab/transport-site/blob/dbee2f1d89a9cb33abae8163d66d6a508e42b914/apps/transport/client/yarn.lock#L3354-L3362

Effectivement la version 1.9.3 est sortie à présent, et il y a eu pas mal de bug fixes:

https://github.com/Leaflet/Leaflet/blob/main/CHANGELOG.md

**Comment by thbar** [comment]
On est sur 1.9.4 qui est la dernière version:

```
❯ yarn list | grep leaflet
├─ deck.gl-leaflet@1.2.1
├─ leaflet.pattern@0.1.0
│  ├─ leaflet@~0.7.1
│  └─ leaflet@0.7.7
├─ leaflet@1.9.4
```

Suite à:
- #2698
- #3390

Donc on est bon !
