### ISSUE TITLE
Afficher toutes les caractéristiques possibles d'un GTFS

### ISSUE THREAD

**Issue by NicolasBerthelot** [etalab/transport-site#2218]
Il pourrait être intéressant d'afficher systématiquement dans l'analyseur de ressources toutes les informations qui auraient pu figurer dans le GTFS et d'afficher dans une couleur particulière celles qui sont effectivement contenues. 
Cela a deux avantages : 
- lever l'ambiguïté sur certaines catégories d'informations (topologie du réseau  et tracés des lignes)
- permettre à l'AOM ou au réutilisateur de savoir ce qui pourrait être ajouté

<img width="621" alt="image" src="https://user-images.githubusercontent.com/61453166/158339344-c686c3af-b6c5-4527-8978-03624dcc6186.png">

**Comment by fchabouis** [comment]
Pour info, les possibilités actuelles sont :
"position des stations", "horaires théoriques", "topologie du réseau", "tarifs", "tracés de lignes", "transport à la demande"

**Comment by fchabouis** [comment]
(faut surement pas rajouter "transport à la demande" partout, c'est pas le plus courant)

**Comment by AntoineAugusti** [comment]
À noter que ces labels ne sont pas traduits de mémoire, ce serait l'occasion de faire ça aussi

**Comment by AntoineAugusti** [comment]
Fait dans l'issue mentionnée.
