### ISSUE TITLE
Rubrique "autres jeux de données" - reprendre les noms des Jdd de transport.data.gouv

### ISSUE THREAD

**Issue by ChristinaLaumond** [etalab/transport-site#2221]
Hello, 

J'ai remarqué que les intitulés pour lister les autres jeux de données disponibles pour la même couverture géographique  / AOM sont issus de data.gouv.fr et non de l'intitulé que nous donnons dans transport.data.Gouv.fr
Exemple pour le SMMAG https://transport.data.gouv.fr/datasets/horaires-theoriques-du-funiculaire-du-plateau-des-petites-roches/
<img width="583" alt="image" src="https://user-images.githubusercontent.com/101095139/158351721-016584b5-a75c-4dcd-9729-3586a7648b36.png">
-> intitulés provenant de data.gouv.fr (https://www.data.gouv.fr/fr/datasets/horaires-theoriques-des-lignes-m-covoit-ligne-plus/)

Les noms donnés sur transport.Data.gouv sont "normés", si on pouvait les afficher à la place ca serait top ;) 

Merci beaucoup !

**Comment by AntoineAugusti** [comment]
À traiter en même temps que #2219
