### ISSUE TITLE
Période de validité nulle affichée sur UI

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#2228]
Pas de dates, mais quand même du texte alors que c'est un NeTEx

![image](https://user-images.githubusercontent.com/295709/158423086-89e825c0-7c69-4d0f-aa7f-3fa37fcb979e.png)

https://transport.data.gouv.fr/datasets/horaires-theoriques-du-reseau-trace-colmar-agglomeration/?locale=fr#backed-up-resources

**Comment by fchabouis** [comment]
J'ai commencé à lire, et je sors juste du rabbit hole. Que je vais te laisser explorer, ou que je finirai plus tard.

Ce que j'ai noté :
* les ressources history ont des metadatas si la ressource associée en a
* certaines ressources NeTEx ont des metadatas du validateur GTFS, ce qui n'est pas attendu.
* ce qui signifie qu'à un moment dans le code, on les valide comme des GTFS
* toutes ces ressources semblent venir de Cityway et s'appelent toutes export-netex.zip
 
![image](https://user-images.githubusercontent.com/15341118/159505196-a414ab28-45d8-4caf-a0d5-6c8b668b18bd.png)

* j'ai pas été voir pour toutes, mais celle ci est tagguée comme un format Neptune sur data.gouv.fr et pas NeTEx. https://demo.data.gouv.fr/api/1/datasets/5f46415fbeeeb9eac62f9bf5/

Il va falloir prévoir une passe de nettoyage des ressources et des ressources history NeTEx qui ont des métadatas de GTFS.

**Comment by AntoineAugusti** [comment]
@fchabouis J'ai ouvert une issue pour traiter séparément ce problème de cohérence. Je propose de ne pas étendre cette issue au-delà de la description initiale et de conserver la PR qui résout le problème décrit.
