### ISSUE TITLE
Licences non traduites en anglais

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#2229]
Un exemple avec `lov2`

https://transport.data.gouv.fr/datasets/horaires-theoriques-du-reseau-trace-colmar-agglomeration/?locale=en

**Comment by fchabouis** [comment]
Tu parles du contenu de la licence ?

**Comment by AntoineAugusti** [comment]
![image](https://user-images.githubusercontent.com/295709/161007884-e82d6b20-4ebd-4cc1-8b21-5ba6fed9a6fd.png)

Le fait qu'on affiche juste `lov2`

**Comment by AntoineAugusti** [comment]
J'ai traduit quelques licences en EN dans https://github.com/etalab/transport-site/pull/2778. Je ferme et on pourra compléter.
