### ISSUE TITLE
Utiliser header HTTP pour choisir locale

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#2240]
Choisir la langue du site en fonction des préférences de l'utilisateur.

---
S'inspirer de https://phrase.com/blog/posts/set-and-manage-locale-data-in-your-phoenix-l10n-project/ (plug à la fin)

ou utiliser [cldr](https://github.com/elixir-cldr/cldr) mais c'est une dépendance assez lourde il me semble

**Comment by thbar** [comment]
Quelques notes :

Tu pensais à `Accept-Language` (https://phrase.com/blog/posts/detecting-a-users-locale/) comme header ?

Ca serait bien d'avoir un comportement par défaut qui fait sens comme ça, et de permettre aussi l'override manuel comme actuellement.

> ou utiliser [cldr](https://github.com/elixir-cldr/cldr) mais c'est une dépendance assez lourde il me semble

Je ne sais plus ce que j'avais lu, que ça allait s'alléger dans les versions suivantes ; mais au final on l'a déjà (`ex_cldr`) dans la build.

**Comment by thbar** [comment]
Neat:

https://github.com/elixir-cldr/cldr#use-case

> Parse an [Accept-Language](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.4) http header or a [language tag](https://tools.ietf.org/html/bcp47)
