### ISSUE TITLE
Ressource SIRI double listée

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#2241]
Sur https://transport.data.gouv.fr/datasets/simouv-horaires-theoriques-et-temps-reel-de-transport-public-transvilles-valenciennes/, je vois la ressource SIRI apparaître à la fois dans `Ressources temps réel` et dans `Ressources`.

Il doit manquer un filtre sur la partie basse, je pense.

![CleanShot 2022-03-17 at 10 29 55@2x](https://user-images.githubusercontent.com/10141/158779575-2f00a4c7-6969-4a17-9be3-de2ebef3ceaa.png)

**Comment by thbar** [comment]
C'est réglé via #2264. Merci @AntoineAugusti

**Comment by AntoineAugusti** [comment]
Ah j'avais raté ce duplicate, merci !

**Comment by thbar** [comment]
Je fais un peu de ménage ;-)
