### ISSUE TITLE
"National" inscrit au lieu de "Européen" pour les jdd européens

### ISSUE THREAD

**Issue by ChristinaLaumond** [etalab/transport-site#2246]
Hello, 

Comme discuté dans Mattermost, si on peut changer le "national" par "Européen" pour les jeux de données Européens comme : 

- https://transport.data.gouv.fr/datasets/flixbus-horaires-theoriques-du-reseau-europeen-1/
- https://transport.data.gouv.fr/datasets/blablacar-bus-horaires-theoriques-et-temps-reel-du-reseau-europeen/
- https://transport.data.gouv.fr/datasets/horaires-theoriques-du-reseau-europeen-eurolines-isilines-gtfs/

Ce serait top ! Merci beaucoup (priorité basse ;) )

![image](https://user-images.githubusercontent.com/101095139/158964555-c734979c-e667-4f25-a3a9-c784941db0df.png)

**Comment by AntoineAugusti** [comment]
@ChristinaLaumond Pas un bug, mais une demande d'évolution 😉

**Comment by AntoineAugusti** [comment]
Voir aussi https://github.com/etalab/transport-site/issues/2044 pour l'échelon départemental. Sans avoir regardé le code gérant ceci, je pense que "europe" est plus facile à gérer que les départements.

**Comment by AntoineAugusti** [comment]
@etalab/transport-bizdev Pourriez-vous partager une notion d'importance/priorité pour cette feature ?

**Comment by ChristinaLaumond** [comment]
Sujet non prioritaire, juste une demande émise en interne pour plus de cohérence entre le nom du jeu qui indique "européen" et la localisation qui dit "national".

**Comment by AntoineAugusti** [comment]
Envisager de renommer "National" en "France" aussi si on fait ce ticket

**Comment by Miryad3108** [comment]
Le sujet a été relancé par Trenitalia ce matin qui demande à ajouter Européen (et ne pas remplacer National par Européen) 
"peut on ajouter « européen » en plus de « national » ?"

**Comment by AntoineAugusti** [comment]
On a décidé de continuer à temporiser pour cette fonctionnalité, pas une grosse friction/plus-value pour le moment.

**Comment by Miryad3108** [comment]
Je ferme l'issue en attendant que le sujet soit de nouveau relancé
