### ISSUE TITLE
Ressources et ResourceHistory avec des métadonnées inattendues 

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#2258]
Il a été découvert que certaines ressources qui ne sont pas des GTFS ont des métadonnées qui sont réservées normalement aux GTFS. Ces métadonnées se sont retrouvées dans des ressources historisées également.

Il faudrait comprendre pourquoi on est arrivé à un tel état et réparer la cohérence des données.

_Originally posted by @fchabouis in https://github.com/etalab/transport-site/issues/2228#issuecomment-1075256450_

**Comment by AntoineAugusti** [comment]
Il y a des ressources en production actuellement qui ont des métadonnées propres à des GTFS. Contrairement à ce qui a été dit dans le commentaire initiale, il n'y a pas que des NeTEx, bien que ce soit quasi exclusivement le cas.

```sql
select *
from resource
where format != 'GTFS' and metadata ? 'modes'
```

J'ai 43 ressources

![image](https://user-images.githubusercontent.com/295709/159656809-2241a1e1-4e5e-463c-b3c7-2bfe6b4172f7.png)

Il n'y a pas de logs de validation pour ces ressources, où la validation n'a pas été _skipped_.

```sql
select *
from logs_validation
where resource_id in (select id
from resource
where format != 'GTFS' and metadata ? 'modes') and not skipped;
# -> 0 rows
```

Il y a des ResourceHistory qui ont été dans leur vie des GTFS et des NeTEx, la classification GTFS semble erronée.

```sql
select *, payload->>'format', payload->>'resource_metadata'
from resource_history
where datagouv_id = '21c91b3a-e34e-4961-9ce9-76f0a64454ee'
```

![image](https://user-images.githubusercontent.com/295709/159657979-b597c2be-4987-406a-8fed-451c3ff96816.png)

On remarque des différences entre
- payload->>'format' (rempli depuis `resource.format`)
- payload->>'resource_metadata' (qui provient des métadonnées de l'ancien système d'historisation)

Le [code de migration de l'ancien système au nouveau](https://github.com/etalab/transport-site/blob/b22e4ccbb4b8bb579883b4e3bbd34294d5f5296f/apps/transport/lib/jobs/migrate_history_job.ex) pourrait contenir des bugs.

À noter également que depuis https://github.com/etalab/transport-site/pull/2038 les métadonnées d'une ressource sont conservées d'un import quotidien à l'autre, dès lors qu'on peut réidentifier la ressource dans notre système. Avec ça en tête, il suffit d'une mauvaise classification/validation et d'un stockage de métadonnées pour perpétrer des données erronées.

**Comment by AntoineAugusti** [comment]
J'ai regardé les ressources du [Rhônexpress](https://transport.data.gouv.fr/datasets/horaires-theoriques-du-service-rhonexpress-de-la-metropole-de-lyon-et-du-departement-du-rhone/) qui comporte 1 GTFS et 1 NeTEx.

```sql
select *, payload->>'format', payload->>'resource_metadata'
from resource_history
where payload->>'dataset_id' = '288'
order by inserted_at;
```

![image](https://user-images.githubusercontent.com/295709/159680633-8bb35c1e-3f72-40c9-846c-f31ebd62a8a0.png)

On remarque que :
- les `datagouv_id` changent tous les jours
- les métadonnées comportent des infos propres à du GTFS pour toutes les lignes, GTFS ou NeTEx
- la 1ère ligne date du `2022-03-08` ce qui est relativement récent

`resource_metadata` est rempli depuis `DB.Resource.metadata` lors de l'historisation

https://github.com/etalab/transport-site/blob/85dd6494a89b6736612f5b6eeefae30937ff5b75/apps/transport/lib/jobs/resource_history_job.ex#L99

En local, j'ai supprimé ce JDD et je l'ai importé/validé sans réussir à avoir des métadonnées GTFS dans la ressource NeTEx.

Je n'ai pas de piste pour le moment expliquant comme `resource.metadata` peut contenir des métadonnées GTFS pour du NeTEx

**Comment by AntoineAugusti** [comment]
@etalab/transport-tech si vous avez des idées sur ce sujet je prends toute piste

**Comment by AntoineAugusti** [comment]
@thbar Les `datagouv_id` semblent changer en effet régulièrement pour les ressources qui sont moissonnées depuis ODS sur datagouv, ça c'est embêtant et une première chose.

Mais la question des métadonnées qui semblent provenir du validateur GTFS dans des ressources dont `format != 'GTFS'` reste non résolue.

La possibilité que je vois c'est :
- une ressource est avec une URL distante avec le format `GTFS`
- la ressource distante change (mais pas son URL) et on conserve la même ressource, et surtout les mêmes métadonnées dans notre système
- on a ainsi une ressource avec un format non GTFS mais des métadonnées incohérentes

https://github.com/etalab/transport-site/blob/85dd6494a89b6736612f5b6eeefae30937ff5b75/apps/transport/lib/transport/import_data.ex#L662-L670

Ce qui me parait étonnant c'est qu'à première vue les URLs des ressources sont clairement des NeTEx (mot inclus dans les URLs par exemple).

**Comment by fchabouis** [comment]
Note : les mauvaises métadatas se sont retrouvées historisées dans les ResourceHistory, on pourra aussi éventuellement les nettoyer là
