### ISSUE TITLE
"Les bonnes pratiques de publication" vide dans espace producteur

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#2262]
Cet encart est vide sur https://transport.data.gouv.fr/espace_producteur

![image](https://user-images.githubusercontent.com/295709/159903007-515b377e-ff23-41f4-8be8-c3b1033f8762.png)

@etalab/transport-bizdev qu'est-ce qui est attendu ?

**Comment by AntoineAugusti** [comment]
@fchabouis Je crois que c'est toi qui a travaillé principalement sur cette page, tu connais l'histoire ?

**Comment by ChristinaLaumond** [comment]
Hello, vu avec @Miryad3108 @NicolasBerthelot  on pourrait dans un 1er temps diriger vers la doc suivante : https://doc.transport.data.gouv.fr/producteurs/mettre-a-jour-des-donnees 
En parallèle, on regarde pour avoir une synthèse à inscrire dans le bloc.

Ok pour vous ?

**Comment by fchabouis** [comment]
L'histoire c'est qu'on c'était dit qu'on allait mettre des choses dedans et qu'on l'a jamais fait :D
