### ISSUE TITLE
Ajouter un sous-titre sous un titre de jdd (Blablacar + Fabrique des Mobilités)

### ISSUE THREAD

**Issue by ChristinaLaumond** [etalab/transport-site#2266]
Hello, 
Nous avons vu avec Miryad que les jeux de données des lieux de covoiturage de:
-  Blablacar https://transport.data.gouv.fr/datasets/aires-de-covoiturage-en-france/
- et de la Fabrique des Mobilités  https://transport.data.gouv.fr/datasets/aires-de-covoiturage-base-de-donnees-commune-des-lieux-et/ 
n'étaient plus mis à jour étant donné que seule la base nationale est la référente avec données à jour. 

On aurait pu simplement "déréférencer" ces 2 jeux de données mais Miryad m'a expliqué que Blablacar tenait à le garder étant donné que c'était le 1er jeu à être publié. 

Une solution afin de ne pas amener de confusion auprès des réutilisateurs qui se rendraient sur ce jdd, pourrait-être de mettre un sous-titre au jeu de données en inscrivant quelque chose comme "Attention, ce jeu n'est plus à jour. Pour retrouver la base nationale à jour rdv ici" avec le lien vers la base nationale. 

Qu'en pensez-vous ? 
Merci

**Comment by ChristinaLaumond** [comment]
D'une manière générale, on pourrait généraliser cette demande d'évolution en ayant la possibilité d'inscrire un sous-titre depuis le back-office pour n'importe quel jdd
.

**Comment by AntoineAugusti** [comment]
Pour l'instant l'équipe du PAN fait assez peu d'éditorialisation de jeux de données, uniquement choisir une catégorie et remanier le titre. Voir si on veut s'aventurer dans ça.

Prévoir de faire ça en EN + FR et dans quels cas on peut se permettre ça si on le fait. Réfléchir à comment cette information serait présente côté API aussi, le site web n'étant qu'un aspect.

**Comment by AntoineAugusti** [comment]
@etalab/transport-bizdev Résolu ? Étant donné que les 2 autres JDD ont été référencés.
