### ISSUE TITLE
Lien vers le jdd après édition de ce dernier

### ISSUE THREAD

**Issue by ChristinaLaumond** [etalab/transport-site#2267]
Hello

Après avoir édité un jdd nous avons le message :
<img width="952" alt="image" src="https://user-images.githubusercontent.com/101095139/159943803-2f6fc5bb-8e19-4367-aee2-433a48bd570e.png">
-> serait-il possible d'ajouter à la suite de ce message, le lien vers le jdd qui vient d'être édité pour pouvoir vérifier directement que tout est ok  ? 

Merci

**Comment by AntoineAugusti** [comment]
J'ai regardé et ça prend pas quelques minutes malheureusement. Le code de dataset_controller dans le backoffice est pas si aisé et surtout les messages des flashs ne sont pas affichés en `raw`, ce qui ne permet pas de mettre des liens.

Il faudrait adapter la structure de données des flashs ou voir si passer en `raw` et donc avoir des messages flash avec du HTML ne poserait pas de problème de sécurité.

https://github.com/etalab/transport-site/blob/eb3254325b44b93c08b3a28b6966c8e6e888c226/apps/transport/lib/transport_web/templates/layout/app.html.eex#L60-L72

**Comment by AntoineAugusti** [comment]
@etalab/transport-tech n'hésitez pas à dire si vous voyez un moyen de faire cette demande rapidement/sans impact

**Comment by fchabouis** [comment]
Je savais pas, mais visiblement on peut passer un iodata en contenu d'un flash message : https://stackoverflow.com/a/42913697/1892308
