### ISSUE TITLE
CSS Issue

### ISSUE THREAD

**Issue by Kulgar** [etalab/transport-site#2272]
Hey guys, 

You have a CSS issue on the #map element. You should use width: 100% instead of width: 100vw. 
On Edge, because of that, it adds an horizontal scroll bar, which... isn't good. 
This is because the 100vw doesn't consider the width of the vertical scrollbar.

**Comment by thbar** [comment]
Hello ! Je vérifierai avec mes collègues en fonction de ce qu'on fait ailleurs. Merci !

**Comment by AntoineAugusti** [comment]
@abulte indique avoir le même problème, bloqué par Leaflet lors du scroll. SafarI

**Comment by Kulgar** [comment]
Ce n'est pas tout à fait le même problème. 
Je l'ai identifié aussi celui-là, mais il s'agit du blocage du scroll vertical : il est difficile d'accéder au footer, car quand on scroll, ça scroll dans la carte quand la souris est à l'intérieur de la carte (évidemment).

**Comment by thbar** [comment]
Bon c'est pas encore tout à fait clair, on va déployer comme ça et on reviendra là dessus je pense :-) merci !

**Comment by thbar** [comment]
Je clôture pour le moment, sachant qu'on va refondre le site (DSFR) à un moment.
