### ISSUE TITLE
Modifier les tests qui utilisent le réseau

### ISSUE THREAD

**Issue by fchabouis** [etalab/transport-site#2287]
J'ai remarqué qu'en lançant certains tests, on utilise le réseau. Ce n'est probablement pas voulu.

![image](https://user-images.githubusercontent.com/15341118/161003180-7fe4d229-d576-4916-9477-2e9404a0ebd1.png)

Je vais lister ici au fur et à mesure les fichiers concernés :

- [x] apps/transport/test/transport_web/controllers/backoffice/backoffice_controller_test.exs
- [ ] #1751 (@thbar est dessus)

**Comment by thbar** [comment]
@fchabouis pour info en lien relatif, je suis en train de gérer celui-ci: #1751 ; j'édite la description pour l'ajouter

**Comment by thbar** [comment]
Il en reste, je réouvre et je vais donner des éléments (découvert en travaillant sur #1853).

**Comment by thbar** [comment]
Les joyeux coupables sont tous les tests qui font une de ces invocations :

```elixir
Mox.stub_with(Transport.HTTPoison.Mock, HTTPoison)
Mox.stub_with(Transport.AvailabilityChecker.Mock, Transport.AvailabilityChecker)
```

Ca cela fait que le mock invoque du vrai code qui requête.

**Comment by AntoineAugusti** [comment]
@etalab/transport-tech c'est résolu ça non ?

**Comment by thbar** [comment]
Les appels que j'avais mentionné plus haut sont toujours potentiellement problématiques, mais je pense qu'on doit faire autre chose à côté qui fait que ça ne dérange pas. On verra si ça se représente !
