### ISSUE TITLE
Ajout du nom de la commune dans la carte de la BNLC 

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#2288]
Philippe de la Haute-Garonne demande si on peut ajouter le nom de la commune sur la [carte de visualisation des lieux de covoiturage du PAN](https://transport.data.gouv.fr/datasets/base-nationale-des-lieux-de-covoiturage/).

Message :
" petite remarque sur la carte de la section Visualisation de la page [transport.data.gouv.fr](http://transport.data.gouv.fr/) (cf. capture-carte-portail-transport-data.jpg). Lorsqu’on clique sur un point sur la carte, il serait judicieux, dans la bulle d’info qui s’ouvre, d’ajouter en plus du nom de l’aire, à minima le nom de la commune et du département. Là c’est une peu maigre comme info texte. Le nom de la commune me semble indispensable."

**Comment by AntoineAugusti** [comment]
Actuellement pour une carte CSV on utilise une seule colonne, parmis ces possibilités

https://github.com/etalab/transport-site/blob/4244c9cdea9b8d78ce0246819a6800fd3072cf79/apps/transport/client/javascripts/resource-viz.js#L18

**Comment by AntoineAugusti** [comment]
@fchabouis Tu as un avis sur cette demande ? J'ai un peu de mal à partir dans des fonctionnalités spécifiques à un JDD.
