### ISSUE TITLE
Affichage cohérent des cartes GeoJSON

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#2301]
Suite à https://github.com/etalab/transport-site/pull/2217 de @fchabouis les GeoJSONs disposent de visualisations sur la page de détails de chaque ressource.

Pourtant, certains jeux de données ont une visualisation du GeoJSON proposé en plus de la liste des ressources.

Voir
- [ZFE Reims](https://transport.data.gouv.fr/datasets/zones-a-faibles-emissions-cugr/) avec 1 ressource GeoJSON + 1 carte
- [ZFE Strasbourg](https://transport.data.gouv.fr/datasets/zone-a-faibles-emissions-mobilite/) qui dispose aussi d'1 GeoJSON mais pas de carte

Envisager de revoir `DatasetView.get_resource_to_display` en conséquence

https://github.com/etalab/transport-site/blob/3e44c53fa7ed354b66869ffe915378d560d2c356/apps/transport/lib/transport_web/templates/dataset/details.html.eex#L43-L62

**Comment by AntoineAugusti** [comment]
https://github.com/etalab/transport-site/blob/24c1481de30936451156838a0c2335bade4d9332/apps/transport/client/javascripts/resource-viz.js#L351-L354 a son rôle aussi

**Comment by ptitfred** [comment]
Dans le cas de Strasbourg, c'est lié au pattern utilisé pour les URLs dans leur API :

```
> {:ok, zfe_strasbourg} = DB.Dataset.get_by_slug("zone-a-faibles-emissions-mobilite")
> TransportWeb.DatasetView.get_resource_to_display(zfe_strasbourg).url
"https://data.strasbourg.eu/api/explore/v2.1/catalog/datasets/zfe_emprise/exports/geojson"
```

**Comment by ptitfred** [comment]
Peut-être devrait-on plutôt s'appuyer sur le nom de la resource ?

**Comment by ptitfred** [comment]
Je vais tenir compte du format, comme fait pour d'autres types de visualisations.
