### ISSUE TITLE
Non-réception des emails invitations calendriers via contact

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#2305]
Quand on crée une invitation dans gmail et qu'on ajoute `contact@transport.beta.gouv.fr ` comme invité, aucun email ne semble délivré.

Reproduit par @fchabouis et lors d'une invitation créée par @AntoineAugusti.

Ca sent le souci transverse embêtant.

**Comment by ChristinaLaumond** [comment]
Autre cas : invitation envoyée à des adresses nominatives @beta.gouv.fr à partir d'un compte Google créé avec l'adresse @beta.gouv.fr pour avoir l'agenda Google associé (mais pas le gmail)

**Comment by AntoineAugusti** [comment]
Est-ce encore arrivé ou les précédents problèmes avec le 2FA de Mailchimp ont résolu en même temps cette issue ?

**Comment by ChristinaLaumond** [comment]
je n'ai pas l'impression que le pb se soit reproduit de mon côté..
