### ISSUE TITLE
Utiliser URL stable pour bouton télécharger si hébergé sur data.gouv.fr

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#2308]
data.gouv.fr a 2 URLs pour des ressources.

- Une URL vers la ressource dans sa version actuelle (`url` dans l'API, par exemple `https://demo-static.data.gouv.fr/resources/base-nationale-zfe/20220408-113432/voies.geojson`)
- Une URL stable (`latest` dans l'API, par exemple `https://demo.data.gouv.fr/fr/datasets/r/98c6bcdb-1205-4481-8859-f885290763f2`)

L'URL stable renvoie `HTTP 302 Found` vers la dernière version de la ressource si c'est un fichier qu'on remplace ou vers l'URL distante.

Pour une ressource avec une URL distante, on a un fonctionnement similaire. Par exemple, [ZFE de Strasbourg](https://demo.data.gouv.fr/api/1/datasets/zfe-m-voies-exceptionnelles/).

- `url` : https://data.strasbourg.eu/explore/dataset/zfe_voie_exception/download?format=json&timezone=Europe/Berlin&use_labels_for_header=false
- `latest` : https://demo.data.gouv.fr/fr/datasets/r/eb71541a-192c-4e83-b3d6-bfe3fbfa9f4e

Ces URLs sont enregistrées dans `DB.Resource` lors de l'import https://github.com/etalab/transport-site/blob/ebaae7b8b31e513a7e071b409b63c45dd9c7ead6/apps/transport/lib/transport/import_data.ex#L345-L353

### API
Le champ `url` d'une ressource comporte la `latest_url` et un champ nommé `original_url` comporte `url`

https://github.com/etalab/transport-site/blob/ebaae7b8b31e513a7e071b409b63c45dd9c7ead6/apps/transport/lib/transport_web/api/controllers/datasets_controller.ex#L178-L185

### Page dataset#details

Si la ressource peut être téléchargée directement (lien en HTTPS et pas hébergé sur GitHub) alors on utilise `url` derrière les boutons "Télécharger" et sinon on utilise un contrôleur du PAN afin de proposer un télécharger en HTTPS avec des headers adéquats.

https://github.com/etalab/transport-site/blob/ebaae7b8b31e513a7e071b409b63c45dd9c7ead6/apps/transport/lib/transport_web/views/dataset_view.ex#L449-L451

## Proposition

Ma proposition serait d'utiliser l'URL `latest` pour le bouton de téléchargement si le fichier est hébergé par data.gouv.fr (~ domaine `static.data.gouv.fr`) et de conserver le fonctionnement actuel pour les autres cas.

➡️  promotion d'URLs stables pour les ressources qui sont susceptibles de changer
➡️ éviter des copier/coller d'URLs qui ne vont plus pointer vers la dernière version
➡️ ne pas masquer des URLs distantes potentiellement stables pour les ressources qui ne sont pas des fichiers déposés sur data.gouv.fr

**Comment by thbar** [comment]
Moi ça me paraît une bonne idée à première vue.

Quelques remarques au passage:
- le nommage est pour moi "un peu à l'envers" (dans mes chaussures à moi) côté datagouv ; l'url `latest` renvoie vers la version la plus récente de la donnée, mais du coup pour moi elle devrait plutôt s'appeler `stable_url` justement, et pas `latest`. Et quelque part, le champ `url`, lui, devrait s'appeler `latest_url` pour indiquer qu'elle n'est pas stable. Après je suis conscient que c'est une question de perspective et de où on se place, je parle de notre nommage à nous
- je ne suis pas fan d'avoir dès l'import `resource["latest"] || resource["url"]` ; techniquement je préférerais que ça soit un layer d'accès au dessus qui fasse ce remplacement, de façon à pouvoir identifier plus clairement en base celles où la donnée est manquante
- on verra ce que ça donne côté API également

Sur le plus long terme, ça pose la question du cycle de vie de la donnée de toute façon, et d'avoir une gestion des versions bien calée, bien observable autant par API que via le site, donc ça fait réfléchir, merci !

**Comment by thbar** [comment]
@AntoineAugusti ah 100% d'accord ; ce sont des réflexions pour plus tard, tout à fait d'accord pour avoir un scope comme il est défini ici.

**Comment by fchabouis** [comment]
je trouve que c'est une bonne idée comme fonctionnement.
