### ISSUE TITLE
Notes en vrac pour les workflows de "consolidation nationale"

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#2310]
On a parlé un peu ce matin entre dévs des points de vigilance lorsqu'on crée des bases consolidées.

Je mets des notes un peu en vrac, basées sur les retours ou sur mes XP précédentes:
- On peut commencer simple (toujours !), on trouvera les bonnes solutions en créant plusieurs aggrégations
- On gagnera à avoir un processus de publication qui travaille dans une zone "de préparation" (une zone de staging comme dirait Ralph Kimball), avec quelques checks (automatisés) en sortie, et ne publier le résultat que si ces checks (screens) passent
- Quand le nombre de ressources agrégées est petit, et/ou quand le cycle de changement est lent, on peut tout à fait avoir des screens "en dur" du genre "la ville de Paris a 7 ressources pour la ZFE, avec ces 7 ids, et si ça change je veux arrêter la production pour aller voir".
- En particulier, il faut éviter de publier une base consolidée où un élément (surtout de grosse taille) habituellement présent se met à disparaître, et préférer une alerte bloquante et une analyse dans ces cas. C'est important pour que les réutilisateurs de la version consolidée gardent confiance en la fiabilité de la ressource consolidée.
- On pourra petit à petit rajouter des screens au fur et à mesure qu'on a des retours
- Techniquement, il faut pour ces processus travailler un peu différemment du mode "fire a job and forget it" qu'on a actuellement ; préférer un cron à une heure bien précise, idéalement à un moment où on ne déploie pas (nocturne), et avoir des alertes Mattermost le matin si la publication n'a pas pu se faire pour X raisons.
- On peut s'inspirer (dans l'esprit) d'outils comme https://cronitor.io qui vont donner une alerte si un job qui est sensé tourner à une heure précise ne s'est pas terminé ou dans les temps, ou bien. Ca peut se faire avec une "marque" dans la base de données, et un contre-test. Exemple tout bête: un endpoint HTTP donne le temps écoulé depuis la dernière consolidation réussie sur tel sujet, et on ajoute le tout dans notre health-check HTTP, de façon à retourner une erreur 500 si le délai prévu est dépassé. Ca permet d'éviter un N-ième SaaS à ajouter, et on garde l'intérêt d'un moniteur externe en terme de check.
- Le tout gagnera à être consolidé dans un rapport matinal directement envoyé dans le Mattermost
- La question de l'interaction avec Data Gouv sera importante ; il faut pouvoir dans notre modèle actuel créer des ressources, ou les mettre à jour. Peut-être qu'il sera préférable de la créer une fois à la main, puis d'utiliser son id via un fichier de configuration afin de faciliter la MAJ etc.

C'est tout pour le moment, @etalab/transport-tech n'hésitez pas à ajouter des remarques pour notre réflexion !

**Comment by AntoineAugusti** [comment]
On a fait évoluer la consolidation des ZFE au fur et à mesure, en particulier par l'utilisation de la multi-validation + historisation pour utiliser la dernière version valide d'une ressource. On a un processus manuel pour le moment qui permet de fortes garanties aussi.

Le niveau de fiabilité pour le moment est acceptable et on n'a pas eu d'autres consolidations à assurer depuis.
