### ISSUE TITLE
Ajout de filtres back-office pour identifier les GTFS à améliorer (enrichissement commercial)

### ISSUE THREAD

**Issue by ChristinaLaumond** [etalab/transport-site#2312]
Hello, 

Comme discuté en point d'équipe, pourriez vous ajouter les filtres suivants pour retrouver les jdd facilement : 
- GTFS sans shapes.txt
- GTFS sans couleurs route_color et route_text_color  (au niveau du fichier routes.txt)
- GTFS sans route_short_name (au niveau du fichier routes.txt)
- GTFS sans route_long_name (au niveau du fichier routes.txt)

Merci beaucoup !

Christina

**Comment by thbar** [comment]
Note pour @etalab/transport-tech ; dans certains cas je pense que fournir une analyse ad-hoc hors backoffice nous apportera de la flexibilité (comme l'a fait @AntoineAugusti l'autre jour sur les GTFS-RT sans status updates ou similaire).

Ca permet d'utiliser des outils pratiques et variés (type Python/Ruby, ou encore LiveBook), sans chercher à déployer.

Quand ça a fait ses preuves on peut aller voir dedans.

Je m'assigne celui-là.

**Comment by fchabouis** [comment]
Une piste pourrait être de faire évoluer notre validateur pour qu'il sorte ces informations. Il y a aussi une petite subtilité, c'est est-ce qu'on veut les GTFS sans shapes, ou les GTFS qui ont des shapes manquantes pour certaines routes ? Le validateur est déjà capable de sortir l'info de la présence de shapes, mais pas de savoir si toutes les routes en ont. Il ne dit rien pour le moment sur les couleurs, etc.
Il y a aussi des warnings existants sur des noms de routes manquantes (`MissingName` : An agency, a route or a stop has its name missing.), faudrait voir si c'est le long, ou le short.

**Comment by Miryad3108** [comment]
On peut fermer l'issue avec l'onglet `Données absentes mais [possibles à modéliser en GTFS](https://doc.transport.data.gouv.fr/producteurs/operateurs-de-transport-regulier-de-personnes/mise-en-qualite-des-donnees-gtfs) :` dans les détails des ressources GTFS ? 

@fchabouis

**Comment by fchabouis** [comment]
Oui on peut je pense. Comme dit plus haut, il est plus rapide de sortir une liste de datasets à la main si c'est un besoin ponctuel. A votre disposition si besoin d'un export :)
Je pense que depuis que cette issue a été ouverte, plusieurs infos supplémentaires ont été ajoutées dans les métadonnées de notre validateur.
