### ISSUE TITLE
Ne plus utiliser de domaine en *.cleverapps.io

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#2313]
Voir #2309.

Il faut faire le tour des applications et ne plus référencer dans nos systèmes les urls en `*.cleverapps.io`, car elles ne sont pas fiables pour la production.

Voir https://www.clever-cloud.com/doc/administrate/domain-names/#using-a-cleverappsio-free-domain-with-built-in-ssl

> cleverapps.io domains are for developement only!
>
> *.cleverapps.io domains are given for development and tests purpose. They point to specific reverse proxies and have the following weaknesses:
>
> * .io TLD is not a stable one
> * since we offer the domain, the probability that people will abuse it is high. Thus, we do not garantee the same QoS on the cleverapps reverse proxies.

Je vais ajouter la liste en cours rapidement ici.

### Points à traiter

- [x] `prod-site` utilise `GTFS_VALIDATOR_URL="https://transport-validator.cleverapps.io"`
- [x] `prod-worker` utilise `GTFS_VALIDATOR_URL="https://transport-validator.cleverapps.io"`
- [x] `staging-site` utilise `GTFS_VALIDATOR_URL="https://transport-validator.cleverapps.io"`
- [x] `staging-worker` utilise `GTFS_VALIDATOR_URL="https://transport-validator.cleverapps.io"`
- [x] `staging-worker` utilise `DATAGOUVFR_REDIRECT_URI="https://prochainement-transport.cleverapps.io/login/callback"` (et ça ne sert à rien ? reste je pense)
- [ ] Ajuster updown.io pour le suivi (@thbar)
- [ ] Ajuster uptimerobot pour notre page status (@fchabouis )

**Comment by thbar** [comment]
@etalab/transport-tech point à traiter, au minimum avant le 10 juillet 2022, idéalement avant !

**Comment by AntoineAugusti** [comment]
Je viens de changer les variables d'env et de lancer un redémarrage, je vérifierai le bon fonctionnement et supprimerai les noms de domaine ensuite.

**Comment by fchabouis** [comment]
C'est fait côté UptimeRobot aussi :+1:

**Comment by AntoineAugusti** [comment]
Merci ! J'ai supprimé les noms de domaine annexes pour cette app en conséquence.
