### ISSUE TITLE
Modifications section "A venir dans les prochains mois" - Page d'accueil 

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#2315]
Peut on : 
- Ajouter une tuile "Données routières" dans section "À venir dans les prochains mois" ?
Ce picto avait été proposé pour la nouvelle identité visuelle : https://drive.google.com/file/d/1fD_3eAxEsoeAamcW3UalGGOIocyf9vw9/view?usp=sharing 
On peut le reprendre sans les couleurs ? 

- Supprimer "Travaux sur voirie" 
- Ajouter tuile "comptage des mobilités", cf : https://github.com/etalab/transport-site/issues/801

Vu avec @Benoit-MINT et @NicolasBerthelot

**Comment by AntoineAugusti** [comment]
Que penses-tu de ce rendu ? (en anglais)

<img width="1274" alt="Screenshot 2022-04-15 at 17 03 30" src="https://user-images.githubusercontent.com/295709/163587006-6f67aa8a-480d-4b40-86f9-e0dea528ddcb.png">

Je suis pas un pro des images, on pourra adapter. Dis-moi si tu trouves un SVG convaincant en ligne.

On a déjà une section ["Réseaux routiers"](https://transport.data.gouv.fr/datasets?type=road-network). Doit-elle être séparée ? Fusionnée ?

**Comment by Miryad3108** [comment]
les pictos me vont parfaitement 
Pour la section "réseaux routiers", je pense qu'on pourrait la fusionner avec les données routières. Vous en pensez quoi @NicolasBerthelot et @Benoit-MINT ?

**Comment by NicolasBerthelot** [comment]
ouais je partage ton avis, on peut renommer "réseaux routiers" en "données routières" mais du coup c'est pas dans prochainement

**Comment by AntoineAugusti** [comment]
Si on choisit de fusionner que doit-on faire ?

- On utilise la catégorie existante que l'on renomme / que l'on garde ainsi ?
- On fait une "fausse tuile" dans données à venir et on changera des choses quand on aura d'autres publications ?

**Comment by Miryad3108** [comment]
Les données de Bison Futé sont bien en temps-réel ? 
Si c'est le cas on pourrait : 
- renommer la tuile "réseaux routiers" en "données routières" comme proposé par @NicolasBerthelot 
- ajouter une "fausse tuile" : "données routières temps-réel (ou dynamiques)" 

ça vous va ?

**Comment by NicolasBerthelot** [comment]
franchement pas sûr qu'on ait besoin de s'embêter avec la fausse tuile, on va très bientôt (cette semaine je pense) référencer de premières données dynamiques.

**Comment by AntoineAugusti** [comment]
@etalab/transport-bizdev Vous pouvez regarder la PR https://github.com/etalab/transport-site/pull/2327 avec les modifications, voire l'approuver :)
