### ISSUE TITLE
Différenciation des services du GTFS-RT au niveau des cartes stats

### ISSUE THREAD

**Issue by ChristinaLaumond** [etalab/transport-site#2316]
Hello, 

Une petite proposition d'évolution des cartes statistiques du PAN. En effet, comme discuté, les cartes ne distinguent pas aujourd'hui les différents services du GTFS-RT : vehicule position, trip update et service alert. 

On pourrait par exemple ajouter sur la carte format des TR, sous le "70 jdd en GTSF-RT -> x contenant les prochains passages, y contenant la position des véhicules, z contenant des infos trafic". Au niveau de la légende de la carte c'est peut-être plus compliqué à gérer vu que certains flux mixent le tout ? Après c'est une info assez importante pour un réutilisateur qui voudra potentiellement utiliser l'un ou l'autre de ses services ou tous. De savoir lesquels sont dispos facilement sur une carte pourrait l'aider. 

Discussion ouverte si vous avez des idées d'affichage :) Ou sinon autre possibilité : faire 3 cartes distinctes ? 

Merci 

<img width="796" alt="image" src="https://user-images.githubusercontent.com/101095139/162908693-8e8d5c9a-2fff-4ef7-aea8-b0ed003b5833.png">

**Comment by AntoineAugusti** [comment]
J'ai fait une partie dans la PR liée, afficher le nombre de flux diffusant chaque type d'information.

Je n'ai pas modifié les légendes ou le contenu des cartes car ceci demandait plus de travail et me paraissait être moins crucial. À noter que la page de chaque JDD indique clairement le type de données diffusées dans chaque flux et que cette information est bien diffusée dans l'API, l'information est donc en partie accessible en l'état.

On pourra travailler sur les autres idées plus tard si on priorise ça !
