### ISSUE TITLE
Ajout d'un champ "zone" dans la BNZFE

### ISSUE THREAD

**Issue by NicolasBerthelot** [etalab/transport-site#2333]
Un réutilisateur souhaiterait qu'on ajoute un champ dans la base nationale : un identifiant (ou le nom) pour la zone. Ainsi tous les polygones et les tronçons pourraient facilement être regroupés par ZFE. Pour le moment cette opération ne serait possible que par calcul géométrique. 
Quelle solution technique on pourrait avoir pour déduire la Zone de rattachement ? 
- on le demande aux producteurs ?
- on le déduit de la géométrie (sur la base d'une cartographie _théorique_ des ZFE)
- on le déduit de l'organisation qui publie les données

Il se trouve qu'un dictionnaire de zones est fait par la DGEC, ça peut être utile: 
- ZFE_01 - Grenoble-Alpes Métropole
- ZFE_02 - Métropole européenne de Lille
- ZFE_03 - Plaine Commune
- ZFE_04 - Eurométropole de Strasbourg
- ZFE_05 - Vallée de l'Arve
- ZFE_06 - Métropole Aix-Marseille-Provence
- ZFE_07 - Toulouse Métropole
- ZFE_08 - Montpellier Méditerranée Métropole
- ZFE_09 - Métropole de Lyon
- ZFE_10 - Saint Etienne Métropole
- ZFE_11 - Métropole du Grand Paris
- ZFE_12 - Métropole Toulon Provence Méditerranée
- ZFE_13 - Communauté urbaine d’Arras
- ZFE_14 - Clermont Auvergne Métropole
- ZFE_15 - Métropole du Grand Nancy
- ZFE_16 - Grand Annecy
- ZFE_17 - Valence Romans Agglo
- ZFE_18 - Communauté d’agglomération de La Rochelle
- ZFE_19 - Fort de France
- VR_A15 - Voie réservée A15 – contrôle pédagogique

**Comment by AntoineAugusti** [comment]
@etalab/transport-bizdev Concernant les identifiants de la DGEC, plusieurs remarques :

- pourraient-ils publier ceci en open data ?
- Pour Paris, est-ce que `ZFE_11` est commun à [Grand Paris](https://annuaire-entreprises.data.gouv.fr/entreprise/525046017) et [Ville de Paris](https://annuaire-entreprises.data.gouv.fr/entreprise/217500016) ? Pas certain du SIREN pour Grand Paris.
- Il manque Reims dans la liste
- Peux-tu me confirmer les entités juridiques derrière ZFE_03 et ZFE_05

**Comment by ChristinaLaumond** [comment]
hello, 

Pour le SIREN de la Métropole du Grand Paris c'est plutôt https://annuaire-entreprises.data.gouv.fr/entreprise/200054781.
La société du grand Paris c'est l'entité qui gère la partie transport (Grand Paris Express).
 
Pour Plaine Commune c'est : https://annuaire-entreprises.data.gouv.fr/entreprise/200057867

Pour Vallée de l'arve et les autres questions j'envoie le mail ;) 

Merci !

**Comment by AntoineAugusti** [comment]
Il manque des identifiants de ZFE venant la DGEC pour Rouen et Reims.

J'ai [mis ici des fichiers générés](https://gist.github.com/AntoineAugusti/b8b7647415ee7bad03919efa55b79b72) après avoir exécuté le code dans la PR. Il faut télécharger pour voir le champ `publisher`.
