### ISSUE TITLE
GBFS : visualisation des stations virtuelles / parkings

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#2334]
Certains opérateurs, dont Bird, prévoient d'indiquer des stations virtuelles pour rendre des véhicules. Ce sont généralement des espaces désignés sur la voie publique ou sur des trottoirs.

Notre visualisation des flux GBFS ne représente pas encore ceci.

Champs pertinents [dans la doc](https://github.com/NABSA/gbfs/blob/v2.3/gbfs.md#station_informationjson) dans `station_information.json`
- `is_virtual_station`
- `station_area`
- `parking_type`

**Comment by AntoineAugusti** [comment]
@etalab/transport-bizdev Si vous voyez passer un flux GBFS avec des informations sur les emplacements de stationnement virtuels (ie pas des stations), pourriez-vous noter le JDD / l'URL ici ? 🙏

**Comment by Miryad3108** [comment]
Par stationnement virtuel on parle bien de geofencing ? Si c'est le cas, on peut fermer le ticket ? 
On l'affiche pour [tous les jeux de données Bird](https://transport.data.gouv.fr/datasets?q=bird) par exemple

@AntoineAugusti

**Comment by AntoineAugusti** [comment]
@Miryad3108, non c'est bien autre chose ! Tu peux relire le premier commentaire et regarder les champs dans la doc ? Si tu as l'app Bird tu devrais voir des symboles de 🅿️ affiché dans leur app pour des stations

**Comment by AntoineAugusti** [comment]
Peu de personnes travaillent actuellement sur le GBFS, je ferme l'issue. On reviendra peut-être dessus un jour !
