### ISSUE TITLE
Distinguer catégories de ressources

### ISSUE THREAD

**Issue by ChristinaLaumond** [etalab/transport-site#2338]
Hello, 

Nous avons la possibilité de catégoriser les ressources d'un jdd de données par type dans data.gouv.fr : 
<img width="619" alt="image" src="https://user-images.githubusercontent.com/101095139/165320366-638af872-45ef-4eb3-a05b-d0b21dce603f.png">

-> l'idée serait de reprendre ces catégories et de les afficher sur le PAN également. 

Merci beaucoup :)

**Comment by AntoineAugusti** [comment]
Je renomme l'issue, la partie tri est dans https://github.com/etalab/transport-site/issues/2340
