### ISSUE TITLE
référencement url http de bison futé

### ISSUE THREAD

**Issue by ChristinaLaumond** [etalab/transport-site#2339]
Hello, 

-> pour télécharger les ressources, le PAN nous fait passer par un lien de téléchargement. exemple pour les évènements routiers on a ce lien : https://transport.data.gouv.fr/resources/79173/download

-> Or cette ressource contient normalement plusieurs fichiers xml. Est-il possible de référencer plutôt l'url stable de data.gouv https://www.data.gouv.fr/fr/datasets/r/d16c8cb6-0123-44e7-b8b1-f99fc6a59497 qui renvoie bien vers l'url initiale : http://tipi.bison-fute.gouv.fr/bison-fute-ouvert/publicationsDIR/Evenementiel-DIR/grt/RRN/ 

Cause du problème remontée par Antoine : http au lieu de https.

Merci :)

Christina

**Comment by AntoineAugusti** [comment]
Faut https://github.com/etalab/transport-site/pull/2345 en plus
