### ISSUE TITLE
Resource.validate_and_save ne nous préviendra pas en cas d'erreur d'insertion des logs de validation

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#2343]
Voir par exemple:

https://github.com/etalab/transport-site/blob/10ada526b16f1e402426eded9acf7387ab9c2de1/apps/db/lib/db/resource.ex#L195-L200

La méthode utilisée (sans "bang") peut retourner une erreur, et elle sera silencieuse.

Je crois que ça a été un compromis pour ne pas perturber le traitement principal.

Il serait toutefois préférable de lancer une `Task` asynchrone non linkée au processus principal pour ces inserts de logs, dans laquelle on utilisera un "bang", pour être notifiés dans Sentry, ça sera plus robuste.

Sauf si ces logs ne servent plus dans quelques semaines ou mois (à mettre au regard des discussions sur l'amélioration des validations).

**Comment by AntoineAugusti** [comment]
Je ferme, cette méthode va être supprimée avec la multi-validation.
