### ISSUE TITLE
Ajouter le schéma à la ResourceHistory

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#2344]
Avec le temps qui passe, on va avoir des sauvegardes historiques qui dépendent d'une certaine version d'un schéma, puis à un moment la resource évoluera de version.

Cela pose problème, car comme signalé par @AntoineAugusti ici, il faut faire le lien avec la Resource actuellement pour avoir le schéma:

https://github.com/etalab/transport-site/pull/2329#discussion_r855098702

Le souci est que si des réutilisateurs (ou nous) font appel à l'historique, on n'aura pas d'information fiable sur la version du schéma (voire, sur le schéma lui-même si il change en cours de route, ce qui est moins immédiatement probable).

**Comment by AntoineAugusti** [comment]
PR ouverte, sans backfill pour le moment. Peut-être un jour ? Pourrait être fait avec une migration en SQL (ou sans 😬).
