### ISSUE TITLE
Evaluer l'utilité de l'intégration du validateur NeTEx de Data4PT

### ISSUE THREAD

**Issue by fchabouis** [etalab/transport-site#2346]
L'outil est disponible en ligne à cette adresse pour jouer avec : https://greenlight.atomite.io/
Le repo Github est [ici](https://github.com/ITxPT/DATA4PTTools).

**Comment by thbar** [comment]
Je suggère les étapes suivantes:
- Identifier les 3 plus gros Netex qui sont chez nous (ou ailleurs, ex: IdFM ?)
- Faire tourner en local en mesurant en particulier l'usage mémoire et CPU
- Faire un rapport d'usage avec tout ça (quel retours ? quelle consommation ?)

Ca permettra de nous faire une idée sur l'utilité en pratique, et sur la facilité à déployer ou pas.

**Comment by thbar** [comment]
Pas dans la roadmap pour le moment, je fais le ménage et on reviendra dessus.
