### ISSUE TITLE
Validateur GTFS hébergé qui redémarre régulièrement

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#2374]
Je pense qu'il sera bon d'ajouter une forme de suivi, métrique ou autre, qui permette de savoir quel était le GTFS validé au moment d'un crash donné. Je crée le ticket pour qu'on garde l'idée.

![CleanShot 2022-05-10 at 10 35 04@2x](https://user-images.githubusercontent.com/10141/167585871-a6b58531-8a2a-432b-8602-b762223b8956.png)

**Comment by AntoineAugusti** [comment]
C'est pas mal arrivé à un moment cet été aussi, on fait quelque chose ou on laisse ?

**Comment by AntoineAugusti** [comment]
Survient beaucoup moins et on a eu quelques échanges avec Clever. On peut augmenter la taille mémoire ou introduire une taille max de fichier en entrée. cc @fchabouis
