### ISSUE TITLE
CSV non téléchargeable pour Bison Futé

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#2381]
Sur https://transport.data.gouv.fr/datasets/etat-de-circulation-en-temps-reel-sur-le-reseau-national-routier-non-concede/#dataset-resources

Lié au fait que la ressource est en `http` et qu'on force l'utilisation de liens permanents data.gouv.fr pour Bison Futé.

**Comment by AntoineAugusti** [comment]
Lié à https://github.com/etalab/transport-site/pull/2341 https://github.com/etalab/transport-site/issues/1709

**Comment by ChristinaLaumond** [comment]
hello, mail envoyé à Bison futé
