### ISSUE TITLE
Voir sur Sentry si nous avons encore des requêtes incorrectes de fichiers statiques

### ISSUE THREAD

**Issue by fchabouis** [etalab/transport-site#2385]
Nous avons des issues sur [Sentry](https://sentry.io/organizations/transport-data-gouv-fr/issues/3192109967/?environment=prod&project=6197733&query=is%3Aunresolved) liées à des requêtes d'éléments statiques sur notre site "incorrects".

Sauf que malheureusement, l'url qui génère cette exception sur Sentry n'est pas enregistrée. J'aimerais bien savoir si ce sont des requêtes externes invalides, ou bien si quelque part nous avons un fichier statique avec un nom étrange, par exemple qui contient des slashs.

Une requête sur https://transport.data.gouv.fr/images/odd%2Fparam%2Fwith%2Fslashes.jpg rajoute bien une telle erreur sur Sentry, mais nous ne connaissons pas l'url demandée. Je vais aller me renseigner et poser la question.

**Comment by fchabouis** [comment]
J'ai posé la question ici : https://github.com/elixir-plug/plug/issues/1097

**Comment by fchabouis** [comment]
J'ai fait une PR sur Plug ici pour ajouter l'information : https://github.com/elixir-plug/plug/pull/1098

**Comment by thbar** [comment]
Je garde ouvert: plug n'a pas pas été releasé avec les fixs pour l'instant (https://github.com/elixir-plug/plug/compare/v1.13.6...main)

**Comment by AntoineAugusti** [comment]
Fait à l'occasion de https://github.com/etalab/transport-site/pull/2833, plug est maintenant en 1.14 qui contient cette PR 😄

**Comment by fchabouis** [comment]
han, ça c'est du long terme ! Merci pour la mise à jour de Plug.
 Je vais garder l'issue ouverte, parce que je voudrais du coup ENFIN aller voir Sentry pour voir si l'erreur arrive encore et pouvoir comprendre d'où elle vient !

**Comment by fchabouis** [comment]
Nous avons finalement la réponse : des urls avec des `..` d'un indiscret pour essayer d'attraper des infos sur le serveur

![image](https://user-images.githubusercontent.com/15341118/210731529-fa0aee55-008b-454a-aa03-81f90c91b2c4.png)
