### ISSUE TITLE
Multi-validation

### ISSUE THREAD

**Issue by fchabouis** [etalab/transport-site#2390]
Sur la suggestion de @AntoineAugusti je vais mettre en commentaire dans le code une ref à cette issue lorsque je vois des choses à faire plus tard dans le cadre de la migration vers la multi validation.

A faire :

- [ ] créer une table de logs pour la multi-validation
- [ ] permettre d'attraper facilement la version de transport-tools pour remplir l'info lorsqu'on a pas accès directement à la version d'un validateur depuis son output
- [ ] Ménage une fois la validation v1 débranchée : il n'y aura plus de severity "Irrelevant", qui sera remplacée partout par "NoError"
- [ ] Rapatrier le validateur Table Schema et différencier erreur HTTP ou erreur de lecture
- [x] Supprimer anciens fichiers GTFS RT du Cellar https://github.com/etalab/transport-site/pull/2529

**Comment by fchabouis** [comment]
Note : j'ai passé la validation des resources history sur une queue Oban à part pour ne pas surcharger notre validateur GTFS qui tirait la langue. Voir https://github.com/etalab/transport-site/pull/2394

**Comment by thbar** [comment]
@etalab/transport-tech j'ai l'impression qu'on a beaucoup avancé là dessus, il reste quelque chose ?

**Comment by fchabouis** [comment]
Il reste à supprimer resource.features et resource.validation

**Comment by AntoineAugusti** [comment]
@fchabouis Tu penses que l'on peut considérer que c'est "terminé" et fermer cette issue ?

**Comment by thbar** [comment]
Je me demande si on peut clôturer ; je garde ouvert il faudrait reprendre les notes ci-dessus de Francis, il y a sûrement des petites choses à supprimer !

**Comment by AntoineAugusti** [comment]
On peut, on peut. Le refactor/nettoyage, c'est tout le temps.

**Comment by thbar** [comment]
Il faudra juste ne pas perdre cette info:

> Il reste à supprimer resource.features, resource.validation, resource.start_date et resource.end_date.

Le premier est déjà traité, les autres à voir.

**Comment by AntoineAugusti** [comment]
C'est fait
