### ISSUE TITLE
Réflexions sur les changements d'url des ressources : quelle information fournir aux réutilisateurs

### ISSUE THREAD

**Issue by ChristinaLaumond** [etalab/transport-site#2395]
Hello, 

Suite à notre discussion avec Bing Maps, j'ouvre un ticket pour voir ensemble comment on pourrait prévenir / notifier les réutilisateurs  d'un changement d'url de leur ressource. 
Faudrait-il mettre en place une sorte d'abonnements / favoris à des ressources  afin de pouvoir cibler les envois ? Faut-il envisager une solution plus universelle avec une page dédiée récapitulant ces changements (il faut que le réutilisateur retrouve facilement les jdd qui l'intéressent, il faut donc prêter attention à ce qui sera mis ici) ? 

Ticket ouvert, toutes les idées / suggestions sont les bienvenues ;)

**Comment by AntoineAugusti** [comment]
> prévenir / notifier les réutilisateurs d'un changement d'url de leur ressource

On a actuellement pas connaissance de ce que fait chaque réutilisateur en terme d'utilisation de ressources.

À noter que la possibilité actuelle serait d'utiliser l'API du PAN pour mettre en place ce système ou que les calculateurs d'itinéraires utilisent leurs outils pour effectuer cette veille. J'imagine qu'ils ont des systèmes plus ou moins automatisés pour vérifier si des URLs changent/ne répondent plus/le jeu de données associé a expiré.

**Comment by AntoineAugusti** [comment]
J'ai un peu de mal à imaginer ce qui pourrait être pertinent pour nos réutilisateurs sans connaître plus leurs fonctionnements et les logiciels qu'ils ont.

Mon avis est qu'ils ont plusieurs sources de données, dans le cas d'une présence dans plusieurs pays/continents et qu'ils sont "normalement" déjà équipés pour cette problématique et on les capacités d'adaptation nécessaires en terme de produit/ingénieurs pour ce genre de besoins. Ce qui me parait être moins le cas pour les AOMs ou transporteurs (selon la taille).

**Comment by Miryad3108** [comment]
Je serai d'avis à fermer le ticket en attendant d'avoir un retour d'autres réutilisateurs qui remontent ce besoin et creuser.
