### ISSUE TITLE
Utiliser les versions hashées des assets

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#2402]
Attention, les références directes à `/js/app.js` (ou similaire, idem sur du css) se traduisent en production par des liens sans le hash à la fin:

<img width="495" alt="CleanShot 2022-05-19 at 09 42 23@2x" src="https://user-images.githubusercontent.com/10141/169239852-802bcc38-2117-4075-90e8-f70ccf5f2104.png">
 
Il faut préférer les liens ayant le hash, ce qui permet d'éviter un bug important : le js peut ne pas être à jour car il reste en cache.

<img width="618" alt="CleanShot 2022-05-19 at 09 42 46@2x" src="https://user-images.githubusercontent.com/10141/169240012-21b138e0-0070-4ae4-885f-051c2f92a969.png">

Il faut voir si on peut remplacer par typiquement ça:

https://github.com/etalab/transport-site/blob/9c7ae884cecf2984b66515ba15c6db6053084fb3/apps/transport/lib/transport_web/templates/page/index.html.eex#L195

J'aimerais aussi "verrouiller" le fonctionnement avec un petit test qui détecte cet usage.

**Comment by thbar** [comment]
Quelques occurrences:

```
❯ ag "src=./js/app.js"
apps/transport/lib/transport_web/live/on_demand_validation_live.html.heex
155:<script defer type="text/javascript" src="/js/app.js">

apps/transport/lib/transport_web/live/backoffice/jobs_live.html.leex
45:<script defer type="text/javascript" src="/js/app.js") %>></script>

apps/transport/lib/transport_web/live/backoffice/gbfs_live.html.leex
23:<script defer type="text/javascript" src="/js/app.js") %>></script>

apps/transport/lib/transport_web/live/backoffice/proxy_config_live.html.leex
40:<script defer type="text/javascript" src="/js/app.js") %>></script>

apps/transport/lib/transport_web/live/on_demand_validation_select_live.html.heex
45:<script defer type="text/javascript" src="/js/app.js" />

apps/transport/lib/transport_web/templates/backoffice/page/form_dataset.html.eex
160:<script src="/js/app.js"></script>
```

**Comment by AntoineAugusti** [comment]
On peut pas utiliser `static_path` dans les templates LiveView ?

**Comment by thbar** [comment]
@AntoineAugusti normalement je pense que oui, mais j'ai un minuscule doute suite à un souvenir flou. On devrait pouvoir faire ça, et au pire il y aura forcément une solution vu que c'est vital

**Comment by AntoineAugusti** [comment]
Voir ce qu'a fait @fchabouis https://github.com/etalab/transport-site/pull/2400/commits/476b2550f36b3d19f76675d3021edafe288102e5

**Comment by thbar** [comment]
J'ai regardé mais il ne vaut mieux pas toucher vu que #2551 est en cours.

**Comment by thbar** [comment]
Je crois que tout est traité dans #2626, en tout cas pour la partie "js".
