### ISSUE TITLE
Downtime sur le site

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#2409]
On a eu une coupure sur la partie front:

https://updown.io/pl8a

<img width="667" alt="CleanShot 2022-05-23 at 15 09 26@2x" src="https://user-images.githubusercontent.com/10141/169826624-a5f6c002-0663-44f3-88d1-421bb5efd43e.png">

**Comment by thbar** [comment]
Le monitoring CC a détecté le souci et relancé :

<img width="810" alt="CleanShot 2022-05-23 at 15 11 14@2x" src="https://user-images.githubusercontent.com/10141/169827021-2c396804-a4da-4ceb-bb40-d8357f3dce63.png">

J'ai vérifié le dernier commit récent, intervenu juste avant ici, Sentry s'est plaint on dirait:

<img width="926" alt="CleanShot 2022-05-23 at 15 10 46@2x" src="https://user-images.githubusercontent.com/10141/169827300-c67a740e-a507-4fde-9ece-8abf5613f3a9.png">

**Comment by thbar** [comment]
Il y a une networking issue chez Sentry (https://status.sentry.io):

<img width="934" alt="CleanShot 2022-05-23 at 15 15 23@2x" src="https://user-images.githubusercontent.com/10141/169827674-2204422f-fcbc-4ad6-93ea-4bc3856a102c.png">

Je me demande si ça pourrait avoir un lien ou un autre, ou si c'est sans rapport.

**Comment by thbar** [comment]
Je ne vois rien de particulier sur la fin des logs (pas de gros crash container mentionné etc).

Peut-être qu'on a eu une "exhaustion" en lien avec Sentry, je vais aller fouiller le code.

On garde ouvert pour le moment, à suivre.

**Comment by thbar** [comment]
Sentry semble utiliser un pool dédié de Hackney:

https://github.com/getsentry/sentry-elixir/search?q=hackney

Bref, c'est pas clair pour l'instant, mais on verra si ça revient.

**Comment by AntoineAugusti** [comment]
@thbar Demande à CleverCloud s'ils ont des infos sur les derniers logs, s'ils peuvent inclure pourquoi le monitoring décide de relancer ?

Avoir le détail de leurs probes à chaque fois parait important. J'ai tenté quelques minutes de trouver _pourquoi_ mais sans rien voir, c'est frustrant.

**Comment by thbar** [comment]
@AntoineAugusti j'ai ouvert le ticket (#10AL8MX). Je pense que la réponse sera que le serveur ne répond plus en HTTP. J'ai insisté pour essayer d'avoir.

À mon avis pour en savoir davantage il faudra qu'on ajoute de la télémétrie à l'application (promex etc), en espérant qu'elle "sorte" dans ce genre de cas...

Merci d'avoir cherché aussi !

**Comment by thbar** [comment]
Ce n'est pas revenu pour le moment. Je clôture mais on a demandé davantage d'informations à l'hébergeur au cas où.
