### ISSUE TITLE
Vérifier que les liens vers la documentation restent valides

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#2420]
On a plusieurs liens vers la documentation https://doc.transport.data.gouv.fr actuellement dans le code source, il semblerait que ces liens puissent devenir invalides dès lors que des pages sont renommées.

On pourrait imaginer :
- des redirections, donc ne pas avoir de liens vers la doc directement mais des URLs du style transport.data.gouv.fr/doc/<slug> et qu'on puisse gérer la destination
- avoir une tâche régulière pour vérifier la présence de liens morts

**Comment by AntoineAugusti** [comment]
@etalab/transport-bizdev Pouvez-vous contacter GitBook et voir s'ils ont des solutions pour ce genre de problèmes ?

**Comment by ChristinaLaumond** [comment]
j'avais pas vu leur réponse, passée dans les spams

Hey Christina,

Thank you for your message :)

If you ever change a space title, the URL will not change according to the name. If you wish to change the URL to the new page name, the old one should still work just fine.

You can confirm this by going to the visibility status of your page, and it's a public or unlisted page, you'll see the URL being used to access that page:

![image](https://user-images.githubusercontent.com/101095139/176653013-7f62859e-d1f6-4e3e-b24f-e41ce69789a9.png)

If you click “Link and domain settings”, you'll see the following:

![image](https://user-images.githubusercontent.com/101095139/176653057-3d2bfffd-2539-4f14-b9fc-f1dc07f0160f.png)


So, you should be good to go, even if you change the URL for that page at any point :)

Please don't hesitate to reach out if you have further questions.

Have a wonderful day,
Rodrigo

**Comment by thbar** [comment]
Merci @ChristinaLaumond ! Je confirme ce réglage dans mes observations réalisées dans #2577 - aujourd'hui les liens retournent 200 (OK) ou 302 (redirect).

Je vais cela dit ouvrir un ticket à part pour la gestion des liens morts de façon plus générale, car j'ai au final vu des choses avec différentes causes, qui mériteront d'être traitées.
