### ISSUE TITLE
Test de restauration de backup PG depuis Scaleway

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#2421]
Je note mes étapes pour essayer de restaurer un backup. En pratique pour l'instant je suis coincé, je verrai avec @AntoineAugusti plus tard là dessus !

1. Je me logge dans https://console.scaleway.com/
2. Je vais sur le projet "transport"
3. Je descends dans le bucket staging, où je vois affiché "11 objects", mais curieusement à l'intérieur ça me dit "bucket is empty" (j'ai été voir par curiosité plus que par besoin)
4. Je vais sur le bucket production, je vois bien les objets, j'en sélectionne un (clic checkbox) puis download, ça m'amène à un "access denied"

Je prends ces notes pour partager avec @fchabouis aussi en cas de surprise, je pense que c'est lié au schéma utilisé pour faire du "write only" a priori.

Je crée la note pour reprendre dessus, rien d'urgent à ce stade (car on a déjà des backups), je verrai avec @AntoineAugusti quand on aura le temps d'en parler, et j'essayerai de documenter la méthode de "restore" complète ici.

**Comment by AntoineAugusti** [comment]
Merci de ta vigilance, je confirme que j'ai le même problème sur la partie web et aussi en CLI avec les credentials qui ont servi à créer le bucket.

**Comment by AntoineAugusti** [comment]
J'ai ouvert [un ticket](https://console.scaleway.com/support/tickets/OQKF-3015-IPIU) pour demander des clarifications. L'[object ownership](https://aws.amazon.com/premiumsupport/knowledge-center/s3-change-object-ownership/) semble différent sur AWS.

> Objects in S3 are no longer automatically owned by the AWS account that uploads it.

**Comment by thbar** [comment]
@AntoineAugusti j'ai testé à nouveau aujourd'hui sur le bucket de prod:

- J'arrive à me logger et à télécharger le fichier
- J'ai téléchargé le fichier également sur CleverCloud et le checksum est bien le même:

```
❯ cksum postgres*
3986171307 242592069 postgresql_4a305f24-8a31-4815-b2bb-23f4711303ee-20220623031011.215572d7-15a5-4b4d-a5d1-a1182117532f.dump
3986171307 242592069 postgresql_4a305f24-8a31-4815-b2bb-23f4711303ee-20220623031011.dump
```

**Comment by thbar** [comment]
Je suis en train de faire un test de restauration en local, ça a l'air long, j'attends de confirmer ce point avant de clôturer.

**Comment by thbar** [comment]
@AntoineAugusti c'est tout bon !
