### ISSUE TITLE
Ajouter un indicateur sur la qualité des données dans la section "ressource historisée" ou dans les détails de la ressource

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#2427]
Certains réutilisateurs utilisent les données historisées et pas que le GTFS en cours. Cet indicateur leur permettrait de connaître la qualité de la ressource sans utilisé le validateur à la demande.  
Cela permettrait également d'avoir un indicateur sur la qualité des données sur un temps long. 

Deux possibilités ont été identifiés pour l'instant 
- Ajouter une colonne "qualité des données" ici : 
<img width="622" alt="image" src="https://user-images.githubusercontent.com/59559301/171219260-98ee697f-3f94-4b71-826f-9aef04169f2a.png">

- Ajouter une frise dans la section "+détails" comme celle pour la disponibilité de la ressource avec un code couleur (proposition de @fchabouis ) : vert pour "0 erreur", jaune pour des informations, orange pour des avertissement, rouge pour des erreurs, rouge foncé/marron pour des erreurs irrécupérables par exemple

**Comment by cyrilmorin** [comment]
Liée à la PR #2834

**Comment by Miryad3108** [comment]
Je ferme en attendant  que ça soit priorisé
