### ISSUE TITLE
Faire une passe validation / accessibilité

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#2429]
Voir https://rocketvalidator.com/s/62d7c233-657c-491f-af35-9c5c28fba770

Sans y mettre une énergie folle vu qu'on va redesigner l'ensemble du site à un moment, ça pourrait être une amélioration appréciable, et permettre surtout d'éviter d'ajouter de nouveaux soucis (notamment sur la home, le listing, et la page de détail d'un dataset).

PS: on dispose d'un abonnement à RocketValidator pour relancer des tests, invitation sur demande n'hésitez pas.

**Comment by thbar** [comment]
Nouveau rapport réalisé ce jour:

https://rocketvalidator.com/s/46963f96-f2c4-4a72-b7af-5f306db990ce

**Comment by hugoguignardchab** [comment]
HTML errors:
-[ ] Un élément "img" doit avoir un attribut "alt".
-[ ] Mauvaise balise de début dans "p" dans "noscript" dans "head".
-[ ] "=" dans une valeur d'attribut non citée. 
-[ ] La référence à un caractère nommé n'était pas terminée par un point-virgule.
-[ ] La balise de début "a" a été vue mais un élément du même type était déjà ouvert. 
-[ ] La balise de début "body" a été vue mais un élément du même type était déjà ouvert. 
-[ ]  Balise de fin errante "a".
-[ ] Balise de fin erronée "head". 
-[ ] Balise de fin erronée "noscript". 
-[ ] L'élément "button" ne doit pas apparaître comme descendant de l'élément "a".

**Comment by thbar** [comment]
@hugoguignardchab il te manque un petit espace après chaque tiret pour que ça fasse des checkboxes. Tu peux utiliser l'onglet "preview" pour débugger :-)

**Comment by thbar** [comment]
@hugoguignardchab si après tu réalise une ou plusieurs PR, tu pourras y faire référence dans cette liste, c'est assez pratique pour le suivi par tout le monde.

**Comment by hugoguignardchab** [comment]
Nouveau rapport : https://rocketvalidator.com/s/02d3cd4d-cd6e-4ddf-a187-a16f51b6a08f
Il reste encore quelques erreurs, la majorité a été corrigée.

**Comment by cyrilmorin** [comment]
Liée à lissue #1558

**Comment by thbar** [comment]
Je clôture pour le moment, sachant qu'il y a un dépôt de dossier qui a été fait et qui, si on est retenu, reviendra sous des hypothèses et avec des moyens différents.
