### ISSUE TITLE
Liste des NeTEx "non communautaires"

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#2431]
En lien avec :
- #2346 
- #854 (han le tout petit numéro d'issue c'est tout mignon)

Et pour ma compréhension générale, j'ai été requête la base de production pour avoir une idée de la volumétrie actuelle des ressources NeTEx. Je partage le résultat ici et ça aidera sur mon travail (#2346) en cours, et de façon générale nos travaux quand on va creuser davantage ce format.

### Répartition des ressources NeTEx par "communautaire ou non"

```sql
select is_community_resource, count(*) from resource where format = 'NeTEx' group by is_community_resource
```

| is_community_resource | count |
|-----------------------|-------|
| f                     |    64 |
| t                     |    18 |

J'ai vérifié que 100% des ressources dites "communautaires" sont (sans trop de surprise) créées par nous:

```sql
select distinct description from resource where format = 'NeTEx' and is_community_resource = true
```

| description                                                                                                                                                                                   |
|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Conversion automatique du fichier GTFS au format NeTEx (profil France)... |

### Liste actuelle

```sql
select url, concat('https://transport.data.gouv.fr/resource/', id), title, last_import from resource where format = 'NeTEx' and is_community_resource = false order by url
```

| url                                                                                                                                                                                 | concat                                        | left                           | last_import                 |
|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------|--------------------------------|-----------------------------|
| https://download.data.grandlyon.com/files/rdata/rx_rhonexpress.rxtheorique/NETEX_RX.ZIP                                                                                             | https://transport.data.gouv.fr/resource/58890 | Horaires théoriques du service | 2022-06-02 04:14:44.621244Z |
| https://download.data.grandlyon.com/files/rdata/tcl_sytral.tcltheorique/NETEX_TCL.ZIP                                                                                               | https://transport.data.gouv.fr/resource/65813 | Horaires théoriques du réseau  | 2022-06-02 04:11:51.874964Z |
| https://eu.ftp.opendatasoft.com/sncf/gtfs/transilien-netexfr.zip                                                                                                                    | https://transport.data.gouv.fr/resource/67596 | Export au format CSV           | 2022-06-02 04:05:22.521996Z |
| https://eu.ftp.opendatasoft.com/sncf/horaires/export-intercites-netex-last.zip                                                                                                      | https://transport.data.gouv.fr/resource/70386 | Export au format CSV           | 2022-06-02 04:10:03.359923Z |
| https://eu.ftp.opendatasoft.com/sncf/horaires/export-ter-netex-last.zip                                                                                                             | https://transport.data.gouv.fr/resource/70299 | Export au format CSV           | 2022-06-02 04:06:25.878285Z |
| https://eu.ftp.opendatasoft.com/sncf/horaires/export-voyages-netex-last.zip                                                                                                         | https://transport.data.gouv.fr/resource/70348 | Export au format CSV           | 2022-06-02 04:08:53.167678Z |
| https://exs.grandest2.cityway.fr/NETEX.aspx?Key=OPENDATA&OperatorCode=ARDENNES                                                                                                      | https://transport.data.gouv.fr/resource/15868 | export-netex.zip               | 2022-06-02 04:04:00.978179Z |
| https://exs.grandest2.cityway.fr/NETEX.aspx?Key=OPENDATA&OperatorCode=AUBE                                                                                                          | https://transport.data.gouv.fr/resource/24398 | export-netex.zip               | 2022-06-02 04:00:31.207134Z |
| https://exs.grandest2.cityway.fr/NETEX.aspx?Key=OPENDATA&OperatorCode=C51                                                                                                           | https://transport.data.gouv.fr/resource/15901 | export-netex.zip               | 2022-06-02 04:14:02.910462Z |
| https://exs.grandest2.cityway.fr/NETEX.aspx?Key=OPENDATA&OperatorCode=CABUS                                                                                                         | https://transport.data.gouv.fr/resource/38771 | export-netex.zip               | 2022-06-02 04:02:18.221550Z |
| https://exs.grandest2.cityway.fr/NETEX.aspx?Key=OPENDATA&OperatorCode=CAC                                                                                                           | https://transport.data.gouv.fr/resource/15893 | export-netex.zip               | 2022-06-02 04:13:52.316575Z |
| https://exs.grandest2.cityway.fr/NETEX.aspx?Key=OPENDATA&OperatorCode=CC3F                                                                                                          | https://transport.data.gouv.fr/resource/15860 | export-netex.zip               | 2022-06-02 04:04:05.572567Z |
| https://exs.grandest2.cityway.fr/NETEX.aspx?Key=OPENDATA&OperatorCode=CCSelestat                                                                                                    | https://transport.data.gouv.fr/resource/15858 | export-netex.zip               | 2022-06-02 04:14:04.467007Z |
| https://exs.grandest2.cityway.fr/NETEX.aspx?Key=OPENDATA&OperatorCode=CEC                                                                                                           | https://transport.data.gouv.fr/resource/15884 | export-netex.zip               | 2022-06-02 04:01:36.370214Z |
| https://exs.grandest2.cityway.fr/NETEX.aspx?Key=OPENDATA&OperatorCode=CG67                                                                                                          | https://transport.data.gouv.fr/resource/15891 | export-netex.zip               | 2022-06-02 04:03:42.946729Z |
| https://exs.grandest2.cityway.fr/NETEX.aspx?Key=OPENDATA&OperatorCode=CG68                                                                                                          | https://transport.data.gouv.fr/resource/15925 | export-netex.zip               | 2022-06-02 04:03:27.801989Z |
| https://exs.grandest2.cityway.fr/NETEX.aspx?Key=OPENDATA&OperatorCode=CHM                                                                                                           | https://transport.data.gouv.fr/resource/15874 | export-netex.zip               | 2022-06-02 04:14:08.746631Z |
| https://exs.grandest2.cityway.fr/NETEX.aspx?Key=OPENDATA&OperatorCode=CHT                                                                                                           | https://transport.data.gouv.fr/resource/16306 | export-netex.zip               | 2022-06-02 04:14:05.066912Z |
| https://exs.grandest2.cityway.fr/NETEX.aspx?Key=OPENDATA&OperatorCode=CITELINE                                                                                                      | https://transport.data.gouv.fr/resource/15883 | export-netex.zip               | 2022-06-02 04:14:03.663218Z |
| https://exs.grandest2.cityway.fr/NETEX.aspx?Key=OPENDATA&OperatorCode=DEOBUS                                                                                                        | https://transport.data.gouv.fr/resource/15889 | export-netex.zip               | 2022-06-02 04:11:58.911298Z |
| https://exs.grandest2.cityway.fr/NETEX.aspx?Key=OPENDATA&OperatorCode=EPY                                                                                                           | https://transport.data.gouv.fr/resource/15877 | export-netex.zip               | 2022-06-02 04:00:00.810693Z |
| https://exs.grandest2.cityway.fr/NETEX.aspx?Key=OPENDATA&OperatorCode=FORBUS                                                                                                        | https://transport.data.gouv.fr/resource/34716 | export-netex.zip               | 2022-06-02 04:04:03.398137Z |
| https://exs.grandest2.cityway.fr/NETEX.aspx?Key=OPENDATA&OperatorCode=Haguenau                                                                                                      | https://transport.data.gouv.fr/resource/15875 | export-netex.zip               | 2022-06-02 04:11:40.704068Z |
| https://exs.grandest2.cityway.fr/NETEX.aspx?Key=OPENDATA&OperatorCode=IMAGINE                                                                                                       | https://transport.data.gouv.fr/resource/15887 | export-netex.zip               | 2022-06-02 04:14:08.004965Z |
| https://exs.grandest2.cityway.fr/NETEX.aspx?Key=OPENDATA&OperatorCode=ISIBUS                                                                                                        | https://transport.data.gouv.fr/resource/15878 | export-netex.zip               | 2022-06-02 04:13:51.729136Z |
| https://exs.grandest2.cityway.fr/NETEX.aspx?Key=OPENDATA&OperatorCode=LAN                                                                                                           | https://transport.data.gouv.fr/resource/15872 | export-netex.zip               | 2022-06-02 04:04:01.511768Z |
| https://exs.grandest2.cityway.fr/NETEX.aspx?Key=OPENDATA&OperatorCode=LCA                                                                                                           | https://transport.data.gouv.fr/resource/15886 | export-netex.zip               | 2022-06-02 04:03:27.143698Z |
| https://exs.grandest2.cityway.fr/NETEX.aspx?Key=OPENDATA&OperatorCode=LEBUS                                                                                                         | https://transport.data.gouv.fr/resource/15839 | export-netex.zip               | 2022-06-02 04:10:44.277763Z |
| https://exs.grandest2.cityway.fr/NETEX.aspx?Key=OPENDATA&OperatorCode=LEFIL                                                                                                         | https://transport.data.gouv.fr/resource/15879 | export-netex.zip               | 2022-06-02 04:01:01.309383Z |
| https://exs.grandest2.cityway.fr/NETEX.aspx?Key=OPENDATA&OperatorCode=LESIT                                                                                                         | https://transport.data.gouv.fr/resource/15846 | export-netex.zip               | 2022-06-02 04:02:20.778467Z |
| https://exs.grandest2.cityway.fr/NETEX.aspx?Key=OPENDATA&OperatorCode=LESUB                                                                                                         | https://transport.data.gouv.fr/resource/15876 | export-netex.zip               | 2022-06-02 04:01:13.197301Z |
| https://exs.grandest2.cityway.fr/NETEX.aspx?Key=OPENDATA&OperatorCode=LIVO                                                                                                          | https://transport.data.gouv.fr/resource/15928 | export-netex.zip               | 2022-06-02 04:09:56.899231Z |
| https://exs.grandest2.cityway.fr/NETEX.aspx?Key=OPENDATA&OperatorCode=LUNEO                                                                                                         | https://transport.data.gouv.fr/resource/15861 | export-netex.zip               | 2022-06-02 04:04:02.086071Z |
| https://exs.grandest2.cityway.fr/NETEX.aspx?Key=OPENDATA&OperatorCode=MOVIA                                                                                                         | https://transport.data.gouv.fr/resource/15890 | export-netex.zip               | 2022-06-02 04:12:02.562248Z |
| https://exs.grandest2.cityway.fr/NETEX.aspx?Key=OPENDATA&OperatorCode=Obernai                                                                                                       | https://transport.data.gouv.fr/resource/15900 | export-netex.zip               | 2022-06-02 04:14:06.219196Z |
| https://exs.grandest2.cityway.fr/NETEX.aspx?Key=OPENDATA&OperatorCode=REI                                                                                                           | https://transport.data.gouv.fr/resource/15885 | export-netex.zip               | 2022-06-02 04:14:05.628647Z |
| https://exs.grandest2.cityway.fr/NETEX.aspx?Key=OPENDATA&OperatorCode=RITM                                                                                                          | https://transport.data.gouv.fr/resource/15865 | export-netex.zip               | 2022-06-02 04:04:02.767637Z |
| https://exs.grandest2.cityway.fr/NETEX.aspx?Key=OPENDATA&OperatorCode=SDZ                                                                                                           | https://transport.data.gouv.fr/resource/15845 | export-netex.zip               | 2022-06-02 04:13:58.986087Z |
| https://exs.grandest2.cityway.fr/NETEX.aspx?Key=OPENDATA&OperatorCode=SITRAM                                                                                                        | https://transport.data.gouv.fr/resource/15888 | export-netex.zip               | 2022-06-02 04:04:06.473940Z |
| https://exs.grandest2.cityway.fr/NETEX.aspx?Key=OPENDATA&OperatorCode=SMD                                                                                                           | https://transport.data.gouv.fr/resource/15859 | export-netex.zip               | 2022-06-02 04:00:28.255158Z |
| https://exs.grandest2.cityway.fr/NETEX.aspx?Key=OPENDATA&OperatorCode=TED                                                                                                           | https://transport.data.gouv.fr/resource/15869 | export-netex.zip               | 2022-06-02 04:13:59.663658Z |
| https://exs.grandest2.cityway.fr/NETEX.aspx?Key=OPENDATA&OperatorCode=TGL                                                                                                           | https://transport.data.gouv.fr/resource/15844 | export-netex.zip               | 2022-06-02 04:04:00.350668Z |
| https://exs.grandest2.cityway.fr/NETEX.aspx?Key=OPENDATA&OperatorCode=TIM                                                                                                           | https://transport.data.gouv.fr/resource/15892 | export-netex.zip               | 2022-06-02 04:14:09.546626Z |
| https://exs.grandest2.cityway.fr/NETEX.aspx?Key=OPENDATA&OperatorCode=TIV                                                                                                           | https://transport.data.gouv.fr/resource/15880 | export-netex.zip               | 2022-04-14 04:00:32.602678Z |
| https://exs.grandest2.cityway.fr/NETEX.aspx?Key=OPENDATA&OperatorCode=TRANSAVOLD                                                                                                    | https://transport.data.gouv.fr/resource/15882 | export-netex.zip               | 2022-06-02 04:10:04.053951Z |
| https://exs.grandest2.cityway.fr/NETEX.aspx?Key=OPENDATA&OperatorCode=TRO                                                                                                           | https://transport.data.gouv.fr/resource/15881 | export-netex.zip               | 2022-06-02 04:02:16.682773Z |
| https://exs.grandest2.cityway.fr/NETEX.aspx?Key=OPENDATA&OperatorCode=TUB                                                                                                           | https://transport.data.gouv.fr/resource/15864 | export-netex.zip               | 2022-06-02 04:14:12.499722Z |
| https://static.data.gouv.fr/resources/arrets-horaires-et-parcours-theoriques-gtfs-du-reseau-routier-regional-de-transport-1/20201218-021905/rhdf-gtfs-com-62.zip.netex.zip          | https://transport.data.gouv.fr/resource/21018 | Fichier NETEX commercial du Pa | 2022-06-02 04:12:17.217793Z |
| https://static.data.gouv.fr/resources/arrets-horaires-et-parcours-theoriques-gtfs-du-reseau-routier-regional-de-transport-1/20211019-031151/rhdf-gtfs-com-62.zip.netex.zip          | https://transport.data.gouv.fr/resource/61957 | Fichier NETEX commercial du Pa | 2022-06-02 04:12:17.259320Z |
| https://static.data.gouv.fr/resources/arrets-horaires-et-parcours-theoriques-gtfs-du-reseau-routier-regional-de-transport-12/20201218-021727/rhdf-gtfs-com-80.zip.netex.zip         | https://transport.data.gouv.fr/resource/21027 | Fichier NETEX commercial de la | 2022-06-02 04:06:26.703427Z |
| https://static.data.gouv.fr/resources/arrets-horaires-et-parcours-theoriques-gtfs-du-reseau-routier-regional-de-transport-31/20201218-021930/rhdf-gtfs-sco-62.zip.netex.zip         | https://transport.data.gouv.fr/resource/21040 | Fichier NETEX scolaire du Pas- | 2022-06-02 04:06:46.514066Z |
| https://static.data.gouv.fr/resources/arrets-horaires-et-parcours-theoriques-gtfs-du-reseau-routier-regional-de-transport-31/20211019-031431/rhdf-gtfs-sco-62.zip.netex.zip         | https://transport.data.gouv.fr/resource/61984 | Fichier NETEX scolaire du Pas- | 2022-06-02 04:06:46.597474Z |
| https://static.data.gouv.fr/resources/arrets-horaires-et-parcours-theoriques-gtfs-du-reseau-routier-regional-de-transport-35/20201218-021812/rhdf-gtfs-com-sco-59-p4.zip.netex.zip  | https://transport.data.gouv.fr/resource/21034 | Fichier NETEX commercial et sc | 2022-06-02 04:06:51.666448Z |
| https://static.data.gouv.fr/resources/arrets-horaires-et-parcours-theoriques-gtfs-du-reseau-routier-regional-de-transport-35/20201218-021826/rhdf-gtfs-com-sco-59-p1.zip.netex.zip  | https://transport.data.gouv.fr/resource/21036 | Fichier NETEX commercial et sc | 2022-06-02 04:06:51.498982Z |
| https://static.data.gouv.fr/resources/arrets-horaires-et-parcours-theoriques-gtfs-du-reseau-routier-regional-de-transport-35/20201218-021843/rhdf-gtfs-com-sco-59-p2.zip.netex.zip  | https://transport.data.gouv.fr/resource/21038 | Fichier NETEX commercial et sc | 2022-06-02 04:06:51.588686Z |
| https://static.data.gouv.fr/resources/arrets-horaires-et-parcours-theoriques-gtfs-du-reseau-routier-regional-de-transport-35/20211019-030355/rhdf-gtfs-com-sco-59-p1.zip.netex.zip  | https://transport.data.gouv.fr/resource/62009 | Fichier NETEX commercial et sc | 2022-06-02 04:06:51.736819Z |
| https://static.data.gouv.fr/resources/arrets-horaires-et-parcours-theoriques-gtfs-du-reseau-routier-regional-de-transport-35/20211019-030539/rhdf-gtfs-com-sco-59-p3b.zip.netex.zip | https://transport.data.gouv.fr/resource/62015 | Fichier NETEX commercial et sc | 2022-06-02 04:06:51.937031Z |
| https://static.data.gouv.fr/resources/arrets-horaires-et-parcours-theoriques-gtfs-du-reseau-routier-regional-de-transport-35/20211019-031243/rhdf-gtfs-com-sco-59-p2.zip.netex.zip  | https://transport.data.gouv.fr/resource/62013 | Fichier NETEX commercial et sc | 2022-06-02 04:06:51.803716Z |
| https://static.data.gouv.fr/resources/arrets-horaires-et-parcours-theoriques-gtfs-du-reseau-routier-regional-de-transport-35/20211019-031326/rhdf-gtfs-com-sco-59-p4.zip.netex.zip  | https://transport.data.gouv.fr/resource/62011 | Fichier NETEX commercial et sc | 2022-06-02 04:06:52.014445Z |
| https://static.data.gouv.fr/resources/arrets-horaires-et-parcours-theoriques-gtfs-du-reseau-routier-regional-de-transport-35/20211019-031456/rhdf-gtfs-com-sco-59-p3a.zip.netex.zip | https://transport.data.gouv.fr/resource/62017 | Fichier NETEX commercial et sc | 2022-06-02 04:06:51.866301Z |
| https://static.data.gouv.fr/resources/arrets-horaires-et-parcours-theoriques-gtfs-du-reseau-routier-regional-de-transport-5/20201218-021738/rhdf-gtfs-com-02.zip.netex.zip          | https://transport.data.gouv.fr/resource/21022 | Fichier NETEX commercial de l’ | 2022-06-02 04:12:17.861551Z |
| https://static.data.gouv.fr/resources/arrets-horaires-et-parcours-theoriques-gtfs-du-reseau-routier-regional-de-transport-5/20211019-031258/rhdf-gtfs-com-02.zip.netex.zip          | https://transport.data.gouv.fr/resource/62005 | Fichier NETEX commercial de l’ | 2022-06-02 04:12:17.944620Z |
| https://static.data.gouv.fr/resources/arrets-horaires-et-parcours-theoriques-gtfs-du-reseau-routier-regional-de-transport-8/20211025-030257/rhdf-gtfs-sco-80.zip.netex.zip          | https://transport.data.gouv.fr/resource/63537 | Fichier Netex commercial de la | 2022-06-02 04:00:17.497949Z |
| https://static.data.gouv.fr/resources/arrets-horaires-et-parcours-theoriques-gtfs-du-reseau-routier-regional-de-transport-scolaire-1/20201218-021752/rhdf-gtfs-sco-02.zip.netex.zip | https://transport.data.gouv.fr/resource/21029 | Fichier NETEX scolaire de l’Ai | 2022-06-02 04:00:14.312943Z |

**Comment by fchabouis** [comment]
il n'y a plus de ressource communautaires publiées par le PAN, et toutes les anciennes ont été supprimées.
Ce sont des ressources fantômes, liées à des datasets inactifs:

``` sql
select is_community_resource, count(*) from resource r left join dataset d on d.id = r.dataset_id where format = 'NeTEx' and d.is_active = true group by is_community_resource
```
|is_community_resource|count|
|-|-|
|false                |   63|

**Comment by thbar** [comment]
Je clôture pour le moment, on verra si ça a un impact à un moment.
