### ISSUE TITLE
Notifier automatiquement les administrateurs des comptes datagouv (ou espace producteur PAN) quand un jeu de données n'est plus disponible 

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#2433]
Olivier Guillon des Pays de la Loire nous a contacté car il aimerait savoir si il y aurait un moyen pour notifier automatiquement les producteurs  quand un de leur jeu de données renvoie vers une page d'erreur pour qu'ils puissent régler le problème rapidement 

Ces cas peuvent se présenter quand :
- les données ne sont plus disponibles sur le site source (quand c'est une URL qui est renseigné et non un dépôt de fichier)
- qu'un jeu de données a été supprimé de datagouv ou du PAN

(peut être d'autres cas que vous pouvez lister)

**Comment by AntoineAugusti** [comment]
On n'a pour le moment pas accès aux données personnelles des producteurs via leur compte organisation sur data.gouv.fr, ce qui rend impossible la fonctionnalité telle que décrite.

On peut laisser des commentaires sur des jeux de données potentiellement !

**Comment by Miryad3108** [comment]
J'y ai accès : on pourrait demander à datagouv d'y donner accès à l'équipe plus largement ? 
Sinon on peut laisser des commentaires, le résultat sera effectivement le même et peut être plus simple que de demander des accès à toute l'équipe.

**Comment by AntoineAugusti** [comment]
@Miryad3108 Le prérequis serait d'y avoir accès via API, pas juste sur le backoffice web. Ce serait possible ?

**Comment by Miryad3108** [comment]
@AntoineAugusti C'est à voir avec les équipes de datagouv mais je trouve que ta solution serait plus simple : d'envoyer sous forme de commentaires comme ça tous les administrateurs/éditeurs recevront une notification 
ce seront les mêmes destinataires que si on passait par les données personnelles des producteurs via leur compte organisation sur data.gouv.fr

**Comment by AntoineAugusti** [comment]
Tiens, on _pourrait_ potentiellement faire des choses maintenant qu'on a des contacts et des notifications.

Je sais pas si ça vaut le coup étant donné que c'est rare et que notre équipe est prévenue quand un JDD est supprimé ou archivé.

À noter qu'on envoie des notifications quand des ressources d'un JDD sont indisponibles pendant > 6h consécutives

**Comment by Miryad3108** [comment]
Je ferme l'issue car c'est réglé avec l'inscription aux notifications depuis l'espace producteur
