### ISSUE TITLE
Évolution des conditions particulières ODbL sur plus de jeux de données

### ISSUE THREAD

**Issue by NicolasBerthelot** [etalab/transport-site#2435]
L'atelier du 10 mai sur l'ODbL a permis de faire évoluer les cas d'application des conditions particulières de la licence ODbL sur le PAN.
Ces conditions particulières n'étaient appliquées que pour les données de transport en commun sous licence ODbL. 
Aussi un script permet d'ajouter cette mention sur tous les jeux de données de type "public-transit" comme ici : 
![image](https://user-images.githubusercontent.com/61453166/171865302-6058ab01-7191-4983-a1f7-eedd41533c80.png)

Ce même système devrait être répliqué pour l'ensemble des jeux de données référencés sur transport.data.gouv.fr. 

A une seule exception : les données extraites d'OpenStreetMap. 
A ce jour deux jeux de données sont à proscrire : https://transport.data.gouv.fr/datasets/stationnements-cyclables-issus-dopenstreetmap/ et https://transport.data.gouv.fr/datasets/amenagements-cyclables-france-metropolitaine/ 
Ces jeux de données étant directement issus d'OSM les Community Guidelines prévalent et on conservera seulement la mention de la licence ODbL sans apposer les conditions particulières.

**Comment by AntoineAugusti** [comment]
J'envisage d'utiliser la présence du tag `openstreemap` sur le jeu de données pour déterminer si c'est un export qui provient d'OSM. Ça évite l'ajout d'un champ en base et dans le backoffice.

## Analyse sur la présence de ce tag

- https://transport.data.gouv.fr/datasets/stationnements-cyclables-issus-dopenstreetmap/ ne contient pas le tag, il faudrait l'ajouter
- https://transport.data.gouv.fr/datasets/amenagements-cyclables-france-metropolitaine/ contient le tag, pas de problème
- https://transport.data.gouv.fr/datasets/cartographie-openstreetmap-des-gares-sncf-transilien-en-ile-de-france-1 est le seul autre jeu de données sur le PAN qui a le tag `openstreemap`

## Mise à jour de la page conditions

Le lien actuel renvoie vers la page https://transport.data.gouv.fr/conditions.

Je note :
- que le contenu est très sommaire
- que le contenu n'est pas traduit

Que pensez-vous de revoir le contenu de cette page en même temps afin d'intégrer les retours de l'atelier ODbL récent et d'avoir une traduction ?

On pourra remettre une couche pour exclure les productions qui viennent d'OSM au passage, comme dit @NicolasBerthelot.

> Ces jeux de données étant directement issus d'OSM les Community Guidelines prévalent et on conservera seulement la mention de la licence ODbL sans apposer les conditions particulières.

**Comment by fchabouis** [comment]
Suite à notre discussion d'équipe de ce matin, nous avons décidé de :
- supprimer la page /conditions et de rediriger les liens vers https://doc.transport.data.gouv.fr/presentation-et-mode-demploi-du-pan/conditions-dutilisation-des-donnees/licence-odbl à la place. Cette page va être mise à jour par Benoit.
- Ajouter un message au niveau des ressources communautaires des datasets ayant comme licence la licence ODbl, rappelant aux réutilisateurs leurs obligations de repartage (à nouveau lien vers la [doc](https://doc.transport.data.gouv.fr/presentation-et-mode-demploi-du-pan/conditions-dutilisation-des-donnees/licence-odbl)) ainsi qu'un lien vers une page de mode d'emploi de publication d'une ressource communautaire qui va être rédigée par @Miryad3108 prochainement.
