### ISSUE TITLE
Partager erreurs flux GBFS 2.3 Smoove à Clermont-Ferrand

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#2436]
Leur signaler que leur flux https://clermontferrand.publicbikesystem.net/customer/gbfs/v2/gbfs.json comporte au moins les erreurs suivantes :

- les liens vers les autres flux dans le gbfs.json doivent être en HTTPS. Actuellement c'est du HTTP et leur serveur ne répond pas en HTTP/ne redirige pas
- leur flux `system_regions.json` doit avoir le bon nom, actuellement il est nommé `station_regions`

Ils peuvent utiliser https://gbfs-validator.netlify.app/ pour vérifier la conformité.

https://github.com/MobilityData/gbfs-validator/issues/55#issuecomment-1146154872
https://github.com/MobilityData/gbfs-validator/issues/74#issuecomment-1146000295

**Comment by AntoineAugusti** [comment]
@Miryad3108 Me semble que tu as fait un e-mail ?

**Comment by AntoineAugusti** [comment]
@Miryad3108 Tu as des nouvelles ?

**Comment by AntoineAugusti** [comment]
@etalab/transport-bizdev Vous avez des nouvelles ? Est-ce Smoove qui est responsable de ce réseau ou c'est avec un partenaire ? Ils semblent aussi avoir un filtrage IP qui empêche de passer leur flux dans le validateur GBFS.

**Comment by Miryad3108** [comment]
Ce n'est plus Smoove leur opérateur mais Citybike. J'avais bien envoyé un premier mail en juin. Je viens de les relancer (je comptais laisser l'été passer avant de faire une relance)

**Comment by Miryad3108** [comment]
@AntoineAugusti C'est résolu et ça sera prochainement déployé chez eux. 
Mail de Citybike : 
· les liens vers les autres flux dans le gbfs.json doivent être en HTTPS. Actuellement c'est du HTTP et votre serveur ne répond pas en HTTP/ne redirige pas

        *Problème connu qui fait l’objet chez nous du ticket Jira n° CSI-187. Problème résolu par le déploiement de la version 2022.2 du backed. C.vélo est encore en version 2022.1, sa mise à jour est donc à prévoir.*

image.png



· le flux system_regions.json doit avoir le bon nom, actuellement il est nommé station_regions

        *Problème connu, ticket n° CSI-595. Résolu dans la version 2022.2 également. Mise à jour du backend à prévoir.*

image.png

**Comment by Miryad3108** [comment]
On ferme vu que le problème est remonté et en cours de résolution de leur côté @AntoineAugusti ou on attend que ça soit résolu ?
