### ISSUE TITLE
Réparer la fonction count_dataset_with_format

### ISSUE THREAD

**Issue by fchabouis** [etalab/transport-site#2441]
La fonction `count_dataset_with_format`, définie [ici](https://github.com/etalab/transport-site/blob/521ad1696c175e657b8589a9ef8ccf5029567e13/apps/transport/lib/transport/stats_handler.ex#L143) ne devrait compter que les ressources qui font partie d'un dataset actif.

Il faudrait la corriger, en faisant une jointure sql sur la table dataset et ajouter une condition `is_active = true` sur le modème de ce qui est fait [ici](https://github.com/etalab/transport-site/blob/dc1e883025d98b8adc32f9524a689dea3d57063a/apps/transport/lib/jobs/gtfs_rt_entities.ex#L18).

Le problème se manifeste sur la page [statistiques](https://transport.data.gouv.fr/stats#public-transport-real-time) dans le compte des ressources, qui compte aussi les ressources des datasets inactifs.

![image](https://user-images.githubusercontent.com/15341118/172415694-468e2bd9-ae04-4b46-b9bc-85a46fc2e8a2.png)
 
Conseils pour cette issue : aller voir la doc [Ecto](https://hexdocs.pm/ecto/Ecto.html) et plus spécifiquement [Ecto.Query](https://hexdocs.pm/ecto/Ecto.Query.html)

**Comment by thbar** [comment]
@fchabouis ça pourrait aller dans le module de "requêtage central" qu'on a évoqué l'autre jour, d'ailleurs !
