### ISSUE TITLE
Page stats : Modifier les couleurs des formats des données temps-réel pour les transports en commun

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#2447]
Sur la carte des stats pour les formats des données temps-réel pour les transports en commun, je trouve ça dommage que "Multiple" renvoie à la fois à GTFS-RT+SIRI comme pour le cas de Valenciennes qu'à "GTFS-RT + non officiellement référencé" comme pour Bordeaux 
Du coup le couple GTFS-RT+SIRI n'est pas mise en avant 

Surtout que l'objectif c'est de pousser les AOM qui ont du SIRI à publier en parallèle du GTFS-RT si ils en ont 

Proposition de @fchabouis : mettre des hachures comme pour les [AOM](https://transport.data.gouv.fr/stats#public-transport-by-aom)

**Comment by hugoguignardchab** [comment]
![gtfsrtsiri](https://user-images.githubusercontent.com/85080846/173410042-d9b80d3f-31ce-46b9-ba4b-a38537421d20.png)
@Miryad3108 
J'ai rajouté la légende GTFS RT + SIRI hachurée en vert et bleu. Cela, convient-il ?

**Comment by fchabouis** [comment]
@hugoguignardchab ça m'a l'air pas mal, tu peux faire une PR (que tu peux mettre en brouillon/draft pour le moment) ?
Merci d'avoir pris l'initiative :+1:

**Comment by hugoguignardchab** [comment]
Avec Francis on a fait des modifications sur la pr ##2474

**Comment by Miryad3108** [comment]
On garde en tête qu'il y aura aussi le couple "GTFS-RT+SIRI-Lite" comme pour BlaBlacar Bus : https://transport.data.gouv.fr/datasets/blablacar-bus-horaires-theoriques-et-temps-reel-du-reseau-europeen/
Vu que Blablacar Bus n'est pas une AOM je pense que ça n'apparaîtra pas sur le carte mais ça viendra aussi pour les réseaux opérés par Zenbus qui, eux, sont affiliés à une AOM 
@hugoguignardchab @fchabouis

**Comment by hugoguignardchab** [comment]
Modification apportée :
- Création d'une nouvelle couleur pour les zones possédant le format gtfs rt et siri hachurée vert claire et bleu
- Échange des couleurs entre siri lite et siri pour une meilleure lecture des hachures gtfs rt + siri
![image](https://user-images.githubusercontent.com/85080846/176436051-955b3418-eae1-4248-9827-e11c257bacd6.png)

- Ajout dans le pop-up d'une ligne indiquant les formats standardisé disponible.
- Changement de la description des ressources disponibles.
![image](https://user-images.githubusercontent.com/85080846/176435704-1170e41e-e086-43d5-8f10-308a78ee68c0.png)

- Ajout du comptage des ressources non officiellement référencées
![image](https://user-images.githubusercontent.com/85080846/176435802-94306da4-da6c-4cf0-a312-c9cf1b19a901.png)
