### ISSUE TITLE
Ajouter un onglet "charte graphique" dans les jeux de données (proposition de Timothée Millet de Transit)

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#2449]
La majorité des AOM ont les pastilles de leurs lignes de transport collectif : on pourrait ajouter un onglet "charte graphique" dans les jeux de données pour que les AOM puissent mettre les pastilles avec le numéro/lettre et couleur de ligne. Cela évitera aux calculateurs d'itinéraires d'aller chercher ces informations dans Wikimedia, par exemple.

Si les AOM n'ont pas ajouté la couleur des lignes, cette charte graphique permettra aux réutilisateurs de faire le parallèle avec le GTFS et le compléter plus facilement. 

Ils pourraient également ajouter les logos qu'ils utilisent pour les trams, métro, bus etc.

⚠️​ Pas de logo de l'opérateur/AOT dans cette section car les réutilisateurs n'ont pas le droit de les intégrer dans leurs services 

On pourrait élargir cela aux véhicules en libre service (vélos, autopartage  etc.)

**Comment by timMillet** [comment]
Merci @Miryad3108 pour avoir partagé cette idée. Quelques détails supplémentaires, si cela peut aider:

Raisons sous-jacentes à cette demande:
- Faciliter la compréhension des composantes d'un réseau (mode, lignes, arrêts/stations) par les usagers
- Faire en sorte que les usagers, quelque soit leur choix d'app, aient une expérience similaire et qualitative
- Mettre en valeur la signalétique et l'identité l'AOM/opérateur

L'onglet "charte graphique" pourrait aussi s'appeler "signalétique". Il pourrait contenir:
- Images vectorielles (svg) représentant les composantes du réseau (logo de mode, logo/pastille de ligne, logo/emblême des totems des arrêts/stations).
- Documents PDF avec lignes directrice de la charte graphique/signalétique (ex: quoi faire et ne pas faire?)
- Liens URL vers la section charte graphique/signalétique de l'AOM/opérateur.

Exemples:
- [CTA Trademark Guidelines for Developers](https://www.transitchicago.com/developers/branding/) (Chicago, US-IL)
- [Auckland Transport Design Manual](https://at.govt.nz/about-us/manuals-guidelines/transport-design-manual-signage/) (Auckland, NZ)

**Comment by AntoineAugusti** [comment]
Un truc peu coûteux en terme de développement que je vois ce serait de sensibiliser les producteurs à avoir des ressources de type "Documentation" pointant vers une page de leurs sites web avec ces éléments.

Le PAN distingue bien cette section et fait la différence entre ressources et documentation, [voir ce jeu de données](https://transport.data.gouv.fr/datasets/etat-de-circulation-en-temps-reel-sur-le-reseau-national-routier-non-concede/#dataset-documentation).

On aurait donc une action de sensibilisation et de la documentation comme action du côté du PAN.

@timMillet est-ce que ce serait déjà bien ? Tu as des exemples pour des agences françaises ? Je ne sais pas à quel point c'est commun d'avoir une page web avec ces éléments graphiques facilement téléchargeables.

**Comment by AntoineAugusti** [comment]
@timMillet As-tu vu mon précédent message ?

**Comment by timMillet** [comment]
Pardon du délai, je consulte rarement les notifications directement sur GibHub. N'hésite pas à me joindre sur le Slack de transport.data.gouv.fr!

- Oui, cette section conviendrait bien au besoin!
- Non, je n'ai pas d'exemples de page sur les sites des agences françaises. D'où le besoin! Pourtant, ces éléments graphiques sont bien souvent présents dans la signalétique des réseaux français, et sont par exemple repris sur Wikipedia (ex: tramway de [Paris](https://upload.wikimedia.org/wikipedia/commons/e/eb/Paris_transit_icons_-_Tram.svg), [Lille](https://upload.wikimedia.org/wikipedia/commons/7/71/Lille_Tramway_Logo_2017.svg), [Marseille](https://upload.wikimedia.org/wikipedia/commons/9/97/Symbole_AMP_Tram.svg) ; ligne [3a](https://upload.wikimedia.org/wikipedia/commons/4/49/Paris_transit_icons_-_M%C3%A9tro_3bis.svg) du métro de Paris ; [Résago](https://upload.wikimedia.org/wikipedia/commons/5/5b/Lyon_tcl_logo-resa-full.svg) des TCL).

Merci :)

**Comment by timMillet** [comment]
Pour information: je viens de voir que la métropole de Lille partage, au sein de sa [fiche](https://www.data.gouv.fr/fr/datasets/localisation-des-arrets-ilevia-bus-metro-et-tram-gtfs-pictogrammes-du-reseau-ilevia/), le fichier "LogosIlevia.pdf" qui contient les pastilles/logos de mode utilisé par Ilévia.

**Comment by AntoineAugusti** [comment]
@timMillet Merci d'avoir repéré ça ! On est en train de réfléchir à comment faire évoluer la partie web/la doc pour mettre en avant cette possibilité, merci de ta suggestion 🙏

**Comment by AntoineAugusti** [comment]
Quelques éléments de réflexion sur [notre Mattermost](https://mattermost.incubateur.net/betagouv/pl/e7afiqqhpiy7jxbaoyjhcx1wky)

**Comment by Miryad3108** [comment]
@AntoineAugusti après avoir lu tes messages dans le Mattermost, je pense que c'est effectivement une bonne idée de mettre ça dans la section "Documentation" et de toujours la faire apparaître comme celle des ressources communautaires. 
La description pourrait être "les producteurs peuvent partager dans cette section des fichiers en lien avec les ressources déposées dans le jeu de données : charte graphique, documentation etc.". (Si il n'y a que les producteurs qui ont accès à cette section.). 

On pourrait donner des préconisations dans la [documentation de transportdatagouv](https://doc.transport.data.gouv.fr/) sur des mots clés à mettre en description des fichiers pour distinguer les types de documentation (les images des fiches de présentations comme la présentation du DATEX II [ici](https://transport.data.gouv.fr/datasets/etat-de-circulation-en-temps-reel-sur-le-reseau-national-routier-non-concede/#dataset-resources) )

**Comment by AntoineAugusti** [comment]
> La description pourrait être "les producteurs peuvent partager dans cette section des fichiers en lien avec les ressources déposées dans le jeu de données : charte graphique, documentation etc.". (Si il n'y a que les producteurs qui ont accès à cette section.).

Mon plan était de mettre ça pour tout le monde.

De ce que je connais, peu de personnes sont connectées lorsqu'elles sont sur le PAN et donc c'est délicat de mettre une condition "si connecté + si producteur de ce JDD".
