### ISSUE TITLE
Amélioration de la carte de visualisation du GTFS (lignes et arrêts) 

### ISSUE THREAD

**Issue by ChristinaLaumond** [etalab/transport-site#2450]
Hello, 
Quelques suggestions pour améliorer la carte 
<img width="662" alt="image" src="https://user-images.githubusercontent.com/101095139/173318039-13a50b22-cbf8-4843-80d0-16e99470032e.png">
- pouvoir cliquer sur une ligne et qu'elle s'affiche intégralement au dessus des autres (aujourd'hui comme les lignes se superposent, on ne voit jamais l'intégralité d'une ligne)
- en parallèle, si on clique sur une ligne, indiquer les infos contenues sur cette ligne : nom court, nom long -> reprendre les champs du fichier routes.txt finalement 
- idem pour les stops en affichant le nom + l'accessibilité (oui / non / inconnu)

Petite question supplémentaire : vous pensez que c'est possible d'avoir une carte nationale des GTFS ? en 1 coup d'œil on aurait un aperçu des données de chaque AOM : shapes ou non, couleurs de lignes ou non, accessibilité des arrêt ou non et ça pourrait être un gros argument pour la mise en qualité des données ! 

Merci

**Comment by thbar** [comment]
> Petite question supplémentaire : vous pensez que c'est possible d'avoir une carte nationale des GTFS ? en 1 coup d'œil on aurait un aperçu des données de chaque AOM : shapes ou non, couleurs de lignes ou non, accessibilité des arrêt ou non et ça pourrait être un gros argument pour la mise en qualité des données !

Oui :-) C'est possible en changeant un peu de méthode, et les outils déjà mis en place sur https://transport.data.gouv.fr/explore pour afficher des données à grande échelle.

Ca a été évoqué dans le passé, on s'est posé la question des vrais bénéfices de faire ça (personnellement je pense qu'il est important pour la partie découvrabilité de la donnée).

On en reparlera!

**Comment by fchabouis** [comment]
ça doit être possible d'améliorer le comportement de la carte actuelle comme tu le décris. Je pourrai aller jeter un œil dessus.
La carte nationale demande plus de travail, mais d'accord avec vous, ça vaudrait le coup.

**Comment by ChristinaLaumond** [comment]
merci pour vos retours!
Je viens de découvrir ce jdd qui rassemble les arrêts et lignes de tous les GTFS du PAN mais vous devez le connaitre https://transport.data.gouv.fr/datasets/position-des-arrets-de-transport-et-traces-de-lignes/  
si on avait une visualisation de ce jeu ca serait nickel en fait !

**Comment by thbar** [comment]
Je suis chaud pour travailler sur une carte nationale, plutôt à partir de chaque ressource que d’un jeu national car je crains que ça soit moins à jour, si on vote ça au prochain trimestre. 

Je vois bien les challenges et comment les gérer.

— Thibaut
