### ISSUE TITLE
Impossible de référencer un jdd (prix des carburants)

### ISSUE THREAD

**Issue by ChristinaLaumond** [etalab/transport-site#2453]
Hello, 
Je souhaitais référencer le jdd suivant mais j'ai une erreur 404 qui remonte : https://www.data.gouv.fr/fr/datasets/prix-des-carburants-en-france-flux-quotidien/
Les infos à indiquer sont :  
nom : Prix des carburants et informations quotidiennes sur les points de vente 
Jeu national 
catégorie : charging station 

Merci

**Comment by AntoineAugusti** [comment]
Je vais jeter un oeil prochainement

**Comment by AntoineAugusti** [comment]
Après avoir regardé, le problème vient que les exports CSV, JSON et GeoJSON du jeu de données sont téléchargés **très lentement depuis OpenDataSoft**.

59 secondes ici pour télécharger un CSV de 70 Mo, sur une connexion fibre à 300 Mbps.
```
$ wget -O /tmp/csv https://data.economie.gouv.fr/explore/dataset/prix-carburants-fichier-quotidien-test-ods/download\?format\=csv\&timezone\=Europe/Berlin\&use_labels_for_header\=false

--2022-06-15 14:33:49--  https://data.economie.gouv.fr/explore/dataset/prix-carburants-fichier-quotidien-test-ods/download?format=csv&timezone=Europe/Berlin&use_labels_for_header=false
Resolving data.economie.gouv.fr (data.economie.gouv.fr)... 109.232.232.161, 171.33.103.241
Connecting to data.economie.gouv.fr (data.economie.gouv.fr)|109.232.232.161|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/csv]
Saving to: ‘/tmp/csv’

/tmp/csv                            [                                         <=>         ]  70.76M  1.25MB/s    in 59s     

2022-06-15 14:34:49 (1.20 MB/s) - ‘/tmp/csv’ saved [74195470]
``` 

Lors du processus d'import, il est nécessaire de calculer un hash du fichier (pour savoir s'il a changé), [fait ici](https://github.com/etalab/transport-site/blob/72f162c7014307c3e339891fe5c905582fc74da3/apps/transport/lib/transport/import_data.ex#L363).

Une autre limitation de Phoenix est qu'il y a [un timeout par défaut de 60s](https://elixirforum.com/t/request-to-phoenix-server-times-out-after-60-seconds/20851) provenant de [Plug.Cowboy](https://hexdocs.pm/plug_cowboy/Plug.Cowboy.html).

Ainsi, comme la requête HTTP prend plus de 60s à être traité (car chaque téléchargement/hash de ressource prend plus de 60s), la requête HTTP est stoppée et l'import ne finit pas. En dev on a un `ERR_EMPTY_RESPONSE` sur Chrome, en prod on a une 404 générique.

Certaines suggestions sont de changer le _idle timeout_ de Cowboy, mais ça me parait assez sale https://github.com/phoenixframework/phoenix/issues/3190#issuecomment-443022895. Je confirme qu'en passant à une valeur énorme de _idle timeout_ pour Cowboy j'arrive bien à importer le jeu de données.

À voir avec @etalab/transport-tech ce qu'on fait.

**Comment by thbar** [comment]
Quelques commentaires (attention je ne vais pas creuser ce matin, je vais aller me concentrer sur le proxy SIRI).

Attention je n'ai pas pris le temps d'aller regarder le code incriminé, peut-être que je vais dire un truc pas adapté !

Si je comprends bien, la requête faite par Christina est une requête où l'import est déclenché en synchrone pendant la requête HTTP, via le back-office, c'est bien ça ?

Si c'est le cas, je pense que le mieux serait de passer à un modèle asynchrone pour libérer le worker HTTP (par exemple: démarrer une LiveView qui fera l'import).

Augmenter le timeout HTTP global entraîne régulièrement (peu importe la techno) des effets de bords (sauf à le faire de façon sélective et je ne sais pas si c'est possible), par ailleurs on a aussi le risque que le load balancer devant aie également une limitation de ce type (même si c'est juste une supposition) et qu'on ne dispose pas de moyen de le contrôler facilement.

Par exemple, c'est plus facile (même si avec Elixir ça sera moins marqué qu'avec Ruby ou Python) de créer un DOS sur le serveur si on a un très long timeout, en épuisant ses ressources.

Un autre point est qu'il faudrait honnêtement signaler ces cas à ODS: un throttling de 1 Mo par seconde, pour l'usage de beaucoup de gens, c'est vraiment beaucoup (même si je comprends leur position).

En conclusion, si c'est bien en synchrone, je recommande le passage à l'asynchrone (typiquement via une LiveView, backée ou par un simple Process, ou par un job Oban si on préfère mais c'est pas forcément utile dans ce cas).

Si c'est pas en synchrone, je ne comprends pas le problème et j'aurai besoin d'en savoir davantage pour avoir une opinion !

**Comment by AntoineAugusti** [comment]
Oui @thbar tu as bien raison, le processus d'import est pour le moment synchrone, ce qui pose de potentiels problèmes de timeout comme dans ce cas.

C'est vrai que le passer en asynchrone serait pas mal, mais j'imagine que ça demande pas mal de taff alors que le problème ne s'est pas présenté dernièrement. **Je vais voir si on peut le contourner pour cette fois et réussir à ajouter ce jeu de données quand même.**

Je ferai bien un retour à OpenDataSoft, j'ai aussi déjà envoyé un courriel aux personnes en charge de data.economie.fr pour leur faire part du problème et j'en ai touché un mot ) Etalab.

**Comment by thbar** [comment]
@AntoineAugusti ok merci pour la confirmation ; effectivement on peut juste l'ajouter à la main via une console iex, si c'est du one-shot ça suffira !

**Comment by AntoineAugusti** [comment]
Fait depuis la console en production, ça a pris plusieurs minutes. J'ai repris le code du controlleur en changeant peu de choses et en construisant les params à la main.

```elixir
alias Datagouvfr.Client.Datasets
alias Transport.ImportData
alias DB.{Dataset, ImportDataWorker, Repo}

 params = %{
  "url" => "https://www.data.gouv.fr/fr/datasets/prix-des-carburants-en-france-flux-quotidien/",
  "custom_title" => "Prix des carburants et informations quotidiennes sur les points de vente",
  "type" => "charging-stations",
  "national_dataset" => "true"
 }

datagouv_id = Datasets.get_id_from_url(params["url"])
{:ok, dg_dataset} = ImportData.import_from_data_gouv(datagouv_id, params["type"])
params = Map.merge(params, dg_dataset)
{:ok, changeset} = Dataset.changeset(params)
{:ok, dataset} = Repo.insert_or_update(changeset)
```

**Comment by AntoineAugusti** [comment]
@fchabouis Merci du partage des perspectives pour le moyen terme ! Je clos cette issue, le jeu de données ayant été ajouté en base de données on est de retour dans un fonctionnement normal.

Je vais envoyer quelques e-mails à ODS et faire le suivi avec la DGFiP.
