### ISSUE TITLE
Utilisation des EPCI récents

### ISSUE THREAD

**Issue by ThomasG77** [etalab/transport-site#2456]
Vous utilisez les EPCI de 2019 alors qu'il y a ceux de 2022 https://github.com/etalab/transport-site/blob/master/apps/transport/lib/mix/tasks/transport/import_epci.ex#L11

**Comment by AntoineAugusti** [comment]
Merci ! Tu sais si c'est compatible, si on doit prévoir des ajustements de code ?

**Comment by thbar** [comment]
@AntoineAugusti je ne l'ai jamais fait, mais ça ressemble au code des mises à jour AOM. Je vois que le code fait de l'upsert en utilisant le code comme clé business, mais ne gère pas les éventuelles suppressions, et je ne sais pas globalement quel impact ça peut avoir.

Ca semble pas atroce mais à regarder de plus près...

On peut déjà faire un diff entre les deux versions et regarder ce que ça voudrait dire.
