### ISSUE TITLE
Bug d'affichage format d'un jeu de données

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#2458]
Il y a une étiquette vide pour le format de données dans ce cas, catégorie [charging stations](https://transport.data.gouv.fr/datasets?type=charging-stations)

![Screenshot 2022-06-16 at 10 45 17](https://user-images.githubusercontent.com/295709/174031243-ef4cd6ae-b1b4-4112-9a9a-26d44c8a9df7.png)

**Comment by AntoineAugusti** [comment]
Je pense que tu pourrais peut-être faire cette issue @hugoguignardchab ! J'ai pas du tout regardé la cause. cc @fchabouis

**Comment by hugoguignardchab** [comment]
il y a également des fichiers qui sont décrits comme zip alors que ce sont des gifs.zip
![image](https://user-images.githubusercontent.com/85080846/175313832-36337837-9c07-4415-98cf-cc0883c3aaa2.png)
![image](https://user-images.githubusercontent.com/85080846/175313980-78ac6f86-0033-421a-83ab-b1c52e1e2444.png)
