### ISSUE TITLE
Vérifier la validité des données pour aom.parent_dataset_id

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#2460]
Ce champ est rempli à la main dans la base de données pour le moment. Pour une AOM, on peut indiquer que ces données sont contenues dans un aggrégat, par exemple à l'échelle département/région.

C'est par ce mécanisme que certains jeux de données remontent, par exemple pour "[Chartres Métropole](https://transport.data.gouv.fr/datasets/aom/37)".

@etalab/transport-bizdev pourriez-vous vérifier ces données et indiquer si des changements sont requis ?

<details><summary>Voir requête SQL</summary>

```sql
select a.id aom_id, a.nom, d.custom_title, d.id dataset_id, 'https://transport.data.gouv.fr/datasets/' || d.slug url
from aom a
join dataset d on d.id = a.parent_dataset_id and d.is_active
where a.parent_dataset_id is not null
order by d.custom_title asc
```

</details>

<details><summary>Voir données</summary>

|aom_id|aom_nom|parent_dataset_custom_title|dataset_id|dataset_url|
|--- | --- | --- | --- | ---|
|1 | CC du Pays de Lunel | Agrégat de réseaux interurbains de la région Occitanie | 387 | https://transport.data.gouv.fr/datasets/fichiers-gtfs-de-la-region-occitanie|
|20 | Lorient Agglomération | Agrégat de réseaux urbains et interurbains de Bretagne | 38 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-transports-publics-en-bretagne-mobibreizh-gtfs|
|310 | Auray Quiberon Terre Atlantique | Agrégat de réseaux urbains et interurbains de Bretagne | 38 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-transports-publics-en-bretagne-mobibreizh-gtfs|
|227 | Lamballe Terre & Mer | Agrégat de réseaux urbains et interurbains de Bretagne | 38 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-transports-publics-en-bretagne-mobibreizh-gtfs|
|115 | Rennes Métropole | Agrégat de réseaux urbains et interurbains de Bretagne | 38 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-transports-publics-en-bretagne-mobibreizh-gtfs|
|3 | CC de Belle-Île-en-Mer | Agrégat de réseaux urbains et interurbains de Bretagne | 38 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-transports-publics-en-bretagne-mobibreizh-gtfs|
|142 | Golfe du Morbihan – Vannes Agglomération | Agrégat de réseaux urbains et interurbains de Bretagne | 38 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-transports-publics-en-bretagne-mobibreizh-gtfs|
|139 | Morlaix Communauté | Agrégat de réseaux urbains et interurbains de Bretagne | 38 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-transports-publics-en-bretagne-mobibreizh-gtfs|
|148 | CA de Concarneau Cornouaille | Agrégat de réseaux urbains et interurbains de Bretagne | 38 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-transports-publics-en-bretagne-mobibreizh-gtfs|
|116 | Saint-Brieuc Armor Agglomération | Agrégat de réseaux urbains et interurbains de Bretagne | 38 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-transports-publics-en-bretagne-mobibreizh-gtfs|
|250 | Guingamp Paimpol Agglomération | Agrégat de réseaux urbains et interurbains de Bretagne | 38 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-transports-publics-en-bretagne-mobibreizh-gtfs|
|218 | Landernau | Agrégat de réseaux urbains et interurbains de Bretagne | 38 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-transports-publics-en-bretagne-mobibreizh-gtfs|
|238 | Quimperlé Communauté | Agrégat de réseaux urbains et interurbains de Bretagne | 38 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-transports-publics-en-bretagne-mobibreizh-gtfs|
|108 | Saint-malo Agglomération | Agrégat de réseaux urbains et interurbains de Bretagne | 38 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-transports-publics-en-bretagne-mobibreizh-gtfs|
|47 | Brest Métropole | Agrégat de réseaux urbains et interurbains de Bretagne | 38 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-transports-publics-en-bretagne-mobibreizh-gtfs|
|219 | Pontivy Communauté | Agrégat de réseaux urbains et interurbains de Bretagne | 38 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-transports-publics-en-bretagne-mobibreizh-gtfs|
|133 | Lannion – Trégor Communauté | Agrégat de réseaux urbains et interurbains de Bretagne | 38 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-transports-publics-en-bretagne-mobibreizh-gtfs|
|175 | Douarnenez | Agrégat de réseaux urbains et interurbains de Bretagne | 38 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-transports-publics-en-bretagne-mobibreizh-gtfs|
|146 | Fougères Agglomération | Agrégat de réseaux urbains et interurbains de Bretagne | 38 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-transports-publics-en-bretagne-mobibreizh-gtfs|
|113 | Quimper Bretagne Occidentale | Agrégat de réseaux urbains et interurbains de Bretagne | 38 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-transports-publics-en-bretagne-mobibreizh-gtfs|
|63 | Arles Crau Camargue Montagnette (ACCM) | Agrégat de réseaux urbains et interurbains de la Métropole Aix-Marseille | 146 | https://transport.data.gouv.fr/datasets/reseaux-de-transports-en-commun-de-la-metropole-daix-marseille-provence-et-des-bouches-du-rhone|
|82 | Moulins Communauté | Agrégat de réseaux urbains et interurbains de la région Auvergne-Rhône-Alpes | 732 | https://transport.data.gouv.fr/datasets/agregat-oura|
|167 | Agglo le Puy-en-Velay | Agrégat de réseaux urbains et interurbains de la région Auvergne-Rhône-Alpes | 732 | https://transport.data.gouv.fr/datasets/agregat-oura|
|127 | Riom Limagne et Volcans | Agrégat de réseaux urbains et interurbains de la région Auvergne-Rhône-Alpes | 732 | https://transport.data.gouv.fr/datasets/agregat-oura|
|9 | Montluçon Communauté | Agrégat de réseaux urbains et interurbains de la région Auvergne-Rhône-Alpes | 732 | https://transport.data.gouv.fr/datasets/agregat-oura|
|164 | CA du Bassin d’Aurillac (CABA) | Agrégat de réseaux urbains et interurbains de la région Auvergne-Rhône-Alpes | 732 | https://transport.data.gouv.fr/datasets/agregat-oura|
|124 | Agglomération Thiers – Peschadoires SIVU-TUT | Agrégat de réseaux urbains et interurbains de la région Auvergne-Rhône-Alpes | 732 | https://transport.data.gouv.fr/datasets/agregat-oura|
|216 | Territoires Vendômois | Agrégat de réseaux urbains et interurbains de la région Centre-Val-de-Loire | 338 | https://transport.data.gouv.fr/datasets/arrets-itineraires-et-horaires-theoriques-des-reseaux-de-transport-des-membres-de-jvmalin|
|35 | Châteauroux Métropole | Agrégat de réseaux urbains et interurbains de la région Centre-Val-de-Loire | 338 | https://transport.data.gouv.fr/datasets/arrets-itineraires-et-horaires-theoriques-des-reseaux-de-transport-des-membres-de-jvmalin|
|138 | Agglomération Montargoise et Rives du Loing | Agrégat de réseaux urbains et interurbains de la région Centre-Val-de-Loire | 338 | https://transport.data.gouv.fr/datasets/arrets-itineraires-et-horaires-theoriques-des-reseaux-de-transport-des-membres-de-jvmalin|
|59 | CA de Blois – Agglopolys | Agrégat de réseaux urbains et interurbains de la région Centre-Val-de-Loire | 338 | https://transport.data.gouv.fr/datasets/arrets-itineraires-et-horaires-theoriques-des-reseaux-de-transport-des-membres-de-jvmalin|
|132 | CA du Pays de Dreux | Agrégat de réseaux urbains et interurbains de la région Centre-Val-de-Loire | 338 | https://transport.data.gouv.fr/datasets/arrets-itineraires-et-horaires-theoriques-des-reseaux-de-transport-des-membres-de-jvmalin|
|37 | Chartres Métropole | Agrégat de réseaux urbains et interurbains de la région Centre-Val-de-Loire | 338 | https://transport.data.gouv.fr/datasets/arrets-itineraires-et-horaires-theoriques-des-reseaux-de-transport-des-membres-de-jvmalin|
|119 | Orléans Métropole | Agrégat de réseaux urbains et interurbains de la région Centre-Val-de-Loire | 338 | https://transport.data.gouv.fr/datasets/arrets-itineraires-et-horaires-theoriques-des-reseaux-de-transport-des-membres-de-jvmalin|
|126 | Vierzon | Agrégat de réseaux urbains et interurbains de la région Centre-Val-de-Loire | 338 | https://transport.data.gouv.fr/datasets/arrets-itineraires-et-horaires-theoriques-des-reseaux-de-transport-des-membres-de-jvmalin|
|230 | CC du Pays d’Issoudun | Agrégat de réseaux urbains et interurbains de la région Centre-Val-de-Loire | 338 | https://transport.data.gouv.fr/datasets/arrets-itineraires-et-horaires-theoriques-des-reseaux-de-transport-des-membres-de-jvmalin|
|50 | CA Bourges Plus (AggloBus) | Agrégat de réseaux urbains et interurbains de la région Centre-Val-de-Loire | 338 | https://transport.data.gouv.fr/datasets/arrets-itineraires-et-horaires-theoriques-des-reseaux-de-transport-des-membres-de-jvmalin|
|215 | Nogent-le-Rotrou | Agrégat de réseaux urbains et interurbains de la région Centre-Val-de-Loire | 338 | https://transport.data.gouv.fr/datasets/arrets-itineraires-et-horaires-theoriques-des-reseaux-de-transport-des-membres-de-jvmalin|
|22 | CA de Laval | Agrégat de réseaux urbains et interurbains de la région Pays de la Loire | 579 | https://transport.data.gouv.fr/datasets/arrets-horaires-et-circuits-des-lignes-de-transports-en-commun-en-pays-de-la-loire-gtfs-destineo-reseaux-aom-aleop|
|38 | CA du Choletais | Agrégat de réseaux urbains et interurbains de la région Pays de la Loire | 579 | https://transport.data.gouv.fr/datasets/arrets-horaires-et-circuits-des-lignes-de-transports-en-commun-en-pays-de-la-loire-gtfs-destineo-reseaux-aom-aleop|
|105 | Saumur – Val de Loire | Agrégat de réseaux urbains et interurbains de la région Pays de la Loire | 579 | https://transport.data.gouv.fr/datasets/arrets-horaires-et-circuits-des-lignes-de-transports-en-commun-en-pays-de-la-loire-gtfs-destineo-reseaux-aom-aleop|
|65 | Angers Loire Métropole | Agrégat de réseaux urbains et interurbains de la région Pays de la Loire | 579 | https://transport.data.gouv.fr/datasets/arrets-horaires-et-circuits-des-lignes-de-transports-en-commun-en-pays-de-la-loire-gtfs-destineo-reseaux-aom-aleop|
|122 | Les Sables d’Olonne Agglomération | Agrégat de réseaux urbains et interurbains de la région Pays de la Loire | 579 | https://transport.data.gouv.fr/datasets/arrets-horaires-et-circuits-des-lignes-de-transports-en-commun-en-pays-de-la-loire-gtfs-destineo-reseaux-aom-aleop|
|15 | Le Mans Métropole | Agrégat de réseaux urbains et interurbains de la région Pays de la Loire | 579 | https://transport.data.gouv.fr/datasets/arrets-horaires-et-circuits-des-lignes-de-transports-en-commun-en-pays-de-la-loire-gtfs-destineo-reseaux-aom-aleop|
|110 | La Roche-sur-Yon Agglomération | Agrégat de réseaux urbains et interurbains de la région Pays de la Loire | 579 | https://transport.data.gouv.fr/datasets/arrets-horaires-et-circuits-des-lignes-de-transports-en-commun-en-pays-de-la-loire-gtfs-destineo-reseaux-aom-aleop|
|5 | Nantes Métropole | Agrégat de réseaux urbains et interurbains de la région Pays de la Loire | 579 | https://transport.data.gouv.fr/datasets/arrets-horaires-et-circuits-des-lignes-de-transports-en-commun-en-pays-de-la-loire-gtfs-destineo-reseaux-aom-aleop|
|137 | Sablé-sur-Sarthe | Agrégat de réseaux urbains et interurbains de la région Pays de la Loire | 579 | https://transport.data.gouv.fr/datasets/arrets-horaires-et-circuits-des-lignes-de-transports-en-commun-en-pays-de-la-loire-gtfs-destineo-reseaux-aom-aleop|
|203 | L’Île d’Yeu | Agrégat de réseaux urbains et interurbains de la région Pays de la Loire | 579 | https://transport.data.gouv.fr/datasets/arrets-horaires-et-circuits-des-lignes-de-transports-en-commun-en-pays-de-la-loire-gtfs-destineo-reseaux-aom-aleop|
|224 | SMTCR de la presqu’île de Guérande Atlantique | Agrégat de réseaux urbains et interurbains de la région Pays de la Loire | 579 | https://transport.data.gouv.fr/datasets/arrets-horaires-et-circuits-des-lignes-de-transports-en-commun-en-pays-de-la-loire-gtfs-destineo-reseaux-aom-aleop|
|106 | CARENE Saint-Nazaire Agglomération | Agrégat de réseaux urbains et interurbains de la région Pays de la Loire | 579 | https://transport.data.gouv.fr/datasets/arrets-horaires-et-circuits-des-lignes-de-transports-en-commun-en-pays-de-la-loire-gtfs-destineo-reseaux-aom-aleop|
|200 | Chantilly | Agrégat de réseaux urbains et interurbains de l'Oise (60) | 506 | https://transport.data.gouv.fr/datasets/arrets-horaires-et-parcours-theoriques-gtfs-des-differents-reseaux-de-transport-membres-du-synd3-1|
|56 | CA du Beauvaisis | Agrégat de réseaux urbains et interurbains de l'Oise (60) | 506 | https://transport.data.gouv.fr/datasets/arrets-horaires-et-parcours-theoriques-gtfs-des-differents-reseaux-de-transport-membres-du-synd3-1|
|260 | Noyon | Agrégat de réseaux urbains et interurbains de l'Oise (60) | 506 | https://transport.data.gouv.fr/datasets/arrets-horaires-et-parcours-theoriques-gtfs-des-differents-reseaux-de-transport-membres-du-synd3-1|
|290 | SMTC de la métropole clermontoise | Agrégat de réseaux urbains et interurbains de l'Oise (60) | 506 | https://transport.data.gouv.fr/datasets/arrets-horaires-et-parcours-theoriques-gtfs-des-differents-reseaux-de-transport-membres-du-synd3-1|
|186 | CA de Compiègne et de la Basse Automne | Agrégat de réseaux urbains et interurbains de l'Oise (60) | 506 | https://transport.data.gouv.fr/datasets/arrets-horaires-et-parcours-theoriques-gtfs-des-differents-reseaux-de-transport-membres-du-synd3-1|
|198 | Crépy-en-Valois | Agrégat de réseaux urbains et interurbains de l'Oise (60) | 506 | https://transport.data.gouv.fr/datasets/arrets-horaires-et-parcours-theoriques-gtfs-des-differents-reseaux-de-transport-membres-du-synd3-1|
|32 | Creil Sud Oise | Agrégat de réseaux urbains et interurbains de l'Oise (60) | 506 | https://transport.data.gouv.fr/datasets/arrets-horaires-et-parcours-theoriques-gtfs-des-differents-reseaux-de-transport-membres-du-synd3-1|
|209 | Senlis | Agrégat de réseaux urbains et interurbains de l'Oise (60) | 506 | https://transport.data.gouv.fr/datasets/arrets-horaires-et-parcours-theoriques-gtfs-des-differents-reseaux-de-transport-membres-du-synd3-1|
|196 | Pont Sainte-Maxence | Agrégat de réseaux urbains et interurbains de l'Oise (60) | 506 | https://transport.data.gouv.fr/datasets/arrets-horaires-et-parcours-theoriques-gtfs-des-differents-reseaux-de-transport-membres-du-synd3-1|
|211 | CC des Sablons | Agrégat de réseaux urbains et interurbains de l'Oise (60) | 506 | https://transport.data.gouv.fr/datasets/arrets-horaires-et-parcours-theoriques-gtfs-des-differents-reseaux-de-transport-membres-du-synd3-1|
|243 | Pont-Audemer | Agrégat de réseaux urbains et interurbains de Normandie | 176 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-des-reseaux-de-transport-public-normands|
|208 | Bayeux et Communes Associées | Agrégat de réseaux urbains et interurbains de Normandie | 176 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-des-reseaux-de-transport-public-normands|
|245 | Bernay | Agrégat de réseaux urbains et interurbains de Normandie | 176 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-des-reseaux-de-transport-public-normands|
|262 | Yvetot | Agrégat de réseaux urbains et interurbains de Normandie | 176 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-des-reseaux-de-transport-public-normands|
|36 | CA du Cotentin | Agrégat de réseaux urbains et interurbains de Normandie | 176 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-des-reseaux-de-transport-public-normands|
|299 | Bagnoles de l’Orne | Agrégat de réseaux urbains et interurbains de Normandie | 176 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-des-reseaux-de-transport-public-normands|
|305 | Granville | Agrégat de réseaux urbains et interurbains de Normandie | 176 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-des-reseaux-de-transport-public-normands|
|44 | Évreux Portes de Normandie | Agrégat de réseaux urbains et interurbains de Normandie | 176 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-des-reseaux-de-transport-public-normands|
|197 | Flers Agglo | Agrégat de réseaux urbains et interurbains de Normandie | 176 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-des-reseaux-de-transport-public-normands|
|217 | Seine Normandie Agglomération | Agrégat de réseaux urbains et interurbains de Normandie | 176 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-des-reseaux-de-transport-public-normands|
|135 | CA Lisieux Normandie | Agrégat de réseaux urbains et interurbains de Normandie | 176 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-des-reseaux-de-transport-public-normands|
|130 | Honfleur | Agrégat de réseaux urbains et interurbains de Normandie | 176 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-des-reseaux-de-transport-public-normands|
|21 | Le Havre Seine Métropole (CODAH) | Agrégat de réseaux urbains et interurbains de Normandie | 176 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-des-reseaux-de-transport-public-normands|
|134 | Dieppe Maritime Agglo | Agrégat de réseaux urbains et interurbains de Normandie | 176 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-des-reseaux-de-transport-public-normands|
|131 | Agglo Fécamp Caux Littoral | Agrégat de réseaux urbains et interurbains de Normandie | 176 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-des-reseaux-de-transport-public-normands|
|311 | CU Alençon | Agrégat de réseaux urbains et interurbains de Normandie | 176 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-des-reseaux-de-transport-public-normands|
|179 | Argentan | Agrégat de réseaux urbains et interurbains de Normandie | 176 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-des-reseaux-de-transport-public-normands|
|206 | Vire Normandie | Agrégat de réseaux urbains et interurbains de Normandie | 176 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-des-reseaux-de-transport-public-normands|
|184 | Seine-Eure agglo | Agrégat de réseaux urbains et interurbains de Normandie | 176 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-des-reseaux-de-transport-public-normands|
|128 | Saint-Lô Agglo | Agrégat de réseaux urbains et interurbains de Normandie | 176 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-des-reseaux-de-transport-public-normands|
|46 | CU Caen la Mer | Agrégat de réseaux urbains et interurbains de Normandie | 176 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-des-reseaux-de-transport-public-normands|
|111 | Métropole Rouen Normandie | Agrégat de réseaux urbains et interurbains de Normandie | 176 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-des-reseaux-de-transport-public-normands|
|335 | Mont-Saint-Michel Normandie | Agrégat de réseaux urbains et interurbains de Normandie | 176 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-des-reseaux-de-transport-public-normands|
|189 | Caux Seine Agglo | Agrégat de réseaux urbains et interurbains de Normandie | 176 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-des-reseaux-de-transport-public-normands|
</details>

**Comment by AntoineAugusti** [comment]
À noter que si vous voyez des choses à ajouter vous pouvez l'indiquer aussi !

**Comment by Miryad3108** [comment]
@AntoineAugusti j'ai vérifié et tous les territoires associés à ces jeux de données m'ont l'air corrects
@ChristinaLaumond n'hésites pas à faire un double check

**Comment by AntoineAugusti** [comment]
Je vous laisse revenir vers nous si nécessaire.
