### ISSUE TITLE
Erreur 500 sur TransportWeb.API.PlacesController.autocomplete

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#2477]
Quand on passe aucun params on a une erreur 500.

[Sur Sentry](https://sentry.io/organizations/transport-data-gouv-fr/issues/3020692350/?environment=prod&project=6197733&query=is%3Aunresolved)

**Comment by thbar** [comment]
J'ai commencé à traiter dans #2547, au final c'est causé par l'API, l'autocomplete semble fonctionne comme prévu (mais le code est confus).

Je vais mettre au propre.

**Comment by thbar** [comment]
Point un peu plus complexe qui mérite discussion, j'en parlerai au point d'équipe.

**Comment by thbar** [comment]
Voir discussion dans #2547, au final c'est causé non pas par l'auto-complete mais par des appels swagger ponctuels, et on n'a pas priorisé de travail sur l'API de ce côté là pour l'instant, donc pas la peine non plus de garder le ticket ouvert.

On revisitera sûrement de façon plus générale dans le futur.
