### ISSUE TITLE
Validateur GTFS à la demande : ajouter l'information "Données présentes dans la ressource"

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#2478]
ça serait possible dans le validateur GTFS (celui disponible dans la rubrique "Outils"") de faire apparaître la brique "données présentes dans le GTFS" ? 

Si on pouvait avoir toute la liste des données pouvant être présentes avec en vert celles qui sont contenues dans le GTFS et en gris celles qui n'apparaissent pas, ça pourrait aider les producteurs à compléter leur GTFS

**Comment by AntoineAugusti** [comment]
Une capture d'écran pour aider à la compréhension.

![image](https://user-images.githubusercontent.com/295709/176000426-3a1647d6-b12d-4443-8d04-0c18c437820b.png)


@Miryad3108 Pour confirmer, tu parles bien de la validation à la demande ?

**Comment by Miryad3108** [comment]
Je parle bien d'ajouter cette information au validateur à la demande (cf. titre de l'issue) 
@AntoineAugusti

**Comment by AntoineAugusti** [comment]
Voir aussi https://github.com/etalab/transport-site/issues/2218
