### ISSUE TITLE
Outil Contribuer qui ne fonctionne pas : "La demande de modification a échoué"

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#2486]
L'Outil Contribuer renvoie ce message d'erreur : 
<img width="634" alt="image" src="https://user-images.githubusercontent.com/59559301/176867490-d8c5e9fc-e745-4eec-94b6-7343d54ce549.png">

J'ai essayé plusieurs fois de faire une contribution mais le même message apparaît. 

Le fichier est valide 
<img width="662" alt="image" src="https://user-images.githubusercontent.com/59559301/176867607-7e02e7e5-1c93-46e3-a666-9b098c2df6e2.png">

Ci-dessous, le fichier que j'ai voulu uploader : 
[bnlc- (78).csv](https://github.com/etalab/transport-site/files/9027775/bnlc-.78.csv)

**Comment by AntoineAugusti** [comment]
Je vais clore cette issue comme le problème est résolu et semblait temporaire, surement avec une API de GitHub.

Si ceci se renouvelle, pourrais-tu regarder la console web de ton navigateur et partager les erreurs ?

Merci !
