### ISSUE TITLE
Ne pas historiser les ressources de type documentation

### ISSUE THREAD

**Issue by fchabouis** [etalab/transport-site#2505]
Ou en tout cas comprendre pourquoi celle ci se fait autant historiser !
https://transport.data.gouv.fr/datasets/stationnement-velo-ouest-cornouaille/#backed-up-resources

**Comment by AntoineAugusti** [comment]
Des éléments sur l'ampleur du phénomène dans https://github.com/etalab/transport-site/pull/2507#issuecomment-1182860162

C'est historisé beaucoup car le lien est vers GitHub et le code source de la page HTML de GitHub doit changer très souvent avec des choses comme du hash sur les fichiers JS.

**Comment by AntoineAugusti** [comment]
Fichiers et lignes supprimés en production https://github.com/etalab/transport-site/pull/2487#issuecomment-1188735595

**Comment by AntoineAugusti** [comment]
162 lignes en moins en staging
