### ISSUE TITLE
Echec irrécupérable suite à un route_text_color incorrecte 

### ISSUE THREAD

**Issue by ChristinaLaumond** [etalab/transport-site#2518]
Comme discuté dans Mattermost, On a un échec irrécupérable à cause d'une route_text_color mal renseignée ("0" à la place de l'hexadécimal attendu) -> https://transport.data.gouv.fr/resources/79011#validation-report
est-ce que c'est normal ? j'aurais imaginé avoir un warning mais pas forcément un échec irrécupérable. Thanks :)

**Comment by ChristinaLaumond** [comment]
Autre échec irrécupérable suite à un pb de shapes pour Montauban https://transport.data.gouv.fr/resources/62959#validation-report : 
<img width="717" alt="image" src="https://user-images.githubusercontent.com/101095139/179688042-c84cfccf-62cd-494a-a0db-66e0f5311b2f.png">

**Comment by AntoineAugusti** [comment]
L'erreur provient de `gtfs_structures`

https://github.com/rust-transit/gtfs-structure/blob/7983d6604f7434a2be6c5d4e2e4539bcf2532c3a/src/error.rs#L28-L30

qui lève une `gtfs_structures::Error`

Ceci est transformé en `issues::Severity::Fatal` par le validateur ensuite.

https://github.com/etalab/transport-validator/blob/e61c5eb850bf786dd0806f8a0d6d79d8156db4f7/src/validate.rs#L7-L18

Le validateur lève une erreur `Fatal` car dès que `gtfs_structures` rencontre une `Error`, le parsing des autres fichiers s'arrête et donc on a pas un rapport complet.

---

Ça semble être [incohérent avec d'autres erreurs](https://github.com/etalab/transport-validator#severity) qui seraient de type `Error`, comme par exemple pour `InvalidCurrency`.

Le problème est que si on choisit de réparer ceci il faut modifier au moins 2 dépendances.

**Comment by Tristramg** [comment]
Pour transformer le `Fatal` en `Error`, il y a moyen de se brancher ici: https://github.com/etalab/transport-validator/blob/master/src/validate.rs#L80 et rajouter un matching sur `InvalidColor`.

Par contre ça ne règle pas le soucis que la transformation de RawGtfs à Gtfs n’est pas possible sans définir un comportement de modification du GTFS pour inventer des valeurs

**Comment by fchabouis** [comment]
Je serais d'avis de laisser comme ça pour l'instant. Il y a une erreur qui est relativement bien signalée et que le producteur peut corriger. Ensuite il peut revalider avec le validateur en ligne. Mettre des couleurs par défaut, ça veut dire qu'on se met à valider un GTFS qu'on a modifié et non plus ce que la personne a fourni, ça ajoute de la complexité et ça rend la compréhension de l'output de validation plus difficile.

**Comment by AntoineAugusti** [comment]
Du même avis que @fchabouis et en faveur de clore l'issue en conséquence
