### ISSUE TITLE
Migration des templates EEX/LEEX vers HEEX

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#2538]
Depuis la [documentation](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.Helpers.html#sigil_H/2):

> HEEx is a HTML-aware and component-friendly extension of Elixir Embedded language ([EEx](https://hexdocs.pm/eex/EEx.html)) that provides:
> - Built-in handling of HTML attributes
> - An HTML-like notation for injecting function components
> - Compile-time validation of the structure of the template
> - The ability to minimize the amount of data sent over the wire

HEEX a débuté comme un remplacement des templates LiveView LEEX, mais au final devient également pertinent pour les vues "normales" (https://github.com/phoenixframework/phoenix_live_view/issues/1506#issuecomment-871740441).

Une migration vers ce nouveau système apportera les bénéfices mentionnés ci-dessus, un formatage automatique (qui a été intégré dans `mix format` directement), et sera plus "future-proof".

### Evaluation du chantier

J'ai fait une mesure rapide, voilà ce que ça donne:

```
❯ git ls-tree -r master --name-only | awk -F'[.]' '{print $NF}' | sort | uniq -c | grep eex
  62 eex
   7 heex
   2 leex
```

### Recommendations

Commencer petit, et y aller par étapes (petites PR), pour que les PR ne durent pas trop longtemps, car sinon on va avoir des changements en parallèle dans les vues et de la perte de temps.

J'ai pendant le processus écrit un script pour aider à passer en revue avec un diff convenable, car GitHub ne donnait pas quelque chose de facile à comparer du fait des renommages : https://gist.github.com/thbar/a637f900b9597f9fe6d78de51b80d38a

**Comment by thbar** [comment]
Poke @fchabouis @hugoguignardchab j'ai préparé quelques éléments ci-dessus pour introduire le sujet !

**Comment by thbar** [comment]
J'ai demandé sur le Slack si il existait un convertisseur, la réponse est:

> Heex is quite good at telling you where things are off
> so changing the extension file by file and making the project compile again works quite well

**Comment by thbar** [comment]
Suite au travail de @hugoguignardchab et de moi-même en review (un peu "impliquée" car c'est velu), on a bien progressé, on passe de 62 `eex` à :

```
❯ git ls-tree -r master --name-only | awk -F'[.]' '{print $NF}' | sort | uniq -c | grep eex
  28 eex
  41 heex
   2 leex
```

J'en reste là pour aujourd'hui, les PR suivantes sont en draft et je suis fatigué :-)

**Comment by thbar** [comment]
Statut actuel :

```
❯ git ls-tree -r master --name-only | awk -F'[.]' '{print $NF}' | sort | uniq -c | grep eex
  17 eex
  55 heex
```

**Comment by hugoguignardchab** [comment]
état actuelle de la transition:
```
>git ls-tree -r master --name-only | awk -F'[.]' '{print $NF}' | sort | uniq -c | grep eex
     14 eex
     58 heex
et 
     6 eex
     66 heex en prenant en compte les pr non merger 😈
```
merci @fchabouis @AntoineAugusti et @thbar de m'avoir aider

**Comment by thbar** [comment]
Bravo encore @hugoguignardchab, super boulot, tu nous auras bien fait avancer ! 💜 💚 ❤️

**Comment by thbar** [comment]
Avec les derniers travaux de @AntoineAugusti, on est bons !!! Beau travail:

```
❯ git ls-tree -r master --name-only | awk -F'[.]' '{print $NF}' | sort | uniq -c | grep eex
  74 heex
```
