### ISSUE TITLE
Référencement d'un nouveau jdd -> message d'alerte si le jdd existe déjà 

### ISSUE THREAD

**Issue by ChristinaLaumond** [etalab/transport-site#2542]
aujourd'hui si on ajoute un jdd déjà existant sur le PAN, on ne nous prévient pas qu'il existe et qu'on va créer un doublon -> le dataset est créé. 

-> Est-ce qu'on pourrait avoir un petit message d'alerte nous indiquant que le jeu existe déjà avec le lien et nous demandant de confirmer l'ajout du nouveau jeu  ? quelque chose comme "Ce jeu de données existe déjà ici. Êtes-vous sur de vouloir le référencer de nouveau ?" "Oui  / Non"

**Comment by AntoineAugusti** [comment]
Peux-tu vérifier qu'actuellement ça ne crée pas de doublon mais ça édite le JDD existant ?

**Comment by ChristinaLaumond** [comment]
en effet, ça édite le jdd existant

**Comment by ChristinaLaumond** [comment]
dans ce cas, l'alerte serait plutôt "Ce jeu de données existe déjà, souhaitez-vous l'éditer ?"

**Comment by AntoineAugusti** [comment]
Cette issue est-elle toujours pertinente ou ça n'arrive pas si souvent que ça et le comportement est "acceptable" ?

**Comment by ChristinaLaumond** [comment]
ok comportement acceptable
