### ISSUE TITLE
investigation erreur 404 - nouveau jdd à référencer

### ISSUE THREAD

**Issue by ChristinaLaumond** [etalab/transport-site#2543]
Comme discuté dans [Mattermost](https://mattermost.incubateur.net/betagouv/pl/596q3fonut8z9y3z5oiyucmhuc), petit ticket pour investiguer sur ce qu'il s'est passé au moment du référencement d'un nouveau jdd (stationnements cyclables Tourcoing).

Au départ, en le créant, j'ai voulu l'associer à la commune Tourcoing -> derrière j'ai eu un message d'erreur me l'indiquant. J'ai donc retenté mais j'ai eu des 404 et au final, le jdd a bien été référencé sans que je m'en rende compte (je n'ai pas vu le message de confirmation que mon jdd avait été créé et que je pouvais le visualiser à telle url). 
 
Plusieurs pistes mais je ne saurais pas dire dans quel ordre ni les réels impacts car en l'espace d'une minute j'ai du faire plusieurs essais : 
- à un moment je n'ai pas mis le https devant l'url data.gouv 
- peut-être que le jeu était référencé mais comme je n'ai pas été prévenu, en voulant persévérer cela a fini par faire une 404 ?  

CF. Lien d'Antoine vers la partie qui force la présence d'une commune ou EPCI pour le champ spatial  https://github.com/etalab/transport-site/blob/dc205251fc729291230f08d064770d2f6bd001b5/apps/transport/lib/transport/import_data.ex#L258-L326

**Comment by thbar** [comment]
Quelques notes en + de la part de @Miryad3108 :

<img width="617" alt="CleanShot 2022-07-25 at 14 56 11@2x" src="https://user-images.githubusercontent.com/10141/180782471-c790aaae-4f48-4741-bc51-8978b27d9af3.png">

**Comment by AntoineAugusti** [comment]
Pas possible à répliquer pour le moment, à voir si ça survient à nouveau.
