### ISSUE TITLE
Référencement d'un Netex alors que n'existe pas pour Caen 

### ISSUE THREAD

**Issue by ChristinaLaumond** [etalab/transport-site#2546]
Hello 
Pour le jdd de Caen je ne sais pas pourquoi on a une case "Ressources Netex" alors qu'il ne semble pas y avoir de Netex pour ce jdd : 
https://transport.data.gouv.fr/datasets/donnees-de-transport-theoriques-du-reseau-twisto/ 
<img width="574" alt="image" src="https://user-images.githubusercontent.com/101095139/180819868-83dc4465-c6ee-4d88-8de3-535ca7270a2a.png">
lien vers data.gouv : https://www.data.gouv.fr/fr/datasets/donnees-de-transport-theoriques-du-reseau-twisto/ 
Thanks

**Comment by AntoineAugusti** [comment]
Ne semble pas réplicable.

**Comment by AntoineAugusti** [comment]
N'hésite pas à rouvrir si ceci se reproduit.
