### ISSUE TITLE
GTFS Nancy avec shapes mais non visibles dans la visualisation

### ISSUE THREAD

**Issue by ChristinaLaumond** [etalab/transport-site#2548]
Hello, 
J'ai remarqué qu'on avait bien les shapes pour ce GTFS https://transport.data.gouv.fr/resources/55795#visualization 
Mais on ne peut pas les visualiser. Est-ce qu'il y a une explication ? Merci
Christina

**Comment by ChristinaLaumond** [comment]
idem pour ce GTFS https://transport.data.gouv.fr/resources/77363#visualization

**Comment by AntoineAugusti** [comment]
> https://transport.data.gouv.fr/resources/55795#visualization

Les `shape_id` dans `shapes.txt` ne correspondent pas au `shape_id` dans `trips.shape_id`.

Pour ceci, manque surement un avertissement dans le validateur.

> idem pour ce GTFS https://transport.data.gouv.fr/resources/77363#visualization

Pour ce fichier, toutes les latitudes/longitudes ont ces valeurs `-90.000000,0.000000`

**Comment by AntoineAugusti** [comment]
@etalab/transport-tech Il y a déjà des règles pour les coordonnées invalides dans le validateur. Pensez-vous qu'une évolution est nécessaire ? https://github.com/etalab/transport-validator/blob/38e655b735f03d63e87094ca3acf74b0c0f23343/src/validators/shapes.rs#L23-L30

**Comment by AntoineAugusti** [comment]
@fchabouis Un avis ?

**Comment by fchabouis** [comment]
Oui ça serait bien qu'on rajoute le check je pense ! Merci d'avoir repéré le problème.

**Comment by AntoineAugusti** [comment]
@fchabouis Tu penses qu'il faut ajouter un check ?

Il y a déjà une sécurité existante https://github.com/etalab/transport-validator/blob/38e655b735f03d63e87094ca3acf74b0c0f23343/src/validators/shapes.rs#L23-L30 mais là toutes les latitudes/longitudes ont ces valeurs `-90.000000,0.000000`, ce qui ne rentre pas dans le périmètre actuellement.

Mais je me demande où est la limite, il y a quelques possibilités si on fait toutes les paires de valeurs extrêmes par exemple.

**Comment by AntoineAugusti** [comment]
@fchabouis Bump

**Comment by fchabouis** [comment]
Normalement des issues de validation vont apparaitre sur cette ressource prochainement, pour dire qu'il y a des soucis avec les shape id. A vérifier :)

**Comment by fchabouis** [comment]
j'ai relancé une validation à la main, mais notre worker a du pain sur la planche visiblement donc ça ne va pas arriver tout de suite.

**Comment by fchabouis** [comment]
Ca y est le validateur a tourné pour le dataset de stan, et les nouvelles issues apparaissent concernant les problèmes de shapes : https://transport.data.gouv.fr/resources/55795?issue_type=InvalidShapeId#issues
Si tu veux le signaler au producteur @ChristinaLaumond tu peux lui partager ce lien :)
