### ISSUE TITLE
Nouvelles sections "Ressources communautaires" et "Documentation" n'apparaissent pas dans la liste déroulante à gauche des jeux de données 

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#2559]
Je remarque que les nouvelles sections qui ont été ajoutées : ressources communautaires, ressources 
n'apparaissent pas dans le menu déroulant à gauche dans le jeu de données (là où on peut cliquer et ça renvoie directement vers la section) : c'est volontaire ?

cf : https://mattermost.incubateur.net/betagouv/pl/rzroaimoubyp9dka7sq3debiya

**Comment by hugoguignardchab** [comment]
En effet, il n'y a pas de section "Ressources communautaire", par contre la section "documentation" existe, mais que lorsqu'il y a une documentation de disponible.

**Comment by AntoineAugusti** [comment]
Hello,

C'était volontaire de me part de ne pas mettre de liens vers ces menus, tant que les sections sont vides (pour Documentation et Ressources communautaires).

La logique était : comme affiche ces sections avec un message d'incitation, il me parait peu opportun de faire un menu qui renvoit vers ça.

Ça peut être remis en question

**Comment by thbar** [comment]
Hello @AntoineAugusti ! Ah je m'étais dit que ça fait un petit "call to action" en terme de découvrabilité d'avoir ça dans le menu. Honnêtement les deux me vont. 

On verra @hugoguignardchab revient la semaine prochaine, maintenant que j'ai compris l'erreur qu'il avait rencontré, il pourra adapter !

**Comment by AntoineAugusti** [comment]
Je propose de fermer et de traiter ça dans https://github.com/etalab/transport-site/issues/2585 si nécessaire.

Actuellement :
- un lien vers les ressources communautaires a été ajouté dans le menu, visible tout le temps
- pas de changement pour la documentation, un lien dans le menu est présent si seulement il y a au moins une ressource
