### ISSUE TITLE
Stationnement cyclable : ne faire apparaître que les données au format "csv" dans la section "Ressource" 

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#2562]
Serait il possible de ne faire apparaître que les données au format "csv" dans la section "Ressource" des données de stationnement cyclable ? 
Il y a des ressources au format csv, geojson, xls dans la section "Ressource" mais le format demandé c'est bien le csv. 

Peut on faire apparaître ces autres formats dans une autre section ?

**Comment by ChristinaLaumond** [comment]
Hello, je complète la même demande pour les IRVE https://transport.data.gouv.fr/datasets/fichier-consolide-des-bornes-de-recharge-pour-vehicules-electriques/ :) Thanks

**Comment by AntoineAugusti** [comment]
Qu'est-ce qui justifie selon vous ce comportement ? On essaie de ne pas faire trop de choix éditoriaux qui amènent à masquer des choses par rapport à data.gouv.fr.

Les ressources de documentation me paraissent pertinentes par exemple pour les IRVE.

**Comment by ChristinaLaumond** [comment]
Les ressources de documentation pour les IRVE sont bien identifiées dans "documentation" 
l'objectif principal est de mettre en avant le format attendu en priorité. @Miryad3108  dis moi si je me trompe ? 
Ex : dans le cas des IRVE on a d'abord le JSON avant le csv. Je connais pas trop le JSON donc je sais même pas si c'est utilisé plus que le csv vous pensez ? dans le monde commun des réutilisateurs y a t'il un avis là dessus ? En tout cas, on peut garder les 2 mais peut-être qu'avoir un truc type "Ressource principale" et "Autres ressources" nous aiderait à rendre plus lisibles les jdd
<img width="568" alt="image" src="https://user-images.githubusercontent.com/101095139/184892455-48cb47b4-f720-4228-a801-315025842c80.png">
