### ISSUE TITLE
Validateur à la demande GBFS : faire apparaître la version du GBFS

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#2563]
On fait apparaître la version du GBFS dans les métadonnées des ressources GBFS sur le PAN. 
Serait-il possible de faire apparaître cette information dans les métadonnées du validateur GBFS à la demande ? (Disponible depuis l'onglet "Outils" de la page d'accueil)
<img width="734" alt="image" src="https://user-images.githubusercontent.com/59559301/182783560-a82f1f14-5c1d-47ae-9913-a275a4869111.png">

cf : https://transport.data.gouv.fr/tools/gbfs/analyze?url=https%3A%2F%2Fvannes-gbfs.klervi.net%2Fgbfs%2F2%2Fgbfs.json

**Comment by AntoineAugusti** [comment]
La validation GBFS avait une erreur mais @PierrickP a amélioré la situation dans https://github.com/MobilityData/gbfs-validator/pull/81 ! 🙏 

On est donc en mesure [d'afficher un rapport de validation](https://transport.data.gouv.fr/tools/gbfs/analyze?url=https%3A%2F%2Fvannes-gbfs.klervi.net%2Fgbfs%2F2%2Fgbfs.json)

**Comment by PierrickP** [comment]
@AntoineAugusti si tu as un contact chez eux, il leur suffit de rajouter la version sur le fichier `gbfs.json` pour améliorer grandement le feed (il sera testé avec la bonne version)

**Comment by AntoineAugusti** [comment]
@PierrickP Oui on a contacté Fifteen début août pour leur indiquer ceci, ça prend un peu de temps avec la période estivale mais c'est bien suivi par @etalab/transport-bizdev 💪
