### ISSUE TITLE
Améliorer référencement du site 

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#2567]
Quand on tape juste "Transportdatagouv", le résultat qui pointe vers le PAN sur Google chrome indique "Transport**s**.data.gouv.fr" 
ça serait bien qu'on retire le "s"
<img width="443" alt="image" src="https://user-images.githubusercontent.com/59559301/183428206-78295914-7eb8-4d31-b8b5-53d0f96aeb2e.png">

Sur Edge le résultat n'est pas le même (mieux que sur Chrome)
<img width="875" alt="image" src="https://user-images.githubusercontent.com/59559301/183428465-a025793d-a098-437c-a2aa-f36dc5c21350.png">

**Comment by ChristinaLaumond** [comment]
Vu en réunion du 09/08 pas de soucis sur les moteurs de recherche google, Bing, Yahoo, Qwant. Voir si le cas se reproduit sur un autre moteur de recherche ?
