### ISSUE TITLE
Rendre les tuiles de présentation du PAN "cliquable" : qu'elles redirigent vers des pages spécifiques du site

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#2568]
Rendre ces 3 tuiles cliquables : 
<img width="610" alt="image" src="https://user-images.githubusercontent.com/59559301/183429844-d2d614b0-b00f-491b-8c0c-b21e75c8ff3f.png">

- Pour la première tuile "Une plateforme GRATUITE et librement ACCESSIBLE" : on pourrait renvoyer vers la tuile [FAQ Généralités](https://doc.transport.data.gouv.fr/foire-aux-questions-1/generalites) de la doc ou ["Notre mission"](https://doc.transport.data.gouv.fr/evolution-et-defis-du-pan) (qu'il faudrait compléter). 

- Pour la tuile "Un catalogue EXHAUSTIF de données ouvertes
Formats homogènes
Licences harmonisées" :  on pourrait rendre rediriger vers [Formats homogènes](https://doc.transport.data.gouv.fr/producteurs/les-delais-douverture-des-donnees/les-formats-par-categorie-de-donnees) et [Licences harmonisées](https://doc.transport.data.gouv.fr/presentation-et-mode-demploi-du-pan/conditions-dutilisation-des-donnees)

- Pour la tuile "Des outils pour faciliter leur réutilisation" : on pourrait faire apparaître la fenêtre "Outils" ? 

ça permettra notamment de rendre découvrable des parties importantes de la documentation

**Comment by AntoineAugusti** [comment]
Est-ce que les visiteurs vont vraiment comprendre que ces blocs sont cliquables ? L'interface me ferait juste penser à du texte sans autre élément comme des couleurs du souligné etc.

**Comment by AntoineAugusti** [comment]
@Miryad3108 As-tu vu ma réponse ?

**Comment by Miryad3108** [comment]
Merci pour ta relance @AntoineAugusti 
Pour moi des tuiles/blocs sont cliquables sur un site du coup je voyais bien une redirection vers des éléments déjà existants  mais on peut laisser comme tel
