### ISSUE TITLE
Ajouter les ressources SIRI-Lite dans la section "Ressources temps-réel"

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#2569]
Dans le [jeu de données BlaBlaCar Bus](https://transport.data.gouv.fr/datasets/blablacar-bus-horaires-theoriques-et-temps-reel-du-reseau-europeen/) où il y a du GTFS, GTFS-RT et SIRI-Lite, les données SIRI-Lite apparaissent dans "Ressources" et non dans "Ressources temps-réel" 
ça serait possible de mettre les ressources SIRI-Lite (et SIRI) dans la section "Ressources temps-réel" ? 
<img width="324" alt="image" src="https://user-images.githubusercontent.com/59559301/183625887-0ec61708-954b-4b9a-bacd-fd09fdcbe6c3.png">

**Comment by AntoineAugusti** [comment]
Réparé :)
