### ISSUE TITLE
Ressources non disponibles sur le serveur distant mais taux de disponibilité au téléchargement de 100% : Oise

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#2575]
Dans le [jeu de données de l'Oise publié par la région](https://transport.data.gouv.fr/datasets/arrets-horaires-et-parcours-theoriques-gtfs-du-reseau-routier-regional-de-transport-18/), quand on clique sur "Télécharger" ça renvoie vers un message d'erreur disant que les données ne sont plus disponibles sur le serveur distant (j'ai forcé l'import des données il y a 1h pour vérifier si c'était pas un soucis d'affichage) mais dans le taux de disponibilité au téléchargement, c'est marqué 100% pour aujourd'hui (et depuis le 27.07)

**Comment by AntoineAugusti** [comment]
Régression introduite dans https://github.com/etalab/transport-site/pull/2544 ou #2495 ?

**Comment by AntoineAugusti** [comment]
Voir [discussion sur Mattermost](https://mattermost.incubateur.net/betagouv/pl/e5e6phe537f67rr78umxiwh9dc).

Après investigation, on constate que les URLs renseignées sont non valides. Exemple : `http://exs.sismo2.cityway.fr/GTFS.aspx?key=SISMO&amp;OperatorCode=LRRL2`

- Le `&amp;` devrait être `&`
- Il faudrait utiliser du HTTPS

@Miryad3108 a pris contact avec les producteurs / Cityway pour voir comment réparer ça. Il faut regarder leur moissonnage aussi.

En regardant l'étendue du problème, ça concerne ce jeu de données et [Agrégat de réseaux urbains et interurbains de l'Oise (60)](https://transport.data.gouv.fr/datasets/arrets-horaires-et-parcours-theoriques-gtfs-des-differents-reseaux-de-transport-membres-du-synd3-1).

@etalab/transport-bizdev si la correction prend trop de temps ou que l'urgence évolue, on peut envisager un correctif technique côté PAN. N'hésitez pas à solliciter quelqu'un.

**Comment by AntoineAugusti** [comment]
Je viens de voir que c'est un doublon de https://github.com/etalab/transport-site/issues/1967 en fait !

**Comment by AntoineAugusti** [comment]
On a bien géré la différence d'affichage d'uptime dans https://github.com/etalab/transport-site/pull/2586. Reste l'autre issue.
