### ISSUE TITLE
Analyse du fonctionnement de la consolidation IRVE v2

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#2576]
Suite à discussion avec @ChristinaLaumond et @Miryad3108, sur le fait qu'on constate des ajouts fréquents en IRVE sur data gouv, qu'on doit assurer le support, mais que pour autant on (je, en tout cas) ne maîtrise pas forcément assez le sujet, j'ai été me renseigner faire une passe d'exploration rapide et voir comment fonctionne le tout.

Je documente ici ma compréhension actuelle.

On a évoqué dans la discussion que:
- le processus gagnerait à être géré directement par "transport", pour pouvoir "laver au coeur du linge" et avoir des cycles de réaction les plus rapides possibles (correctifs, logs, déploiements etc) si ce n'est pas problématique pour "data gouv"
- (opinion personnelle) je pense que ré-intégrer le fonctionnement dans notre stack Elixir directement (nativement, en job Oban) permettrait d'avoir un meilleur suivi ; opinion confortée par le fait d'avoir pris connaissance du code de consolidation, que je résume ci-dessous, qu'on pourrait mettre sous tests etc dans notre codebase

On peut voir directement le code de production (sauf erreur) ici https://github.com/etalab/notebooks/blob/master/irve-v2/consolidation-irve-v2.ipynb (et le code Python apparaitra).

On a en résumé le fonctionnement suivant:

1. L'algorithme parcourt data gouv via l'API, avec plusieurs sources ([tags](https://www.data.gouv.fr/api/1/datasets/?tag=irve), [meta-data schema](https://www.data.gouv.fr/api/1/datasets/?schema=etalab/schema-irve), recherche ([mode 1](https://www.data.gouv.fr/api/1/datasets/?q=recharge+v%C3%A9hicules+%C3%A9lectriques) et [mode 2](https://www.data.gouv.fr/api/1/datasets/?q=irve)) - peut-être qu'une façon de faire unique est recommandée aujourd'hui ? Peut-être que les autres sont "legacy" ? A voir.
2. Les datasets etalab (`['54231d4a88ee38334b5b9e1d', '5448d3e0c751df01f85d0572']`) sont filtrés de la recherche - j'imagine que ce sont les deux consolidations elles-mêmes, ou quelque chose comme ça
3. Un dédoublonnage est réalisé (puisque chaque recherche peut retourner plusieurs fois une ressource donnée)
4. Les ressources sont téléchargées en local (je ne vois pas quel traitement d'erreur est fait ; des logs sont générés)
5. Une validation via validata est réalisée, après un mapping des champs en fonction de la version du schéma IRVE (ce qui me fait me demander quelle est la répartition selon la version), le tout retourne un array de resources + leur status de validation
6. Un dédoublonnage supplémentaire est réalisé (je ne sais pas encore pourquoi, mais il y a sûrement une bonne raison, je n'ai pas creusé le code à 100% - EDIT, je vois plus bas pourquoi)
7. Une publication est réalisée (ressource, logs)

Dans la globalité, ça donne à peu près ça.

Voilà, pour future base de discussion !

**Comment by thbar** [comment]
PS: tout est à discuter, c'est simplement une prise de notes :smile:

**Comment by AntoineAugusti** [comment]
Chaud pour discuter de la raison pour laquelle il faudrait que le PAN reprenne cette consolidation en terme de gouvernance et de code !

**Comment by thbar** [comment]
Je comprends mieux ce qui se passe à présent. Vu avec @geoffreyaldebert et @ChristinaLaumond, en l'état on conserve la consolidation Python, et on la fera évoluer de façon légère ; si les besoins divergent trop (il y a un besoin de généricité côté data gouv), on sera amené à reprendre en main chez nous, en Elixir.

En "entre-deux", pour satisfaire les besoins d'analyse "pre-consolidation" qu'on va avoir, j'ai réalisé un script qui aide bien ici (et qui est très efficient : installation plus facile pour nous, rapidité d'exécution avec un cache local automatique etc).

- https://github.com/etalab/transport-site/pull/2639

Pour l'instant je clôture ici.
