### ISSUE TITLE
Bouton "télécharger" à adapter en fonction du type de données 

### ISSUE THREAD

**Issue by ChristinaLaumond** [etalab/transport-site#2578]
hello, comme discuté [ici ](https://mattermost.incubateur.net/betagouv/pl/hzmne1pqefnftdqhapu4aun9ge),  le bouton "télécharger" a du sens quand on télécharge réellement un fichier statique sur son ordinateur (GTFS, CSV etc.). Lorsqu'on parle d'un format temps réel type SIRI en xml ou même GTFS-RT ou GBFS, au lieu de télécharger on pourrait avoir un bouton "lien API" ou "lien GTFS-RT" ou "lien SIRI" 

-> tous les avis sont bons à prendre :) @Miryad3108  tu en penses quoi ?

**Comment by Miryad3108** [comment]
Bonne idée de distinguer ce qu'on peut télécharger à ce qui renvoie vers d'autres pages/redirections
Mettre juste "Lien" pourrait suffire ?

**Comment by AntoineAugusti** [comment]
@hugoguignardchab Vaut mieux attendre que tu aies fini https://github.com/etalab/transport-site/pull/2582 ?
