### ISSUE TITLE
Page dataset : beaucoup de messages d'infos

### ISSUE THREAD

**Issue by fchabouis** [etalab/transport-site#2585]
Je trouve que la page dataset a maintenant beaucoup de petits messages, qui sont écrits de manière hétérogènes : certains avec des :information_source: , certains en gris clair, d'autre en gris foncé et que le résultat est un peu fouillis. Ça serait bien de lisser un peu tout ça, de revoir les paddings, etc.

![image](https://user-images.githubusercontent.com/15341118/185916047-24231e40-93a6-4984-9921-4543d62d62d1.png)

**Comment by AntoineAugusti** [comment]
Carrément. C'est moi le responsable.

Je suis retombé dessus et c'est vrai que maintenant c'est beaucoup moins joli qu'auparavant, en particulier quand il n'y a pas de ressources de documentation/ressources communautaires.

**Comment by AntoineAugusti** [comment]
@fchabouis Tu as une idée de comment améliorer la situation ? @etalab/transport-bizdev peut-être ?

**Comment by ChristinaLaumond** [comment]
Pour homogénéiser on peut simplement dans un premier temps : 
- mettre tous les titres de la même police et même couleur : noire et de la même taille que "Ressources communautaires" par exemple. 
- mettre tous les corps de texte en gris même taille, même police
Le petit "i" info ne me choque pas.

**Comment by AntoineAugusti** [comment]
@ChristinaLaumond En complément, envisager de déplacer la phrase

> Vous réutilisez ce jeu de données ? [Envoyez-nous un message](https://transport.data.gouv.fr/#mail_form) afin que l’on puisse en discuter et mettre en avant votre réutilisation.

Dans la section "Réutilisations" (et l'afficher quand même s'il n'y a aucune réutilisation)
