### ISSUE TITLE
Datasets' reusability information

### ISSUE THREAD

**Issue by maukoquiroga** [etalab/transport-site#26]
[Check this theme in the roadmap](https://trello.com/c/H7T37ylX/13-producers-know-datasets-reusability)

**Definition of done**

- [ ] I can visually identify reusable datasets
- [ ] I can visually identify not reusable datasets
- [ ] I can click on a dataset to have more info
- [ ] If it's reusable, I want to click somewhere to download the dataset
- [ ] If it's not reusable, I want to know why it's not reusable
- [ ] If it's not reusable, I want to how to make it reusable
- [ ] If it's not reusable, I want to be able to contact the data producer

**Comment by Tristramg** [comment]
Closing as over a year old.
