### ISSUE TITLE
Disponibilité d'un jdd à 100% alors que non dispo car sur FTP

### ISSUE THREAD

**Issue by ChristinaLaumond** [etalab/transport-site#2602]
Hello, nous avons remarqué que la dispo du jdd du réseau Oléane était à 100% alors que le GTFS n'est pas dispo car présent sur un FTP au lieu d'une url HTTPS 
<img width="349" alt="image" src="https://user-images.githubusercontent.com/101095139/187154937-026afcfa-e06f-484f-9db7-d8c881dea3ce.png">
Il semblerait qu'il y ait un souci peut-être du à l'indisponibilité générale du fichier ? 
Merci 
Christina

**Comment by AntoineAugusti** [comment]
Le code de détection de dispo/indispo ne gère pas les ressources qui ont une URL FTP, comme le reste du PAN, ce qui explique ce comportement.

https://github.com/etalab/transport-site/blob/f2f183ca0cb5f65140e216a2001083d72851b50b/apps/transport/lib/jobs/resource_history_job.ex#L30

Il n'est pas prévu de gérer les ressources en FTP pour le moment.
