### ISSUE TITLE
Ne pas avoir de ressources en FTP

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#2603]
Lié à #2602 

Le PAN ne gère pas les ressources avec des URL FTP.

Il y a actuellement 2 ressources référencées sur le PAN.
- https://transport.data.gouv.fr/datasets/lignes-arrets-et-horaires-theorique-du-reseau-de-transport-gtfs-les-sables-dolonne-agglomeration
- https://transport.data.gouv.fr/datasets/arrets-horaires-et-circuit-de-la-lignes-yeu-continent-gtfs

Est-il possible de prendre contact avec les producteurs et d'assurer une publication en HTTPS ?

**Comment by ChristinaLaumond** [comment]
merci. Le producteur est prévenu. Apparemment les modifications ont déjà été apportées pour l'île d'Yeu. Je relancerai pour les Sables d'Olonne. La bonne nouvelle c'est que des htpps existent ;) 
Je ferme le ticket ! merci
