### ISSUE TITLE
Import + validation d'un jdd mais non actualisation des ressources présentes

### ISSUE THREAD

**Issue by ChristinaLaumond** [etalab/transport-site#2607]
Hello,
Le producteur de Montluçon a mis un nouveau GTFS sur data.gouv.fr (le GTFS de la rentrée), j'ai donc importé puis validé le jeu de données pour que l'ajout du nouveau GTFS soit effectif directement mais cela ne semble pas fonctionner, le Nouveau GTFS n'arrive pas sur le PAN.
https://transport.data.gouv.fr/datasets/horaires-theoriques-du-reseau-maelis-montlucon-communaute-gtfs
thanks
Christina

**Comment by AntoineAugusti** [comment]
Hello,

Il faudrait : 
- renseigner le format comme `GTFS` au lieu de `zip` (le plus fiable)
- faire apparaitre le mot clé GTFS de manière isolée (avec un espace) dans le titre ou la description

**Comment by AntoineAugusti** [comment]
À noter que c'est assez complexe actuellement, mais stable dans le temps pour ne pas affecter les ressources ou habitudes des producteurs.

On pourrait adapter en cas de besoin !

https://github.com/etalab/transport-site/blob/f2f183ca0cb5f65140e216a2001083d72851b50b/apps/transport/lib/transport/import_data.ex#L446-L476

**Comment by ChristinaLaumond** [comment]
merci Antoine, j'ai un nouveau cas ce matin avec Vesoul je vais contacter le producteur.
Petite question, pour Montluçon, le GTFS est bien à jour désormais, est-ce grâce à une manip de ta part ? ou parce que le GTFS peut quand même arriver dans la nuit avec le process normal depuis data.gouv ? 
Merci

**Comment by ChristinaLaumond** [comment]
Le producteur de Vesoul a bien mis le format GTFS et correctement nommé son fichier mais je n'arrive toujours pas à rapatrier le GTFS à jour sur le PAN (via Import + validation) 
https://www.data.gouv.fr/fr/datasets/horaires-theoriques-du-reseau-vbus-communaute-dagglomeration-de-vesoul-gtfs/

**Comment by AntoineAugusti** [comment]
Vu en DM avec @ChristinaLaumond.

Pour Montluçon l'import a bien été fait, les fichiers sont détectés grâce au `filename` qui contient le mot clé `gtfs`.

Pour Vesoul, la question portait sur la partie validation (affectée par la multi-validation), pas de problème du côté de l'import.

Je ferme comme il n'y a pas d'évidence de bug (mais clairement de la confusion introduite par l'import de données "en retard" et la multi-validation, déjà connue).
