### ISSUE TITLE
Revoir fiches transport sur api.gouv.fr

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#2617]
Revoir les fiches du PAN sur https://api.gouv.fr/rechercher-api

Les fichiers concernés :

- https://github.com/betagouv/api.gouv.fr/blob/master/_data/api/temps_reel_transport.md
- https://github.com/betagouv/api.gouv.fr/blob/master/_data/api/api_catalogue_transport.md

**Comment by fchabouis** [comment]
J'ai fait la partie facile, j'ai demandé la suppression de https://tr.transport.data.gouv.fr :
https://github.com/betagouv/api.gouv.fr/pull/1033

**Comment by AntoineAugusti** [comment]
Voir https://github.com/betagouv/api.gouv.fr/pull/1045

**Comment by AntoineAugusti** [comment]
Les PRs ont été mergées !
