### ISSUE TITLE
Ajouter des headers CSP

### ISSUE THREAD

**Issue by fchabouis** [etalab/transport-site#2644]
Ca fait partie des points les plus problématiques relevés par https://dashlord.incubateur.net/url/transport-data-gouv-fr/securite/, nous n'avons pas des headers CSP.

En utilisant une [extension](https://github.com/april/laboratory) FF, et en me promenant rapidement sur le site, voici ce qu'il faudrait ajouter à nos headers pour que le site fonctionne (j'ai pu louper des pages):

```
default-src 'none'; 
connect-src 'self' https://transport-data-gouv-fr-resource-history-prod.cellar-c2.services.clever-cloud.com/conversions/gtfs-to-geojson/11765/11765.20220814.060152.519888.zip.geojson; 
font-src 'self'; 
img-src 'self' data: https://api.mapbox.com https://static.data.gouv.fr https://www.data.gouv.fr; 
script-src 'self' 'unsafe-eval' 'unsafe-inline' https://stats.data.gouv.fr/matomo.js; 
style-src 'self' 'unsafe-inline' 
```

Si je comprends bien les lignes les plus problématiques sont :
```
script-src 'self' 'unsafe-eval' 'unsafe-inline' https://stats.data.gouv.fr/matomo.js; 
style-src 'self' 'unsafe-inline' 
```

J'ai l'impression qu'on pourrait commencer par ajouter le header (après avoir bien visité toutes les pages du site pour ne rien casser), puis traiter les points un par un pour nous permettre de rendre la policy de plus en plus restrictive.

Il faudrait par exemple enlever tout le CSS inline de notre code pour pouvoir enlever le 'unsafe-inline'  correspondant.

Que pensez vous de cette manière de procéder @thbar et @AntoineAugusti ?

**Comment by thbar** [comment]
Je suis en train de traiter ce sujet pour un autre client, voilà des éléments intéressants :
- il existe un mode "report only" avec une "report-uri" qui permet de monitorer, sans "enforcer", la CSP (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy-Report-Only)
- Avec les maps et trucs de ce genre ça peut être funky
- Il y a ça https://elixirforum.com/t/phoenix-blog-post-content-security-policy-configuration-in-phoenix-with-liveview/37809 et je me suis demandé comment c'était traité dans le template actuel de Phoenix (si c'est traité tout court), il faudra aller jeter un oeil

**Comment by fchabouis** [comment]
Je viens de lire qu'on peut mettre des wildcards dans des urls, en laissant un "/" final. Par exemple, si on met `https://raw.githubusercontent.com/etalab/`, ça autorise toutes les urls qui commencent par cette chaine de caractères.

Une première version de notre CSP pourrait être :
```
 default-src 'none'; 
 connect-src 'self' https://raw.githubusercontent.com/etalab/ https://transport-data-gouv-fr-resource-history-prod.cellar-c2.services.clever-cloud.com/; 
 font-src 'self'; 
 img-src 'self' data: https://api.mapbox.com https://static.data.gouv.fr https://www.data.gouv.fr; 
 script-src 'self' 'unsafe-eval' 'unsafe-inline' https://stats.data.gouv.fr/matomo.js; 
 style-src 'self' 'unsafe-inline' 
```

**Comment by fchabouis** [comment]
Copies d'écran du rapport actuel, pour mémoire et pour vérifier qu'on résoud bien les problèmes après merge.
![image](https://user-images.githubusercontent.com/15341118/190186187-c170ebc2-f506-4951-a9e5-65a66db6a2c7.png)
![image](https://user-images.githubusercontent.com/15341118/190186207-9da4ae62-d322-4790-a20f-94f483330ff1.png)
