### ISSUE TITLE
Données GTFS-RT Rouen non validées depuis +10j 

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#2653]
Rouen nous a contacté parce que le rapport de validation d'[un de leur GTFS-RT](https://transport.data.gouv.fr/datasets/donnees-en-temps-reel-des-lignes-26-et-530-du-reseau-astuce-metropole-rouen-normandie) montrait 24 erreurs parce qu'il datait du 3/09 alors que le GTFS a été remplacé/corrigé le 8/09 
J'ai validé depuis le backoffice et là il n'y a plus d'erreur car la validation s'est basée sur le nouveau GTFS. 

ça faisait donc+10j que leurs données TR apparaissaient comme étant invalides alors qu'elles étaient valides 

<img width="537" alt="image" src="https://user-images.githubusercontent.com/59559301/190407855-deb8247f-aa5d-468e-a3c7-6b9d1d7d047d.png">

<img width="298" alt="image" src="https://user-images.githubusercontent.com/59559301/190407933-bf4d6f76-5333-4410-a356-33a4df9ea0fb.png">

**Comment by AntoineAugusti** [comment]
Hello,

En regardant le code, quelques logs, la base de données, je n'ai pas trouvé d'explication pour le moment. J'ai regardé plusieurs fois ce jeu de données depuis, sans constater de nouvelle occurence du bug.

À voir si ceci se reproduit plus tard ou dans d'autres circonstances.
