### ISSUE TITLE
Ajouter "Visualisation des données disponibles" pour les ressources geojson

### ISSUE THREAD

**Issue by fchabouis** [etalab/transport-site#2654]
Sur la page dataset, dans la carte de la ressource.
Pour faire comme sur les GTFS.

![image](https://user-images.githubusercontent.com/15341118/190982505-4b6655f6-80bf-4ebe-84f6-08e4a0991825.png)

**Comment by AntoineAugusti** [comment]
https://github.com/etalab/transport-site/issues/2301 est dans le même ton si tu es motivé
