### ISSUE TITLE
Couleurs des lignes bien présentes dans GTFS mais non détectées par le validateur

### ISSUE THREAD

**Issue by ChristinaLaumond** [etalab/transport-site#2656]
Hello, je viens de remarquer l'absence du flag "couleur des lignes" pour le GTFS de  Rennes alors qu'elles sont pourtant bien intégrées au GTFS : https://transport.data.gouv.fr/resources/79673 
<img width="469" alt="image" src="https://user-images.githubusercontent.com/101095139/191445603-1c8d3b11-1e29-4d74-81c8-41ad47a60ee2.png">
<img width="952" alt="image" src="https://user-images.githubusercontent.com/101095139/191445642-95edf605-52fe-45fe-b668-a5ba15c7e950.png">

Merci :)

**Comment by AntoineAugusti** [comment]
Hello,

En regardant les métadonnées, on a
```
"lines_count": 157,
"lines_with_custom_color_count": 155,
```

donc pas 100 %, mais très proche. Actuellement on demande 100 %, ce qui explique la chose. Tu penses que ça mérite un assouplissement ?

**Comment by ChristinaLaumond** [comment]
merci pour l'analyse ! on peut tenter d'assouplir à 80%  alors. 
merci
