### ISSUE TITLE
Supprimer le DNS pour tr.transport.data.gouv.fr

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#2681]
Il est encore là et ça peut prêter à confusion ("this app is starting")

**Comment by AntoineAugusti** [comment]
https://dns.google/query?name=tr.transport.data.gouv.fr ne donne pas de résultat, il faut faire quelque chose ?

**Comment by thbar** [comment]
@AntoineAugusti j'ai géré hier, on peut clôturer !
