### ISSUE TITLE
Améliorer la visualisation du contenu GTFS-RT tous types de services confondus

### ISSUE THREAD

**Issue by ChristinaLaumond** [etalab/transport-site#2688]
Dans le cas d'une visualisation du contenu d'un GTFS-RT contenant les 3 types de service (alert, update et position), la visualisation est moins simple que lorsque les flux sont séparés. En effet, dans ce genre de cas, tout se mélange et les infos trafics ne sont donc pas aussi lisibles que lorsque le flux est à part. Est-ce envisageable de différencier la visualisation du contenu par type de service  ?

Exemple de flux complet :  https://transport.data.gouv.fr/resources/52582
Exemple de flux indépendants facilitant la lisibilité du contenu : https://transport.data.gouv.fr/datasets/horaires-theoriques-et-temps-reel-des-bus-et-tramways-circulant-sur-le-territoire-de-brest-metropole 

Merci

**Comment by AntoineAugusti** [comment]
@ChristinaLaumond Comment est-ce que ça pourrait être amélioré ?

Les infos trafic sont affichées de manière "riche" (comme par exemple [pour Brest](https://transport.data.gouv.fr/resources/49675)) dès lors que le flux en contient actuellement. Il n'y a pas d'affichage s'il n'y en a pas à l'instant t, on renseigne également sur le fait qu'il y en a eu lors des 7 derniers jours à un moment.

**Comment by ChristinaLaumond** [comment]
Ok vu, les alerts s'affichent bien de manière séparée même lorsqu'on a un flux unique complet 
<img width="465" alt="image" src="https://user-images.githubusercontent.com/101095139/194242020-e5103c16-2536-4525-8fa2-4ea80603c8be.png">
merci
