### ISSUE TITLE
Showcase the products and organisations using the data

### ISSUE THREAD

**Issue by maukoquiroga** [etalab/transport-site#27]

**Comment by Tristramg** [comment]
@IshanB t’as une idée de comment on voudrait mettre ça en avant ? c’est un vieux sujet

**Comment by IshanB** [comment]
Comme ça ? https://data.nantesmetropole.fr/explore/dataset/244400404_tan-arrets-horaires-circuits/information/
![image](https://user-images.githubusercontent.com/28890473/47648611-d02e7a00-db7a-11e8-90a4-f4f2a8f35c6c.png)

mais on peut pas utiliser l'api de datagouv tout simplement ?

**Comment by Tristramg** [comment]
Considérons que le travail de @l-vincent-l là dessus y répond.
