### ISSUE TITLE
Essayer d'utiliser un fond de carte gratuit

### ISSUE THREAD

**Issue by fchabouis** [etalab/transport-site#2702]
J'en ai marre de payer des factures à Mapbox pour ses fonds de carte.
On a ça de [dispo](https://openmaptiles.geo.data.gouv.fr/) gratuitement, mais ce sont des vector tiles. Je voudrais essayer un de ces plugins pour voir si ça marche bien avec Leaflet.

* https://gitlab.com/jkuebart/Leaflet.VectorTileLayer/
* https://github.com/Leaflet/Leaflet.VectorGrid

**Comment by AntoineAugusti** [comment]
@fchabouis Il existe ceci aussi https://guides.etalab.gouv.fr/apis-geo/3-tuiles-vecteur.html

**Comment by fchabouis** [comment]
Pour info, https://github.com/Leaflet/Leaflet.VectorGrid [ne semble pas compatible](https://github.com/Leaflet/Leaflet.VectorGrid/issues/196) avec ce qui est mis à disposition par Etalab. C'est le styling qui n'est pas compatible. D'autre part, j'ai l'impression que le plugin rame pas mal (j'ai fait un style à la main avec la mer en rouge, et c'est assez lent).

![image](https://user-images.githubusercontent.com/15341118/195864993-742b31ea-dbe4-43f2-ac29-f232a350bcc7.png)

```js
    const vectorTileOptions = {
        vectorTileLayerStyles: {
            water: {
                fillColor: 'red',
                fillOpacity: 1,
                weight: 0,
                fill: true
            }
        }
    }

    Leaflet.vectorGrid.protobuf('https://openmaptiles.geo.data.gouv.fr/data/france-vector/{z}/{x}/{y}.pbf', vectorTileOptions).addTo(map)
```

Du coup j'ai essayé un fond de carte OSM gratuit en Francais, mais il est moins neutre que le précédent, ça fait des trucs comme ca :

![image](https://user-images.githubusercontent.com/15341118/195865205-c4863e6a-4aca-4088-98e7-21ec9f8a3398.png)
 à comparer avec l'état actuel :
![image](https://user-images.githubusercontent.com/15341118/195865358-eaffc7b9-34dc-4637-b0bb-aea28ebf2b8a.png)

**Comment by fchabouis** [comment]
On a une option intéressante à creuser du côté du [MEAE](https://www.gouvernement.fr/ministere-de-l-europe-et-des-affaires-etrangeres) qui a un fond de carte dispo : `https://{s}.piano.tiles.quaidorsay.fr/fr{r}/{z}/{x}/{y}.png`. Je vais essayer de les contacter pour leur demander l'autorisation de l'utiliser et voir si nos volumes sont compatibles avec leurs capacités.

Le fond est joli en plus :
![image](https://user-images.githubusercontent.com/15341118/203560881-9f5b016d-d5ef-4d45-8706-11cc4fe9142c.png)

**Comment by fchabouis** [comment]
la discussion en cours...https://mattermost.incubateur.net/betagouv/pl/3s9jxhae7bfe8y9oy6a8ot1p6c

**Comment by thbar** [comment]
@AntoineAugusti "good-first-issue" maybe ?

**Comment by AntoineAugusti** [comment]
Allez, j'ajoute ! Ce serait top d'aller au bout de cette issue.

**Comment by fchabouis** [comment]
Je pense qu'on peut fermer, je viens de me rendre compte qu'il est possible de requeter chez Mapbox des tuiles en 512*512 au lieu de 256*256, et comme on paye à la tuile, ça divise la conso par 4 ! Mapbox redeviendrait donc gratuit.
Si un jour on a une réponse du MEAE et un feu vert de leur part, on pourra remplacer Mapbox par ce fond de carte.
Pour l'instant je clôture l'issue, le problème de facturation est à priori réglé.
