### ISSUE TITLE
GTFS Fablio - Erreur sur parent_station ?

### ISSUE THREAD

**Issue by cyrilmorin** [etalab/transport-site#2731]
Hello,

Je ne comprends pas l'erreur irrécupérable mentionnée pour le GTFS Fablio - Châteaux Thierry
https://transport.data.gouv.fr/resources/79843?issue_type=InvalidReference#issues

Identifiant	Nom de l’objet     Identifiant associé	                 Détails
0		                                     ROUESSES (STA-NOGROUE1)      The stop is referenced as a stop's parent_station but does not exist

Dans le GTFS en question aucun arrêt ne semble faire référence à ce stop comme parent_station
https://www.data.gouv.fr/fr/datasets/r/eb2adabb-001f-4433-ba66-073a190fa04f

Merci pour votre aide !

Cyril

**Comment by AntoineAugusti** [comment]
Hello,

J'imagine que tu as téléchargé le fichier que tu voyais en haut de page et que tu ne voyais plus l'erreur ? En fait la validation est effectuée sur une version précise d'un GTFS.

Dans ce cas, le producteur a modifié le fichier entre temps. https://transport.data.gouv.fr/datasets/gtfs-reseau-fablio-lignes-regulieres voir "Discussions" où Bing Maps relève le problème.

Tu pourras voir le problème si tu télécharges le fichier [gtfs-10-18-2022-10-02-32.zip](https://transport-data-gouv-fr-resource-history-prod.cellar-c2.services.clever-cloud.com/79843/79843.20221025.115730.295793.zip) du 25/10/2022.

**Comment by AntoineAugusti** [comment]
Le processus d'historisation va détecter un changement dans le fichier GTFS, lancer un archivage et une validation sur ce nouveau fichier. L'erreur va disparaitre.

**Comment by cyrilmorin** [comment]
parfait merci !
