### ISSUE TITLE
API erreur 500

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#2752]
> Les jeux de données de STAR Rennes Métropole sont inaccessibles depuis l'API (erreur 500).

**Comment by thbar** [comment]
Je vois en particulier en faisant une recherche:
- https://transport.data.gouv.fr/datasets/versions-des-horaires-theoriques-des-lignes-du-reseau-star-au-format-gtfs (API: https://transport.data.gouv.fr/api/datasets/580a574aa3a7292dcfa9d1da)
- https://transport.data.gouv.fr/datasets/versions-des-horaires-theoriques-des-lignes-du-reseau-star-au-format-gtfs-1 (API: https://transport.data.gouv.fr/api/datasets/580defb1a3a7292dcfa9d33f)

**Comment by thbar** [comment]
J'ai une reproduction, je vois bien une erreur 500 sur les deux appels d'API:

```
❯ curl -I https://transport.data.gouv.fr/api/datasets/580a574aa3a7292dcfa9d1da
HTTP/1.1 500 Internal Server Error
content-length: 0
Sozu-Id: 01GH0T1JGEAHQWPHVD47W4GZ7F


transport-site on  siri-querier-parameter-queries [$!⇣] via 💧 v1.14.0 (OTP 24) 
❯ curl -I https://transport.data.gouv.fr/api/datasets/580defb1a3a7292dcfa9d33f
HTTP/1.1 500 Internal Server Error
content-length: 0
Sozu-Id: 01GH0T1R1PKGSK33HXNB8JFTHT
```

**Comment by thbar** [comment]
Je vois l'erreur apparaître dans Sentry: https://sentry.io/organizations/transport-data-gouv-fr/issues/3716741561/?project=6197733&query=is%3Aunresolved&referrer=issue-stream

<img width="689" alt="CleanShot 2022-11-04 at 08 54 35@2x" src="https://user-images.githubusercontent.com/10141/199921413-21d6324c-5973-4b9e-81a2-8d2edf29d9ca.png">

```
  File "lib/ecto/repo/queryable.ex", line 150, in Ecto.Repo.Queryable.one/3
  File "lib/transport_web/api/controllers/datasets_controller.ex", line 101, in TransportWeb.API.DatasetController.by_id/2
  File "lib/transport_web/api/controllers/datasets_controller.ex", line 1, in TransportWeb.API.DatasetController.action/2
  File "lib/transport_web/api/controllers/datasets_controller.ex", line 1, in TransportWeb.API.DatasetController.phoenix_controller_pipeline/2
  File "lib/phoenix/router.ex", line 354, in Phoenix.Router.__call__/2
  File "lib/transport_web/api/router.ex", line 1, in TransportWeb.API.Router.call/2
  File "lib/plug/router.ex", line 246, in anonymous fn/4 in TransportWeb.Plugs.Router.dispatch/2
  File "/phoenixapp/deps/telemetry/src/telemetry.erl", line 320, in :telemetry.span/3
```

**Comment by thbar** [comment]
Ok c'est causé par:

https://github.com/etalab/transport-site/blob/6411079cf5ddbae7beaed88653759bab0f5dcc6f/apps/transport/lib/transport_web/api/controllers/datasets_controller.ex#L90-L101

**Comment by thbar** [comment]
Régression effectivement introduite dans:
- https://github.com/etalab/transport-site/pull/2733

Je vais travailler en local à partir de là.

**Comment by AntoineAugusti** [comment]
Je remarque ce sont des JDD qui proviennent d'ODS où le CSV a été parsé. Peut-être une piste.

**Comment by thbar** [comment]
Pour mesurer l'impact j'ai été compter le nombre de jeux qui retournent un 500 en local, en m'assurant que c'était bien l'erreur dont on parle, voilà ce que ça donne (ça nous servira à vérifier le correctif après):

```elixir
%{200 => 406, {500, "# Ecto.MultipleResultsError "} => 144}
```

26% des jeux sont affectés.

<details>
<summary>Code utilisé pour évaluer en local</summary>

```elixir
Mix.install([
  {:req, ">= 0.0.0"}
])

require Logger
Logger.info("Starting...")

%{body: datasets} = Req.get!("http://localhost:5000/api/datasets")

datasets
|> Enum.map(& &1["id"])
|> Task.async_stream(
  fn id ->
    %{body: body, status: status} =
      Req.get!("http://localhost:5000/api/datasets/#{id}", retry: :never)

    cond do
      status == 500 ->
        {status, body |> String.split("\n") |> List.first() |> String.split("at") |> List.first()}

      true ->
        status
    end
  end,
  max_concurrency: 50
)
|> Enum.map(fn {:ok, id} -> id end)
|> Enum.group_by(& &1)
|> Enum.map(fn {k, v} -> {k, Enum.count(v)} end)
|> Enum.into(%{})
|> IO.inspect(IEx.inspect_opts())

Logger.info("Done...")
```

</details>

**Comment by thbar** [comment]
Code:

```elixir
import Ecto.Query

id = "580a574aa3a7292dcfa9d1da"

Transport.Validators.GTFSTransport.validator_name()
|> DB.Dataset.join_from_dataset_to_metadata()
|> where([dataset: d], d.datagouv_id == ^id)
|> preload([:resources, :aom, :region, :communes])
|> select([metadata: rm, dataset: d, multi_validation: mv, resource_history: rh], %{
  dataset: d,
  metadata: rm,
  multi_validation: {mv.id, mv.resource_history_id},
  resource_history: {rh.id, rh.resource_id}
})
|> DB.Repo.all()
|> Enum.map(fn(%{dataset: %{id: d_id}, metadata: %{id: md_id}, multi_validation: mv, resource_history: rh}) ->
  {d_id, md_id, mv, rh}
end)
|> IO.inspect(IEx.inspect_opts)
```

**Comment by thbar** [comment]
Et le retour associé:

```elixir
[
  {3, 48962, {38525, 49351}, {49351, 79889}},
  {3, 48124, {38443, 49276}, {49276, 79876}}
]
```

**Comment by thbar** [comment]
J'ai déployé #2553 pour un correctif temporaire qui enlève une partie de la payload.

Je vois par ailleurs que l'API est gourmande et qu'il est facile de déclencher des erreurs de timeout.

En allant pas trop vite, j'obtiens des 200 pour tous les jeux avec le hotfix sur la production:

```elixir
%{200 => 549}
```

Affaire à suivre pour:
- Rétablir l'output d'origine avec une jointure corrigée
- Mettre un minimum de cache (même à 30 secondes) car on peut faire tomber le site facilement

**Comment by thbar** [comment]
Poke @fchabouis tu as des élément ici !

**Comment by AntoineAugusti** [comment]
Liée à https://github.com/etalab/transport-site/issues/2730
