### ISSUE TITLE
Liens utiles SIRI

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#2756]
Je commence à collecter ici différents types de liens glanés à droite à gauche:
- [La suite de tests d'Ara sous forme de scénarios Cucumber](https://bitbucket.org/enroute-mobi/ara/src/master/features/siri/estimated-time-tables-for-subscription.feature)
- [La suite de tests de siri-xsd](https://bitbucket.org/enroute-mobi/siri-xsd/src/master/spec/fixtures/soap/)
- [Le catalogue d'exemples SIRI de la Norvège](https://enturas.atlassian.net/wiki/spaces/PUBLIC/pages/637370773/SIRI+Examples+Catalogue) (attention pas au même profil)
- [Notre requêteur SIRI](http://transport.data.gouv.fr/tools/siri-querier)

Je complèterai ici, puis j'en dégagerai au final une doc.

**Comment by thbar** [comment]
On peut clôturer pour le moment en attente des prochains trimestres.

**Comment by thbar** [comment]
(je n'ai pas créé de doc mais ça se retrouve facilement dans les issues)

**Comment by AntoineAugusti** [comment]
More links

- https://github.com/SIRI-CEN/SIRI
- https://github.com/entur/profile-examples
