### ISSUE TITLE
Pas de visualisation pour la base IRVE 

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#2766]
Voir https://transport.data.gouv.fr/datasets/fichier-consolide-des-bornes-de-recharge-pour-vehicules-electriques, il serait bien de pouvoir les afficher, de façon à ce qu'un réutilisateur (voir contact via le formulaire PAN) puisse voir dans sa zone les données éventuellement disponibles (avant de tout filtrer et de voir qu'il n'y a pas ce qu'il/elle cherche, par exemple).

<img width="1045" alt="CleanShot 2022-11-10 at 09 25 29@2x" src="https://user-images.githubusercontent.com/10141/201039234-0cbe48d4-a623-4eb4-b95f-c7ae5492e2f4.png">

On voit aussi dans les logs javascript ceci:

<img width="1264" alt="CleanShot 2022-11-10 at 09 25 42@2x" src="https://user-images.githubusercontent.com/10141/201039315-3af4f5fc-e281-459c-bd84-cf5614df602e.png">

**Comment by thbar** [comment]
@etalab/transport-tech c'est déjà connu, ou est-ce une régression liée à la mise en place du CSP, à votre avis ?

**Comment by thbar** [comment]
Idéalement ne cherchez pas à corriger manuellement, qu'on puisse corriger solidement.

Pistes:
- Voir https://github.com/etalab/transport-site/pull/2646, 1h max de refresh
- Mais la consolidation est refaite journalièrement, donc ça veut dire du downtime tous les jours ?
- Peut-être utiliser l'url stable, mais j'aimerais qu'on s'assure que "ce que je télécharge" est la même chose que "ce que je visualise", sinon ça peut être très frustrant en tant que consommateur de la donnée (sauf à alerter explicitement)

**Comment by thbar** [comment]
La visualisation est revenue (partie centrale).

**Comment by fchabouis** [comment]
y'avait peut etre juste temporairement un soucis avec le fichier coté data.gouv

**Comment by AntoineAugusti** [comment]
Question similaire de @cyrilmorin pour la BNLS, [voir Mattermost](https://mattermost.incubateur.net/betagouv/pl/xk38tp5d97bc5y3yrnzbx8eega)

**Comment by thbar** [comment]
Ca a l'air de s'afficher correctement des deux côtés, je clôture pour le moment.
