### ISSUE TITLE
Mettre en place un système de support

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#2767]
L'équipe du PAN peut être sollicitée par différents moyens :
- via le formulaire de contact (qui résulte en un email)
- par des emails directs ou via une liasse d'équipe (contact, déploiement)
- indirectement sur des sujets qui débutent ailleurs (exemple: un message twitter, un commentaire sur data gouv)

On commence à se sentir "en stress" suite aux changements RH (départs / arrivées), ce qui me pousse à proposer une mise en place de système de suivi / ticketing qui serait adapté à notre situation. Sujet abordé en équipe et sur lequel je vais aller faire des tests.

### Outils possibles

- https://front.com
- https://freshdesk.com
- https://crisp.chat (merci @AntoineAugusti) -> retour d'XP par Visio via quelqu'un à venir
- https://zammad.com (via `domaine-support` sur Mattermost)
- https://www.zendesk.fr
- https://helpscout.com
- EDIT: j'en ai d'autres via "beta gouv" toutefois lien que je ne peux pas partager ici

Je vais en parler côté Beta Gouv et voir si d'autres utilisent quelque chose déjà.

### Points d'attention

- Bien coller à notre besoin (voir plus haut, il faudra brainstormer un peu pour vérifier que ça colle)
- Idéalement, ne pas nécessiter de changement dans nos systèmes email (par exemple, certains outils que j'ai testé dans le passé savent via un petit marqueur se faire discrets, sans changer les serveurs ; mais je ne sais pas si ça fonctionnera bien avec notre "boite commune", qui est aujourd'hui une simple redirection et pas une vraie boite)
- Coût acceptable et capacité à scaler un peu dans le temps
- RGPD / hébergement / privacy

**Comment by AntoineAugusti** [comment]
Zammad est utilisé par data.gouv.fr (en self hosted je crois), voir [prix](https://zammad.com/en/pricing)

**Comment by thbar** [comment]
J'ai une visio retour d'XP Crisp avec quelqu'un de beta gouv jeudi prochain.

**Comment by thbar** [comment]
Pour l'instant je pense qu'on a réussi à s'en passer (pose @ChristinaLaumond @cyrilmorin) et je clôture. Je pourrai avancer dessus à nouveau si besoin.
