### ISSUE TITLE
Revoir label "Producteur de la donnée"

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#2772]
cc @etalab/transport-bizdev

Peut-être indiquer plutôt "Diffuseur de la donnée" ?

![image](https://user-images.githubusercontent.com/295709/201107884-6be093e6-c0fb-4119-aa19-2e144a73bb6d.png)

**Comment by ChristinaLaumond** [comment]
Je n'étais pas là pendant votre échange mais ce n'est pas la 1ère fois qu'on nous remonte ce sujet. En effet, souvent le producteur identifié n'est pas le réel producteur mais celui qui la publie / diffuse. "Publieur" serait pas très beau, ok pour "diffuseur" de mon côté.
En revanche, on perdrait complètement l'item producteur du coup c'est ça ?

**Comment by cyrilmorin** [comment]
Pour réflexion : il pourrait être intéressant pour une organisation de pouvoir publier des données pour le compte d'une autre organisation et donc de : 
1. différencier le diffuseur et le producteur 
2. d'associer l'image correspondante au producteur (au sens "commercial" vs au sens data.gouv)

**Comment by AntoineAugusti** [comment]
On peut :

1. Changer le label "Producteur de la donnée" en "Diffuseur de la donnée" partout sur le PAN
2. Changer le label "Producteur de la donnée" en "Diffuseur de la donnée" pour certaines organisations (on utilise leur nom pour les cibler). Le ciblage des organisations se fait avec leur nom, dans un fichier CSV ou dans le code.
3. Ne rien faire et convaincre NAM que ce label correspond à la majorité des cas

Pour NAM, ils indiquent sur chaque JDD une phrase du style suivant (exemple pour [Yégo](https://transport.data.gouv.fr/datasets/arrets-horaires-et-parcours-theoriques-des-reseaux-naq-yeg-nva-m))

> Les données sont diffusées par Nouvelle-Aquitaine Mobilités et produites par [MOBIMACS](https://www.mobi-macs.org/).

## Distinguer producteur et diffuseur

@cyrilmorin Pour distinguer diffuseur et producteur, il faut disposer de l'information de manière structurée. Les infos dont on dispose pour le JDD proviennent de l'API de data.gouv.fr et [ressemblent par exemple à ça](https://www.data.gouv.fr/api/1/datasets/arrets-horaires-et-parcours-theoriques-des-reseaux-naq-yeg-nva-m/). On affiche `organization.name` actuellement.

Si on voulait faire mieux, il faudrait : 
- disposer de l'information dans l'API de data.gouv.fr (pour les JDD publiés là-bas et moissonnés)
- demander aux producteurs d'ajouter des informations structurées, par exemple dans `extras` (mais requiert d'utiliser l'API data.gouv.fr)
- avoir un fichier CSV/YAML de notre côté, maintenu à jour par les bizdevs
- envisager un développement plus conséquent pour stocker ceci dans notre base de données et renseigner ceci dans le backoffice

## Recommendation

Comme le problème semble concerncer peu d'organisations, je recommande **la solution 2.** pour le moment.

On suit déjà ce principe pour la licence mobilités, où on a le nom de la Métropole de Lyon présent dans le code pour écraser la licence (indiquée comme non spécifiée sur data.gouv.fr)

https://github.com/etalab/transport-site/blob/ec61255fd3ac4c3cf1bdfe993969d35847427f02/apps/transport/lib/transport/import_data.ex#L207

---

Qu'en pensez-vous ?

**Comment by AntoineAugusti** [comment]
Changer le label par

> "Donnée publiée par"

proposé par @fchabouis

**Comment by AntoineAugusti** [comment]
Label adapté dans la PR ci-dessous, on pourra étendre la fonctionnalité plus tard.

**Comment by fchabouis** [comment]
"Données publiées par" au pluriel plutôt :)

**Comment by AntoineAugusti** [comment]
@fchabouis C'est au pluriel dans la PR.
