### ISSUE TITLE
Page contribuer BNLC - lien logo renvoie vers une page d'erreur

### ISSUE THREAD

**Issue by cyrilmorin** [etalab/transport-site#2780]
Hello,

Le lien du logo du header "transport.data.gouv.fr" sur la page https://contribuer.transport.data.gouv.fr/ renvoie vers une page d'erreur 
"Page Not found" https://contribuer.transport.data.gouv.fr/transport.data.gouv.fr

Par contre je ne sais pas si c'est le lien qui n'est pas le bon ou la page en question qui pose problème ...

Merci !

**Comment by AntoineAugusti** [comment]
Le dépôt du site web https://contribuer.transport.data.gouv.fr est https://github.com/etalab/transport-community-contributions
