### ISSUE TITLE
Mail automatique "jdd qui disparaisse" - interrogation jdd Ain

### ISSUE THREAD

**Issue by ChristinaLaumond** [etalab/transport-site#2790]
hello, 

Petite interrogation par rapport à ce mail automatique ci-après car on a ce [jdd ](https://transport.data.gouv.fr/datasets/reseau-interurbain-cars-region-ain-01)de référence pour l'AIN toujours référencé sur le PAN. Ou alors on avait un doublon qu'on avait pas repéré avant ? 

Merci pour l'éclairage ! 

Mail : _De : transport.data.gouv.fr <contact@transport.beta.gouv.fr>
Date: dim. 20 nov. 2022 à 01:00
Subject: Jeux de données qui disparaissent
To: <deploiement@transport.beta.gouv.fr>

Bonjour,
Certains jeux de données ont disparus de [data.gouv.fr](http://data.gouv.fr/) :
 * Cars Région Ain : horaires théoriques du réseau de transport  interurbain - https://transport.data.gouv.fr/datasets/cars-region-ain-horaires-theoriques-du-reseau-de-transport-interurbain

Il faut peut être creuser pour savoir si c'est normal._

**Comment by AntoineAugusti** [comment]
Hello,

Ce jeu de données a bien disparu. https://www.data.gouv.fr/fr/datasets/cars-region-ain-horaires-theoriques-du-reseau-de-transport-interurbain/ (l'URL datagouv avec l'ancien slug) est une 404 et ne redirige pas (ce qui serait le cas si on avait eu un changement de slug). Dans notre base de données ce JDD avait l'identifiant datagouv `63569acc24ce645b6139bd80`. L'API ne donne rien [avec cet identifiant](https://www.data.gouv.fr/api/1/datasets/63569acc24ce645b6139bd80/) non plus.

https://www.data.gouv.fr/fr/datasets/reseau-interurbain-cars-region-ain-01/ que vous avez référencé est donc peut-être un ancien doublon ou le JDD qui a remplacé l'ancien.

En tout cas l'identifiant du JDD a changé, ce qui signifie changement de slug, perte des discussions, de l'historisation etc.

**Comment by AntoineAugusti** [comment]
Je pense avoir répondu à ta question, hésite pas à ouvrir à nouveau si ce n'est pas résolu.
