### ISSUE TITLE
problème d'import : EPCI Métropole Européenne de Lille 

### ISSUE THREAD

**Issue by fchabouis** [etalab/transport-site#2795]
Nous avons ce jeu de donnée qui refuse de s'importer : https://transport.data.gouv.fr/datasets/velos-libre-service-lille-vlille-disponibilite-en-temps-reel

En cause, la zone datagouv renvoyée par leur API, qui nous dit que le jeu est rattaché à l'EPCI 245900410 ("fr:epci:245900410@2017-01-01"). Or dans notre base qui vient de ce [fichier](https://unpkg.com/@etalab/decoupage-administratif@2.0.0/data/epci.json), la Métropole Européenne de Lille à le code 200093201.

Je ne sais pas qui a raison, faudrait creuser.

https://www.insee.fr/fr/metadonnees/cog/intercommunalite-metropole/EPCI200093201-metropole-europeenne-de-lille
https://sig.ville.gouv.fr/Territoire/245900410

Ca serait bien aussi que si la zone datagouv n'est pas trouvée dans nos bases, on gère mieux la situation chez nous et que ça ne bloque pas l'import.

**Comment by AntoineAugusti** [comment]
Les données de datagouv semblent erronées voir pour [le SIREN 245900410](https://annuaire-entreprises.data.gouv.fr/entreprise/245900410) et le nouveau [SIREN 200093201](https://annuaire-entreprises.data.gouv.fr/entreprise/200093201).

J'avais pointé des incohérences des données geozones [sur Mattermost](https://mattermost.incubateur.net/betagouv/pl/b4ezbrrq1tn7innwwmtd4b79hw) récemment aussi.

**Comment by AntoineAugusti** [comment]
Réglé en rattachant le JDD à l'AOM de la MEL. https://transport.data.gouv.fr/datasets/velos-libre-service-lille-vlille-disponibilite-en-temps-reel Suffisant ?

**Comment by fchabouis** [comment]
oui très bien pour débloquer l'import :+1:
