### ISSUE TITLE
Vérification de la disponibilité des ressources API et réponse 401

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#2818]
Soulevé par IDFM, [sur leur JDD](https://transport.data.gouv.fr/datasets/horaires-prevus-sur-les-lignes-de-transport-en-commun-dile-de-france-gtfs-datahub).

Considérer que pour les ressources SIRI, une réponse 401 n'est pas une erreur ?

**Comment by thbar** [comment]
Autre idée : avoir une clé privée qui nous permet de faire la vérification en mode authentifié. Je crains qu'on ai des faux positifs sinon...
