### ISSUE TITLE
Validateur GTFS-RT : gérer erreurs de mémoire avec shapes

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#2832]
Suite de #2212 

Actuellement [~3% des validations GTFS-RT](https://github.com/etalab/transport-site/issues/2212#issuecomment-1337096332) n'ont pas pu être effectuée suite à une erreur de mémoire trop importante lors de l'exécution du validateur. Ceci survient quand le fichier `shapes.txt` est trop grand et qu'on essaie de voir si la position des véhicules est trop éloignée des shapes indiquée.

Quand ceci survient, un utilisateur obtient un erreur assez cryptique avec une stacktrace Java. Toutefois le message d'errreur contient "OutOfMemoryError" qui devrait parler à un utilisateur technique.

## Solutions envisagées

- c'est assez rare pour ne rien faire (arrive dans 3% des validations)
- tenter par défaut une analyse avec shapes et si on obtient une erreur de mémoire relancer en excluant l'analyse des shapes
- changer le code pour avoir une heuristique du style "si le fichier `shapes.txt` est > X Mo je ne fais pas l'analyse des shapes" (en regardant les données le GTFS le plus petit GTFS avec une erreur mémoire fait ~25 Mo)
- prendre un chiffre de mémoire au hasard (java heap space) et espérer que ce sera suffisant pour faire passer plus de fichiers
- modifier la validation à la demande en ajoutant une checkbox pour demander d'ignorer l'analyse des shapes par rapport aux vehicle positions

**Reste à définir la piste privilégiée**

**Comment by cyrilmorin** [comment]
@AntoineAugusti comme vu ensemble pour ne pas pénaliser les 97% et si pas trop complexe :
1-adapter le message d'erreur
2- option "tenter par défaut une analyse avec shapes et si on obtient une erreur de mémoire relancer en excluant l'analyse des shapes"
