### ISSUE TITLE
Afficher ressources de type json pour public-transit

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#2841]
Demande [d'IDFM](https://transport.data.gouv.fr/datasets/horaires-prevus-sur-les-lignes-de-transport-en-commun-dile-de-france-gtfs-datahub) : avoir le calculateur d'itinéraire au format `json` visible sur leur page de JDD.

Actuellement on filtre ces ressources pour le type `public-transit`

**Comment by AntoineAugusti** [comment]
Voici le code actuel qui limite les ressources que l'on garde pour le type `public-transit`.

https://github.com/etalab/transport-site/blob/30050a327ce54bfcc145d650094db7c14f2ab929/apps/transport/lib/transport/import_data.ex#L430-L438

Que doit-on faire ? Garder tous les autres types des ressources ? Seulement certains formats ?

**Comment by AntoineAugusti** [comment]
@etalab/transport-bizdev N'hésitez pas à solliciter un dev quand vous aurez défini le comportement attendu !

**Comment by fchabouis** [comment]
Ca sort un peu de notre scope en même temps.

![image](https://user-images.githubusercontent.com/15341118/215047237-ad1aeb8f-f8db-4bff-8b93-07ccc5e25695.png)

Là c'est plus un service (calcul d'itinéraire, etc) que de la donnée, le format n'est pas homogène et la licence n'est pas harmonisée. Ca me choque pas plus que ça qu'on ne l'affiche pas.

**Comment by Miryad3108** [comment]
Je serai d'avis aussi à ne pas l'afficher vu qu'on met beaucoup en avant l'aspect 1 tuile = un/des format.s de données 
Ils ne peuvent pas mettre juste un lien ? 
Je peux reprendre la main et voir avec eux @AntoineAugusti

**Comment by AntoineAugusti** [comment]
@Miryad3108 Faisons ainsi !
