### ISSUE TITLE
Récupérer et afficher la description des ressources

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#2842]
Soulevé par [IDFM](https://www.data.gouv.fr/fr/datasets/horaires-prevus-sur-les-lignes-de-transport-en-commun-dile-de-france-gtfs-datahub/) : de nombreuses ressources ont des descriptions pertinentes mais ce n'est pas une information qu'on récupère/qu'on affiche actuellement.

**Comment by AntoineAugusti** [comment]
On a déjà la description des ressources en base de données en fait, mais ce n'est jamais affiché.

Je pense l'afficher uniquement sur la page "+ détails" des ressources. Voici l'UI que j'ai.

![image](https://user-images.githubusercontent.com/295709/206189564-64f3759b-b7d4-4953-9041-cbbe42942bf0.png)

Je n'afficherais pas cette section pour les ressources se nommant "Export au format ..." provenant d'ODS car leur description ressemble à ceci :

- *Libellé*: libelle[text]
- *Description*: description[text]
- *Fichier*: fichier[text]
- *Publication*: publication[date]

**Comment by cyrilmorin** [comment]
Looks good :) 
Du coup dans "Détails de la ressource" pour un GTFS par exemple on aurait notre texte "généré automatique" avec à la fin l'éventuelle description de la ressource du producteur ?
On peut peut-être mettre un titre genre "Description complémentaire" ?
