### ISSUE TITLE
Impossible de référencer le JDD Couralin - Grand Dax

### ISSUE THREAD

**Issue by cyrilmorin** [etalab/transport-site#2863]
Après plusieurs tentatives, je n'arrive pas à référencer le JDD Grand Dax (pas de souci côté rapprochement de l'AOM à priori)
https://www.data.gouv.fr/fr/datasets/reseau-couralin-grand-dax/

L'erreur :

![image](https://user-images.githubusercontent.com/116101828/208399104-209d9c90-e538-4bf5-b738-14f19651b609.png)

**Comment by AntoineAugusti** [comment]
Hello !

Ce jeu de données avait été supprimé de data.gouv.fr, ce qui a libéré le slug. Il était précédemment présent chez nous, mais marqué comme supprimé.

Le problème survenait dans le backoffice car le `datagouv_id` associé au slug était différent du notre, d'où le conflit. J'ai rétabli ceci à la main.

https://transport.data.gouv.fr/datasets/reseau-couralin-grand-dax
