### ISSUE TITLE
Réduire taille table de metrics

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#2877]
La table `metrics` compte actuellement 780k lignes et a un poids de 187 MB (données et index).

Elle contient le nombre de requêtes par flux présent dans les proxys GBFS et GTFS-RT, en distinguant externe et interne avec un pas de temps à l'heure.

On pourrait réduire le nombre de lignes en gardant seulement un pas de temps à la journée après un temps, par exemple 3 mois (avec cette hypothèse on passerait de ~505k rows à ~22k rows).

**Comment by fchabouis** [comment]
ça me parait être une bonne idée !
