### ISSUE TITLE
Notification d'un jdd supprimé alors que jdd non supprimé 

### ISSUE THREAD

**Issue by ChristinaLaumond** [etalab/transport-site#2887]
hello, 
on a reçu une alerte de suppression de data.gouv pour le jdd LIO Aveyron (mail ci-après) mais pourtant le jdd n'est pas supprimé sur data.gouv : https://www.data.gouv.fr/fr/datasets/gtfs-lio-aveyron/ et c'est bien l'url actuellement référencé sur le PAN : 
<img width="293" alt="image" src="https://user-images.githubusercontent.com/101095139/210253728-af859c43-41ec-40db-9804-0e0b7a7b5ef1.png">

> ---------- Forwarded message ---------
De : transport.data.gouv.fr <contact@transport.beta.gouv.fr>
Date: lun. 2 janv. 2023 à 01:00
Subject: Jeux de données supprimés ou archivés
To: <deploiement@transport.beta.gouv.fr>
Bonjour,
Certains jeux de données ont disparus de [data.gouv.fr](http://data.gouv.fr/) : 
-Réseau interurbain liO - Aveyron - https://transport.data.gouv.fr/datasets/gtfs-lio-aveyron
Certains jeux de données disparus sont réapparus sur [data.gouv.fr](http://data.gouv.fr/) :
-Vélib - https://transport.data.gouv.fr/datasets/velib-velos-et-bornes-disponibilite-temps-reel
Il faut peut être creuser pour savoir si c'est normal.

**Comment by ChristinaLaumond** [comment]
Idem pour 

> ---------- Forwarded message ---------
De : transport.data.gouv.fr <contact@transport.beta.gouv.fr>
Date: dim. 1 janv. 2023 à 01:00
Subject: Jeux de données supprimés ou archivés
To: <deploiement@transport.beta.gouv.fr>


Bonjour,
Certains jeux de données ont disparus de [data.gouv.fr](http://data.gouv.fr/) :
 *Vélib - https://transport.data.gouv.fr/datasets/velib-velos-et-bornes-disponibilite-temps-reel

**Comment by AntoineAugusti** [comment]
Merci, je vais jeter un oeil ! Le code actuel laisse penser que ce serait une erreur temporaire côté API data.gouv.fr mais très étonnant que ça arrive maintenant.

**Comment by ChristinaLaumond** [comment]
Autre exemple du jour : 
<img width="951" alt="image" src="https://user-images.githubusercontent.com/101095139/210340959-00233536-b557-404d-8f80-580f2ab8aa0b.png">
https://transport.data.gouv.fr/datasets/horaires-theoriques-et-temps-reel-du-reseau-ritmo-haguenau-gtfs-gtfs-rt

**Comment by AntoineAugusti** [comment]
@ChristinaLaumond Yep merci, bien vu ! J'ai préparé une PR pour ajouter du logging afin de trouver la source, à défaut d'avoir trouvé la cause pour le moment.

**Comment by AntoineAugusti** [comment]
#2888 est en prod avec du logging, on verra si ça survient à nouveau !

**Comment by AntoineAugusti** [comment]
J'ai remis le réseau "Ritmo" comme actif à la main, normal de ne pas le voir dans le mail demain du coup.

**Comment by AntoineAugusti** [comment]
C'est de retour avec 2 JDD désactivés aujourd'hui. On a [pu collecter des logs](https://github.com/etalab/transport-site/issues/2887) sur la raison (timeout de l'API datagouv).
