### ISSUE TITLE
[Administration] Ajouter colonne Organisation dans le tableau des JDD filtrés

### ISSUE THREAD

**Issue by cyrilmorin** [etalab/transport-site#2891]
Dans l'administration des données et le tableau des jeux de données filtrés

![image](https://user-images.githubusercontent.com/116101828/210346178-e32ce42b-cb08-4933-a44d-b1f18dd1c86c.png)

Est-il possible d'ajouter une colonne "Organisation" après "Dataset" avec comme valeur le nom de l'organisation avec un lien vers data.gouv.fr qui renvoie sur la liste des JDD de l'organisation

Exemple dans la colonne "Organisation" : [Palmbus](https://www.data.gouv.fr/fr/organizations/palmbus/)

En complément d'info, pour certains cas, cette information permet d'identifier une récurrence (moissonnage notamment) ou de vérifier dans data.gouv de potentiels doublons.

Merci !

**Comment by AntoineAugusti** [comment]
@cyrilmorin Hello ! Est-ce que uniquement le nom de l'organisation serait utile dans un premier temps ? On a pas d'information sur le slug de l'organisation ou son ID, ce qui fait qu'on ne peut pas créer une URL vers data.gouv.fr.

Si on veut faire un lien vers la page de l'organisation il faut ajouter une nouvelle colonne dans la table des JDD (ou créer une table liées aux organisations), ce qui demande plus de travail.

On peut accéder à l'organisation depuis le lien data.gouv.fr du JDD (colonne data.gouv.fr)

**Comment by cyrilmorin** [comment]
Hello @AntoineAugusti  

Oui ça suffirait et permettrait déjà de trier et d'identifier plus facilement les "anomalies" et/ou récurrences (ex : organisation qui moissone = n JDD archivés/supprimés) 
Merci !

**Comment by AntoineAugusti** [comment]
@cyrilmorin Il faut aussi que ce soit possible de trier en fonction de l'organisation du coup ?

**Comment by cyrilmorin** [comment]
@AntoineAugusti oui ce serait vraiment utile pour justement voir les organisations présentes plusieurs fois.
Merci
