### ISSUE TITLE
Backoffice : modifier url datagouv

### ISSUE THREAD

**Issue by fchabouis** [etalab/transport-site#2902]
Pour le moment si on modifie une URL d'un dataset dans le BO, on perd tout l'historique du dataset.
Est-ce qu'il serait possible de faire en sorte qu'il ne soit pas perdu ?

**Comment by AntoineAugusti** [comment]
Lié à #1523 ?

On peut modifier l'URL dans le backoffice et ne pas avoir de changement. Tant que le `datagouv_id` est le même c'est bon.

**Comment by fchabouis** [comment]
oui c'est lié, j'aimerais bien aller voir si on peut juste éditer un dataset, changer l'url (et du coup de datagouv_id), et que ça mette à jour le dataset, sans le supprimer. Du coup on garderait le dataset_id et l'historique associé. Mais je sais pas si ce que je raconte à bien du sens, faut que j'aille voir le code associé.

**Comment by AntoineAugusti** [comment]
À mon avis c'est ok pour la partie PAN qui se repose sur `dataset.id` mais les appels à l'API datagouv sont basés sur `datagouv_id` pour réutilisations, commentaires etc et là ça dépend de :
- si l'ancien JDD datagouv existe encore ou si ça a été supprimé 
- si le fonctionnement attendu c'est dans ce cas de faire des appels à l'API datagouv avec plusieurs datagouv IDs et de merger le tout

**Comment by fchabouis** [comment]
Je pensais à ce que ça fasse la même chose qu'actuellement, c'est à dire aller chercher les commentaires, réutilisations, ressources du nouveau datagouv_id. Mais sans changer de dataset_id PAN, ce qui nous permettrait de garder l'historique des ressources en plus.
