### ISSUE TITLE
Réflexion : envoi de notifications lorsqu'une ressource change et qu'elle contient des erreurs

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#2903]
Un ticket pour réfléchir à une nouvelle fonctionnalité : l'envoi de notifications par e-mail aux producteurs lorsque le contenu de leur ressource change et que la validation sur cette nouvelle version contient une erreur.

Hypothèses retenues :

- Validateurs utilisées : GTFS, TableSchema, JSON Schema. On ignore GTFS-RT et GBFS (car données temps réel et qu'il est plus probable que si une erreur survient elle perdure dans le temps)
- Gravité d'erreur :
  - Pour GTFS : niveau `Error` ou `Fatal` uniquements. Exclus : `Information` ou `Warning`
  - Schémas (JSON Schema et TableSchema) : >= 1 erreur
- Destinataires : si on détecte une erreur pour une ressource, on remonte au dataset associé et on utilise les contacts renseignés au [motif de l'expiration des données dans transport-notifications](https://github.com/etalab/transport-notifications/blob/8c56d2ce9975b7a760223d2e9c8f45581532e77a/config.yml#L9)

On enverrait un e-mail du style :

```
Objet : erreur de validation détectée sur $JDD

Bonjour,

Vous venez de mettre à jour la ressource $nom_resource.

Nous avons détecté que cette ressource comportait des erreurs ce qui nuit à sa réutilisation.

Vous pouvez consulter le rapport de validation en question : https://transport.data.gouv.fr/resource/$id

---
Vous pouvez répondre à cet e-mail pour ajuster les notifications que vous recevez ou obtenir de l'aide de notre équipe.
```

## Estimation du nombre de notifications envoyées

Avec les critères ci-dessus, et sur la période (2022-12-01 - 2023-01-05) on aurait eu :

### Par jour
|date|nb_notifications|
|--- | ---|
|2022-12-01 | 6|
|2022-12-02 | 3|
|2022-12-03 | 3|
|2022-12-04 | 4|
|2022-12-05 | 7|
|2022-12-06 | 8|
|2022-12-07 | 5|
|2022-12-08 | 5|
|2022-12-09 | 6|
|2022-12-10 | 3|
|2022-12-11 | 3|
|2022-12-12 | 4|
|2022-12-13 | 5|
|2022-12-14 | 6|
|2022-12-15 | 4|
|2022-12-16 | 5|
|2022-12-17 | 3|
|2022-12-18 | 4|
|2022-12-19 | 6|
|2022-12-20 | 5|
|2022-12-21 | 7|
|2022-12-22 | 4|
|2022-12-23 | 5|
|2022-12-24 | 5|
|2022-12-25 | 6|
|2022-12-26 | 6|
|2022-12-27 | 4|
|2022-12-28 | 4|
|2022-12-29 | 4|
|2022-12-30 | 5|
|2022-12-31 | 2|
|2023-01-02 | 2|
|2023-01-03 | 6|
|2023-01-04 | 7|
|2023-01-05 | 14|

### Par validateur

|Validateur|nb|
|--- | ---|
|EXJSONSchema | 37|
|GTFS transport-validator | 73|
|validata-api | 66|

### Par ressource

Je masque tous les résultats (25 ressources) où il n'y a qu'une erreur pour la ressource sur la période.

|resource_id|nb_erreurs|
|--- | ---|
|79011 | 45|
|56171 | 34|
|75718 | 32|
|78955 | 17|
|38859 | 11|
|78975 | 9|

Pour [la resource 79011](https://transport.data.gouv.fr/resources/79011) on aurait donc envoyé 45 e-mails sur la période. Ceci s'explique par le fait que cette ressource GTFS est mise à jour de manière automatique et que la génération de ce fichier produisait des erreurs fatales durant cette période.

## Limitations actuelles

- Potentiel de "spam" quand une ressource est mise à jour régulièrement, automatiquement et qu'elle contient des erreurs
- Connaissance des destinataires partielle (réutilisation de contacts "expiration", liste non exhaustive)
- La notification arrivera uniquement au moment où on aura pu historiser et valider la ressource (entre 1h et 6h après le changement effectif de la ressource)
- La notification est sur la base d'une ressource : si 1 JDD contient 2 ressources et que ces 2 ressources sont modifiées ~en même temps et ont des erreurs, on envoie potentiellement 2 e-mails (on pourrait surement au moins grouper par JDD, peut-être pas encore par destinataire)

## Questions

Quels sont les ajustements à effectuer pour que cette fonctionnalité soit développée et utile ?

**Comment by AntoineAugusti** [comment]
Un envoi max tous les 15 jours

**Comment by ChristinaLaumond** [comment]
Re Antoine, 

VOilà ce qu'on te propose comme mail avec Cyril :

**Comment by AntoineAugusti** [comment]
@etalab/transport-bizdev Merci 🙏 Je vous tiens au jus

**Comment by AntoineAugusti** [comment]
Je ferme car 2 PRs ont été mergées
