### ISSUE TITLE
[Validation GTFS] Aucune info sur Avertissement "agency_id non renseignée"

### ISSUE THREAD

**Issue by cyrilmorin** [etalab/transport-site#2905]
Hello,

Lorsque l'id d'une agency n'est pas renseignée le rapport de validation ne permet pas de comprendre l'erreur facilement pour les producteurs.
Cela est peut-être le cas pour d'autres valeurs "obligatoires" non renseignée ?

Ex : pour le [rapport d'un jeu test eurostar](https://transport.data.gouv.fr/validation/55832?issue_type=MissingId&token=fc42bc0f-5cd0-4e0d-9e7b-42cd6d5f8c8c) : 

![image](https://user-images.githubusercontent.com/116101828/210797396-19a4727f-0767-4819-a001-8cb2add6d623.png)

**Comment by AntoineAugusti** [comment]
@cyrilmorin C'est corrigé en prod, avec une meilleure interface (voir PR).

PS : 💡 on n'a pas accès aux fichiers déposés sur la validation à la demande (ils sont immédiatement supprimés), hésite pas à mettre le fichier dans l'issue quand tu ouvres un bug 💅
