### ISSUE TITLE
Réponse invalide du serveur api-data.cacl-guyane.fr empêchant l'historisation de données

### ISSUE THREAD

**Issue by cyrilmorin** [etalab/transport-site#2910]
Hello,

Pour le JDD [Agglobus](https://transport.data.gouv.fr/datasets/agence-agglobus), les dates de validité du rapport de validation manuel ne sont pas les mêmes que les détails de la ressource pour le même fichier GTFS

[Détails de la ressource](https://transport.data.gouv.fr/resources/66828)
![image](https://user-images.githubusercontent.com/116101828/211363269-cf4c7948-081b-4143-9433-24afcf94114d.png)

[Rapport de validation ](https://transport.data.gouv.fr/validation/56790?issue_type=IdNotAscii&token=cbdf7522-08c4-4738-88fa-6775aea7d4fb)
![image](https://user-images.githubusercontent.com/116101828/211362375-2d80e166-63f1-4605-a04b-de9074f35ca7.png)

Fichier GTFS en question
[AGGLOBUS-PERI-URBAIN_gtfs_2022-05-20_03-35-08.zip](https://github.com/etalab/transport-site/files/10375284/AGGLOBUS-PERI-URBAIN_gtfs_2022-05-20_03-35-08.zip)

**Comment by AntoineAugusti** [comment]
@cyrilmorin À première vue ce serait plutôt un problème au niveau de l'historisation lié au GTFS diffusé, je regarde.

**Comment by AntoineAugusti** [comment]
@cyrilmorin En regardant en détail la réponse que l'on reçoit, on obtient une erreur HTTP 550 qui correspond à une erreur serveur. Le serveur diffusant leurs données à l'adresse refuse de nous répondre. En conséquence on historise pas leur GTFS.

Le détail de la réponse et de la requête.

```
%HTTPoison.Response{
  status_code: 550,
  body: "Data Analyzer is inactive",
  headers: [
    {"Content-Type", "text/html; charset=utf-8"},
    {"Content-Length", "25"},
    {"Connection", "keep-alive"},
    {"Date", "Tue, 10 Jan 2023 08:58:25 GMT"},
    {"X-Powered-By", "Express"},
    {"Access-Control-Allow-Origin", "*"},
    {"Access-Control-Expose-Headers",
     "Elements-Count,Elements-Total-Count,results-count,total-results-count"},
    {"ETag", "W/\"19-UccgvIDtSoT70N8xof7EFwoFYME\""},
    {"Vary", "Accept-Encoding"},
    {"X-Cache", "Error from cloudfront"},
    {"Via",
     "1.1 1ccafca48442bcbc69901f59de3acd48.cloudfront.net (CloudFront)"},
    {"X-Amz-Cf-Pop", "MRS52-P1"},
    {"X-Amz-Cf-Id",
     "UITFSjIbpbDrHOSwUyFLllTFx3VKdaYOfunHlfHO0B0ap8XQPYo-3A=="}
  ],
  request: %HTTPoison.Request{
    method: :get,
    url: "https://api-data.cacl-guyane.fr/v1/gtfs-agglobus-agency/!sourcefiles",
    headers: [],
    body: "",
    params: %{},
    options: [follow_redirect: true]
  }
}
```

Peux-tu contacter ce réseau et leur prestataire technique pour leur transmettre ces éléments et demander s'ils ont des filtres qui empêchent le téléchargement de données en fonction de certains critères ?

N'hésite pas à mettre tech@transport.beta.gouv.fr en copie

**Comment by cyrilmorin** [comment]
@AntoineAugusti  c'est fait !

**Comment by AntoineAugusti** [comment]
La requête que l'on fait

```
GET /v1/gtfs-agglobus-agency/%21sourcefiles HTTP/1.1
Host: api-data.cacl-guyane.fr
User-Agent: hackney/1.18.1
```

**Comment by AntoineAugusti** [comment]
Un correctif a déjà été déployé par le producteur sur le code de son serveur, voir e-mail ayant comme objet "[Agglobus - CACCL Guyanne] Erreur HTTP 550 sur l'appel de transport.data.gouv.fr"
