### ISSUE TITLE
Question sur 1 AOM "rapprochée" / intégrée dans une autre qui ne devrait a priori pas 

### ISSUE THREAD

**Issue by ChristinaLaumond** [etalab/transport-site#2937]
Hello, 

Je me demande pourquoi l'[AOM CA d'Arles-Crau-Camargue-Montagnette est "rapprochée" / "intégrée" dans l'AOM Aix-Marseille](https://transport.data.gouv.fr/datasets/aom/63) ? 
<img width="699" alt="image" src="https://user-images.githubusercontent.com/101095139/213428688-7a853711-4b90-4ac1-a267-57f07944808c.png">
alors que cette AOM publie bien son [jeu de données de manière indépendante](https://transport.data.gouv.fr/datasets/reseau-envia) mais je n'ai pas l'impression qu'il soit publié dans [l'agrégat](https://transport.data.gouv.fr/datasets/reseaux-de-transports-en-commun-de-la-metropole-daix-marseille-provence-et-des-bouches-du-rhone/) global tel que représenté sur la carte ? 

Merci :)

**Comment by AntoineAugusti** [comment]
👋 

C'est parce qu'on a une configuration en base de données qui dit que cette AOM (id = 63), on indique que son `parent_dataset_id` est le 146, soit [l'aggrégat](https://transport.data.gouv.fr/datasets/146). Je pense que dans le passé c'était contenu dedans, mais ça a changé.

On doit changer à la main en base de données actuellement pour ce cas.

Voici les autres AOMs pour lesquelles on rattache un "parent dataset" et qui ont pourtant au moins un dataset associé à cette AOM

|url|nom AOM|
|--- | ---|
|https://transport.data.gouv.fr/datasets/aom/108 | CA du Pays de Saint Malo Agglomération|
|https://transport.data.gouv.fr/datasets/aom/111 | Métropole Rouen Normandie|
|https://transport.data.gouv.fr/datasets/aom/113 | CA Quimper Bretagne Occidentale|
|https://transport.data.gouv.fr/datasets/aom/115 | Rennes Métropole|
|https://transport.data.gouv.fr/datasets/aom/116 | CA Saint-Brieuc Armor Agglomération|
|https://transport.data.gouv.fr/datasets/aom/119 | Orléans Métropole|
|https://transport.data.gouv.fr/datasets/aom/132 | CA Agglo du Pays de Dreux|
|https://transport.data.gouv.fr/datasets/aom/135 | CA Lisieux Normandie|
|https://transport.data.gouv.fr/datasets/aom/138 | CA Montargoise et Rives du Loing (AME)|
|https://transport.data.gouv.fr/datasets/aom/142 | CA Golfe du Morbihan - Vannes Agglomération|
|https://transport.data.gouv.fr/datasets/aom/146 | CA Fougères Agglomération|
|https://transport.data.gouv.fr/datasets/aom/184 | CA Seine-Eure|
|https://transport.data.gouv.fr/datasets/aom/189 | CA Caux Seine Agglo|
|https://transport.data.gouv.fr/datasets/aom/20 | CA Lorient Agglomération|
|https://transport.data.gouv.fr/datasets/aom/21 | Le Havre Seine Métropole|
|https://transport.data.gouv.fr/datasets/aom/216 | CA Territoires Vendômois|
|https://transport.data.gouv.fr/datasets/aom/227 | CA Lamballe Terre et Mer|
|https://transport.data.gouv.fr/datasets/aom/230 | CC du Pays d'Issoudun|
|https://transport.data.gouv.fr/datasets/aom/250 | CA Guingamp-Paimpol Agglomération de l'Armor à l'Argoat|
|https://transport.data.gouv.fr/datasets/aom/35 | CA Châteauroux Métropole|
|https://transport.data.gouv.fr/datasets/aom/36 | CA du Cotentin|
|https://transport.data.gouv.fr/datasets/aom/46 | CU Caen la Mer|
|https://transport.data.gouv.fr/datasets/aom/47 | Brest Métropole|
|https://transport.data.gouv.fr/datasets/aom/50 | SIVOTU|
|https://transport.data.gouv.fr/datasets/aom/59 | CA de Blois ''Agglopolys''|
|https://transport.data.gouv.fr/datasets/aom/63 | CA d'Arles-Crau-Camargue-Montagnette|
|https://transport.data.gouv.fr/datasets/aom/85 | CA Montélimar Agglomération|
|https://transport.data.gouv.fr/datasets/aom/9 | CA Montluçon Communauté|

**Comment by AntoineAugusti** [comment]
Voir issues précédentes parlant de cette fonctionnalité https://github.com/etalab/transport-site/issues/2820 https://github.com/etalab/transport-site/issues/2460

**Comment by AntoineAugusti** [comment]
Le tableau partagé précédemment dans #2460 actualisé

|aom_id|aom_nom|parent_dataset_custom_title|dataset_id|dataset_url|
|--- | --- | --- | --- | ---|
|146 | CA Fougères Agglomération | Agrégat de réseaux urbains et interurbains de Bretagne | 38 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-transports-publics-en-bretagne-mobibreizh-gtfs|
|148 | CA Concarneau Cornouaille Agglomération | Agrégat de réseaux urbains et interurbains de Bretagne | 38 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-transports-publics-en-bretagne-mobibreizh-gtfs|
|20 | CA Lorient Agglomération | Agrégat de réseaux urbains et interurbains de Bretagne | 38 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-transports-publics-en-bretagne-mobibreizh-gtfs|
|47 | Brest Métropole | Agrégat de réseaux urbains et interurbains de Bretagne | 38 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-transports-publics-en-bretagne-mobibreizh-gtfs|
|133 | CA Lannion-Trégor Communauté | Agrégat de réseaux urbains et interurbains de Bretagne | 38 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-transports-publics-en-bretagne-mobibreizh-gtfs|
|113 | CA Quimper Bretagne Occidentale | Agrégat de réseaux urbains et interurbains de Bretagne | 38 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-transports-publics-en-bretagne-mobibreizh-gtfs|
|142 | CA Golfe du Morbihan - Vannes Agglomération | Agrégat de réseaux urbains et interurbains de Bretagne | 38 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-transports-publics-en-bretagne-mobibreizh-gtfs|
|238 | CA Quimperlé Communauté | Agrégat de réseaux urbains et interurbains de Bretagne | 38 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-transports-publics-en-bretagne-mobibreizh-gtfs|
|219 | CC Pontivy Communauté | Agrégat de réseaux urbains et interurbains de Bretagne | 38 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-transports-publics-en-bretagne-mobibreizh-gtfs|
|250 | CA Guingamp-Paimpol Agglomération de l'Armor à l'Argoat | Agrégat de réseaux urbains et interurbains de Bretagne | 38 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-transports-publics-en-bretagne-mobibreizh-gtfs|
|310 | CC Auray Quiberon Terre Atlantique | Agrégat de réseaux urbains et interurbains de Bretagne | 38 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-transports-publics-en-bretagne-mobibreizh-gtfs|
|108 | CA du Pays de Saint Malo Agglomération | Agrégat de réseaux urbains et interurbains de Bretagne | 38 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-transports-publics-en-bretagne-mobibreizh-gtfs|
|115 | Rennes Métropole | Agrégat de réseaux urbains et interurbains de Bretagne | 38 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-transports-publics-en-bretagne-mobibreizh-gtfs|
|139 | CA Morlaix Communauté | Agrégat de réseaux urbains et interurbains de Bretagne | 38 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-transports-publics-en-bretagne-mobibreizh-gtfs|
|116 | CA Saint-Brieuc Armor Agglomération | Agrégat de réseaux urbains et interurbains de Bretagne | 38 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-transports-publics-en-bretagne-mobibreizh-gtfs|
|227 | CA Lamballe Terre et Mer | Agrégat de réseaux urbains et interurbains de Bretagne | 38 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-transports-publics-en-bretagne-mobibreizh-gtfs|
|63 | CA d'Arles-Crau-Camargue-Montagnette | Agrégat de réseaux urbains et interurbains de la Métropole Aix-Marseille | 146 | https://transport.data.gouv.fr/datasets/reseaux-de-transports-en-commun-de-la-metropole-daix-marseille-provence-et-des-bouches-du-rhone|
|82 | CA Moulins Communauté | Agrégat de réseaux urbains et interurbains de la région Auvergne-Rhône-Alpes | 732 | https://transport.data.gouv.fr/datasets/agregat-oura|
|9 | CA Montluçon Communauté | Agrégat de réseaux urbains et interurbains de la région Auvergne-Rhône-Alpes | 732 | https://transport.data.gouv.fr/datasets/agregat-oura|
|164 | CA du Bassin d'Aurillac | Agrégat de réseaux urbains et interurbains de la région Auvergne-Rhône-Alpes | 732 | https://transport.data.gouv.fr/datasets/agregat-oura|
|85 | CA Montélimar Agglomération | Agrégat de réseaux urbains et interurbains de la région Auvergne-Rhône-Alpes | 732 | https://transport.data.gouv.fr/datasets/agregat-oura|
|127 | CA Riom Limagne et Volcans | Agrégat de réseaux urbains et interurbains de la région Auvergne-Rhône-Alpes | 732 | https://transport.data.gouv.fr/datasets/agregat-oura|
|124 | Syndicat mixte des transports urbains du bassin thiernois | Agrégat de réseaux urbains et interurbains de la région Auvergne-Rhône-Alpes | 732 | https://transport.data.gouv.fr/datasets/agregat-oura|
|167 | CA du Puy-en-Velay | Agrégat de réseaux urbains et interurbains de la région Auvergne-Rhône-Alpes | 732 | https://transport.data.gouv.fr/datasets/agregat-oura|
|230 | CC du Pays d'Issoudun | Agrégat de réseaux urbains et interurbains de la région Centre-Val-de-Loire | 338 | https://transport.data.gouv.fr/datasets/arrets-itineraires-et-horaires-theoriques-des-reseaux-de-transport-des-membres-de-jvmalin|
|132 | CA Agglo du Pays de Dreux | Agrégat de réseaux urbains et interurbains de la région Centre-Val-de-Loire | 338 | https://transport.data.gouv.fr/datasets/arrets-itineraires-et-horaires-theoriques-des-reseaux-de-transport-des-membres-de-jvmalin|
|50 | SIVOTU | Agrégat de réseaux urbains et interurbains de la région Centre-Val-de-Loire | 338 | https://transport.data.gouv.fr/datasets/arrets-itineraires-et-horaires-theoriques-des-reseaux-de-transport-des-membres-de-jvmalin|
|37 | CA Chartres Métropole | Agrégat de réseaux urbains et interurbains de la région Centre-Val-de-Loire | 338 | https://transport.data.gouv.fr/datasets/arrets-itineraires-et-horaires-theoriques-des-reseaux-de-transport-des-membres-de-jvmalin|
|59 | CA de Blois ''Agglopolys'' | Agrégat de réseaux urbains et interurbains de la région Centre-Val-de-Loire | 338 | https://transport.data.gouv.fr/datasets/arrets-itineraires-et-horaires-theoriques-des-reseaux-de-transport-des-membres-de-jvmalin|
|35 | CA Châteauroux Métropole | Agrégat de réseaux urbains et interurbains de la région Centre-Val-de-Loire | 338 | https://transport.data.gouv.fr/datasets/arrets-itineraires-et-horaires-theoriques-des-reseaux-de-transport-des-membres-de-jvmalin|
|119 | Orléans Métropole | Agrégat de réseaux urbains et interurbains de la région Centre-Val-de-Loire | 338 | https://transport.data.gouv.fr/datasets/arrets-itineraires-et-horaires-theoriques-des-reseaux-de-transport-des-membres-de-jvmalin|
|138 | CA Montargoise et Rives du Loing (AME) | Agrégat de réseaux urbains et interurbains de la région Centre-Val-de-Loire | 338 | https://transport.data.gouv.fr/datasets/arrets-itineraires-et-horaires-theoriques-des-reseaux-de-transport-des-membres-de-jvmalin|
|216 | CA Territoires Vendômois | Agrégat de réseaux urbains et interurbains de la région Centre-Val-de-Loire | 338 | https://transport.data.gouv.fr/datasets/arrets-itineraires-et-horaires-theoriques-des-reseaux-de-transport-des-membres-de-jvmalin|
|32 | CA Creil Sud Oise | Agrégat de réseaux urbains et interurbains de l'Oise (60) | 506 | https://transport.data.gouv.fr/datasets/arrets-horaires-et-parcours-theoriques-gtfs-des-differents-reseaux-de-transport-membres-du-synd3-1|
|200 | CC de l'Aire Cantilienne | Agrégat de réseaux urbains et interurbains de l'Oise (60) | 506 | https://transport.data.gouv.fr/datasets/arrets-horaires-et-parcours-theoriques-gtfs-des-differents-reseaux-de-transport-membres-du-synd3-1|
|196 | CC des Pays d'Oise et d'Halatte | Agrégat de réseaux urbains et interurbains de l'Oise (60) | 506 | https://transport.data.gouv.fr/datasets/arrets-horaires-et-parcours-theoriques-gtfs-des-differents-reseaux-de-transport-membres-du-synd3-1|
|186 | CA de la Région de Compiègne et de la Basse Automne | Agrégat de réseaux urbains et interurbains de l'Oise (60) | 506 | https://transport.data.gouv.fr/datasets/arrets-horaires-et-parcours-theoriques-gtfs-des-differents-reseaux-de-transport-membres-du-synd3-1|
|211 | CC des Sablons | Agrégat de réseaux urbains et interurbains de l'Oise (60) | 506 | https://transport.data.gouv.fr/datasets/arrets-horaires-et-parcours-theoriques-gtfs-des-differents-reseaux-de-transport-membres-du-synd3-1|
|56 | CA du Beauvaisis | Agrégat de réseaux urbains et interurbains de l'Oise (60) | 506 | https://transport.data.gouv.fr/datasets/arrets-horaires-et-parcours-theoriques-gtfs-des-differents-reseaux-de-transport-membres-du-synd3-1|
|290 | CC du Clermontois | Agrégat de réseaux urbains et interurbains de l'Oise (60) | 506 | https://transport.data.gouv.fr/datasets/arrets-horaires-et-parcours-theoriques-gtfs-des-differents-reseaux-de-transport-membres-du-synd3-1|
|189 | CA Caux Seine Agglo | Agrégat de réseaux urbains et interurbains de Normandie | 176 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-des-reseaux-de-transport-public-normands|
|197 | CA Flers Agglo | Agrégat de réseaux urbains et interurbains de Normandie | 176 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-des-reseaux-de-transport-public-normands|
|111 | Métropole Rouen Normandie | Agrégat de réseaux urbains et interurbains de Normandie | 176 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-des-reseaux-de-transport-public-normands|
|36 | CA du Cotentin | Agrégat de réseaux urbains et interurbains de Normandie | 176 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-des-reseaux-de-transport-public-normands|
|44 | CA Evreux Portes de Normandie | Agrégat de réseaux urbains et interurbains de Normandie | 176 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-des-reseaux-de-transport-public-normands|
|184 | CA Seine-Eure | Agrégat de réseaux urbains et interurbains de Normandie | 176 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-des-reseaux-de-transport-public-normands|
|134 | CA de la Région Dieppoise | Agrégat de réseaux urbains et interurbains de Normandie | 176 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-des-reseaux-de-transport-public-normands|
|128 | CA Saint-Lô Agglo | Agrégat de réseaux urbains et interurbains de Normandie | 176 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-des-reseaux-de-transport-public-normands|
|21 | Le Havre Seine Métropole | Agrégat de réseaux urbains et interurbains de Normandie | 176 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-des-reseaux-de-transport-public-normands|
|46 | CU Caen la Mer | Agrégat de réseaux urbains et interurbains de Normandie | 176 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-des-reseaux-de-transport-public-normands|
|131 | CA Fécamp Caux Littoral Agglomération | Agrégat de réseaux urbains et interurbains de Normandie | 176 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-des-reseaux-de-transport-public-normands|
|217 | CA Seine Normandie Agglomération | Agrégat de réseaux urbains et interurbains de Normandie | 176 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-des-reseaux-de-transport-public-normands|
|208 | SIVU transport urbain Bayeux et communes associées | Agrégat de réseaux urbains et interurbains de Normandie | 176 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-des-reseaux-de-transport-public-normands|
|311 | CU d'Alençon | Agrégat de réseaux urbains et interurbains de Normandie | 176 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-des-reseaux-de-transport-public-normands|
|335 | CA Mont-Saint-Michel-Normandie | Agrégat de réseaux urbains et interurbains de Normandie | 176 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-des-reseaux-de-transport-public-normands|
|135 | CA Lisieux Normandie | Agrégat de réseaux urbains et interurbains de Normandie | 176 | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-des-reseaux-de-transport-public-normands|
|105 | CA Saumur Val de Loire | Agrégat des réseaux urbains et interurbains de la Région Pays de la Loire | 787 | https://transport.data.gouv.fr/datasets/arrets-horaires-et-circuits-des-lignes-de-transports-en-commun-en-pays-de-la-loire-gtfs-destineo-reseaux-aom-aleop-1|

**Comment by AntoineAugusti** [comment]
@etalab/transport-bizdev Hello, ce sujet est-il toujours d'actualité ?

**Comment by AntoineAugusti** [comment]
@etalab/transport-bizdev Ping 👼

**Comment by Miryad3108** [comment]
Merci du rappel @AntoineAugusti 
J'en parlerai avec @cyrilmorin et @Benoit-MINT

**Comment by cyrilmorin** [comment]
Hello @AntoineAugusti @Miryad3108 

La façon de faire apparaître les territoires avec le parent_dataset_id "en dur" me semble impossible à maintenir et la volonté de définir des territoires proprement allait dans ce sens :) (même si j'ai bien compris que c'était un gros chantier !)

Il existe dorénavant la possibilité de mettre plusieurs AOM pour un dataset et donc un agrégat.
Il existe donc des AOM qui potentiellement ont 2 datasets associés (via le champ "Représentant légaux")

J'imagine qu'à ce jour les AOM des cartes sont hérités de l'unique AOM du dataset comme avant et non pas du champ "Représentant légaux"

Peux-tu nous dire si ce parent_dataset_id  ne pourrait dorénavant pas être hérité des "représentants légaux" ce qui correspondrait sans artifice à ce qui est renseigné dans le BO ?

On pourrait donc avoir 1 parent_dataset_id dès le 2ème dataset associé à l'AOM "x"

A dispo pour en parler

Merci !

**Comment by AntoineAugusti** [comment]
@cyrilmorin Une liste des AOMs qui ont un "parent dataset" actuellement, et le JDD en question.

|ID AOM|Nom AOM|Nom JDD|URL|
|--- | --- | --- | ---|
|116 | CA Saint-Brieuc Armor Agglomération | Agrégat de réseaux urbains et interurbains de Bretagne | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-transports-publics-en-bretagne-mobibreizh-gtfs|
|20 | CA Lorient Agglomération | Agrégat de réseaux urbains et interurbains de Bretagne | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-transports-publics-en-bretagne-mobibreizh-gtfs|
|113 | CA Quimper Bretagne Occidentale | Agrégat de réseaux urbains et interurbains de Bretagne | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-transports-publics-en-bretagne-mobibreizh-gtfs|
|250 | CA Guingamp-Paimpol Agglomération de l'Armor à l'Argoat | Agrégat de réseaux urbains et interurbains de Bretagne | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-transports-publics-en-bretagne-mobibreizh-gtfs|
|219 | CC Pontivy Communauté | Agrégat de réseaux urbains et interurbains de Bretagne | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-transports-publics-en-bretagne-mobibreizh-gtfs|
|142 | CA Golfe du Morbihan - Vannes Agglomération | Agrégat de réseaux urbains et interurbains de Bretagne | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-transports-publics-en-bretagne-mobibreizh-gtfs|
|227 | CA Lamballe Terre et Mer | Agrégat de réseaux urbains et interurbains de Bretagne | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-transports-publics-en-bretagne-mobibreizh-gtfs|
|133 | CA Lannion-Trégor Communauté | Agrégat de réseaux urbains et interurbains de Bretagne | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-transports-publics-en-bretagne-mobibreizh-gtfs|
|310 | CC Auray Quiberon Terre Atlantique | Agrégat de réseaux urbains et interurbains de Bretagne | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-transports-publics-en-bretagne-mobibreizh-gtfs|
|108 | CA du Pays de Saint Malo Agglomération | Agrégat de réseaux urbains et interurbains de Bretagne | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-transports-publics-en-bretagne-mobibreizh-gtfs|
|148 | CA Concarneau Cornouaille Agglomération | Agrégat de réseaux urbains et interurbains de Bretagne | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-transports-publics-en-bretagne-mobibreizh-gtfs|
|146 | CA Fougères Agglomération | Agrégat de réseaux urbains et interurbains de Bretagne | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-transports-publics-en-bretagne-mobibreizh-gtfs|
|139 | CA Morlaix Communauté | Agrégat de réseaux urbains et interurbains de Bretagne | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-transports-publics-en-bretagne-mobibreizh-gtfs|
|115 | Rennes Métropole | Agrégat de réseaux urbains et interurbains de Bretagne | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-transports-publics-en-bretagne-mobibreizh-gtfs|
|238 | CA Quimperlé Communauté | Agrégat de réseaux urbains et interurbains de Bretagne | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-transports-publics-en-bretagne-mobibreizh-gtfs|
|47 | Brest Métropole | Agrégat de réseaux urbains et interurbains de Bretagne | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-transports-publics-en-bretagne-mobibreizh-gtfs|
|63 | CA d'Arles-Crau-Camargue-Montagnette | Agrégat de réseaux urbains et interurbains de la Métropole Aix-Marseille | https://transport.data.gouv.fr/datasets/reseaux-de-transports-en-commun-de-la-metropole-daix-marseille-provence-et-des-bouches-du-rhone|
|167 | CA du Puy-en-Velay | Agrégat de réseaux urbains et interurbains de la région Auvergne-Rhône-Alpes | https://transport.data.gouv.fr/datasets/agregat-oura|
|164 | CA du Bassin d'Aurillac | Agrégat de réseaux urbains et interurbains de la région Auvergne-Rhône-Alpes | https://transport.data.gouv.fr/datasets/agregat-oura|
|82 | CA Moulins Communauté | Agrégat de réseaux urbains et interurbains de la région Auvergne-Rhône-Alpes | https://transport.data.gouv.fr/datasets/agregat-oura|
|127 | CA Riom Limagne et Volcans | Agrégat de réseaux urbains et interurbains de la région Auvergne-Rhône-Alpes | https://transport.data.gouv.fr/datasets/agregat-oura|
|9 | CA Montluçon Communauté | Agrégat de réseaux urbains et interurbains de la région Auvergne-Rhône-Alpes | https://transport.data.gouv.fr/datasets/agregat-oura|
|85 | CA Montélimar Agglomération | Agrégat de réseaux urbains et interurbains de la région Auvergne-Rhône-Alpes | https://transport.data.gouv.fr/datasets/agregat-oura|
|124 | Syndicat mixte des transports urbains du bassin thiernois | Agrégat de réseaux urbains et interurbains de la région Auvergne-Rhône-Alpes | https://transport.data.gouv.fr/datasets/agregat-oura|
|50 | SIVOTU | Agrégat de réseaux urbains et interurbains de la région Centre-Val-de-Loire | https://transport.data.gouv.fr/datasets/arrets-itineraires-et-horaires-theoriques-des-reseaux-de-transport-des-membres-de-jvmalin|
|216 | CA Territoires Vendômois | Agrégat de réseaux urbains et interurbains de la région Centre-Val-de-Loire | https://transport.data.gouv.fr/datasets/arrets-itineraires-et-horaires-theoriques-des-reseaux-de-transport-des-membres-de-jvmalin|
|230 | CC du Pays d'Issoudun | Agrégat de réseaux urbains et interurbains de la région Centre-Val-de-Loire | https://transport.data.gouv.fr/datasets/arrets-itineraires-et-horaires-theoriques-des-reseaux-de-transport-des-membres-de-jvmalin|
|37 | CA Chartres Métropole | Agrégat de réseaux urbains et interurbains de la région Centre-Val-de-Loire | https://transport.data.gouv.fr/datasets/arrets-itineraires-et-horaires-theoriques-des-reseaux-de-transport-des-membres-de-jvmalin|
|59 | CA de Blois ''Agglopolys'' | Agrégat de réseaux urbains et interurbains de la région Centre-Val-de-Loire | https://transport.data.gouv.fr/datasets/arrets-itineraires-et-horaires-theoriques-des-reseaux-de-transport-des-membres-de-jvmalin|
|35 | CA Châteauroux Métropole | Agrégat de réseaux urbains et interurbains de la région Centre-Val-de-Loire | https://transport.data.gouv.fr/datasets/arrets-itineraires-et-horaires-theoriques-des-reseaux-de-transport-des-membres-de-jvmalin|
|138 | CA Montargoise et Rives du Loing (AME) | Agrégat de réseaux urbains et interurbains de la région Centre-Val-de-Loire | https://transport.data.gouv.fr/datasets/arrets-itineraires-et-horaires-theoriques-des-reseaux-de-transport-des-membres-de-jvmalin|
|132 | CA Agglo du Pays de Dreux | Agrégat de réseaux urbains et interurbains de la région Centre-Val-de-Loire | https://transport.data.gouv.fr/datasets/arrets-itineraires-et-horaires-theoriques-des-reseaux-de-transport-des-membres-de-jvmalin|
|119 | Orléans Métropole | Agrégat de réseaux urbains et interurbains de la région Centre-Val-de-Loire | https://transport.data.gouv.fr/datasets/arrets-itineraires-et-horaires-theoriques-des-reseaux-de-transport-des-membres-de-jvmalin|
|189 | CA Caux Seine Agglo | Agrégat de réseaux urbains et interurbains de Normandie | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-des-reseaux-de-transport-public-normands|
|335 | CA Mont-Saint-Michel-Normandie | Agrégat de réseaux urbains et interurbains de Normandie | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-des-reseaux-de-transport-public-normands|
|217 | CA Seine Normandie Agglomération | Agrégat de réseaux urbains et interurbains de Normandie | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-des-reseaux-de-transport-public-normands|
|131 | CA Fécamp Caux Littoral Agglomération | Agrégat de réseaux urbains et interurbains de Normandie | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-des-reseaux-de-transport-public-normands|
|46 | CU Caen la Mer | Agrégat de réseaux urbains et interurbains de Normandie | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-des-reseaux-de-transport-public-normands|
|21 | Le Havre Seine Métropole | Agrégat de réseaux urbains et interurbains de Normandie | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-des-reseaux-de-transport-public-normands|
|134 | CA de la Région Dieppoise | Agrégat de réseaux urbains et interurbains de Normandie | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-des-reseaux-de-transport-public-normands|
|184 | CA Seine-Eure | Agrégat de réseaux urbains et interurbains de Normandie | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-des-reseaux-de-transport-public-normands|
|36 | CA du Cotentin | Agrégat de réseaux urbains et interurbains de Normandie | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-des-reseaux-de-transport-public-normands|
|111 | Métropole Rouen Normandie | Agrégat de réseaux urbains et interurbains de Normandie | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-des-reseaux-de-transport-public-normands|
|197 | CA Flers Agglo | Agrégat de réseaux urbains et interurbains de Normandie | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-des-reseaux-de-transport-public-normands|
|44 | CA Evreux Portes de Normandie | Agrégat de réseaux urbains et interurbains de Normandie | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-des-reseaux-de-transport-public-normands|
|128 | CA Saint-Lô Agglo | Agrégat de réseaux urbains et interurbains de Normandie | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-des-reseaux-de-transport-public-normands|
|208 | SIVU transport urbain Bayeux et communes associées | Agrégat de réseaux urbains et interurbains de Normandie | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-des-reseaux-de-transport-public-normands|
|311 | CU d'Alençon | Agrégat de réseaux urbains et interurbains de Normandie | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-des-reseaux-de-transport-public-normands|
|135 | CA Lisieux Normandie | Agrégat de réseaux urbains et interurbains de Normandie | https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-des-reseaux-de-transport-public-normands|
|105 | CA Saumur Val de Loire | Agrégat des réseaux urbains et interurbains de la Région Pays de la Loire | https://transport.data.gouv.fr/datasets/arrets-horaires-et-circuits-des-lignes-de-transports-en-commun-en-pays-de-la-loire-gtfs-destineo-reseaux-aom-aleop-1|
|200 | CC de l'Aire Cantilienne | Réseaux urbains et interurbains de l'Oise (60) | https://transport.data.gouv.fr/datasets/arrets-horaires-et-parcours-theoriques-gtfs-des-differents-reseaux-de-transport-membres-du-synd3-1|
|196 | CC des Pays d'Oise et d'Halatte | Réseaux urbains et interurbains de l'Oise (60) | https://transport.data.gouv.fr/datasets/arrets-horaires-et-parcours-theoriques-gtfs-des-differents-reseaux-de-transport-membres-du-synd3-1|
|186 | CA de la Région de Compiègne et de la Basse Automne | Réseaux urbains et interurbains de l'Oise (60) | https://transport.data.gouv.fr/datasets/arrets-horaires-et-parcours-theoriques-gtfs-des-differents-reseaux-de-transport-membres-du-synd3-1|
|211 | CC des Sablons | Réseaux urbains et interurbains de l'Oise (60) | https://transport.data.gouv.fr/datasets/arrets-horaires-et-parcours-theoriques-gtfs-des-differents-reseaux-de-transport-membres-du-synd3-1|
|56 | CA du Beauvaisis | Réseaux urbains et interurbains de l'Oise (60) | https://transport.data.gouv.fr/datasets/arrets-horaires-et-parcours-theoriques-gtfs-des-differents-reseaux-de-transport-membres-du-synd3-1|
|32 | CA Creil Sud Oise | Réseaux urbains et interurbains de l'Oise (60) | https://transport.data.gouv.fr/datasets/arrets-horaires-et-parcours-theoriques-gtfs-des-differents-reseaux-de-transport-membres-du-synd3-1|
|290 | CC du Clermontois | Réseaux urbains et interurbains de l'Oise (60) | https://transport.data.gouv.fr/datasets/arrets-horaires-et-parcours-theoriques-gtfs-des-differents-reseaux-de-transport-membres-du-synd3-1|

**Comment by cyrilmorin** [comment]
Tout est OK !
Pour info il en manquait 2-3 côté BO mais beaucoup plus côté config :)
