### ISSUE TITLE
Commentaires passés

### ISSUE THREAD

**Issue by cyrilmorin** [etalab/transport-site#2954]
Hello,

Rien d'urgent ni de majeur, mais lorsque l'on référence un JDD "oublié" qui était présent sur datagouv mais pas sur le PAN, la notification "Commentaires" comporte également les commentaires passés.

Est-il possible de n'afficher que les commentaires du jour pour éviter toute confusion ?
Exemple notif du 26/01 pour [Filibus ](https://transport.data.gouv.fr/datasets/filibus-urbain)qui a été référencé le 25/01 mais qui comporte également des commentaires de 2020

Merci !

**Comment by AntoineAugusti** [comment]
@cyrilmorin Pourquoi souhaites-tu ce fonctionnement ? Ça ne me parait pas souhaitable

**Comment by AntoineAugusti** [comment]
Je retire le tag `notifications`, ça ne me parait pas lié au sujet des notifications étant donné que ce sont des discussions/commentaires

**Comment by cyrilmorin** [comment]
Désolé je me suis mal exprimé, c'est au sujet du mail pas des commentaires en tant que tel :) 
 dans le mail d'aujourd'hui on a les commentaires passés mais ça n'est pas très grave !

**Comment by AntoineAugusti** [comment]
Ah oui je comprends mieux ! Ça me parait trop rare pour prévoir un développement pour gérer ce cas alors.

Je te propose de fermer le ticket et on reviendra dessus si c'est pertinent ?

**Comment by cyrilmorin** [comment]
oui pas de souci, c'est effectivement pas très important !
