### ISSUE TITLE
"Non disponible" affiché alors que ressource a priori dispo

### ISSUE THREAD

**Issue by ChristinaLaumond** [etalab/transport-site#2959]
Hello, 
Le tag "non disponible" apparait pour le GTFS de Nice alors qu'on arrive bien à le télécharger. 
<img width="257" alt="image" src="https://user-images.githubusercontent.com/101095139/215532073-3e89449a-7c7b-4731-a56c-c22e48572caa.png">

Je sais qu'il y avait un sujet avec le fait que data.gouv récupérait le GTFS depuis un HTTP. Est-ce que c'est lié ? 

En tout cas si besoin de précisions, de mon côté, je suis sur Chrome pour le télécharger. 
Merci

**Comment by AntoineAugusti** [comment]
C'est indiqué car non indisponible car le serveur source met du temps à répondre. Sur la page de disponibilité d'une ressource, on indique le test exact que l'on fait et il faut répondre en moins de 5s, ce qui n'est pas le cas.

**Comment by ChristinaLaumond** [comment]
Merci j'ai répondu en ce sens à l'agglo. Ils sont en cours de refonte de leur opendata, j'espère que ca améliorera cela. A suivre !
