### ISSUE TITLE
Allow to merge two GTFS

### ISSUE THREAD

**Issue by Tristramg** [etalab/transport-site#296]
Currently some dataset are provided as two different (because of different operators or winter/summer services).

We should provide a way to merge them to reduce the effort for producers.

**Comment by antoine-de** [comment]
for this one idea would be to use an already existing OS tool (like maybe adapt https://github.com/CanalTP/transit_model/blob/master/src/bin/merge-ntfs.rs ?)

**Comment by Tristramg** [comment]
yup. This project is not the right place for that anyways.
