### ISSUE TITLE
Ajout logo réutilisateur Transtools

### ISSUE THREAD

**Issue by cyrilmorin** [etalab/transport-site#2970]
Hello !

Pouvez-vous rajouter comme logo réutilisateur l'image ci-jointe de  svp ?

<img width="294" alt="Logo TransTools" src="https://user-images.githubusercontent.com/116101828/219040051-fd7e305c-739e-46fa-8f72-a001f98d7140.png">

Lien souhaité par le réutilisateur : https://trans-tools.com/

Merci,

Cyril

**Comment by AntoineAugusti** [comment]
J'ai redécoupé leur logo dans la PR. Il y avait beaucoup de marge.
