### ISSUE TITLE
Penser à supprimer l'url gbfs/marseille/gbfs.json

### ISSUE THREAD

**Issue by fchabouis** [etalab/transport-site#2974]
Suite à https://github.com/etalab/transport-site/pull/2971 nous redirigeons l'url https://transport.data.gouv.fr/gbfs/marseille/gbfs.json vers le nouveau flux GBFS de Fifteen.

Notre url n'est plus référencée nulle part, et ce serait bien que les utilisateurs requêtent directement la bonne url. 

Pensons de temps en temps à vérifier l'usage de gbfs/marseille/gbfs.json pour couper cette url si très peu de de personnes s'en servent. La nous sommes encore à 150k requêtes par semaine...

**Comment by AntoineAugusti** [comment]
Traiter aussi les autres réseaux : Strasbourg et Montpellier.

#2298 #2669

**Comment by AntoineAugusti** [comment]
On vient d'être contacté par Cityway qui gère le calculateur et le référentiel du site ZOU ! pour la Région SUD (PACA) qui utilisait encore cette URL.

cc @etalab/transport-bizdev

**Comment by AntoineAugusti** [comment]
On pourra supprimer le GBFS pour Rouen à partir de juillet 2023 aussi (changement d'opérateur), ils publieront eux-mêmes le JDD et le flux

**Comment by AntoineAugusti** [comment]
Fait dans https://github.com/etalab/transport-site/pull/3241, on pourra supprimer aussi
