### ISSUE TITLE
Brique "Publicateur" non présente sur JDD Intercom

### ISSUE THREAD

**Issue by cyrilmorin** [etalab/transport-site#2977]
Hello,

Je remplissais plusieurs datasets avec les types de publicateur et le JDD [Intercom ](https://transport.data.gouv.fr/datasets/horaires-du-reseau-de-bus-intercom-2) ne présente pas la brique.

A priori, l'info du publicateur ne semble tout simplement pas remonter de datagouv ...
![image](https://user-images.githubusercontent.com/116101828/219697172-9d5d570a-f135-4d49-a554-84d937132d66.png)

 Je vous laisse regarder !

Merci,

Cyril

**Comment by AntoineAugusti** [comment]
- https://transport.data.gouv.fr/datasets/342
- https://transport.data.gouv.fr/datasets/626

ont le même problème

**Comment by AntoineAugusti** [comment]
Si vous pensez @etalab/transport-bizdev qu'il faut prévoir d'autres correctifs (interdire le référencement de JDD qui ne sont pas publiés par une orga / adapter l'UI) n'hésitez pas à le dire !

**Comment by cyrilmorin** [comment]
Hello @AntoineAugusti merci pour ton retour, je comprends mieux :)
