### ISSUE TITLE
Idées de système permettant de représenter la densité d'arrêt, puis les arrêts eux-mêmes

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#2982]
Suite aux différents échanges et démos avec @etalab/transport-bizdev et @etalab/transport-tech, et après avoir creusé différentes briques techniques, je note ce que j'ai trouvé.

La base des arrêts comprend actuellement 650k stops (latitude, longitude, id, nom, et lien id avec l'import correspondant). Si on fait un JSON sous forme d'array (juste les valeurs) ça se traduit par environ 40MB de données.

On aimerait bien être capable:
- d'afficher les arrêts eux-mêmes (en cliquable) dès lors qu'on a assez zoomé
- donner une idée de la densité en arrêts (pour voir les zones blanches etc)

### Traitement full client

La couche cliente (DeckGL en particulier) étant très optimisé (voir https://deck.gl/docs/developer-guide/performance), le rendu pourrait être réalisé côté client purement, si on parvient à envoyer les données du serveur à l'autre côté. J'ai commencé à faire cela pour voir, il faudrait zipper l'output et vérifier le volume total (qui pourrait peut-être descendre à 5MB), et éventuellement découper ça en "batchs" pour faire un affichage progressif.

Cette possibilité reste à étudier, c'est un peu "bulky" et ne permet pas de faire un affichage global rapide dès l'arrivée sur la page, mais pourrait au final être intéressant.

Voir aussi GeoParquet/GeoArrow pour optimiser un peu plus la donnée (https://observablehq.com/@kylebarron/geoarrow-and-geoparquet-in-deck-gl#cell-279).

### Utilisation de la base de données en direct (Postgres/PostGIS)

Il existe la possibilité de réaliser des clusters avec un minimum de distance / densité (avec https://postgis.net/docs/ST_ClusterDBSCAN.html), toutefois apparemment c'est assez gourmand, car réalisé en mémoire et sans index.

On peut utiliser `ST_SnapToGrid` pour grouper les points en arrondissant la lat/lon, ça pourrait être assez malin et basique (c'est rapide).

<details>
<summary>Requête</summary>

```sql
ALTER TABLE gtfs_stops ADD COLUMN geom geometry(Point, 4326);
UPDATE gtfs_stops SET geom = ST_SetSRID(ST_MakePoint(stop_lon, stop_lat), 4326);

with clusters as (
	select ST_SnapToGrid(geom, 0.01) as x, count(*) as c from gtfs_stops group by x
)

select 
	ST_X (ST_Transform (x, 4326)) AS cluster_lon,
	ST_Y (ST_Transform (x, 4326)) AS cluster_lat,
	c
from clusters
order by c desc
```

</details>

<details>
<summary>Résultat</summary>

| cluster_lon          | cluster_lat         | c   |
|----------------------|---------------------|-----|
|                    0 |                   0 | 941 |
|                 0.62 |                44.2 | 231 |
|                -1.68 |               48.11 | 223 |
|                -0.55 |               47.47 | 174 |
|                 0.63 |               44.19 | 173 |
|                -0.77 |               48.07 | 172 |
|                -0.36 |               49.18 | 171 |
|                 2.37 |               51.03 | 160 |
|                 1.45 |               43.61 | 154 |
|                 2.38 |               51.03 | 153 |
| -0.35000000000000003 |               49.18 | 150 |
|                 0.63 |               44.21 | 140 |
|                 2.38 |               51.02 | 135 |
|                 2.39 |               47.08 | 133 |
|                 4.08 |  48.300000000000004 | 132 |
|                 4.08 |               44.13 | 132 |
|                 7.42 |               43.74 | 132 |
|                 0.34 |               46.58 | 131 |
|                -1.78 |                46.5 | 129 |
|                 0.19 |                  48 | 129 |
|                 7.49 |               43.77 | 129 |
|                 7.43 |               43.75 | 129 |
|                 2.36 |               48.88 | 128 |
|                  0.2 |               48.01 | 127 |
|                 4.07 |  48.300000000000004 | 127 |
|                 2.36 |               51.03 | 124 |
|                 2.33 |               51.02 | 124 |
|                -0.58 |               44.84 | 122 |
|                 6.48 |               46.37 | 122 |
|                 0.65 |               44.24 | 122 |
|                 4.08 |               48.29 | 121 |
|                 0.19 |               48.01 | 121 |
|                  2.4 |               51.04 | 120 |
|                -4.49 |               48.39 | 119 |
|                 2.15 |               43.93 | 118 |
|                -1.18 |               47.37 | 118 |
|                 4.75 |               44.56 | 118 |
|                 2.35 |               51.02 | 118 |
|   2.3000000000000003 |               51.01 | 116 |
|                 0.62 |               44.21 | 116 |
|                -0.36 |               49.19 | 116 |
|                  3.1 |               45.78 | 116 |
|                 0.16 |               45.65 | 116 |
|                -1.48 |               43.49 | 116 |
|                 2.29 |               51.01 | 116 |
|                 6.93 |  43.660000000000004 | 115 |
|   0.6900000000000001 |               47.39 | 113 |
|                -1.55 |               47.19 | 113 |
|                 4.07 |               48.29 | 112 |
|                 3.09 |               45.78 | 112 |
|                -0.36 |                49.2 | 112 |
|                 2.34 |               51.03 | 112 |

</details>

Avec le bon "pas" de grille on arrive à avoir des datasets petits, qui vont permettre d'afficher un nuage de points

### Utilisation de grilles hexagonales directement dans PostGIS

Voir https://blog.rustprooflabs.com/2022/04/postgis-h3-intro, ce système permettrait de représenter la densité correctement.

Cela requiert une extension h3 si on veut des hexagones plus réalistes, sinon https://postgis.net/docs/ST_HexagonGrid.html peut faire l'affaire aussi.

### Utilisation d'un serveur de tiles vectorielles

Un outil comme http://martin.maplibre.org peut être utilisé directement avec DeckGL, Leaflet etc (voir https://github.com/maplibre/martin#using-with-maplibre).

La source de données sera ou bien directement Postgres, ou bien des fichiers MBTiles/PMTiles.

https://github.com/mapbox/tippecanoe sait produire des MBTiles à partir de GeoJSON, et réalise plusieurs niveaux de zoom avec un échantillonnage graduel (les points sont supprimés au fur et à mesure qu'on dézoome).

J'ai découvert que Martin permettait de faire du filtre côté serveur, via les fonctions sources (https://github.com/maplibre/martin#function-sources), mais ça reste à creuser.

**Comment by thbar** [comment]
Notes intéressantes concernant DeckGL:
- https://deck.gl/docs/api-reference/geo-layers/tile-layer qui sait passer le niveau de zoom et le x/y de la tile (sur laquelle on pourrait s'appuyer pour faire un retour intelligent côté serveur, quitte à n'agréger qu'à quelques niveaux)
- https://deck.gl/docs/api-reference/aggregation-layers/hexagon-layer qui fait l'agrégation côté client

**Comment by antoine-de** [comment]
Salut @thbar , si t'as deja une API, tu peux aussi facilement générer des tuiles vectorielles directement depuis postgis (ce que fait martin en fait). via [ST_AsMVT](https://postgis.net/docs/ST_AsMVT.html) (ce que je faissais sur un autre projet combiné avec un Snap_ToGrid + déduplication, il y a quelques examples [ici](https://gitlab.com/geovisio/geovisio/-/merge_requests/18)).

Sinon t'as regardé https://protomaps.com/ ? Ca peut etre trop cool, tu te fais un job en background qui converti ton json en tuile (via tippecanoe ou autre), tu fous ca dans un bucket et t'as ton serveur de tuile :tada:

**Comment by fchabouis** [comment]
Et ça te permet quand même de filtrer les données comme tu veux @Antoine D
***@***.***> ?

**Comment by antoine-de** [comment]
je ne suis pas un expert, mais d’après ce que j'ai compris, l'idée c'est juste d'avoir un gros fichier bien rangé, calé dans un bucket, pis d'en demander des bouts avec des range requests http pour avoir tes tuiles. C'est moins flexible qu'une base, tu vas à chaque fois récupérer toute la tuile que tu veux. 
Après vu ce sont des tuiles vectorielles, tu peux filtrer en post traitement (mais tu payes le transfers complet).

L'idée dans ce cas, c'est quand meme que ton process de génération du gros fichier fasse la majeure partie de ton filtrage je dirais.

**Comment by thbar** [comment]
Je me dis qu'on pourrait tenter le coup du `ST_SnapToGrid` que j'avais repéré et que @antoine-de a utilisé ; pour la partie "vue globale" ça permettrait de faire une sorte de heat map peu coûteuse à créer (qu'on pourrait mettre en cache à différents niveaux de zoom d'ailleurs, quitte à ensuite faire du "bounding box"), ce qui gèrera la vue d'ensemble.

Et après en zoomant voir autre chose (totalité des points dans la bounding box ou dans un rayon comme suggéré par @fchabouis sur un autre projet), en attendant mieux ça pourrait suffire.

On va en discuter cet après-midi au point d'équipe.

**Comment by thbar** [comment]
Voir #2995

**Comment by thbar** [comment]
Implémenté dans:
- #2995
