### ISSUE TITLE
Adaptations code pour catégorie car-motorbike-sharing

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#2989]
Suite à la publication du [premier JDD](https://transport.data.gouv.fr/datasets/vehicules-en-autopartage-leo-go-dans-la-metropole-de-lyon-disponibilites-temps-reel) dans cette catégorie, il faut prévoir quelques adaptations qui étaient faites pour `bike-scooter-sharing`

- Détection du format `gbfs` lors de l'import
- Affichage d'une carte
- Calcul de métadonnées
- Ne pas historiser

**Comment by AntoineAugusti** [comment]
@cyrilmorin Pourrais-tu me proposer du texte EN et FR pour la catégorie ? Voilà ce qu'on a pour `bike-scooter-sharing`.

https://github.com/etalab/transport-site/blob/d7014ffb0152f273dcb8d0725c8e54b3b7b33a07/apps/transport/priv/search_custom_messages.yml#L131-L148

**Comment by cyrilmorin** [comment]
@AntoineAugusti : on va faire simple et homogène en remplaçant juste le mode de transport :) 
j'ai juste rajouté une précision sur le GBFS pour la v2.3 minimum.

N'hésites pas à modifier/corriger si besoin !

     fr: | 
Les jeux de données référencés dans cette catégorie contiennent des flux d’information décrivant des flottes de voitures ou deux-roues motorisées en libre service en station ou en freefloating. 
Ces données sont disponibles en temps réel pour connaître la position des véhicules ou le taux de remplissage des stations. 
Le standard utilisé est le [GBFS à partir de la v2.3 ](https://github.com/NABSA/gbfs). 
  
     en: | 
The datasets referenced in this category contain information flows describing fleets of self-service cars or motobikes in stations or in freefloating. 
 These data are available in real time to know the position of vehicles or the filling rate of stations. 
The standard used is [GBFS] from 2.3 (https://github.com/NABSA/gbfs).
