### ISSUE TITLE
Points bloquants pour la mise à jour de "castore"

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#3015]
En tentant de mettre des librairies à jour, j'ai vu que Finch est "coincé" sur `castore` version 0.1.x, alors qu'à présent `castore` est passé en version 1.0. Ce point est corrigé sur master (https://github.com/sneako/finch/pull/210) mais pas encore livré.

Il est important de pouvoir mettre à jour `castore` facilement car cela nous permet d'assurer des connections HTTPS solides (pour l'extraction des données, les validations etc), avec des certificats à jour.

J'ouvre ce ticket pour qu'on pense à mettre à jour et suivre ce point, et il y aura peut-être d'autres points similaires à suivre.

**Comment by AntoineAugusti** [comment]
Fixed in https://github.com/etalab/transport-site/pull/3038
