### ISSUE TITLE
Redirections 308 non gérées sur data.gouv.fr

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#3016]
[Voir Sentry](https://transport-data-gouv-fr.sentry.io/issues/3987059322/?environment=prod&project=6197733&referrer=issue-stream)

Il faudrait robustifier https://github.com/etalab/transport-site/pull/2871

Les réponses ont l'air d'avoir changé, maintenant ce n'est plus une URL complète mais uniquement le path, sans le domaine.

```
$ curl -I https://www.data.gouv.fr/api/1/datasets/fichier-gtfs/
HTTP/1.1 308 PERMANENT REDIRECT
server: nginx
date: Thu, 09 Mar 2023 17:06:03 GMT
content-type: text/html; charset=utf-8
content-length: 233
location: /api/1/datasets/ametis/
access-control-allow-origin: *
pragma: public
cache-control: public
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
x-frame-options: SAMEORIGIN
```

Faudrait adapter le code en conséquence

**Comment by maudetes** [comment]
En effet, ça fait suite à l'upgrade de Werkzeug dans https://github.com/opendatateam/udata/pull/2816, qui embarque notamment https://github.com/pallets/werkzeug/issues/2352.

**Comment by AntoineAugusti** [comment]
@maudetes Merci de confirmer, j'avais vu ce commit et je me suis dit que c'était surement ça, sans pour autant mener l'investigation complète !

J'aurais dû faire un code plus robuste 👍

**Comment by AntoineAugusti** [comment]
La vie aurait été plus simple si https://github.com/benoitc/hackney/pull/692 était mergée https://github.com/etalab/transport-site/issues/1801
