### ISSUE TITLE
Quelques problématiques rencontrées dans la recherche du PAN

### ISSUE THREAD

**Issue by ChristinaLaumond** [etalab/transport-site#3021]
Hello,  

Quelques problématiques rencontrées dans la barre de recherche pour alimenter les futures améliorations :
- Quand on fait une recherche pour Clermont-Ferrand, le GTFS de Clermont-Ferrand arrive en dernière position : https://transport.data.gouv.fr/datasets?insee_commune=63113&page=2
- Quand on fait une recherche pour l'île de France, l'agrégat IDFM arrive dans les dernières positions également : https://transport.data.gouv.fr/datasets/region/6 

Thanks

**Comment by AntoineAugusti** [comment]
@fchabouis Je t'assign aussi (si tu traites l'autre !), dis-moi si tu veux de l'aide !

**Comment by AntoineAugusti** [comment]
Voir [discussion sur Mattermost](https://mattermost.incubateur.net/betagouv/pl/7epdfg4qzjy1fmetct1fgxenuw) qui continue sur la réflexion

**Comment by AntoineAugusti** [comment]
@etalab/transport-bizdev Vaste sujet la recherche, n'hésitez pas à ouvrir d'autres tickets en cas de besoin
