### ISSUE TITLE
Gérer le pluriel pour les messages de validation

### ISSUE THREAD

**Issue by fchabouis** [etalab/transport-site#3025]
![image](https://user-images.githubusercontent.com/15341118/225034956-ba0a7eb7-2be6-4b18-9586-343c423d8d4a.png)

![image](https://user-images.githubusercontent.com/15341118/225034984-a24dee9c-c750-4fff-9b81-4810193354f6.png)

La manière dont c'est fait [actuellement](https://github.com/etalab/transport-site/blob/35ee1222bf0a366a0995238cc3fa203e25d6b748/apps/transport/lib/validators/gtfs_transport_validator.ex#L71) ne le permet pas

**Comment by AntoineAugusti** [comment]
Ça fait tellement longtemps que ça me frustre de voir ceci mais je sais que le code est pas facile à modifier 😬

**Comment by AntoineAugusti** [comment]
Merci @ptitfred d'avoir traité ce vieux ticket ! 🙏
