### ISSUE TITLE
Les validateurs des schémas Tableschema du PAN renvoie vers l'ancien nom de domaine Validata

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#3061]
- Lieux de covoiturage
- Comptage des mobilités 
- Stationnement 
- Stationnement cyclable 
- IRVE statique

**Comment by AntoineAugusti** [comment]
@Miryad3108 Tu peux me préciser une URL / mettre une capture d'écran / donner un lien erroné ?

**Comment by Miryad3108** [comment]
Sur ce lien : https://transport.data.gouv.fr/validation/77779?token=e446cd8a-b4ac-465b-9a4f-1582c7f3e8dc
si tu cliques sur "Montre seulement les 50 premières lignes. Consultez toutes les erreurs [sur ce site web](https://validata.etalab.studio/table-schema?schema_name=schema-transport.etalab%2Fschema-irve-statique)." ça renvoie vers une page d'erreur 
@AntoineAugusti
