### ISSUE TITLE
Organiser les jeux de données schéma comptage des mobilités 

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#3064]
Le [Grand Lyon publie plusieurs formats pour les données de comptage des mobilités](https://transport.data.gouv.fr/datasets?type=transport-traffic) : SHP, GEOJSON, JSON et CSV mais seul le format CSV est demandé. Les autres formats peuvent également être utiles aux réutilisateurs mais avoir tous ces format dans une même section pourrait rendre le jeu de données illisibles car il faut trois fichiers pour ce schéma (Measure, site, channels). 
Serait-il possible d'avoir deux sections pour les jeux de données comptage avec : 
- Ressources CSV 
- Autres Ressources
ou 
- Ressources avec schéma 
- Ressource 
et on demandera aux collectivités de n'affilier que la ressource CSV au schéma, comme c'est fait avec la [ZFE de Paris](https://transport.data.gouv.fr/datasets/zone-a-faibles-emissions-zfe) par exemple

(ou d'autres termes pour séparer le format CSV des autres formats)

**Comment by AntoineAugusti** [comment]
Hello !

Le découpage avec des sections "Ressources avec schéma" et "Ressources" est mis en place pour toutes les catégories de données, ce n'est pas spécifique aux ZFE.

Ainsi, si le schéma est bien spécifié sur un JDD comptage des mobilités on aurait bien la séparation des ressources.
