### ISSUE TITLE
API reach

### ISSUE THREAD

**Issue by ppezziardi** [etalab/transport-site#308]
Une première API est disponible donnant accès à toutes les sources de données transport public fusionnées.

http://transport.data.gouv.fr/api/publictransport/reach
lat=
lon=
time=

Renvoie l'ensemble des lignes de TP permettant d'atteindre lat/lon à l'heure time. L'API estime donc la part de trajet à pied entre l'arrêt de desserte et lat/lon.

Permet donc à un réutilisateur (ex. Pass Culture) d'afficher "Y aller en transport ?" "Prendre la ligne X qui arrive à hh:mm (départ hh:mm du terminusBas, direction terminusHaut), et marcher y minutes"

**Comment by Tristramg** [comment]
Réflexion encore un peu floue :

* Dans le cadre du temps réel, on va lire le gtfs
* On va répondre avec du théorique lorsqu’il n’y a pas de temps réel
* On peut donc l’instancier sur toutes les données qu’on a, même s’il n’y a pas de temps réel
* Ça répondra à une partie des questions

**Comment by Tristramg** [comment]
Je pense que ça sera le travail de TOPO de rendre ce genre de service. Je ferme du coup.
