### ISSUE TITLE
Notification autour du passage de/vers Licence ouverte de/vers autres licences

### ISSUE THREAD

**Issue by cyrilmorin** [etalab/transport-site#3084]
Hello @AntoineAugusti 

Comme vu ensemble, peut-on enrichir (voire renommer ?) la notif "dataset_now_licence_ouverte" pour les jeux qui passent en LO en enrichissant la notif  avec les jeux qui passent de la LO vers une autre licence également.

Cela nous permettrait d'alerter les réutilisateurs qui intègrent les données dans le cadre de l'obligation de l'utilisation des JDD en LO disponibles sur le PAN + nous permettrait de contacter les producteur sen questions pour leur rappeler cette obligation

Merci !

cc @Miryad3108

**Comment by AntoineAugusti** [comment]
Voir PR liée pour le détail de l'implémentation et le contenu
