### ISSUE TITLE
"Prochainement" (recette) est cassé

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#3089]
C'est embêtant pour différentes raisons:
- difficultés/impossibilité à tester des petites ou grosses upgrades (Elixir, javascript...)

**Comment by thbar** [comment]
(ce ticket n'apparaît pas dans ma liste sur le ticket center...)

**Comment by AntoineAugusti** [comment]
@thbar Yes, tu peux y aller à ta convenance 😋

**Comment by thbar** [comment]
Ca marche sur un test simple oauth, nickel merci @AntoineAugusti d'avoir tacklé ça.

On retrouvera le ticket si besoin de refaire je pense...
