### ISSUE TITLE
Mettre au propre le credential transport-proxy-config-service-user

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#3102]
Ce user a accès en lecture seule à la configuration proxy (voir https://github.com/etalab/transport-proxy-config/settings/access).

Pour que @AntoineAugusti en dispose aussi il faut:
- que je partage le login pass avec Antoine
- que je réinitialise le 2FA

**Comment by AntoineAugusti** [comment]
J'ai pu me connecter avec succès ✅ J'ai fait un tour rapide dans les paramètres ça me parait bon.
