### ISSUE TITLE
Statistiques de fréquentation du site => pas de stats pour doc.transport, blog.transport et normes.transport

### ISSUE THREAD

**Issue by cyrilmorin** [etalab/transport-site#3123]
Les stats de fréquentation du site transport.data.gouv.fr ne semblent pas comprendre les pages des sous-domaines [doc.transport.data.gouv.fr](https://doc.transport.data.gouv.fr/), [blog.transport.data.gouv.fr](https://blog.transport.data.gouv.fr/) et [normes.transport.data.gouv.fr](https://normes.transport.data.gouv.fr/)
Nous n'avons donc aucune information sur l'intérêt ou la facilité d'accès aux pages de documentation ni pour le blog

Accès aux stats : [matomo](https://stats.data.gouv.fr/index.php?module=CoreHome&action=index&idSite=58&period=range&date=previous30#?period=range&date=previous30&category=Dashboard_Dashboard&subcategory=1&idSite=58)

Est-il possible de rajouter sur ce même espace (site web) "TRANSPORT.DATA.GOUV.FR" les pages commençant par doc.transport.data.gouv.fr, blog.transport.data.gouv.fr ET normes.transport.data.gouv.fr ?
![image](https://user-images.githubusercontent.com/116101828/235714995-77ec8e56-d0f4-45ef-bc4f-60cbd26de918.png)

Merci !

**Comment by AntoineAugusti** [comment]
Ça arrive en prod pour le blog et les normes

**Comment by cyrilmorin** [comment]
@AntoineAugusti comme vu ensemble peux-tu voir directement avec eux les aspects techniques concernant notre demande 
via leur support stp ? [support](https://docs.gitbook.com/faq/support) : support@gitbook.com
Merci :)

**Comment by AntoineAugusti** [comment]
✅

**Comment by AntoineAugusti** [comment]
GitBook a répondu ceci.

---

Currently, we don't have an integration with Matomo. You could use our integrations API to create that for yourself. [Here are the details in our documentation](https://developer.gitbook.com/integrations/integrations).

I do understand that this requires some work on your side and it might not be suitable for you at this time, but we don't have plans to introduce that integration as a first-party built by GitBook.

I understand this is not the answer that you were hoping for, but hopefully it clarifies.

**Comment by AntoineAugusti** [comment]
@cyrilmorin On peut considérer comme fait ? Pour GitBook faudra se contenter des outils qu'ils proposent il semble.
