### ISSUE TITLE
L'absence d'extension sur les CSV via le proxy est troublant pour les utilisateurs

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#3165]
Ça a été remonté par @cyrilmorin et GIREVE: notamment pour les liens IRVE qui passent par le proxy, le fait que le fichier n'aie pas d'extension après téléchargement crée de la confusion.

Autant sur le SIRI ou sur le GTFS-RT on est sur des utilisateurs qui s'attendent à du XML et du binaire protobuf, autant sur le CSV ça a l'air d'être différent.

On pourrait modifier le header adapté à la volée en permettant de configurer une extension de téléchargement à ajouter en bout d'identifiant par exemple.

**Comment by AntoineAugusti** [comment]
Est-ce à nous de résoudre ceci ou au producteur qui peut ajouter les headers indiquant le nom du fichier au téléchargement ?

**Comment by thbar** [comment]
@AntoineAugusti en pratique on sette déjà ce header nous-même ([Content-Disposition](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition) qui permet aussi de définir le nom):

https://github.com/etalab/transport-site/blob/a7c37c300e3ea2fdae0377b27a6c49bc75ad4da1/apps/unlock/lib/controller.ex#L107-L113

Je pense que ça serait plus compliqué de demander ça au producteur que d'adapter chez nous pour le coup.

On en reparle !

**Comment by AntoineAugusti** [comment]
Ah oui c'est vrai, merci.

On pourrait avoir de la configuration pour ajouter des headers, genre `extra_headers` ?

**Comment by thbar** [comment]
Je pensais à avoir directement une notion d'extension, qui quand elle est présente donne lieu à une modification de ce qui est setté de notre côté:

```elixir
put_resp_header("content-disposition", "attachment; ; filename=\"#{the_slug}#{the_extension}\"") 
```

Ou bien éventuellement un truc plus générique du type "type: irve" qui donnerait lieu à ça, mais c'est un peu bancal.

**Comment by AntoineAugusti** [comment]
Ah oui je vois ! Je pense que je préfère l'ajout d'headers, c'est plutôt générique et c'est similaire aux headers qu'on ajoute quand on fait des requêtes.

Je te laisse choisir si tu t'en charges 😊

**Comment by thbar** [comment]
@AntoineAugusti oui ça devrait le faire même si pas très DRY, je pense que ça sera ça. Je m'en chargerai merci
