### ISSUE TITLE
Liste des limitations connues de la carte de consolidation GTFS

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#3167]
Je liste ici les limitations connues de la carte des arrêts GTFS https://transport.data.gouv.fr/explore/gtfs-stops.

Liste à consolider par rapport aux autres tickets déjà ouverts.

- Un fichier marqué "valide" sur le PAN peut ne pas apparaître dans la carte (voir https://github.com/google/transit/issues/377 par exemple), car le validateur GTFS et le module d'import de la carte nationale ne sont pas stricts sur les mêmes aspects
- Les GTFS expirés sont quand même affichés (https://github.com/etalab/transport-site/issues/3156).
- Si une ressource GTFS est supprimée, les points restent actuellement sur la carte (https://github.com/etalab/transport-site/issues/3138).
- Les doublons (ou +) "légitimes ou pas" apparaissent bien dans les aggrégats (lorsqu'on ne zoom pas trop), toutefois lorsqu'on n'affiche plus des aggrégats mais les points eux-mêmes, cela ne se voit plus car les points sont exactement au même endroit sur la carte et elle n'affiche pas cette information actuellement (en lien avec [DeckGL Picking](https://deck.gl/docs/developer-guide/custom-layers/picking))
- Les fichiers GTFS générant une erreur technique lors du traitement ne sont pas intégrés (pour l'équipe, voir https://transport.data.gouv.fr/backoffice/batch-report pour la liste, actuellement 18 fichiers, dont une bonne moitié liée au fait qu'un sous-répertoire est présent dans le zip - on peut partir de cette liste pour améliorer la qualité). Voir https://github.com/etalab/transport-qualite-des-donnees/issues avec une liste publique d'éléments concernés
- https://github.com/etalab/transport-site/issues/3179

**Comment by thbar** [comment]
Je clôture pour le moment pour faire le tri, le ticket reste linké depuis la carte, on pourra réouvrir.

**Comment by Mathieu-Ptz** [comment]
Bonjour est il possible d'avoir la liste des 18 fichiers ne pouvant pas être affichés sur la Carte consolidée des arrêts GTFS et avoir une vision encore plus exhaustive. 
Comme évoqué ci-dessus il y a bien des GTFS valide qui ne s'affiche pas sur la carte car il y a un sous répértoire. C'est notamment le cas pour le réseau urbain d'Abbeville : https://transport.data.gouv.fr/resources/83757#validation-report. Cette liste pourrait être intéressante.
