### ISSUE TITLE
BO - Représentants légaux : erreur "Unable to get datagouv id"

### ISSUE THREAD

**Issue by cyrilmorin** [etalab/transport-site#3181]
Hello,

Lorsque l'on renseigne le représentant légal l'erreur "_Unable to get datagouv id_" s'affiche suite à l'enregistrement de la modification
Test réalisé sur le dataset : https://transport.data.gouv.fr/backoffice/datasets/542/edit avec l'AOM "Région Grand Est"

![image](https://github.com/etalab/transport-site/assets/116101828/986fefae-5eca-4848-bfbe-4c53001067d8)

**Comment by AntoineAugusti** [comment]
@cyrilmorin Tu peux essayer à nouveau ? Ça ressemble à une erreur temporaire côté API datagouv

**Comment by AntoineAugusti** [comment]
J'ai pu le mettre sans problème ce matin. Je ferme, je te laisse ouvrir à nouveau si ça revient.
