### ISSUE TITLE
Possibilité d'envoyer un mail depuis la backoffice quand un jeu de données est référencé sur le PAN

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#3184]
Ajouter la possibilité d'envoyer un mail aux personnes qui publient les données sur datagouv pour leur annoncer que leurs données ont été référencées sur la PAN et renvoyer vers l'espace producteur pour gérer leurs données. 

Dans le backoffice : 
- ajouter une option "Envoyer mail aux administrateurs"  qui enverra un mail au contact associé au jeu de données ;
- avoir un historique permettant de savoir si un mail a déjà été envoyé.

⚠️ Conditions pour pouvoir envoyer ces mails : avoir associé un contact au préalable au jeu de données grâce à l'onglet "Gestion des contacts" du backoffice

"Bonjour, 

Votre jeu de données [mettre titre+lien vers le jeu de données sur le PAN] a bien été référencé sur le [Point d'accès national aux données de transport, transport.data.gouv.fr](https://doc.transport.data.gouv.fr/guide-du-pan). 
Pour gérer la qualité de vos données : [les mettre à jour](https://doc.transport.data.gouv.fr/producteurs/mettre-a-jour-des-donnees), vous [inscrire à des notifications](https://doc.transport.data.gouv.fr/producteurs/gerer-la-qualite-des-donnees/sinscrire-aux-notifications) etc. nous vous encourageons à passer par l'[espace producteur du PAN](https://transport.data.gouv.fr/espace_producteur). 

Si vous avez des questions, n'hésitez pas à contacter notre équipe à l'adresse : contact@transport.beta.gouv.fr.

Bien à vous,"

**Comment by AntoineAugusti** [comment]
@etalab/transport-bizdev Ça arrive en prod. Vous verrez le bouton en dessous des abonnements aux notifications sur la page d'un JDD qui a été référencé il y a moins de 30 jours, quand vous avez ajouté des contacts et que cet e-mail n'a pas encore été envoyé
