### ISSUE TITLE
BO : les infos saisies disparaissent à l'ajout du champ "Représentant légaux"

### ISSUE THREAD

**Issue by cyrilmorin** [etalab/transport-site#3192]
Hello,

Lorsque l'on ajoute un JDD dans le BO et qu'on complète le formulaire de bas en haut, l'ajout du "Représentant légal" fait disparaître les saisies précédemment renseignées dans le formulaire.

Pas de souci lorsque l'on modifie un JDD existant et que l'on ajoute l'info "Représentant légaux"

Merci

**Comment by AntoineAugusti** [comment]
@fchabouis Tu as travaillé sur cette partie, tu souhaites regarder ? C'est un problème lié au LiveView il me semble.

Pour réproduire :
- ajouter un JDD depuis le BO
- renseigner nom + URL
- renseigner responsable légal
- 🐛 constater que les champs précédents sont vidés

**Comment by fchabouis** [comment]
je regarde, merci !
