### ISSUE TITLE
Améliorations possibles pour la table notifications

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#3196]
La structure actuelle de la table

```sql
CREATE TABLE notifications (
    id BIGSERIAL PRIMARY KEY,
    reason character varying(255) NOT NULL,
    dataset_id bigint REFERENCES dataset(id) ON DELETE SET NULL,
    email bytea NOT NULL,
    email_hash bytea NOT NULL,
    inserted_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    dataset_datagouv_id character varying(255)
);
```

Quelques améliorations possibles :
- ajouter `notification_subscription_id`
- ajouter `contact_id`
- ajouter un flag "soft delete" pour les rares cas où on souhaite faire du nettoyage sans perdre toute trace de logs
- ajouter des métadonnées pour la notification qui complète la raison et le potentiel JDD. Permettrait d'indiquer qu'on envoie une notification d'expiration pour un JDD, _avec une péremption dans x jours_.

**Comment by AntoineAugusti** [comment]
Utiliser `fetch_env!` ou `compile_env!` dans le code qui définit l'adresse d'envoi https://github.com/etalab/transport-site/pull/3347#discussion_r1273459912

**Comment by vdegove** [comment]
+1 pour notification_subscription_id, mais du coup il faut faire du soft delete côté notification_subscription (dans le cas où quelqu’un se désabonne, mais qu’on a envie de retrouver ses petits dans cette table).

Je remets un truc que j’ai mis ici https://github.com/etalab/transport-site/pull/3353#discussion_r1276216225 mais pour moi, il y a un lien dans notification_subscription entre le duo raison + rôle et les templates d’email qu’il serait pas mal de lister. Genre, en vrai, on s’abonne à un email donné, c’est la raison d’être de cette table. Enfin, à réfléchir.

**Comment by AntoineAugusti** [comment]
Avec l'ajout des abonnements, vérifier la cohérence de `reason` : pour certaines valeurs `dataset_id` est requis ou pas

**Comment by ptitfred** [comment]
Supporter le cas où l'email a été préparé mais pas correctement envoyé ? https://github.com/etalab/transport-site/pull/3846#discussion_r1549910253

**Comment by AntoineAugusti** [comment]
https://github.com/etalab/transport-site/issues/3943 une rapide amélioration

**Comment by vdegove** [comment]
Quelques éléments en plus :
- Pour la suppression d’un abonnement de notification, je voulais pas parler de « soft delete », mais juste que le `notification_subscription_id` côté table `subscription` soit nullé, au lieu que la ligne soit supprimée en cascade (pour garder les logs).
- C’est le bon moment pour découper un module `Transport.NotificationReason` en reprenant les bonnes fonctions de `DB.NotificationSubscription`, qui se retrouvera considérablement allégé avec un découpage des responsabilités plus clair ; et se servir de ce nouveau module dans `DB.NotificationSubscription` et `DB.Notification`.
- Faudrait mettre une validation sur les motifs dans `DB.Notification`, et peut-être d’autres validations pour vérifier que l’ensemble est cohérent (vu qu’il y a des données dénormalisées).
- Le payload est une bonne idée ; ça peut être pas mal d’y insérer les données genre liste de datasets, de contacts, etc, qui sont passés au template d’email – ça pourra bien aider pour débugguer et vérifier qu’on liste bien les choses qu’on doit lister.
