### ISSUE TITLE
Ajouter vidéo de présentation de la mission du PAN sous forme d'encart

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#3200]
Ajouter [la vidéo de présentation de la mission du PAN](https://www.youtube.com/watch?v=pTrDst_JX_4) sous forme d'encart ici
https://github.com/etalab/transport-site/blob/master/apps/transport/lib/transport_web/templates/page/missions.html.md

A la fin de la partie "Contexte"
Je ne pense pas qu'il y ai besoin d'introduire la vidéo. Le texte de la partie "Contexte" suffit.

**Comment by AntoineAugusti** [comment]
Éviter de mettre un embed YouTube (hébergé sur mon compte perso 😬), je vais voir avec la DINUM ce qui est plus approprié
