### ISSUE TITLE
Backoffice : crash suppression region_id d'un dataset

### ISSUE THREAD

**Issue by fchabouis** [etalab/transport-site#3202]
On associe un dataset à une région (region_id), on sauvegarde.
Puis on enlève l'association avec la région et on le passe en national par exemple.
=> crash du BO

**Comment by AntoineAugusti** [comment]
Ah ouais ?!? C'est une régression ? Ça parait un cas pas si rare que ça.

**Comment by AntoineAugusti** [comment]
[Voir Sentry](https://transport-data-gouv-fr.sentry.io/issues/4223322080/?environment=prod&project=6197733&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=1)
