### ISSUE TITLE
[Fil Bleu-Tours] : Validation GTFS-RT renvoie sur une erreur 

### ISSUE THREAD

**Issue by cyrilmorin** [etalab/transport-site#3206]
Hello,

La validation du GTFS-RT de [Fil Bleu ](https://transport.data.gouv.fr/datasets/fil-bleu-syndicat-des-mobilites-gtfs-gtfs-rt) renvoie l'erreur '*Impossible de déterminer le fichier GTFS à utiliser pour effectuer une validation du GTFS-RT* alors qu'il n'y a qu'un unique GTFS. 
Vous pouvez regarder pourquoi svp ?

Merci !!

**Comment by AntoineAugusti** [comment]
Voir https://github.com/etalab/transport-site/issues/2832

**Comment by AntoineAugusti** [comment]
Je vais voir pour traiter le cas mentionné dans l'issue cité précédemment et adapter le message d'erreur.
