### ISSUE TITLE
Encourager les producteurs à passer d’abord par la validation avant de publier

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#3227]
## Besoin

Les producteurs ne sont pas assez au courant que le validateur de données existe, et n’ont pas suffisamment le reflexe de l’utiliser. Conséquence : ils publient des jeux de données invalides ou à qualité insuffisante, ça fait des ping pong d’emails entre eux et nous, et potentiellement des réutilisateurs ont des données de mauvaise qualité.

On veut inciter à ce qu’ils passent le plus possible par le validateur de données avant la publication (sans rendre cette étape obligatoire pour l’instant).

À faire :
- [x] Sur la page d’accueil de l’espace producteur : mettre la boîte sur la validation tout en haut à gauche
- [x] Facile : page de publication ou d’édition de ressource : rajouter une mention statique à la validation

À décaler sur une autre issue :
- [ ] ~~Plus compliqué : page de publication ou d’édition de ressource : publication en deux étapes, ou le même fichier est d’abord passé au validateur, puis publié.~~

## Ancienne issue de Miryad

Rediriger vers les validateurs à la demande quand on veut publier ou mettre à jour une ressource/un jeu de données 

- Publier un jeu de données 
Ajouter une étape "Evaluer la qualité d'un fichier" avant de renvoyer vers data.gouv.fr 

- Mettre à jour un jeu de données 
Ajouter une étape "Evaluer la qualité d'un fichier" avant "Envoyer un fichier"
<img width="551" alt="image" src="https://github.com/etalab/transport-site/assets/59559301/596c2ba5-91a2-406b-9b3b-40ee3ddcf0e3">

**Comment by vdegove** [comment]
Remarque intéressante d’un utilisateur : il ne sait pas qui fait quoi entre data.gouv et transport.data.gouv.
