### ISSUE TITLE
Actions court-terme suivi article 122

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#3228]
## Pour retirer le badge article 122

- Détecter JDD article 122 qui passe à licence != LO
  - Envoyer un e-mail à J+1 aux bizdevs 
  - Enlever le tag `loi-climat-resilience` automatiquement
  - Les réutilisateurs seront informés le prochain lundi automatiquement
  - Ajouter une formule indiquant que notre équipe est en contact avec les producteurs cc @Miryad3108

- Ajouter une icône permettant d'identifier les JDD article 122 dans le backoffice (et réutiliser les filtres de péremption + erreur fatale pour faire le tri)

## Pour l'éligibilité

- Faire une analyse adhoc pour trouver les JDD public-transit LO, sans erreur et à jour. @etalab/transport-bizdev fera le tour de ces JDD pour mettre le badge article 122, au cours de plusieurs semaines, peut-être région par région
- Faire un export pour @Benoit-MINT contenant les JDD publiés en ODbl avec les contacts associés et indiquer à @Miryad3108 les JDD qui n'ont pas de contact.

**Comment by AntoineAugusti** [comment]
## Export

Un export des JDD qui n'ont pas encore le badge, qui n'ont pas d'erreur importante ou fatale et qui ne sont pas périmés : 56 JDD.

[results.csv](https://github.com/etalab/transport-site/files/11798628/results.csv)

|url|custom_title|population|AOM|Région|
|--- | --- | --- | --- | ---|
|https://transport.data.gouv.fr/datasets/agen-gtfs-tad | Réseau TAD Agen | 103761 | CA Agglomération d'Agen | Nouvelle-Aquitaine|
|https://transport.data.gouv.fr/datasets/agen-gtfs-urbain | Réseau urbain Tempo Bus | 103761 | CA Agglomération d'Agen | Nouvelle-Aquitaine|
|https://transport.data.gouv.fr/datasets/agglobus | Réseau urbain agglo'Bus | 29588 | CA du Grand Guéret | Nouvelle-Aquitaine|
|https://transport.data.gouv.fr/datasets/arrets-horaires-et-circuit-de-la-lignes-yeu-continent-gtfs | Réseau maritime Yeu-Continent | 4967 | L'Île-d'Yeu | Pays de la Loire|
|https://transport.data.gouv.fr/datasets/arrets-horaires-et-parcours-theoriques-du-reseau-stan-gtfs | Réseau urbain Stan | 262121 | Métropole du Grand Nancy | Grand Est|
|https://transport.data.gouv.fr/datasets/ctlb-donnees-theoriques-et-rt-aix-les-bains-lac-du-bourget | Réseau urbain Ondéa | 78417 | CA Grand Lac | Auvergne-Rhône-Alpes|
|https://transport.data.gouv.fr/datasets/donnees-de-transport-en-commun-reseau-altigo-communaute-de-communes-du-brianconnais-format-gtfs | Réseau urbain et interurbain Altigo | 20299 | CC du Briançonnais | Région Sud — Provence-Alpes-Côte d’Azur|
|https://transport.data.gouv.fr/datasets/donnees-gtfs-du-reseau-de-transport-public-cara-bus | Réseau urbain Cara'bus | 85447 | CA Royan Atlantique | Nouvelle-Aquitaine|
|https://transport.data.gouv.fr/datasets/donnees-gtfs-reseau-bus-pastel | Réseau urbain Pastel | 82117 | CA du Saint-Quentinois | Hauts-de-France|
|https://transport.data.gouv.fr/datasets/donnees-gtfs-reseau-tuc-communaute-dagglomeration-de-cambrai | Réseau urbain TUC | 82704 | CA de Cambrai | Hauts-de-France|
|https://transport.data.gouv.fr/datasets/eurostar-gtfs | Réseau européen Eurostar |  |  | National|
|https://transport.data.gouv.fr/datasets/export-quotidien-au-format-gtfs-du-reseau-de-transport-lignes-d-azur | Réseau urbain Lignes d'Azur | 556023 | Métropole Nice Côte d'Azur | Région Sud — Provence-Alpes-Côte d’Azur|
|https://transport.data.gouv.fr/datasets/fichier-des-donnees-theoriques-du-reseau-idelis-au-format-gtfs | Réseau urbain Idelis | 183088 | SM Pau Béarn Pyrénées mobilités | Nouvelle-Aquitaine|
|https://transport.data.gouv.fr/datasets/fichiers-gtfs-eurometropole-de-metz | Réseau urbain Le Met' | 228793 | Metz Métropole | Grand Est|
|https://transport.data.gouv.fr/datasets/fil-bleu-syndicat-des-mobilites-gtfs-gtfs-rt | Réseau urbain et périurbain Fil Bleu | 313634 | Syndicat des Mobilités de Touraine | Centre-Val de Loire|
|https://transport.data.gouv.fr/datasets/fr-200052264-t0002-0000-1 | Réseau urbain TAC | 124154 | Ardenne Métropole | Grand Est|
|https://transport.data.gouv.fr/datasets/fr-200052264-t0011-0000-1 | Réseau urbain Rezo | 28749 | CA du Grand Verdun | Grand Est|
|https://transport.data.gouv.fr/datasets/fr-200052264-t0012-0000-1 | Réseau urbain Mouvéo | 48701 | CA Epernay, Coteaux et Plaine de Champagne | Grand Est|
|https://transport.data.gouv.fr/datasets/fr-200052264-t0014-0000-1 | Réseau urbain Solea | 278186 | CA Mulhouse Alsace Agglomération | Grand Est|
|https://transport.data.gouv.fr/datasets/fr-200052264-t0027-0000-1 | Réseau urbain Colibri | 45231 | CC Terres Touloises | Grand Est|
|https://transport.data.gouv.fr/datasets/fr-200052264-t0031-0000-1 | Réseau urbain Citura | 301070 | CU du Grand Reims | Grand Est|
|https://transport.data.gouv.fr/datasets/fr-200052264-t0050-0000-1 | Réseau interurbain Fluo Grand-Est - Haut-Rhin (68) | 5682902 |  | Grand Est|
|https://transport.data.gouv.fr/datasets/fr-200052264-t0052-0000-1 | Réseau interurbain Fluo Grand-Est - Moselle (57) | 5682902 |  | Grand Est|
|https://transport.data.gouv.fr/datasets/gtfs-arvi | Réseau urbain ARVI | 47216 | CC Cluses-Arve et Montagnes | Auvergne-Rhône-Alpes|
|https://transport.data.gouv.fr/datasets/gtfs-reseau-fablio-lignes-regulieres | Réseau urbain Fablio | 55721 | CA de la Région de Château-Thierry | Hauts-de-France|
|https://transport.data.gouv.fr/datasets/gtfs-rna79-region-nouvelle-aquitaine-reseau-deux-sevres | Réseau interurbain des Deux-Sèvres (79) | 4371779 |  | Nouvelle-Aquitaine|
|https://transport.data.gouv.fr/datasets/gtfs-static-et-real-time-transporteur-thalys | Réseau européen Thalys |  |  | National|
|https://transport.data.gouv.fr/datasets/horaires-des-trains-trenitalia-france-du-25-05-2023-au-13-10-2023 | Horaires des trains à grande vitesse Frecciarossa Paris – Lyon – Milan |  |  | National|
|https://transport.data.gouv.fr/datasets/horaires-theoriques-au-format-gtfs-et-horaires-temps-reel-au-format-gtfs-rt-du-reseau-car-jaune-a-la-reunion | Réseau interurbain Cars Jaunes | 870870 |  | La Réunion|
|https://transport.data.gouv.fr/datasets/horaires-theoriques-des-bus-et-tramways-du-reseau-cts-au-format-gtfs | Réseau urbain CTS | 510718 | Eurométropole de Strasbourg | Grand Est|
|https://transport.data.gouv.fr/datasets/horaires-theoriques-du-reseau-ctrl-format-gtfs-de-lorient-agglomeration-1 | Réseau urbain CTRL | 210286 | CA Lorient Agglomération | Bretagne|
|https://transport.data.gouv.fr/datasets/horaires-theoriques-du-reseau-montelibus-montelimar-agglomeration-gtfs | Réseau urbain Montélibus | 69476 | CA Montélimar Agglomération | Auvergne-Rhône-Alpes|
|https://transport.data.gouv.fr/datasets/horaires-theoriques-du-reseau-urbain-de-laon-tul-gtfs | Réseau urbain TUL | 43219 | CA du Pays de Laon | Hauts-de-France|
|https://transport.data.gouv.fr/datasets/horaires-theoriques-et-temps-reel-des-bus-et-tramways-circulant-sur-le-territoire-de-brest-metropole | Réseau urbain Bibus | 215367 | Brest Métropole | Bretagne|
|https://transport.data.gouv.fr/datasets/horaires-theoriques-et-temps-reel-du-reseau-de-transport-marineo | Réseau urbain Marinéo | 113744 | CA du Boulonnais | Hauts-de-France|
|https://transport.data.gouv.fr/datasets/horaires-theoriques-reseau-choletbus | Réseau Urbain Choletbus | 107500 | CA Agglomération du Choletais | Pays de la Loire|
|https://transport.data.gouv.fr/datasets/lignes-arrets-et-horaires-de-transport-pour-cap-atlantique-lila-presquile-gtfs | Réseau urbain Lila Presqu'ile | 77073 | SM des transports collectifs routiers de la presqu'île de Guérande Atlantique | Pays de la Loire|
|https://transport.data.gouv.fr/datasets/localisation-des-arrets-ilevia-bus-metro-et-tram-gtfs-pictogrammes-du-reseau-ilevia | Réseau urbain ilévia | 1189961 | Métropole Européenne de Lille | Hauts-de-France|
|https://transport.data.gouv.fr/datasets/mobivie-reseau-urbain-vichy-communaute | Réseau urbain Mobivie | 84755 | CA Vichy Communauté | Auvergne-Rhône-Alpes|
|https://transport.data.gouv.fr/datasets/offre-de-transport-du-reseau-de-vannes-kiceo-donnees-theoriques-et-temps-reel | Réseau urbain Kicéo | 176603 | CA Golfe du Morbihan - Vannes Agglomération | Bretagne|
|https://transport.data.gouv.fr/datasets/offre-de-transports-jybus-a-rumilly | Réseau urbain Jybus | 32905 | CC Rumilly Terre de Savoie | Auvergne-Rhône-Alpes|
|https://transport.data.gouv.fr/datasets/offre-de-transports-reseau-tac-annemasse-agglo-decembre-2022 | Réseau urbain TAC | 92023 | CA Annemasse-Les Voirons-Agglomération | Auvergne-Rhône-Alpes|
|https://transport.data.gouv.fr/datasets/offres-de-services-bus-et-tramway-gtfs | Réseau urbain TBM | 824449 | Bordeaux Métropole | Nouvelle-Aquitaine|
|https://transport.data.gouv.fr/datasets/offre-transport-st-malo | Réseau urbain MAT | 86952 | CA du Pays de Saint Malo Agglomération | Bretagne|
|https://transport.data.gouv.fr/datasets/referentiel-topologique-du-reseau | Réseau urbain CarSud | 131514 | CA du Sud | La Réunion|
|https://transport.data.gouv.fr/datasets/reseau-couralin-grand-dax-1 | Réseau urbain Couralin | 57873 | CA du Grand Dax | Nouvelle-Aquitaine|
|https://transport.data.gouv.fr/datasets/reseau-de-transport-urbain-de-la-metropole-toulon-provence-mediterranee | Réseau urbain Mistral | 449118 | Métropole Toulon-Provence-Méditerranée | Région Sud — Provence-Alpes-Côte d’Azur|
|https://transport.data.gouv.fr/datasets/reseau-lagglo-bus-de-lagglo-foix-varilhes | Réseau urbain F'Bus | 32879 | CA Pays Foix-Varilhes | Occitanie|
|https://transport.data.gouv.fr/datasets/reseau-transport-urbain-de-bernay | Réseau urbain l'Bus | 56166 | CC Intercom Bernay Terres de Normandie | Normandie|
|https://transport.data.gouv.fr/datasets/reseaux-de-transports-en-commun-de-la-metropole-daix-marseille-provence-et-des-bouches-du-rhone | Agrégat de réseaux urbains et interurbains de la Métropole Aix-Marseille | 1920664 | Métropole d'Aix-Marseille-Provence | Région Sud — Provence-Alpes-Côte d’Azur|
|https://transport.data.gouv.fr/datasets/sngo-vernon-les-andelys-seine-normandie-agglo | Réseau urbain SNgo! | 84514 | CA Seine Normandie Agglomération | Normandie|
|https://transport.data.gouv.fr/datasets/tbk-offre-theorique-et-temps-reel-du-reseau-de-transports-du-pays-de-quimperle | Réseau urbain TBK | 57458 | CA Quimperlé Communauté | Bretagne|
|https://transport.data.gouv.fr/datasets/transports-publics-urbains-sur-le-territoire-de-la-ca-du-pays-de-gex | Réseau interurbain Pays de Gex | 100515 | CA du Pays de Gex | Auvergne-Rhône-Alpes|
|https://transport.data.gouv.fr/datasets/transports-urbains-st-cyr-s-mer | Navette interquartiers de Saint-Cyr-sur-Mer | 62527 | CA Sud Sainte Baume | Région Sud — Provence-Alpes-Côte d’Azur|
|https://transport.data.gouv.fr/datasets/transports-urbains-tad-ville-de-soissons | Transport à la demande - Soissons | 61390 | SI des transports urbains soissonnais (SITUS) | Hauts-de-France|
|https://transport.data.gouv.fr/datasets/transports-urbains-tus-ville-de-soissons | Réseau urbain TUS | 61390 | SI des transports urbains soissonnais (SITUS) | Hauts-de-France|


```sql
select distinct
	'https://transport.data.gouv.fr/datasets/' || d.slug url,
	d.custom_title,
	d.population,
	a.nom nom_aom,
	re.nom nom_region
from resource_history rh
join multi_validation mv on mv.resource_history_id = rh.id
join resource_metadata rm on rm.multi_validation_id = mv.id
join resource r on r.id = rh.resource_id
join dataset d on d.id = r.dataset_id
left join aom a on a.id = d.aom_id
left join region re on re.id = d.region_id or a.region_id = re.id
where mv.id in (
	select mv_id from (
		select rh.resource_id, max(mv.id) mv_id
		from resource_history rh
		join multi_validation mv on mv.resource_history_id = rh.id and mv.validator = 'GTFS transport-validator'
		where rh.resource_id is not null
		group by 1
	) t
)
and mv.max_error not in ('Fatal', 'Error') and now()::date <= (rm.metadata->>'end_date')::date and now()::date >= (rm.metadata->>'start_date')::date
and not custom_tags @> '{loi-climat-resilience}' and d.licence in ('fr-lo', 'lov2') and d.type = 'public-transit' and d.custom_title not like '%scolaire%'
```

**Comment by Miryad3108** [comment]
Merci @AntoineAugusti pour l'export 
Je regarderai ces JDD et ajouterai le tagg à partir de demain ou vendredi

**Comment by AntoineAugusti** [comment]
J'ai fait les exports et transmis les fichiers à @etalab/transport-bizdev et @Benoit-MINT

**Comment by Miryad3108** [comment]
Certains jeux de la liste n'ont pas été ajoutée car : 
- ressource qui n'est pas en HTTPS et sans réponse de l'administrateur du compte datagouv depuis plusieurs mois 
- nous n'avons pas assez d'historique pour savoir si les mises à jour seront faites à temps et de la bonne manière 
- nous avons déjà rencontré des soucis avec la qualité des données : mises à jour tardives récurrentes, ressource contenant des erreurs

**Comment by AntoineAugusti** [comment]
@Miryad3108 Super, merci pour le suivi !

**Comment by AntoineAugusti** [comment]
Liste mise à jour

|URL|Nom JDD|Population|AOM|Région|
|--- | --- | --- | --- | ---|
|https://transport.data.gouv.fr/datasets/horaires-des-trains-trenitalia-france-du-25-05-2023-au-13-10-2023 | Horaires des trains à grande vitesse Frecciarossa Paris – Lyon – Milan |  |  | National|
|https://transport.data.gouv.fr/datasets/lignes-814-818-1 | Lignes transfrontalières Pays de Gex - Canton de Vaud (Suisse) | 100515 | CA du Pays de Gex | Auvergne-Rhône-Alpes|
|https://transport.data.gouv.fr/datasets/transports-urbains-st-cyr-s-mer | Navette interquartiers de Saint-Cyr-sur-Mer | 62527 | CA Sud Sainte Baume | Région Sud — Provence-Alpes-Côte d’Azur|
|https://transport.data.gouv.fr/datasets/gtfs-la-navette-cc-haut-val-de-sevre | Navette La Crèche (CC Haut Val de Sèvre) | 31542 | CC Haut Val de Sèvre | Nouvelle-Aquitaine|
|https://transport.data.gouv.fr/datasets/gtfs-static-et-real-time-transporteur-thalys | Réseau européen Thalys |  |  | National|
|https://transport.data.gouv.fr/datasets/gtfs-rna79-region-nouvelle-aquitaine-reseau-deux-sevres | Réseau interurbain des Deux-Sèvres (79) | 4371779 |  | Nouvelle-Aquitaine|
|https://transport.data.gouv.fr/datasets/transports-publics-urbains-sur-le-territoire-de-la-ca-du-pays-de-gex | Réseau interurbain Pays de Gex | 100515 | CA du Pays de Gex | Auvergne-Rhône-Alpes|
|https://transport.data.gouv.fr/datasets/reseau-interurbain-tig | Réseau interurbain TIG | 149206 |  | Guyane|
|https://transport.data.gouv.fr/datasets/arrets-horaires-et-circuit-de-la-lignes-yeu-continent-gtfs | Réseau maritime Yeu-Continent | 4967 | L'Île-d'Yeu | Pays de la Loire|
|https://transport.data.gouv.fr/datasets/agen-gtfs-tad | Réseau TAD Agen | 103761 | CA Agglomération d'Agen | Nouvelle-Aquitaine|
|https://transport.data.gouv.fr/datasets/horaires-theoriques-du-reseau-artis | Réseau urbain Artis | 110743 | CU d'Arras | Hauts-de-France|
|https://transport.data.gouv.fr/datasets/gtfs-arvi | Réseau urbain ARVI | 47216 | CC Cluses-Arve et Montagnes | Auvergne-Rhône-Alpes|
|https://transport.data.gouv.fr/datasets/donnees-theoriques-et-temps-reel-du-reseau-axo-communaute-dagglomeration-creil-sud-oise | Réseau urbain AXO | 89121 | CA Creil Sud Oise | Hauts-de-France|
|https://transport.data.gouv.fr/datasets/donnees-gtfs-du-reseau-de-transport-public-cara-bus | Réseau urbain Cara'bus | 85447 | CA Royan Atlantique | Nouvelle-Aquitaine|
|https://transport.data.gouv.fr/datasets/horaires-theoriques-reseau-choletbus | Réseau Urbain Choletbus | 107500 | CA Agglomération du Choletais | Pays de la Loire|
|https://transport.data.gouv.fr/datasets/reseau-couralin-grand-dax-1 | Réseau urbain Couralin | 57873 | CA du Grand Dax | Nouvelle-Aquitaine|
|https://transport.data.gouv.fr/datasets/horaires-theoriques-du-reseau-ctrl-format-gtfs-de-lorient-agglomeration-1 | Réseau urbain CTRL | 210286 | CA Lorient Agglomération | Bretagne|
|https://transport.data.gouv.fr/datasets/donnees-theoriques-et-temps-reel-du-reseau-cypre-communaute-de-communes-du-pays-de-valois | Réseau urbain Cypré | 57020 | CC du Pays de Valois | Hauts-de-France|
|https://transport.data.gouv.fr/datasets/reseau-urbain-cacl-agglobus | Réseau urbain de la Communauté d'agglomération du Centre Littoral | 149206 | CA du Centre Littoral | Guyane|
|https://transport.data.gouv.fr/datasets/syndicat-mixte-des-transports-du-petit-cul-de-sac-marin | Réseau urbain du Syndicat Mixte des Transports du Petit Cul de Sac Marin | 165206 | SM des transports du Petit cul de sac marin | Guadeloupe|
|https://transport.data.gouv.fr/datasets/donnees-theoriques-et-temps-reel-du-reseau-duc-communaute-de-communes-de-laire-cantilienne | Réseau urbain DUC | 46209 | CC de l'Aire Cantilienne | Hauts-de-France|
|https://transport.data.gouv.fr/datasets/donnees-de-transport-en-commun-reseau-altigo-communaute-de-communes-du-brianconnais-format-gtfs | Réseau urbain et interurbain Altigo | 20299 | CC du Briançonnais | Région Sud — Provence-Alpes-Côte d’Azur|
|https://transport.data.gouv.fr/datasets/gtfs-reseau-fablio-lignes-regulieres | Réseau urbain Fablio | 55721 | CA de la Région de Château-Thierry | Hauts-de-France|
|https://transport.data.gouv.fr/datasets/filibus-urbain | Réseau urbain Filibus | 140187 | CA Chartres Métropole | Centre-Val de Loire|
|https://transport.data.gouv.fr/datasets/donnees-theoriques-et-temps-reel-du-reseau-flexobus-communaute-de-communes-de-laire-cantilienne | Réseau urbain Flexobus | 46209 | CC de l'Aire Cantilienne | Hauts-de-France|
|https://transport.data.gouv.fr/datasets/gtfs-noirmoutier-gratibus-ete-2023 | Réseau urbain Gratibus | 9459 | CC de l'Ile de Noirmoutier | Pays de la Loire|
|https://transport.data.gouv.fr/datasets/fichier-des-donnees-theoriques-du-reseau-idelis-au-format-gtfs | Réseau urbain Idelis | 183088 | SM Pau Béarn Pyrénées mobilités | Nouvelle-Aquitaine|
|https://transport.data.gouv.fr/datasets/reseau-de-transport-impulsyon-a-la-roche-sur-yon | Réseau urbain Impulsyon | 101782 | CA La Roche sur Yon - Agglomération | Pays de la Loire|
|https://transport.data.gouv.fr/datasets/donnees-theoriques-et-temps-reel-du-reseau-le-bus-communaute-de-communes-du-clermontois | Réseau urbain Le Bus | 38105 | CC du Clermontois | Hauts-de-France|
|https://transport.data.gouv.fr/datasets/donnees-theoriques-et-temps-reel-du-reseau-libbus-communaute-de-communes-du-pays-noyonnais | Réseau urbain Lib'Bus | 33279 | CC du Pays Noyonnais | Hauts-de-France|
|https://transport.data.gouv.fr/datasets/export-quotidien-au-format-gtfs-du-reseau-de-transport-lignes-d-azur | Réseau urbain Lignes d'Azur | 556023 | Métropole Nice Côte d'Azur | Région Sud — Provence-Alpes-Côte d’Azur|
|https://transport.data.gouv.fr/datasets/mobivie-reseau-urbain-vichy-communaute | Réseau urbain Mobivie | 84755 | CA Vichy Communauté | Auvergne-Rhône-Alpes|
|https://transport.data.gouv.fr/datasets/horaires-theoriques-du-reseau-montelibus-montelimar-agglomeration-gtfs | Réseau urbain Montélibus | 69476 | CA Montélimar Agglomération | Auvergne-Rhône-Alpes|
|https://transport.data.gouv.fr/datasets/fr-200052264-t0012-0000-1 | Réseau urbain Mouvéo | 48701 | CA Epernay, Coteaux et Plaine de Champagne | Grand Est|
|https://transport.data.gouv.fr/datasets/information-sur-les-transports-en-commun | Réseau urbain Muvitarra | 89654 | CA du Pays Ajaccien | Corse|
|https://transport.data.gouv.fr/datasets/donnees-theoriques-et-temps-reel-du-reseau-pass-thelle-bus-communaute-de-communes-thelloise | Réseau urbain Pass Thelle Bus | 62315 | CC Thelloise | Hauts-de-France|
|https://transport.data.gouv.fr/datasets/donnees-gtfs-reseau-bus-pastel | Réseau urbain Pastel | 82117 | CA du Saint-Quentinois | Hauts-de-France|
|https://transport.data.gouv.fr/datasets/donnees-theoriques-et-temps-reel-du-reseau-sablons-bus-communaute-de-communes-des-sablons | Réseau urbain Sablons Bus | 38956 | CC des Sablons | Hauts-de-France|
|https://transport.data.gouv.fr/datasets/sngo-vernon-les-andelys-seine-normandie-agglo | Réseau urbain SNgo! | 84514 | CA Seine Normandie Agglomération | Normandie|
|https://transport.data.gouv.fr/datasets/fr-200052264-t0002-0000-1 | Réseau urbain TAC | 124154 | Ardenne Métropole | Grand Est|
|https://transport.data.gouv.fr/datasets/donnees-gtfs | Réseau urbain Tanlib | 125100 | CA du Niortais | Nouvelle-Aquitaine|
|https://transport.data.gouv.fr/datasets/agen-gtfs-urbain | Réseau urbain Tempo Bus | 103761 | CA Agglomération d'Agen | Nouvelle-Aquitaine|
|https://transport.data.gouv.fr/datasets/donnees-theoriques-et-temps-reel-du-reseau-tohm-communaute-de-communes-des-pays-doise-et-dhalatte | Réseau urbain TOHM | 34901 | CC des Pays d'Oise et d'Halatte | Hauts-de-France|
|https://transport.data.gouv.fr/datasets/donnees-theoriques-et-temps-reel | Réseau urbain Tout'enbus | 32349 | SI de transport urbain Tout'en Bus | Auvergne-Rhône-Alpes|
|https://transport.data.gouv.fr/datasets/valable-du-14-fevrier-au-31-aout-2023 | Réseau urbain Transvilles | 354227 | SI de mobilité et d'organisation urbaine du Valenciennois | Hauts-de-France|
|https://transport.data.gouv.fr/datasets/donnees-gtfs-reseau-tuc-communaute-dagglomeration-de-cambrai | Réseau urbain TUC | 82704 | CA de Cambrai | Hauts-de-France|
|https://transport.data.gouv.fr/datasets/horaires-theoriques-du-reseau-urbain-de-laon-tul-gtfs | Réseau urbain TUL | 43219 | CA du Pays de Laon | Hauts-de-France|
|https://transport.data.gouv.fr/datasets/transports-urbains-tus-ville-de-soissons | Réseau urbain TUS | 61390 | SI des transports urbains soissonnais (SITUS) | Hauts-de-France|
|https://transport.data.gouv.fr/datasets/reseau-urbain-ville-de-vitre | Réseau urbain Vitobus | 83830 | CA Vitré Communauté | Bretagne|
|https://transport.data.gouv.fr/datasets/ce-jeu-de-donnees-contient-la-liste-des-arrets-des-horaires-et-des-parcours-theoriques-du-reseau-de-transport-urbain-et-interurbain-de-vrm | Réseau urbain VRM | 263636 | Valence-Romans déplacements | Auvergne-Rhône-Alpes|
|https://transport.data.gouv.fr/datasets/transports-urbains-tad-ville-de-soissons | Transport à la demande - Soissons | 61390 | SI des transports urbains soissonnais (SITUS) | Hauts-de-France|
