### ISSUE TITLE
Développement d'un espace réutilisateurs 

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#3231]
Nous développerons un espace réutilisateurs pour faciliter la gestion des données que réutilisent les réutilisateurs déclarés du PAN. 

Vu avec @AntoineAugusti : je vais contacter les réutilisateurs afin de m'assurer que les notifications que nous envisageons de rendre accessibles depuis l'espace réutilisateurs leur seront utiles. 
Je leur demanderai également si ils ont d'autres besoins. 

Nous envisageons de donner accès à :

### Des notifications propres à un jeu de données 
- [ expiration](https://doc.transport.data.gouv.fr/producteurs/gerer-la-qualite-des-donnees/sinscrire-aux-notifications#expiration-de-donnees) ;
- [indisponibilité](https://doc.transport.data.gouv.fr/producteurs/gerer-la-qualite-des-donnees/sinscrire-aux-notifications#ressources-indisponibles) ;
- [erreurs de validation](https://doc.transport.data.gouv.fr/producteurs/gerer-la-qualite-des-donnees/sinscrire-aux-notifications#erreurs-de-validation) ;
- ajout d'une ressource 
- suppression d'une ressource

### Des notifications qui ne sont pas propres à un jeu de données 
- modification d'une licence notamment au regard de l'article 122 ;
- publication d'un nouveau jeu de données
- suppression d'un nouveau jeu de données
- publication de nouveaux commentaires 

### Des notifications liés aux schémas transport sur transport.data.gouv.fr 
- évolution d'un schéma et donc modification de sa version

**Comment by AntoineAugusti** [comment]
À propos de l'inscription à des notifs liés à des schémas, datagouv indique ceci.

> il y a des travaux chez nous à ce sujet aussi, avec notamment les playlists et l'espace personnel qui fera peau neuve 

on s'en parle en septembre

**Comment by AntoineAugusti** [comment]
La suite dans #3803
