### ISSUE TITLE
Erreurs 500 sporadiques : connexions à la base de données

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#3233]
Signalées par @Miryad3108 ce matin.

**Comment by thbar** [comment]
On a eu un pic d'erreurs DBConnection :

https://transport-data-gouv-fr.sentry.io/issues/?project=6197733&query=is%3Aunresolved+DBConnection&referrer=issue-list&statsPeriod=14d

**Comment by thbar** [comment]
2700 erreurs autour de 9h07

https://transport-data-gouv-fr.sentry.io/issues/3016768499/?project=6197733&query=is%3Aunresolved&referrer=issue-stream&stream_index=4

**Comment by thbar** [comment]
Correction: il y en a beaucoup moins, l'essentiel venait de la recette.

**Comment by thbar** [comment]
Tickets associés:
- TRANSPORT-SITE-C9 https://transport-data-gouv-fr.sentry.io/issues/3812616020/?project=6197733&query=is%3Aunresolved+DBConnection&referrer=issue-stream&statsPeriod=14d&stream_index=0
- TRANSPORT-SITE-ED https://transport-data-gouv-fr.sentry.io/issues/3920226061/?project=6197733&query=is%3Aunresolved+DBConnection&referrer=issue-stream&statsPeriod=14d&stream_index=2
- TRANSPORT-SITE-2 https://transport-data-gouv-fr.sentry.io/issues/3016768499/?project=6197733&query=is%3Aunresolved+DBConnection&referrer=issue-stream&statsPeriod=14d&stream_index=1

**Comment by thbar** [comment]
J'étudie des outils APM.

**Comment by AurelienC** [comment]
Erreur 500 présente actuellement sur cette page également : https://transport.data.gouv.fr/aoms

**Comment by vdegove** [comment]
Je viens d’avoir une erreur 500 sur /aoms : https://transport-data-gouv-fr.sentry.io/issues/4267625129/?project=6197733&query=is%3Aunresolved&referrer=issue-stream&stream_index=0

**Comment by AntoineAugusti** [comment]
@AurelienC @vdegove C'est un autre problème, j'ouvre une autre issue https://github.com/etalab/transport-site/issues/3265

**Comment by thbar** [comment]
Depuis la mise en place de AppSignal, on peut faire le lien entre les actions et les erreurs générées.

Une des causes principales est:
- #3301 

Je clôture ici maintenant qu'on a des éléments plus précis.
