### ISSUE TITLE
Lien cassé dans la documentation (licence)

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#3234]
Sur https://doc.transport.data.gouv.fr/reutilisateurs/utilisation-par-les-reutilisateurs-de-donnees, le lien est affiché mais ne mène nulle part:

![CleanShot 2023-06-19 at 10 19 01@2x](https://github.com/etalab/transport-site/assets/10141/29b1a30a-f328-4d76-9d96-acd3811893cf)

**Comment by Miryad3108** [comment]
C'est réglé : j'ai mis le bon lien 
Merci @thbar
