### ISSUE TITLE
Pouvoir envoyer des mails depuis le backoffice

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#3245]
ça serait bien d'avoir la possibilité d'envoyer des mails depuis le backoffice pour prévenir les AOM/producteurs quand leurs données ne sont plus à jour/contiennent des erreurs 

Discussions : https://mattermost.incubateur.net/betagouv/pl/qqkbwcuo17ft5qsty7r1gz9cso

**Comment by thbar** [comment]
@AntoineAugusti avec les notifications actuelles, est-ce qu'on ne peut pas clôturer ?

**Comment by AntoineAugusti** [comment]
@thbar Non, la fonctionnalité envisagée est différente : les bizdevs indiquent des URLs/IDs ou je ne sais quoi, rédigent un sujet/e-mail et c'est envoyé automatiquement aux personnes indiquées comme producteurs.

**Comment by AntoineAugusti** [comment]
Ce n'est pas revenu sur le haut de la pile depuis un moment.

cc @etalab/transport-bizdev si jamais ceci est un besoin un jour
