### ISSUE TITLE
Carte d'exploration - Ajout IRVE statique

### ISSUE THREAD

**Issue by cyrilmorin** [etalab/transport-site#3246]
Ajouter sur [la carte d'exploration](https://transport.data.gouv.fr/explore) les stations IRVE. 
Baser l'objet sur l'id_station_itinerance du [le fichier consolidé statique](https://transport.data.gouv.fr/datasets/fichier-consolide-des-bornes-de-recharge-pour-vehicules-electriques)

On pourrait appliquer des traitements comme "Utiliser le 1er ID si les coordonnées sont différentes pour un même id_station_itinerance" ou ignorer les stations avec coordonnées 0;0 mais je propose de laisser l'info la plus brute possible car cela reflète la réalité et nous permettra de constater clairement certaines anomalies.

A voir si on essaie d'intégrer ou ignorer les stations avec la valeur "Non concerné" pour id_station_itinerance (surtout si on se base sur ce champ)

Info bulle :

nom_enseigne
id_station_itinerance
nom_station
nbre_pdc

A dispo pour en parler !

## Notes tech

- [ ] passer les checkbox des JDD affichés sur la carte en 2 colonnes

**Comment by AntoineAugusti** [comment]
@vdegove devrait s'en occuper dans les semaines à venir !

**Comment by cyrilmorin** [comment]
@vdegove dispo pour en parler quand tu t'y mets ;)

**Comment by thbar** [comment]
@vdegove dispo si tu veux discuter de façons de découper le chantier en plusieurs PR pour te faciliter la digestion (ainsi qu'à nous) pendant la suite de ton apprentissage !

**Comment by vdegove** [comment]
Ça marche, je suis pas encore dessus mais je te dis quand j’y suis !

**Comment by vdegove** [comment]
Je m’y colle. @cyrilmorin j’aurais besoin de comprendre le besoin métier sous-jacent, on s’appelle :)
