### ISSUE TITLE
Modifier logo du réutilisateur Mobireport 

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#3249]
Pouvez-vous remplacer le logo de Mobireport par celui là ? Rediriger vers cette page : https://matawan-mobility.com/
![Matawan](https://github.com/etalab/transport-site/assets/59559301/8f7a71a4-e063-42bc-afc3-4cc355fbb9fd)

![image](https://github.com/etalab/transport-site/assets/59559301/e87a0679-c485-4e75-be5e-0d3c9439227a)

**Comment by vdegove** [comment]
Remarque perso pour un peu de contexte : Matawan a racheté Mobireport en 2022 https://www.usine-digitale.fr/article/ubitransport-se-rebaptise-matawan-pour-s-imposer-a-l-international.N2139732
