### ISSUE TITLE
DataChecker : détecter quand un jeu de données a été mis en privé

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#3257]
Quand un JDD est mis en privé, l'API de data.gouv.fr répond avec un status_code `410 GONE`.

Ce cas n'est pas géré, on devrait détecter que ce JDD est supprimé.

Exemple de retour d'API : https://www.data.gouv.fr/api/1/datasets/horaires-temps-reels-reseau-a-citadina/

Il semble que depuis toujours l'API de data.gouv.fr répond une 410 et non une 404 https://github.com/opendatateam/udata/blob/59bd0e4b1604c7ec3609d2f773c7bf2f1655d73f/udata/core/dataset/api.py#L192

Code pertinent https://github.com/etalab/transport-site/blob/570d77dcb86f670fced4fd5cd95134c2e0b554b1/apps/transport/lib/transport/data_checker.ex#L69-L96

**Comment by AntoineAugusti** [comment]
J'ai pas fait le bon fix dans https://github.com/etalab/transport-site/pull/3119 visiblement

**Comment by vdegove** [comment]
@AntoineAugusti, pour clarifier "Ce cas n'est pas géré, on devrait détecter que ce JDD est supprimé." => est-ce que ça te va si du point de vue de l’application, on considère que c’est « désactivé » et du coup qu’on passe le flag active à false dans notre propre base de données ?

**Comment by AntoineAugusti** [comment]
@vdegove yep c'est bien ce qui est attendu !
