### ISSUE TITLE
Besoins en reporting interne IRVE (statique)

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#3272]
Suite à discussion avec @cyrilmorin aujourd'hui, je note ce qu'il fait à la main et pour lequel il aimerait une partie d'automatisation (à voir sous quelle forme ça peut se faire, une url protégée qu'on fait remonter dans un google sheet, un outil plus élaboré, à voir).

* Partir du dataset consolidation IRVE statique https://transport.data.gouv.fr/datasets/fichier-consolide-des-bornes-de-recharge-pour-vehicules-electriques
* Prendre la ressource associée
* Déterminer les `id_pdc_itinerance` présents plus d'une fois et différents de la valeur spéciale "non concerné" (certains fournisseurs ne font pas d'itinérance)
* Pour ces ids, obtenir datagouv_organization_or_owner, datagouv_resource_id, datagouv_dataset_id de façon générale
* Prendre également les cas où il y a plus d'un datagouv_organization_or_owner qui publient un même pdc (ce qui permet d'identifier un souci de gouvernance), en faisant une liste ou un compte "nombre de datagouv_organization_or_owner" par doublon

Attention: à terme datagouv_organization_or_owner deviendra "datagouv_organization" pour aller vers des ressources "officielles" non gérées par un individu.

À affiner !

**Comment by AntoineAugusti** [comment]
@cyrilmorin Est-ce que ceci peut être réglé par un Google Sheets / Excel avec plusieurs onglets ? Le premier onglet peut être utilisé pour les données en utilisant [IMPORTDATA](https://support.google.com/docs/answer/3093335?hl=en) et les d'autres onglets dédiés aux filtres permettant de mettre en évidence ces autres choses ?

**Comment by cyrilmorin** [comment]
@AntoineAugusti oui un google sheets / Excel devrait effectivement faire l'affaire !

**Comment by AntoineAugusti** [comment]
@cyrilmorin D'acc, dans ce cas pas besoin d'un dev ? Tu peux construire ceci ?

**Comment by cyrilmorin** [comment]
@AntoineAugusti 
je viens de regarder est c'est OK pour un petit fichier comme chargepoly 
![image](https://github.com/etalab/transport-site/assets/116101828/26d74bee-20d8-4d76-a326-912238c1c10c)

Mais KO pour le fichier consolidé :(
![image](https://github.com/etalab/transport-site/assets/116101828/30fcf7aa-f445-426a-ab13-58861312c6fa)

**Comment by thbar** [comment]
Qu'est-ce que ça donne sur ce point ?

**Comment by cyrilmorin** [comment]
@thbar Googlesheet avec IMPORTDATA n'est pas adapté pour un fichier de la taille du fichier consolidé, j'ai besoin d'un dev :)

**Comment by thbar** [comment]
@cyrilmorin ok merci on va en reparler alors.

**Comment by AntoineAugusti** [comment]
Un petit exemple de requête de travail

```sql
select
  g.payload->>'id_pdc_itinerance',
  g.payload->>'datagouv_resource_id',
  g.payload->>'datagouv_organization_or_owner',
  g.payload->>'datagouv_dataset_id'
from geo_data g
where g.geo_data_import_id = 1395 and g.payload->>'id_pdc_itinerance' in (
	select
	  g.payload->>'id_pdc_itinerance'
	from geo_data g
	where g.geo_data_import_id = 1395 and g.payload->>'id_pdc_itinerance' != 'Non concerné'
	group by 1
	having count(1) > 1
)
order by g.payload->>'id_pdc_itinerance'
```

qui donne sur les premières lignes
| id_pdc_itinerance | datagouv_resource_id | datagouv_organization_or_owner | datagouv_dataset_id |
|--- | --- | --- | ---|
|FRA16EWIIZ10011 | 5f2e4e91-ae95-485b-bc30-087640573f54 | communaute-dagglomeration-sophia-antipolis-casa | 5ae9d7aac751df5738c39823|
|FRA16EWIIZ10011 | 87194f3d-57fb-4b0e-a81c-c22cc4aa59e3 | izivia | 6112801882206048b39452c2|
|FRA16EWIIZ10012 | 5f2e4e91-ae95-485b-bc30-087640573f54 | communaute-dagglomeration-sophia-antipolis-casa | 5ae9d7aac751df5738c39823|
|FRA16EWIIZ10012 | 87194f3d-57fb-4b0e-a81c-c22cc4aa59e3 | izivia | 6112801882206048b39452c2|
|FRA16EWIIZ1011 | 5f2e4e91-ae95-485b-bc30-087640573f54 | communaute-dagglomeration-sophia-antipolis-casa | 5ae9d7aac751df5738c39823|
|FRA16EWIIZ1011 | 87194f3d-57fb-4b0e-a81c-c22cc4aa59e3 | izivia | 6112801882206048b39452c2|
|FRA16EWIIZ10111 | 5f2e4e91-ae95-485b-bc30-087640573f54 | communaute-dagglomeration-sophia-antipolis-casa | 5ae9d7aac751df5738c39823|
|FRA16EWIIZ10111 | 87194f3d-57fb-4b0e-a81c-c22cc4aa59e3 | izivia | 6112801882206048b39452c2|
|FRA16EWIIZ10112 | 5f2e4e91-ae95-485b-bc30-087640573f54 | communaute-dagglomeration-sophia-antipolis-casa | 5ae9d7aac751df5738c39823|
|FRA16EWIIZ10112 | 87194f3d-57fb-4b0e-a81c-c22cc4aa59e3 | izivia | 6112801882206048b39452c2|

@cyrilmorin on s'en reparle

**Comment by cyrilmorin** [comment]
@thbar je suis partagé car ça diminue vraiment parce que je suis à fond dessus, mais sur le long terme il faudrait pouvoir identifier ces anomalies. 
Ce besoin vient presque plus dans la catégorie score qualité "IRVE" de la base nationale

**Comment by thbar** [comment]
Ca paraît une bonne approche à plus long terme d'automatiser la "maintenance" si c'est pas trop coûteux à faire oui :smile: histoire de réduire le temps humain dessus.

**Comment by thbar** [comment]
Voir (un peu en lien):
- #3544

**Comment by thbar** [comment]
Poke @stephane-pignal @jmaupetit pour info.

**Comment by thbar** [comment]
On a d'autres besoins à présent (pré-consolidation) et d'autres outils, je clôture ce point pour le moment.
