### ISSUE TITLE
Jeux de données contenant des pièces jointes ODS

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#3286]
@maudetes [a indiqué](https://mattermost.incubateur.net/betagouv/pl/nutezwwk7tdnbj85rjqgtrh8or)

> Pour info, avec les modifs sur le moissonnage ODS à venir (via DCAT), seuls les exports alternatifs seront correctement exposés et donc moissonnés par data.gouv.fr

Les jeux de données suivants sont sur le PAN et sont des pièces jointes côté ODS.

|Nom JDD|URL|
|--- | ---|
|Gares et points d'arrêt Transilien en Ile-de-France | https://transport.data.gouv.fr/datasets/gares-et-points-darret-du-reseau-transilien|
|Passages à niveau du Réseau Ferré National | https://transport.data.gouv.fr/datasets/liste-des-passages-a-niveau|
|Réseau urbain et scolaire Synchro Bus | https://transport.data.gouv.fr/datasets/arrets-et-horaires-theoriques-bus|
|Réseau urbain Horizon | https://transport.data.gouv.fr/datasets/reseau-de-bus-urbain-horizon|
|Réseau urbain T2C | https://transport.data.gouv.fr/datasets/horaires-theoriques-du-reseau-de-transport-public-gtfs-du-syndicat-mixte-des-transports-en-commun-de-lagglomeration-clermontoise-smtc-ac|
|Réseau urbain TBM | https://transport.data.gouv.fr/datasets/offres-de-services-bus-et-tramway-gtfs|
|Zone à Faibles Emission - Eurométropole de Strasbourg - Aire réglementée | https://transport.data.gouv.fr/datasets/zone-a-faibles-emissions-mobilite|
|Zone à Faibles Emissions - Métropole d'Aix-Marseille-Provence | https://transport.data.gouv.fr/datasets/zfe-m|

Il faudrait passer à des "Exports"
<details>
    <summary>Requête SQL</summary>

```sql
select distinct d.custom_title, 'https://transport.data.gouv.fr/datasets/' || d.slug
from resource r
join dataset d on d.id = r.dataset_id
where url like '%attachments%' and url not like '%ubitransport%'
```
</details>

**Comment by maudetes** [comment]
Pour compléter, le retour que j'avais eu  de la part d'ODS sur la question de l'exposition pour moissonnage des exports alternatifs et des pièces jointes :
> Pièce jointe / export alternatifs : seuls les exports alternatifs seront disponibles en tant que distribution, il faut donc que les clients effectuent le changement - nous pourrons les y aider.

Lors de la migration vers le moissonnage DCAT, les pièces jointes qui étaient moissonnées précédemment ne seront pas supprimées de notre côté (mais plus synchronisées lors des futurs moissonnages).

**Comment by AntoineAugusti** [comment]
JDD|URL|Ressources|
|--- | --- | ---|
|Gares et points d'arrêt Transilien en Ile-de-France | https://transport.data.gouv.fr/datasets/gares-et-points-darret-du-reseau-transilien | Descriptif - Fichier Gares IDF.pdf|
|Passages à niveau du Réseau Ferré National | https://transport.data.gouv.fr/datasets/liste-des-passages-a-niveau | Classe des PN.xlsx|
|Réseau urbain et scolaire Synchro Bus | https://transport.data.gouv.fr/datasets/arrets-et-horaires-theoriques-bus | Licence ODbL_Grand Chambery.pdf|
|Réseau urbain Horizon | https://transport.data.gouv.fr/datasets/reseau-de-bus-urbain-horizon | GTFS _190623.zip|
|Réseau urbain T2C | https://transport.data.gouv.fr/datasets/horaires-theoriques-du-reseau-de-transport-public-gtfs-du-syndicat-mixte-des-transports-en-commun-de-lagglomeration-clermontoise-smtc-ac | gtfs-t2c_plus_scolaire.zip,gtfs-t2c.zip|
|Réseau urbain TBM | https://transport.data.gouv.fr/datasets/offres-de-services-bus-et-tramway-gtfs | keolis_tram.zip,keolis_bus.zip|
|Zone à Faibles Emission - Eurométropole de Strasbourg - Aire réglementée | https://transport.data.gouv.fr/datasets/zone-a-faibles-emissions-mobilite | zfe_emprise.png|
|Zone à Faibles Emissions - Métropole d'Aix-Marseille-Provence | https://transport.data.gouv.fr/datasets/zfe-m | ZFE-m-Marseille_arrete-22-322-CM.pdf|

**Comment by Miryad3108** [comment]
Je les ai tous contacté, je ferme l'issue
