### ISSUE TITLE
Mettre plus en évidence la page de vue des resources cachée derrière les boutons « + détail »

### ISSUE THREAD

**Issue by vdegove** [etalab/transport-site#3294]
Sur la page d’un jeu de données, le lien qui amène vers la page d’une resource est discret. La forme et le wording pourrait laisser croire que ça ne fait que déplier un bloc d’informations techniques (par exemple) alors que ça emmène (parfois, en fonction du type de resource) vers une page avec de vraies fonctionnalités : visualisation cartographique de la resource, rapport de validation, etc.

![Sélection_058](https://github.com/etalab/transport-site/assets/15861435/9cac396a-c035-4fb8-a022-d0d5f3916048)

On pourrait : 
- [ ] mettre un bouton primaire « voir la resource », à côté de télécharger
- [ ] au contraire transformer le bouton télécharger en lien
- [x] re-rajouter un bouton télécharger sur la page de la resource
- [ ] Rajouter sur la page d’une resource son historique propre

Après, le problème est que seuls certains types de resources ont des choses intéressantes sur la page + de détails, emmener sur cette page alors que on ne va rien y voir de plus que ce qui est dit sur la page des datasets, c’est pas forcément pertinent. Peut-être revoir ce fonctionnement en fonction des types de resources ? Aussi, les resources communautaires n’ont pas de page détails.

**Comment by vdegove** [comment]
@AntoineAugusti j’avais oublié que j’avais fait cette issue en draft ;) C’est bon j’ai complété.

**Comment by ptitfred** [comment]
> bouton télécharger sur la page de la resource

Sauf erreur de ma part c'est le cas désormais.

**Comment by ptitfred** [comment]
>  mettre un bouton primaire « voir la resource », à côté de télécharger

Je me serais attendu à ce que la carte entière soit cliquable ou à défaut le titre.
