### ISSUE TITLE
Allow AOs to claim their organisation

### ISSUE THREAD

**Issue by maukoquiroga** [etalab/transport-site#33]
When I log in for the first time,
    And I'm asked to which my organisation is,
    I want to have my organisation already listed,
    so I can claim it to publish my data.

Scénario :

- [x] I can see search for my AOs #33 #34 
- [ ] I have an explanation of what I'm doing
- [ ] I can select and submit one AO.
- [ ] I have feedback that everything is OK and I'm not supposed to do anything else.

![photo](https://user-images.githubusercontent.com/329236/30537842-a464d030-9c6b-11e7-9c8b-d9da89e70d96.jpg)

**Comment by Tristramg** [comment]
Closing as over a year old.
