### ISSUE TITLE
Preloading des validations non nécessaire

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#3324]
En lien avec:
- #3302 (qui m'a aider à voir où ça valait le coup d'aller regarder)
- https://github.com/etalab/transport-site/pull/3320 (qui m'a permis de détecter ce bug)

Une grosse lenteur a été constatée ce matin (https://appsignal.com/transport-dot-data-dot-gouv-dot-fr/sites/64a54ec183eb67b60f03fb6e/actions/web/TransportWeb.API.DatasetController%23by_id?timeframe=R7D), avec jusqu'à 330 requêtes par minute (20k par heure) sur `/api/datasets/{:id}`:

<img width="856" alt="CleanShot 2023-07-17 at 16 32 11@2x" src="https://github.com/etalab/transport-site/assets/10141/30f4d4cb-1948-44f7-99af-7ff0ed30c908">

J'ai pu fouiller de plus près et comprendre un souci en particulier (voir #3320).

Le endpoint `/api/datasets/{:id}` fait un preloading des validations ici:

https://github.com/etalab/transport-site/blob/ce6f9046b1d83790f6812ced3409130c91e2303a/apps/transport/lib/transport/history_fetcher.ex#L46

via:

https://github.com/etalab/transport-site/blob/ce6f9046b1d83790f6812ced3409130c91e2303a/apps/transport/lib/transport_web/api/controllers/datasets_controller.ex#L161

J'ai pu vérifier dans #3320 que le preload des validations était actuellement inutile, car si on l'enlève, l'output JSON de l'API reste le même (il est nécessaire à d'autres endroits toutefois !).

Je crée ce ticket pour conserver une trace et y faire référence.

**Comment by vdegove** [comment]
Qu’est-ce que le preload des validations ?

**Comment by thbar** [comment]
@vdegove bonne question:
- le preloading fait référence à l'opération Ecto pour précharger une association (https://hexdocs.pm/ecto/Ecto.Query.html#preload/3)
- dans le cas présent on chargeait les validations associées à la requête (voir https://github.com/etalab/transport-site/blob/ce6f9046b1d83790f6812ced3409130c91e2303a/apps/transport/lib/transport/history_fetcher.ex#L46) mais ce n'était pas nécessaire

On pourra détailler davantage ensemble ou ici.

**Comment by vdegove** [comment]
Ahh @thbar ok, merci ! Non mais j’ai cru qu’on parlait des validations au sens Ecto / Phoenix ([vérification sur un changeset avant enregistrement](https://hexdocs.pm/ecto/3.10.1/Ecto.Changeset.html#module-validations-and-constraints)) alors qu’on parle de validations au sens métier transport (validité de la donnée de transport). Du coup je comprenais pas, ça faisait pas sens, et effectivement ;)

**Comment by thbar** [comment]
L'optimisation réalisée dans:
- #3326

a bien porté ses fruits:

![image](https://github.com/etalab/transport-site/assets/10141/2081eb20-95f9-4729-8baa-23eb73c15931)

Je clôture.
