### ISSUE TITLE
Formattage du code (désiré ou non ?) par VSCode

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#3329]
Quand je travaille avec VSCode, et le réglage par défaut dans les settings:

```JSON
{
  "editor.formatOnSave": false,
}
```

Je finis en sauvant des fichiers par avoir du code formatté différemment, à des endroits que je n'ai pas touché. Ca rend le commit plus difficile.

Voir avec @etalab/transport-tech ce qui se produit chez chacun, et homogénéiser la configuration.

Je ne sais plus à quel point ça interagit avec `mix format` ou pas etc, à vérifier.

Bref, l'idée étant de ne pas avoir de "faux changements" (quitte à reformatter toute la codebase d'un coup si nécessaire) dans VSCode, mais c'est sûrement lié à mon setup.

**Comment by thbar** [comment]
Explication probable:
- https://github.com/elixir-lsp/vscode-elixir-ls/discussions/224

**Comment by vdegove** [comment]
Je n’ai pas ce problème, ça ne va pas formatter des trucs à des endroits pas touchés. Mais en fait, ça ne formatte rien du tout, et j’aurais presque envie de mettre ce setting à true pour que ça me fasse un coup de mix format à l’enregistrement. Parce que je git push régulièrement du code non formatté…

**Comment by AntoineAugusti** [comment]
Je n'utilise pas VS Code pour ma part. Visiblement le plugin associé n'appelle pas vraiment `mix format`, ce ne sera donc peut-être pas adapté.

Peut-être utiliser directement `mix format` et un Git pre-commit hook si vous oubliez trop souvent ?

**Comment by thbar** [comment]
Ok donc c'est mon cas particulier :smile: je fais `mix format` et j'oublie rarement donc pas de souci de ce côté là, c'est davantage pour les diffs dans git que c'est embêtant. Je clôture étant le seul à être dans le cas, et j'irai me renseigner. Merci pour vos retours !

**Comment by vdegove** [comment]
(C’est quand même dommage que ce truc ne soit pas compatible avec le formatage de git format, en fait, parce que pratique.)
