### ISSUE TITLE
Rappel ponctuel des abonnements aux notifications pour les producteurs

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#3337]
## Fonctionnalité envisagée
Envoyer un e-mail aux contacts identifiés comme producteur les informant qu'ils sont susceptibles de recevoir des notifications pour plusieurs jeux de données où ils ont un rôle de production de la donnée. Leur rappeler le fonctionnement de cette fonctionnalité. Inviter à mettre à jour ces abonnements, inscrire d'autres personnes.

## Finalités
- Informer les producteurs des notifications qu'ils sont susceptibles de recevoir
- Maintenir des abonnements aux notifications pertinents
- Amener des producteurs sur le PAN, en particulier sur l'espace producteur
- Mieux suivre les changements de postes, les départs/arrivées de collaborateurs
- Initier des discussions avec notre équipe

## Fréquence
3 fois par an ? Octobre, février et juin ?

## Points d'attention
- Attention au contenu de la notification : certains destinataires peuvent avoir été inscrits d'office aux notifications. Il faut être bien pédagogique. 
- Notre abonnement à Mailjet (e-mails ponctuels) a une limite de 200 e-mails/jour dans son plan gratuit, prévoir d'étaler ces envois sur plusieurs jours (envoyer uniquement en jours ouvrés).

**Comment by AntoineAugusti** [comment]
Sur les moments d'envoi. @Miryad3108 :

> La temporalité est bien aussi je trouve parce qu'il peut y avoir un fort turn over 
> Peut être novembre plutôt qu'octobre et mars plutôt que février parce qu'ils sont souvent sous l'eau septembre/octobre et janvier/février

**Comment by Miryad3108** [comment]
Bonjour, 

Vous êtes identifiés comme responsable de la qualité des données publiées au nom de votre Autorité organisatrice des mobilités (**ou juste "organisation" au lieu d'AOM vu qu'il y a aussi des opérateurs comme Bird etc**.) sur transport.data.gouv.fr. Pour vous faciliter la gestion de ces données, vous pouvez activer des notifications depuis [votre espace producteur du Point d'accès national.](https://transport.data.gouv.fr/infos_producteurs). Elles vous permettront d'être averti de l'[expiration de vos ressources, des erreurs qu'elles peuvent contenir et de leur potentielle indisponibilités](https://doc.transport.data.gouv.fr/producteurs/gerer-la-qualite-des-donnees/sinscrire-aux-notifications#les-differents-types-de-notifications). Notre équipe a déjà activé certaines notifications. N'hésitez pas à les modifier selon vos besoins. 


Bien à vous,

**Comment by AntoineAugusti** [comment]
@Miryad3108 J'envisageais de lister les JDD pour lesquels ils sont susceptibles de recevoir des notifications et d'indiquer qu'ils peuvent modifier. Tu en penses quoi ? Sans ceci j'ai peur que ce soit simplement ignoré.

**Comment by Miryad3108** [comment]
Je ne pensais pas que ça serait un mail "personnalisé", si c'est le cas je pense que c'est une bonne idée oui de lister les JDD

**Comment by AntoineAugusti** [comment]
@Miryad3108 Ah yes plutôt personnalisé pour avoir de l'engagement. Ça t'inspire ?

**Comment by Miryad3108** [comment]
**Si il y a déjà des notifications activées :** 

"Bonjour,

Vous gérez la publication du jeu de données $NOM_JDD + URL sur transport.data.gouv.fr. 
Pour vous faciliter la gestion de ces données, vous pouvez activer des notifications depuis [votre espace producteur du Point d'accès national](https://transport.data.gouv.fr/infos_producteurs). Elles vous permettront d'être averti de l'[expiration de vos ressources, des erreurs qu'elles peuvent contenir et de leur potentielle indisponibilité](https://doc.transport.data.gouv.fr/producteurs/gerer-la-qualite-des-donnees/sinscrire-aux-notifications#les-differents-types-de-notifications). 
Notre équipe a déjà activé les notifications [choisir selon les notifications activées] : 
- Expiration d'une ressource 
- Indisponibilité d'une ressource
- Erreurs sur une ressource 
N'hésitez pas à les modifier selon vos besoins.

*Si +1 personne abonnées aux notifications*
Les autres personnes inscrites à ces notifications sont :  [lister les autres personnes associées aux notifications de ce JDD]
Si certaines d'entre elles ne font plus partie de votre organisation, vous pouvez supprimer leur accès depuis data.gouv.fr. Si d'autres personnes administrent vos données, elles peuvent [rejoindre votre organisation sur data.gouv.fr](https://doc.transport.data.gouv.fr/producteurs/comment-et-pourquoi-les-producteurs-de-donnees-utilisent-ils-le-pan/creer-une-organisation-sur-data.gouv.fr).


Bien à vous,"

**Si il n'y a pas de notifications activées**

"Bonjour,

Vous gérez la publication du jeu de données $NOM_JDD + URL sur transport.data.gouv.fr. 
Pour vous faciliter la gestion de ces données, vous pouvez activer des notifications depuis [votre espace producteur du Point d'accès national](https://transport.data.gouv.fr/infos_producteurs). Elles vous permettront d'être averti de l'[expiration de vos ressources, des erreurs qu'elles peuvent contenir et de leur potentielle indisponibilité](https://doc.transport.data.gouv.fr/producteurs/gerer-la-qualite-des-donnees/sinscrire-aux-notifications#les-differents-types-de-notifications). 

Les autres personnes pouvant s'inscrir à ces notifications en tant qu'administrateur de votre compte sont :  [lister les autres personnes associées aux notifications de ce JDD]
Si certaines d'entre elles ne font plus partie de votre organisation, vous pouvez supprimer leur accès depuis data.gouv.fr. Si d'autres personnes administrent vos données, elles peuvent [rejoindre votre organisation sur data.gouv.fr](https://doc.transport.data.gouv.fr/producteurs/comment-et-pourquoi-les-producteurs-de-donnees-utilisent-ils-le-pan/creer-une-organisation-sur-data.gouv.fr).


Bien à vous,"

**Comment by Miryad3108** [comment]
@AntoineAugusti je me note de mettre à jour la doc sur le fait de rejoindre une organisation data.gouv.fr
