### ISSUE TITLE
Erreur 500 espace producteur liste de ressources

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#3339]
[Voir sur Sentry](https://transport-data-gouv-fr.sentry.io/issues/4887179804/)

Survient sur `https://transport.data.gouv.fr/resources/update/datasets/:dataset_datagouv_id/resources` quand le JDD a été supprimé.

Avoir une 404 dans ce cas ?

**Comment by vdegove** [comment]
Hum, alors je veux bien votre avis là dessus @AntoineAugusti et @thbar.

Ça arrive avec m’importe quel GET sur `resources/update/datasets/n_importe_quoi/resources` avec `n_importe_quoi ` qui correspond à un dataset qui n’existe pas sur data.gouv.fr. Dans la vue, la variable `@dataset`, qui provient non de notre BDD mais directement d’un appel API à data.gouv.fr est alors un array vide (`[ ]`) et `[ ]["id"]` donne une erreur.

Cette variable @dataset est assignée dans `apps/transport/lib/transport_web/controllers/resource_controller.ex#resources_list` avec un appel à la fonction `assign_or_flash/3`, qui elle même fait l’appel à l’API data.gouv.fr. J’ai ça dans mon terminal  : ```{:ok, %{body: %{"message" => "The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again. You have requested this URI [/api/1/datasets/uirsteurst/] but did you mean /api/1/datasets/suggest/ or /api/1/datasets/<dataset:dataset>/resources/ or /api/1/datasets/r/<uuid:id> ?"}, status_code: 404}}```

Je pourrais modifier cette fonction assign_or_flash (ou le wrapper de l’API datagouv ? pourquoi on a un symbole :ok pour une 404 ?), faire en sorte qu’elle renvoie une erreur en cas de 404, et du coup le contrôleur qui rend notre 404, mais je me demande si il ne faut pas plutôt arrêter d’utiliser cette fonction là, pour ces besoins là. Elle a été introduite il y a 4 ans ici https://github.com/etalab/transport-site/pull/687 On en avait discuté l’autre jour avec @AntoineAugusti et on ne comprenait pas très bien pourquoi on s’appuyait sur l’API de datagouv plutôt que notre propre base de données. J’imagine qu’on veut éviter de potentiellement upload une resource sur un jeu de donnée qui a été supprimé de datagouv ?

**Comment by AntoineAugusti** [comment]
@vdegove Sinon on regarde la fréquence d'occurence de cette erreur qui doit être anecdotique et on ne ferait rien jusqu'à ce soit un truc à gérer. Laisser une notre côté Sentry avec cette issue.

Mais pour réparer il faudrait probablement modifier le retour de notre client API datagouv.

L'utilisation de l'API de datagouv permet d'avoir un état toujours cohérent avec la réalité de datagouv comme le refresh de JDD/ressources se fait 1 fois par jour au pire côté PAN.

**Comment by vdegove** [comment]
Occurrence toujours très faible. Remarque : si un jour on namespace dans l’espace producteur tout ce qui est édition de resources, ça vaut le coup de s’en occuper. (Je faisais un tour.)
