### ISSUE TITLE
[BO-Contact] Autocompletion - Recherche dans drop down list contact

### ISSUE THREAD

**Issue by cyrilmorin** [etalab/transport-site#3344]
Salut,

Pouvez-vous améliorer la recherche de contacts afin de faciliter la recherche et ne pas en créer de doublon svp ?

[Page Gestion des contacts](https://transport.data.gouv.fr/backoffice/contacts)
1- Ajouter autocompletion avec liste comme le triangle le suggère
![image](https://github.com/etalab/transport-site/assets/116101828/9d911f72-9bc7-4436-b18b-77ced471b7a7)

2- Rechercher avec critère "contient". Actuellement la recherche ne trouve pas si le nom/prénom n'est pas complètement saisi
Ex: avec [Mustaph ](https://transport.data.gouv.fr/backoffice/contacts?q=mustaph)

![image](https://github.com/etalab/transport-site/assets/116101828/de20fe66-4d28-4c4e-b934-48ca6d54506f)

[Page BO dataset](https://transport.data.gouv.fr/backoffice/datasets/950/edit#notification_subscriptions)
Ne pas prendre en compte les accents exemple Emilie vs Émilie
![image](https://github.com/etalab/transport-site/assets/116101828/36fe221b-5da5-4510-9250-6f25468c5136)

![image](https://github.com/etalab/transport-site/assets/116101828/261e7612-4277-468d-85e5-016d6ffeda41)

**Comment by AntoineAugusti** [comment]
Les autocomplete dans le BO sont fait de manière assez chiche, avec du [datalist](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist), qui se base sur une liste d'options possible et permet de "refine" à la saisie. Ce serait assez couteux d'avoir de l'autocomplete qui analyse la saisie mais on peut surement faire un peu mieux.
