### ISSUE TITLE
Lister un nombre plus réduit d’historique de resources sur la page des datasets

### ISSUE THREAD

**Issue by vdegove** [etalab/transport-site#3355]
@Benoit-MINT indique que la liste des versions historiques des resources prend un peu trop de place sur la page d’un dataset, il faudrait la réduire.

Perso, je me demande si il ne faudrait pas carrément la migrer sur la page d’une resource, et mettre la page de détails des resources plus en évidence (c’est à dire que le bouton discret «+ de détails» devient un vrai bouton bien visible).

**Comment by AntoineAugusti** [comment]
Voir https://github.com/etalab/transport-site/issues/3294 (pas de contenu pour le moment)
