### ISSUE TITLE
Bornes IRVE Rouen qui ne sont plus dans la Base nationale

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-site#3371]
Melanie Le Jean de Rouen nous a contacté 
" Je me permets de vous contacter car je ne vois plus la Métropole de Rouen dans le fichier consolidé des bornes IRVE. Savez vous s’il y a un problème du côté de GIREVE ?

J’ai contacté notre opérateur (Bouygues) et de leur côté normalement tout fonctionne."

Possible de creuser et lui répondre @thbar ?

**Comment by thbar** [comment]
Questions qu'on peut se poser:
- est-ce que c'est bien apporté via la consolidation GIREVE, ou via la consolidation data gouv (qui inclut celle de GIREVE°

**Comment by AntoineAugusti** [comment]
J'ai répondu [au ticket](https://app.frontapp.com/open/cnv_yyeu4ie?key=1eZlwMeL-tWC4ELJP24682ZX6Nr7v98V), on suit là-bas
