### ISSUE TITLE
Mise à jour Phoenix 1.6 -> 1.7 à prévoir

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#3393]
En travaillant sur:
- #3390 

Je re-remarque qu'on est sur Phoenix 1.6, et que la 1.7 est sortie depuis 6 mois (https://hex.pm/packages/phoenix/versions) et a été mise à jour plusieurs fois.

Je crée le ticket pour noter ce qui est utile.

- [Upgrading from Phoenix v1.6.x to v1.7.0](https://gist.github.com/chrismccord/00a6ea2a96bc57df0cce526bd20af8a7) - le guide par Chris McChord

Éléments optionnels mais à considérer:
- [Mise à jour Elixir 1.14](https://gist.github.com/chrismccord/00a6ea2a96bc57df0cce526bd20af8a7#optional-upgrade-to-elixir-v1140) -> déja fait
- [Update your app to support Phoenix.VerifiedRoutes](https://gist.github.com/chrismccord/00a6ea2a96bc57df0cce526bd20af8a7#optional-update-your-app-to-support-phoenixverifiedroutes) -> intéressant à faire
- [Migrate from Phoenix.View to Phoenix.Component](https://gist.github.com/chrismccord/00a6ea2a96bc57df0cce526bd20af8a7#optional-migrate-from-phoenixview-to-phoenixcomponent) -> pas obligatoire pour le moment, mais il serait bon de ne pas accumuler de la dette là dessus et de commencer à bouger

Attention à:
- #3433

**Comment by vdegove** [comment]
Concernant la migration vue -> composants, il y a un gros pavé qui explique le pourquoi du comment et les implications dans le blogpost de sortie, ici https://phoenixframework.org/blog/phoenix-1.7-final-released dans la section «Unified function components across Controllers and LiveViews»

Extrait utile : «Most large, established applications are probably best served by continuing to depend on Phoenix.View.» 

Si ça se fait, ça semble être l’objet d’un ou plusieurs tickets à part.

À savoir : ils ont retiré les références à Phoenix.View dans les guides d’intro de Phoenix 1.7, ce qui explique que j’étais un peu perdu entre le code du PAN et la documentation et les appellations des différents concepts «attends, un composant c’est pas une vue en fait ?». À garder en tête pour les prochains embarquements dev.
![Sélection_074](https://github.com/etalab/transport-site/assets/15861435/ae327962-91c2-40da-b8e0-2202dbfab1ca)
![Sélection_075](https://github.com/etalab/transport-site/assets/15861435/5286d164-8a3b-45ac-b7fd-dc49f7ec05ca)

**Comment by AntoineAugusti** [comment]
Les verified routes ont un problème chez nous actuellement, voir #3695
