### ISSUE TITLE
Serveur de recette cassé

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#3394]
En essayant de tester:
- #3390 

Je vois qu'on a des 500:

```
2023-08-13T12:22:16+02:00 ** (Postgrex.Error) ERROR 42703 (undefined_column) column d0.details does not exist

SELECT d0."id", d0."dataset_id", d0."topic", d0."score", d0."timestamp", d0."details" FROM "dataset_score" AS d0 WHERE (d0."id" IN (SELECT DISTINCT first_value(sd0."id") OVER (PARTITION BY sd0."topic" ORDER BY sd0."timestamp" DESC) FROM "dataset_score" AS sd0 WHERE ((sd0."dataset_id" = $1) AND sd0."topic" = ANY($2))))
```

**Comment by AntoineAugusti** [comment]
J'ai été investiguer et voici ce que j'ai fait.

- mis `master` sur prochainement
- vérifié que toutes les migrations ont été exécutées
- constaté que le problème était toujours présent
- regardé la PR qui a ajouté `dataset_score`, constaté que le champ `details` avait été ajouté en court de route https://github.com/etalab/transport-site/pull/3177
- j'ai fait l'hypothèse que cette branche a été déployée sur prochainement avant l'ajout de ce champ et j'ai donc ajouté ce champ à la main `alter table dataset_score add column details jsonb;`
- j'ai vérifié que les tables/colonnes étaient les mêmes en prod et staging 

```sql
SELECT table_name, column_name, ordinal_position, is_nullable, data_type
FROM information_schema.columns
WHERE table_schema = 'public'
ORDER BY 1, 2
```

**Comment by thbar** [comment]
Super, merci @AntoineAugusti pour le fix et le rapport !
