### ISSUE TITLE
API: ces champs sont-ils obligatoirement présents?

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#3396]
Durant:
- #3351

Je me pose une question concernant des valeurs à null là où une valeur string est apparemment attendue.

```
1) test gtfs-rt features are filled (TransportWeb.API.DatasetControllerTest)
     apps/transport/test/transport_web/controllers/api/datasets_controller_test.exs:482
     Value does not conform to schema DatasetsResponse: 

     null value where string expected at /0/aom/siren
     null value where string expected at /0/licence
     null value where string expected at /0/title
```

Je vais aller voir si ces champs sont toujours fournis, et si oui adapter le test, si non voir comment modifier la spécification associée.

**Comment by thbar** [comment]
Réponse: ça dépend du champ. L'AOM SIREN n'est pas obligatoire, les autres semblent être tout le temps là.

```
❯ jq -r ".[] .aom.siren" datasets | grep null | wc -l
     166

❯ jq -r ".[] .title" datasets | grep null | wc -l
       0

❯ jq -r ".[] .licence" datasets | grep null | wc -l
       0
```

@AntoineAugusti ça te parle comme résultat ?

**Comment by thbar** [comment]
Voir #3399:
- `.title` dans l'API provient de `custom_title`, toujours renseigné apparemment
- idem pour `.licence`

Je vais passer `.aom.siren` en nullable et je clôture ici.

**Comment by AntoineAugusti** [comment]
@thbar Pour le SIREN d'une AOM non renseigné, ce sont des JDD rattachés à des régions ou des communes ?

**Comment by thbar** [comment]
@AntoineAugusti je n'ai pas regardé en détail pour le moment ...

**Comment by thbar** [comment]
@AntoineAugusti oui c'est bien le cas pour la partie AOM.

Voir:
- #3422

**Comment by thbar** [comment]
Ok je pense que c'est à présent plus clair, voir la doc API.
