### ISSUE TITLE
Souci de RAM sur le validateur Rust

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#3402]
La validation https://transport.data.gouv.fr/datasets/reseau-urbain-et-interurbain-dile-de-france-mobilites#backed-up-resources ne passe plus depuis quelques jours (remonté par @AntoineAugusti).

Via Grafana, on voit le reboot de 5h:

<img width="1196" alt="CleanShot 2023-08-16 at 11 57 08@2x" src="https://github.com/etalab/transport-site/assets/10141/8abf7c4b-526f-4c2c-a3c2-356b0339df56">

<img width="584" alt="CleanShot 2023-08-16 at 11 58 29@2x" src="https://github.com/etalab/transport-site/assets/10141/a1962cd4-a4a7-4550-8421-96b792679f19">

**Comment by thbar** [comment]
L'état semble par ailleurs bancal:

<img width="616" alt="CleanShot 2023-08-16 at 11 56 12@2x" src="https://github.com/etalab/transport-site/assets/10141/8b12a0ac-6714-4869-8a21-652df30df0ed">

**Comment by AntoineAugusti** [comment]
À noter que le souci est réparé en passant à une instance L. Voir sur [Mattermost](https://mattermost.incubateur.net/betagouv/pl/xqngnmjw4ingubw1j619ueidxa)

**Comment by thbar** [comment]
Suggestion de CleverCloud: https://www.clever-cloud.com/doc/administrate/scalability/#vertical-scaling

Cela dit ça ne serait pas optimal, ça voudrait dire qu'il faut une gestion de retry pour que ça fonctionne (si je comprends bien, la machine serait coupée de toute façon, la RAM n'est pas allouée à chaud).

J'attends leur retour.

**Comment by thbar** [comment]
Comme je le pensais: pas possible d'augmenter la RAM à chaud.

**Comment by thbar** [comment]
<img width="344" alt="CleanShot 2023-09-21 at 11 31 01@2x" src="https://github.com/etalab/transport-site/assets/10141/a522c85a-6614-4cdb-8d44-c1e04784db33">

Dans l'immédiat ça a l'air OK modulo quels jours difficiles de temps en temps.

Je ne sais pas si du coup certaines ressources ne sont "jamais validées" suite à exhaust de retries.

@AntoineAugusti je clôture pour le moment, on ré-ouvre si besoin ?

**Comment by AntoineAugusti** [comment]
@thbar

```sql
select count(1)
from resource_history rh
left join multi_validation mv on mv.resource_history_id = rh.id
where rh.payload->>'format' = 'GTFS' and mv.id is null
```

donne 0 ! Il me semble qu'il y a pas du code qui est censé faire la voiture balai et réessayer les validations qui n'ont pas été effectuées.
