### ISSUE TITLE
Détecter automatiquement URLs mortes sur real_time_providers.csv

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#3405]
Suite à #3404, il serait bien de pouvoir identifier les URLs qui n'existent plus afin de les mettre à jour. Peut-être en CI, comme fait dans https://github.com/etalab/transport-site/pull/3378

**Comment by AntoineAugusti** [comment]
@cyrilmorin [se demandait](https://mattermost.incubateur.net/betagouv/pl/494odpnxubg55fe3qem154q1ie) si on n'allait pas supprimer [cette page](https://transport.data.gouv.fr/real_time), peut-être attendre un peu.

**Comment by thbar** [comment]
Oui je me faisais la même réflexion !
