### ISSUE TITLE
Supprimer les multiparts uploads sur Scaleway

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#3406]
https://www.scaleway.com/en/docs/storage/object/api-cli/lifecycle-rules-api/#setting-rules-for-incomplete-multipart-uploads

Adapter [les lifecycle rules](https://github.com/etalab/transport-site/tree/master/docs/scaleway) de Scaleway.

Exemple actuel : en staging on a 575 Mo d'objets mais un bucket size de 5,65 GB 😬

**Comment by thbar** [comment]
Je me demande comment ça se fait qu'on en aie autant ? Ce sont des transferts interrompus ?

**Comment by AntoineAugusti** [comment]
@thbar J'imagine ? 🤷 Ce serait bien de creuser.

**Comment by AntoineAugusti** [comment]
En regardant il n'y a pas tant que ça et ils sont assez anciens.

```
aws --endpoint-url "https://s3.fr-par.scw.cloud" --region fr-par s3api list-multipart-uploads --bucket transport-prod-backups
```

J'ai déjà vu des jobs Oban de transferts de backups qui échouent 1 fois ou 2. On a une alerte en cas d'un échec 3 fois de suite du job depuis https://github.com/etalab/transport-site/pull/3387

**Comment by AntoineAugusti** [comment]
Au lendemain de l'application de la configuration en production, passage de 140 GB de stockage à 76 GB de stockage (sur le bucket de production) sans supprimer des objets. Ça fait du bien de supprimer les anciens fichiers temporaires.

![image](https://github.com/etalab/transport-site/assets/295709/8caec395-654b-4bd9-99c0-54a69e10a96a)
