### ISSUE TITLE
Mise au propre du compte Scaleway

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#3412]
Le compte Scaleway a été créé "vite fait" pour tester les backups hors-site, et on peut à présent le passer au propre.

### Tâches

- [x] Notre organisation appartient toujours à @fchabouis (avec adresse personnelle), transférer l'ownership de ce compte. EDIT: en cours vers @thbar 
- [x] Inviter Boris en "billing"
- [x] Modifier l'email de réception des factures (adresse PathTech pour le traitement dinum)
- [x] Modifier le nom de la structure (champ bloqué) - EDIT: @thbar échange avec Scaleway là dessus (k-bis etc)
- [x] Corriger le nom "Francis" qui reste attaché à Thibaut sur les tickets - EDIT: ticket en cours
- [x] Enlever Francis
- [x] Requérir le 2FA pour tout le monde - EDIT: @thbar échange avec Scaleway sur ce sujet EDIT -> ✅

**Comment by AntoineAugusti** [comment]
@thbar Je t'assign l'issue comme il me semble que tu gères ça, je te laisse compléter puis fermer

**Comment by thbar** [comment]
@AntoineAugusti tout à fait, merci !

**Comment by thbar** [comment]
Tout est traité ! Je clôture.
