### ISSUE TITLE
Revoir la documentation API sur doc.transport.data.gouv.fr

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#3420]
Comme vu avec @Miryad3108, je vais revoir cette documentation:
- https://doc.transport.data.gouv.fr/administration-des-donnees/outils/api

(en tout cas la partie pour consommer les données), en m'appuyant sur ce que j'ai appris ici:

- #3351 

Je crée le ticket pour ne pas zapper (et le contenu sera noté ici car c'est plus simple, comme vu avec Miryad également).

### API de transport.data.gouv.fr pour réutiliser les données

Le PAN propose une API, sans authentification ni quota, en JSON. Elle diffuse des informations sur les jeux de données, ressources, AOMs, historisations, validations conduites par le PAN.

L'API permet :
- d'automatiser la récupération des informations affichées sur le site web ;
- de construire des automatisations spécifiques à vos besoins, en autonomie ;
- de suivre les dernières informations disponibles sur l'intégralité du catalogue du PAN.

Pour découvrir l'API, rendez-vous sur le portail "Swagger" ici https://transport.data.gouv.fr/swaggerui.

Les opérations disponibles (endpoints) sont décrites, ainsi que les paramètres éventuels et la structure des réponses.

Le endpoint le plus important est celui qui retourne, en un seul appel, la liste de la totalité des datasets et ressources associées:

`https://transport.data.gouv.fr/api/datasets`

Une fois que vous disposez de l'identifiant du dataset, vous pouvez si vous le souhaitez récupérer une version plus détaillée (avec notamment l'historique des changements de ressources, les conversions éventuellement réalisées)  ici:

`https://transport.data.gouv.fr/api/datasets/:id`

Une section d'opérations permet aussi de récupérer les informations liées aux Autorités Organisatrices de la Mobilité.

Certaines opérations n'ont d'utilité que pour le PAN lui-même, mais sont disponibles malgré tout.

N'hésitez pas à nous contacter en cas de besoin, nous sommes à votre disposition pour vous aider ! (TODO: ajouter le bon email)

**Comment by thbar** [comment]
@Miryad3108 le contenu est prêt !

**Comment by thbar** [comment]
Vu avec @Miryad3108, le contenu est déjà sur une branche dans GitBook, en attente de merge.

@AurelienC préviens-nous quand c'est mergé, je crois que c'est toi qui finalisera ? Merci !

**Comment by AurelienC** [comment]
C'est finalisé de mon côté, je me cale avec @cyrilmorin pour merger !

**Comment by thbar** [comment]
Merci @AurelienC, bippez-nous ici quand c'est bouclé pour de bon, j'irais vérifier que rien ne cloche (vu que ça a pu bouger un peu). Merci !

**Comment by thbar** [comment]
Je crois que ce n'est pas mergé dans GitBook pour le moment (en tout cas je ne vois pas les impacts sur le site en production), je garde ouvert.

**Comment by cyrilmorin** [comment]
Hello @thbar la doc est mergé, je te laisse checker !

**Comment by thbar** [comment]
Merci pour le ping @cyrilmorin, j'ai été vérifier et je ne vois pas de souci ! Je clôture.
