### ISSUE TITLE
AOM: départements non homogènes dans la donnée (espaces en trop)

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#3423]
Une bizarrerie de données (pas très grave mais je note vu que j'ai remarqué pour ne pas perdre l'info), certaines AOM ont un département avec un espace en trop à la fin (car c'est stocké sous forme de chaîne).

Probablement lié à la donnée utilisée en entrée, qu'il aurait fallu "trimmer", on pourra s'en souvenir au prochain import, voire, faire remonter le souci upstream si ça vient de là bas.

Ca pourrait surprendre quelqu'un qui fait un group by département de sa donnée sans être trop prudent, par exemple.

```sql
WITH departements AS (
	SELECT
		*,
		departement AS d,
		replace(departement, ' ', '') AS clean_d
	FROM
		aom
)
SELECT
	id as aom_id,
	'"' || d || '"' as d,
	'"' || clean_d || '"' as clean_d
FROM
	departements
WHERE
	d != clean_d
```

### Résultat sur les données de production de ce jour

| aom_id | d     | clean_d |
|--------|-------|---------|
|    458 | "59 " | "59"    |
|    460 | "21 " | "21"    |
|    577 | "55 " | "55"    |
|    653 | "25 " | "25"    |
|    856 | "84 " | "84"    |
|    503 | "44 " | "44"    |
|    459 | "55 " | "55"    |
|    461 | "27 " | "27"    |
|    576 | "85 " | "85"    |
|    840 | "2A " | "2A"    |
|    854 | "05 " | "05"    |
|    659 | "44 " | "44"    |
|    507 | "25 " | "25"    |
|    682 | "86 " | "86"    |
|    510 | "38 " | "38"    |
|    709 | "68 " | "68"    |
|    462 | "71 " | "71"    |
|    463 | "68 " | "68"    |
|    652 | "14 " | "14"    |
|    414 | "67 " | "67"    |
|    654 | "24 " | "24"    |
|    415 | "25 " | "25"    |
|    655 | "63 " | "63"    |
|    515 | "39 " | "39"    |
|    855 | "17 " | "17"    |
|    408 | "40 " | "40"    |
|    409 | "38 " | "38"    |
|    410 | "72 " | "72"    |
|    452 | "25 " | "25"    |
|    492 | "72 " | "72"    |
|    412 | "53 " | "53"    |
|    416 | "29 " | "29"    |
|    417 | "14 " | "14"    |
|    435 | "10 " | "10"    |
|    418 | "25 " | "25"    |
|    419 | "44 " | "44"    |
|    422 | "21 " | "21"    |
|    420 | "47 " | "47"    |
|    421 | "70 " | "70"    |
|    424 | "2B " | "2B"    |
|    606 | "76 " | "76"    |
|    407 | "60 " | "60"    |
|    411 | "90 " | "90"    |
|    440 | "74 " | "74"    |
|    447 | "57 " | "57"    |
|    489 | "49 " | "49"    |
|    425 | "88 " | "88"    |
|    426 | "10 " | "10"    |
|    427 | "60 " | "60"    |
|    428 | "15 " | "15"    |
|    436 | "62 " | "62"    |
|    437 | "85 " | "85"    |
|    431 | "44 " | "44"    |
|    429 | "47 " | "47"    |
|    432 | "68 " | "68"    |
|    430 | "21 " | "21"    |
|    433 | "36 " | "36"    |
|    434 | "54 " | "54"    |
|    442 | "39 " | "39"    |
|    438 | "28 " | "28"    |
|    439 | "85 " | "85"    |
|    526 | "72 " | "72"    |
|    443 | "58 " | "58"    |
|    584 | "69 " | "69"    |
|    444 | "58 " | "58"    |
|    445 | "76 " | "76"    |
|    446 | "35 " | "35"    |
|    448 | "54 " | "54"    |
|    450 | "60 " | "60"    |
|    451 | "76 " | "76"    |
|    453 | "10 " | "10"    |
|    466 | "57 " | "57"    |
|    454 | "21 " | "21"    |
|    485 | "17 " | "17"    |
|    455 | "05 " | "05"    |
|    456 | "72 " | "72"    |
|    457 | "47 " | "47"    |
|    464 | "89 " | "89"    |
|    486 | "62 " | "62"    |
|    465 | "28 " | "28"    |
|    467 | "49 " | "49"    |
|    468 | "28 " | "28"    |
|    469 | "63 " | "63"    |
|    727 | "08 " | "08"    |
|    470 | "80 " | "80"    |
|    740 | "02 " | "02"    |
|    750 | "90 " | "90"    |
|    471 | "02 " | "02"    |
|    472 | "35 " | "35"    |
|    473 | "74 " | "74"    |
|    474 | "85 " | "85"    |
|    475 | "49 " | "49"    |
|    476 | "67 " | "67"    |
|    789 | "14 " | "14"    |
|    477 | "52 " | "52"    |
|    478 | "51 " | "51"    |
|    479 | "62 " | "62"    |
|    480 | "10 " | "10"    |
|    481 | "39 " | "39"    |
|    482 | "67 " | "67"    |
|    483 | "53 " | "53"    |
|    484 | "56 " | "56"    |
|    487 | "60 " | "60"    |
|    860 | "54 " | "54"    |
|    488 | "23 " | "23"    |
|    413 | "62 " | "62"    |
|    423 | "54 " | "54"    |
|    441 | "63 " | "63"    |
|    491 | "52 " | "52"    |
|    494 | "69 " | "69"    |
|    501 | "63 " | "63"    |
|    506 | "69 " | "69"    |
|    585 | "19 " | "19"    |
|    509 | "67 " | "67"    |
|    513 | "69 " | "69"    |
|    521 | "38 " | "38"    |
|    558 | "74 " | "74"    |
|    575 | "02 " | "02"    |
|    593 | "69 " | "69"    |
|    603 | "54 " | "54"    |
|    642 | "69 " | "69"    |
|    677 | "74 " | "74"    |
|    671 | "85 " | "85"    |
|    580 | "84 " | "84"    |
|    703 | "67 " | "67"    |
|    705 | "54 " | "54"    |
|    714 | "69 " | "69"    |
|    716 | "54 " | "54"    |
|    774 | "07 " | "07"    |
|    540 | "51 " | "51"    |
|    554 | "24 " | "24"    |
|    829 | "69 " | "69"    |
|    631 | "61 " | "61"    |
|    848 | "54 " | "54"    |
|    861 | "23 " | "23"    |
|    573 | "67 " | "67"    |
|    685 | "29 " | "29"    |
|    674 | "72 " | "72"    |
|    511 | "55 " | "55"    |
|    490 | "02 " | "02"    |
|    493 | "88 " | "88"    |
|    495 | "76 " | "76"    |
|    581 | "68 " | "68"    |
|    496 | "59 " | "59"    |
|    497 | "44 " | "44"    |
|    578 | "76 " | "76"    |
|    579 | "68 " | "68"    |
|    498 | "61 " | "61"    |
|    499 | "70 " | "70"    |
|    500 | "60 " | "60"    |
|    502 | "62 " | "62"    |
|    582 | "89 " | "89"    |
|    504 | "10 " | "10"    |
|    505 | "58 " | "58"    |
|    546 | "45 " | "45"    |
|    586 | "84 " | "84"    |
|    508 | "89 " | "89"    |
|    514 | "07 " | "07"    |
|    524 | "88 " | "88"    |
|    512 | "70 " | "70"    |
|    516 | "21 " | "21"    |
|    517 | "2B " | "2B"    |
|    518 | "47 " | "47"    |
|    548 | "14 " | "14"    |
|    519 | "62 " | "62"    |
|    520 | "55 " | "55"    |
|    522 | "89 " | "89"    |
|    587 | "67 " | "67"    |
|    873 | "69 " | "69"    |
|    523 | "72 " | "72"    |
|    525 | "08 " | "08"    |
|    799 | "71 " | "71"    |
|    527 | "45 " | "45"    |
|    528 | "57 " | "57"    |
|    809 | "72 " | "72"    |
|    529 | "50 " | "50"    |
|    551 | "58 " | "58"    |
|    530 | "37 " | "37"    |
|    531 | "05 " | "05"    |
|    535 | "57 " | "57"    |
|    532 | "10 " | "10"    |
|    533 | "39 " | "39"    |
|    534 | "21 " | "21"    |
|    536 | "35 " | "35"    |
|    537 | "67 " | "67"    |
|    547 | "57 " | "57"    |
|    538 | "25 " | "25"    |
|    539 | "61 " | "61"    |
|    542 | "39 " | "39"    |
|    726 | "27 " | "27"    |
|    541 | "72 " | "72"    |
|    543 | "57 " | "57"    |
|    545 | "02 " | "02"    |
|    544 | "19 " | "19"    |
|    678 | "71 " | "71"    |
|    560 | "83 " | "83"    |
|    561 | "60 " | "60"    |
|    607 | "27 " | "27"    |
|    550 | "71 " | "71"    |
|    608 | "14 " | "14"    |
|    552 | "67 " | "67"    |
|    553 | "29 " | "29"    |
|    634 | "44 " | "44"    |
|    555 | "50 " | "50"    |
|    556 | "21 " | "21"    |
|    612 | "25 " | "25"    |
|    557 | "57 " | "57"    |
|    718 | "67 " | "67"    |
|    559 | "47 " | "47"    |
|    562 | "55 " | "55"    |
|    565 | "33 " | "33"    |
|    563 | "44 " | "44"    |
|    564 | "53 " | "53"    |
|    566 | "39 " | "39"    |
|    567 | "57 " | "57"    |
|    625 | "53 " | "53"    |
|    626 | "2B " | "2B"    |
|    627 | "35 " | "35"    |
|    628 | "67 " | "67"    |
|    629 | "72 " | "72"    |
|    815 | "74 " | "74"    |
|    630 | "89 " | "89"    |
|    568 | "45 " | "45"    |
|    569 | "83 " | "83"    |
|    590 | "59 " | "59"    |
|    570 | "2B " | "2B"    |
|    598 | "29 " | "29"    |
|    571 | "29 " | "29"    |
|    572 | "53 " | "53"    |
|    574 | "2A " | "2A"    |
|    583 | "35 " | "35"    |
|    621 | "44 " | "44"    |
|    588 | "14 " | "14"    |
|    589 | "88 " | "88"    |
|    591 | "71 " | "71"    |
|    822 | "33 " | "33"    |
|    592 | "60 " | "60"    |
|    622 | "79 " | "79"    |
|    594 | "08 " | "08"    |
|    595 | "29 " | "29"    |
|    596 | "71 " | "71"    |
|    623 | "59 " | "59"    |
|    632 | "59 " | "59"    |
|    633 | "25 " | "25"    |
|    597 | "08 " | "08"    |
|    599 | "27 " | "27"    |
|    600 | "80 " | "80"    |
|    601 | "88 " | "88"    |
|    602 | "67 " | "67"    |
|    604 | "23 " | "23"    |
|    605 | "79 " | "79"    |
|    823 | "67 " | "67"    |
|    824 | "68 " | "68"    |
|    609 | "57 " | "57"    |
|    610 | "85 " | "85"    |
|    641 | "85 " | "85"    |
|    611 | "52 " | "52"    |
|    613 | "58 " | "58"    |
|    647 | "25 " | "25"    |
|    717 | "47 " | "47"    |
|    719 | "55 " | "55"    |
|    614 | "62 " | "62"    |
|    615 | "71 " | "71"    |
|    650 | "68 " | "68"    |
|    616 | "89 " | "89"    |
|    651 | "44 " | "44"    |
|    617 | "72 " | "72"    |
|    618 | "85 " | "85"    |
|    656 | "21 " | "21"    |
|    619 | "58 " | "58"    |
|    620 | "80 " | "80"    |
|    624 | "27 " | "27"    |
|    635 | "70 " | "70"    |
|    637 | "27 " | "27"    |
|    638 | "68 " | "68"    |
|    639 | "62 " | "62"    |
|    640 | "85 " | "85"    |
|    676 | "57 " | "57"    |
|    668 | "51 " | "51"    |
|    643 | "58 " | "58"    |
|    644 | "76 " | "76"    |
|    670 | "70 " | "70"    |
|    645 | "72 " | "72"    |
|    649 | "13 " | "13"    |
|    646 | "85 " | "85"    |
|    648 | "67 " | "67"    |
|    681 | "45 " | "45"    |
|    657 | "76 " | "76"    |
|    658 | "10 " | "10"    |
|    673 | "59 " | "59"    |
|    660 | "68 " | "68"    |
|    661 | "89 " | "89"    |
|    662 | "35 " | "35"    |
|    663 | "72 " | "72"    |
|    664 | "35 " | "35"    |
|    665 | "45 " | "45"    |
|    666 | "39 " | "39"    |
|    667 | "27 " | "27"    |
|    669 | "61 " | "61"    |
|    672 | "39 " | "39"    |
|    675 | "53 " | "53"    |
|    724 | "56 " | "56"    |
|    725 | "84 " | "84"    |
|    679 | "53 " | "53"    |
|    680 | "79 " | "79"    |
|    683 | "64 " | "64"    |
|    684 | "71 " | "71"    |
|    686 | "50 " | "50"    |
|    689 | "67 " | "67"    |
|    687 | "21 " | "21"    |
|    698 | "68 " | "68"    |
|    688 | "29 " | "29"    |
|    690 | "08 " | "08"    |
|    691 | "85 " | "85"    |
|    692 | "35 " | "35"    |
|    693 | "68 " | "68"    |
|    694 | "29 " | "29"    |
|    701 | "62 " | "62"    |
|    695 | "39 " | "39"    |
|    702 | "76 " | "76"    |
|    696 | "70 " | "70"    |
|    697 | "41 " | "41"    |
|    699 | "33 " | "33"    |
|    700 | "71 " | "71"    |
|    704 | "27 " | "27"    |
|    706 | "61 " | "61"    |
|    707 | "70 " | "70"    |
|    708 | "59 " | "59"    |
|    710 | "54 " | "54"    |
|    721 | "71 " | "71"    |
|    711 | "80 " | "80"    |
|    712 | "29 " | "29"    |
|    713 | "73 " | "73"    |
|    715 | "68 " | "68"    |
|    720 | "72 " | "72"    |
|    722 | "62 " | "62"    |
|    723 | "61 " | "61"    |
|    728 | "02 " | "02"    |
|    729 | "86 " | "86"    |
|    730 | "55 " | "55"    |
|    739 | "35 " | "35"    |
|    731 | "55 " | "55"    |
|    732 | "02 " | "02"    |
|    733 | "25 " | "25"    |
|    734 | "53 " | "53"    |
|    743 | "33 " | "33"    |
|    744 | "76 " | "76"    |
|    735 | "25 " | "25"    |
|    736 | "49 " | "49"    |
|    737 | "10 " | "10"    |
|    745 | "89 " | "89"    |
|    738 | "14 " | "14"    |
|    751 | "67 " | "67"    |
|    741 | "80 " | "80"    |
|    742 | "61 " | "61"    |
|    746 | "22 " | "22"    |
|    747 | "70 " | "70"    |
|    748 | "50 " | "50"    |
|    749 | "35 " | "35"    |
|    752 | "67 " | "67"    |
|    794 | "84 " | "84"    |
|    753 | "08 " | "08"    |
|    793 | "14 " | "14"    |
|    754 | "35 " | "35"    |
|    755 | "51 " | "51"    |
|    766 | "76 " | "76"    |
|    756 | "26 " | "26"    |
|    757 | "55 " | "55"    |
|    825 | "76 " | "76"    |
|    758 | "88 " | "88"    |
|    811 | "61 " | "61"    |
|    812 | "33 " | "33"    |
|    759 | "27 " | "27"    |
|    761 | "71 " | "71"    |
|    760 | "29 " | "29"    |
|    762 | "56 " | "56"    |
|    833 | "10 " | "10"    |
|    834 | "72 " | "72"    |
|    763 | "85 " | "85"    |
|    835 | "68 " | "68"    |
|    764 | "54 " | "54"    |
|    838 | "57 " | "57"    |
|    765 | "85 " | "85"    |
|    839 | "60 " | "60"    |
|    767 | "25 " | "25"    |
|    853 | "67 " | "67"    |
|    768 | "44 " | "44"    |
|    769 | "24 " | "24"    |
|    780 | "88 " | "88"    |
|    771 | "02 " | "02"    |
|    770 | "61 " | "61"    |
|    772 | "71 " | "71"    |
|    827 | "57 " | "57"    |
|    773 | "85 " | "85"    |
|    783 | "84 " | "84"    |
|    775 | "21 " | "21"    |
|    858 | "85 " | "85"    |
|    862 | "57 " | "57"    |
|    776 | "61 " | "61"    |
|    867 | "67 " | "67"    |
|    777 | "21 " | "21"    |
|    778 | "45 " | "45"    |
|    779 | "83 " | "83"    |
|    828 | "80 " | "80"    |
|    785 | "47 " | "47"    |
|    781 | "60 " | "60"    |
|    782 | "2A " | "2A"    |
|    784 | "58 " | "58"    |
|    786 | "51 " | "51"    |
|    787 | "29 " | "29"    |
|    790 | "23 " | "23"    |
|    791 | "76 " | "76"    |
|    792 | "25 " | "25"    |
|    795 | "76 " | "76"    |
|    796 | "71 " | "71"    |
|    797 | "67 " | "67"    |
|    798 | "51 " | "51"    |
|    800 | "02 " | "02"    |
|    801 | "29 " | "29"    |
|    802 | "49 " | "49"    |
|    803 | "23 " | "23"    |
|    804 | "23 " | "23"    |
|    805 | "63 " | "63"    |
|    806 | "21 " | "21"    |
|    807 | "56 " | "56"    |
|    808 | "55 " | "55"    |
|    810 | "83 " | "83"    |
|    813 | "19 " | "19"    |
|    814 | "50 " | "50"    |
|    816 | "60 " | "60"    |
|    817 | "21 " | "21"    |
|    818 | "54 " | "54"    |
|    819 | "56 " | "56"    |
|    836 | "67 " | "67"    |
|    837 | "44 " | "44"    |
|    820 | "62 " | "62"    |
|    821 | "88 " | "88"    |
|    826 | "85 " | "85"    |
|    830 | "24 " | "24"    |
|    831 | "39 " | "39"    |
|    832 | "35 " | "35"    |
|    841 | "2A " | "2A"    |
|    842 | "28 " | "28"    |
|    843 | "14 " | "14"    |
|    844 | "51 " | "51"    |
|    845 | "56 " | "56"    |
|    846 | "35 " | "35"    |
|    847 | "06 " | "06"    |
|    849 | "56 " | "56"    |
|    850 | "39 " | "39"    |
|    851 | "2B " | "2B"    |
|    852 | "14 " | "14"    |
|    857 | "55 " | "55"    |
|    859 | "2A " | "2A"    |
|    863 | "29 " | "29"    |
|    864 | "05 " | "05"    |
|    865 | "10 " | "10"    |
|    866 | "05 " | "05"    |
|    868 | "80 " | "80"    |
|    869 | "59 " | "59"    |
|    870 | "61 " | "61"    |
|    871 | "61 " | "61"    |
|    872 | "14 " | "14"    |
|    874 | "80 " | "80"    |
|    875 | "29 " | "29"    |
|    876 | "05 " | "05"    |

**Comment by thbar** [comment]
Liens utiles:
- https://github.com/etalab/transport-site/blob/98ee562f72ba94e7674ab95396f0e99f49b83fa2/apps/transport/lib/transport/import_aom.ex#L61

**Comment by AntoineAugusti** [comment]
Je vais modifier le code/faire une tite migration pour 💤 tranquille

**Comment by thbar** [comment]
Merci @AntoineAugusti!
