### ISSUE TITLE
Créer un module de feedback pour les nouvelles fonctionnalités

### ISSUE THREAD

**Issue by vdegove** [etalab/transport-site#3424]
## Problème à résoudre

L’équipe du PAN souhaite avoir du feedback sur les outils expérimentaux déployés au fur et à mesure, afin de mesurer leur utilité et les améliorer.

## Solution envisagée

Sur des pages sélectionnées (exemple : carte d’exploration), faire apparaître à tous les visiteurs du site un module de feedback, qui permet :
1. de noter simplement la fonctionnalité – 3 niveaux :-) :-| :-( 
2. de laisser un message explicatif
3. laisser éventuellement son email pour recontact

Pour commencer, cela enverra un email. Si besoin, on stockera la donnée dans un deuxième temps.

## Remarques et questions en suspens concernant le feedback et contact sur le PAN

Dans les autres besoins de feedback que sur ces fonctionnalités expérimentales :
- Le feedback sur la qualité des données est déjà couvert par une enquête annuelle
- Le feedback plus général sur le PAN et son ergonomie peut être intéressant, mais on a peur d’avoir du bruit

Le module de contact en position fixe en bas à droite est bizarrement peu visible et fait doublon avec le contact email dans le footer. On pourrait aussi l’améliorer et créer des catégories (comme « suggestions »).

**Comment by AntoineAugusti** [comment]
Ça me parait pas mal pour débuter ! T'as déjà en tête une volumétrie qui pourrait nous amener à stocker ceci en BDD ? Il y a un mockup de l'UI envisagée ? Certains champs vont apparaitre uniquement avoir choisi l'un des 3 niveaux ?

Envisage d'ajouter un champ honeypot, ce qui est déjà fait pour le formulaire de contact mis dans le coin en bas à droite https://github.com/etalab/transport-site/blob/98ee562f72ba94e7674ab95396f0e99f49b83fa2/apps/transport/lib/transport_web/controllers/contact_controller.ex#L6 pour éviter du spam.

### Concernant le module de contact

On reçoit toutes les semaines des e-mails via ce biais, visiblement certaines personnes utilisent ceci ! Le menu en haut de page est assez lourd maintenant, reste le footer.

**Comment by vdegove** [comment]
> Ça me parait pas mal pour débuter ! T'as déjà en tête une volumétrie qui pourrait nous amener à stocker ceci en BDD ?

Pas vraiment. Je dirais à partir d’une douzaine de feedbacks par semaine, qu’ils contiennent un commentaire en plus de la notation ou pas ?

>  Il y a un mockup de l'UI envisagée ? 

Non, je pensais faire l’UI en développant, (et même, commencer par ça, et vous la proposer une fois faite avant al fin de la MR) mais tu me conseilles de faire un mockup dans un outil de design avant ?

>  Certains champs vont apparaitre uniquement avoir choisi l'un des 3 niveaux ?

J’hésite là dessus, il y a trois possibilités :
1. Un bouton « laisser un avis sur la fonctionnalité » (wording à affiner) qui déplie le formulaire entier.
2. Seulement la notation en smiley qui apparaît, et une fois un niveau selectionné le reste du formulaire apparaît (à la service-public.fr)
3. Le module entier apparaît sur les pages sélectionnées, sans rien de caché.

J’hésite entre 3 et 1, je pensais faire d’abord le 3, évaluer si c’est trop lourd visuellement, et si oui basculer sur le 1.

> Envisage d'ajouter un champ honeypot, ce qui est déjà fait pour le formulaire de contact mis dans le coin en bas à droite 

Je connaissais pas, merci !

> On reçoit toutes les semaines des e-mails via ce biais, visiblement certaines personnes utilisent ceci !

Ah oui oui l’idée c’était pas de le jarter, au contraire je me demandais si on pouvait pas le rendre un chouia plus visible (mais comment, sans être gênant ? Si on met un texte à côté de l’icône, ça va être vite gênant) et l’améliorer. Après ça vient juste d’une remarque personnelle : mon œil est devenu complètement aveugle à ce module, j’avais oublié qu’il était là… Et Benoît m’a fait la même remarque. Après c’est peut-être justement parce qu’on est habitués au PAN qu’on a cette cécité. 

De toutes façons c’est en dehors du scope de cette issue, c’est juste parce qu’on l’a mentionné que je l’ai mis dans cette prise de notes.
