### ISSUE TITLE
Code erroné depuis plusieurs années (`is_user_in_followers?(page['next_page']`)

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#3431]
Comme relevé par @AntoineAugusti ici:
- https://github.com/etalab/transport-site/pull/3429/files/fdcdb682d3f3710a38ab859014c6e49e9aad2212#diff-4d4888522b02752cabd07d027f229fb4b98b0c7d0ca8775663e65404a3d1c6ed

Le reformattage apporté par Elixir 1.15 permet de voir qu'on accède à une clé de payload datagouv par `'next_page'` et non `"next_page"`.

Du coup cela retourne `nil` systématiquement.

J'allais corriger dans la PR #3429 mais j'ai eu un doute en lisant le code.

Je préfère éviter de modifier là-bas, car il n'y a pas de tests, et le bug étant ancien, je préfère éviter de modifier sans vérification plus précise (éviter une boucle infinie, des lenteurs ou autre, car il y a des requêtes HTTP supplémentaires).

Je pense qu'il vaut mieux ajouter des tests tranquillement, le bug étant par ailleurs très ancien (plus de 5 ans)

Voir aussi:
- #3430.

https://github.com/etalab/transport-site/blob/85282f8b7c487ca50af60115eb5aa81aa2d751ee/apps/datagouvfr/lib/datagouvfr/client/datasets.ex#L156-L171

**Comment by AntoineAugusti** [comment]
Peut-être qu'on peut avoir un `per_page` pour cette requête plus grand pour éviter de faire trop de requêtes pour voir si la personne est abonnée ou pas. Je sais pas s'il y a des JDD avec beaucoup de followers

**Comment by thbar** [comment]
J'irai regarder un peu la data pour comprendre, mais vu que c'est vieux j'ai préféré ne pas hâter les choses et me planter un jeudi :-)

**Comment by thbar** [comment]
Différent et sans le même impact mais surprenant quand même:
- https://github.com/etalab/transport-site/pull/3429#pullrequestreview-1604864726

**Comment by AntoineAugusti** [comment]
Je vais le traiter

**Comment by thbar** [comment]
@AntoineAugusti un point auquel j'avais pensé c'est qu'il faut faire un peu gaffe aux effets de bords du type "volume retourné beaucoup plus importants" potentiellement

**Comment by AntoineAugusti** [comment]
Ouais je vais regarder le temps de réponse et s'il vaut mieux avoir plus d'éléments par page (`per_page`) pour éviter qu'on fasse 3-4 requêtes si il y a beaucoup de résultats

**Comment by thbar** [comment]
# :coffee: :smile:

- https://github.com/etalab/transport-site/pull/3486
