### ISSUE TITLE
Mise à jour phoenix_live_view avec breaking changes

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#3433]
Découvert dans:
- #3432 
- #3429

Voir:
- https://github.com/phoenixframework/phoenix_live_view/blob/main/CHANGELOG.md#0195-2023-07-19
- https://github.com/phoenixframework/phoenix_live_view/blob/main/CHANGELOG.md#0190-2023-05-29

**Comment by AntoineAugusti** [comment]
Je vais traiter après #3676
