### ISSUE TITLE
Tagger les "hosts" avec "worker"/"site" dans AppSignal

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#3442]
C'est très brouillon de retrouve quel host (avec un nom temporaire sous forme de UUID) a quel rôle:

Je pense qu'ajouter l'option suivante avec "worker" et "site" aidera beaucoup:
- https://docs.appsignal.com/standalone-agent/configuration/options.html#option-host_role

**Comment by AntoineAugusti** [comment]
Done in #3444

**Comment by thbar** [comment]
@AntoineAugusti merci pour la clôture ; pour info je ne vois pas trop où ça sort, j'aurais aimé pouvoir distinguer les containers dans la liste, mais je vais leur écrire là dessus.

**Comment by thbar** [comment]
Question posée à AppSignal:

> Hello ! In the "host metrics" view, it would be lovely to show the host role, which we have configured here [2023-09-12](https://github.com/etalab/transport-site/blob/2ccb1ed1e58e5c4889d28453f285dc434fd49110/config/runtime.exs#L231-L237) and here https://github.com/etalab/transport-site/blob/2ccb1ed1e58e5c4889d28453f285dc434fd49110/config/runtime.exs#L251-L261. I am not sure about the exact UX etc, but it would help us identify the host we want to look at.
Is it doable or planned? Thanks !
