### ISSUE TITLE
[epic] Cartographie & traitement des parties de code qui ne font pas de streaming

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#3447]
Voir:
- #3446 
- #3435
- https://github.com/etalab/transport-site/issues/3440#issuecomment-1706229371
- #3535
- https://github.com/etalab/transport-site/issues/2067

Un point clair de surconsommation de mémoire est le téléchargement HTTP de ressources "en mémoire" plutôt que streamé (et il y aura sûrement d'autres points similaires), et c'est aujourd'hui ce qui semble causer le + de reboots du worker (la deuxième cause étant la conversion gtfs2netex, qu'on aurait pu améliorer mais il y a un chantier pour le changer de toute façon, voir https://github.com/etalab/transport-site/issues/3427).

Le but de ce ticket est de lister les endroits de code à adapter, de noter ce que j'ai trouvé niveau solutions (sachant qu'il faudra conserver une bonne "testabilité" du code et ne pas faire d'impasse dessus, ce qui voudra probablement dire wrapping/behaviour).

Je crée ce placeholder, je vais noter ci-dessous.

:warning: le but n'est pas de passer tout en streaming, mais de voir les endroits où c'est particulièrement utile.

Un cas typique est le téléchargement de https://transport.data.gouv.fr/resources/65185 qui consomme 500MB en RAM:

```
❯ curl -IL https://www.data.gouv.fr/fr/datasets/r/c83ba91e-2cd1-40f7-a632-eb0a76d83c49 | grep content-length
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   439    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0  551M    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
content-length: 439
content-length: 578719744
```

### Ressources utiles

* https://github.com/wojtekmach/req/releases/tag/v0.4.0 intègre le streaming qui s'appuie sur Finch
* http://poeticoding.com/download-large-files-with-httpoison-async-requests/ montre comment streamer avec HTTPoison mais j'ai vu des gens ayant des soucis, j'aimerais autant utiliser Finch plutôt

**Comment by thbar** [comment]
Je crois qu'on est pas trop mal là dessus au final, poke @AntoineAugusti on peut clôturer je pense ?

**Comment by AntoineAugusti** [comment]
Oui, traité dans la PR #3666
