### ISSUE TITLE
Espace producteur du PAN : Pouvoir supprimer une ressource

### ISSUE THREAD

**Issue by cyrilmorin** [etalab/transport-site#3449]
Hello,

Il serait intéressant de pouvoir supprimer une ressource depuis l'espace producteur du PAN à l'image de la mise à jour et de l'ajout de ressource.
Je propose 

1- d'ajouter un bouton "Supprimer une ressource" en rouge à droite du bouton "Ajouter une ressource"
![image](https://github.com/etalab/transport-site/assets/116101828/fcaee34e-0563-4316-8337-7453650c2463)

2- Suite au clic sur le bouton "Supprimer une ressource" : afficher un 1er message nécessitant une validation de l'utilisateur avec "Voulez-vous mettre à jour la ressource ou supprimer définitivement la ressource ?" avec bouton "mettre à jour la ressource" (vers écran modifier la ressource) et un bouton sur "supprimer la ressource" avec la suppression directe (ou un renvoie sur datagouv si suppression non possible ...)
NB : cet écran peut paraître redondant mais permet d'inciter le producteur à se reposer la question

Merci

**Comment by AntoineAugusti** [comment]
@cyrilmorin Je viens de regarder pour réaliser ce ticket.

Problème, à cette étape on est au niveau du JDD. Quand tu cliques sur "Modifier une ressource", on liste les ressources.

Est-ce qu'on met pas ça plus tard en conséquence ? Ou alors "Supprimer une ressource", lister toutes les ressources et avoir un bandeau indiquant dans quel cas il faut mettre à jour ?
