### ISSUE TITLE
Contacts : distinguer fonction et organisation

### ISSUE THREAD

**Issue by cyrilmorin** [etalab/transport-site#3450]
Dans l'écran récap de tous les contacts il faudrait distinguer Fonction et Organisation
Aujourd'hui c'est un mélange des 2

Proposition : Ajouter la colonne "Organisation" (c'est bien l'information la plus importante)

Exemple avec la "fonction" saisie on a dans la colonne Fonction : [Fonction (Organisation)] : 
![image](https://github.com/etalab/transport-site/assets/116101828/80c91440-eee6-481a-adcb-9f3c76e7999a)

Exemple sans "fonction" saisie on a dans la colonne Fonction : [Organisation] : 
![image](https://github.com/etalab/transport-site/assets/116101828/0fdc6841-3ef9-435e-b906-7163efe3fe80)

**Comment by AntoineAugusti** [comment]
Pour clairifer, souhaites-tu 2 colonnes _Fonction_ et _Organisation_ ou uniquement _Organisation_ ?

**Comment by cyrilmorin** [comment]
Hello,

Pour faire au plus simple et complet : 2 colonnes !

Merci :)

**Comment by AntoineAugusti** [comment]
Cool, j'ai déjà fait comme ça dans la PR citée. Ça arrive bientôt.
