### ISSUE TITLE
État des lieux des traitements GBFS réalisés

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#3455]
J'ai fait un état des lieux rapide de ce qui traite (conversion et/ou proxy cache ou redirection) sur la partie GBFS suite au point d'équipe de ce matin. /cc @Benoit-MINT 

Au final on retrouve:
* 9 réseaux JC Decaux, pour lesquels on fait une conversion + cache (sauf erreur, vérifier dans le code plus bas: Amiens, Besançon, Cergy-Pontoise, Créteil, Lyon, Mulhouse, Nancy, Nantes, Toulouse)
* 4 réseaux pour lesquels on "redirige" sans conversion (Montpellier, Strasbourg, Rouen, Marseille)
* (1) réseau VCUB (Bordeaux) pour lequel on opère une conversion
* (1) réseau VLille (Lille) pour lequel on opère également une conversion

@AntoineAugusti peux-tu relire et voir si je n'ai rien oublié ? Merci !

### Réseaux JC Decaux qui sont configurés dans le proxy GBFS

https://github.com/etalab/transport-site/blob/e25f9c70641063a5152201fdef87ce60fa97c395/apps/gbfs/lib/gbfs/router.ex#L23-L33

### Réseaux pour lesquels on "redirige"

https://github.com/etalab/transport-site/blob/e25f9c70641063a5152201fdef87ce60fa97c395/apps/gbfs/lib/gbfs/router.ex#L35-L76

### Réseau VCub

https://github.com/etalab/transport-site/blob/e25f9c70641063a5152201fdef87ce60fa97c395/apps/gbfs/lib/gbfs/router.ex#L95-L100

https://github.com/etalab/transport-site/blob/master/apps/gbfs/lib/gbfs/controllers/vcub_controller.ex

### Réseau VLille

https://github.com/etalab/transport-site/blob/e25f9c70641063a5152201fdef87ce60fa97c395/apps/gbfs/lib/gbfs/router.ex#L102-L107

https://github.com/etalab/transport-site/blob/master/apps/gbfs/lib/gbfs/controllers/vlille_controller.ex

**Comment by AntoineAugusti** [comment]
C'est bien ce que j'avais partagé à Benoît ! Il y a des issues ouvertes pour supprimer les redirections récentes, je m'en chargerai.

Je relirai les communications à destination des entreprises et AOMs que @Miryad3108 va écrire

**Comment by AntoineAugusti** [comment]
#2974

**Comment by thbar** [comment]
Merci @AntoineAugusti pour la confirmation! Top :smile:

**Comment by AntoineAugusti** [comment]
Au niveau délai, on avait convenu :
- Pour JC Decaux (qui est en cours de développement/déploiement de son GBFS), janvier 2024
- Pour Lille et Bordeaux, fin T1 2024 et on sera à l'écoute si c'est la panique

**Comment by Miryad3108** [comment]
J'ai contacté : 
- toutes les villes pour lesquelles on convertissait les données JCDecaux hors Créteil et Cergy-Pontoise car je n'ai pas leurs coordonnées 
- JCDecaux pour voir avec eux quand ils proposent l'export GBFS pour qu'on arrête les conversions quand ils proposeront ça (je l'ai formulé comme ça dans le mail)
- Lille et Bordeaux pour leur demander si ils peuvent fournir du GBFS au lieu d'un tableau

**Comment by AntoineAugusti** [comment]
[JC Decaux indique](https://app.frontapp.com/open/msg_23yccg2e?key=_h-4LISIti76ELWZ4Mr-7cfrMnTHbKly) avoir commencé à déployer ses APIs au format GBFS 2.3.

---

Vous trouverez ci-dessous la liste des catalogues que nous exposons pour les villes suivantes :

- Nantes : https://api.cyclocity.fr/contracts/nantes/gbfs/gbfs.json
- Lyon : https://api.cyclocity.fr/contracts/lyon/gbfs/gbfs.json
- Cergy : https://api.cyclocity.fr/contracts/cergy/gbfs/gbfs.json
- Nancy : https://api.cyclocity.fr/contracts/nancy/gbfs/gbfs.json
- Besançon : https://api.cyclocity.fr/contracts/besancon/gbfs/gbfs.json
- Mulhouse : https://api.cyclocity.fr/contracts/mulhouse/gbfs/gbfs.json

 
Nous avons prévu de passer Amiens sur notre nouveau système au printemps et Toulouse à l’été. Ainsi toutes nos villes françaises disposeront de l’open data VLS en GBFS.

**Comment by AntoineAugusti** [comment]
@stephane-pignal Les URLs suivantes issues de conversions de flux JC Decaux sont encore référencées sur le PAN pour le moment.

https://transport.data.gouv.fr/gbfs/cergy-pontoise/gbfs.json
https://transport.data.gouv.fr/gbfs/creteil/gbfs.json
https://transport.data.gouv.fr/gbfs/mulhouse/gbfs.json
https://transport.data.gouv.fr/gbfs/nantes/gbfs.json
https://transport.data.gouv.fr/gbfs/toulouse/gbfs.json

**Comment by stephane-pignal** [comment]
Ok je les relance, merci

**Comment by AntoineAugusti** [comment]
@stephane-pignal JC Decaux n'a pas migré Créteil / Cristolib vers leur nouvelle diffusion en GBFS étant donné que leur contrat prend fin à l'été 2024, on peut laisser de côté ceci.

**Comment by AntoineAugusti** [comment]
Les conversions custom Vcub (maintenant nommé "TBM Le Vélo") et V'Lille sont supprimées dans #4005.

Restera uniquement les conversions JC Decaux

**Comment by AntoineAugusti** [comment]
L'arrêt des conversions JC Decaux est prévu pour le 01/09/2024. Toutes les URLs présentes sur https://transport.data.gouv.fr/gbfs retourneront une 404 à partir de cette date.

Côté tech on pourra supprimer l'app `gbfs` à ce moment.

Tu me confirmes que c'est bien ceci @stephane-pignal ?
