### ISSUE TITLE
[BO] Réseau + tag saisonnier : gestion de la péremption 

### ISSUE THREAD

**Issue by cyrilmorin** [etalab/transport-site#3457]
Les réseaux saisonniers (navettes ski, réseau été ...) ont des calendriers qui sont périmés une bonne partie de l'année de façon logique.
calendrier du 01/07 au 30/08 par exemple. Tous les producteurs de GTFS ne renseigneront pas l'info dans feed_info malheureusement.

Pour alerter à minima les réutilisateurs et si la description du jdd n'est pas explicite il serait intéressant d'ajouter un traitement spécifique pour ces jeux annoncés comme périmés (défaut de qualité présumé) alors qu'ils ne le sont pas.

Pour faire simple et pour commencer on pourrait afficher un texte d'alerte au-dessus de la description (par exemple)

Proposition de texte : "Attention le service de transport de ce jeu de donnée ne fonctionne pas toute l'année et les ressources associées peuvent être périmées selon la période de l'année. Nous vous invitons à contacter le producteur via la discussion pour plus d'information sur le sujet"

**Comment by AntoineAugusti** [comment]
En lien avec #2336
