### ISSUE TITLE
[BO] Exports ressources - Représentants légaux renseignés mais pas dans l'export

### ISSUE THREAD

**Issue by cyrilmorin** [etalab/transport-site#3467]
Hello,

Il semble y avoir un souci sur l'export des ressources pour les JDD "Région" où le champ est bien complété, mais il n'apparaît pas dans l'export.

Exemple [Réseau interurbain Mobigo](https://transport.data.gouv.fr/backoffice/datasets/505/edit)
![image](https://github.com/etalab/transport-site/assets/116101828/32cd2d61-2464-42d9-9fa6-a8f13721af23)

Merci !

**Comment by AntoineAugusti** [comment]
Pas vraiment un bug mais plus une incompréhension je dirais. Dans https://github.com/etalab/transport-site/pull/3448, les seules données proviennent de la table `contacts`, sans rien regarder ailleurs. Les représentants légaux sont stockés ailleurs, avec une relation n-n vers des contacts.

Comment ceci devrait être présent dans un export de contacts ?

**Comment by AntoineAugusti** [comment]
Voir https://github.com/etalab/transport-site/pull/3342

La première implémentation n'utilise pas du tout les données renseignées dans `dataset_region_legal_owner`, uniquement dans `dataset_aom_legal_owner`.

@cyrilmorin Comment distinguer ça ? Avant c'était (premier non null) : représentants légaux AOMs ou SIREN d'une entreprise. On ajoute régions ici ? C'est possible régions + AOMs ? Si oui j'imagine qu'on peut faire plusieurs colonnes, ou tout mélanger.

Your choice

**Comment by cyrilmorin** [comment]
On ne vient pas chercher au même endroit l'AOM si c'est une région ? Je ne me souviens plus mais peut-être qu'on l'avait effectivement déjà évoqué.

Les Régions ne sont pas dans la table AOM ?

Fonctionnellement, une Région est une AOM comme une autre mais j'imagine que c'est un héritage du fonctionnement de notre BO et c'est pour ça qu'il y a la distinction dans le libellé (ce n'était pas une demande explicite initialement)
![image](https://github.com/etalab/transport-site/assets/116101828/961f0255-f9d7-4ef4-8746-3c2063ea6421)

Pour répondre à ta question il pourrait y avoir en représentant légal 1 AOM locale et 1 régionale (ex : aggrégats)

![image](https://github.com/etalab/transport-site/assets/116101828/5e1d59cb-85c7-4000-8d85-0a688862bfdf)

**Comment by AntoineAugusti** [comment]
@cyrilmorin J'ai mis dans la PR régions + AOMs dans la même colonne

**Comment by cyrilmorin** [comment]
pas d'urgence @AntoineAugusti on en reparle tranquillement

**Comment by AntoineAugusti** [comment]
@cyrilmorin J'ai déjà fait la modification (ajouter les régions en plus des autres AOMs) dans la pull request ☺ Si c'est le comportement attendu c'est tout pour moi.

**Comment by cyrilmorin** [comment]
OK pour je comprenne bien on aura donc dans la colonne "Représentant légaux" l'info saisie que  ce soit une AOM "locale" ou une AOM "régionale" ?
Si oui c'est tout bon pour moi pour l'export :)

**Comment by AntoineAugusti** [comment]
@cyrilmorin Ce sera en prod dans ~15 minutes

**Comment by cyrilmorin** [comment]
@AntoineAugusti dans l'export des ressources pour Bretagne (par exemple) on à 0 représentants légaux au lieu d'avoir la liste énorme de toutes les AOMs. Tu peux regarder stp ?

**Comment by AntoineAugusti** [comment]
@cyrilmorin Peux-tu préciser quel est le JDD concerné ?

En téléchargeant depuis la prod à l'instant je vois ceci, ça me parait être ce qui est attendu.

> Région Bretagne,Base de données multimodale transports publics en Bretagne - Korrigo- GTFS,Agrégat de réseaux urbains et interurbains de Bretagne,https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-transports-publics-en-bretagne-korrigo-gtfs,odc-odbl,public-transit,,AOM,Bretagne,"Brest Métropole,Bretagne,CA Concarneau Cornouaille Agglomération,CA du Pays de Landerneau-Daoulas,CA du Pays de Saint Malo Agglomération,CA Fougères Agglomération,CA Golfe du Morbihan - Vannes Agglomération,CA Guingamp-Paimpol Agglomération de l'Armor à l'Argoat,CA Lamballe Terre et Mer,CA Lannion-Trégor Communauté,CA Lorient Agglomération,CA Morlaix Communauté,CA Quimper Bretagne Occidentale,CA Quimperlé Communauté,CA Saint-Brieuc Armor Agglomération,CC Auray Quiberon Terre Atlantique,CC Douarnenez Communauté,CC Pontivy Communauté,Ploërmel Communauté,Rennes Métropole",actif,KorriGo - Fichier GTFS,main,false,GTFS,false,automatique,2024-06-04 06:08:13.564024,Warning,2026-01-01,559a4970c751df46a9a453ba,38,81559,1.0,0.9409509947773105,0.9982599916894433

**Comment by cyrilmorin** [comment]
c'est bon maintenant !!! Bon, c'était KO hier ou c'est l'export et la transmformation libre office / excel ... 
bon je ferme, sorry pour la fausse alerte
