### ISSUE TITLE
Requêteur SIRI : décoder réponses non encodées en UTF-8

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#3469]
Certains serveurs SIRI envoient des réponses encodées en Latin 1, qui n'est pas de l'UTF-8. Pour ces réponses, on n'affiche pas la réponse et notre LiveView crashe.

Vu en travaillant sur #3462 

Exemple avec `GetStopMonitoring` sur le serveur SIRI du réseau Mistral, Toulon. SAE INEO.

```xml
<S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/" xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"><S:Body><sw:GetStopMonitoring xmlns:sw="http://wsdl.siri.org.uk" xmlns:siri="http://www.siri.org.uk/siri"><ServiceRequestInfo><siri:RequestTimestamp>2023-09-18T14:24:38.251116Z</siri:RequestTimestamp><siri:RequestorRef>OPENDATA</siri:RequestorRef><siri:MessageIdentifier>Test::Message::febb1b1f-e4a4-486c-8041-1df40d4809ed</siri:MessageIdentifier></ServiceRequestInfo><Request><siri:RequestTimestamp>2023-09-18T14:24:38.251116Z</siri:RequestTimestamp><siri:MessageIdentifier>Test::Message::febb1b1f-e4a4-486c-8041-1df40d4809ed</siri:MessageIdentifier><siri:MonitoringRef>TOGR09</siri:MonitoringRef><siri:StopVisitTypes>all</siri:StopVisitTypes></Request><RequestExtension/></sw:GetStopMonitoring></S:Body></S:Envelope>
```

```
$ curl -vvv -X POST --data @request_pan.xml -H 'Accept: text/xml' -H 'Accept-charset: utf-8' https://saes.ratpdev.com/rdtpm

< HTTP/1.1 200 OK
< Server: nginx
< Date: Tue, 19 Sep 2023 05:57:07 GMT
< Content-Type: text/xml;charset=ISO-8859-1
< Content-Length: 9145
< Connection: keep-alive
< X-Powered-By: Undertow/1
```

Voir un exemple d'approche avec notre client HTTP : https://bernheisel.com/blog/httpoison-and-decompression

**Comment by thbar** [comment]
Quelques notes :
- contrairement à ce que je t’ai dit hier, on doit pouvoir se passer d’iconv sur ce cas et gérer juste avec https://www.erlang.org/doc/man/unicode.html
- Là elle n’est pas présente mais si elle l’était, la marque encoding en haut du XML devrait également être adaptée à la main (string replace) si présente !

**Comment by AntoineAugusti** [comment]
@thbar Avec unicode ça passe dans la PR, j'ai repris ce qui était partagé dans l'article de blog avec quelques ajustements.

**Comment by thbar** [comment]
TIL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Charset 

> Warning: Do not use this header. Browsers omit this header and servers should ignore it.

**Comment by AntoineAugusti** [comment]
@thbar Yes, j'avais vu et du coup je voulais voir si c'était pris en compte par le serveur mais visiblement c'est ignoré par tout le monde donc il faut faire avec ce qu'on nous retourne.
