### ISSUE TITLE
IRVE-Dynamique - horodatage et màj dynamique erronées ?

### ISSUE THREAD

**Issue by cyrilmorin** [etalab/transport-site#3477]
Hello !
J'ai quleques questionnements sur les données dynamiques IRVE :

1- [Eco-Movement](https://www.data.gouv.fr/fr/datasets/bornes-de-chargement-publiques-pour-voitures-electriques-du-plusieurs-operateurs/) met apparemment à jour le fichier dynamique toutes les 5 minutes (via api de mémoire). Vous confirmez (je ne sais pas où voir l'info). 
Lorsque je regarde l'horodatage dans [les données](https://explore.data.gouv.fr/?url=https%3A%2F%2Fwww.data.gouv.fr%2Ffr%2Fdatasets%2Fr%2Fb20d2793-db42-4d6d-a0b4-e94bf5ee4279) la dernière infos est remontée vers 1h ce matin.
![image](https://github.com/etalab/transport-site/assets/116101828/e07299c1-1f4c-4631-9e03-ff8c79ff7242)

C'est parce qu'ils renseignent la dernière heure de modif au lieu de renseigner la dernière heure d'update ?

2- moins grave mais un peu perturbant,  l'heure de modification est le 21/09 mais à 17:00 dans le turfu (probablement une histoire de config serveur ?)
![image](https://github.com/etalab/transport-site/assets/116101828/125fda39-6656-450f-b0a7-f69dd66b6357)

Merci !

**Comment by AntoineAugusti** [comment]
## Fréquence de mise à jour des fichiers

On ne peut pas voir si les ressources sont mises à jour via API ou "à la main" dans les métadonnées exposées par data.gouv.fr, seul le producteur pourra confirmer.

Pour savoir la date de dernier remplacement d'un fichier, tu peux :
- regarder l'URL static.data.gouv.fr, qui contient un timestamp à la fin (je ne sais pas si c'est UTC ou heure locale de Paris, à confirmer)
- regarder les réponses de [l'API data.gouv.fr du JDD](https://www.data.gouv.fr/api/1/datasets/bornes-de-chargement-publiques-pour-voitures-electriques-du-plusieurs-operateurs/) qui va indiquer l'URL + des champs de dates de data.gouv.fr

Au moment où j'écris ce commentaire (2023-09-21 16h45 Europe/Paris), le fichier indique `20230921-140003/irve-dynamique.csv` donc ils ne semblent pas remplacer toutes les 5 minutes actuellement. À confirmer avec eux.

➡️ EcoMovement

## Sur le contenu du fichier

Leur fichier, à la date 2023-09-21 16h45 Europe/Paris, contient comme valeur la plus récente `2023-09-21T00:59:30Z` ce qui est loin de l'heure courante. Pourtant le fichier a été upload à 14h (UTC ou Paris, à confirmer). À voir si il est possible d'avoir des données plus fraiches.

➡️ EcoMovement

## Sur les timestamps

Il y a une incohérence des fuseaux horaires côté API et interface data.gouv.fr, entre UTC et Europe/Paris

➡️ data.gouv.fr

**Comment by AntoineAugusti** [comment]
@cyrilmorin N'hésite pas à réouvrir si tu penses qu'on a une responsabilité côté PAN. Et si besoin d'aide technique tu sais où nous trouver.

**Comment by maudetes** [comment]
Je viens de faire un tour sur les dates data.gouv.fr entre celles renseignées, détectées ou affichées dans l'admin.
En créant [une nouvelle ressource de test](https://demo.data.gouv.fr/fr/datasets/un-jeu-de-test-des-dates/#/resources/c0120328-ba12-4288-a293-b87a7b238d2e), on a bien toutes nos dates en UTC par API (10:57) :
```
    {
      "created_at": "2023-12-01T10:57:20.562000+00:00",
      "internal": {
        "created_at_internal": "2023-12-01T10:57:20.562000+00:00",
        "last_modified_internal": "2023-12-01T10:57:23.610000+00:00"
      },
      "last_modified": "2023-12-01T10:57:23.610000+00:00",
      "url": "https://demo-static.data.gouv.fr/resources/un-jeu-de-test-des-dates/20231201-105720/author.png",
      "...": "..."
    }
```
Et celle affichée sur l'admin est en timezone locale (Paris)
![image](https://github.com/etalab/transport-site/assets/28541902/84a9e544-4bf4-46b6-aa94-6fb59a1dbafb)

J'ai pour l'instant du mal à m'expliquer la différence dans le cas du [fichier IRVE dynamique](https://www.data.gouv.fr/api/1/datasets/bornes-de-chargement-publiques-pour-voitures-electriques-du-plusieurs-operateurs/), où ça diffère en effet.

**Comment by AntoineAugusti** [comment]
@maudetes As-tu fait tes tests en utilisant l'admin data.gouv.fr dans un navigateur ? Est-il possible qu'il y ait une différence de comportement quand la mise à jour est effectuée via l'API ?
