### ISSUE TITLE
Migrer les emails existants vers Swoosh

### ISSUE THREAD

**Issue by vdegove** [etalab/transport-site#3481]
Voir [ce qui a été fait pour les formulaires de feedback et de contact](https://github.com/etalab/transport-site/pull/3451), ainsi que pour la notification resource_changed_notification_job. Pour chaque email envoyé :
- 1. Modifier le code
- 2. Modifier les tests en s’appuyant sur les helpers Swoosh

À voir, mais ça peut être pertinent :
- De créer un module unique `Transport.UserNotifier` avec une fonction différente par email envoyé (et du coup supprimer `Transport.ResourcesChangedNotifier`)
- À la fin on peut supprimer le mailer historique, et sa version mock. Attention : la vue `TransportWeb.EmailView` est commune au mailer historique et au mailer Swoosh (et permet automagiquement, de mémoire, de gérer les templates Markdown), pas la supprimer.
- Voir pour un mécanisme asynchrone qui crée des jobs d’envoi, pour l’instant côté feedback et formulaire de contact c’est du synchrone.

**Comment by AntoineAugusti** [comment]
Il y a un adapter qui a été ajouté pour Scaleway ! https://github.com/swoosh/swoosh/pull/825

**Comment by vdegove** [comment]
Ça tombe bien ça !
