### ISSUE TITLE
Conversion NeTEx : ne pas proposer de conversion quand une ressource est présente

### ISSUE THREAD

**Issue by cyrilmorin** [etalab/transport-site#3490]
Demande légitime de datasud => ne plus proposer de conversion auto netex dans la mesure où ils publient du Netex eux-mêmes

L'option tordue et probablement couteuse : 
=> Ne pas proposer de conversion netex lorsqu'une autre ressource du jeu est au format netex

L'option visée et optimale vu que l'ART n'acceptera prochainement plus ces conversions pour considérer l'AOM comme "en règle" ET au vue du faible nb d'utilisations 70 sur l'année de mémoire ...
=> Supprimer rapidement la conversion auto Netex depuis nos ressources PAN

Je rajoute qu'on serait en totale cohérence avec l'arrêt de la conversion des flux GBFS !

**Comment by AntoineAugusti** [comment]
> L'option tordue et probablement couteuse : => Ne pas proposer de conversion NeTEx lorsqu'une autre ressource du jeu est au format NeTEx

On peut avoir une règle simple "dès qu'on a au moins 1 NeTEx" dans le JDD mais peut-être trop simple pour JDD avec plusieurs GTFS ou la publication d'un NeTEx autre périmètre (genre tarifaire ou accessibilité). Ce n'est pas spécialement coûteux en terme de dev.

Si la règle simple et globale n'est pas une option, on peut proposer de désactiver en espace producteur (leur responsabilité, par JDD) ou backoffice (notre équipe, mais difficile de faire connaître cette possibilité). Ces 2 solutions ont plus couteuses.

> L'option visée et optimale vu que l'ART n'acceptera prochainement plus ces conversions pour considérer l'AOM comme "en règle" ET au vue du faible nb d'utilisations 70 sur l'année de mémoire ... => Supprimer rapidement la conversion auto Netex depuis nos ressources PAN
Doit-on ne pas convertir/afficher la conversion automatique quand ils publient en NeTEx ?

Me semble que ces conversions sont importantes pour s'assurer d'une conformité à la réglementation 🇪🇺 et qu'on pourrait envisager de couper mais en prévenant extrêmement longtemps en avance, genre plusieurs années.

## Changement de prestataire pour les conversions

Si on n'arrête pas les conversions faut qu'on passe du [convertisseur Kisio](https://github.com/hove-io/transit_model/tree/master/gtfs2netexfr) à EnRoute aussi. https://github.com/etalab/transport-site/issues/3427

**Comment by AntoineAugusti** [comment]
@cyrilmorin Je pense traiter ce ticket prochainement.

En réévaluant les choses et en regardant un peu les données, j'envisage de suivre ce que tu avais indiqué comme première possibilité.

> Ne pas proposer de conversion NeTEx lorsqu'une autre ressource du jeu est au format NeTEx

On garderait cette règle et si ça présente des difficultés on revoit notre positionnement ? On pourra proposer de faire ça depuis l'espace producteur ou en ajoutant un tag spécial sur un JDD par exemple.

Ça te parait bien ?

**Comment by cyrilmorin** [comment]
@AntoineAugusti oui me ça semble aussi une bonne 1ère solution pour gérer ces 1ers cas
