### ISSUE TITLE
Bug de compilation sur `phoenix_markdown`

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#3499]
Situation bizarre de compilation que j'ai rencontré en local:

```
❯ mix test
==> phoenix_markdown
Compiling 2 files (.ex)
error: Earmark.Options.__struct__/0 is undefined, cannot expand struct Earmark.Options. Make sure the struct name is correct. If the struct name exists and is correct but it still cannot be found, you likely have cyclic module usage in your code
  lib/phoenix_markdown/engine.ex:25: PhoenixMarkdown.Engine.compile/2


== Compilation error in file lib/phoenix_markdown/engine.ex ==
** (CompileError) lib/phoenix_markdown/engine.ex: cannot compile module PhoenixMarkdown.Engine (errors have been logged)
    (stdlib 3.17.2.4) lists.erl:1358: :lists.mapfoldl/3
could not compile dependency :phoenix_markdown, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile phoenix_markdown --force", update it with "mix deps.update phoenix_markdown" or clean it with "mix deps.clean phoenix_markdown"
```

Pas sûr de comment je suis tombé là dedans mais je note, et je vais aller commenter ici:
- https://github.com/elixir-lang/elixir/issues/12913

**Comment by josevalim** [comment]
Bonjour, this PR should address it: https://github.com/boydm/phoenix_markdown/pull/13

**Comment by thbar** [comment]
Thank you @josevalim!!!

**Comment by thbar** [comment]
Je tente d'obtenir un merge de PR sur le projet associé, dans l'espoir que ça corrige (problème sporadique).

Nos options principales sont:
- obtenir une MAJ de la librairie
- un petit fork dans `etalab`
- un "vendoring" dans l'application vu que le code est petit

**Comment by AntoineAugusti** [comment]
Tiens j'ai eu ce problème aussi, j'ai `rm -rf _build` et relancé

**Comment by AntoineAugusti** [comment]
J'ai fait un fix sur `scrivener_html` aussi https://github.com/mgwidmann/scrivener_html/pull/110
