### ISSUE TITLE
Consolidation BNLC - colonnes supplémentaires intégrées au fichier final

### ISSUE THREAD

**Issue by AurelienC** [etalab/transport-site#3511]
Lié à #3419 

La consolidation se fait avec deux ressources. [L'une d'entre elles](https://www.data.gouv.fr/fr/datasets/test-lieux-de-covoiturage-organisation-point-dacces-national-transport-data-gouv-fr/) contient des colonnes (autre1, autre2) qui n'existent pas dans le schéma.
![image](https://github.com/etalab/transport-site/assets/4528670/41f7bc17-e2e6-4b8a-ad59-6fa7f0b781fa)

Ces données ne doivent pas se retrouver dans le fichier final de la consolidation (données à droite de la colonne en jaune, ligne rouge)
![image](https://github.com/etalab/transport-site/assets/4528670/ddac7b29-1cb8-45bf-b16f-dd3c13beda01)

**Comment by AntoineAugusti** [comment]
Bien vu, merci !
