### ISSUE TITLE
DatabaseBackupReplicationJob : timeout lors de l'upload vers Scaleway

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#3529]
Le job `DatabaseBackupReplicationJob` est en charge de répliquer quotidiennement nos sauvegardes de bases de données de Clever Cloud vers Scaleway.

Il arrive que ce job fail à cause d'un timeout lors de l'upload vers Scaleway.

https://github.com/etalab/transport-site/blob/bb2d2c705bc321a7e968a43b8218f2feb446a13f/apps/transport/lib/jobs/database_backup_replication_job.ex#L46-L47

Stracktrace

```
** (Oban.CrashError) ** (exit) exited in: Task.Supervised.stream(30000)
** (EXIT) time out
(elixir 1.15.5) lib/task/supervised.ex:314: Task.Supervised.stream_reduce/7
(elixir 1.15.5) lib/enum.ex:4387: Enum.map/2
(ex_aws_s3 2.4.0) lib/ex_aws/s3/upload.ex:126: ExAws.Operation.ExAws.S3.Upload.perform/2
(ex_aws 2.5.0) lib/ex_aws.ex:85: ExAws.request!/2
(transport 0.0.1) lib/jobs/database_backup_replication_job.ex:48: Transport.Jobs.DatabaseBackupReplicationJob.upload!/1
(transport 0.0.1) lib/jobs/database_backup_replication_job.ex:18: Transport.Jobs.DatabaseBackupReplicationJob.perform/1
(oban 2.15.4) lib/oban/queue/executor.ex:129: Oban.Queue.Executor.perform/1
(oban 2.15.4) lib/oban/queue/executor.ex:74: Oban.Queue.Executor.call/1\n
```

C'est assez étonnant car :
- le timeout est de 30s pour un multiupload part et que le fichier à envoyer fait 1 Go
- le job retry 3 fois, avec 1 minute d'intervalle et fail 3 fois de suite. Il est possible d'avoir un problème réseau ponctuel mais pendant 3-4 minutes chez Scaleway (ou entre Clever Cloud et Scaleway) me parait étonnant
- je n'ai pas vu d'incident réseau déclaré chez Scaleway/Clever au moment où ceci survenait
- j'ai parfois ouvert des tickets pour demander des précisions et on ne m'a pas signalé d'incident réseau

Bref, je ne suis pas sûr de comment résoudre ça.

Quelques solutions bof (?!?) :
- avoir un timeout plus important https://github.com/ex-aws/ex_aws_s3/blob/eba66287297db8447627555981079e7da197e6c3/lib/ex_aws/s3.ex#L788
- avoir plus de retries/un délai plus espacé
- faire plus de tickets pour investiguer
- le problème est autre

**Comment by AntoineAugusti** [comment]
@thbar devrait t'intéresser ! Au passage le download/upload de backups BDD sur S3 sont bien streamés.

**Comment by thbar** [comment]
> Au passage le download/upload de backups BDD sur S3 sont bien streamés.

Ah c'est une super nouvelle, merci d'avoir vérifié :smile:

> le timeout est de 30s pour un multiupload part et que le fichier à envoyer fait 1 Go

Pour un fichier de cette taille ça ne me choque pas de monter quand même, ça commence à faire une belle taille, on pourrait "logger" l'upload progress pour vérifier mais c'est peut-être juste une question de temps.

D'ailleurs pour savoir de combien, une connection en SSH sur le node et une exécution à la main permettrait d'en savoir davantage, en conditions réelles.

Je passerais bien à 3 minutes par exemple.

**Comment by AntoineAugusti** [comment]
Testé sur `prod-worker` à l'instant, c'est pas stable.

```
iex(2)> DateTime.utc_now(); latest_dump() |> upload!(); DateTime.utc_now()
** (exit) exited in: Task.Supervised.stream(30000)
    ** (EXIT) time out
    (elixir 1.15.5) lib/task/supervised.ex:314: Task.Supervised.stream_reduce/7
    (elixir 1.15.5) lib/enum.ex:4387: Enum.map/2
    (ex_aws_s3 2.4.0) lib/ex_aws/s3/upload.ex:126: ExAws.Operation.ExAws.S3.Upload.perform/2
    (ex_aws 2.5.0) lib/ex_aws.ex:85: ExAws.request!/2
    (transport 0.0.1) lib/jobs/database_backup_replication_job.ex:48: Transport.Jobs.DatabaseBackupReplicationJob.upload!/1
iex(2)> 16:23:01.393 [notice]     :alarm_handler: {:clear, :system_memory_high_watermark}
 
nil
iex(3)> IO.inspect(DateTime.utc_now()); latest_dump() |> upload!(); IO.inspect(DateTime.utc_now())
~U[2023-10-12 14:24:12.650512Z]
16:25:01.399 [notice]     :alarm_handler: {:set, {:system_memory_high_watermark, []}}
** (exit) exited in: Task.Supervised.stream(30000)
    ** (EXIT) time out
    (elixir 1.15.5) lib/task/supervised.ex:314: Task.Supervised.stream_reduce/7
    (elixir 1.15.5) lib/enum.ex:4387: Enum.map/2
    (ex_aws_s3 2.4.0) lib/ex_aws/s3/upload.ex:126: ExAws.Operation.ExAws.S3.Upload.perform/2
    (ex_aws 2.5.0) lib/ex_aws.ex:85: ExAws.request!/2
    (transport 0.0.1) lib/jobs/database_backup_replication_job.ex:48: Transport.Jobs.DatabaseBackupReplicationJob.upload!/1
iex(3)> 16:26:01.402 [notice]     :alarm_handler: {:clear, :system_memory_high_watermark}
 
nil
iex(4)> IO.inspect(DateTime.utc_now()); latest_dump() |> upload!(); IO.inspect(DateTime.utc_now())
~U[2023-10-12 14:26:26.762016Z]
~U[2023-10-12 14:27:00.094757Z]
```

**Comment by thbar** [comment]
> Task.Supervised.stream(30000)

C'est un timeout de 30 secondes là ? Je pense qu'il faudra gonfler, 1 GB c'est quand même joufflu.

**Comment by AntoineAugusti** [comment]
@thbar C'était 30s par défaut mais j'ai augmenté en suivant ta suggestion, voir la PR :)

**Comment by AntoineAugusti** [comment]
@thbar Oui avant c'était la valeur par défaut à 30s donc. Ça passe sans problème et on a eu environ 5 fails sur 3 mois donc augmenter un peu devrait faire l'affaire.

**Comment by thbar** [comment]
Ok super !

**Comment by thbar** [comment]
Il faut qu'on voit si le timeout de 90 secondes qui a été mergé a été suffisant !

Je peux aller voir demain.

**Comment by AntoineAugusti** [comment]
@thbar Tu peux aller vérifier mais il me semble que c'est bon car on reçoit un e-mail en cas d'erreur sur ce job. #3395

**Comment by thbar** [comment]
J'ai été vérifier ce matin en regardant mais aussi en en profitant pour faire un "restore testé", et tout semble ok:

![CleanShot 2023-10-23 at 09 01 30@2x](https://github.com/etalab/transport-site/assets/10141/43fa02b5-79ed-4baf-9ac7-909fe025347a)

Je ne vois d'ailleurs pas de "trou" dans la séquence, ce qui indique que le timeout est absent de façon durable sur la période observée.

<img width="624" alt="CleanShot 2023-10-23 at 09 01 59@2x" src="https://github.com/etalab/transport-site/assets/10141/52a559ae-9c92-405e-9308-4f37df9e8b02">

Merci pour le fix @AntoineAugusti, c'est OK !
