### ISSUE TITLE
Mise à jour données géographiques millésime 2023

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#3537]
Prévoir de mettre à jour les données des :
- [x] communes
- [x] Départements ?
- [x] AOMs
- [x] associations AOMs <> communes (ou régions)
- [x] EPCI

Optionnel :
- [ ] #3720

Les [données des AOMs viennent du Cerema](https://www.cerema.fr/fr/actualites/liste-composition-autorites-organisatrices-mobilite-au-1er-4) et nécessitent un travail de nettoyage en local dans un tableur ou avec un rapide script. Il sera peut-être nécessaire d'ajuster la tâche d'import `ImportAOM`.

Précédentes PRs utiles à regarder
- https://github.com/etalab/transport-site/pull/2665
- https://github.com/etalab/transport-site/pull/2690
- https://github.com/etalab/transport-site/pull/2612

**Comment by vdegove** [comment]
Pour les AOM : le site du Cerema n’a pas posté d’article lié comme pour 2022, mais les données ont bien été mises à jour en juillet 2023 ici https://transport.data.gouv.fr/datasets/liste-et-composition-des-autorites-organisatrices-de-la-mobilite-aom – ils ont en réalité rajouté une nouvelle resource plutôt que remplacer l’ancienne.

**Comment by vdegove** [comment]
En cas de doute voir BANATIC https://www.banatic.interieur.gouv.fr/V5/recherche-de-groupements/fiche-raison-sociale.php?siren=242100410&arch=01/01/2023&dcou=

**Comment by AntoineAugusti** [comment]
@vdegove Peux-tu lancer les tâches Mix pour mettre à jour les données géo en staging ?
