### ISSUE TITLE
GTFS avec fichiers dans un sous-dossier

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#3540]
La spécification GTFS a été clarifiée pour indiquer que les fichiers TXT doivent être à la racine d'une archive ZIP et non dans un sous-dossier. https://github.com/google/transit/pull/379

> All dataset files must be zipped together. The files must reside at the root level directly, not in a subfolder.

Il faut :
- [x] prévenir les producteurs de ces données ce problème (@AntoineAugusti)
- [x] adapter notre validateur GTFS pour lever une erreur à l'avenir https://github.com/etalab/transport-validator/issues/160

Les jeux de données suivants ont actuellement un GTFS avec des fichiers dans un sous-dossier et non à la racine.

|filenames|dataset_id|dataset_url|resource_title|
| --- | --- | --- | --- |
|   \["GTFS\_20230927\_143025\_BAIA/", "GTFS\_20230927\_143025\_BAIA/GTFS\_20230927\_143025\_BAIA.zip", "GTFS\_20230927\_143025\_BAIA/agency.txt", "GTFS\_20230927\_143025\_BAIA/calendar.txt", "GTFS\_20230927\_143025\_BAIA/calendar\_dates.txt", "GTFS\_20230927\_143025\_BAIA/routes.txt", "GTFS\_20230927\_143025\_BAIA/stop\_times.txt", "GTFS\_20230927\_143025\_BAIA/stops.txt", "GTFS\_20230927\_143025\_BAIA/trips.txt"\]   |   47   |   https://transport.data.gouv.fr/datasets/offre-de-transports-cobas-reseau-baia-gtfs   |   Horaires valables jusqu'au 7 janvier 2024   |
|   \["GTFS/agency.txt", "GTFS/calendar.txt", "GTFS/calendar\_dates.txt", "GTFS/routes.txt", "GTFS/shapes.txt", "GTFS/stop\_times.txt", "GTFS/stops.txt", "GTFS/transfers.txt", "GTFS/trips.txt"\]   |   141   |   https://transport.data.gouv.fr/datasets/arrets-et-horaires-theoriques-bus   |   Export au format CSV   |
|   \["gtfs-moova/agency.txt", "gtfs-moova/calendar.txt", "gtfs-moova/calendar\_dates.txt", "gtfs-moova/routes.txt", "gtfs-moova/shapes.txt", "gtfs-moova/stop\_times.txt", "gtfs-moova/stops.txt", "gtfs-moova/trips.txt"\]   |   171   |   https://transport.data.gouv.fr/datasets/horaires-theoriques-du-reseau-moova-communaute-dagglomeration-de-vesoul-gtfs   |   gtfs-moova.zip   |
|   \["GTFS-20231012-20231225-20231012131814/", "GTFS-20231012-20231225-20231012131814/agency.txt", "GTFS-20231012-20231225-20231012131814/calendar.txt", "GTFS-20231012-20231225-20231012131814/calendar\_dates.txt", "GTFS-20231012-20231225-20231012131814/routes.txt", "GTFS-20231012-20231225-20231012131814/shapes.txt", "GTFS-20231012-20231225-20231012131814/stop\_times.txt", "GTFS-20231012-20231225-20231012131814/stops.txt", "GTFS-20231012-20231225-20231012131814/trips.txt"\]   |   232   |   https://transport.data.gouv.fr/datasets/gtfs-diviamobilites   |   gtfs-diviamobilites-current.zip   |
|   \["\_\_MACOSX/.\_agency.txt", "\_\_MACOSX/.\_calendar.txt", "\_\_MACOSX/.\_calendar\_dates.txt", "\_\_MACOSX/.\_routes.txt", "\_\_MACOSX/.\_shapes.txt", "\_\_MACOSX/.\_stop\_times.txt", "\_\_MACOSX/.\_stops.txt", "\_\_MACOSX/.\_trips.txt", "\_\_MACOSX/.\_trips\_extensions.txt", "agency.txt", "calendar.txt", "calendar\_dates.txt", "routes.txt", "shapes.txt", "stop\_times.txt", "stops.txt", "trips.txt", "trips\_extensions.txt"\]   |   598   |   https://transport.data.gouv.fr/datasets/reseau-urbain-cacl-agglobus   |   cacl-l7-obis-ligne-7-gtfs-2023-06-08-05-33-51-v2.zip   |
|   \["GTFS 190623/agency.txt", "GTFS 190623/calendar.txt", "GTFS 190623/calendar\_dates.txt", "GTFS 190623/feed\_info.txt", "GTFS 190623/routes (002).txt", "GTFS 190623/routes.txt", "GTFS 190623/stop\_times.txt", "GTFS 190623/stops.txt", "GTFS 190623/trips.txt"\]   |   656   |   https://transport.data.gouv.fr/datasets/reseau-de-bus-urbain-horizon   |   GTFS \_190623.zip   |
|   \["GTFS 190623/agency.txt", "GTFS 190623/calendar.txt", "GTFS 190623/calendar\_dates.txt", "GTFS 190623/feed\_info.txt", "GTFS 190623/routes (002).txt", "GTFS 190623/routes.txt", "GTFS 190623/stop\_times.txt", "GTFS 190623/stops.txt", "GTFS 190623/trips.txt"\]   |   656   |   https://transport.data.gouv.fr/datasets/reseau-de-bus-urbain-horizon   |   GTFS \_190623.zip   |
|   \["GTFS AUTOMNE 2023/", "GTFS AUTOMNE 2023/agency.txt", "GTFS AUTOMNE 2023/calendar.txt", "GTFS AUTOMNE 2023/calendar\_dates.txt", "GTFS AUTOMNE 2023/routes.txt", "GTFS AUTOMNE 2023/shapes.txt", "GTFS AUTOMNE 2023/stop\_times.txt", "GTFS AUTOMNE 2023/stops.txt", "GTFS AUTOMNE 2023/trips.txt"\]   |   776   |   https://transport.data.gouv.fr/datasets/chamonix-bus-1   |   GTFS AUTOMNE 2023   |
|   \["RTUD\_gtfs\_2022-10-10\_09-28-07/", "RTUD\_gtfs\_2022-10-10\_09-28-07/agency.txt", "RTUD\_gtfs\_2022-10-10\_09-28-07/calendar.txt", "RTUD\_gtfs\_2022-10-10\_09-28-07/calendar\_dates.txt", "RTUD\_gtfs\_2022-10-10\_09-28-07/routes.txt", "RTUD\_gtfs\_2022-10-10\_09-28-07/shapes.txt", "RTUD\_gtfs\_2022-10-10\_09-28-07/stop\_times.txt", "RTUD\_gtfs\_2022-10-10\_09-28-07/stops.txt", "RTUD\_gtfs\_2022-10-10\_09-28-07/trips.txt", "RTUD\_gtfs\_2022-10-10\_09-28-07/trips\_extensions.txt"\]   |   801   |   https://transport.data.gouv.fr/datasets/reseau-de-transport-urbains-dignois   |   Transports Urbains Dignois (TUD).GTFS   |
|   \["\_\_MACOSX/.\_agency.txt", "\_\_MACOSX/.\_calendar.txt", "\_\_MACOSX/.\_calendar\_dates.txt", "\_\_MACOSX/.\_routes.txt", "\_\_MACOSX/.\_shapes.txt", "\_\_MACOSX/.\_stop\_times.txt", "\_\_MACOSX/.\_stops.txt", "\_\_MACOSX/.\_trips.txt", "\_\_MACOSX/.\_trips\_extensions.txt", "agency.txt", "calendar.txt", "calendar\_dates.txt", "routes.txt", "shapes.txt", "stop\_times.txt", "stops.txt", "trips.txt", "trips\_extensions.txt"\]   |   820   |   https://transport.data.gouv.fr/datasets/gtfs-urbain-de-la-zone-sud   |   gtfs-sud-sudlib.zip   |
|   \["\_\_MACOSX/.\_agency.txt", "\_\_MACOSX/.\_calendar.txt", "\_\_MACOSX/.\_calendar\_dates.txt", "\_\_MACOSX/.\_routes.txt", "\_\_MACOSX/.\_shapes.txt", "\_\_MACOSX/.\_stop\_times.txt", "\_\_MACOSX/.\_stops.txt", "\_\_MACOSX/.\_trips.txt", "agency.txt", "calendar.txt", "calendar\_dates.txt", "routes.txt", "shapes.txt", "stop\_times.txt", "stops.txt", "trips.txt"\]   |   821   |   https://transport.data.gouv.fr/datasets/gtfs-urbain-de-la-zone-centre   |   gtfs-centre-rtm.zip   |
|   \["GTFS\_Evad\_0910au10122023/GTFS Evad 0910 au 1012 2023/", "GTFS\_Evad\_0910au10122023/GTFS Evad 0910 au 1012 2023/agency.txt", "GTFS\_Evad\_0910au10122023/GTFS Evad 0910 au 1012 2023/calendar.txt", "GTFS\_Evad\_0910au10122023/GTFS Evad 0910 au 1012 2023/calendar\_dates.txt", "GTFS\_Evad\_0910au10122023/GTFS Evad 0910 au 1012 2023/routes.txt", "GTFS\_Evad\_0910au10122023/GTFS Evad 0910 au 1012 2023/shapes.txt", "GTFS\_Evad\_0910au10122023/GTFS Evad 0910 au 1012 2023/stop\_times.txt", "GTFS\_Evad\_0910au10122023/GTFS Evad 0910 au 1012 2023/stops.txt", "GTFS\_Evad\_0910au10122023/GTFS Evad 0910 au 1012 2023/trips.txt"\]   |   862   |   https://transport.data.gouv.fr/datasets/donnees-du-reseau-evad-1   |   gtfs-evad-1-.zip   |
|   \["\_\_MACOSX/.\_agency.txt", "\_\_MACOSX/.\_calendar.txt", "\_\_MACOSX/.\_calendar\_dates.txt", "\_\_MACOSX/.\_routes.txt", "\_\_MACOSX/.\_shapes.txt", "\_\_MACOSX/.\_stop\_times.txt", "\_\_MACOSX/.\_stops.txt", "\_\_MACOSX/.\_trips.txt", "agency.txt", "calendar.txt", "calendar\_dates.txt", "routes.txt", "shapes.txt", "stop\_times.txt", "stops.txt", "trips.txt"\]   |   881   |   https://transport.data.gouv.fr/datasets/gtfs-urbain-de-la-zone-nord-cap-nord   |   gtfs-nord-rtm.zip   |
|   \["GTFS 17 04 2023 au 31 12 2023/", "GTFS 17 04 2023 au 31 12 2023/agency.txt", "GTFS 17 04 2023 au 31 12 2023/calendar.txt", "GTFS 17 04 2023 au 31 12 2023/calendar\_dates.txt", "GTFS 17 04 2023 au 31 12 2023/routes.txt", "GTFS 17 04 2023 au 31 12 2023/shapes.txt", "GTFS 17 04 2023 au 31 12 2023/stop\_times.txt", "GTFS 17 04 2023 au 31 12 2023/stops.txt", "GTFS 17 04 2023 au 31 12 2023/trips.txt"\]   |   936   |   https://transport.data.gouv.fr/datasets/mobivie-reseau-urbain-vichy-communaute   |   mobivie-gtfs-14042023-31122023.zip   |
|   \["GTFS\_SCOLAIRES/agency.txt", "GTFS\_SCOLAIRES/calendar.txt", "GTFS\_SCOLAIRES/calendar\_dates.txt", "GTFS\_SCOLAIRES/routes.txt", "GTFS\_SCOLAIRES/shapes.txt", "GTFS\_SCOLAIRES/stop\_times.txt", "GTFS\_SCOLAIRES/stops.txt", "GTFS\_SCOLAIRES/transfers.txt", "GTFS\_SCOLAIRES/trips.txt"\]   |   966   |   https://transport.data.gouv.fr/datasets/arrets-et-horaires-theoriques-bus-des-lignes-scolaires   |   Export au format CSV   |

## Requête SQL

```sql
select
  rh.payload->>'filenames',
  d.id dataset_id,
  'https://transport.data.gouv.fr/datasets/' || d.slug,
  r.title
from resource r
join dataset d on d.id = r.dataset_id and d.is_active
join (
  select
    rh.*,
    row_number() over (partition by rh.resource_id order by rh.inserted_at desc) row_number
  from resource_history rh
) rh on rh.resource_id = r.id and rh.row_number = 1 and rh.payload->>'format' = 'GTFS'
where (rh.payload->>'filenames')::varchar like '%/%'
```

**Comment by thbar** [comment]
Super ! En théorie ça doit se recouper avec ce qui est détecté comme erreurs d'imports par le batch nocturne global des GTFS (https://transport.data.gouv.fr/backoffice/batch-report).

J'ai copié collé ça donne ça (j'en compte rapidement 16 au lieu de 15, mais je n'ai pas comparé les ids).

À toutes fins utiles :-)

* [81291](https://transport.data.gouv.fr/resources/81291)	99100	error	Unzip.Error	File "stops.txt" not present in the zip
* [81184](https://transport.data.gouv.fr/resources/81184)	90636	error	Unzip.Error	File "stops.txt" not present in the zip
* [81222](https://transport.data.gouv.fr/resources/81222)	102003	error	Unzip.Error	File "stops.txt" not present in the zip
* [80742](https://transport.data.gouv.fr/resources/80742)	102062	error	Unzip.Error	File "stops.txt" not present in the zip
* [81092](https://transport.data.gouv.fr/resources/81092)	97718	error	Unzip.Error	File "stops.txt" not present in the zip
* [81090](https://transport.data.gouv.fr/resources/81090)	99029	error	Unzip.Error	File "stops.txt" not present in the zip
* [81081](https://transport.data.gouv.fr/resources/81081)	102772	error	Unzip.Error	File "stops.txt" not present in the zip
* [81091](https://transport.data.gouv.fr/resources/81091)	101671	error	Unzip.Error	File "stops.txt" not present in the zip
* [81022](https://transport.data.gouv.fr/resources/81022)	82764	error	Unzip.Error	File "stops.txt" not present in the zip
* [81021](https://transport.data.gouv.fr/resources/81021)	82763	error	Unzip.Error	File "stops.txt" not present in the zip
* [81199](https://transport.data.gouv.fr/resources/81199)	92001	error	Unzip.Error	File "stops.txt" not present in the zip
* [79810](https://transport.data.gouv.fr/resources/79810)	86715	error	Unzip.Error	File "stops.txt" not present in the zip
* [81176](https://transport.data.gouv.fr/resources/81176)	88220	error	Unzip.Error	File "stops.txt" not present in the zip
* [80973](https://transport.data.gouv.fr/resources/80973)	101390	error	Unzip.Error	File "stops.txt" not present in the zip
* [80965](https://transport.data.gouv.fr/resources/80965)	77711	error	Unzip.Error	File "stops.txt" not present in the zip
* [81188](https://transport.data.gouv.fr/resources/81188)	90647	error	Unzip.Error	File "stops.txt" not present in the zip

**Comment by thbar** [comment]
(la conséquence est que ces jeux n'apparaissent pas ni sur la carte, ni dans l'API gtfs-stops, ni dans l'export global)

**Comment by thbar** [comment]
Pour info @bmericskay, d'ailleurs, ceci a un impact sur tes infographies :smile:
