### ISSUE TITLE
Suivre le nombre de "PDC" de la consolidation IRVE dans le temps

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#3544]
Je ne crois pas qu'on dispose de grand chose pour ça et c'est dommage.

En travaillant sur #3543, j'ai remarqué que cette nuit on avait perdu (il me semble, sauf erreur) 2000 points de charge.

Je sais qu'il y a des logs etc, mais je pense qu'avoir un petit suivi du volume a minima permettrait de mieux suivre l'évolution.

Ca pourrait être fait grâce à une historisation tous les jours, par exemple, et analyse a posteriori.

À réfléchir mais je pense qu'avoir un peu de pilotage là dessus serait nécessaire.

**Comment by AntoineAugusti** [comment]
L'autre cas d'usage que je vois c'est d'avoir un chiffre dynamique/fiable sur le message de la catégorie `charging-stations` https://transport.data.gouv.fr/datasets?type=charging-stations

**Comment by AntoineAugusti** [comment]
Ça peut potentiellement se stocker en tant qu'entier dans `stats_history` via [StatsHandler](https://github.com/etalab/transport-site/blob/804353718391c5ac3a8ba1f1e24aa31787840302/apps/transport/lib/transport/stats_handler.ex#L1), peut-être pour tout ce qui se trouve dans `geo_data`. Un nombre de lignes simple.

**Comment by thbar** [comment]
Yes c'est une bonne idée de stocker ça a minima.

@AntoineAugusti que penses-tu d'historiser par ailleurs (pas forcément pour ce suivi) le jeu dans le temps, genre une fois par jour ? Je me demande si ça ne va pas nous aider à faire des analyses plus poussées, une fois qu'on aura constaté la chute ; je me pose aussi la question par rapport au travail sur le concentrateur IRVE qui va débuter, ça pourrait être bien utile de pouvoir dire "à telle date, tel fournisseur a modifié sa façon de codifier et ça pose problème".

**Comment by AntoineAugusti** [comment]
La base nationale statique IRVE est déjà consolidée étant donné que c'est une ressource comme une autre.

```sql
select *
from resource_history rh
where rh.resource_id = 79624
```

**Comment by thbar** [comment]
Merci @AntoineAugusti - j'ai pu grapher le résultat avec ta requête et un coup de Livebook (je partage ça à côté), ça donne actuellement:

<img width="922" alt="CleanShot 2023-10-20 at 09 09 57@2x" src="https://github.com/etalab/transport-site/assets/10141/f811cc1e-5a6b-4e16-8ac5-6d926ee401d3">

C'est quand même grandement instable...

À partir du Livebook que j'ai créé il serait facile de lister jour par jour les "gros producteurs" qui disparaissent, par exemple.

À rediscuter j'en reste là pour le moment.

**Comment by thbar** [comment]
On va discuter de tout ça avec Qualicharge (Nicolas Forget et @jmaupetit), en l'état je clôture.
