### ISSUE TITLE
Écrire quelques tests pour les enregistrements DNS importants

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#3554]
Suggestion provenant de https://github.com/etalab/transport-site/pull/3552#pullrequestreview-1689922740

Il n'y a pas de fournisseur DNS pour notre hébergeur DNS actuel (AlwaysData) malheureusement. Si on passe à Scaleway il y a [ce qu'il faut](https://registry.terraform.io/providers/scaleway/scaleway/latest/docs/resources/domain_record).

On peut au moins écrire des tests pour les enregistrements liés :
- aux e-mails (SPF + DKIM + MX)
- aux sites satellites comme normes/validation/contribuer

**Comment by thbar** [comment]
Merci pour le ticket ! Note : si on veut éviter de faire un shell-out à `dig`, on peut s'appuyer sur une librairie comme https://github.com/tungd/elixir-dns.
