### ISSUE TITLE
Ajouter "Données" dans le menu

### ISSUE THREAD

**Issue by AurelienC** [etalab/transport-site#3566]
Permettre d'accéder à la page des jeux de données (`/datasets`) directement via le menu sur site.

Exemple :
<img width="1439" alt="image" src="https://github.com/etalab/transport-site/assets/4528670/88734d20-1308-4bee-b504-2a41ec556ade">

C'est ici ? 👀
https://github.com/etalab/transport-site/blob/0777938c8a3a99d862d53ef93ff58862b797999b/apps/transport/lib/transport_web/templates/layout/_header.html.heex

**Comment by AurelienC** [comment]
Un travail pour réduire la taille du menu pourrait être envisagé ?

### Menu actuel
- Documentation
- Outils
  - Vérifier la qualité d'un fichier ou d'un flux
  - Comparer deux GTFS
  - Générateur de requêtes SIRI
  - Carte d'exploration
  - Carte nationale des arrêts GTFS
  - État des services
- Infos producteurs
- Règlementation
  - Normes
  - Loi climat et résilience
  - Déclaration de conformité 
- A propos
  - Nos missions
- Blog

---
### Menu réduit ?
- Données
- Outils
  - Espace producteur 
  - Vérifier la qualité d'un fichier ou d'un flux
  - Comparateur de GTFS
  - Générateur de requêtes SIRI
  - Carte d'exploration
  - Carte nationale des arrêts GTFS
  - État des services
- Documentation
- Blog
- A propos
  - Nos missions
  - Normes
  - Loi climat et résilience
  - Déclaration de conformité

**Comment by AntoineAugusti** [comment]
@Benoit-MINT As-tu un avis ? Il me semble que l'onglet Réglementation peut être important à mettre en évidence.

**Comment by Benoit-MINT** [comment]
Oui, conservons l'onglet "Reglementation"

**Comment by cyrilmorin** [comment]
@AurelienC OK pour le fermer au vu de https://github.com/etalab/transport-site/issues/3914 ?

**Comment by AntoineAugusti** [comment]
Yep, il l'a indiqué ici 👌 https://github.com/etalab/transport-site/issues/3914#issuecomment-2182426273
