### ISSUE TITLE
Revue du contenu des notifications

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#3567]
Le PAN envoie des e-mails à des partenaires, particulièrement des producteurs/responsables de données actuellement.

Il faut que notre contenu soit clair, cohérent et actionnable.

## Contenu actuel

Le différent contenu des e-mails envoyés par le PAN est dans le dossier [`templates/email`](https://github.com/etalab/transport-site/tree/master/apps/transport/lib/transport_web/templates/email).

**Note** : je n'ai pas fait apparaitre les e-mails qui sont adressés à notre équipe uniquement.

Les sujets des e-mails correspondants 

|template|sujet|
|---|---|
|dataset_now_on_nap|Votre jeu de données a été référencé sur transport.data.gouv.fr|
|dataset_with_error_producer|Erreurs détectées dans le jeu de données #{dataset.custom_title}|
|dataset_with_error_reuser|Erreurs détectées dans le jeu de données #{dataset.custom_title}|
|datasets_switching_climate_resilience_bill|Loi climat et résilience : suivi des jeux de données|
|expiration_producer|Jeu de données arrivant à expiration|
|producer_with_subscriptions|Rappel : vos notifications pour vos données sur transport.data.gouv.fr|
|producer_without_subscriptions|Notifications pour vos données sur transport.data.gouv.fr|
|resource_unavailable_producer|Ressources indisponibles dans le jeu de données #{dataset.custom_title}|
|resource_unavailable_reuser|Ressources indisponibles dans le jeu de données #{dataset.custom_title}|

@etalab/transport-bizdev Pouvez-vous indiquer si des choses sont à modifier ? Vous pouvez faire vos retours sur ce ticket en indiquant le template et les changements à faire.

- https://github.com/etalab/transport-site/pull/3624 une bonne partie des templates
- à venir : `producer_with_subscriptions` et `producer_without_subscriptions`

**Comment by ChristinaLaumond** [comment]
Hello Antoine, voici nos propositions de modifications : 
https://www.notion.so/Gestion-des-notifications-externes-3e43125a9e6c41309fa72082c2008945 

Pour en rediscuter ! N'hésite pas si tu veux à ajouter une colonne dans le tableau de NOTION pour que tu puisses commenter. 

_NB : Je n'arrive pas à coller proprement le tableau depuis Notion donc je t'envoie le lien c'est plus simple.._

**Comment by AntoineAugusti** [comment]
@ChristinaLaumond J'ai ajouté une colonne sur le Notion avec quelques commentaires.

Je ferai les changements dans les semaines à venir

**Comment by AntoineAugusti** [comment]
@ChristinaLaumond Pour `dataset_with_error_reuser`, je ne comprends le changement que vous proposez.

Voici les modifications (avant/après)

```diff
- <%= if @producer_warned do %> Le producteur de ces données a été informé de ces erreurs. <% end %>
+ <%= if @producer_warned do %>
+   N’hésitez pas à contacter le producteur via le fil de discussion
+   du jeu de données (mettre le lien vers la création d’une nouvelle discussion du Jdd sur le PAN)
+ <% end %>
```

Cette notification étant adressée aux réutilisateurs, l'idée était d'informer que le producteur a déjà été informé par notification automatique de l'erreur. Pourquoi proposez-vous de remettre une couche en démarrant une nouvelle discussion ?

**Comment by AntoineAugusti** [comment]
La PR liée (#3624) traite plusieurs templates, il restera `producer_with_subscriptions` et `producer_without_subscriptions` à traiter dans une PR à venir.
