### ISSUE TITLE
Expiration de données : avoir un template pour les réutilisateurs

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#3568]
Dans `DataChecker` pour les notifications avec motif `:expiration` nous n'avons actuellement pas de template différencié entre producteurs et réutilisateurs.

Le code actuel sélectionne des e-mails pour les 2 rôles et envoie un template nommé "_producer".

https://github.com/etalab/transport-site/blob/0777938c8a3a99d862d53ef93ff58862b797999b/apps/transport/lib/transport/data_checker.ex#L170-L184

Il faudrait distinguer les 2 rôles et adapter le contenu en conséquence.

- [x] s'assurer qu'on envoie les notifications uniquement aux producteurs https://github.com/etalab/transport-site/pull/3569
- [x] ajouter un template dédié aux réutilisateurs https://github.com/etalab/transport-site/pull/3950

**Comment by AntoineAugusti** [comment]
@cyrilmorin Je te sollicite pour connaitre les délais à destination des réutilisateurs pour les jeux de données qu'ils suivent. Ils parait préférable d'avoir une liste de délais fixe que l'on applique à tout le monde, n'ayant pas de mécanisme permettant de personnaliser ceci pour le moment.

Voici les valeurs pour les producteurs pour le moment. Les valeurs négatives sont des rappels quand les données sont expirées.

https://github.com/etalab/transport-site/blob/5ded552dec0397e980b2620a998f56e2e6159462/apps/transport/lib/transport/data_checker.ex#L14-L15

**Comment by cyrilmorin** [comment]
@AntoineAugusti  OK je propose pour les réutilisateurs : @default_outdated_data_delays [-30, -7, 0, 7, 14]

**Comment by cyrilmorin** [comment]
Hello @AntoineAugusti,

Pour le contenu des mails, je propose :

Bonjour,

Voici un résumé de vos jeux de données favoris arrivant à expiration : 

Jeux de données périmant demain :
[Nom du jeu de données] avec lien vers le jeu de données   

Jeux de données périmant dans x jours / Jeux de données périmés depuis x jours : 
[Nom du jeu de données] avec lien vers le jeu de données 

Nous vous invitons à contacter les producteurs via la discussion du jeu de données si besoin.

Pour rappel, vous pouvez paramétrer vos alertes sur le suivi de vos jeux de données favoris depuis votre [espace réutilisateur ](https://transport.data.gouv.fr/espace_reutilisateur)

=> Reprendre les formules/signatures des autres mails à destinations des réutilisateurs)
