### ISSUE TITLE
Ajouter un score de conformité

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#3579]
Comme ce qui est fait pour le score de disponibilité et de fraicheur, ajouter un score de conformité qui indique si une ressource est valide ou non.

Ce qu'on a décidé avec @cyrilmorin :
- concerne les ressources qui sont actuellement validées
- ignore les ressources GTFS-RT
- pour GTFS ne s'intéresser qu'aux erreurs de type `Error` et `Fatal` (comme ce qui est fait pour la notification d'erreurs de validation)
- le score vaut 0 ou 1
- pour un JDD, faire la moyenne des scores des ressources prises en compte
- [déterminer une valeur d'alpha](https://docs.google.com/spreadsheets/d/1P2GYPr9pGIfe6VjmYJ5Owun2sD39EYjOxNGAgitIGcM/edit#gid=0) pour suivre la logique des autres scores (on prend en compte les scores passés)

**Comment by AntoineAugusti** [comment]
@cyrilmorin Une idée pour le nom en anglais ? On a availability et freshness pour les autres.

**Comment by cyrilmorin** [comment]
@AntoineAugusti compliancy ? conformity ?

**Comment by AntoineAugusti** [comment]
@cyrilmorin _Compliance_ me parait bien ! As-tu pu voir l'impact de la valeur alpha pour ce score ?

**Comment by cyrilmorin** [comment]
@AntoineAugusti yes j'ai pas mal joué avec surtout sur un temps un peu long (100 jours) plus proche de ce que l'on recherche finalement

Je propose 0.95 qui permet à la fois de pénaliser clairement mais de se souvenir du passé ce qui est important pour un "indice de confiance". Dispo pour échanger on fait un peu de la chimie là ;) on fera évoluer si besoin dans le futur

Voici quelques exemples avec plus ou moins d'indispo et plus ou moins anciennes (score moyen % représente le pourcentage brut de jour de dispo)

![image](https://github.com/etalab/transport-site/assets/116101828/55e25d91-fe25-4049-8381-618a92c418f0)

![image](https://github.com/etalab/transport-site/assets/116101828/2eb66d54-fc9b-441e-a233-edbaab7cd59b)

![image](https://github.com/etalab/transport-site/assets/116101828/8af03b01-6c63-468d-b5d9-a87c947c4f9a)
