### ISSUE TITLE
Documenter comment forcer une PR de hotfix sans risque

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#3611]
Pour merger:
- #3610 

étant seul, il a fallu modifier les réglages de protection de la branche master, et décocher ces deux cases "temporairement".

![CleanShot 2023-11-17 at 16 24 54@2x](https://github.com/etalab/transport-site/assets/10141/0e89147c-a39f-4a97-8e6d-4edc183ada60)

"Evidemment", il y avait plein de PR en attente qui se sont mises à s'auto-enqueuer :smile: et que j'ai annulé à la main.

Il serait bon qu'on note comment on fait "proprement" pour ne pas commettre d'impair.

Le besoin de passer des hotfix en solo va revenir, il faut être sûr que ça soit remis en bon état, ou que mieux, il n'y aie rien à modifier (sorte de "mode bypass" si ça existe quelque part).

**Comment by thbar** [comment]
À discuter @etalab/transport-tech

**Comment by AntoineAugusti** [comment]
Tu peux bypass les branch protection rules en cochant quelque chose à côté du bouton de merge, sans retirer ceci.

**Comment by AntoineAugusti** [comment]
![IMG_20231117_165054](https://github.com/etalab/transport-site/assets/295709/bf3b1e14-0949-431b-88dc-9adc485bd8fd)

**Comment by thbar** [comment]
Dooooh. Dans l'empressement je ne l'ai pas vu, alors que je m'en suis déjà servi plusieurs fois. Je crois que j'ai juste confondu avec un autre projet où je n'ai pas cette option en place 😄 merci !
