### ISSUE TITLE
[Export des ressources] Identifier ou supprimer les ressources communautaires de l'export

### ISSUE THREAD

**Issue by cyrilmorin** [etalab/transport-site#3618]
Hello,

Serait-il possible d'identifier dans l'export les ressources communautaires ?

Par exemple en ajoutant une colonne _type_ressource_ (après _titre_ressource_) avec choix : 
- statique
- temps-réel
- documentaire
- communautaire

Si c'est compliqué alors il faudrait les filtrer pour ne pas les exporter svp 

Merci :)

**Comment by AntoineAugusti** [comment]
@cyrilmorin Que préfères-tu comme solution ? C'est équivalent.

**Comment by cyrilmorin** [comment]
Cool alors ajout de la colonne "_type_ressource_" ça nous permettra entre autre d'identifier toutes les ressources communautaires (et de faire du ménage pour MyBus qui a des calendriers "2019") #mercilexportdesressources ;) 

Pour la liste, n'hésites pas à rajouter d'autres "type" que je n'aurai pas listés s'il en existe

Merci !
