### ISSUE TITLE
"function ExCoveralls.start/2 is undefined"

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#3619]
Je cherchais à vérifier la couverture des tests durant une review et je suis tombé là dessus.

@etalab/transport-tech est-ce que quelqu'un reproduit cette erreur ?

Ça pourrait être ou bien purement "temporaire" ou bien lié à une upgrade d'Elixir par exemple.

Commande:

```
MIX_ENV=test mix coveralls --umbrella
```

Résultat chez moi (je n'ai pu tester que sur une seule machine):

```
** (UndefinedFunctionError) function ExCoveralls.start/2 is undefined (module ExCoveralls is not available)
    (excoveralls 0.18.0) ExCoveralls.start("/Users/thbar/git/transport/transport-site/_build/test/lib/shared/ebin", [export: false, output: "cover", tool: ExCoveralls])
    (mix 1.15.5) lib/mix/tasks/test.ex:534: Mix.Tasks.Test.do_run/3
    (mix 1.15.5) lib/mix/task.ex:447: anonymous fn/3 in Mix.Task.run_task/5
    (mix 1.15.5) lib/mix/project.ex:458: Mix.Project.in_project/4
    (elixir 1.15.5) lib/file.ex:1624: File.cd!/2
    (mix 1.15.5) lib/mix/task.ex:604: anonymous fn/4 in Mix.Task.run_in_children_projects/2
    (elixir 1.15.5) lib/enum.ex:2510: Enum."-reduce/3-lists^foldl/2-0-"/3
    (mix 1.15.5) lib/mix/task.ex:603: Mix.Task.run_in_children_projects/2
```

**Comment by AntoineAugusti** [comment]
Même output chez moi

**Comment by thbar** [comment]
Introduit par la mise à jour d'`excoveralls` de 0.17.1 à 0.18.0 ici:
- https://github.com/etalab/transport-site/pull/3561

**Comment by thbar** [comment]
Je ferai un bugreport, pour l'instant je rollback à la main en local sans commiter, pour avoir la couverture dont j'ai besoin.

**Comment by thbar** [comment]
Plus subtile que ça! Ca dépend du type de rapport invoqué.

**Comment by AntoineAugusti** [comment]
@thbar As-tu plus d'éléments ? Sinon je vais [ouvrir un bug report](https://github.com/parroty/excoveralls/issues)

**Comment by thbar** [comment]
@AntoineAugusti je vais gérer !

**Comment by thbar** [comment]
@AntoineAugusti tu es bloqué sur un usage spécifique là ? Ou c'est juste pour que ça avance ?

**Comment by AntoineAugusti** [comment]
@thbar Non rien d'urgent, je regardais les tickets récents !

**Comment by thbar** [comment]
Ref:
- https://github.com/parroty/excoveralls/issues/321
