### ISSUE TITLE
Erreur 500 suite à modification url (avec changement d'Organization)

### ISSUE THREAD

**Issue by cyrilmorin** [etalab/transport-site#3642]
Hello,

Nous avons une erreur 500 sur le jeu de données [Réseau urbain Chamonix](https://transport.data.gouv.fr/datasets/gtfs-reseau-chamonix-mobilite)

La manip a probablement causé cette erreur car j'ai modifié depuis le BO l'url et que le dataset provient d'une autre Organisation (jeu précédemment référencé : [Chamonix bus](https://www.data.gouv.fr/fr/datasets/chamonix-bus-1/))

Je vous laisse investigué :)

Merci !

**Comment by AntoineAugusti** [comment]
@cyrilmorin Le problème vient du fait que le GTFS a le schéma `NaturalSolutions/schema-arbre` associé [sur la ressource](https://www.data.gouv.fr/fr/datasets/gtfs-reseau-chamonix-mobilite/). On ne peut avoir que des schémas "transport" sur le PAN.

Il est impossible de retirer un schéma depuis l'admin de data.gouv.fr (bug identifié) https://github.com/etalab/data.gouv.fr/issues/876, je demande donc à data.gouv.fr de le faire.

Une fois que ce sera fait un nouvel import corrigera le problème.

Voir erreur [sur Sentry](https://transport-data-gouv-fr.sentry.io/issues/4452809738/?environment=prod&project=6197733&query=is%3Aunresolved&referrer=issue-stream&stream_index=0)

**Comment by AntoineAugusti** [comment]
[Demande à datagouv](https://mattermost.incubateur.net/betagouv/pl/cdefi6ctbidu9nkyt1p3bbwbcw)
