### ISSUE TITLE
Ressource indispo indiquée comme dispo

### ISSUE THREAD

**Issue by ChristinaLaumond** [etalab/transport-site#3645]
Hello, 

Lorsque l'on veut télécharger le GTFS de ce [jdd ](https://transport.data.gouv.fr/datasets/arrets-horaires-et-parcours-theoriques-des-bus-du-reseau-des-transports-publics-envibus), on tombe sur : [lien](https://open-share.agglo-casa.fr/s/34FS2SWg36NEZk4/download)
<img width="775" alt="image" src="https://github.com/etalab/transport-site/assets/101095139/4e08d384-df08-4f68-b83f-1bd3182cdc2c">

Le GTFS en question n'est pas marqué comme étant indisponible, pour autant sa dispo (%) semble impactée depuis le 04/12
<img width="465" alt="image" src="https://github.com/etalab/transport-site/assets/101095139/3107cc43-da37-4eb8-b243-6e9622b49832">

**Comment by AntoineAugusti** [comment]
@ChristinaLaumond J'ai investigué ce problème et ce serveur Nextcloud semble avoir des problèmes.

On a détecté plusieurs fois de courtes indisponibilités.

![image](https://github.com/etalab/transport-site/assets/295709/56d5e625-624b-43a2-bf90-7f86d920fc1f)

On exécute bien une vérification automatique toutes les heures.

![image](https://github.com/etalab/transport-site/assets/295709/184a3c35-a56e-4c9e-9837-e3d8eb74ea5d)

En forçant une exécution de la vérification de la disponibilité à l'instant on détecte bien que la ressource est indisponible (tu peux vérifier en production actuellement).

![image](https://github.com/etalab/transport-site/assets/295709/058703ab-a80f-4be5-97e3-b7b651fff6cc)

La vérification s'effectuant 1 fois par heure, il est possible de rater de courtes indisponibilités.

**Comment by AntoineAugusti** [comment]
Ma conclusion serait que le système fonctionne de manière correcte actuellement.

À voir si on veut effectuer des vérifications de disponibilités plus fréquentes à l'avenir pour identifier plus de cas comme celui-ci. Les règles actuelles sont indiquées sur la page de ressource, section "Disponibilité au téléchargement", "En savoir plus".

@ChristinaLaumond je te laisse fermer ou proposer des modifications !

**Comment by ChristinaLaumond** [comment]
Merci pour l'investigation ! ça me va comme ça.
