### ISSUE TITLE
Migration du moissonneur ODS -> moissonneur DCAT (9 janvier 2024 :warning:)

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#3647]
Message de @maudetes (si je ne me trompe pas de handle GitHub):

================

La migration du moissonneur ODS au moissonneur DCAT est en train d'être prévue pour le 9 janvier 2024 prochain.
En appliquant la migration ODS, il va y avoir plusieurs impacts qui peuvent vous intéresser / concerner :

- toutes les URLs des ressources seront mises à jour
- les pièces jointes sont moissonnées de type other (plutôt que le défaut main)
- les ressources additionnelles sont moissonnées de la même manière que les autres exports ODS
- les filetype des ressources moissonnées seront tous remote
- les moissonneurs seront de type DCAT, donc tous les filtres (sur des mots clés, producteurs), seront des paramètres de l'URL directement
- voir [documentation ODS](https://userguide.opendatasoft.com/l/fr/article/vi2xzx1pno-se-faire-moissonner-par-data-gouv-fr), et côté data.gouv.fr, on va mettre à jour la doc avec ODS dans les [logiciels supportés avec moissonnage DCAT](https://guides.data.gouv.fr/publier-des-donnees/guide-data.gouv.fr/moissonnage/les-differents-types-de-moissonneurs#logiciels-supportes)
- les champs ods_* dans les métadonnées harvest seront donc supprimés
- les identifiants des remote_id dans les métadonnées d'un JDD seront mis à jour

Voici un exemple de fiches ([1](https://demo.data.gouv.fr/fr/datasets/angers-loire-metropole-reseau-irigo-gtfs-gtfs-rt-siri/)) et ([2](https://demo.data.gouv.fr/fr/datasets/base-adresse-locale-bal-communes-dangers-loire-metropole/)) après migration vs avant migration ([1](https://www.data.gouv.fr/fr/datasets/angers-loire-metropole-reseau-irigo-gtfs-gtfs-rt-siri/)) et ([2](https://www.data.gouv.fr/fr/datasets/base-adresse-locale-bal-communes-dangers-loire-metropole/)). J'ai fait tourné la migration sur 

Est-ce que c'est tout clair et tout bon pour vous ?

==============

**Comment by AntoineAugusti** [comment]
### Méthode suivie

J'ai regardé notre code source et fait des recherches sur des termes spécifiques à OpenDataSoft : ODS, OpenDataSoft, des numéros d'issues etc…

J'ai regardé les réponses d'API :
- [Ancien moissonnage pour Angers](https://www.data.gouv.fr/api/1/datasets/angers-loire-metropole-reseau-irigo-gtfs-gtfs-rt-siri/)
- [Nouveau moissonnage DCAT pour Angers](https://demo.data.gouv.fr/api/1/datasets/angers-loire-metropole-reseau-irigo-gtfs-gtfs-rt-siri/)

### Tâches identifiées

Les médailles indiquent le degré de criticité/impact.

- [ ] 🥇 **La détection d'une ressource ODS ne peut plus se faire par le fait que la ressource soit nommée `Export au format (JSON|CSV|GeoJSON)`.** En regardant [une réponse d'API nouvelle](https://demo.data.gouv.fr/api/1/datasets/angers-loire-metropole-reseau-irigo-gtfs-gtfs-rt-siri/) on devrait pouvoir utiliser `resources.harvest.uri` pour identifier ce cas.
- [ ] 🥉 **Adapter la logique pour savoir si on doit afficher la documentation d'une ressource.** [Logique actuelle](https://github.com/etalab/transport-site/blob/69c59b8fb711f45d98630a65d1121a7833a426ef/apps/transport/lib/transport_web/views/resource_view.ex#L277). C'est la même justification que le cas précédent. Peut-être qu'on peut abandonner cette distinction, maintenant que `resource.description` n'est plus aussi pollué qu'avant. Avant pour une ressource "Export au format CSV" la description était `- *description*: description[text]\n- *url*: url[text]\n` et maintenant c'est `null`. Cette tâche n'est pas prioriataire.

**Comment by AntoineAugusti** [comment]
@maudetes On avait [cette logique](https://github.com/etalab/transport-site/blob/69c59b8fb711f45d98630a65d1121a7833a426ef/apps/transport/lib/jobs/resource_unavailable_job.ex#L98-L104) chez nous pour résoudre l'URL finale.

L'URL finale est différente quand c'est une redirection, que le contenu n'est pas hébergé chez ODS. Par exemple avec https://twisto.opendatasoft.com/api/explore/v2.1/catalog/datasets/fichier-gtfs-du-reseau-twisto/alternative_exports/https_api_okina_fr_gateway_cae_realtime_anshar_ws_services

**Comment by AntoineAugusti** [comment]
Pour **🥈 Correction du bug lié au filetype**, [ODS a indiqué](https://app.frontapp.com/open/msg_23x6vtna?key=CTubsq3nwlvBDBimzRKUq4ngpsBPb80x) que le correctif a été effectué sur l'export DCAT, on a bien l'URL finale indiquée par le producteur et plus une redirection ODS -> URL finale.

On devrait donc pouvoir supprimer le commentaire et laisser la logique de "follow" uniquement pour `filetype = file` et ne pas être impacté par le correctif sur `filetype = remote` pour cette partie.

**Comment by maudetes** [comment]
Thanks @AntoineAugusti
J'ai mis à jour le script de migration pour utiliser l'URL finale si détectée : https://github.com/opendatateam/udata-ods/pull/247/commits/bb43adb52736574f9d8eb98a113e86cc7cdcf331.
Quand je check les resources concernées par une URL finale hors ODS, j'ai seulement les 9 suivantes sur la prod, ça vous paraît crédible ?

<details><summary>Ressources avec URL finale hors ODS</summary>

URL ODS | URL finale
-- | --
http://data.laregion.fr/api/datasets/1.0/reseau-lio/alternative_exports/https_app_mecatran_com_utw_ws_gtfsfeed_static_lio_apikey_2b160d626f783808095373766f18714901325e45 | https://app.mecatran.com/utw/ws/gtfsfeed/static/lio?apiKey=2b160d626f783808095373766f18714901325e45&type=gtfs_lio
https://twisto.opendatasoft.com/api/datasets/1.0/fichier-gtfs-du-reseau-twisto/alternative_exports/https_api_okina_fr_gateway_cae_realtime_anshar_ws_services | https://api.okina.fr/gateway/cae/realtime/anshar/ws/services
https://opendata.bordeaux-metropole.fr/api/datasets/1.0/offres-de-services-bus-tramway-gtfs/alternative_exports/https_bdx_mecatran_com_utw_ws_gtfsfeed_static_bordeaux_apikey_opendata_bordeaux_metropole_flux_gtf | https://bdx.mecatran.com/utw/ws/gtfsfeed/static/bordeaux?apiKey=opendata-bordeaux-metropole-flux-gtfs-rt
https://opendata.bordeaux-metropole.fr/api/datasets/1.0/offres-de-services-bus-tramway-gtfs/alternative_exports/https_bdx_mecatran_com_utw_ws_gtfsfeed_realtime_bordeaux_apikey_opendata_bordeaux_metropole_flux_g | https://bdx.mecatran.com/utw/ws/gtfsfeed/realtime/bordeaux?apiKey=opendata-bordeaux-metropole-flux-gtfs-rt
https://opendata.bordeaux-metropole.fr/api/datasets/1.0/offres-de-services-bus-tramway-gtfs/alternative_exports/https_bdx_mecatran_com_utw_ws_gtfsfeed_vehicles_bordeaux_apikey_opendata_bordeaux_metropole_flux_g | https://bdx.mecatran.com/utw/ws/gtfsfeed/vehicles/bordeaux?apiKey=opendata-bordeaux-metropole-flux-gtfs-rt
https://opendata.bordeaux-metropole.fr/api/datasets/1.0/offres-de-services-bus-tramway-gtfs/alternative_exports/https_bdx_mecatran_com_utw_ws_gtfsfeed_alerts_bordeaux_apikey_opendata_bordeaux_metropole_flux_gtf | https://bdx.mecatran.com/utw/ws/gtfsfeed/alerts/bordeaux?apiKey=opendata-bordeaux-metropole-flux-gtfs-rt
https://data.economie.gouv.fr/api/datasets/1.0/rappelconso0/alternative_exports/https_rappel_conso_gouv_fr_api_export | https://rappel.conso.gouv.fr/api/export
https://data.loire-atlantique.fr/api/datasets/1.0/224400028_marches-publics-du-departement-de-loire-atlantique/alternative_exports/https_marches_loire_atlantique_fr_app_php_api_v1_donnees_essentielles_contrat_xml_extraire_critere | https://marches.loire-atlantique.fr/app.php/api/v1/donnees-essentielles/contrat/xml-extraire-criteres/t5y/0/1/2023/false/false/false/false/false/false/false/false/false
http://breizh.opendatasoft.com/api/datasets/1.0/base-de-donnees-multimodale-transports-publics-en-bretagne-mobibreizh/alternative_exports/https_www_korrigo_bzh_ftp_opendata_korrigobret_gtfs_zip | https://www.korrigo.bzh/ftp/OPENDATA/KORRIGOBRET.gtfs.zip

</details>

**Comment by AntoineAugusti** [comment]
@maudetes Ça me parait bien crédible ! Nous n'avons pas encore fait de campagne demandant à changer la méthode de publication avec @etalab/transport-bizdev. Pour la partie PAN j'avais bien en tête Bordeaux et Twisto.

Du coup avec le script de migration qui sera appliqué sur data.gouv.fr les ressources data.gouv.fr seront modifiées et ne seront pas de nouveau créées ? Elles conserveront bien le même `datagouv_id` ? On se demandait si on doit faire des opérations de migration pour nos ressources (ou adapter notre logique de matching en fonction de l'URL) afin de pas supprimer/recréer des ressources pour rien.

**Comment by maudetes** [comment]
Oui, l'idée c'est de bien garder tous les identifiants stables lors de la migration pour les JDDs et les ressources (d'où la migration des URLs, qui nous servent d'identifiants de ressource lors du moissonnage d'une fois sur l'autre). Il ne devrait pas y avoir de doublon :crossed_fingers: ou de création/suppression de ressources avec la migration.

**Comment by AntoineAugusti** [comment]
@maudetes Super, ça nous arrange bien ! @vdegove, je pense qu'il n'y aura donc rien à faire pour la tâche **🥇 Gérer le changement des URLs des ressources ODS.** car on cherche à retrouver une ressource existante chez nous avec son `datagouv_id` déjà (dans `Transport.ImportData.get_existing_resource`).

**Comment by AntoineAugusti** [comment]
@maudetes Est-il envisageable de déployer la nouvelle version du moissonneur ODS sur une organisation spécifique en production (je dirais [Twisto](https://www.data.gouv.fr/fr/organizations/twisto/)) afin de vérifier le bon fonctionnement ?

**Comment by AntoineAugusti** [comment]
PRs mergées en prod aujourd'hui suite au déploiement de la nouvelle version du moissonneur côté data.gouv.fr !
