### ISSUE TITLE
Ajustement quota ou périmètre rate limiter

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#3677]
Constat : notre application se fait ban elle-même en requêtant des flux GTFS-RT sur la carte des vehicle positions.

[Voir Mattermost](https://mattermost.incubateur.net/betagouv/pl/ofurauayopbxjkfmxcpyjd4iqa)

## Code pertinent

Le plug de rate limiting est déclaré dans `TransportWeb.Endpoint` actuellement

https://github.com/etalab/transport-site/blob/c16d891b74ed7de53cd2ea1c04cef64cf8965637/apps/transport/lib/transport_web/endpoint.ex#L43

en conséquence ceci est appliqué à toutes les applications : web, gbfs et proxy GTFS-RT.

À noter que le routing vers `Unlock` en charge du proxy GTFS-RT est ici 

https://github.com/etalab/transport-site/blob/c16d891b74ed7de53cd2ea1c04cef64cf8965637/apps/transport/lib/transport_web/plugs/router.ex#L14

### Paramètres du rate limiting

Les [paramètres du rate limiting](https://transport.data.gouv.fr/backoffice/rate_limiter) actuellement sont `PHOENIX_DDOS_MAX_2MIN_REQUESTS = 200` ce qui donne un max de 200 requêtes HTTP par période de 2 minutes par IP.

Ceci est assez faible, en particulier en requêtant du GTFS-RT. On a actuellement ~50 flux disponibles, en requêtant toutes les 10s avec la même adresse IP on arrive à 600 requêtes en 2 minutes ce qui engendre un ban.

## Questions

Faut-il :
- simplement augmenter le quota ? à combien ?
- retirer le rate liming pour le proxy GTFS-RT ?

**Comment by thbar** [comment]
Je remets à peu près ce qu'on s'est dit sur Mattermost.

> notre application se fait ban elle-même en requêtant des flux GTFS-RT sur la carte des vehicle positions.

Tout à fait, et il est intéressant de remarquer qu'on est en fait sur un usage assez "basique" qui correspond à ce que ferait un réutilisateur un peu lambda qui consommerait du GTFS-RT.

Vu les limitations actuelles du GTFS-RT (système de polling, pas de push disponible), si on est intéressé par N flux, on doit poller régulièrement (typiquement toutes les 10, 20, 30 secondes, et je ne considère pas 10 secondes comme abusif pour le coup).

Quand N est égal à la totalité des flux du PAN, on se retrouve à avoir N requêtes toutes les 10 secondes, et ça ne me paraît pas abusif, plutôt assez normal pour des données temps réel.

> en conséquence ceci est appliqué à toutes les applications : web, gbfs et proxy GTFS-RT.
> retirer le rate liming pour le proxy GTFS-RT ?

À ce stade le rate-limiting a été mis en place pour des questions de crawling sur les pages web, mais il n'y avait pas de besoin sur la partie proxy du tout, et le proxy tiendra bien la charge x 10 ou plus sans trop de soucis.

Donc je suis clairement pour retirer le rate-limiting de la partie proxy au complet (GBFS, proxy unlock etc).

Et probablement aussi pour la partie API à mon avis (qui bénéficie déjà de cache sur certaines parties par ailleurs).

Comme ça on "protège" uniquement contre le risque qui a été avéré (le crawler un peu trop zélé), sans polluer les réutilisateurs en surprotégeant.

Comment ? On doit pouvoir s'en tirer en précisant les chemins à "skip" en terme de rate limiting, quitte à wrapper le plug dans un autre plug qui prend en paramètre un module et une fonction.

**Comment by thbar** [comment]
Poke @AntoineAugusti dis-moi ce que tu en penses, je peux peut-être prendre en charge cette partie run à un moment ? Comme tu le sens.

**Comment by AntoineAugusti** [comment]
@thbar Très bien, je te laisse gérer ceci à ta convenance ! Ce que tu proposes me parait bien. À voir si on simplement retirer la logique de rate limiting jail ou également ce qui est en charge de logger des requêtes/user-agent.

Le code pertinent est dans `TransportWeb.Plugs.RateLimiter`.

**Comment by AntoineAugusti** [comment]
On a changé les quotas à l'instant :
- 2 minutes : 1 500
- 1h : 100 000

**Comment by AntoineAugusti** [comment]
On a vu cette issue revenir pour la partie proxy. Je vais traiter cette issue et appliquer le plug uniquement à la partie web et traiter ce qu'on avait identifié auparavant.

> Donc je suis clairement pour retirer le rate-limiting de la partie proxy au complet (GBFS, proxy unlock etc).
