### ISSUE TITLE
Nettoyer fichiers statiques non utilisés

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#3697]
Plusieurs fichiers statiques ne sont plus utilisés, il faudrait les supprimer.

Au moins :
- BingSiteAuth.xml
- google5be4b09db1274976.html
- demo_rt.html

**Comment by thbar** [comment]
Pour

> google5be4b09db1274976.html

ce n'est plus utilisé non plus pour authentifier le site en accès sur la console d'indexation google ?

**Comment by AntoineAugusti** [comment]
> ce n'est plus utilisé non plus pour authentifier le site en accès sur la console d'indexation google ?

C'est fait en DNS désormais https://github.com/etalab/transport-deploy/blob/39f6e40eec10177d0584cb7612e939be30871e27/dns/transport.data.gouv.fr.zone#L9

**Comment by thbar** [comment]
> > ce n'est plus utilisé non plus pour authentifier le site en accès sur la console d'indexation google ?
> 
> C'est fait en DNS désormais https://github.com/etalab/transport-deploy/blob/39f6e40eec10177d0584cb7612e939be30871e27/dns/transport.data.gouv.fr.zone#L9

Ok super, merci pour la précision !
