### ISSUE TITLE
Non détection d'un GTFS-Flex 

### ISSUE THREAD

**Issue by cyrilmorin** [etalab/transport-site#3704]
Le jeu de données [TAO Orléans Flex](https://transport.data.gouv.fr/datasets/description-de-loffre-tad-tao-gtfs-flex-orleans-metropole
) ne semble plus être détecté comme du Flex et présente donc une erreur de validation
![image](https://github.com/etalab/transport-site/assets/116101828/9d5ab3ac-4595-4d96-8b11-778654b3dd24)

En vérifiant très rapidement il y a pourtant bien les attributs du flex dans l'archive 
![image](https://github.com/etalab/transport-site/assets/116101828/db929828-f895-496e-a9f7-716734e406f4) 

Pour rappel cf issue [3058](https://github.com/etalab/transport-site/issues/3058)

**Comment by AntoineAugusti** [comment]
Hello,

En regardant, les fichiers sont contenus dans un dossier ce qui est invalide d'après la spec GTFS et empêche la détection du GTFS Flex.

Voir [retour de notre API](https://transport.data.gouv.fr/api/datasets/6569252ddf850d55eca3e3d9) qui indique

```json
"filenames": [
  "GTFS_FLEX_stopsUpdated/agency.txt",
  "GTFS_FLEX_stopsUpdated/booking_rules.txt",
  "GTFS_FLEX_stopsUpdated/calendar.txt",
  "GTFS_FLEX_stopsUpdated/calendar_dates.txt",
  "GTFS_FLEX_stopsUpdated/ds_store",
  "GTFS_FLEX_stopsUpdated/feed_info.txt",
  "GTFS_FLEX_stopsUpdated/location_groups.txt",
  "GTFS_FLEX_stopsUpdated/locations.geojson",
  "GTFS_FLEX_stopsUpdated/routes.txt",
  "GTFS_FLEX_stopsUpdated/stop_times.txt",
  "GTFS_FLEX_stopsUpdated/stops.txt",
  "GTFS_FLEX_stopsUpdated/trips.txt"
]
```

**Comment by cyrilmorin** [comment]
merci @AntoineAugusti trop bizarre, je n'ai pas vu ça hier ... mais j'ai dû ouvrir trop rapidement le dossier et le sous dossier !

Pas de bug donc ... je ferme
