### ISSUE TITLE
Nombre de ressources différent du nombre listé

### ISSUE THREAD

**Issue by AurelienC** [etalab/transport-site#3705]
Sur l'affichage d'un jeu de données, le nombre de ressources affichées dans la colonne de gauche diffère du nombre de ressources affichées dans la page.

### Exemple
Avec la [Base nationale consolidée des lieux de covoiturage
](https://transport.data.gouv.fr/datasets/base-nationale-des-lieux-de-covoiturage#dataset-resources)

2 ressources affichées dans la liste mais 3 dans le décompte :
![image](https://github.com/etalab/transport-site/assets/4528670/d68b57d2-de3b-4409-96f8-0d8bc6e80f9b)

Les 3 ressources visibles dans le backoffice :
![image](https://github.com/etalab/transport-site/assets/4528670/ddd1b31b-6a20-4917-82e8-6c9f00e618fc)

Dont une est une ressource communautaire :
![image](https://github.com/etalab/transport-site/assets/4528670/397bd403-02fb-4044-91ba-64debeff22df)

### Comportement attendu
Le nombre affiché de ressources dans la colonne de gauche correspond au nombre de ressources affichées à l'utilisateur

**Comment by AntoineAugusti** [comment]
Le compteur avait été ajouté dans https://github.com/etalab/transport-site/pull/1693 et le menu "Ressources communautaires" dans https://github.com/etalab/transport-site/pull/2564 mais on n'avait pas ajusté le compteur à ce moment.

Bien vu 🐛
