### ISSUE TITLE
CI cassé ?

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#3714]
Un peu de mal à merger:
- https://github.com/etalab/transport-site/pull/3703

et il me semble avoir vu le même souci sur une autre PR (mais je ne suis pas sûr à 100%)

Je vois:

<img width="873" alt="CleanShot 2024-01-10 at 14 11 40@2x" src="https://github.com/etalab/transport-site/assets/10141/730ab4fb-3ab4-4afb-b74d-c6bf02da2bf9">

**Comment by AntoineAugusti** [comment]
Vu [sur Mattermost](https://mattermost.incubateur.net/betagouv/pl/n6f1yggs4t8jpdfmec1hsudbrh), c'était expliqué par un message `skip ci` dans un commit.

Discussion pertinente https://github.com/orgs/community/discussions/15925
