### ISSUE TITLE
Ajout encart pour le questionnaire utilisateur sur l'évolution du moteur de recherche

### ISSUE THREAD

**Issue by AurelienC** [etalab/transport-site#3719]
En lien avec #3640 

### Demande
Ajout d'un encart temporaire sur la page d'accueil et la page de résultat des recherches (`https://transport.data.gouv.fr/datasets`)

### Texte

> Le moteur de recherche va évoluer ! Participez à son évolution en répondant à notre [questionnaire en ligne](https://framaforms.org/nouveau-moteur-de-recherche-du-pan-1705056765) pour nous détailler vos attentes (réponse possible jusqu'au 15/02/2024).

### Page d'accueil
L'encart pourrait être en haut de la page ou au-dessous du champ de recherche
![image](https://github.com/etalab/transport-site/assets/4528670/c9855f0b-e58a-4d15-b7a5-7bafe16036e8)

### Page résultats de recherche
Encart au-dessus du champ de recherche
![image](https://github.com/etalab/transport-site/assets/4528670/fb894546-45e7-4d76-a28a-b295e9de27dd)

**Comment by thbar** [comment]
Message qui était précédemment en place, pour qu'on puisse éventuellement le remettre après:

✉️ Producteurs, [activez des notifications](https://doc.transport.data.gouv.fr/administration-des-donnees/procedures-de-publication/gerer-la-qualite-des-donnees#sinscrire-aux-notifications) pour améliorer la gestion de vos données.

**Comment by thbar** [comment]
@AurelienC j'ai opté pour une reconfiguration de la "breaking news" (ça se fait via le back-office).

<img width="1259" alt="CleanShot 2024-01-22 at 18 23 52@2x" src="https://github.com/etalab/transport-site/assets/10141/cac09ad6-86ab-4034-bd14-6052469f160a">

Qu'est-ce qu'on prévoit pour pousser ça dehors davantage ?

J'ai pensé à :
- [ ] Prochaine newsletter ? (mais quand ?)
- [ ] Publication(s) twitter ? LinkedIn ?
- [ ] Envoi spécifique à notre base email si pas de NL ?

**Comment by AntoineAugusti** [comment]
On devrait pouvoir fermer ce ticket il me semble ? Peut-être retirer le bandeau aussi 😅

**Comment by thbar** [comment]
J'ai déjà dans l'immédiat retiré la date limite du bandeau, on se voit avec Aurélien début de semaine prochaine. Merci !

**Comment by thbar** [comment]
On a supprimé le bandeau !
