### ISSUE TITLE
Arrêts perdus dans la conversion GTFS -> NeTEx

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#3732]
Je reprends ce retour de @jthiard pour ne pas perdre l'info en bas de l'issue suivante:
- https://github.com/etalab/transport-site/issues/3427

### Auto-suggestion de tâches

Juste une idée vite fait, chacun dans @etalab/transport-tech peut changer ça !

- [x] Je serais tenté d'aller voir dans la donnée pour apprendre à comparer ça de plus près (constater par nous-même)
- [x] Remonter le souci à EnRoute

### Retour

Bonjour,
je travaille avec JungleBus sur les outils de collecte de donnée d'Accessibilité (société Someware).
Je ne sais pas si ce point a été remonté à enRoute, mais il arrive que la conversion NeTEx ait beaucoup moins d'arrêts que le GTFS.

Ex: Réseau STAR de Rennes Métropole : https://transport.data.gouv.fr/datasets/versions-des-horaires-theoriques-des-lignes-de-bus-et-de-metro-du-reseau-star-au-format-gtfs

- Dans le GTFS tous les arrêts bus / métro sont présents.
- Dans le NeTEx seuls les arrêts de métro sont présents.

**Comment by jthiard** [comment]
Merci @thbar pour le suivi !

**Comment by AntoineAugusti** [comment]
Je reproduis bien le problème en local et je ne vois pas de problème apparent sur les données GTFS, notre validateur GTFS ne remonte pas d'erreurs non plus.

Je viens de [créer un ticket](https://enroute.atlassian.net/servicedesk/customer/portal/1/SUPPORT-1161?created=true) chez EnRoute.

---

Bonjour,

Un réutilisateur [nous a remonté](https://github.com/etalab/transport-site/issues/3732) avoir constaté des arrêts manquants dans une conversion GTFS vers NeTEx. Ceci concerne [le réseau STAR de Rennes](https://transport.data.gouv.fr/datasets/versions-des-horaires-theoriques-des-lignes-de-bus-et-de-metro-du-reseau-star-au-format-gtfs).

Je constate que la conversion NeTEx réalisée comporte uniquement les arrêts des lignes de métro dans le fichier STOP.xml. Les arrêts de bus sont absents de ce fichier mais les fichiers des lignes sont bien créés. Il me semble que ces arrêts sont bien dans ce cas :

> For each GTFS Stops (location_type = 0) without a GTFS Parent Station, Chouette Convert a NeTEx StopPlace with the following information:

Auriez-vous une explication de ce comportement ou est-ce un bug ?

Bonne journée

**Comment by AntoineAugusti** [comment]
EnRoute indique

> Le comportement paraît en effet étrange. Nous ouvrons un ticket en interne pour analyser/corriger la chose.

**Comment by AntoineAugusti** [comment]
EnRoute indique

> Le soucis est confirmé. Nous travaillons sur une correction qui sera déployée en production au plus vite.

**Comment by AntoineAugusti** [comment]
EnRoute indique

---

La version de Chouette Convert (build 170) intégrant le correctif à cette anomalie vient d'être déployée en production.

Le fichier GTFS converti utilisant des "" dans stops.txt/parent_station, cela mettait à mal un test (nil vs blank ......) important lors de la création des ressources NeTEx Quay / Stop Place :-/

Nous sommes en train de mettre en place de nouveaux outils de QA pour être plus proactif sur ce genre d'anomalies.

**Comment by AntoineAugusti** [comment]
Je viens de lancer une conversion GTFS vers NeTEx pour tous les jeux de données pour profiter de ce patch. Ceci prendra quelques dizaines de minutes.

```iex
iex> DB.Dataset.base_query() |> where([dataset: d], d.type == "public-transit") |> select([dataset: d], d.id) |> DB.Repo.all() |> Enum.each(&DB.DataConversion.force_refresh_netex_conversions/1)
```

**Comment by AntoineAugusti** [comment]
Les conversions sont terminées. La conversion [du réseau STAR](https://transport.data.gouv.fr/datasets/versions-des-horaires-theoriques-des-lignes-de-bus-et-de-metro-du-reseau-star-au-format-gtfs) comprend désormais les arrêts attendus.

Merci @jthiard pour le report de bug 🙏 Merci @thbar pour le suivi sur le problème 🙏

**Comment by jthiard** [comment]
Top merci @AntoineAugusti et enRoute.

**Comment by thbar** [comment]
Merci @AntoineAugusti pour la gestion !
