### ISSUE TITLE
Espace Producteur : améliorer page gestion des notifications

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#3754]
Améliorer [la page](https://transport.data.gouv.fr/espace_producteur/notifications) permettant de gérer les notifications.

Améliorations envisagées :
- indiquer les collègues recevant les notifications pour les JDDs de la même organisation (quand la personne connectée est inscrite ou pas)
- revoir le texte sur la page

**Comment by vdegove** [comment]
Quel est l’objectif derrière l’amélioration du texte sur la page @AntoineAugusti ? Juste faire un peu de pédagogie et reprendre une explication plus complète inspirée de la FAQ ? @AurelienC as-tu des requêtes particulières à ce sujet ?

**Comment by AntoineAugusti** [comment]
@vdegove Oui, j'avais envisagé ça. Je trouve la page un peu vide/légère pour le moment, c'était donc une suggestion. Sans pour autant savoir quoi faire exactement.

Si vous jugez ceci comme suffisant pas de problème !
