### ISSUE TITLE
Factures hébergement en attente (devraient être auto-prélevées)

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#3763]
Vu avec Boris, on doit être en prélèvement auto sur la CB, or, j'ai vu ceci aujourd'hui:

<img width="651" alt="CleanShot 2024-02-01 at 13 54 11@2x" src="https://github.com/etalab/transport-site/assets/10141/8a1bceb7-8c86-4ef0-bd4c-379933f15cb9">

Je vais ouvrir un ticket chez CC pour vérifier si c'est temporaire et pas un souci, ou un bug qui peut poser problème.

**Comment by AntoineAugusti** [comment]
Pas de problème tada 🥳 

---

> A priori tout est en ordre
> La facture du 02/01 vient d'être édité, donc la tentative de paiement n'a pas encore eu lieu
> LA dernière tentative de paiement se fait le 25 du mois, c'est la date d'émission de l'autre facture, elles sont donc tombé toutes les 2 entre des tentatives de paiement, la prochaine est le 5, le paiement automatique devrait les régler d'un coup

**Comment by thbar** [comment]
La personne du support CleverCloud a trouvé étrange tout de même. C'est peut-être lié (mon hypothèse) à l'introduction d'un add-on à 120€ et des histoires de dates de chevauchement oui.

Je leur ai remonté quand même que ça fait un warning sur le site qui fait qu'on se pose la question pour rien du coup, peut-être qu'ils prendront ça en compte pour améliorer leur produit !

Mais oui on est bon, pas de souci opérationnel du coup.

**Comment by thbar** [comment]
Et l'explication finale est qu'il y avait bien un souci, effectivement en lien avec l'edge-case. Ils vont intégrer ça. En tout cas pas de souci opérationnel pour nous sur ce tour.

> Oui le warning peut faire peur en effet, vous êtes juste dans un edge case avec une facture supplémentaire suite a un setup custom qui est tombé après la dernière vague de paiement du mois dernier
> Je vais faire remonter le point à l'équipe front pour voir comment nous pourrions ajuster cela :wink:
