### ISSUE TITLE
Logo - Fond blanc sur image redimensionnée

### ISSUE THREAD

**Issue by cyrilmorin** [etalab/transport-site#3768]
Hello,

Lorsque les user changent leur logo on a actuellement un fond noir lorsque le logo ne correspond pas totalement à la taille attendue (logo rectangulaire par exemple)
Serait-il possible de ne pas afficher le fond noir et proposer un fond blanc qui correspond à la charte graphique du site ?
Exemple avec [Fluo](https://transport.data.gouv.fr/datasets?q=fluo&page=2) et les logos transformés (avec bords noirs)
![image](https://github.com/etalab/transport-site/assets/116101828/dc0e0f3e-f186-465f-a675-d0a00b61ee5f)

Merci !

**Comment by AntoineAugusti** [comment]
Je pensais que https://github.com/etalab/transport-site/blob/334649e18a7241fb33ae05e28cef0bcf8bf93d86/scripts/custom_logo.exs#L20 était suffisant mais non, je vais regarder. Merci !

**Comment by AntoineAugusti** [comment]
J'ai corrigé pour les logos de la région Grand Est. C'est corrigé dans le script de génération d'images pour les logos à venir.

C'est visible dès à présent en navigation privée. Si tu as déjà vu les logos le cache est d'une durée d'une semaine donc tu pourrais voir l'ancienne version sans refresh.

N'hésite pas à m'indiquer si tu vois d'autres logos avec un fond noir et je corrigerai !

Merci :pray:
