### ISSUE TITLE
Remise en question du warning Credo "Pipe chain should start with a raw value"

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#3773]
Ce warning m'embête régulièrement, dans le sens où j'ai l'impression de tordre le code "pour faire plaisir à Credo":

https://github.com/etalab/transport-site/blob/04976c9de139b8c7148909088eee97e8d2a154af/scripts/irve/req_custom_cache.exs#L41-L54

En particulier celui-ci:

```elixir
:crypto.hash(:sha256, :erlang.term_to_binary(request.url))
|> Base.encode16(case: :lower)
```

**Comment by thbar** [comment]
Votre avis @etalab/transport-tech - êtes-vous OK pour muter ce warning spécifique, ou le trouvez-vous intéressant ?

**Comment by AntoineAugusti** [comment]
Oui, il y a quelques cas qui ne me paraissent pas naturels. Genre `:transport |> Application.fetch_env!(:foo) |> String.trim()`

**Comment by thbar** [comment]
Traité ici: https://github.com/etalab/transport-site/pull/3772/files#diff-c44b474280f99dde56e6b80c90554ced12592de34aaa8d42186984126d5521d9L104
