### ISSUE TITLE
Erreur 500 sur le dataset Gap-Durance

### ISSUE THREAD

**Issue by cyrilmorin** [etalab/transport-site#3776]
Hello,

Erreur 500 sur le dataset [Gap ](https://transport.data.gouv.fr/datasets/horaires-theoriques-et-temps-reels-du-reseau-de-transports-lagglo-en-bus-communaute-dagglomeration-gap-tallard-durance)
Pour info, j'ai cliqué sur "Valider" puis "Importer" via le BO suite à la mise à jour dont le producteur m'a informé mais que je ne voyais pas de notre côté (ressource GTFS-RT ajoutée)

Merci :)

**Comment by AntoineAugusti** [comment]
C'était un problème de détection de format. Le GTFS avait un format `zip` ce qui normalement suffit à bien détecter mais l'URL de la ressource avait `gtfs-rt` dedans.

![image](https://github.com/etalab/transport-site/assets/295709/83125a5b-7aa3-476a-adb7-ac4e5cbca8cf)

Avoir un format plus explicite sur data.gouv.fr permet d'éviter le problème.
