### ISSUE TITLE
Cap Cotentin Lier ressources GTFS-Rt avec GTFS

### ISSUE THREAD

**Issue by cyrilmorin** [etalab/transport-site#3783]
Hello,

Pour le dataset [Cap Cotentin](https://transport.data.gouv.fr/datasets/horaires-theoriques-et-en-temps-reel-des-bus-et-autocars-circulant-sur-le-reseau-cap-cotentin)
Lier la ressource GTFS-RT 79830 à la ressource GTFS 79831

Merci !

**Comment by AntoineAugusti** [comment]
Fait ✅
