### ISSUE TITLE
Indicateurs disponibilité à 0 pour datasets sans ressource ?

### ISSUE THREAD

**Issue by cyrilmorin** [etalab/transport-site#3786]
Hello,

Dans le dataset de [Toulouse ](https://transport.data.gouv.fr/datasets/tisseo-offre-de-transport-gtfs) qui provient d'un moissonage depuis open data, la ressource propose un csv vers le lien de téléchargement (à modifier en amont si possible)

Ceci étant dit, on s'est retrouvé avec un dataset sans ressource affichée sur la PAN mais dont la disponibilité n'était pas impactée.

J'ai modifier pour tester le format (csv -> GTFS) ce 28/02/2024 mais vu que la donnée est moissonnée, le format csv reviendra dès demain à mon avis.

La question qui se pose est que l'indicateur de disponibilité n'a pas été impacté.
A-t-on prévu de le mettre à 0 si aucune ressource n'est proposée (affichée sur le PAN) ? Si oui y a-t-il une autre explication ?

Merci !!

**Comment by cyrilmorin** [comment]
Merci pour ton retour.

A partir du moment où on a un dataset référencé sans aucune ressource, ça me semble une bonne option de considéré le dataset comme indisponible et pénaliser le score. Je ne vois pas à 1ère vue d'effet de bord là-dessus. Si tu envoies n'hésites pas !

Merci @AntoineAugusti

**Comment by AntoineAugusti** [comment]
Je viens d'ouvrir une PR avec un correctif pour ce cas 👌 

J'ai vérifié,

```sql
select d.custom_title, count(r.id)
from dataset d
join resource r on r.dataset_id = d.id and r.type != 'documentation'
where d.is_active
group by 1
```

il n'y a pas d'autres JDD avec 0 ressources ou uniquement de la documentation.
