### ISSUE TITLE
Détails des ressources : Ajouter le nombre de lignes

### ISSUE THREAD

**Issue by cyrilmorin** [etalab/transport-site#3788]
Hello, 

En voyant notre super récap des données comprises dans le GTFS (#3739) c'est obvious que le nombre de lignes manque à l'appel !

1- Traduire "stops" par "arrêts"
2- Rajouter entre mode de transport et nombre de stops ?
![image](https://github.com/etalab/transport-site/assets/116101828/c45c05be-b26d-41e5-9816-d08a5efa57e7)

Merci !!!

**Comment by AntoineAugusti** [comment]
@cyrilmorin On laisse le jargon stop points/stop areas ou pas ?

**Comment by cyrilmorin** [comment]
@AntoineAugusti ouais c'est bof t'as raison => on dégage !
merci
