### ISSUE TITLE
Paris 2024 - Publication des données mobilités liées aux JO 

### ISSUE THREAD

**Issue by cyrilmorin** [etalab/transport-site#3790]
Comme vu ensemble nous allons référencer les JDD (même hors standard) sur le PAN pour participer  à la mise en avant des données disponibles liées à la mobilité sur l'événement :

1- Ajouter une brique Paris JO 2024 dans les catégories de transport
2- La brique contiendra les datasets avec le tag Paris2024

Je transmettrai l'info aux admin de l'organisation [Paris 2024](https://www.data.gouv.fr/fr/organizations/paris-2024/) pour valider leur accord sur le sujet

Merci !

**Comment by AntoineAugusti** [comment]
@cyrilmorin On a des logos pour chaque brique, quel logo devons-nous utiliser pour ceci ? On utilise du noir et blanc d'habitude

**Comment by cyrilmorin** [comment]
on pourrait mettre au choix et toujours en noir et blanc les anneaux olympiques ou la flamme olympique ?

**Comment by AntoineAugusti** [comment]
@cyrilmorin D'acc 👌 Pourrais-tu proposer des textes en FR et EN pour cette catégorie ? C'est affiché sur la page listant les JDD

**Comment by cyrilmorin** [comment]
@AntoineAugusti : 2 propositions, n'hésites pas à corriger et/ou modifier si besoin :

FR : Les jeux de données référencés dans cette catégorie contiennent des jeux de données publiés sur data.gouv.fr et contenant des information liées à la mobilité et à l'événement Paris 2024 
Les données ne sont pas forcément aux standards attendus, mais nous avons fait le choix de les répertorier vu l'importance de l'évènement.

EN : The datasets listed in this category contain datasets published on data.gouv.fr information and related to mobility aroiund Paris 2024 event.
They might not meet the expected standards, but we have chosen to list them given the importance of the event.
