### ISSUE TITLE
Test de netex-validator-java d'Entur

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#3792]
Ce ticket décrit les tests réalisés avec la librairie [netex-validator-java](https://github.com/entur/netex-validator-java) d'Entur.

Solifa, prestataire de [Fintraffic](https://www.fintraffic.fi/en) a été très sympathique en partageant [un wrapper CLI](https://app.frontapp.com/open/cnv_179yvixi?key=I2veul4lVLZm1kRBnq7c4CqKORLG7UIv) pour exécuter cette librairie en ligne de commande. La librairie propose une validation à l'aide des schémas XSD et [quelques règles supplémentaires](https://github.com/entur/netex-validator-java?tab=readme-ov-file#default-rule-set) principalement à base de règles XPath.

## Installation et exécution en local

J'ai compilé et exécuté l'outil CLI en local, de manière directe et sans utiliser le Docker. Voici la procédure suivie avec OpenJDK 19.

Le fichier NeTEx à tester et à mettre dans le dossier `in/netex.zip`.

```sh
# Compilation
mvn package -DskipTests
# Exécution
java -jar validation-netex-entur.jar -i in -o out > netex.log
```

Les logs sont alors disponibles dans `netex.log` et le résultat de la validation est dans `out/reports.json`. Voici un exemple [du fichier JSON généré](https://gist.github.com/AntoineAugusti/ad41d57e14cab7360cc0a11a14c4a814), pour une validation sans erreurs.

**Comment by thbar** [comment]
Vu nos travaux en cours, je propose de ferme ce ficher, @AntoineAugusti ça te va ?
