### ISSUE TITLE
Metabase - paramétrage des courriels pour avoir accès à la fonctionnalité d'alerte

### ISSUE THREAD

**Issue by AurelienC** [etalab/transport-site#3805]
Dans l'objectif de pouvoir utiliser [le système d'alerte](https://www.metabase.com/docs/latest/questions/sharing/alerts) de Metabase, à vocation purement interne, il faut configurer la partie courriel.

![image](https://github.com/etalab/transport-site/assets/4528670/7f6f8db7-2f0d-4d47-8c82-cb44311e71c1)

Vu avec @thbar , il faut évaluer les impacts potentiels en cas de piratage du système si nous configurons les courriels dans Metabase.

**Comment by thbar** [comment]
@AurelienC j'ai fait un premier test ce soir en mettant une configuration spécifique Postmark (un outil SMTP pour lequel j'ai un abonnement), mais ce n'était pas concluant. Il faudra revisiter ça ensemble, ça sera plus simple ! 

J'ai fait un rollback après.

**Comment by thbar** [comment]
Ce n'est pas revenu sur la table pour le moment. On pourra réouvrir si besoin.
