### ISSUE TITLE
Jeu IRVE Belib invalide

### ISSUE THREAD

**Issue by stephane-pignal** [etalab/transport-site#3811]
J'ai testé la fonctionnalité suivante :
- #3772

Avec cette [ressource Belib](https://opendata.paris.fr/api/explore/v2.1/catalog/datasets/belib-points-de-recharge-pour-vehicules-electriques-donnees-statiques/exports/csv)

Qui se trouvait dans le [fichier consolidé](https://static.data.gouv.fr/resources/fichier-consolide-des-bornes-de-recharge-pour-vehicules-electriques/20240315-070825/consolidation-etalab-schema-irve-statique-v-2.3.1-20240315.csv) 

J'ai testé l'url Belib dans Validata, la validation ne semble ne pas fonctionner _"Erreur de lecture du fichier source : impossible de lire le contenu"_

Par contre cela semble marcher en téléchargeant le fichier

poke @thbar

**Comment by AntoineAugusti** [comment]
Je pense que c'est [ce bug connu](https://gitlab.com/validata-table/validata-table/-/issues/126) de Validata

**Comment by stephane-pignal** [comment]
En effet cela fonctionne avec l'url.csv du fichier Tesla. Merci @AntoineAugusti
