### ISSUE TITLE
Nouvelle discussion : titre et contenu sont obligatoires

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#3825]
[Retour d'expérience](https://app.frontapp.com/open/msg_25tb1nfa?key=K8mqLb4VHKmEwuc0E3XX7aZFNuLCH5bS) de Google Maps. Quand on démarre une nouvelle discussion sur transport.data.gouv.fr et qu'on ne renseigne pas un titre, on obtient une erreur lors de l'envoi du formulaire et on réinitialise les champs.

Rendre obligatoire le titre et le contenu quand on démarre une nouvelle discussion.

**Comment by AntoineAugusti** [comment]
Il serait super d'en profiter pour faire du textarea autoexpand après le merge de #3840 🚀

**Comment by ptitfred** [comment]
Pour l'instant je ne reproduis pas ce comportement en local.

J'observe ceci:
- Le champs renseigné n'est pas réinitialisé (mais c'est peut-être Firefox qui fait l'effort de conserver le contenu d'un formulaire).
- J'ai l'impression qu'ouvrir une discussion sans tous les champs rend le dataset inaccessible côté demo.data.gouv.fr. Peut-être une coïncidence avec d'autres opérations en cours chez data.gouv ?

**Comment by ptitfred** [comment]
> Il serait super d'en profiter pour faire du textarea autoexpand après le merge de #3840 🚀

Je réalise en te lisant que je n'ai sans doute pas mis le css au bon endroit dans les sources. J'en profiterai pour corriger ça.

**Comment by ptitfred** [comment]
Lucas a été prévenu.
