### ISSUE TITLE
Tests "Ops" qui bloquent les PR sans raison

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#3829]
Il y a des problèmes de résolution temporaire qui affectent le merge ou le CI en général, ça arrive actuellement assez souvent donc je crée un ticket pour ça.

```
  1) test Check DNS records SPF, DKIM and DMARC (Transport.OpsTests)
Error:      ops_tests/ops_tests.exs:77
     match (=) failed
     code:  assert {:ok, [[~c"v=spf1 include:sendgrid.net ~all"]]} = DNS.resolve("front-mail.#{@domain_name}", :txt)
     left:  {:ok, [[~c"v=spf1 include:sendgrid.net ~all"]]}
     right: {:error, :timeout}
     stacktrace:
       ops_tests/ops_tests.exs:85: (test)
```

Ça pose les questions suivantes:
- pourquoi ça échoue en premier lieu ? 
- est-ce qu'il y a une chance minime que ça impacte la production ? (je tablerais plutôt sur un souci lié au setup de résoluition "chez GitHub" mais il vaudrait mieux s'en assurer et comprendre)
- faut-il décaler ces tests en dehors des PR, plutôt avec un trigger régulier, pour ne pas bloquer les PR pour ça ?

à réfléchir !

**Comment by AntoineAugusti** [comment]
On peut changer de serveur DNS pour la résolution pour prendre quelque chose de plus stable peut-être

**Comment by AntoineAugusti** [comment]
Je me demande au passage comment on peut avoir un `{:error, :timeout}` d'ailleurs, alors que c'est censé être à `:infinity` par défaut 🤔 

https://github.com/tungd/elixir-dns/blob/a32f6998dbecedaf177edc2c9436dc057eea500b/lib/dns.ex#L31

**Comment by AntoineAugusti** [comment]
Asked around https://github.com/tungd/elixir-dns/issues/60

**Comment by thbar** [comment]
> Note: the :inet_dns module is considered internal to Erlang and subject to change. If this happened this library will be updated to accommodate for that, but for now :inet_dns is simple and worked for me.

https://github.com/tungd/elixir-dns/issues/53

Je me demande s'il y a un lien avec tout ça, c'est du code plutôt "interne" qui est utilisé par ce wrapper!

**Comment by AntoineAugusti** [comment]
Pas vu depuis des semaines. GitHub a amélioré la stabilité du DNS en CI ? On ferme ?

Pas eu de retour sur `elixir-dns` malheureusement.
