### ISSUE TITLE
Accès back-office pour Frédéric

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#3833]
Je me le note pour y penser.

Poke @ptitfred si tu peux me donner ton identifiant beta gouv je t'ajouterai à la team (et si tu n'en as pas on voit pour en faire un !).

**Comment by ptitfred** [comment]
frederic.menou@transport.data.gouv.fr

**Comment by thbar** [comment]
Hum je vois: https://www.data.gouv.fr/fr/users/frederic-menou/ mais je n'ai pas l'email. J'ajoute à partir du nom, tu me diras si c'est bon !

**Comment by ptitfred** [comment]
C'est bien ce compte.

**Comment by ptitfred** [comment]
J'ai accès au backoffice ; merci
