### ISSUE TITLE
Contacts : prévenir puis supprimer après une durée d'inactivité

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#3841]
Nous avons des contacts en base de données dans la table `contact`. Ils sont créés : lors de la connexion avec leur compte data.gouv.fr ou quand ils sont créés depuis le backoffice par l'équipe du PAN.

Cette table comporte une colonne `last_login_at`, [mise à jour lors de la connexion avec un compte data.gouv.fr](https://github.com/etalab/transport-site/blob/3f353dec9c168b456004ce6ad92e671e857a1dc8/apps/transport/lib/transport_web/controllers/session_controller.ex#L86).

Il faudrait :
- définir une durée de conservation appropriée, peut-être que [cette page](https://www.cnil.fr/fr/passer-laction/les-durees-de-conservation-des-donnees) peut donner quelques pistes ?
- ajouter un job Oban prévenant les utilisateurs qui sont inactifs depuis un moment que leur compte reste supprimer sans action de leur part (quelques rappels ?)
- prévoir un job de suppression

solliciter @etalab/transport-bizdev pour le contenu des e-mails envoyés et la durée appropriée. [ArchiveMetricsJob](https://github.com/etalab/transport-site/blob/master/apps/transport/lib/jobs/archive_metrics_job.ex) peut être une source d'inspiration !

**Comment by ptitfred** [comment]
Lors du premier passage du job en production, les contacts inactifs doivent-ils tout de même être prévenus ?

**Comment by AntoineAugusti** [comment]
> Lors du premier passage du job en production, les contacts inactifs doivent-ils tout de même être prévenus ?

Ça me parait acceptable. Si on reste sur 1 an (qui peut être un peu rapide), personne n'est concerné actuellement

**Comment by cyrilmorin** [comment]
Hello @AntoineAugusti et @ptitfred 

J'imagine que l'objectif est d'être un peu plus RGPD compatible et/ou de nettoyer notre BDD qui pourrait se remplir inutilement et empiriquement.

Avant de supprimer, il serait surement utile de traiter le sujet des différences entre nos contacts "user_datagouv" vs "liste de diffusion pour notifs" qui eux n'ont pas de date de _last_login_at_ par définition.
Maintenant qu'on va avoir des vrais user "producteur" et "réutilisateur" je pense qu'il faudra à terme rapprocher (via les adresses email ?) les contacts créés indépendamment qui sont également des users (c'est peut-être déjà fait !)

Autre point, tous ces contacts sont presque "occasionnels" (1 màj par an pour certains) et beaucoup passent encore par data.gouv (malheureusement). 
De plus ils peuvent avoir ont un rôle "passif" pour bénéficier de certaines features qui ne nécessitent pas de connexion comme la réception de notifs par exemple où on le fait à l'initialisation puis plus jamais mais où l'on bénéficie du service sur une longue période avec plaisir :) Du coup l'absence de mails sera alors considérer comme "pas de problème" notamment pour les contacts de type support@.... ou opendata@...  !

Autres cas pour la màj des données où il n'y a pas d'action à réaliser si on a une url distante (ce qu'on encourage)

Bref, on réfléchit à un mail explicite sur le sujet mais le côté "inactivité" pour le PAN est un critère que nous devons peut-être prendre avec des pincettes vu la fréquence de visite peu élevée voir nulle pour certains acteurs "actifs".

Dispo comme d'hab pour en parler si besoin !

**Comment by ptitfred** [comment]
Merci @cyrilmorin ,

Une option serait de retravailler les éléments de langage du premier email pour inclure ce cas et inviter la personne contactée à simplement nous confirme qu'elle souhaite rester active en cliquant sur un lien.
