### ISSUE TITLE
Plantage validata.fr et notre validateur

### ISSUE THREAD

**Issue by stephane-pignal** [etalab/transport-site#3845]
Concerne la [Ressource IRVE Alysé](https://www.data.gouv.fr/fr/admin/dataset/64c28634468d0d94dd98405e/resource/f762059d-32b2-417b-85b7-702ac36b0c0e) 

Avec le schéma annoncé [etalab/schema-sdirve](https://schema.data.gouv.fr/etalab/schema-sdirve/) 
A l'intérieur cela ressemble à un[ irve-statique](https://schema.data.gouv.fr/etalab/schema-irve-statique/) 

validata.fr et notre validateur plante
data précise bien "Documentation des fichiers manquante"
explore.data l'affiche correctement

![Capture d’écran 2024-03-28 à 14 18 52](https://github.com/etalab/transport-site/assets/162135418/c3299040-cde4-4b08-a9db-d572c96b0425)
![Capture d’écran 2024-03-28 à 14 43 50](https://github.com/etalab/transport-site/assets/162135418/7ae06a1c-2e20-453c-903a-f978af9967d3)

**Comment by thbar** [comment]
Merci @stephane-pignal je regarde !

**Comment by stephane-pignal** [comment]
Suite échange avec Cyril, il n'y aurait pas de lien direct entre l'erreur de tag du schéma (celui précisé lors du dépôt par le producteur) et le plantage validata.fr
