### ISSUE TITLE
Recherche : ordre non déterministe des jeux de données

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#3847]
Quand on effectue une recherche avec un résultat assez large (public-transit + LO par exemple, 203 jeux de données) et qu'on ne choisit pas un tri (ordre alphabétique ou récemment ajouté) l'ordre est non déterministe et peut poser problème étant donné que le résultat est par la suite paginé.

https://transport.data.gouv.fr/datasets?licence=licence-ouverte&type=public-transit affiche "Réseau urbain Astuce - lignes 26 et 530 (temps-réel)" en bas de page sur plusieurs pages actuellement.

Améliorer le fonctionnement par défaut pour offrir un ordre déterministe.

[Voir rapport de bug](https://app.frontapp.com/open/cnv_17ommlhy?key=xVGL6OTSWVove_A73mRoNegRWsXroLw1)

**Comment by thbar** [comment]
Merci pour l'info, je prends en compte pour les itérations du moteur de recherche v2 !
