### ISSUE TITLE
Documenter le fonctionnement des contacts et leur cycle de vie

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#3850]
Après quelques PR en liens avec ça, je m'aperçois que je n'ai pas une compréhension super claire du fonctionnement des contacts (cycle de vie, règles, lien avec DataGouv etc).

J'ai besoin de bien comprendre ça.

Il y a déjà eu des efforts de documentation ici (merci @AntoineAugusti pour la réponse et @vdegove pour la question :heart:):
- https://github.com/etalab/transport-site/pull/3804/files#r1525108913

On a du "prior art" en terme d'explications qui ont pu aider une partie de l'équipe:
- https://github.com/etalab/transport-site/blob/master/docs/data_model.livemd
- https://github.com/etalab/transport-site/blob/master/docs/inventaire_donnees_geographiques_septembre_2023.md

Je suis assez persuadé que bien expliciter ça par écrit, et s'assurer que chaque développeur (dans un premier temps) puis bizdev (dans un second temps) a la même compréhension, sera utile pour communiquer les usages au public aussi (on a vu ça plusieurs fois - si le concept n'est pas clair pour une partie de l'équipe, il y a aussi de la confusion pour les utilisateurs derrière, cf exemple ci-dessus avec la géographie).

Par ailleurs ça aidera aussi à clarifier au besoin des clauses RGPD à un moment, même si en l'état l'usage ne semble pas problématique.

**Comment by thbar** [comment]
Je suggère la création d'un label "ELI5" ("explain like I'm 5.") d'ailleurs éventuellement, pour marquer un peu l'idée !!!

**Comment by AntoineAugusti** [comment]
D'acc', je peux écrire un rapide document. J'avais évoqué de faire une présentation orale à l'équipe tech à un moment et je ne sais plus si ça avait été effectué !
