### ISSUE TITLE
UX - Indicateurs, les tableaux de bord débordent parfois

### ISSUE THREAD

**Issue by cyrilmorin** [etalab/transport-site#3851]
Hello, 

Remonté par Maxime Siret mais je n'arrive pas à reproduire de mon côté.
_Le graphique "déborde" dans le rendu UI lorsque que l'historique contient a +3 mois (cf. en PJ "graph.png")._
![image](https://github.com/etalab/transport-site/assets/116101828/a53998d7-812c-4cf0-b4ca-683da8ab87b6)

éléments complémentaires : _J'arrive à reproduire sur Marseille ([lien](https://transport.data.gouv.fr/datasets/reseaux-de-transports-en-commun-de-la-metropole-daix-marseille-provence-et-des-bouches-du-rhone) + screen en PJ) par exemple, sur Chrome OS_.
![image](https://github.com/etalab/transport-site/assets/116101828/6470770d-7bee-4000-98cd-34b1408ab1be)

**Comment by AntoineAugusti** [comment]
Je me souviens avoir déjà galéré sur ce sujet quand j'avais fait la première implémentation mais je vais regarder de nouveau.

https://github.com/vega/react-vega/issues/85 pourrait donner des pistes

**Comment by AntoineAugusti** [comment]
@cyrilmorin Ceci devrait être corrigé en production. Peux-tu prévenir Maxime de la correction ? Je peux m'en charger si tu souhaites.

**Comment by cyrilmorin** [comment]
@AntoineAugusti OK parfait merci, je m'en occupe
