### ISSUE TITLE
NewDatagouvDatasetsJob : exécuter uniquement les jours ouvrés

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#3856]
[Ce job](https://github.com/etalab/transport-site/blob/master/apps/transport/lib/jobs/new_datagouv_datasets_job.ex) est en charge d'effectuer une veille automatisée des jeux de données publiés sur data.gouv.fr et qui sont susceptibles d'avoir leur place sur notre plateforme. Il est adressé à nos bizdevs.

Ce job est exécuté de manière quotidienne actuellement, entrainant des e-mails le samedi ou le dimanche.

Adapter ce job pour avoir une exécution uniquement du lundi au vendredi afin de limiter le nombre d'e-mails et faciliter le suivi. #3846 ajoute ce mécanisme si tu souhaites t'en inspirer ou trouver un moyen de mettre ceci en commun.

**Comment by AntoineAugusti** [comment]
cc @etalab/transport-bizdev une petite amélioration pour ce process

**Comment by ptitfred** [comment]
> Adapter ce job pour avoir une exécution uniquement du lundi au vendredi afin de limiter le nombre d'e-mails et faciliter le suivi. #3846 ajoute ce mécanisme si tu souhaites t'en inspirer ou trouver un moyen de mettre ceci en commun.

C'est ce que je comptais faire, à l'ancienne façon cron
