### ISSUE TITLE
Espace réutilisateurs - Fonctionnement de l'ajout d'un favori via le coeur

### ISSUE THREAD

**Issue by cyrilmorin** [etalab/transport-site#3859]
Hello @AntoineAugusti 

Suite à notre discussion voici quelques précisions pour le comportement suite au clic sur le cœur "noir"

Mode non connecté : 

1. Invitation à se connecter/s'inscrire avec la phrase "Connectez vous [lien vers avec une redirection vers la page de connexion] pour bénéficier des services liés aux jeux de données !" . 
2. Une fois connecté/inscrit => retour sur la page du dataset avec le cœur "rouge"

Mode connecté :
Le cœur devient rouge au clic et déclenche les actions ci-dessous :

1. Apparition d'un message (bannière verte ? message uniquement ? à proximité du cœur ?) : "Jeu de données ajouté aux favoris ! Personnalisez vous préférences depuis votre espace réutilisateur [Lien vers espace réutilisateur et redirection vers un nouvel onglet]
2. Ajout du dataset dans la liste des favoris du réutilisateur
3. Ajout par défaut de toutes les notifications "réutilisateurs" liées au dataset en question
4. Ajout par défaut au suivi des discussions liées au dataset en question
5. Envoyer un email de bienvenue suite à la création du 1er favori (uniquement) : 

"Bonjour,

Vous venez d'ajouter votre 1er favori pour suivre un jeu de données référencé sur le PAN et nous vous en félicitons !

Vous pourrez désormais être alerté lorsque le jeu de données est indisponible ou contient des erreurs par exemple. Vous serez également tenu au courant des différentes discussions publiques initiées par les producteurs de données ou d'autres réutilisateurs.

Rendez-vous sur votre espace réutilisateur [Lien vers espace réutilisateur] pour personnaliser vos préférences et participer à la constante amélioration de la qualité des données de mobilité !

A bientôt,

L'équipe du PAN"

Le clic sur le cœur rouge rend le cœur noir et désactive les notif et suivis de discussion du jeu en question pour le réutilisateur

A dispo pour en parler à nouveau si besoin

**Comment by AntoineAugusti** [comment]
@cyrilmorin

> Une fois connecté/inscrit => retour sur la page du dataset avec le cœur "rouge"

Ça va être pas si aisé d'effectuer l'action, mais je vais m'assurer d'aller jusqu'à la redirection sur la page du jeu de données en question.

> Ajout par défaut au suivi des discussions liées au dataset en question

Le suivi des discussions est une notification qui n'est pas spécifique à un JDD, on parle de "platform wide". On peut s'abonner à cette notification pour tous les JDDs que l'on suit ou à rien du tout. transport.data.gouv.fr fera un résumé des discussions quotidien et non un e-mail à chaque fois qu'il y a une action.

Les autres motifs :
https://github.com/etalab/transport-site/blob/5a128523894079441436cff96d3e71e23d4fb7e5/apps/transport/lib/db/notification_subscription.ex#L15-L16

Je vais faire en sorte d'inscrire la personne à cette fonctionnalité si :
- la personne n'est pas inscrite déjà à ce motif
- il n'y a pas d'abonnements à des notifications pour d'autres JDDs

En effet il est possible qu'on inscrive la personne "de force" puis qu'elle se désinscrive et il ne faut pas qu'on l'inscrive par défaut la prochaine fois que l'utilisateur suit un autre jeu de données.

**Comment by AntoineAugusti** [comment]
@cyrilmorin Peux-tu me proposer un sujet pour l'e-mail envoyé ? On l'envoie immédiatement ou en différé ?

**Comment by AntoineAugusti** [comment]
@cyrilmorin Il y aura bien la redirection vers la page du JDD, juste pas l'action de le mettre en favori etc. Il faudra que la personne clique à nouveau après la redirection.

J'ai modifié le sujet de l'e-mail https://github.com/etalab/transport-site/pull/3864/commits/f96e9b97cc1ab620f13d9c2b39b22e0023d1f5b9
