### ISSUE TITLE
Planifier la montée en charge du proxy GTFS-RT sur l'année 2024+

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#3872]
Vu qu'on discute demain les objectifs trimestriels, je me suis rappelé qu'il fallait que je vérifie la tendance sur le mois de mars, qui est maintenant écoulé, pour au moins en toucher un mot, "because the clock is ticking".

Pour différentes raisons le trafic continue à monter (+ de jeux de données, + de visibilité sur les réseaux sociaux, + de réutilisations).

On a fait environ x3 entre janvier 2023 et janvier 2024 si je ne me trompe pas.

Il va falloir commencer à faire certaines vérifications:
- que peut supporter l'archi actuelle en l'état, sans optimisation ?
- combien de temps ça nous laisse ?
- quelle est la tendance sur les 3 mois à venir ? (et faire des projections)

Et planifier ou pas les adaptations de scaling adéquates (et il peut y en avoir des très légères, ou des plus lourdes).

Merci Metabase, on a ce joli graphique actuellement:

![CleanShot 2024-04-10 at 21 30 18@2x](https://github.com/etalab/transport-site/assets/10141/6e47cd10-7f44-471f-bfd9-6f58fb7a7635)

**Comment by AntoineAugusti** [comment]
La fin du proxy pour les conversions GBFS #3455 retirera environ 5,5M de requêtes par mois [Mattermost](https://mattermost.incubateur.net/betagouv/pl/oh8617o8s3gw58ok1ydtdp616c)

**Comment by thbar** [comment]
Je vais aller faire un test de charge 😄

**Comment by thbar** [comment]
Voilà ce que je vais faire:
- [ ] Créer des éléments de configuration alternative (sur 4 ou 5 flux) sur https://github.com/etalab/transport-proxy-config (afin de pouvoir charger la barque directement sur la production, mais sans polluer les métriques)
- [ ] Scripting d'un peu de charge (avec un script capable de fonctionner autant depuis un poste de dév, que depuis la machine elle-même pour pouvoir tester "un peu plus haut" avec une latence réduite)

En effet, sur un premier test rapide, je vois qu'on a de la perte (attendue à un moment) d'events au niveau de Ecto, sur `prochainement` en tout cas.

Si je lance 10k requêtes, elles retournent (bonne nouvelle) bien 10k en HTTP 200.

`hey -n 10000 -c 50 https://proxy.prochainement.transport.data.gouv.fr/resource/divia-dijon-gtfs-rt-trip-update`

<details>

<summary>output</summary>

```
Summary:
  Total:	38.1099 secs
  Slowest:	1.0237 secs
  Fastest:	0.0240 secs
  Average:	0.1877 secs
  Requests/sec:	262.3992
  

Response time histogram:
  0.024 [1]	|
  0.124 [1124]	|■■■■■■
  0.224 [7457]	|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
  0.324 [863]	|■■■■■
  0.424 [203]	|■
  0.524 [115]	|■
  0.624 [145]	|■
  0.724 [70]	|
  0.824 [14]	|
  0.924 [2]	|
  1.024 [6]	|


Latency distribution:
  10% in 0.1210 secs
  25% in 0.1467 secs
  50% in 0.1704 secs
  75% in 0.1942 secs
  90% in 0.2549 secs
  95% in 0.3391 secs
  99% in 0.6183 secs

Details (average, fastest, slowest):
  DNS+dialup:	0.0006 secs, 0.0240 secs, 1.0237 secs
  DNS-lookup:	0.0003 secs, 0.0000 secs, 0.0658 secs
  req write:	0.0000 secs, 0.0000 secs, 0.0034 secs
  resp wait:	0.1845 secs, 0.0226 secs, 0.8953 secs
  resp read:	0.0026 secs, 0.0009 secs, 0.0369 secs

Status code distribution:
  [200]	10000 responses
```

</details>

Mais en base on ne retrouve pas les petits, ce qui indique (et on voit des erreurs Sentry) que l'insertion des métriques attend ses limites:

```sql
select * from metrics where target like '%divia%'
```

| id    | target                                | event                  | period              | count | inserted_at                | updated_at                 |
|-------|---------------------------------------|------------------------|---------------------|-------|----------------------------|----------------------------|
| 10600 | proxy:divia-dijon-gtfs-rt-trip-update | proxy:request:internal | 2024-05-20 15:00:00 |     4 | 2024-05-20 15:09:35.089634 | 2024-05-20 15:09:35.089634 |
| 10596 | proxy:divia-dijon-gtfs-rt-trip-update | proxy:request:external | 2024-05-20 15:00:00 |  9330 | 2024-05-20 15:09:35.088964 | 2024-05-20 15:09:35.088964 |

Comme attendu, à un moment l'upsert "un par un" finit par tirer sur le pool Ecto un peu trop:

https://github.com/etalab/transport-site/blob/aa4f121987204709a11ee4655af0a8805c1cbea6/apps/transport/lib/transport/telemetry.ex#L100-L115

Tout ceci concerne `prochainement`, voir plus haut, il faudra reproduire cela sur la production de façon non intrusive, déterminer le seuil approximatif où ça commence à craquer, et voir combien de temps on a devant nous.

**Comment by thbar** [comment]
Mes tests tournaient à 260 rps. J'ai cherché à aller voir où se situent nos pointes en "requêtes externes". 

On ne peut pas obtenir le "max rps" réel (par seconde), mais on peut avoir celui moyenné sur une heure.

:warning: requête à relire à tête reposée

```sql
select period, sum(count) as count, sum(count) / (60*60) as average_requests_per_sec from metrics
where event = 'proxy:request:external'
group by period
order by count desc
```

Ce qui m'interpelle c'est que les RPS max sont tous autour de minuit (je regarderai ça de plus près, j'ai pu juste me tromper dans ma requête):

| period              | count   | average_requests_per_sec |
|---------------------|---------|--------------------------|
| 2024-02-10 00:00:00 | 2189160 |                      608 |
| 2024-01-19 00:00:00 | 2156081 |                      598 |
| 2024-01-25 00:00:00 | 2147131 |                      596 |
| 2024-01-20 00:00:00 | 2019283 |                      560 |
| 2024-01-31 00:00:00 | 1926555 |                      535 |
| 2024-02-06 00:00:00 | 1914865 |                      531 |
| 2024-02-14 00:00:00 | 1820662 |                      505 |
| 2024-02-05 00:00:00 | 1797976 |                      499 |
| 2024-02-09 00:00:00 | 1769301 |                      491 |

En pointe on serait à 600 rps.

À suivre, je continuerai mon enquête.

**Comment by thbar** [comment]
Hum j'obtiens des mesures très bizarres sur certaines requêtes 🤣 je regarderai clairement de plus près.

**Comment by AntoineAugusti** [comment]
@thbar J'ai pas eu l'explication immédiate puis je me suis souvenu, on regroupe à la journée après 90 jours et donc on n'a plus le détail à l'heure pour ces anciennes lignes.

https://github.com/etalab/transport-site/blob/master/apps/transport/lib/jobs/archive_metrics_job.ex

**Comment by thbar** [comment]
@AntoineAugusti ok, ça me paraissait curieux !!! Ok merci il faudra prendre ça en compte, merci pour le déterrage de job !

**Comment by ptitfred** [comment]
À toutes fins utiles :

```sql
SELECT extract(hour from period) as hour_of_day, count(*)
FROM metrics
GROUP BY 1
ORDER BY 1;
```

| hour_of_day | count  |
|-------------|--------|
|           0 | 133042 |
|           1 |  17166 |
|           2 |  16974 |
|           3 |  16976 |
|           4 |  16976 |
|           5 |  16976 |
|           6 |  16978 |
|           7 |  16992 |
|           8 |  16996 |
|           9 |  16990 |
|          10 |  16982 |
|          11 |  16978 |
|          12 |  16982 |
|          13 |  16982 |
|          14 |  16982 |
|          15 |  16986 |
|          16 |  16988 |
|          17 |  16982 |
|          18 |  16978 |
|          19 |  16978 |
|          20 |  16978 |
|          21 |  16980 |
|          22 |  16978 |
|          23 |  16978 |

**Comment by thbar** [comment]
J'ai amendé ma requête pour ne pas aller au delà de 2 mois, cf discussions précédentes:

```sql
select period, sum(count) as count, sum(count) / (60*60) as average_requests_per_sec from metrics
where event = 'proxy:request:external'
and period >= (NOW() - INTERVAL '2 months')
group by period
order by count desc
```

On obtient ainsi le RPS moyen par seconde, sur l'heure.

Les dix premières sont:

| period              | count  | average_requests_per_sec |
|---------------------|--------|--------------------------|
| 2024-06-05 20:00:00 | 140383 |                       38 |
| 2024-05-31 08:00:00 | 139122 |                       38 |
| 2024-06-04 12:00:00 | 138352 |                       38 |
| 2024-06-06 15:00:00 | 138239 |                       38 |
| 2024-06-04 13:00:00 | 137196 |                       38 |
| 2024-06-12 10:00:00 | 136807 |                       38 |
| 2024-06-06 02:00:00 | 136483 |                       37 |
| 2024-06-05 17:00:00 | 135828 |                       37 |
| 2024-05-31 11:00:00 | 135788 |                       37 |
| 2024-06-05 19:00:00 | 135674 |                       37 |

Attention, ça reste une moyenne _à la seconde_ basée sur une heure de calcul, autant dire ça ne permet pas de conclure sur un "max RPS" fiable du tout. Pour ça il faudrait capturer sur une granularité plus fine, avec TimescaleDB par exemple.

Je vais néanmoins me baser là dessus pour les tests que je réalise là.

**Comment by thbar** [comment]
J'ai réalisé différents tests, en m'appuyant sur le nombre de requêtes moyennes ci-dessus (qui n'est qu'indicatif vu qu'on n'a pas la granularité à la minute ou plus bas).

### TL;DR

- ça commence à craquer (en termes de retours HTTP et de payload proxifiée) autour de 950 requêtes/secondes (sur cible unique), avec un tout petit pourcentage -> si ce test reflète assez bien la réalité, on a pas mal de mou, considérant qu'on a un "rps moyenné sur l'heure max" de 40 actuellement (mais une fois de plus, ça ne reflète pas le "peak" sur une minute donnée, ça on n'en a aucune idée actuellement)
- en l'absence de traffic externe autre que le proxy, le pool Ecto tient très bien
- et ça craque au niveau Ecto beaucoup plus rapidement (une requête seconde sur les "modes" à côté va "manger" le pool, et à partir de là les métriques ne sont plus insérés). Si on continue à avoir des salves d'erreurs comme https://github.com/etalab/transport-site/issues/3997 après https://github.com/etalab/transport-site/pull/4006 et autres optimisations de ce type), il faudra envisager de "batcher" les upserts un petit peu (là c'est du upsert individuel)

On a du temps (sauf évènement particulier) devant nous (ce qui est était ce que je voulais vérifier), et il y a donc deux hotspots à optimiser à un moment:
- upsert des métriques, en passant de "un par un" à "un peu de batch" (mais en faisant attention à ne pas perdre d'info au restart, il faut flusher à la fin du cycle de vie, et régulièrement aussi, genre une fois par seconde devrait suffire)
- craquage au niveau du code proxy à un moment (inévitable, il y a toujours un endroit où ça finit par nécessiter une amélioration)

Et surtout il faut optimiser les soucis comme #3301 dès que possible, de façon générale.

### Méthodo suivie

- lancer des commandes en local avec `hey` (https://github.com/rakyll/hey), en ajustant les paramètres `-n` (nombre de requêtes total), `-c` (nombre de workers) et `-q` (max rps). Vu que c'est en local, `-q` ne fixe pas le rps effectif, il faut un peu jongler, et s'appuyer sur le nombre de rps rapportés par l'outil dans l'output, plutôt que dans celui demandé, car l'écart est parfois très important
- je n'ai testé qu'avec une url à chaque fois (voir mise en place dans https://github.com/etalab/transport-proxy-config/pull/98)
- je vérifie les outputs consolidés (HTTP 200, 502 etc)
- je suis en base avec du SQL, que les métriques sont bien injectés (voir plus bas), pour que ça témoigne du fait que le pool Ecto est suffisamment solide
- j'en ai profité pour faire le même exercice avec des requêtes sur les "modes" (#3301, #4006) tant que j'y étais

### Résultats

1. si pas d'autre charge sur le site, on peut monter assez haut (dans les 980 requêtes/secondes). La partie métriques et ecto tient bien (nombre de métriques en base = nombre de requêtes), toutefois il y a autre chose qui plante (peut-être un pool HTTP je pense, ou autre chose), pour un tout petit pourcentage de requêtes (11 erreurs, 19989 ok, sur 20000 demandées), ce qui montre un bottleneck futur quelque part qu'il faudra traiter si on atteint ces échelles. Ça montre aussi qu'on ne peut pas juste s'appuyer sur le fait que les métriques sont là, il faudrait aussi logger les HTTP status

<details><summary>Test 20k requêtes</summary>

```
❯ hey -n 20000 -c 25 -q 2000 https://proxy.prochainement.transport.data.gouv.fr/resource/transport-data-load-testing-001

Summary:
  Total:	20.2925 secs
  Slowest:	0.8936 secs
  Fastest:	0.0150 secs
  Average:	0.0251 secs
  Requests/sec:	985.5848
  
  Total data:	857068474 bytes
  Size/request:	42853 bytes

Response time histogram:
  0.015 [1]	|
  0.103 [19941]	|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
  0.191 [7]	|
  0.279 [0]	|
  0.366 [17]	|
  0.454 [9]	|
  0.542 [0]	|
  0.630 [0]	|
  0.718 [0]	|
  0.806 [0]	|
  0.894 [25]	|


Latency distribution:
  10% in 0.0188 secs
  25% in 0.0202 secs
  50% in 0.0222 secs
  75% in 0.0254 secs
  90% in 0.0297 secs
  95% in 0.0333 secs
  99% in 0.0441 secs

Details (average, fastest, slowest):
  DNS+dialup:	0.0001 secs, 0.0150 secs, 0.8936 secs
  DNS-lookup:	0.0000 secs, 0.0000 secs, 0.0169 secs
  req write:	0.0000 secs, 0.0000 secs, 0.0194 secs
  resp wait:	0.0244 secs, 0.0148 secs, 0.8616 secs
  resp read:	0.0005 secs, 0.0000 secs, 0.0352 secs

Status code distribution:
  [200]	19989 responses
  [502]	11 responses
```

</details>

2. si un peu de charge à côté sur des requêtes lentes, typiquement sur https://github.com/etalab/transport-site/issues/3301 actuellement, le proxy tient bien (réponse 200) grâce au design qui "décale" les upserts Ecto pour les métriques dans une tâche asynchrone, mais heureusement, car les métriques eux sont perdus en grande majorité (359 comptés, pour 20k réalisés). Cela montre (comme projeté) l'impact des défaillances à côté, sur le proxy, du fait du partage du pool Ecto d'une part, et surtout du fait des lenteurs à côté:

<details><summary>100% de HTTP 200</summary>

```
❯ hey -n 20000 -c 25 -q 2000 https://proxy.prochainement.transport.data.gouv.fr/resource/transport-data-load-testing-001

Summary:
  Total:	39.0853 secs
  Slowest:	2.3512 secs
  Fastest:	0.0145 secs
  Average:	0.0483 secs
  Requests/sec:	511.7014
  
  Total data:	857540000 bytes
  Size/request:	42877 bytes

Response time histogram:
  0.015 [1]	|
  0.248 [19532]	|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
  0.482 [62]	|
  0.716 [92]	|
  0.949 [41]	|
  1.183 [115]	|
  1.417 [83]	|
  1.650 [25]	|
  1.884 [0]	|
  2.118 [25]	|
  2.351 [24]	|


Latency distribution:
  10% in 0.0187 secs
  25% in 0.0201 secs
  50% in 0.0223 secs
  75% in 0.0257 secs
  90% in 0.0312 secs
  95% in 0.0376 secs
  99% in 1.1199 secs

Details (average, fastest, slowest):
  DNS+dialup:	0.0001 secs, 0.0145 secs, 2.3512 secs
  DNS-lookup:	0.0000 secs, 0.0000 secs, 0.0036 secs
  req write:	0.0000 secs, 0.0000 secs, 0.0038 secs
  resp wait:	0.0473 secs, 0.0144 secs, 2.3352 secs
  resp read:	0.0009 secs, 0.0000 secs, 0.0375 secs

Status code distribution:
  [200]	20000 responses
```

</details>

mais requête SQL (voir plus bas en annexe) qui donne:

| target                                | event                  | sum |
|---------------------------------------|------------------------|-----|
| proxy:transport-data-load-testing-001 | proxy:request:external | 356 |

(356 au lieu de 20000)

### Requêtes SQL utiles

```sql
select * from metrics
where target like '%transport-data-load-testing%'

delete from metrics where target like '%transport-data-load-testing%'

select target, event, sum(count) from metrics
where target like '%transport-data-load-testing%'
group by target, event
```

**Comment by ptitfred** [comment]
👏 joli boulot

**Comment by thbar** [comment]
> 👏 joli boulot

Merci !

**Comment by AntoineAugusti** [comment]
@thbar Merci pour le rapport et l'analyse détaillée 👏 Bonne nouvelle 🎉
