### ISSUE TITLE
Erreur 500 sur la page de notifications de l’espace producteur : could not put/update key :team_subscriptions on a nil value

### ISSUE THREAD

**Issue by vdegove** [etalab/transport-site#3887]
Sentry : https://transport-data-gouv-fr.sentry.io/issues/5217654056

- [ ] Page de notifications : aller chercher en BDD uniquement les notifs des reasons qui correspondent au rôle dans la requête via DB.NotificationSubscription
- [ ] Mettre une contrainte en changeset sur les types de notifications vs rôle
- [ ] L’utiliser dans la page de notifs

**Comment by vdegove** [comment]
En gros le problème c’est ici : https://github.com/etalab/transport-site/blob/f94a12d3de2390bcd20091a969d71c7dc10a42bb/apps/transport/lib/transport_web/live/notifications_live.ex#L132

Le reduce s’appuie sur une structure vide, créée par `subscriptions_empty_map(:producer, datasets)` avec des cases pour chaque notification possible en tant que producteur. Or on essaye de fourrer dans cette structure vide des notifications qui n’ont pas un motif prévu pour les producteurs.

**Comment by AntoineAugusti** [comment]
@ptitfred Pour ton suivi, @vdegove a détaillé une liste de tâches à réaliser (on avait déjà abordé un bon bout ensemble). Vincent va indiquer quelles tâches il va réaliser et on pourra se répartir le reste.

**Comment by vdegove** [comment]
La suite est donc ici https://github.com/etalab/transport-site/issues/3896
