### ISSUE TITLE
CI : vérifier que le fichier Protobuf GTFS-RT est bien à jour

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#3891]
Voir #3888 

Le fichier GTFS-RT change de manière périodique. Il est possible qu'on ne soit pas au courant et que ceci pose des problèmes (voir https://github.com/etalab/transport-site/issues/3053 précédemment).

Ajouter un job en CI qui vérifie que notre fichier local dans le dépôt est bien le même que sur https://github.com/google/transit/tree/master/gtfs-realtime/proto ?

Quand le job fail (sans bloquer un merge) on pourra prévoir de mettre à jour chez nous.

**Comment by ptitfred** [comment]
Est-ce que les producteurs suivent les montées de version ?

**Comment by AntoineAugusti** [comment]
La théorie voudrait que oui, avec plus ou moins de délai.

**Comment by ptitfred** [comment]
Néglige-t-on ce déphasage potentiel ?
