### ISSUE TITLE
Notifications : durcir la séparation producteur / réutilisateur

### ISSUE THREAD

**Issue by vdegove** [etalab/transport-site#3896]
Suite de https://github.com/etalab/transport-site/issues/3887

- [x] Empêcher d’importer en favori un JDD pour lequel on est producteur @AntoineAugusti https://github.com/etalab/transport-site/pull/3898
- [x] Quand quelqu’un passe de réutilisateur à producteur, supprimer ses notifs au lieu de les modifier et recréer toutes les notifs de l’autre rôle @AntoineAugusti https://github.com/etalab/transport-site/pull/3912   
- [x] Modifier le role à `reuser` pour les abonnements existants aux motifs _platform-wide_ @AntoineAugusti #3906 
- [x] Créer par défaut toutes les notifs quand on fav 
- [ ] Créer par défaut toutes les notifs quand on est rajouté comme contact producteur (à vérifier avec @cyrilmorin d'abord)
- [x] Utiliser le changeset partout où on édite des notifications
- [x] UX/UI : liens vers l’espace producteur / espace réutilisateur sur les JDD produits ou suivis. Sera traité dans https://github.com/etalab/transport-site/issues/3908

**Comment by cyrilmorin** [comment]
Hello @vdegove

Je te confirme pour "_Créer par défaut toutes les notifs quand on est rajouté comme contact producteur (à vérifier avec @cyrilmorin d'abord_)" => OK pour moi !
Pour "UX/UI : liens vers l’espace producteur / espace réutilisateur sur les JDD produits ou suivis" j'essaie de vous faire des propositions en essayant de bien penser également à la visibilité de la feature qu'on souhaite mettre en avant

Merci !

**Comment by cyrilmorin** [comment]
Hello @AntoineAugusti 

**Créer par défaut toutes les notifs quand on est rajouté comme contact producteur**
Yes, c'est vrai que nos utilisateurs "PAN" le deviennent finalement à l'instant où ils se connectent au PAN pour la 1ère fois (hors action d'une super admin). 
Il faudrait effectivement les inscrire aux notifs à ce moment et envoyer le mail de bienvenue et gestion des notifs pour leur donner à la fois l'info et la possibilité de les supprimer si besoin (atténue le côté "pushy")

**Gérer le désabonnement automatique des notifs d'un producteur**
Est-ce qu'on gère bien le cas de figure où on est producteur de données d'1 organisation mais qu'on suit une organisation dont on ne fait pas partie (réutilisateur) ?
C'est le cas pour Nicolas De Cocquerel (Membre de AURA mais pas d'Isère) et Mme Solé (Membre de Grand Narbonne mais pas de Open SIG Langudoc Roussilon). Ce sont des producteurs et des réutilisateurs selon le dataset
Après je ne sais pas si ils ont vraiment quitté l'autre organisation ou pas ...

A ce stade je ne m'embêterai pas trop pour les suppressions des notifs, ils ont accès à leur BO et on leur rappellera dans les mails "Vous ne vous êtes pas connecté depuis plus d'1 an ...."

OK pour toi ?

**Comment by AntoineAugusti** [comment]
@cyrilmorin 

## Créer par défaut toutes les notifs quand on est rajouté comme contact producteur

> Il faudrait effectivement les inscrire aux notifs à ce moment et envoyer le mail de bienvenue et gestion des notifs pour leur donner à la fois l'info et la possibilité de les supprimer si besoin (atténue le côté "pushy")

Je peux faire ça ! Peux-tu me proposer un sujet + contenu pour l'e-mail correspondant ?

Voir [le contenu de l'e-mail](https://github.com/etalab/transport-site/blob/master/apps/transport/lib/transport_web/templates/email/promote_reuser_space.html.md) que l'on envoie lorsqu'un réutilisateur utilise le coeur pour la première fois.

## Gérer le désabonnement automatique des notifs d'un producteur

> Est-ce qu'on gère bien le cas de figure où on est producteur de données d'1 organisation mais qu'on suit une organisation dont on ne fait pas partie (réutilisateur) ?

Oui, c'est bien géré. Par contre il ne verra pas le "coeur bleu" ou "espace producteur" comme il n'est pas producteur au sens membre de l'organisation mais il recevra les notifications en tant que producteur. Il ne pourra pas gérer ça dans son "Espace producteur" actuellement, @vdegove avait mis en évidence cette difficulté. À revoir…

> A ce stade je ne m'embêterai pas trop pour les suppressions des notifs, ils ont accès à leur BO et on leur rappellera dans les mails "Vous ne vous êtes pas connecté depuis plus d'1 an ...."

👌

**Comment by AntoineAugusti** [comment]
@cyrilmorin Je t'ai proposé le texte suivant.

**Sujet :** Bienvenue ! Découvrez votre Espace producteur
[Contenu](https://github.com/etalab/transport-site/pull/3940/files#diff-206e4ed7943a37d61cd86a900db7ebf28abfbf4fb5b85628d6391bc155e1c40b)

**Comment by cyrilmorin** [comment]
@AntoineAugusti Merci pour le contenu c'est parfait pour moi !
