### ISSUE TITLE
Ajout d’un `mtm_campaign` pour l’API de recherche d’entreprises

### ISSUE THREAD

**Issue by XavierJp** [etalab/transport-site#3902]
Nous souhaiterions tracker plus finement les utilisations de notre API Recherche d’Entreprises. Pourriez-vous ajouter `mtm_campaign=transport-data-gouv-fr` à la fin de l’url ?

https://github.com/etalab/transport-site/blob/64bbc889be9678df4bb8c864874c5db4ef14f005/apps/transport/lib/transport/companies.ex#L9

Les stats apparaitront ici dans la partie `Campagne` :
https://stats.data.gouv.fr/index.php?module=CoreHome&action=index&idSite=294&period=range&date=previous30#?period=day&date=2024-04-30&idSite=294&category=Referrers_Referrers&subcategory=Referrers_WidgetGetAll

**Comment by AntoineAugusti** [comment]
@XavierJp Bien sûr 👌

**Comment by XavierJp** [comment]
Merci ! :)
