### ISSUE TITLE
Modifications quick win pour BO (wording ...)

### ISSUE THREAD

**Issue by cyrilmorin** [etalab/transport-site#3905]
Quelques éléments ne sont pas toujours explicites pour les nouveaux arrivants et objectivement de manière générale.
Des modifications mineures permettraient de faciliter la prise en main et l'usage.

Depuis la page [d'édition d'un dataset](https://transport.data.gouv.fr/backoffice/datasets/38/edit) : 
=> Modifier le texte du bouton "Editer" par "Enregistrer"

=> Modifier le titre "Abonnements aux notifications" par "Abonnements aux notifications des producteurs"
En effet, avec l'arrivée du suivi des datasets par les réutilisateurs, il faudra préciser que les abonnements aux notifications depuis le BO sont celles des contacts producteurs uniquement. 
A confirmer que c'est bien le cas. Si tous les contacts seront présents dans le BO on spécifiera dans un autre ticket le fonctionnement attendu (probablement une tag "producteurs de données" sera suffisant à l'image des discussions actuellement)

Depuis le menu "Jeux de données disponibles"  sur la page "[Administration](https://transport.data.gouv.fr/backoffice)" 
=> Modifier le texte du bouton "Supprimer" par "Déréférencer" qui précise qu'on ne supprimer le dataset (dans datagouv) mais qu'on le déréférence du PAN uniquement
=> Modifier l'action des liens vers les datasets de transport.datagouv.fr et data.gouv.fr pour ouvrir dans un nouvel onglet plutôt que de remplacer la page actuelle

A dispo si besoin et merci !

**Comment by AntoineAugusti** [comment]
> Si tous les contacts seront présents dans le BO on spécifiera dans un autre ticket le fonctionnement attendu (probablement une tag "producteurs de données" sera suffisant à l'image des discussions actuellement)

Les contacts dans le backoffice et en base de données sont :
- des personnes ou mailing list ajoutées par notre équipe dans le BO
- des personnes qui se sont connectées avec leur compte data.gouv.fr chez nous (qui peuvent être producteur, réutilisateur ou les deux)

L'interface met en évidence les contacts membres de l'organisation qui produit le JDD qui se sont déjà connectés chez nous, pour les inscrire rapidement si besoin. J'ai amélioré un peu l'interface.

![image](https://github.com/etalab/transport-site/assets/295709/3304f632-643c-4112-8dcf-ecabc1a0e166)
