### ISSUE TITLE
Créer une page Info_réutilisateur et en faire une page SAS pour le mode déconnecté

### ISSUE THREAD

**Issue by cyrilmorin** [etalab/transport-site#3907]
L'accès à l'espace réutilisateur en mode déconnecté peut reprendre le principe prévu pour l'espace producteur en proposant une page d'info rétuilisateur et en faire une page SAS du mode déconnecté.

### Pour l'espace producteur 
La page info n'est pas une page SAS et il faudrait modifier le comportement actuel lors de la tentative d'accès l'espace producteur en mode déconnecté :
Actuellement elle renvoie sur la page de connection avec bandeau bleu
![image](https://github.com/etalab/transport-site/assets/116101828/544c2f6f-95fa-4728-8342-a843d06eb204)

=> Rediriger vers [infos_producteurs](https://transport.data.gouv.fr/infos_producteurs) qui ajoute une plus value dans le fait d'expliquer le concept même s'il y a un écran de plus pour se connecter.

### Pour l'espace réutilisateur 
Il faudrait donc 
- Créer  une page info qui permet d'accéder à l'espace en mode connecté ou invite à s'identifier en mode déconnecté. 
- Ajouter la brique de la feature "Gérez vos notifications qui est déjà disponible (voir ultérieurement pour les autres briques et textes complémenatires)

Exemple :
1-**En mode déconnecté "Identifiez vous"**

 ![image](https://github.com/etalab/transport-site/assets/116101828/94cd43b2-3ad1-4dc1-ac47-cfc038b1bcac)

2- **En mode connecté "Accédez à l'espace producteur"**
![image](https://github.com/etalab/transport-site/assets/116101828/13e59119-b8ab-41e1-97e6-d2b5243c8bbf)

**Comment by AntoineAugusti** [comment]
@cyrilmorin Faut-il ajouter cette page dans le menu et à quel emplacement ?

**Comment by AntoineAugusti** [comment]
Répondu https://github.com/etalab/transport-site/pull/3916#issuecomment-2106933661, la réponse est oui

**Comment by ptitfred** [comment]
Qu'entend-on par "page SAS" ?

**Comment by cyrilmorin** [comment]
@ptitfred sorry page SAS (comme décompression) ce doit être un vieux jargon utilisé dans des vies antérieures ... 
Je voulais dire une page "intermédiaire" qui permet d'informer (message urgent imposé ou info générale) ou de faire un sommaire d'accès aux features (plutôt que via des onglets/menus ...)
