### ISSUE TITLE
Gestion de l'affichage et des interactions des coeurs de suivi de datasets

### ISSUE THREAD

**Issue by cyrilmorin** [etalab/transport-site#3908]
En préambule il faut préciser qu'une page de BO user (réutilisateur et plus tard producteur) par dataset sera disponible pour la gestion des services "par dataset" (à l'image du BO du PAN)

_En mode déconnecté :_
Le cœur (suivi des favoris) n’est jamais affiché

_En mode connecté :_ 

### Pour les producteurs : 
Les producteurs ne peuvent pas suivre leurs jeux de données car ils ont des services quasi similaires ou spécifiques dans leur espace producteur. Il faudrait par conséquent :
1- Ajouter un cœur bleu pour tous les datasets qui sont publiés par ses différentes organisations (un utilisateur peut appartenir à plusieurs organisations).
2- Le cœur n’est pas activable sur la page de recherche d’un dataset 
3- Sur la page du dataset, au passage de la souris sur le cœur bleu, ajouter info bulle « Gérez votre jeu de données ! » 
4- Au clic sur le cœur bleu, on renvoie vers l'espace producteur (pas de page BO par dataset pour les producteurs à ce stade)

### Pour tous : 
**Affichage des cœurs**
Le cœur noir (non suivi), rouge (suivi) ou bleu (producteur) est affiché sur tous les datasets
_A créer pour l’affichage du cœur sur les briques de la page de recherche d’un dataset_

Page recherche 
![image](https://github.com/etalab/transport-site/assets/116101828/7dd633b2-e615-4466-9ea9-1a81a2419a26)

Page dataset
![image](https://github.com/etalab/transport-site/assets/116101828/db180fb4-5ac1-48af-82fd-260f666e80dc)

**Lorsque le cœur est noir** 

- Le cœur n’est pas activable sur la page de recherche d’un dataset 
- Sur la page du dataset, au passage de la souris sur le cœur noir, ajouter info bulle « Suivre ce jeu de données ! » 
- Le cœur devient rouge au clic (uniquement sur la page du dataset) pour permettre un action rapide d’ajout de favori.
          + Affichage d'un message d’invitation à découvrir son espace
![image](https://github.com/etalab/transport-site/assets/116101828/7319de90-4730-487c-91f4-5cb73845b657)
          + Ajout auto de toutes les notifications liées au dataset

**Lorsque le cœur est rouge (dataset déjà suivi)**
- Le cœur n’est pas activable sur la page de recherche d’un dataset 
- Sur la page du dataset, au passage de la souris sur le cœur rouge, ajouter info bulle « Gérez les services liés à ce jeu de données ! » 
- Pour éviter de supprimer toutes les configurations déjà réalisées sur le dataset en question, le clic sur le cœur rouge ne supprime pas les notifications mais renvoie vers la page BO du dataset (Page BO du dataset à créer). Cette page permettra de modifier ou supprimer le suivi du dataset de manière non consciente.

**Comment by cyrilmorin** [comment]
Yo

**Mode déconnecté**
Merci pour ce rappel qui nous permet de voir que notre réflexion évolue au fil du temps et plus on rentre dans le détail :)
C'est presque plus le fonctionnement actuel de la gestion de l'espace producteur qui m'a fait un peu changé de position, mais je te propose qu'on en reparle ensemble pour trouver une solution simple et efficace.

**Wording**
A 100% d'accord avec toi il faut qu'on définisse 1 unique terme dans l'idéal et le terme "favori" semble objectivement plus facile à intégrer pour les user et les échanges futurs (support, doc ...). On essaie de refaire un passe pour voir où on a des mentions différentes.

**Espace réutilisation > page dataset**
Oui je vais faire un ticket : il faut qu'on se pose et échange, cette page sera la plus structurante à mon sens une fois qu'on aura plusieurs "services" à proposer.

**Terme backoffice**
Effectivement on pourra employer "backoffice" pour l'espace Admin + "backoffice/dataset" (user équipe PAN) et parler d'espace réutilisateur avec espace_réutilisateur (accueil) + espace_réutilisateur/dataset pour les pages de configuration des services personnels et des users standards. La page par dataset n'étant qu'une sous section de l'espace réutilisateur/producteur

**Comment by AntoineAugusti** [comment]
L'implémentation a été réalisée dans #3917 (partie résultats de recherche) et #3918 (partie `dataset#details`), je te laisserai vérifier que ça correspond bien !

On peut discuter du mode déconnecté ensemble si tu souhaites des modifications.

**Comment by AntoineAugusti** [comment]
On va discuter du mode déconnecté et ensuite ce ticket sera terminé.

**Comment by AntoineAugusti** [comment]
En mode non connecté : pas d'infobulle comme actuellement, clic bannière apparait, modifier vers infos réutilisateur dans un nouvel onglet.
