### ISSUE TITLE
Proposition modification light Accueil PAN pour intégration "Espaces user"

### ISSUE THREAD

**Issue by cyrilmorin** [etalab/transport-site#3914]
Voici quelques propositions à discuter pour modifier quelque peu l'accueil de PAN et surtout intégrer et mettre en avant les nouvelles fonctionnalités liées à l'espace réutilisateur : 

### Onglets du PAN 

1. Ajouter le menu « Espace réutilisateur » sous « Espace producteur » depuis le menu personnel
2. Supprimer l’onglet « Info producteur » pour homogénéiser les accès « users »
3. De manière général, l’usage semble être de proposer l’accès aux « Espaces utilisateurs » en cliquant sur son nom de compte. Toutefois on pourrait ajouter un v ou > (ou autre astuce) après le nom de user pour inviter à déplier le menu au rollover ?

 
### _Hors espace réutilisateur_ - Profiter de cette modification pour : 

1. Ajouter un onglet « Cartes » à la place d'"Infos producteurs" avec les pages ci-dessous et les enlever de l’onglet « Outils »
- [Carte d'exploration](https://transport.data.gouv.fr/explore) 
- [Carte nationale des arrêts GTFS](https://transport.data.gouv.fr/explore/gtfs-stops)

2. Ajouter un onglet "Statistiques" même si la page est actuellement partiellement aboutie et à revoir et renvoyer vers https://transport.data.gouv.fr/stats

### Contenu de la page Accueil
Page à repenser pour mettre en avant les « Espaces users » et nos outils dont notamment le « Validateur » l’outil star !
Propositions relativement rapides à réaliser en attendant un plus gros chantier de refonte : 

1-	Redimensionner/reconfigurer la brique supérieure de l’écran pour caser l’accès rapide aux 3 features "[Espaces réutilisateurs](https://github.com/etalab/transport-site/issues/3907)" , Espace producteur "[Info producteur](https://transport.data.gouv.fr/infos_producteurs)" et "[Outils de validation](https://transport.data.gouv.fr/validation)".
Brique supérieure de l'écran
![image](https://github.com/etalab/transport-site/assets/116101828/869353a9-6b8b-45fe-9da8-a2812e0e87ef)

OU

2-	Supprimer les accès rapides ci-dessous sous "Vous pouvez également" pour mettre à la place les 3 features ci-dessus :

- « Voir jeux de données récents » => peu d’utilités et encore moins d’utilité avec les notifs sur nouveaux dataset référencés (ce sont 2 propositions concurrentes plus qu’alternatives)
- Utiliser nos API => l’usage semble être d’y avoir accès depuis le footer ou plus bas dans la page
- Onglet statistique disponible dans le menu (cf ci-dessus)

A discuter !!

**Comment by AntoineAugusti** [comment]
@cyrilmorin Comme discuté ensemble, je te laisse en discuter avec @etalab/transport-bizdev pour avoir une vue d'ensemble et arbitrer entre le menu/les icônes sous la barre de recherche sur l'accueil

**Comment by cyrilmorin** [comment]
@AntoineAugusti : Ajustements envisagés 

**Onglets du PAN** :
1- Ajouter en  1ère position : "Données" avec comme sous-menus :
- "Toutes les données" qui renvoie vers la page [datasets](https://transport.data.gouv.fr/datasets)
- "Carte d'exploration"
- "Carte nationale des arrêts GTFS"
2- Supprimer "Info producteur"
3- Ajouter un onglet "Statistiques" qui renvoie vers https://transport.data.gouv.fr/stats entre "Outils" et "Reglementation" 

**Quick access** :

1. Remplacer l'icone "Rechercher sur la carte" par "Valider ses données" avec une icone genre "Check vert (et croix rouge ?)" ou "Tampon conformité" ou "certificat" ...  ou une meilleure idée !!! 

2. Ajouter 2 "gros boutons" sous le texte de gauche (Rassembler les données ....)
- "Espace producteur" en bleu qui redirige vers https://transport.data.gouv.fr/espace_producteur
- "Espace réutilisateur" en vert qui redirige vers https://transport.data.gouv.fr/espace_reutilisateur

On en reparle ;)

**Comment by AurelienC** [comment]
En lien avec https://github.com/etalab/transport-site/issues/3566
