### ISSUE TITLE
Ajouter lien "espace_user" sur la page dataset

### ISSUE THREAD

**Issue by cyrilmorin** [etalab/transport-site#3923]
### Ajout d'un lien "espace_réutilisateur" sur la page dataset
Ajouter quel que soit le mode (connecté/déconnecté) un lien « espace réutilisateur » sous le titre, à l’image de « backoffice » pour les admin du PAN.

Pour cette 1ère étape, l’objectif est de proposer des interactions simples via ce lien (nous pourrons ajuster et/ou améliorer plus tard)

- En mode déconnecté => redirection dans un nouvel onglet vers la page [info_reutilisateurs](https://transport.data.gouv.fr/infos_reutilisateurs).
- En mode connecté + dataset pas en favori => redirection dans un nouvel onglet vers l’accueil de l’[espace_réutilisateur](https://transport.data.gouv.fr/espace_reutilisateur).
- En mode connecté + dataset en favori => redirection dans un nouvel onglet vers la page espace_réutilisateur/dataset (à créer).

### Ajout d'un lien "espace_producteur" sur la page dataset
Afficher le lien uniquement si les conditions ci-dessous sont respectées 

1. L'utilisateur est connecté 
2. L'utilisateur est producteur du dataset en question (appartient à l'Organisation qui publie le dataset)

Le lien renvoie vers la page [espace_producteur](https://transport.data.gouv.fr/espace_producteur) (la page par dataset n'existe pas à ce stade et n'est pas prévue rapidement)

NB : Pour les producteurs : pouvoir accéder uniquement au lien espace_producteur sur leur dataset (ils sont réutilisateurs lambda sur les autres datasets)

**Comment by AntoineAugusti** [comment]
@cyrilmorin Pour les membres du PAN, quel est le fonctionnement attendu ? Lien vers le backoffice tout le temps et masquer "espace réutilisateur" ou "espace producteur" selon le JDD ?

**Comment by cyrilmorin** [comment]
@AntoineAugusti yes absolutely  !
pour tout te dire, je l'avais spécifié au début et enlevé après en me disant que pour le lien backoffice il n'ya avait pas de changement et que de toute manière on ne pouvait pas accéder à l'espace producteur des "autres" producteurs :)
