### ISSUE TITLE
Lien vers brique "Autocars longue distance" renvoie vers erreur 500

### ISSUE THREAD

**Issue by cyrilmorin** [etalab/transport-site#3926]
Salut,

Le lien de la brique en page d'accueil "[Autocars longue distance](https://transport.data.gouv.fr/datasets/region/14?modes%5B%5D=bus)" renvoie vers une erreur 500
![image](https://github.com/etalab/transport-site/assets/116101828/372e2595-5959-477e-bb0c-b16a6837fb9f)

**Comment by AntoineAugusti** [comment]
[Remonté par Brewenn récemment](https://mattermost.incubateur.net/betagouv/pl/xfyqh9n5afyxigwgy1yuqotpoh). Voir #3301 cc @thbar

**Comment by cyrilmorin** [comment]
ok je ferme du coup
