### ISSUE TITLE
Historiser resource.datagouv_id dans resource_history et dataset_history_resources

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#3932]
`resource.datagouv_id` n'est pas stocké lors de l'historisation d'une ressource ou dans l'historique quotidien des ressources composant un jeu de données.

Cet identifiant est la clé primaire côté data.gouv.fr et est donc très utile en cas de jointures ou d'investigations.

Prévoir d'ajouter ceci.

cc @thbar avec qui on en a discuté

**Comment by ptitfred** [comment]
Il existe déjà [un champ datagouv_id sur resource_history](https://github.com/etalab/transport-site/blob/master/apps/transport/lib/db/resource_history.ex#L11) (not null dans le schéma SQL). Ai-je loupé une subtilité en lisant le code ?

**Comment by AntoineAugusti** [comment]
> Ai-je loupé une subtilité en lisant le code ?

Non, c'est moi. Je pense que j'avais requêté dans `resource_history.payload` qui contient un tas d'attributs en oubliant cette colonne.
