### ISSUE TITLE
Ajout de nouveaux types sur les JDD / covoiturage

### ISSUE THREAD

**Issue by AurelienC** [etalab/transport-site#3955]
Afin de pouvoir référencer de nouveaux types de jeux de données, nous avons besoin d'ajouter des valeurs dans le champ "type" sur les datasets.

Valeurs à ajouter :
- `carpooling-lines` → "Lignes de covoiturage" (FR) / "Carpooling lines" (EN)
- `carpooling-offers` → "Offres de covoiturage" (FR) / "Carpooling offers" (EN)

Le format reste à définir mais il semblerait qu'ils seront ceux-ci :
- `carpooling-lines` → GTFS (extension Flex)
- `carpooling-offers` → API

L'ajout d'une tuile sur la page d'accueil et dans les filtres de la recherche n'est pas primordial pour l'instant, mais peuvent être prévu ou réalisé dès maintenant pour les deux nouveaux types si cela simplifie le travail.

Concernant les icônes à associer, savez-vous si nous avons une banque dans laquelle piocher ?

Il me semble avoir fournis les informations nécessaires mais à votre disposition s'il en manque :-)

**Comment by AntoineAugusti** [comment]
@ptitfred Ça te de faire ceci ? On peut en parler tous les deux.

**Comment by AntoineAugusti** [comment]
@AurelienC Avec ces ajouts on aurait 3 catégories : `carpooling-areas`, `carpooling-lines` et `carpooling-offers`. La spécialisation est-elle justifiée ?

Tu peux aussi rédiger le texte de présentation de la catégorie en EN/FR ([exemple](https://transport.data.gouv.fr/datasets?type=carpooling-areas))

**Comment by AntoineAugusti** [comment]
Je me mets comme je m'en occupe avec @AurelienC

**Comment by ptitfred** [comment]
> Je me mets comme je m'en occupe avec @AurelienC

farpait, je n'avais pas du tout commencé à regarder

**Comment by AurelienC** [comment]
# Textes de description
## carpooling-areas
*Si possible de l'intégrer dans cette issue, sinon j'en ferai une autre*
**FR**
> Les jeux de données de cette catégorie décrivent les lieux de covoiturage en France.
>
> Ces données respectent le [schéma national des aires de covoiturage](https://schema.data.gouv.fr/etalab/schema-lieux-covoiturage/).
>
> Une [base nationale des lieux de covoiturage (BNLC)](https://transport.data.gouv.fr/datasets/base-nationale-des-lieux-de-covoiturage) est disponible. Elle respecte le schéma et est mise à jour par l’équipe du point national à partir des données conformes publiées sur data.gouv.fr.

**EN**
> The datasets in this category describe carpooling areas in France.
>
> These data comply with the [national schema for carpooling areas](https://schema.data.gouv.fr/etalab/schema-lieux-covoiturage/).
>
> A [national database](https://transport.data.gouv.fr/datasets/base-nationale-des-lieux-de-covoiturage) is available. It complies with the scheme and is updated by the NAP team using compliant data published on data.gouv.fr.

## carpooling-lines
**FR**
> Les jeux de données de cette catégorie décrivent les lignes de covoiturage en France.

**EN**
> The datasets in this category describe carpooling lines in France.

## carpooling-offers
**FR**
> Les jeux de données de cette catégorie décrivent les offres de covoiturage planifiées du quotidien en France.
>
> Les données respectent le [standard-covoiturage](https://github.com/fabmob/standard-covoiturage/).

**EN**
> The datasets in this category describe daily scheduled carpooling offers in France.
>
> These data comply with the [standard-covoiturage](https://github.com/fabmob/standard-covoiturage/).

# Ordre des tuiles
...
low-emission-zones
**carpooling-areas**
**carpooling-lines**
**carpooling-offers**
chargin-stations
...

# Icônes
## carpooling-areas
*Si possible de l'intégrer dans cette issue, sinon j'en ferai une autre*
![carpooling-areas](https://github.com/etalab/transport-site/assets/4528670/039dcd8f-2150-4ca1-a500-37dae003b8f8)

## carpooling-lines
![carpooling-lines](https://github.com/etalab/transport-site/assets/4528670/b7c31369-259a-4e7a-b770-f08a95a84826)

## carpooling-offers
![carpooling-offers](https://github.com/etalab/transport-site/assets/4528670/0d9a0a33-05af-45f2-bd79-c78f6311adce)

**Comment by ptitfred** [comment]
@AurelienC je te laisse juger si c'est bon à fermer désormais

**Comment by AntoineAugusti** [comment]
@AurelienC C'est fait automatiquement dès qu'un JDD est référencé dans ces catégories 😄
