### ISSUE TITLE
Accès aux données référencées pour 1 organisation

### ISSUE THREAD

**Issue by cyrilmorin** [etalab/transport-site#3957]
Hello,

Il serait utile de pouvoir avoir accès à toutes les données référencées sur le PAN par une organisation. 
=> Ajouter un lien qui permette d'avoir accès à la page dataset filtrée par l'organisation recherchée.
![image](https://github.com/etalab/transport-site/assets/116101828/86721002-48b8-4a5c-a2e0-85182fdb41e9)

**A l'image du lien** 
par _type de données_ 
![image](https://github.com/etalab/transport-site/assets/116101828/97d7e892-766b-49bf-b1e1-945128c4baa3)

par _organisation (sur datagouv)_
![image](https://github.com/etalab/transport-site/assets/116101828/6b820dfd-569d-49ec-9338-321dcaacb40c)

Merci !

**Comment by AntoineAugusti** [comment]
@thbar Semble être lié/à traiter dans le refactor de la recherche ? https://github.com/etalab/transport-site/issues/3640 cc @thbar @AurelienC

**Comment by thbar** [comment]
@AntoineAugusti oui ça sera bien dedans, toutefois une mitigation court terme pourrait être étudiée.

@cyrilmorin est-ce que ça vaut le coup (j'ai tendance à dire oui) d'intégrer ça sans attendre la refonte du site (DSFR / recherche v2 / accessibilité) ?

**Comment by cyrilmorin** [comment]
@thbar si possible oui, cela ne semble par trop gros (je vous laisse me dire si ça l'est en fait !) et finalement très utile "au quotidien" !
Merci :)

**Comment by thbar** [comment]
Merci @cyrilmorin, voir #3999 pour l'implémentation !
