### ISSUE TITLE
Référencement données compagnie aérienne Finist'Air dans agrégat Bretagne

### ISSUE THREAD

**Issue by Brewennn** [etalab/transport-site#3958]
Dans le jeu de données agrégées des services urbains et interurbains de la région Bretagne, il y a les services Finist'Air (compagnie aérienne régionale qui font du service conventionné) : https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-transports-publics-en-bretagne-korrigo-gtfs. Pouvez-vous référencer les données également dans la catégorie transport aérien ?

**Comment by AntoineAugusti** [comment]
@Brewennn Salut Brewenn, on ne peut référencer que des jeux de données existants sur le PAN (dont il y a une fiche sur data.gouv.fr / portail open data).

Voir avec la région Bretagne pour extraire ces données de l'agrégat et en faire un JDD dédié ?

**Comment by Brewennn** [comment]
Je ne comprends pas les données agrégées pour la région Bretagne existantes sur data.gouv : https://www.data.gouv.fr/fr/datasets/base-de-donnees-multimodale-transports-publics-en-bretagne-korrigo-gtfs/ et référencées sur le PAN. Le jeu apparaît dans la catégorie TC, données ferroviaires, données maritimes. Il pourrait apparaitre dans la catégorie aérien ? Après on peut leur demander d'extraire les données aériennes comme pour le TER et le fluvial en plus de la publication agrégée.

**Comment by AntoineAugusti** [comment]
@Brewennn Ah je comprends ta demande. Actuellement ce n'est pas modélisé comme ça, on pourrait mettre le sujet sur la table ! Pour ferroviaire et maritime on a le même type de données (`public-transit` dans notre backoffice) et on construit ces catégories en inspectant les modes présents dans les données GTFS pour les regrouper dans une tuile, dans une logique de mettre en avant.

Pour les données aériennes actuellement on en a fait un type (`air-transport` dans le backoffice) et pas (`public-transit` avec le mode `air` dans les données, extrait automatiquement), à voir entre bizdevs @etalab/transport-bizdev.

Les données pour la région Bretagne sont mal modélisées pour le moment pour Finist'Air, j'ai [posé la question](https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-transports-publics-en-bretagne-korrigo-gtfs#dataset-discussions). Tu peux chercher `air` sur notre moteur de recherche pour voir [les données qui contiennent ça](https://transport.data.gouv.fr/datasets?modes%5B%5D=air) (0 pour le moment).

**Comment by AntoineAugusti** [comment]
Discuté [sur Mattermost](https://mattermost.incubateur.net/betagouv/pl/oowwaocb5jf5jmrh6yi5jitxco) ensuite. On reste avec le fonctionnement actuel pour le moment. La région Bretagne a été contactée pour tenter d'avoir un JDD aérien à part.
