### ISSUE TITLE
Historiser le nombre de lignes de la consolidation IRVE dans stats_history

### ISSUE THREAD

**Issue by vdegove** [etalab/transport-site#3963]
On voudrait avoir un historique du nombre de lignes dans le fichier.

**Comment by thbar** [comment]
On a eu besoin de cette information assez souvent, c'est vraiment rentable je pense de l'intégrer quelque part.

Idéalement metabase-compatible, mais aussi affichable sur le site (rapports).

**Comment by AntoineAugusti** [comment]
[Plusieurs jobs](https://github.com/etalab/transport-site/tree/master/apps/transport/lib/jobs/geo_data) écrivent des données dans `geo_data`.

Peut-être adapter [`StatsHandler`](https://github.com/etalab/transport-site/blob/master/apps/transport/lib/transport/stats_handler.ex) pour requêter ces données et écrire la bonne `(clé, valeur)` ?

**Comment by thbar** [comment]
Voir aussi le nettoyage réalisé ici (qui impacte positivement `geo_data`):
- https://github.com/etalab/transport-site/issues/3860#issuecomment-2042771989

**Comment by thbar** [comment]
Suggestion (redite de Mattermost): faire en sorte d'avoir un nommage assez agnostique (du type "row_count" et référençant peut-être l'id de ressource directement), comme ça on pourrait faire des analyses un peu systématiques à terme.

**Comment by thbar** [comment]
@vdegove ça pourrait être namespacé ou un peu comme suit: `row_count:resource:118` (différent de ce qui se fait actuellement, mais similaire à ce qui se fait ailleurs dans l'application)

**Comment by vdegove** [comment]
Ok, je réfléchis et je vous propose un truc alors (je suis en train de travailler dessus, c’était mon petit bonbon de la journée).
