### ISSUE TITLE
Erreur importation jeu de données data.gouv.fr

### ISSUE THREAD

**Issue by Brewennn** [etalab/transport-site#3976]
Bonjour, 

La CC de Corse du Sud à rajouté son jeu GTFS à celui de son GTFS-RT sur data.gouv : https://www.data.gouv.fr/fr/datasets/reseau-a-citadina-porto-vecchio-horaires-theoriques-et-temps-reel/

Toutefois, la mise à jour ne se fait pas sur transport.data.gouv : https://transport.data.gouv.fr/datasets/reseau-a-citadina-porto-vecchio-horaires-theoriques-et-temps-reel et lorsque je clique sur "importer" dans le back office, l'erreur suivante apparaît comme si l'application ne comprenait pas qu'il s'agit d'une mise à jour et non d'un ajout de jeu de données : 

Impossible d'importer le jeu de données (%MatchError{term: {:error, "%{resources: [%{}, %{id: [\"has already been taken\"]}]}"}})

**Comment by ptitfred** [comment]
Voir https://github.com/etalab/transport-site/issues/3656

**Comment by Brewennn** [comment]
J'ai fait le test de mon côté et ça fonctionne c'est top, merci Fred !

**Comment by ptitfred** [comment]
Le fix a été revert.

**Comment by ptitfred** [comment]
Nouvelle tentative: https://github.com/etalab/transport-site/pull/4077
