### ISSUE TITLE
How to use apps/transport/lib/transport/gtfs_diff.ex?

### ISSUE THREAD

**Issue by dancesWithCycles** [etalab/transport-site#3981]
Hi folks,
Thank you so much for providing and maintaining this repository.

I randomly stumbled over this [readme file](https://github.com/MobilityData/gtfs_diff/blob/main/README.md) that leaded me to this [source file](https://github.com/etalab/transport-site/blob/b6bdd7749192e52bccb9ecbb33e436b56c9fd693/apps/transport/lib/transport/gtfs_diff.ex).

It is the first time I come across Elixir. Do you mind providing an instruction set that describes how to use the GTFS Diff tool from scratch imagining a clear Linux operating system environment?

Example:

* prepare Elixir
```
cd
apt install curl git
git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.14.0

orThis issue is linked to [this issue](https://github.com/etalab/transport-site/issues/3981).



git clone https://aur.archlinux.org/asdf-vm.git && cd asdf-vm && makepkg -si
```

Add the following to ~/.bashrc:
```shell

. "$HOME/.asdf/asdf.sh"
```

Completions must be configured by adding the following to your .bashrc:
```shell

. "$HOME/.asdf/completions/asdf.bash"
```

* install plugins
```
asdf plugin-add erlang (https://github.com/asdf-vm/asdf-erlang)
asdf plugin-add elixir
```

* get repo
```
cd
git clone git@github.com:etalab/transport-site.git
cd transport-site
```

* run Elixir tool
```
mix cmd --app  apps/transport/lib/transport/gtfs_diff.ex
```

This issue is linked to [this issue](https://github.com/MobilityData/gtfs_diff/issues/7).

Cheers!

**Comment by thbar** [comment]
Hi @dancesWithCycles! Thanks for the issue :smile:

> It is the first time I come across Elixir. Do you mind providing an instruction set that describes how to use the GTFS Diff tool from scratch imagining a clear Linux operating system environment?

I would need to verify my understanding: are you asking for help on the tool, or you do not need help and instead are suggesting an improvement on the documentation?

Thanks!

**Comment by dancesWithCycles** [comment]
Hi @thbar ,
Thx for asking for clarification. Indeed, I am asking for both. An extension to the documentation with the instruction set to install the dependencies and use the tool in a clean Linux (e.g. GNU/Debian) environment would help me to run the GTFS Diff tool. But it also would help others that miss a running Elixir environment on hand. Of course, a more complete documentation would help everyone.

Cheers!

**Comment by thbar** [comment]
Thanks for the clarification @dancesWithCycles!

After a long day, coming back with some points: one must note that the current implementation of GTFS-Diff does not scale well (this is why there is a 10MB limit on https://transport.data.gouv.fr/tools/gtfs_diff).

This means we are not going to put a lot of effort in the documentation (it will likely change if we optimise the algorithm later).

I will see if I can tweak things in a few lines to make things work from a script, and provide guidance here (because `mix cmd --app  apps/transport/lib/transport/gtfs_diff.ex` will not work currently unless I'm mistaken).

I'll keep that issue opened for now, thanks for your patience.

**Comment by thbar** [comment]
@dancesWithCycles thanks for the delay. Our bandwidth is too tight to properly manage that, so I will have to close the issue for now. Sorry about that, as we manage a lot of topics!
