### ISSUE TITLE
Retour UX sur [Retirer des favoris]

### ISSUE THREAD

**Issue by cyrilmorin** [etalab/transport-site#3983]
Hello @AntoineAugusti 

Mon retour rapide UX sur [Retirer des favoris](https://github.com/etalab/transport-site/pull/3968) 

1- Renommer "Retirer de vos favoris" par "Supprimer de vos favoris" sur les écrans mentionnant l'action

2- Tu me confirmes que le page [https://transport.data.gouv.fr/espace_reutilisateur/datasets/xxx#](https://transport.data.gouv.fr/espace_reutilisateur/datasets/xxx) est bien la page de gestion des différentes fonctionnalités de l'espace réutilisateur par dataset ? On rajoutera dans le futur les fonctionnalités : Notification, Discussion, Partage des données modifiées ... ?

Si oui, je redirigerai la brique vers la page "espace_reutilisateur/datasets/xxx" au lieu de la page dataset, comme vu précédemment. Cette page contient donc actuellement uniquement la fonctionnalité "Supprimer de vos favoris"

3- Je supprimerai le bouton Edit et rajouterai un quick access avec un logo de corbeille (assez explicite et commun) qui renvoie directement sur la popup de confirmation de suppression du favori. Info bulle sur corbeille "Supprimer de vos favoris".
![image](https://github.com/etalab/transport-site/assets/116101828/77d5ecca-4be2-4b20-9192-800c8cd2454e)

4- Proposition de texte de warning pour la suppression de favoris "Attention, vous allez supprimer le jeu de données [Nom du dataset] de la liste de vos favoris. Vous allez perdre tous les paramétrages ou actions que vous avez réalisées précédemment sur ce jeu de données."

On en parle !!!

Merci :)

**Comment by AntoineAugusti** [comment]
- Ajout icône flèche pour ouvrir le JDD dans un nouvel onglet
- Renommer bouton "Éditer" vers "Gérer le favori"
- Page détails : bloc notification à coder bientôt, "Repartage des données améliorées", "Discussions".
- Bouton "Supprimer des favoris" en haut à droite + icône corbeille
