### ISSUE TITLE
Notifications "commentaires" souci ergo mineur

### ISSUE THREAD

**Issue by cyrilmorin** [etalab/transport-site#3989]
Hello,

Je viens d'identifier une souci mineur sur le 2nd datasets sur la notif réutilisateur sur les commentaires.
En effet dans le corp du mail la 2nde ressource est sur un niveau de puce différent.
![image](https://github.com/etalab/transport-site/assets/116101828/a498a752-7ecb-47bd-8e28-76d74f8d7649)

**Comment by AntoineAugusti** [comment]
Merci.

Peux-tu partager le code HTML de cet e-mail ?

> In Microsoft Outlook, double-click to open an email. You'll see an “Actions” menu under the “Message” tab. Click on that menu and select the “Other Actions,” then click on “View Source” to see the HTML code.

Ou quelque chose de similaire.

**Comment by cyrilmorin** [comment]
Je t'ai rajouté à l'email de Front !

<p>
Bonjour,</p>
<p>
Des discussions ont eu lieu sur certains jeux de données que vous suivez. Vous pouvez prendre connaissance de ces échanges.</p>
<p>
</p>
<ul>
  <li>
<a href="https://mailjet-link-tracking.transport.data.gouv.fr/lnk/EAAABaVJM64AAAAAAAAAASqWiDsAAAAARUgAAAAAABGtEwBmaAQSvteEmusPSo27xYz8PFv1MgARuyQ/1/6rsBOjnjBPKDHrwwCO-bOw/aHR0cHM6Ly90cmFuc3BvcnQuZGF0YS5nb3V2LmZyL2RhdGFzZXRzL2JyZWl6aGdvLWNhciNkYXRhc2V0LWRpc2N1c3Npb25z#dataset-discussions">Réseau interurbain BreizhGo Car</a>
</p>
<ul>
  <li>
<a href="https://mailjet-link-tracking.transport.data.gouv.fr/lnk/EAAABaVJM64AAAAAAAAAASqWiDsAAAAARUgAAAAAABGtEwBmaAQSvteEmusPSo27xYz8PFv1MgARuyQ/2/fpMg2Y5nJyhZnuoY6HXKLw/aHR0cHM6Ly90cmFuc3BvcnQuZGF0YS5nb3V2LmZyL2RhdGFzZXRzL2JyZWl6aGdvLWJhdGVhdXgjZGF0YXNldC1kaXNjdXNzaW9ucw#dataset-discussions">Réseau interurbain BreizhGo Bateaux</a>
  </li>
</ul>
<p>
L’équipe transport.data.gouv.fr</p>

<br/><img src="https://mailjet-link-tracking.transport.data.gouv.fr/oo/EAAABaVJM64AAAAAAAAAASqWiDsAAAAARUgAAAAAABGtEwBmaAQSvteEmusPSo27xYz8PFv1MgARuyQ/4871d08c/e.gif" height="1" width="1" alt="" border="0" style="height:1px;width:1px;border:0;"/>

**Comment by AntoineAugusti** [comment]
[E-mail concerné dans Front](https://app.frontapp.com/open/cnv_18i1spzq?key=dmmLnBT5XS3Uy-dvwa7BjjRlOaSwEi-K)

**Comment by cyrilmorin** [comment]
<p>
Bonjour,</p>
<p>
Des discussions ont eu lieu sur certains jeux de données que vous suivez. Vous pouvez prendre connaissance de ces échanges.</p>
<p>
</p>
<ul>
  <li>
<a href="https://mailjet-link-tracking.transport.data.gouv.fr/lnk/EAAABaVJM64AAAAAAAAAASqWiDsAAAAARUgAAAAAABGtEwBmaAQSvteEmusPSo27xYz8PFv1MgARuyQ/1/6rsBOjnjBPKDHrwwCO-bOw/aHR0cHM6Ly90cmFuc3BvcnQuZGF0YS5nb3V2LmZyL2RhdGFzZXRzL2JyZWl6aGdvLWNhciNkYXRhc2V0LWRpc2N1c3Npb25z#dataset-discussions">Réseau interurbain BreizhGo Car</a>
</p>
<ul>
  <li>
<a href="https://mailjet-link-tracking.transport.data.gouv.fr/lnk/EAAABaVJM64AAAAAAAAAASqWiDsAAAAARUgAAAAAABGtEwBmaAQSvteEmusPSo27xYz8PFv1MgARuyQ/2/fpMg2Y5nJyhZnuoY6HXKLw/aHR0cHM6Ly90cmFuc3BvcnQuZGF0YS5nb3V2LmZyL2RhdGFzZXRzL2JyZWl6aGdvLWJhdGVhdXgjZGF0YXNldC1kaXNjdXNzaW9ucw#dataset-discussions">Réseau interurbain BreizhGo Bateaux</a>
  </li>
</ul>
<p>
L’équipe transport.data.gouv.fr</p>

<br/><img src="https://mailjet-link-tracking.transport.data.gouv.fr/oo/EAAABaVJM64AAAAAAAAAASqWiDsAAAAARUgAAAAAABGtEwBmaAQSvteEmusPSo27xYz8PFv1MgARuyQ/4871d08c/e.gif" height="1" width="1" alt="" border="0" style="height:1px;width:1px;border:0;"/>

**Comment by AntoineAugusti** [comment]
@ptitfred Serais-tu intéressé par ce ticket ?

Visiblement le Markdown to HTML sur ce template/ligne https://github.com/etalab/transport-site/blob/9ecf35543bd1aa836981d4dd2d2630c8126081a4/apps/transport/lib/transport_web/templates/email/new_comments_reuser.html.md?plain=1#L6 se déroule mal. Voir si en changeant un peu le Markdown ça passe, ou mettre directement des balises HTML dans le template ?

Voir pour adapter le test aussi, montrer qu'on ne met pas plusieurs `<ul></ul>`.

Je t'ai déjà suggéré de travailler sur plusieurs tickets 🐛 dernièrement. Dis-moi si tu veux que je m'en charge.

**Comment by ptitfred** [comment]
J'avais jeté un œil rapide ce matin des fois que ça me saute aux yeux mais pas trouvé. Je vais étendre les tests et fixer le template.

**Comment by AntoineAugusti** [comment]
Ça peut être un bug de `phoenix_markdown` https://github.com/etalab/transport-site/blob/9ecf35543bd1aa836981d4dd2d2630c8126081a4/apps/transport/mix.exs#L66 ou de l'usage qu'on en fait.

Me semble que j'avais déjà eu des problèmes dans le passé avec des listes dans les e-mails en Markdown, que j'étais passé en HTML ensuite.

Là en regardant le template Markdown le markup me semble bon et ne devrait pas produire ce résultat.
