### ISSUE TITLE
Notifications : ajustements interface dans le backoffice

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#4009]
Avec l'arrivée de notifications à destination des réutilisateurs, nous allons avoir une volumétrie plus importante à destination des réutilisateurs (plus nombreux que les producteurs) et les interfaces existantes font l'hypothèse que les notifications sont uniquement adressées à des producteurs.

Prévoir d'effectuer quelques ajustements pour garder une clarté dans le BO et afficher des informations d'activité concernant les réutilisateurs.

- [Page JDD](https://transport.data.gouv.fr/backoffice/datasets/614/edit)
  - afficher uniquement les abonnements des producteurs + récap nombre d'abonnements et nombre de contacts réutilisateurs (idée du volume)
  - afficher uniquement les notifications envoyées aux producteurs `notifications.role = :producer` https://github.com/etalab/transport-site/pull/4000
  - pour les notifications reasons permettant d'abonner un producteur, vérifier que ce n'est pas une liste hardcodée sinon utiliser les helpers dans `DB.NotificationSubscription`
- [Page de contact](https://transport.data.gouv.fr/backoffice/contacts/206/edit)
  - afficher les notifications envoyées `notifications.contact_id` https://github.com/etalab/transport-site/pull/4000
  - expliciter que l'abonnement à des notifications depuis cette page ne se fait que pour `role = producer` ⚠️ (ou offrir la possibilité d'abonner en tant que réutilisateur, mais les motifs sont différents…)

**Comment by ptitfred** [comment]
> * pour les notifications reasons permettant d'abonner un producteur, vérifier que ce n'est pas une liste hardcodée sinon utiliser les helpers dans `DB.NotificationSubscription`

Autant que je puisse en juger et si j'ai bien compris cet énoncé, c'est déjà fait en appelant `DB.NotificationSubscription.subscribable_reasons_related_to_datasets(:producer)` dans `backoffice/page/form_dataset.html.heex`.

**Comment by AntoineAugusti** [comment]
#4000 a été mergé donc le reste des tâches est désormais réalisable comme les colonnes existent désormais

**Comment by AntoineAugusti** [comment]
@ptitfred Je prends la suite de ce ticket pour que tu puisses te concentrer sur l'intégration du validateur NeTEx ?
