### ISSUE TITLE
Carte exploration : ZFE difficilement visibles

### ISSUE THREAD

**Issue by cyrilmorin** [etalab/transport-site#4012]
Sur la carte d'exploration le contraste des zones ZFE n'est pas OK et on distingue difficilement les zones lorsque le zoom est sur la France.
=> foncer la couleur pour qu'elle soit plus visible
![image](https://github.com/etalab/transport-site/assets/116101828/40e74ebf-8974-4d1a-8220-51a1ccfd5a55)

La couleur de la zone n'a d'ailleurs pas l'air d'être la même que celle de la case
![image](https://github.com/etalab/transport-site/assets/116101828/f2662363-9fed-4e13-9e88-880e216aef7e)

**Comment by AntoineAugusti** [comment]
Bug découvert à cette occassion https://github.com/etalab/transport-site/issues/4027
