### ISSUE TITLE
Erreur 500 quand organization_id est nil

### ISSUE THREAD

**Issue by cyrilmorin** [etalab/transport-site#4017]
Hello,

Le dataset [Réseau urbain Intercom](https://transport.data.gouv.fr/datasets/horaires-du-reseau-de-bus-intercom-2) renvoie vers une erreur 500

Merci :)

**Comment by vdegove** [comment]
https://transport-data-gouv-fr.sentry.io/issues/5528852013/?environment=prod&project=6197733&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=14d&stream_index=3

**Comment by cyrilmorin** [comment]
pour info c'est un jeu avec un "Auteur" au lieu d'une "Organisation", le producteur devait modifié .... je le relance

**Comment by vdegove** [comment]
Effectivement, les champs organization, organization_id et organization_type de ce dataset sont vides en base de donnée :

![image](https://github.com/etalab/transport-site/assets/15861435/5a99746b-f866-4dd0-96e9-2dda4535b83d)

Ce qui plante sur cette fonction :

```elixir
  defp assign_is_producer(
         %Plug.Conn{assigns: %{current_contact: current_contact}} = conn,
         %DB.Dataset{organization_id: organization_id}
       ) do
    is_producer =
      if is_nil(current_contact) do
        false
      else
        DB.Contact.base_query()
        |> join(:inner, [contact: c], c in assoc(c, :organizations), as: :organization)
        |> where([contact: c, organization: o], c.id == ^current_contact.id and o.id == ^organization_id)
        |> DB.Repo.exists?()
      end

    assign(conn, :is_producer, is_producer)
  end
  ```

Mais si ça n’avait pas planté ici, ça aurait planté ailleurs, c’est pas normal qu’on laisse importer de la mauvaise donnée comme ça, je crée une issue.

**Comment by vdegove** [comment]
(@cyrilmorin que dis-tu de supprimer le JDD pour l’instant ?)

**Comment by cyrilmorin** [comment]
Je viens de renvoyer ce matin le message et j'avais alerté à maintes reprises le producteur.
Ce jeu n'aurait jamais d'être référencé initialement je te rejoins (il l'était depuis un moment je crois !) 

Je le déréférence de ce pas !

**Comment by cyrilmorin** [comment]
@vdegove pour info en vérifiant il y a un autre dataset sans Organisation et il est en erreur 500 également 
https://transport.data.gouv.fr/datasets/reseau-de-transport-routier-national-metropolitain

**Comment by vdegove** [comment]
Clos en faveur de #4018

**Comment by AntoineAugusti** [comment]
Étant donné que ceci affecte l'affichage de plusieurs JDDs et que #4018 + la migration des quelques JDDs concernés ne sera pas immédiate je propose de corriger le bug.

Je pense que c'est moi qui ait écrit le code problématique, j'avais conscience que `organization_id` pouvait être `nil` mais visiblement je me suis fait surprendre.
