### ISSUE TITLE
Empêcher d’importer des jeux de donnée sans organisation

### ISSUE THREAD

**Issue by vdegove** [etalab/transport-site#4018]
On a un plantage ici https://github.com/etalab/transport-site/issues/4017 qui est dû au fait qu’un JDD était rattaché à un « auteur » sans organisation.

Ça plante dans `dataset_controller.ex`, mais si ça ne plantait pas là, ça aurait planté ailleurs, tout le code part du principe qu’il y a une organisation rattachée à un jeu de données.

Il faudrait :
- Avoir un changeset sur dataset qui oblige à avoir un organization_id et organization
- Vérifier si on a bien un message d’erreur à l’import en cas «d’auteur» (voir avec @cyrilmorin pour en créer un).

**Comment by cyrilmorin** [comment]
[issue ](https://github.com/etalab/transport-site/issues/4019) créée !

**Comment by AntoineAugusti** [comment]
Le test ajouté dans #4025 sera à retirer quand ce ticket aura été traité + les JDDs existants retirés ou migrés vers une organisation

**Comment by AntoineAugusti** [comment]
@cyrilmorin Il n'y a plus qu'un JDD référencé chez nous qui n'est pas rattaché à une organisation, [Réseau de transport routier national métropolitain](https://transport.data.gouv.fr/datasets/342) (regarde en navigation privée, il y a un bug actuellement).

On peut le déréférencer au profit d'un autre ? Peut-être que le JDD IGN "Route 500" est suffisant ?

En retirant le dernier JDD on pourra interdire le référencement + mettre en place d'autres contraintes.

**Comment by cyrilmorin** [comment]
@AntoineAugusti OK merci.
Plutôt OK pour le déréférencer (dernière màj en 2019 ...). Il restera de toute façon disponible sur datagouv pour les réutilisateurs actuels mais pas d'intérêt de le mettre en avant de notre côté.
cc @etalab/transport-bizdev 
![image](https://github.com/user-attachments/assets/6c963ee1-77bf-46e2-b75c-b1803530ca6a)

Je déréférence
