### ISSUE TITLE
Dataset Tudbus NeTEx OK mais pas le GTFS

### ISSUE THREAD

**Issue by cyrilmorin** [etalab/transport-site#4020]
Dans datagouv le dataset [Tudbus ](https://www.data.gouv.fr/fr/datasets/tudbus-douarnenez-communaute-transport/)contient bien le GTFS (avec dans la description Fichier GTFS) et le Netex mais sur le PAN le dataset [Tudbus ](https://transport.data.gouv.fr/datasets/tudbus-douarnenez-communaute-transport) ne contient pas le GTFS et je ne comprends pas trop pourquoi (Netex OK)

![image](https://github.com/etalab/transport-site/assets/116101828/efe981b0-015d-4efb-ad00-a011b5c4555a)

![image](https://github.com/etalab/transport-site/assets/116101828/1ef7ec17-7e27-48fe-adcf-c5610b8d2f81)

**Comment by AntoineAugusti** [comment]
Je viens de regarder notre code et leurs ressources.

Pour les GTFS, on ne regarde pas l'URL pour trouver le mot clé `GTFS` car on peut avoir une confusion avec `gtfs-rt` (qui contient `gtfs`).

La logique complète est là

https://github.com/etalab/transport-site/blob/eca78acc21b7e7df85ed5ee7e6414213e513a686/apps/transport/lib/transport/import_data.ex#L495-L506

Leur fichier n'est pas détecté car le format de la ressource n'est pas top et _surtout_ ils ont une typo dans la description, voir ta capture d'écran ce qui est surligné. `GFTS` au lieu de `GTFS`. Peuvent-ils modifier ? Ça devrait être bon ensuite.

**Comment by cyrilmorin** [comment]
@AntoineAugusti  bien ouéj, j'avais pas vu le GFTS ...
Je les préviens !

**Comment by cyrilmorin** [comment]
@AntoineAugusti pour info, c'est modifié et dorénavant OK !
