### ISSUE TITLE
UX : Système de pagination sur page dataset perturbant

### ISSUE THREAD

**Issue by cyrilmorin** [etalab/transport-site#4023]
La pagination sur la page [dataset ](https://transport.data.gouv.fr/datasets?type=public-transit&page=1) pose problème car on pense parfois avoir tout vu (à tort) à cause des n° de pages situés tout en bas de l'écran alors que le nb de cards est limité à 10

![image](https://github.com/etalab/transport-site/assets/116101828/1cedd508-d0c1-4dea-bf52-8c1d3a5781ab)

Propositions : 
1- Supprimer les système de pagination (en ne chargeant les briques que lorsque l'on scroll vers le bas ?)
2- Augmenter le nombre de briques à 20 (voire proposer les options de nombres de briques à charger (ex : 10, 20, 50))
3- Afficher le nombre de page en haut et en bas de la liste

Faites au mieux :)

Merci,

Cyril

**Comment by vdegove** [comment]
Est-ce que simplement remonter la liste des pages t’irait ? Comme ça :
![image](https://github.com/etalab/transport-site/assets/15861435/b3138c07-027d-42cb-b2a5-d61156262221)

**Comment by cyrilmorin** [comment]
Hello @vdegove ,
Oui j'y a avais pensé en mode quick win, ce serait déjà mieux :)
On pourrait à minima augmenter le nb de dataset à 20 si ce n'impacte pas les perf ?

Sinon OK pour moi !

**Comment by vdegove** [comment]
Alors, j’ai fait le 1er (changer l’emplacement du bloc de pagination), je suis sur le 2ème (changer le nombre d’items renvoyés).

Le problème c’est que le PAN a une config unique pour la pagination, qui vaut pour tous les endroits où on _pagine des trucs_. Changer à 20 items le changerait sur tous les endroits suivants :
- Liste de datasets (recherche)
- Liste de contacts dans le backoffice
- Liste de datasets dans le backoffice
- Liste d’erreurs sur la page de détail d’une resource
- Liste d’erreurs sur la page spécifique de validation (je sais même plus si ce template est vraiment utilisé, ahah)

T’es ok avec ça ?

Exemple, ici 

![image](https://github.com/etalab/transport-site/assets/15861435/6c0a592e-68e7-4914-a250-0a510b652d6d)

Du peu que j’ai pu tester, ça n’affecte pas la performance, mais c’est du test manuel, je ne suis pas outillé pour ça.

**Comment by AntoineAugusti** [comment]
> Le problème c’est que le PAN a une config unique pour la pagination, qui vaut pour tous les endroits où on pagine des trucs.

On peut adapter notre code existante pour que Scrivener, l'outil de pagination, ait une configuration différente selon l'usage je pense. À voir si c'est OK de passer à 20 partout.

**Comment by cyrilmorin** [comment]
@vdegove je trouve que cela apporte un plus également pour les autres pages concernées.
Dans le même esprit, si on a une liste à rallonge, on a toujours intérêt à voir un peu plus d'item pour chaque liste

=> Banco !
