### ISSUE TITLE
UX Modifier le libellé pour la mise à jour du logo

### ISSUE THREAD

**Issue by cyrilmorin** [etalab/transport-site#4033]
Le bouton "Edit" qui permet de modifier le logo du dataset depuis l'espace producteur n'est pas très explicite.
Comme pour le moment c'est la seule feature et qu'il faudra repenser l'espace producteur suite à la création de l'espace réutilisateur je propose de
=> Modifier "Edit" en "Changer l'image" 

![image](https://github.com/etalab/transport-site/assets/116101828/3fb81111-c231-4726-9b7c-ace04493211e)

**Comment by Brewennn** [comment]
Je suis d'accord pour ta proposition. Est-ce qu'il est possible de changer de traiter cet issue d'ici la semaine prochaine pour que je mette à jour la capture d'écran dans la Newsletter svp ?

**Comment by AntoineAugusti** [comment]
#4053 propose une page d'édition avec les ressources et le logo, on ne va donc pas faire ce quick fix.

**Comment by Brewennn** [comment]
C'est ok pour moi.
