### ISSUE TITLE
Bandeau d'informations pour annoncer la fin de la BNLS et Parc Relais

### ISSUE THREAD

**Issue by Brewennn** [etalab/transport-site#4043]
Je vous propose de rajouter un bandeau en rouge sur la page d'accueil des données sur le stationnement hors voirie (https://transport.data.gouv.fr/datasets?type=private-parking) et sur les JDD de la BNLS (https://transport.data.gouv.fr/datasets/base-nationale-des-lieux-de-stationnement) et des parcs relais (https://transport.data.gouv.fr/datasets/base-nationale-des-parkings-relais-experimentation) afin d'indiquer que la base ne sera pas maintenu. Je pense qu'on peut laisser la base des Parking relais. 

En message pourrait être le suivant : "En raison de la publication du Profil France Parkings de la norme NeTEX disponible sur normes.transport.data.gouv.fr, les base nationales des lieux de stationnements hors voirie et des parcs relais seront supprimées le 1er septembre 2024". On peut discuter dans Github du contenu du message.

**Comment by AntoineAugusti** [comment]
@Brewennn Le texte parait bien 👌 Peux-tu proposer une version en anglais aussi ? Le PAN est toujours en FR + EN.

**Comment by Brewennn** [comment]
Top ok je prépare ça.

**Comment by Brewennn** [comment]
et je n'oublie pas de préparer une autre issue pour le bandeau lié à la licence mobilité je m'en occupe demain.

**Comment by Brewennn** [comment]
En français : "En raison de la publication du Profil France Parkings de la norme NeTEX, disponible sur normes.transport.data.gouv.fr, les base nationales des lieux de stationnements hors voirie et des parcs relais seront supprimées le 1er septembre 2024".

En anglais : "Due to the release of the French profile “Parkings” applicable to NeTEx, available on normes.transport.data.gouv.fr, the national datasets related to car parks and park-and-ride will be deleted the September 1st 2024."

**Comment by Brewennn** [comment]
@AntoineAugusti, je propose de garder que la première phrase du texte introductif : "Les données concernant le stationnement hors-voirie en France sont produites par différentes collectivités et gestionnaires de parking." et ajouter le bandeau au dessus (https://mattermost.incubateur.net/betagouv/pl/g5z66oezmtnxfp3ypzsj5c8juw)

**Comment by thbar** [comment]
@Brewennn la PR va passer en production sous peu ; on fait un email à Tu-Tho et aussi au GT9 pour prévenir qu'on a retenu cette posture si ça te va ?

**Comment by Brewennn** [comment]
Pour moi, c'est ok pour les PR dont je comprends le code. Ok @thbar pour faire un mail à Tu-Tho et Thierry ça permettra de rajouter un petit coup de pression pour la publication en NeTEX.

**Comment by thbar** [comment]
@Brewennn ça marche je m'en charge, je leur enverrai les urls des deux pages quand ça sera déployé.

**Comment by AntoineAugusti** [comment]
C'est en production https://transport.data.gouv.fr/datasets?type=private-parking

**Comment by thbar** [comment]
Relais de Thierry du GT9:

> - N'est ce pas prématuré, ne faut il pas informer au minimum tous ceux qui ont publié sur ces bases et laisser le temps de migrer vers Netex avant de dé-publier des bases existantes ?
> - Avez vous prévu une migration (traduction) des bases existantes pour aider ceux qui ont fait l'effort de publier sur ces bases ?

Point à affiner en point d'équipe. Je ne connais pas l'état de qualité ni de fraîcheur de ces deux bases, ni leur taux actuel de réutilisabilité non plus.

**Comment by thbar** [comment]
Rollback car délai trop court, il faut donner un peu + de mou.
