### ISSUE TITLE
Lien Typeform dans la Newsletter

### ISSUE THREAD

**Issue by Brewennn** [etalab/transport-site#4045]
On avait reçu un mail de Maxime nous informant que le lien pour évaluer transport.data.gouv.fr sur une échelle de 1 à 10 dans la Newsletter d'avril était obsolète : 
https://app.frontapp.com/inboxes/teammates/folders/20651926/archived/97450015510/search/workspace/with%3Asiret%40google.com/95660158422?around=348054554390.

Peut-on mettre à jour cette fonctionnalité si c'est utile ou faut-il l'enlever de le Newletter ?

**Comment by ptitfred** [comment]
J'ai lu trop vite en m'assignant, je pensais qu'il fallait mettre à jour un lien dans un template.

**Comment by Brewennn** [comment]
Ce n'est pas grave, pour l'instant le lien typeform je vais l'enlever tant que personne ne peut sait pas comment le mettre à jour (il existe peut être un compte pour ça ?)

**Comment by AntoineAugusti** [comment]
@Brewennn Je ne pense pas qu'on ait un accès à ce compte. Tu peux tenter un reset de mot de passe en utilisant l'adresse contact@transport.beta.gouv.fr ou contact@transport.data.gouv.fr.

À voir si on souhaite toujours avoir un outil comme typeform en bas de notre newsletter pour noter le contenu ou pas.

**Comment by Brewennn** [comment]
@AntoineAugusti, le mail de renouvellement de mot de passe n'est pas arrivé dans la boite contact (voir discussion [Mattermost](https://mattermost.incubateur.net/betagouv/pl/wa8gtyy4t78mbgazpytiognwhh)). Etant donné que le sondage est supprimé de la newsletter, on peut laisser comme ça et le compte sera désactivé au bout d'un moment.
