### ISSUE TITLE
Ajout bandeau "authentification" pour JDD de Lyon Métropole

### ISSUE THREAD

**Issue by Brewennn** [etalab/transport-site#4051]
Salut @AntoineAugusti et @cyrilmorin,

A la suite des échanges à propos des données de Lyon Métropole mises à disposition sous la Licence Mobilités [(https://mattermost.incubateur.net/betagouv/pl/friuortqstrx7c8rajzj6yzx5y)](), je vous propose ce projet de bandeau pour indiquer qu'une authentification est nécessaire pour accéder aux JDD et que le PAN ne peut proposer de validation des jeux.

Ce bandeau pourrait être affiché uniquement pour le JDD de Lyon et non pour celui d'IDFM dont l'accès est ouvert. Cela signifierait à mon sens de créer un nouveau tag en backoffice en plus du tag Licence mobilité (ça complique un peu mais ça me semble jouable car je ne pense pas qu'il y ait beaucoup d'AOM qui choisissent cette licence). Toutefois, ça permettrait de laisser la main au biz dev d'indiquer eux-mêmes les JDD au lieu de créer un ticket et peut être se donner la liberté de référencer d'autres jeux nécessitant une authentification si une autre licence est utilisée (je ne suis pas pour mais on ne sait jamais). 

**Les messages seraient les suivants :** 

FR : "Le producteur de données demande une authentification pour accéder au jeu de données. Pour cette raison, transport.data.gouv.fr ne peut ni mettre à disposition ce jeu ni afficher le rapport de validation. Pour réutiliser le jeu de données, nous vous invitons à vous connecter sur la plateforme opendata du producteur". 

EN : "The producer requests an authentification to access to the dataset. That's the reason why transport.data.gouv.fr can provide neither the dataset nor the validation report. Thus, we invite you to connect to the producer's opendata to use it."

**Si j'essaye de traduire ça sur une partie du code** (attention, je débute et je n'ai pas pris tous les scripts concernés): 

En lien avec la PR #3604, le script dans apps/transport/lib/transport_web/live/backoffice/custom_tags_live.ex pourrait intégrer à la fin : 

**defp tags_documentation do**

    [
      %{name: "licence-mobilités", doc: "Applique la licence mobilités pour ce jeu de données"},
      %{
        name: "loi-climat-resilience",
        doc:
          "Ce jeu de données est soumis à l'obligation de réutilisation selon l'article 122 de la loi climat et résilience"
      },
      %{name: "requestor_ref:<valeur>", doc: "Renseigne le requestor_ref des ressources SIRI pour ce jeu de données"},
      %{name: "saisonnier", doc: "Indique sur la page du JDD que ce jeu de données n'opère qu'une partie de l'année"},
      %{name: "skip_history", doc: "Désactive l'historisation des ressources pour ce jeu de données"}
      %{name: "skip_history", doc: "Désactive l'historisation des ressources pour ce jeu de données"},
      %{
        name: "keep_netex_conversions",
        doc:
          "Conserve les conversions NeTEx automatiques pour ce jeu de données, même s'il contient des ressources NeTEx"
      }
       %{name: "authentification", 
       doc: 
          "Indique sur la page du JDD que ce jeu nécessite une authentification sur l'opendata du producteur"},
    ]

 
En lien avec la PR  #3482, le script apps/transport/lib/transport_web/live/backoffice/custom_tags_live.ex pourrait intégrer : 

  **<div class="dataset-infos">**

    <section>
      <p :if={authentification_warning?(@dataset)} class="notification">
        ℹ️ <%= dgettext(
          "page-dataset-details",
          "The producer requests an authentification to access to the dataset. That's the reason why transport.data.gouv.fr can provide neither theses datasets nor the validation report. Thus, we invite you to connect to the producer's opendata to use it."
        ) %>
      </p>
      <div class="panel">
        <%= description(@dataset) %>
      </div>

**Comment by cyrilmorin** [comment]
Hello @Brewennn OK pour moi pour l'ajout d'un tag pour ce bandeau. c'est un cas spécifique que l'on doit traiter

**Comment by Brewennn** [comment]
@cyrilmorin, par contre es-tu d'accord pour l'ajout d'un tag spécifique ? Là j'avoue que je ne sais pas trop quelle option choisir entre ce tag, associer le bandeau avec le tag 'licence-mobilité' ou juste ajouter le bandeau en lien avec le datagouv_id associé à Lyon Métropole

**Comment by cyrilmorin** [comment]
@Brewennn oui ça me semble aussi une bonne idée de créer un tag spécifique sur le sujet car on pourra potentiellement retrouvé ce cas de figure hors Licence mobilité. Je pense notamment à certains "services/API"

**Comment by AntoineAugusti** [comment]
Très bien, je vous tiens au courant pour quand ce sera prêt à review ou disponible.

**Comment by Brewennn** [comment]
@AntoineAugusti. En lien avec #4052 que l'on peut clôturer, je propose d'ajuster le message (changement en gras) : 

FR : "Le producteur de données demande une authentification pour accéder au jeu de données. Pour cette raison, transport.data.gouv.fr ne peut ni mettre à disposition ce jeu ni afficher le rapport de validation. **Pour connaître la disponibilité de ce jeu et le réutiliser**, nous vous invitons à vous connecter sur la plateforme opendata du producteur".

EN : "The producer requests an authentification to access to the dataset. That's the reason why transport.data.gouv.fr can provide neither the dataset nor the validation report. Thus, we invite you to connect to the producer's opendata to **check its avaibility and** use it."

**Comment by AntoineAugusti** [comment]
@Brewennn J'avais rédigé autre chose avant ton dernier commentaire. Tu pourras voir dans la PR le texte retenu en FR + EN ainsi que le code nécessaire à la modification. Sympa d'avoir fait l'effort d'essayer de savoir ce qu'il fallait modifier 😃

**Comment by Brewennn** [comment]
J'essaye de m'imprégner du code pour comprendre comment tout ça fonctionne. Pour le coup, je n'ai pas proposé les modifications sur l'ensemble des scripts car ça allait faire beaucoup de texte dans l'issue ou faire des PR pour ne pas perturber le fonctionnement. Je pense que j'aurai pas mal de questions aux développeurs la prochaine fois qu'on se verra tous pour bien comprendre le fonctionnement.

**Comment by AntoineAugusti** [comment]
[C'est en prod](https://mattermost.incubateur.net/betagouv/pl/kcbt5yjq3ig1texgs6ey4qs3to)

@Brewennn n'hésite pas à poser toutes les questions que tu souhaites !
