### ISSUE TITLE
Suppression de l'affichage "indisponibilité" pour le JDD de Lyon Métropole

### ISSUE THREAD

**Issue by Brewennn** [etalab/transport-site#4052]
Re salut @AntoineAugusti et @cyrilmorin,

En lien avec l'issue #4051 relative aux données de Lyon Métropole, je vous propose de ne pas afficher ni sur la page du JDD ni dans l'API que le jeu de données est indisponible, ou à l'inverse on affiche que c'est disponible par défaut. Etant donné qu'il y aura le bandeau pour indiquer que l'information sur ces jeux n'est pas disponible, on laisse les réutilisateurs se connecter sur l'open data de Lyon pour qu'ils se fassent une idée. 

Si c'est ok, je me demande comment l'indiquer dans la partie "resources" dans l'API pour le champ 'is_availabe :'  est-ce qu'on le met en 'True' par défaut ou change-t-on la nature de ce champ en format text pour indiquer un attribut "Not_communicated" en plus de "False" et "True" ? Je pense que la première solution serait plus simple.

**Comment by cyrilmorin** [comment]
Hello @Brewenn,

Je suis un peu embêté philosophiquement pour afficher une ressource comme "Disponible" alors qu'on ne le sait pas. Notre bandeau est un plus mais a objectivement moins d'impact et d'utilité que nos api/stats/score/monitoring/notifications ... qui seraient tous impactés.
En plus il se peut qu'on ait d'autres publications soumises à authentification qu'on afficherait Indisponible j'imagine (?)

@AntoineAugusti de manière générale, suite à notre tentative d'accès au fichier/service soumis à authentification, est-ce qu'on a un retour différencié du système requêté genre Erreur 403 Forbidden ?
Si oui ça pourrait être bien d'avoir un statut intermédiaire genre "Unknown" effectivement entre True et False.

@Brewennn Je préfère ta version 2 :) mais je laisse @AntoineAugusti nous préciser la complexité !

Dispo pour en parler

**Comment by AntoineAugusti** [comment]
> En plus il se peut qu'on ait d'autres publications soumises à authentification qu'on afficherait Indisponible j'imagine (?)

Je serais pour pouvoir contrôler ce comportement à l'aide d'un tag pour ne pas faire de la métropole de Lyon un cas spécial. Ceci peut être fait par le biais de https://github.com/etalab/transport-site/issues/4051 qui permet d'indiquer qu'une authentification est nécessaire pour accéder aux données.

> Je suis un peu embêté philosophiquement pour afficher une ressource comme "Disponible" alors qu'on ne le sait pas

Je suis plus réservé, comme @cyrilmorin, sur le fait de donner un passe-droit sur la disponibilité des données quand une authentification est en place. Sans s'être authentifié et avoir tenté de télécharger on ne connaît pas l'état de disponibilité des données. Accorder un ✅ me parait un peu précipité.

Ne pas avoir téléchargé la donnée a plus d'impacts que l'état de disponibilité, [quand on regarde une page de JDD](https://transport.data.gouv.fr/datasets/horaires-theoriques-du-service-rhonexpress-de-la-metropole-de-lyon-et-du-departement-du-rhone), on constate que :
- ressources affichées comme indisponibles
- scores de disponibilité à 0 partout
- informations de période de validité du calendrier erronées
- ressources historisées incohérentes (plusieurs versions ont été publiées mais on ne les a pas)

Je me demande donc quel degré d'adaptation nous souhaitons faire.
- un bandeau expliquant que ces fonctionnalités sont indisponibles à cause de l'authentification uniquement #4051 et laisser les autres fonctionnalités en l'état dégradé
- une adaptation en profondeur (il faudra tout spécifier et adapter alors, en plus de l'indisponibilité)
- se plier à l'authentification et accéder aux données en étant authentifié ("acceptation" de la licence mobilité et nécessité de gérer des identifiants pour plusieurs JDDs)

**Comment by Brewennn** [comment]
@AntoineAugusti et @cyrilmorin,

L'objectif est bien de faire le strict minimum pour Lyon et juste enlever la notion "indisponible" qui tend à induire les utilisateurs en erreur car même avec le bandeau, on pourrait croire que le jeu n'est pas disponible ni sur le PAN ni sur l'open data de Lyon Métropole. Au regard de ce que vous avez dit, j'y vois deux solutions : 

- Soit indiquer une notion "Inconnue" pour la disponibilité mais c'est un peu plus technique. 
- Soit laisser la notion "Indisponible" et préciser dans le texte du bandeau (#4051) que le jeu est indisponible sur transport.data.gouv et inciter les utilisateurs à aller sur l'open data de Lyon Métropole. 

J'opte pour la seconde solution plus simple.

**Comment by cyrilmorin** [comment]
Pour un quick win 2nde option également de mon côté !

**Comment by Brewennn** [comment]
Dans ce cas on peut clôturer cet issue.

**Comment by AntoineAugusti** [comment]
#4051 est adapté pour pouvoir traiter ce ticket
