### ISSUE TITLE
Erreur sur import jdd Aix-Marseille

### ISSUE THREAD

**Issue by cyrilmorin** [etalab/transport-site#4057]
Hello,

J'ai tenté d'importer via le bouton "Importer" dans le BO le dataset [Aix ](https://transport.data.gouv.fr/datasets/reseaux-de-transports-en-commun-de-la-metropole-daix-marseille-provence-et-des-bouches-du-rhone) mais j'ai eu l'erreur ci-dessous :

Impossible d'importer le jeu de données (%Ecto.MultipleResultsError{message: "expected at most one result but got 2 in query:\n\nfrom r0 in DB.Resource,\n left_join: d1 in DB.Dataset,\n on: r0.dataset_id == d1.id,\n where: r0.datagouv_id == ^\"e8a86701-6359-45de-bee5-95e648ec04e3\" or\n (r0.datagouv_id not in ^[\n \"50573d16-eeec-492a-a5d3-c14a036368c9\",\n \"304e9bce-2f14-417f-a02e-3b3827de8d5f\",\n \"e8a86701-6359-45de-bee5-95e648ec04e3\",\n \"7eef6ec9-9ebb-44f2-becb-2efc522522d6\",\n \"3fc0ab9d-e7a3-4728-ac2b-be55d927e757\",\n \"42b6ba26-f817-455b-8ba2-fa30c100fff4\",\n \"d61403a1-7694-4a04-a229-044a43aff5c7\",\n \"2bbfc260-c908-4242-9796-c30cb36511ea\",\n \"05c200aa-798d-4660-bae7-3bf77e551c4c\",\n \"c671fcc9-fe50-4bee-bed0-78e6443c1010\",\n \"cde22673-d7e4-4cbd-837f-3c8bd9fb2f9b\",\n \"2316529b-3075-4013-8b85-46777fefd56e\",\n \"ab931edc-0bc1-4c66-960a-dc546b46df03\",\n \"10e025a1-9048-4c19-925a-466b2a79232f\",\n \"9b44cd04-63b5-46e7-a1f8-d5c1c9151d5a\"\n ] and\n r0.url ==\n ^\"https://app.mecatran.com/utw/ws/gtfsfeed/static/mamp-uly?apiKey=0940631b6473164b4a1c136a2828324e6f3f3c08\"),\n where: d1.datagouv_id == ^\"5b3b3de988ee38708ada1789\",\n select: map(r0, [:id])\n"})

![image](https://github.com/etalab/transport-site/assets/116101828/924d9550-b613-4f15-bd58-1bbf6897775b)

**Comment by cyrilmorin** [comment]
en complément https://app.frontapp.com/inboxes/teammates/15533974/assigned/snoozed/97533335894

**Comment by AntoineAugusti** [comment]
@ptitfred Pourras-tu regarder ce ticket à ton retour ? Ça peut être lié au changement introduit dans #3978.

La requête exécutée qui sort 2 résultats
```sql
select *
from dataset d
join resource r on r.dataset_id = d.id
where d.datagouv_id = '5b3b3de988ee38708ada1789'
and r.datagouv_id = 'e8a86701-6359-45de-bee5-95e648ec04e3' or (r.datagouv_id not in ('50573d16-eeec-492a-a5d3-c14a036368c9', '304e9bce-2f14-417f-a02e-3b3827de8d5f', 'e8a86701-6359-45de-bee5-95e648ec04e3', '7eef6ec9-9ebb-44f2-becb-2efc522522d6', '3fc0ab9d-e7a3-4728-ac2b-be55d927e757', '42b6ba26-f817-455b-8ba2-fa30c100fff4', 'd61403a1-7694-4a04-a229-044a43aff5c7', '2bbfc260-c908-4242-9796-c30cb36511ea', '05c200aa-798d-4660-bae7-3bf77e551c4c', 'c671fcc9-fe50-4bee-bed0-78e6443c1010', 'cde22673-d7e4-4cbd-837f-3c8bd9fb2f9b', '2316529b-3075-4013-8b85-46777fefd56e', 'ab931edc-0bc1-4c66-960a-dc546b46df03', '10e025a1-9048-4c19-925a-466b2a79232f', '9b44cd04-63b5-46e7-a1f8-d5c1c9151d5a') and r.url = 'https://app.mecatran.com/utw/ws/gtfsfeed/static/mamp-uly?apiKey=0940631b6473164b4a1c136a2828324e6f3f3c08')
```

**Comment by AntoineAugusti** [comment]
Une [autre sollicitation](https://app.frontapp.com/open/msg_28ke7tjq?key=FWBpyCB-0pOsRC8-6PvK641tJKx8EewN) de la métropole AMP pour connaitre un délai de résolution de ce problème

**Comment by AntoineAugusti** [comment]
@ptitfred a fait une correction rapide [en supprimant](https://mattermost.incubateur.net/betagouv/pl/ifboqdwfp7fbxnfpkohh6fai9a) une ressource qui posait problème en base de données.

Un correctif plus long terme est en cours.

Le producteur a été [tenu au courant](https://app.frontapp.com/open/msg_28lmpy8m?key=FWBpyCB-0pOsRC8-6PvK641tJKx8EewN).

**Comment by ptitfred** [comment]
J'ai un fix plus solide dans les tuyaux, retesté avec le dump de prod de la semaine passée.

J'ai de bonnes raisons d'espérer qu'on soit plus tranquille à l'avenir quand des refactorings sont fait dans les ressources côté data.gouv :crossed_fingers:
