### ISSUE TITLE
Attribution OpenStreetMap incomplète

### ISSUE THREAD

**Issue by Jean-BaptisteC** [etalab/transport-site#4074]
Bonjour,

L'attribution présente sur les fonds de plan pour chaque jeu de données est incomplète, l'hyperlien renvoi vers la page openstreetmap.org hors les règles de la licence indique que l'hyperlien de l'attribution doit rediriger vers la page suivante https://www.openstreetmap.org/copyright.

Merci

**Comment by AntoineAugusti** [comment]
Bonjour @Jean-BaptisteC, merci, on corrige ça rapidement !
