### ISSUE TITLE
"Liste des emails et notifications envoyées aux utilisateurs"

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#4075]
Demande de @agaronne via Mattermost (qui aura son utilité pour le reste de l'équipe):

> Est-ce que c'est possible de me sortir la liste des emails et notifs que vous envoyez aux users svp ?

Je crée un ticket pour qu'on attache les éléments ici, voire si on dégage une petite doc ou autre.

**Comment by AntoineAugusti** [comment]
J'ai répondu à @agarrone [sur Mattermost](https://mattermost.incubateur.net/betagouv/pl/u969xe6xgbdgzqffum4fmfph7a).

Le contenu des notifications est là https://github.com/etalab/transport-site/tree/master/apps/transport/lib/transport_web/templates/email et peut être complété ici https://github.com/etalab/transport-site/blob/master/apps/transport/lib/mailer/user_notifier.ex.

Les règles précises pour l'envoi de chaque notification sont dans les jobs de chaque motif de notification.
