### ISSUE TITLE
Erreur sur les flux proxy (sncf-*)

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#4076]
https://x.com/NicolasW_GRAOU/status/1815284728901066872

> Hello [@transportdatafr](https://x.com/transportdatafr) !
> Y'a, a priori, une erreur de proxy visiblement sur tous les flux GTFS-RT (par ex > [https://proxy.transport.data.gouv.fr/resource/sncf-ter-gtfs-rt-trip-updates](https://t.co/scJ1TnY2Lp) ) vous sauriez quand ça > pourrait être réparé ? Merci et bon courage !

**Comment by thbar** [comment]
Après avoir été voir dans https://transport.data.gouv.fr/backoffice/proxy-config, ça ne concerne que les flux SNCF.

**Comment by thbar** [comment]
Copies d'écran:

![CleanShot 2024-07-22 at 09 39 42@2x](https://github.com/user-attachments/assets/5ca33310-801f-4b26-9675-ada39147ab8f)


![CleanShot 2024-07-22 at 09 39 09@2x](https://github.com/user-attachments/assets/dab6a3d2-107b-4c1c-87f6-0eeaa30ffca8)

**Comment by thbar** [comment]
Ok en requérant le flux d'origine chez SNCF, on a déjà un Bad Gateway, donc le proxy relaye ça directement.

Je vais chercher à contacter SNCF.

**Comment by nicolaswurtz** [comment]
Ok super, merci beaucoup pour l'investigation !

**Comment by thbar** [comment]
Pour @etalab/transport-tech, voilà l'email que j'ai envoyé pour signaler le souci:

https://app.frontapp.com/inboxes/teammates/15551830/sent/d97ca6b784a68e00f612d38e64bb9fa7

**Comment by ptitfred** [comment]
> Pour @etalab/transport-tech, voilà l'email que j'ai envoyé pour signaler le souci:
> 
> https://app.frontapp.com/inboxes/teammates/15551830/sent/d97ca6b784a68e00f612d38e64bb9fa7

Je n'ai pas accès au message via ce lien.

**Comment by ptitfred** [comment]
> Oui, j’ai déjà eu le signalement par le PAN jeudi dernier, et j’ai mis un commentaire sur les 3 JDD concernés.
> 
> Effectivement, le problème vient de la source, nos endpoints renvoient cette erreur 502. Le ticket est bien ouvert depuis jeudi soir, et puis nous sommes tombés dans le WE (je n’ai pas d’astreinte auprès de lui pour ces flux opendata). J’espère que nous réglerons le pb dans la journée, sinon, je contacterai Antoine pour lui proposer de se connecter sur des endpoints de recettes en attendant la résolution.
> 
> Arnaud

**Comment by thbar** [comment]
(Problème identifié et déjà signalé à SNCF jeudi dernier - ah et je vois que @ptitfred a copié collé ici, ce que j'allais faire, parfait merci !!!)

**Comment by ptitfred** [comment]
Observé à 13:21: les 502 sont désormais des 404.

**Comment by ptitfred** [comment]
Observé à 16:09: retour des 502.

**Comment by ptitfred** [comment]
Observé à 13:49: rétablissement du service.

**Comment by ptitfred** [comment]
Frédéric 14:13:
> Je n'observe plus les erreurs. Peut-on considérer l'incident clos ?

Arnaud 14:20:
> Oui normalement. Je préfère néanmoins attendre encore quelques heures de fonctionnement avant de considérer clos le sujet. Je dois aussi vérifier quelques données métiers, notamment les versions de trip_id.

**Comment by AntoineAugusti** [comment]
@ptitfred Me semble que l'on peut clôturer. On n'a pas d'incident sur un composant chez nous et la SNCF suit le sujet avec attention en lien avec son prestataire.

On pourra ouvrir un autre ticket pour améliorer la lisibilité des choses : notre composant d'infrastructure fonctionne, le problème est chez le diffuseur source.

**Comment by ptitfred** [comment]
Incident est clos, Arnaud 16:16:
