### ISSUE TITLE
Erreur lors de changement d'URL avec la contrainte liée au ressources historisées (JDD Lille Métropole) 

### ISSUE THREAD

**Issue by Brewennn** [etalab/transport-site#4081]
Bonjour,

En voulant changer l'URL du JDD de Lille : https://transport.data.gouv.fr/datasets/localisation-des-arrets-ilevia-bus-metro-et-tram-gtfs-pictogrammes-du-reseau-ilevia, j'ai eu le message suivant : 

![image](https://github.com/user-attachments/assets/51b4f3fa-4dab-47a9-b328-027d3b288e2b)

L'ancien URL de data.gouv.fr n'est plus d'actualité car il correspond à des jeux archivés, d'où le remplacement de l'URL par https://www.data.gouv.fr/fr/datasets/localisation-des-arrets-ilevia-bus-metro-et-tram-gtfs-pictogrammes-du-reseau-ilevia-2/. 

En rapport avec cet issue clos #4061, je comprend qu'il serait nécessaire de supprimer les jeux historisés afin de contourner la règle de contrainte en effectuant la commande suivante avant de réimporter le jeu en indiquant le nouvel URL : 

delete from resource where dataset_id = 5

**Comment by AntoineAugusti** [comment]
@ptitfred Visiblement c'est une nouvelle occurence du problème vu précédemment https://github.com/etalab/transport-site/issues/4061#issuecomment-2236335201

Je n'avais pas trouvé la source, pour moi on doit bien supprimer resource + resource_metadata. Si jamais tu vois ce que j'ai raté 🙏

**Comment by Brewennn** [comment]
En attendant de trouver une solution pérenne, je peux déférencer le jeu et en créer un nouveau ?

**Comment by AntoineAugusti** [comment]
@Brewennn J'ai fait une opération manuelle pour permettre le changement.

J'ai supprimé la ressource GTFS-RT, qui supprime les lignes associées dans `resource_metadata`.

```sql
delete from resource where id = 79630;
```

J'ai changé la source du JDD pour https://www.data.gouv.fr/fr/datasets/gtfs-et-visualisation-du-reseau-ilevia-2/.

Le GTFS n'est pas détecté car il n'y a pas le mot clé dans le titre/format ou description de la ressource. La MEL devrait ajouter aussi le GTFS-RT https://proxy.transport.data.gouv.fr/resource/ilevia-lille-gtfs-rt pour le JDD.

**Comment by AntoineAugusti** [comment]
@ptitfred Comme discusté sur Mattermost, je suis preneur d'un second avis sur ce problème de remplacement de JDD source et avec une erreur de contrainte en BDD.

On peut en parler à l'oral à un moment si tu veux.

**Comment by Brewennn** [comment]
Merci @AntoineAugusti. Le lien avec le GTFS  et le GTFS-RT est celui-ci : https://www.data.gouv.fr/fr/datasets/localisation-des-arrets-ilevia-bus-metro-et-tram-gtfs-pictogrammes-du-reseau-ilevia-2/. J'ai remplacé l'URL et indiqué les bons formats dans data?gouv.fr, tout est en ordre pour l'instant. Le moissonnage n'aura pas comme effet de modifier le format sur data.gouv.fr ?

**Comment by AntoineAugusti** [comment]
> Le moissonnage n'aura pas comme effet de modifier le format sur data.gouv.fr ?

C'est possible que ceci écrase tes changements et crée un problème. Tu pourras vérifier demain ?

Si c'est un problème on avisera.

**Comment by Brewennn** [comment]
Demain je suis en congé. Je pourrai vérifier lundi.

**Comment by Brewennn** [comment]
Effectivement, je n'avais pas regardé. J'ai fait le test à nouveau et le problème est réglé : je n'ai plus de message d'erreur.
