### ISSUE TITLE
Infrastructure down

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#4108]
![CleanShot 2024-08-02 at 14 06 49@2x](https://github.com/user-attachments/assets/a88306ab-dfa5-4a5a-aa07-aebb8fdd5ce2)

**Comment by thbar** [comment]
Par ailleurs:

![CleanShot 2024-08-02 at 14 07 09@2x](https://github.com/user-attachments/assets/d3288f84-72da-41ba-83a2-1c99fa5f3935)

(il faudra faire un ticket dédié)

Je vais consulter l'état CleverCloud.

**Comment by thbar** [comment]
Major outage:

https://www.clevercloudstatus.com

![CleanShot 2024-08-02 at 14 09 44@2x](https://github.com/user-attachments/assets/47007ca4-77af-4930-8dcf-360cad26e786)

**Comment by AntoineAugusti** [comment]
Pour le changement des enregistrements DNS c'est déjà fait https://github.com/etalab/transport-site/pull/4086 #4089.

**Comment by thbar** [comment]
Je donne la main à Antoine qui est au boulot, je retourne en congés 😄

**Comment by AntoineAugusti** [comment]
Voir le [thread sur Mattermost](https://mattermost.incubateur.net/betagouv/pl/jgfxy43z7jfk9q9reofbpaertr) et [l'incident chez Clever Cloud](https://www.clevercloudstatus.com/incident/880).

Le site web principal est de retour depuis 14h40. Les autres : workers, staging, metabase étaient déjà en ligne peu avant.

**Comment by thbar** [comment]
Petite liste post-mortem de choses en vrac :
- [ ] vérifier qui dans @etalab/transport-tech est notifié par email
  - [ ] @ptitfred 
  - [ ] @AntoineAugusti 
  - [ ] @thbar 
  - [ ] @vdegove (sur la durée)
 - [ ] vérifier la durée du downtime: OK 2h via updown (Thibaut)
 - [ ] Reprioriser un peu de temps long terme sur une redondance partielle (par exemple, un déploiement sans DB redondée, permettrait de ne pas avoir de downtime sur le proxy, composant utilisé en direct sur le flux en temps réel des utilisateurs)

**Comment by thbar** [comment]
Avec:
- ajout de Frédéric et Antoine dans les destinataires emails
- partage de la doc
- prise de notes pour envisager de commencer à redonner "juste" le proxy dans le futur

ça clôture le dossier pour ce tour.
