### ISSUE TITLE
Homogénéisation des entêtes de page des catégories de données

### ISSUE THREAD

**Issue by Brewennn** [etalab/transport-site#4115]
Salut,

Petite demande d’harmonisation des entêtes de page pour chaque catégorie de données. Pour certaines pages, la mention "catégorie" est bien indiquée avec le nom de la catégorie concernée. Pour d'autres, on retrouve le terme "jeux de données" (voir image ci-dessous) ou "région - national" pour les [autocars longue distance](https://transport.data.gouv.fr/datasets/region/14?modes%5B%5D=bus).

Voici les catégories de données dont l'entête de page devrait être mis à jour : 

- [ ] [TC - temps réel](https://transport.data.gouv.fr/datasets?type=public-transit&filter=has_realtime) ;
- [ ] [Autocars longue distance](https://transport.data.gouv.fr/datasets/region/14?modes%5B%5D=bus) ;
- [ ] [Transport ferroviaire](https://transport.data.gouv.fr/datasets?modes%5B%5D=rail) ;
- [ ] [Transport maritime et fluvial](https://transport.data.gouv.fr/datasets?modes%5B%5D=ferry) ;
- [ ] Facultatif car ça devrait bientôt disparaître : [JOP 2024](https://transport.data.gouv.fr/datasets?custom_tag=paris2024).

![Présentation1](https://github.com/user-attachments/assets/a714bbfe-c568-4009-b640-85e3489f1586)

**Comment by AntoineAugusti** [comment]
Héhé, tu fais bien de le relever, ça fait depuis très longtemps que c'est comme ça et ce n'est pas immédiat à corriger !

**Comment by AntoineAugusti** [comment]
@Brewennn C'est en production
