### ISSUE TITLE
ResourceHistoryJob : revoir méthode pour détecter un ZIP

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#4120]
Le code en charge d'archiver les données statiques a pour le moment une heuristique très simple pour détecter qu'une ressource est un ZIP.

https://github.com/etalab/transport-site/blob/63a5e4850897cc9795520d05f2253d85ba07d885/apps/transport/lib/jobs/resource_history_job.ex#L236

Ceci ne semble pas approprié, les fichiers NeTEx pouvant être zippés ou non.

🐛 un fichier NeTEx non zippé n'est actuellement pas historisé/validé etc en conséquence. Ceci survient pour [Cheminements piétons dans Paris d'après OpenstreetMap
](https://transport.data.gouv.fr/datasets/cheminements-pietons-dans-paris-dapres-openstreetmap).

cc @thbar si tu es intéressé.

[Mattermost](https://mattermost.incubateur.net/betagouv/pl/dnir6k1f53fg7y6rfxbds1erur)

**Comment by thbar** [comment]
> Ceci ne semble pas approprié, les fichiers NeTEx pouvant être zippés ou non.

Je vais remonter ce point au GT7, car vu la taille habituelle des fichiers, une recommendation de zipper systématiquement ne semble pas une mauvaise idée (comme le fait le GTFS). Merci !

**Comment by ptitfred** [comment]
Cela risque de devenir obligatoire si la structure des fichiers NeTEx impose une nomenclature.

**Comment by ptitfred** [comment]
A noter que le plus gros NeTEx dans notre inventaire est non compressé : 432Mo de XML, dommage

**Comment by AntoineAugusti** [comment]
[Le fichier NeTEx](https://transport.data.gouv.fr/datasets/cheminements-pietons-dans-paris-dapres-openstreetmap#backed-up-resources) a bien été historisé après le merge de la PR.
