### ISSUE TITLE
Anomalie rapport IRVE backoffice transport.data.gouv.fr

### ISSUE THREAD

**Issue by stephane-pignal** [etalab/transport-site#4123]
Le job semble ne pas se lancer, aucun message retour précisant une anomalie
https://transport.data.gouv.fr/backoffice/irve-dashboard
@thbar ou @ptitfred ?

**Comment by thbar** [comment]
Copie d'écran:

![CleanShot 2024-08-16 at 16 25 35@2x](https://github.com/user-attachments/assets/b18b75d1-2b03-44b9-aac5-e3efe12a6400)

Lien: https://transport.data.gouv.fr/backoffice/irve-dashboard

**Comment by thbar** [comment]
@stephane-pignal j'ai l'impression que c'est simplement que ce traitement n'est pas lancé en automatique toutes les nuits ! à vérifier, mais tu peux le lancer avec le bouton et là ça fonctionne:

![CleanShot 2024-08-16 at 16 26 26@2x](https://github.com/user-attachments/assets/4bd6bb16-cc53-4eea-941e-80bc3f6c5dd3)

**Comment by stephane-pignal** [comment]
@thbar merci du retour, le problème était justement que cela ne se lançait pas manuellement.
D'ailleurs je lance tous les jours manuellement et ne savait pas qu'il était lancé quotidiennement en automatique
En tout cas il re-fonctionne manuellement.

**Comment by thbar** [comment]
> le problème était justement que cela ne se lançait pas manuellement.

Ok merci @stephane-pignal ! Alors je n'ai pas pu retomber sur le souci. Il est possible que tu sois tombé "entre deux déploiements" et que ça aie posé un souci (juste une idée, potentiellement).

Si ça se reproduit préviens-moi et j'irai enquêter ! 

Je clôture pour le moment.
