### ISSUE TITLE
Régression sur les métriques ? Ou problème de production réel ?

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#4126]
Suite à une enquête sans lien avec ça (je retrouvais davantage #3997 de DBConnection.Error dans Sentry depuis le 5 août), je me suis rendu compte que les métriques AppSignal montrent des courbes étranges depuis le 5 août vers 15h environ :
- taux d'erreur très élevé
- mais en même temps, throughput proche de zéro sur beaucoup de requêtes.

### Copies d'écran

https://appsignal.com/transport-dot-data-dot-gouv-dot-fr/sites/64a54ec183eb67b60f03fb6e/dashboard?

![CleanShot 2024-08-16 at 15 40 04@2x](https://github.com/user-attachments/assets/d2f6a9ea-80ba-4c7b-b26e-185878b9a97c)

Visible sur des pages de détail aussi:

https://appsignal.com/transport-dot-data-dot-gouv-dot-fr/sites/64a54ec183eb67b60f03fb6e/actions/web/TransportWeb.API.DatasetController%23geojson_by_id

![CleanShot 2024-08-16 at 15 42 51@2x](https://github.com/user-attachments/assets/8781f9e6-b9b7-4774-85d8-15320b416648)

(mais pas sur 100% des pages)

### Cause possible

Je remarque qu'au niveau du timing, cela coincide avec la mise en production de:
- #4101

Si ça colle au niveau timing, pour l'instant je n'ai pas la preuve du lien.

### Points de synchronicité

- les DBConnection.Error ont augmenté dans le même temps
- mais updown.io n'indique pas de downtime pour autant (toutefois cela ne requête qu'un endpoint précis)

### Idées possibles pour corriger

En premier lieu, je tenterais bien... de rollbacker juste `app_signal` et la version phoenix aussi, pour voir si à tout hasard, ça ne corrige pas le souci.

**Comment by thbar** [comment]
Poke @etalab/transport-tech point à regarder en priorité je pense lundi ! Je partage ça sur Mattermost.

**Comment by AntoineAugusti** [comment]
J'ai vérifié de nouveau les CHANGELOGs de appsignal et appsignal_phoenix sans rien remarquer ou d'opérations à effectuer.

J'ai contacté le support d'AppSignal pour avoir plus d'infos.

<details><summary>Details</summary>

```
Hello,

On Aug 8 we updated AppSignal dependencies for our Phoenix app and since then the number of HTTP actions/errors has dropped.

Version upgrades:
- appsignal 2.9.1 to 2.12.1
- appsignal_phoenix 2.3.5 to 2.4.0
- 
We read CHANGELOGs and didn't change code or configuration.

Did we miss something?
```

</details>

**Comment by AntoineAugusti** [comment]
Retour du support d'AppSignal

> We're investigating an issue that might have something to do with this. Could you downgrade to 2.3.9 to see if that resolves the issue for you?

Je vais faire ce downgrade.

**Comment by AntoineAugusti** [comment]
La PR a résolu le problème, le volume constaté sur AppSignal est désormais de retour à la normal.

Un dév de l'équipe AppSignal en charge du plugin Phoenix a répondu au ticket et fait un commit sur une branche pour essayer de débug. Cette branche est déployée sur staging pour tenter de leur donner des informations pertinentes pour trouver l'origine du problème.

[Voir échanges sur Front](https://app.frontapp.com/open/cnv_1948v8d2?key=gt-hNhGIMSHv8sCMUZ8pURofbKleyalx)
