### ISSUE TITLE
Supprimer @déploiement des notifs "pilotage" 

### ISSUE THREAD

**Issue by cyrilmorin** [etalab/transport-site#4145]
Hello,

On reçoit les notifs liés au pilotage ("nouveaux dataset possiblement à référencer", "les commentaires", "les datasets archivés" ....) dans les 2 boîtes mails : "contact" et "déploiement".

Finalement on se rend compte qu'un seule boîte nous simplifierait la vie vu notre fonctionnement actuel.

Après avoir checké que la boîte "contact" reçoit bien l'exhaustivité de ces alertes pouvez-vous supprimer l'adresse "déploiement" de la liste de diffusion svp ?

Merci :)

**Comment by AntoineAugusti** [comment]
Hello,

Ces notifications sont envoyées uniquement à `deploiement@` mais sont affichées par Front dans "Contact" + "Déploiement" car l'expéditeur des notifications est `contact@`.

Vous pouvez paraméter les notifications pour déploiement [depuis le BO](https://transport.data.gouv.fr/backoffice/contacts/55/edit). Peut-être créer un contact pour `contact@` et s'abonner aux mêmes notifications ?

Sinon peut-être que ceci peut être réglé par des filtres sur Front.

**Comment by cyrilmorin** [comment]
OK je me disais bien aussi ... bon on va creuser côté Front alors 
Merci je ferme ! (et non pas je la ferme !)

**Comment by AntoineAugusti** [comment]
J'ai modifié l'adresse e-mail/et le nom du contact de `deploiement@` à `contact@` dans le backoffice.
