### ISSUE TITLE
Bizdev - Modification de la notif Bizdev "Nouveaux jeux de données à référencer - data.gouv.fr"

### ISSUE THREAD

**Issue by cyrilmorin** [etalab/transport-site#4159]
Hello,

Avec @etalab/transport-bizdev et pour mieux nous organiser (traitement et archivage des mails) nous souhaiterions modifier le contenu des emails "Nouveaux jeux de données à référencer - data.gouv.fr" en les splitant en grandes familles.

Je propose les modifications ci-dessous qu'on pourra réajuster ultérieurement si besoin après retour d'expérience : 

=> Transmettre dorénavant 4 emails distincts en modifiant :

1- Le titre _Nouveaux jeux de données [Catégories] à référencer - data.gouv.fr_
2- Transmettre à contact@transport.data.gouv.fr (au lieu de deploiement@transport.data.gouv.fr)
3- 1 email par catégorie en suivant la catégorisation ci-dessous : 

**Transport en commun**

	@relevant_tags MapSet.new([
					   "bus",
					   "deplacements",
					   "déplacements",
					   "horaires",
					   "mobilite",
					   "mobilité",
					   "temps-reel"
					   "temps-réel",
					   "transport",
					   "transports"
					 ])
	  @relevant_formats MapSet.new(["gtfs", "netex", "gtfs-rt", "gtfsrt", "siri", "ssim"])
	  
**Freefloating**

	@relevant_tags MapSet.new([
					   "autopartage",
					   "freefloating",
					   "trottinette",
					   "vls"				 
					 ])
	  @relevant_formats MapSet.new(["gbfs"])
	  
**Vélo et stationnements**

	@relevant_tags MapSet.new([
					   "cyclable",
					   "parking",
					   "stationnement",
					   "velo",
					 ])	  
**Covoiturage et ZFE**

	@relevant_tags MapSet.new([
					   "covoiturage",
					   "zfe"
					 ])

IRVE ne semblait plus dans les notifs si je me réfère à https://github.com/etalab/transport-site/blob/master/apps/transport/lib/jobs/new_datagouv_datasets_job.ex ce qui semble logique au vu de la consolidation auto des ressources "IRVE" (@stephane-pignal n'hésites pas si je dis des bêtises !)

Merci et OK pour échanger sur le sujet si besoin

Cyril

**Comment by AntoineAugusti** [comment]
Le changement d'adresse e-mail de destinataire a déjà été réalisé https://github.com/etalab/transport-site/issues/4145#issuecomment-2326610039

**Comment by AntoineAugusti** [comment]
@cyrilmorin Je me demande si vous souhaiteriez avoir cette fonctionnalité dans le BO, sous forme d'un tableau et de sections. Avec une ✅ si le JDD a été renseigné.

Ou garder des e-mails envoyés tous les jours ouvrés.

**Comment by Brewennn** [comment]
> @cyrilmorin Je me demande si vous souhaiteriez avoir cette fonctionnalité dans le BO, sous forme d'un tableau et de sections. Avec une ✅ si le JDD a été renseigné.
> 
> Ou garder des e-mails envoyés tous les jours ouvrés.

Ça risque d'être complexe à mettre en place dans la BO surtout pour faire le lien avec data.gouv.fr ? Si ce n'est pas le cas, ça pourrait être un bon outil sinon l'envoi de mail suffirait.

**Comment by stephane-pignal** [comment]
1- Suite échange avec @cyrilmorin et @thbar même si cela ne vise pas directement le référencement d'un nouveau jdd sur le PAN, cela reste pertinent d'être averti d'une nouvelle ressource IRVE déposée sur data.gouv qui pour une raison x n'a pas été prise en compte par la consolidation.

 1er jet de "mots clés" ou "tags" à paramétrer :
"infrastructure de recharge"
"borne de recharge"
"irve"
"sdirve"
"électrique"
"electrique"

2- L'idée que les bizdev aient la main sur le choix des mots via notre BO par ex. me parait très intéressante. 
Cela nous permet d'ajuster la liste en toute autonomie.

3- Concernant "Freefloating", merci de rajouter
"scooter"

Concernant "Vélo et stationnements", merci de rajouter :
"libre-service"
"vélo" (la casse a apparemment son importance)

**Comment by AntoineAugusti** [comment]
> Le changement d'adresse e-mail de destinataire a déjà été réalisé [#4145 (comment)](https://github.com/etalab/transport-site/issues/4145#issuecomment-2326610039)

J'ai menti, il y a encore quelques trucs à modifier ici

https://github.com/etalab/transport-site/blob/3c34291a2bc56d100780db1ae24f740909339936/apps/transport/lib/mailer/admin_notifier.ex#L120-L125

Ce sera fait prochainement.

**Comment by AntoineAugusti** [comment]
Je viens d'ouvrir une PR pour implémenter le changement d'envoi de plusieurs e-mails par catégorie de données.

Vous aurez dans le footer un rappel des règles de ciblage pour les adapter au fur et à mesure. Notez que les schémas sont aussi utilisés pour assigner des JDDs à des catégories.

https://github.com/etalab/transport-site/pull/4163#discussion_r1745131203

**Comment by AntoineAugusti** [comment]
Changement d'adresse de destination dans #4168.

Les nouveaux e-mails sont disponibles dès à présent.
