### ISSUE TITLE
Ajout d'un lien vers explore.data.gouv.fr sur les ressources

### ISSUE THREAD

**Issue by AurelienC** [etalab/transport-site#4162]
Afin d'améliorer l'exploration des ressources, il serait utile d'ajouter le même bouton que présent sur data.gouv.fr pour ouvrir les ressources CSV, geoJson, dans l'outil explore.data.gouv.fr. Quelques améliorations sont proposées par la même occasion.

Proposition d'évolution de la page `/resources/`, avec en jaune ce qui évolue :
![image](https://github.com/user-attachments/assets/946736ff-b03d-4ac3-b633-6df420cf1dc5)

Le lien vers explore.data.gouv.fr se compose ainsi (à vérifier) avec les id côté datagouv :
`https://explore.data.gouv.fr/fr/datasets/{dataset_id}/#/resources/{resource_id}`

**Comment by thbar** [comment]
L'idée me paraît chouette !

Les questions qui me viennent:
- on resterait sur "CSV, geoJson" comme tu l'indiques, ça paraît bien ?
- et existe-t-il des cas où explore ne tient pas (fichiers trop gros) etc, à ta connaissance ?

**Comment by AurelienC** [comment]
Suite aux retours de l'équipe explore, voici les ressources lisibles :
- csv, csv.gz, excel, geoJson
- 100Mo maxi

Ce qui vérifie actuellement dans les ressources d'un dataset que c'est un fichier lisible est ici (`isCsv`, `isGeojson`) : https://github.com/datagouv/explore.data.gouv.fr/blob/07982019a81eec1ea0b1de583e0fde1bb9cda5b1/src/apps/tabular/ResourceView.vue#L196

**Comment by AurelienC** [comment]
Et ici, la vérification côté datagouv sur la prévisualisation qui pourrait permettre aussi de filtrer les ressources tabulaires (lisible par explore) ou non : https://github.com/opendatateam/udata-tabular-preview/blob/master/udata_tabular_preview/preview.py#L18-L21

**Comment by AurelienC** [comment]
Super, merci @AntoineAugusti !
