### ISSUE TITLE
Warning dans les tests du Transport.DataChecker

### ISSUE THREAD

**Issue by ptitfred** [etalab/transport-site#4178]
Un warning (relatif à Sentry?) est loggué dans les tests du Transport.DataChecker:

```
[warning] Event dropped due to being a duplicate of a previously-captured event.
```

Je n'ai pas le fin de l'histoire, mais une ressource à considérer est la [documentation de Sentry pour l'environnement de test](https://hexdocs.pm/sentry/Sentry.Test.html).

**Comment by thbar** [comment]
C'est ici: https://github.com/getsentry/sentry-elixir/blob/b8e40d793a7d45f6d1a1965120ce3a586793ce69/lib/sentry/client.ex#L114-L116
