### ISSUE TITLE
Sankéo - Lien ressources GTFS / GTFS-RT

### ISSUE THREAD

**Issue by cyrilmorin** [etalab/transport-site#4186]
Hello,

Pour le dataset [Sankéo ](https://transport.data.gouv.fr/datasets/gtfs-sankeo) qui contient 3 ressources dont le TR scolaire, pouvez-vous lier le couple GTFS/GTFS-RT correspondants svp ?
Ressources scolaires 82271 et 82273

![image](https://github.com/user-attachments/assets/f24aeb38-27da-46b8-9246-2dad2f2e56b9)

Merci !

**Comment by AntoineAugusti** [comment]
@etalab/transport-tech L'un de vous peut-il traiter ? Voici ce qu'il faut faire https://github.com/etalab/transport-site/issues/3987#issuecomment-2158247599 et [Mattermost](https://mattermost.incubateur.net/betagouv/pl/p9uqkdbck3gimddtw8s47b771e)

**Comment by ptitfred** [comment]
> @etalab/transport-tech L'un de vous peut-il traiter ? Voici ce qu'il faut faire [#3987 (comment)](https://github.com/etalab/transport-site/issues/3987#issuecomment-2158247599) et [Mattermost](https://mattermost.incubateur.net/betagouv/pl/p9uqkdbck3gimddtw8s47b771e)

Je peux oui.

**Comment by ptitfred** [comment]
Nous pourrions avoir un bouton dans le backoffice pour ça.

**Comment by ptitfred** [comment]
@cyrilmorin fait

**Comment by cyrilmorin** [comment]
Merci @ptitfred 
Pour le moment j'ai encore le message d'erreur malgré mais tentative d'import cet aprem.
Je check demain et te valide tout ça !
![{BD4B6801-41DE-4D32-81ED-F0DB3D65A9E7}](https://github.com/user-attachments/assets/af9bb571-b8ed-4caf-b6ca-95bc9a10c440)

**Comment by ptitfred** [comment]
Je ne suis pas encore familiarisé avec ce processus. Tiens moi au courant que je creuse au besoin.

**Comment by AntoineAugusti** [comment]
Il faut attendre qu'une validation GTFS-RT automatique ait eu lieu pour ne plus voir ce message.

Il est possible de lancer une validation sans attendre la prochaine exécution depuis le BO en cliquant sur "Valider". La validation prendra en compte la ressource GTFS associée alors.

**Comment by cyrilmorin** [comment]
yes j'avais Importé uniquement je pense ... sorry, je suis toujours sur mon idée de "Import" = "lancement de la validation" par définition ...
Tout est OK à présent Merci les gars !
