### ISSUE TITLE
BO : Export csv "contacts"

### ISSUE THREAD

**Issue by cyrilmorin** [etalab/transport-site#4189]
Hello,

L'export de la base contacts à des fins de nettoyage et pilotage semble nécessaire.
Une vue tabulaire triable et filtrable serait aussi intéressante mais peut-être plus compliquée ... un csv des familles serait suffisant à ce stade et pour un 1er jet.
RGPD : à priori l'export est OK, nous avons déjà les informations via l'IHM et en faisons un usage interne lié à l'activité.

Proposition des colonnes de l'export à discuter ensemble si besoin, pas clair ou pas possible : 

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/morin/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/morin/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">

Données | Commentaires
-- | --
ID |  
First Name |  
Last Name |  
Email |  
Email Hash | A quoi cela correspond ?
Phone Number |  
Job Title |  
Organization à renommer en Entity ? Entité en FR | Pour ne pas confondre Organization base contact et organization datagouv
Inserted At |  
Updated At |  
Secondary Phone Number | à supprimer ainsi que les valeurs (2 valeurs sur 755 contacts)
Datagouv User ID |  
Datagouv Organization Name | Quand un user ID est associé à une organisation datagouv = afficher le   nom de l'organisation
Last Login At |  
Created By | "system", "automation:import_contact_point"
Is Producer |  
Producer Dataset With Error | abonné aux notifs correspondantes avec valeurs = "oui" ou   "non" (1 dataset minimum = "oui")
Producer Expiration | abonné aux notifs correspondantes avec valeurs = "oui" ou   "non" (1 dataset minimum = "oui")
Producer Resource Unavailable | abonné aux notifs correspondantes avec valeurs = "oui" ou   "non" (1 dataset minimum = "oui")
Is Reuser | vérifier si au moins 1 dataset est en favori avec valeur oui ou non
Reuser Dataset With Error | abonné aux notifs correspondantes avec valeurs = "oui" ou   "non" (1 dataset minimum = "oui")
Reuser Expiration | abonné aux notifs correspondantes avec valeurs = "oui" ou   "non" (1 dataset minimum = "oui")
Reuser Resource Unavailable | abonné aux notifs correspondantes avec valeurs = "oui" ou   "non" (1 dataset minimum = "oui")
Reuser Resource Modification | abonné aux notifs correspondantes avec valeurs = "oui" ou   "non" (1 dataset minimum = "oui")
Reuser Dataset New Comment | abonné aux notifs correspondantes avec valeurs = "oui" ou   "non" (1 dataset minimum = "oui")

</body>

</html>

Merci !

**Comment by AntoineAugusti** [comment]
- `email_hash` est un champ technique qui permet de chercher un contact par adresse e-mail dans la base de données. L'adresse e-mail est chiffrée en base de donnée, ce champ technique permet d'aller vérifier l'existence/de retrouver un contact sans déchiffrer _toutes_ ces adresses
- `organization` est en effet un champ qui peut prêter à confusion https://github.com/etalab/transport-site/issues/3269 aborde ce problème

## Questions

"Datagouv Organization Name" : on peut être membre de plusieurs organisations. Que faire dans ce cas ?

**Comment by cyrilmorin** [comment]
Merci pour la précision sur email_hash

OK pour le label Organization => https://github.com/etalab/transport-site/issues/3269 mis à jour (renommer avec Entity - (_je modifie également dans la demande initial pour éviter toute confusion)_

Pour "Datagouv Organization Name" et si c'est possible, il faudrait lister toutes les Organizations auxquelles l'utilisateur est associée.
