### ISSUE TITLE
Erreur lors de la consolidation de la BNLC

### ISSUE THREAD

**Issue by AurelienC** [etalab/transport-site#4192]
La consolidation de la BNLC en l'état actuel, se termine avec une erreur, que voici :

`(MatchError) no match of right hand side value: {:error, :terminated}\n (elixir 1.16.2) lib/file/stream.ex:202: Enumerable.File.Stream.trim_bom/2
 (elixir 1.16.2) lib/file/stream.ex:178: Enumerable.File.Stream.skip_bom_and_offset/3
 (elixir 1.16.2) lib/stream.ex:1612: anonymous fn
 in Stream.resource/3
 (elixir 1.16.2) lib/stream.ex:1052: Stream.do_transform_inner_enum/7
 (elixir 1.16.2) lib/stream.ex:943: Stream.do_transform/5
 (elixir 1.16.2) lib/stream.ex:1828: Enumerable.Stream.do_each/4
 (elixir 1.16.2) lib/stream.ex:943: Stream.do_transform/5
 (elixir 1.16.2) lib/stream.ex:1828: Enumerable.Stream.do_each/4"`

id | state | queue | worker | args | inserted_at | errors
-- | -- | -- | -- | -- | -- | --
60018427 | discarded | default | Transport.Jobs.ConsolidateBNLCJob | %{} | 2024-09-17T08:46:31.921232 | [%{"at" => "2024-09-17T08:46:41.624926Z", "attempt" => 1, "error" => "** (MatchError) no match of right hand side value: {:error, :terminated}\n (elixir 1.16.2) lib/file/stream.ex:202: Enumerable.File.Stream.trim_bom/2\n (elixir 1.16.2) lib/file/stream.ex:178: Enumerable.File.Stream.skip_bom_and_offset/3\n (elixir 1.16.2) lib/stream.ex:1612: anonymous fn/5 in Stream.resource/3\n (elixir 1.16.2) lib/stream.ex:1052: Stream.do_transform_inner_enum/7\n (elixir 1.16.2) lib/stream.ex:943: Stream.do_transform/5\n (elixir 1.16.2) lib/stream.ex:1828: Enumerable.Stream.do_each/4\n (elixir 1.16.2) lib/stream.ex:943: Stream.do_transform/5\n (elixir 1.16.2) lib/stream.ex:1828: Enumerable.Stream.do_each/4\n"}, %{"at" => "2024-09-17T08:47:09.203920Z", "attempt" => 2, "error" => "** (MatchError) no match of right hand side value: {:error, :terminated}\n (elixir 1.16.2) lib/file/stream.ex:202: Enumerable.File.Stream.trim_bom/2\n (elixir 1.16.2) lib/file/stream.ex:178: Enumerable.File.Stream.skip_bom_and_offset/3\n (elixir 1.16.2) lib/stream.ex:1612: anonymous fn/5 in Stream.resource/3\n (elixir 1.16.2) lib/stream.ex:1052: Stream.do_transform_inner_enum/7\n (elixir 1.16.2) lib/stream.ex:943: Stream.do_transform/5\n (elixir 1.16.2) lib/stream.ex:1828: Enumerable.Stream.do_each/4\n (elixir 1.16.2) lib/stream.ex:943: Stream.do_transform/5\n (elixir 1.16.2) lib/stream.ex:1828: Enumerable.Stream.do_each/4\n"}, %{"at" => "2024-09-17T08:47:41.325480Z", "attempt" => 3, "error" => "** (MatchError) no match of right hand side value: {:error, :terminated}\n (elixir 1.16.2) lib/file/stream.ex:202: Enumerable.File.Stream.trim_bom/2\n (elixir 1.16.2) lib/file/stream.ex:178: Enumerable.File.Stream.skip_bom_and_offset/3\n (elixir 1.16.2) lib/stream.ex:1612: anonymous fn/5 in Stream.resource/3\n (elixir 1.16.2) lib/stream.ex:1052: Stream.do_transform_inner_enum/7\n (elixir 1.16.2) lib/stream.ex:943: Stream.do_transform/5\n (elixir 1.16.2) lib/stream.ex:1828: Enumerable.Stream.do_each/4\n (elixir 1.16.2) lib/stream.ex:943: Stream.do_transform/5\n (elixir 1.16.2) lib/stream.ex:1828: Enumerable.Stream.do_each/4\n"}]

****

**Comment by AntoineAugusti** [comment]
Le fichier des [lieux de covoiturage de la Corse](https://www.data.gouv.fr/fr/datasets/base-nationale-des-lieux-de-covoiturage-en-corse/) diffuse un CSV a pour encodage `latin1`.

```
$ file -I file.csv
/tmp/file.csv: text/plain; charset=iso-8859-1
```

Il faut gérer le fait qu'on peut avoir de l'UTF8 ou du Latin 1.
