### ISSUE TITLE
Tentative de modification logo Linéotim

### ISSUE THREAD

**Issue by cyrilmorin** [etalab/transport-site#4219]
Hello,

Le producteur aurait modifié hier le logo du dataset [Lineotim](https://transport.data.gouv.fr/datasets/lineotim-morlaix-communaute) mais le logo du publicateur (from datagouv) semble toujours s'affiché.
Trouvez vous bien trace de cette tentative ou y a-t-il un souci avec l'image en question 

Merci !

**Comment by AntoineAugusti** [comment]
La personne peut-elle essayer de nouveau ? Je vois un fichier vide déposé chez nous. 

[Finist'Air](https://transport.data.gouv.fr/datasets/finistair-region-bretagne) a été modifié peu après avec succès.

**Comment by cyrilmorin** [comment]
Yes merci, j'ai demandé en parallèle de retenter. Merci pour la confirmation : pas de trace du logo de notre côté
Je ferme
