### ISSUE TITLE
GBFSMetadata : compter le nombre de stations, de véhicules et distinguer par type

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#4258]
Ajouter des attributs pour compter :
- le nombre de stations
- le nombre de véhicules en freefloating
- distinguer le nombre de véhicules par type #4257

**Comment by stephane-pignal** [comment]
[Inventaire](https://www.notion.so/transport-data-gouv-fr/Roadmap-48ca8620efb046a984a7c34699b12841) gbfs publié sur le PAN à ce jour 
55 gbfs au total (31 VLS, 3 Vélos en free floating, 17 Trottinettes en free floating, 4 Vélos et Trottinettes en free floating)
A suivre +25 Ecovelo, une douzaine de Cykleo en standby, une douzaine de Fifteen et quelques JC Decaux à chasser
Target ressources VLS réévaluer à 6 mois : 60

**Comment by stephane-pignal** [comment]
Toutes les ressources gbfs publiées sur le PAN sont caractérisés "bike-scooter-sharing"
Chaque ressource publiée comporte dans son intitulé le type de service :
- VLS 
- Vélos (free floating)
- Trottinettes  (free floating)  
- Vélos et Trottinettes (free floating)
