### ISSUE TITLE
Publication d'un JDD "données expérimentales de l'accessibilité des cheminements piétons" en format NeTEx profil France

### ISSUE THREAD

**Issue by Brewennn** [etalab/transport-site#4275]
A la suite des échanges relatifs à la collecte des jeux des données sur l’accessibilité piétons avec AccesLibre Mobilité, plusieurs acteurs nous ont sollicité pour publier les premières données en format NeTEx - Profil France Accessibilité à titre expérimental afin de mettre à disposition des exemple de JDD [perso, je suis d'accord pour leur publication]

Des personnes de La Rochelle et Dieppe souhaitent mettre leurs données à disposition sans pour autant les officialiser au nom de leur organisation et ces données ne doivent pas être intégrées par un calculateur.

Pour publier leurs données une première solution à envisager serait de publier un JDD par le PAN et de rajouter les données en ressources. On indiquerait dans le titre et la description que ces données sont bien expérimentales et sont publiées à titre de premier exemples. Ces données pourraient être publiées dans une rubrique à part "autres données" ?

Une seconde solution serait que ces personnes publient en leur nom sur data.gouv.fr et que nous récupérons les liens URL pour les référencer dans une rubrique à part "autres données" ? [je suis moins fan de cette solution]

**Comment by Brewennn** [comment]
@thbar je te notifie car on a échangé rapidement sur ce sujet.

**Comment by Brewennn** [comment]
Cet issue est liée également avec celle ci #3806, sauf qu'ici les acteurs ne souhaitent pas associer la publication avec leur organisation

**Comment by ptitfred** [comment]
Cela n'est-il pas périlleux que de publier des données dont on ne veut pas qu'elles soient réutilisées ?

**Comment by Brewennn** [comment]
Pour ne pas être réutilisé pour du calcul d'itinéraire mais plutôt pour faire des tests et diffuser le NeTEx en mode beta. Finalement on a déjà des jeux comme ça dans les rubriques "lieux de mobilité" et "Autres informations". ça serai l'occasion de clarifier l'usage de ces rubriques

**Comment by thbar** [comment]
Quelques notes en vrac suite au point d'équipe:
- si on publie en tant que PAN, avoir un gros bandeau bien explicite en haut des jeux
- obtenir l'accord écrit de l'AOM avant toute publication
- gérer ça via un tag
- exclure les jeux ayant ce tag de l'API pour éviter tout souci de consommation où le réutilisateur ne serait pas conscient des limites (ne pas envoyer quelqu'un sur un trajet d'accessibilité complètement erroné, par exemple)
- privilégier NeTEx accessibilité et tarifs, éviter d'utiliser cela pour des formats exotiques (pente glissante / fragmentation)

**Comment by Brewennn** [comment]
Dans ce cas : 

- [ ] publier un jeu expérimental du PAN et ajouter les ressources au fur et à mesure. Ce jeu aura le tag 'masqué' pour qu'il n'apparaisse pas dans l'API et sera publié dans la rubrique 'Autres informations'. Le titre du jeu de données et la description sera détaillé ci-après.
- [ ] ajouter un bandeau sur ce jeu de données avec un tag 'experimental'. Le contenu du bandeau sera détaillé ci-après.

 _optionnel_ : prévoir une rubrique 'jeux expérimentaux' ?

**Comment by thbar** [comment]
> publier un jeu expérimental du PAN et ajouter les ressources au fur et à mesure. Ce jeu aura le tag 'masqué' pour qu'il n'apparaisse pas dans l'API et sera publié dans la rubrique 'Autres informations'. Le titre du jeu de données et la description sera détaillé ci-après.

@Brewennn je pensais plutôt avoir N jeux expérimentaux (avec chacun sa description, qui apparaît dans le listing du PAN séparément) qu'un seul jeu avec N ressources (de différences provenances), pour des questions de clarté. Et techniquement faire ça rendra facile le fait de faire une "rubrique jeux expérimentaux" justement. Est-ce que ça te va dans ce sens ?

**Comment by Brewennn** [comment]
ça me va

**Comment by Brewennn** [comment]
- les accents sont autorisés mais je ne suis pas très fan (on m'a toujours dit d'éviter en codage).
- la première PR n'est pas utile puisqu'il y a déjà un tag 'masqué' dans le Back office qui permet de cacher les JDD de l'API ?
- ok pour la seconde PR.
- ok
- ok

je pense qu'on a tout

**Comment by thbar** [comment]
+1 pour les accents :-) 

Première PR -> je vais aller vérifier ce point pour être sûr, je te confirme ça !

Et sinon on est bon !

**Comment by Brewennn** [comment]
Voici ma proposition d'éditorialisation pour la publication des jeux de données. Je reprécise que les données ne sont pas à réutiliser pour de l'information voyageur en bas du texte en plus du bandeau qui sera en haut : mieux vaut avertir l’utilisateur deux fois qu'une !

**Titre JDD :** 
Cheminements piétons [ville/EPCI X] – Données expérimentales

**Description JDD :**

Ce jeu de données expérimental décrit le cheminement piétons autour d’un ou plusieurs points d’arrêts prioritaires et intègre l’information sur leur accessibilité. 

Le jeu de données est produit notamment à partir de l’outil de collecte [AccesLibre Mobilité](https://mtes-mct.github.io/alm-docs/) et est publié au format d’échange [NeTEx](https://fr.wikipedia.org/wiki/NeTEx), [profil français pour l’accessibilité](https://normes.transport.data.gouv.fr/normes/netex/accessibilit%C3%A9/) conformément à l’[arrêté du 28 mai 2024](https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000049642987). 

****Le Point d’Accès National met à disposition ce jeux de données expérimental à titre d’illustration** en accord avec les agents de la collectivité. Les données sont en cours de collecte et seront publiées officiellement par la collectivité dans un second temps.**

**Nous vous remercions de ne pas réutiliser ce jeu à des fins d’information voyageur.**

**Comment by Brewennn** [comment]
Pour le bandeau et la tag, je tente du code à ajouter : 

**Tag**

1. [apps/transport/lib/transport_web/live/backoffice/custom_tags_live.ex](apps/transport/lib/transport_web/live/backoffice/custom_tags_live.ex) : ligne 75

},
      %{
        name: "experimental",
        doc: "Ajoute sur la page du JDD une bannière indiquant que le jeu est expérimental"
      }

2. [apps/transport/lib/transport_web/templates/dataset/_banner.html.heex](apps/transport/lib/transport_web/templates/dataset/_banner.html.heex)

<p :if={experimental?(@dataset)} class="notification mt-0">
  ℹ️ <%= dgettext(
    "page-dataset-details",
    "This unofficial dataset is provided experimentally. Do not use it for travel information purpose."
  ) %>
</p>

-> on peut changer la couleur et le logo "i" pour mettre quelque chose plus de avertissant ?

**Bandeau**

1. [apps/transport/priv/gettext/en/LC_MESSAGES/page-dataset-details.po](apps/transport/priv/gettext/en/LC_MESSAGES/page-dataset-details.po)

#, elixir-autogen, elixir-format
msgid "This unofficial dataset is provided experimentally. Do not use it for travel information purpose"
msgstr "Ce jeu de données non officiel est publié à titre expérimental. Veuillez à ne pas le réutiliser à des fins d'information voyageur."

4. [apps/transport/priv/gettext/en/LC_MESSAGES/page-dataset-details.po](apps/transport/priv/gettext/en/LC_MESSAGES/page-dataset-details.po)

#, elixir-autogen, elixir-format
msgid "This unofficial dataset is provided experimentally. Do not use it for travel information purpose"
msgstr ""

5. [apps/transport/priv/gettext/page-dataset-details.pot](apps/transport/priv/gettext/page-dataset-details.pot)

#, elixir-autogen, elixir-format
msgid "This unofficial dataset is provided experimentally. Do not use it for travel information purpose"
msgstr ""

**Comment by Brewennn** [comment]
> > Qu'on définisse le tag à mettre à la main (ex: `expérimental` ? je verrai si l'accent ne pose pas de problème)
> 
> Pas d'accents dans les tags de dataset actuellement si ça peut aider.

Dans [apps/transport/lib/transport_web/live/backoffice/custom_tags_live.ex](apps/transport/lib/transport_web/live/backoffice/custom_tags_live.ex) ligne 53 on a le tag `licence-mobilités`

**Comment by ptitfred** [comment]
> Pour le bandeau et la tag, je tente du code à ajouter :

J'ai pas bien suivi : tu t'occupes des changements ?

**Comment by Brewennn** [comment]
Effectivement je n'ai pas été clair. Non, je ne tente pas de Pull request j'ai juste mis mes propositions ici dans l'issue. Mais je peux proposer de changements si c'est ok pour vous. Par contre je ne saurai pas faire de propositions dans les codes "test" je ne sais pas comment ça fonctionne.

**Comment by ptitfred** [comment]
Merci pour les textes déjà :)

**Comment by thbar** [comment]
Merci @ptitfred pour l'implém !

**Comment by thbar** [comment]
@Brewennn le titre me paraît nickel.

Je propose d'être plus incisif sur le "disclaimer" de la description, par contre:

> Nous vous remercions de ne pas réutiliser ce jeu à des fins d’information voyageur.

Remplacé par 

> ⚠️ Ne pas utiliser ce jeu de données à des fins d'information voyageur. Données non validées pour un usage en production

Et je mettrai ça plus haut dans la description pour que ça sois inratable (ou plus dur à rater), juste en dessous de :

> Ce jeu de données expérimental décrit le cheminement piétons autour d’un ou plusieurs points d’arrêts prioritaires et intègre l’information sur leur accessibilité.

**Comment by Brewennn** [comment]
@thbar ok pour moi. Je l'avais mis en bas car il y a en plus le bandeau en haut mais ok pour le remonter.

Pour le warning, je propose cette phrase pour être plus clair à mon sens : 

⚠️ Données non validées officiellement : ne pas utiliser ce jeu de données à des fins d'information voyageur.

**Comment by thbar** [comment]
@Brewennn parfait !

**Comment by Brewennn** [comment]
@thbar voici le rendu final pour le JDD https://transport.data.gouv.fr/datasets/cheminements-pietons-ville-test-donnees-experimentales (j'ai mis en statut privé sur data.gouv pour l’instant). Dis-moi ce que tu en penses. 

Je n'ai pas encore précisé ni dans le titre ni dans le back office la commune concernée par ces jeux je souhaite bien avoir leur aval avant de l'indiquer

Par ailleurs, il sera nécessaire d'avoir l'accord pour l'utilisation de la licence ouverte.

**Comment by thbar** [comment]
@Brewennn c'est parfait !

**Comment by AntoineAugusti** [comment]
C'est bien publié en prod https://transport.data.gouv.fr/datasets/cheminements-pietons-de-lorient-agglomeration-donnees-experimentales
