### ISSUE TITLE
Consolidation ZFE : JDD non consolidé

### ISSUE THREAD

**Issue by AurelienC** [etalab/transport-site#4289]
Le [jeu de données de la métropole de Lyon](https://www.data.gouv.fr/fr/datasets/zone-a-faibles-emissions-de-la-metropole-de-lyon-zfe/) ne semble pas être consolidé, différence constatée notamment tout au Sud de la zone principale.

A gauche : le JDD de la métropole
A droite : la BNZFE
<img width="1210" alt="image" src="https://github.com/user-attachments/assets/9a7adda3-b7aa-4398-8df2-f4e4a124b121">

Le(s) job(s) se termine(nt) sans erreur :
id | state | queue | worker | args | inserted_at (Paris time)
-- | -- | -- | -- | -- | --
62931894 | completed | default | Transport.Jobs.ConsolidateLEZsJob | %{} | 2024-11-04 at 18:07
62931886 | completed | default | Transport.Jobs.ConsolidateLEZsJob | %{} | 2024-11-04 at 18:02
62925111 | completed | default | Transport.Jobs.ConsolidateLEZsJob | %{} | 2024-11-04 at 15:16

**Comment by AntoineAugusti** [comment]
@AurelienC Ce JDD [n'est pas référencé](https://transport.data.gouv.fr/datasets/region/2?type=low-emission-zones) dans la catégorie des ZFE. Il a été créé fin septembre 2024.

Peux-tu le référencer et lancer de nouveau une consolidation ?
