### ISSUE TITLE
GBFS : connaitre les opérateurs des différents flux

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#4299]
La spec GBFS ajoute un champ _optionnel_ `operator` [à partir de la v3.0](https://gbfs.org/specification/reference/#system_informationjson) dans `system_information.operator`.

Voici les valeurs actuelles sur notre plateforme.

operator | count
-- | --
  | 21
"Bird Rides, Inc." | 14
"pony" | 4
"CITYBIKE Normandie - groupe INURBA Mobility" | 1
"Donkey Republic" | 1
"Fifteen" | 1
"STAR" | 1
"Strasbourg Mobilités Vélo, 55 rue du Marché Gare, 67000 Strasbourg" | 1

Il est souhaitable de connaitre ces opérateurs pour avoir des statistiques utiles. On peut faire ceci à l'aide de l'URL de diffusion/ou un tag dans le backoffice en complément de ce qui est renseigné dans le flux GBFS.

## Mapping des URLs

En faisant une études URLs de diffusion actuellement, le mapping pourrait ressembler à ça.

```sql
select distinct split_part(r.url, '/', 3) domain
from resource r
where r.format = 'gbfs'
```

URL | operator
-- | --
api.cyclocity.fr|JC Decaux
api.saint-etienne-metropole.fr|Fifteen
bdx.mecatran.com|Cykleo
bird.co|Bird
clermontferrand.publicbikesystem.net|Citybike
data.mobilites-m.fr/api/gbfs/dott_grenoble|Dott
data.optymo.fr|SMTC 90
donkey.bike|Donkey Republic
download.data.grandlyon.com|JC Decaux
ecovelo.mobi|Écovélo
eu.ftp.opendatasoft.com/star|Cykleo
fifteen.eu|Fifteen
fifteen.site|Fifteen
getapony.com|Pony
lime.bike|Lime
nextbike.net|nextbike
smovengo.cloud|Fifteen
urbansharing.com/lovelolibreservice.fr|Citybike
voiapp.io|Voi
zoov.eu|Fifteen
zoov.io|Fifteen
zoov.site|Fifteen

Est-ce que ce mapping te convient @stephane-pignal ? Préfères-tu que l'on passe par un tag à définir dans le backoffice pour renseigner l'opérateur ?

**Comment by stephane-pignal** [comment]
@AntoineAugusti l'url me parait plus simple et adaptée
Ok pour ce 1er mapping
