### ISSUE TITLE
Tri sur datasets "récemment ajoutés" NOK pour les users

### ISSUE THREAD

**Issue by cyrilmorin** [etalab/transport-site#4337]
Hello,

On retrouve plusieurs mentions du "Récemment ajouté" sur le site : 

**1-** En page d'accueil comme si c'était un feature importante (à voir de son importance dans le futur)
![image](https://github.com/user-attachments/assets/81353003-43a2-4732-899c-a127f4b0b2cd)
**2-** En tri "en dur" sur la page [des datasets](https://transport.data.gouv.fr/datasets?order_by=most_recent)
![{DC9B74C1-13F0-4866-846A-95331EBDBD05}](https://github.com/user-attachments/assets/37bf7964-ed31-49ea-b24f-c76a2eb23cfa)

Or le tri est fortement déceptif (et faux d'un point de vue utilisateur) car on a des datasets anciens mais qui sont mis à jour quotidiennement mais transmis comme "nouveaux" par datagouv (je vous laisse confirmer si ce n'est pas le cas). 
Je sais que c'est un sujet déjà abordé et les causes sont à ce stade moins prioritaires que d'essayer d'améliorer le rendu de notre côté ! 

Voici quelques propositions pour avancer :

1- Est-il possible de voir avec datagouv si le problème sera réglé prochainement ?
2- Si non, est-ce que trier par date d'ajout chez nous (référencement sur le PAN) ne serait pas une bonne idée ? C'est ce que l'on veut vraiment savoir finalement ...

Merci pour vos retours et/ou propositions :)

**Comment by AntoineAugusti** [comment]
> 1- Est-il possible de voir avec datagouv si le problème sera réglé prochainement ?

C'est lié au fonctionnement des moissonneurs donc c'est assez instable

> 2- Si non, est-ce que trier par date d'ajout chez nous (référencement sur le PAN) ne serait pas une bonne idée ? C'est ce que l'on veut vraiment savoir finalement ...

Ça c'est facile à faire par contre, je m'en occupe.

**Comment by AntoineAugusti** [comment]
C'est bien en prod, je te laisse me confirmer que c'est mieux

**Comment by cyrilmorin** [comment]
C'est top, beaucoup mieux et cohérent en effet ! 
Merci :)
