### ISSUE TITLE
Mise à jour des informations sur la page https://normes.transport.data.gouv.fr/

### ISSUE THREAD

**Issue by Brewennn** [etalab/transport-site#4349]
Avec l'évolution de la réglementation européenne, le GT07 a retravaillé les informations juridiques dans les profils et sur la page d'accueil : https://normes.transport.data.gouv.fr/. 

L'objectif de la PR est de mettre à jour les infos sur la page d'accueil. 

@thbar, @TuThoThai

**Comment by TuThoThai** [comment]
[PR ouverte](https://github.com/etalab/transport-normes-site/pull/29) pour ta review, @Brewennn

**Comment by thbar** [comment]
Je crois qu'on a:
- #29 première tentative (avec un nom d'accent dans la branche)
- remplacé par #30 (qui vient d'être mergé)

Donc je clôture ici !
