### ISSUE TITLE
Mise à jour Ecto impossible - souci lié aux migrations

### ISSUE THREAD

**Issue by thbar** [etalab/transport-site#4358]
"Yak-shaving ahead"

<a href="https://www.youtube.com/watch?v=AbSehcT19u0">
   <img src="https://img.youtube.com/vi/AbSehcT19u0/0.jpg" width="40%">
</a>

Voilà la pelote de laine:
- je travaillais sur les MAJ techniques ici #4216 
- quand à un moment, je me rends compte qu'il est souhaitable de mettre à jour Ecto (notamment pour dégager `connection` qui n'est plus maintenu ; la dépendance disparaît en mettant à jour `postgrex`)
- je tente ma chance ici https://github.com/etalab/transport-site/pull/4347
- quand soudainement, une migration de 2022 [se met à planter](https://github.com/etalab/transport-site/pull/4347#issuecomment-2512226040)
- je regarde de plus près, et comprends que la syntaxe n'a, si je lis bien, jamais été correcte (et que la mise à jour d'Ecto réduit une souplesse sur ce qui était ignoré de façon silencieuse avant):

https://github.com/etalab/transport-site/blob/01db0667d599ff6ea532ad6d8502a881e52cb0d6/apps/transport/priv/repo/migrations/20221206135302_data_import_delete.exs#L21-L24

- En effet, [`references`](https://hexdocs.pm/ecto_sql/Ecto.Migration.html#references/2) ne prend pas d'option `from:`, c'est plutôt à mettre si je lis bien sur [`modify`](https://hexdocs.pm/ecto_sql/Ecto.Migration.html#modify/3).
- On peut tenter de corriger la syntaxe:

```elixir
      alter table(tbl) do
        modify(
          :data_import_id,
          references(:data_import, on_delete: :delete_all),
          from: references(:data_import, on_delete: :nothing)
        )
      end
```

- Toutefois après avoir fait ça, un autre problème apparaît, qui était probablement lui aussi pré-existant: `** (Postgrex.Error) ERROR 42704 (undefined_object) constraint "gtfs_stops_data_import_id_fkey" of relation "gtfs_stops" does not exist`

### Mais quoi faire ?

À ce stade on peut penser à deux stratégies:
1. essayer de rétro-corriger cette migration, en respectant l'état final attendu
2. ou https://github.com/etalab/transport-site/issues/3596, qui nous pendait au nez de toute façon à un moment, avec actuellement pas moins de 193 migrations

Traiter le point 1 sera plus rapide si on arrive à corriger ça proprement.

Traiter le point 2 se fait bien (https://github.com/fly-apps/safe-ecto-migrations?tab=readme-ov-file#squashing-migrations) toutefois dans notre cas, des données "référentielles" ont été injectées par endroit via les migrations, il y a des triggers etc, donc il faudra s'assurer que le dump est "propre" et suffisamment proche de la production pour qu'on ne pense pas en dév, que les choses marchent, pendant qu'elles échoueront en production.

Et ça serait sûrement le bon moment d'introduire un [`seeds.exs`](https://github.com/phoenixframework/phoenix/blob/main/installer/templates/phx_ecto/seeds.exs) pour charger les données automatiquement en dev/test avec ce référentiel (et ne conserver que de la structure dans les migrations).

**Comment by AntoineAugusti** [comment]
Je prends en charge ce ticket et propose de suivre uniquement le 1) pour le moment, les autres tâches demandant bien plus de travail, il faudra qu'elles soient évaluées/planifiées.

Je regarde donc pour réparer cette migration.

**Comment by thbar** [comment]
Merci @AntoineAugusti !
