### ISSUE TITLE
Coquille message warning sur "dataset expérimental"

### ISSUE THREAD

**Issue by cyrilmorin** [etalab/transport-site#4363]
Hello, 

Pour le texte de warning il y a une petite coquille sur le texte warning sur les [dataset données expérimentales 
](https://transport.data.gouv.fr/datasets/cheminements-pietons-de-la-communaute-dagglomeration-de-la-rochelle-donnees-experimentales)
![image](https://github.com/user-attachments/assets/8b6b9c51-2d44-4a0a-83d2-6d0e3f4e5f6a)

Modifier avec "Veuillez ne pas le réutiliser ..." (ou Veillez à ne pas le réutiliser ...)

**Comment by AntoineAugusti** [comment]
🚨🇫🇷🇫🇷🚨
