### ISSUE TITLE
Traitements de fond (jobs) en panne de façon régulière (impact: validations etc)

### ISSUE THREAD

**Issue by Brewennn** [etalab/transport-site#4377]
Bonjour,

La région Normandie nous a rapporté que le rapport de validation ne s'affichait pas lors de l'utilisation du validateur. Ils ont tenté la validation d'un fichier très léger de 12 Ko. J'ai fait le test avec ce même fichier et d'autres, ainsi que sur deux navigateurs : Firefox et Microsoft Edge.

Je reste bloqué sur la page de rafraichissement.

**Comment by AntoineAugusti** [comment]
Notre scheduler de tâches asynchrones semble être indisponible. Le dernier job exécuté date d'il y a plusieurs heures.

```
select max(attempted_at)
from oban_jobs
where state = 'completed'
```

`2024-12-12 03:55:07.539034`

Je vais redémarrer le worker.

**Comment by AntoineAugusti** [comment]
Un redémarrage du worker règle le problème. Les jobs asynchrones s'exécutent de nouveau.

Il y a du retard de traitement.

|queue|job_count|
| --- | --- |
|   default   |   1933   |
|   on\_demand\_validation   |   9   |
|   resource\_validation   |   1176   |
|   workflow   |   4   |


|worker|job_count|
| --- | --- |
|   Transport.Jobs.ResourceUnavailableJob   |   1521   |
|   Transport.Jobs.ResourceHistoryValidationJob   |   956   |
|   Transport.Jobs.GTFSRTMetadataJob   |   254   |
|   Transport.Jobs.GTFSRTMultiValidationJob   |   150   |
|   Transport.Jobs.GBFSMultiValidationJob   |   65   |
|   Transport.Jobs.UpdateCounterCacheJob   |   61   |
|   Transport.Jobs.ResourcesUnavailableDispatcherJob   |   33   |
|   Transport.Jobs.MultiValidationWithErrorNotificationJob   |   10   |
|   Transport.Jobs.ResourceUnavailableNotificationJob   |   9   |
|   Transport.Jobs.Workflow   |   4   |
|   Transport.Jobs.NewDatagouvDatasetsJob   |   2   |
|   Transport.Jobs.GTFSRTMetadataDispatcherJob   |   2   |
|   Transport.Jobs.ResourceHistoryJob   |   2   |
|   Transport.Jobs.GTFSToGeoJSONConverterJob   |   1   |
|   Transport.Jobs.RemoveHistoryJob   |   1   |
|   Transport.Jobs.ExpirationNotificationJob   |   1   |
|   Transport.Jobs.GBFSStationsToGeoData   |   1   |
|   Transport.Jobs.DatabaseBackupReplicationJob   |   1   |
|   Transport.Jobs.CleanOrphanConversionsJob   |   1   |
|   Transport.Jobs.ImportResourceMonthlyMetricsJob   |   1   |
|   Transport.Jobs.NewCommentsNotificationJob   |   1   |
|   Transport.Jobs.ConsolidateLEZsJob   |   1   |
|   Transport.Jobs.DatasetsClimateResilienceBillNotLOLicenceJob   |   1   |
|   Transport.Jobs.WarnUserInactivityJob   |   1   |
|   Transport.Jobs.NewDatasetNotificationsJob   |   1   |
|   Transport.Jobs.LowEmissionZonesToGeoData   |   1   |
|   Transport.Jobs.ImportGBFSFeedContactEmailJob   |   1   |
|   Transport.Jobs.ResourceHistoryAndValidationDispatcherJob   |   1   |
|   Transport.Jobs.IRVEToGeoData   |   1   |
|   Transport.Jobs.BNLCToGeoData   |   1   |
|   Transport.Jobs.ParkingsRelaisToGeoData   |   1   |
|   Transport.Jobs.GTFSToNeTExConverterJob   |   1   |

**Comment by Brewennn** [comment]
Merci. Effectivement il y a pas mal de tâches en attente. Tu sais quand tout sera traité ?

**Comment by AntoineAugusti** [comment]
@Brewennn Pour la validation à la demande c'est de retour immédiatement, le reste prendra quelques heures et c'est difficile de donner une estimation.

**Comment by thbar** [comment]
On a eu un autre cas (voir #4384).

Même symptôme que précédemment: rien n'est "attempted" comme vu ici https://github.com/etalab/transport-site/issues/4377#issuecomment-2538451761.

```sql
SELECT
	count(*) AS COUNT,
	date_trunc('hour', attempted_at) AS HOUR
FROM
	oban_jobs
WHERE
	state = 'completed'
GROUP BY
	HOUR
ORDER BY
	HOUR
```

| count | hour                |
|-------|---------------------|
|   226 | 2024-12-15 09:00:00 |
|  2062 | 2024-12-15 10:00:00 |
|  1801 | 2024-12-15 11:00:00 |
|  4608 | 2024-12-15 12:00:00 |
|  1809 | 2024-12-15 13:00:00 |
|  2059 | 2024-12-15 14:00:00 |
|  1965 | 2024-12-15 15:00:00 |
|  2680 | 2024-12-15 16:00:00 |
|  1811 | 2024-12-15 17:00:00 |
|  2463 | 2024-12-15 18:00:00 |
|   342 | 2024-12-16 09:00:00 |

Je vais aller signaler ça sur le Slack de Oban, voir si c'est déjà arrivé à quelqu'un.

Par ailleurs je propose les outils ops suivants:
- modifier le health-check HTTP pour avoir une sous-partie permettant de détecter si le `max(attempted_at)` est au delà d'une certaine durée (latence max), donnerait un 500 et donc une alerte (avec une url indépendante si on veut considérer que c'est moins critique qu'un downtime complet):

https://github.com/etalab/transport-site/blob/c1258ddbe2ac16acf92e2732751fffba15062c8a/apps/transport/lib/transport_web/plugs/health_check.ex#L38-L43

- suivre des métriques supplémentaires dans AppSignal : nombre de jobs pending, latence de traitement typique

**Comment by thbar** [comment]
Je suis curieux de voir aussi si #4371 règle le souci, ce n'est pas complètement exclu.

**Comment by stephane-pignal** [comment]
@thbar pour info, toujours la même chose coté https://github.com/etalab/transport-site/issues/4383

**Comment by thbar** [comment]
@stephane-pignal merci je vais aller enquêter

**Comment by thbar** [comment]
Requête intéressante à suivre (à reviewer à un moment, je vais l'intégrer dans le health-check je pense)

```sql
SELECT 
    NOW() - MAX(attempted_at) AS time_since_last_attempt
FROM
    oban_jobs
WHERE
    state = 'completed'
```

(à tester dans la vraie vie sur la durée, ça peut aller dans AppSignal assez facilement + UpDown derrière)

**Comment by thbar** [comment]
J'ai testé [cette requête](https://github.com/etalab/transport-site/issues/4377#issuecomment-2546938740) à l'instant sur une envie qui passait, et en fait le problème de production est présent. Je vais redémarrer le worker.

| time_since_last_attempt |
|-------------------------|
| 07:46:12.579013         |
