### ISSUE TITLE
Rapport IRVE dans le back office bloqué depuis le 24-10-2024

### ISSUE THREAD

**Issue by stephane-pignal** [etalab/transport-site#4383]
@thbar l'analyse consolidée dans le back office semble ne plus fonctionner.
La semaine dernière, la tâche était lancée mais restait bloquée à 24%
Aujourd'hui elle semble ne pas démarrer, en tout cas à l'affichage

**Comment by thbar** [comment]
@stephane-pignal merci je vais aller voir !

**Comment by thbar** [comment]
Voir si il n'y a pas un lien avec:
- #4377 (et son doublon #4384)

**Comment by thbar** [comment]
Il s'agit bien d'un symptôme de + de #4377 (@etalab/transport-tech le scanner IRVE est bien un job Oban https://github.com/etalab/transport-site/blob/c1258ddbe2ac16acf92e2732751fffba15062c8a/apps/transport/lib/jobs/analyze_irve_job.ex#L1-L2).

@stephane-pignal je clôture le présent ticket car c'est un doublon de #4377. Merci d'avoir signalé !

**Comment by thbar** [comment]
#4377 était bien un pré-requis, mais il y a autre chose en prime ! Je ré-ouvre.

**Comment by thbar** [comment]
@stephane-pignal j'ai compris - je prépare un fix.

**Comment by thbar** [comment]
@stephane-pignal le correctif est prêt pour review côté @etalab/transport-tech ; le cas précis qui a fait planter est une nouveauté : une ressource indiquée "valide" par data gouv, mais qui est actuellement en 404, j'ai rendu le code plus souple là dessus.

**Comment by thbar** [comment]
Le correctif est en train d'être déployé, je clôture ici. @stephane-pignal pourras-tu vérifier que ça marche bien pour toi ? merci !

**Comment by stephane-pignal** [comment]
Merci @thbar cela remarche ! La chasse au pdc est repartie
