### ISSUE TITLE
Retards de traitement sur les jobs (impact: validateur à la demande et autres)

### ISSUE THREAD

**Issue by stephane-pignal** [etalab/transport-site#4384]
@thbar quelque soit la ressource en input, le validateur irve statique du PAN reste sur la page "Validation en cours, cette page va se rafraichir automatiquement"
![Capture d’écran 2024-12-16 à 09 56 31](https://github.com/user-attachments/assets/3ff05390-1d9a-4f45-b09d-6f09b718c368)

**Comment by thbar** [comment]
Merci @stephane-pignal. Je viens de reproduire le souci, ce n'est pas propre à l'IRVE. Il y a du retard dans nos traitements de job j'ai l'impression, à première vue.

```sql
select count(*) as c, state from oban_jobs group by state order by c desc
```

| c     | state     |
|-------|-----------|
| 21573 | completed |
|  1036 | available |
|   993 | discarded |
|     4 | scheduled |
|     2 | cancelled |

Je renomme le ticket et je partage avec @etalab/transport-tech

**Comment by AntoineAugusti** [comment]
Semble similaire à https://github.com/etalab/transport-site/issues/4377#issuecomment-2538451761

Le `max(completed_at)` est à `2024-12-15 18:09:11.879175`

**Comment by AntoineAugusti** [comment]
Je viens de reboot `prod-worker`

**Comment by thbar** [comment]
Oui c'est bien un doublon, @stephane-pignal je t'invite à suivre #4377 pour la suite ! On clôture ici du coup.

**Comment by stephane-pignal** [comment]
En effet problème réglé. Merci @AntoineAugusti et @thbar
