### ISSUE TITLE
Explain to AOs why their published data is not in the reusable whitelist

### ISSUE THREAD

**Issue by maukoquiroga** [etalab/transport-site#45]
**Story :**

    When I visit transport.beta.gouv.fr,
    and I click in the button to reuse data,
    and that I don't see my data,
    and that I've already had 5 coffees and I'm irritable,
    I want to understand why my data is not there, in the list,
    so I can felt accomplished,
    and go home soon,
    and be with my kids and family.

**Definition of done**:

- [ ] I have an explanation of why my data is not here
- [ ] I can click somewhere to make my data appear in the list
- [ ] I can click somewhere to ask for help

**Mockup :**

![image uploaded from ios](https://user-images.githubusercontent.com/329236/30814048-5910b938-a20f-11e7-85b0-86fc087b2966.jpg)

**Comment by Tristramg** [comment]
Closing as over a year old.
