### ISSUE TITLE
Redirection vers HTTPS

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-site#488]
Actuellement le site peut être servi en HTTP ou HTTPS. Il serait idéal d'avoir une redirection 301 systématique vers le HTTPS.

```
$ curl -I http://transport.data.gouv.fr
HTTP/1.1 200 OK
server: Cowboy
date: Thu, 06 Dec 2018 09:32:57 GMT
```

**Comment by Tristramg** [comment]
Merci ! ça a été corrigé dans #493
