### ISSUE TITLE
Afficher clairement quel type de données est chaque fiche

### ISSUE THREAD

**Issue by Tristramg** [etalab/transport-site#545]
Aussi bien sur la fiche que dans les listes (recherche & co)

@thimy peut-être que t’as un avis pour faire un logo ? Sinon je prends sur font-awesome et je creuse pas.

Pour l’instant on les modes suivants :

* transport-statique
* aires-covoiturage
* référentiel d’arrêt
* bornes-recharge
* vélo en libre service
 
Probablement à venir : voitures en auto-partage

**Comment by Tristramg** [comment]
t’as trop bossé chez CT ;)

**Comment by antoine-de** [comment]
on peut pas juste réutiliser les tpicto des ypes de la home ?

On retombe dans la discussion sur le fait que les jeux de données peuvent avoir plusieurs type (genre le temps réel), mais si on met ca de coté (et que pour le temps réel on met juste le picto du théorique), ca pourrait donner ca (pas taper pour la forme :stuck_out_tongue_winking_eye: )

![image](https://user-images.githubusercontent.com/3987698/71827944-37a65a80-3099-11ea-977a-63cef04d6842.png)

**Comment by Tristramg** [comment]
Je pense que c’est un bon début déjà.
Il faudrait aussi le faire sur la page du dataset en lui-même également.
Mais ça peut très bien se faire en deux temps.
