### ISSUE TITLE
Pas de mise à jour des titres et URL de jeux de données transportdatagouv <> datagouv

### ISSUE THREAD

**Issue by IshanB** [etalab/transport-site#580]
Le producteur de données a modifié la description et le titre de son jeu de données sur data.gouv.fr mais la modif ne s'est pas répercutée sur transport.data.gouv.fr

https://www.data.gouv.fr/fr/datasets/localisation-des-arrets-ilevia-bus-metro-et-tram-gtfs-pictogrammes-du-reseau-ilevia/

donne 

https://transport.data.gouv.fr/datasets/localisation-des-arrets-transpole-bus-metro-et-tram-gtfs-pictogrammes-du-reseau-transpole

**Comment by Tristramg** [comment]
Est-ce que ça ne datait pas d’un moment où on avait des soucis avec data.gouv.fr ?
