### ISSUE TITLE
crawler le site après un déploiement 

### ISSUE THREAD

**Issue by l-vincent-l** [etalab/transport-site#590]
Après un déploiement crawler le site et remonter les erreurs 500.

**Comment by antoine-de** [comment]
what do you mean by this issue ?
Is it to remove the outdated resources ? if so it is already done no ?

**Comment by Tristramg** [comment]
It is meant as an external sensor

**Comment by Tristramg** [comment]
Shouldn’t we close this issue? I don’t think we’ll ever do it.
