### ISSUE TITLE
Lien mort Compte rendu freefloating

### ISSUE THREAD

**Issue by IshanB** [etalab/transport-site#606]
Quand je clique sur le lien du compte rendu VLS qui est référencé sur transport.data.gouv.fr/stats, le lien est mort

**Comment by IshanB** [comment]
[Atelier data vls autopartage freefloating.pdf](https://github.com/etalab/transport-site/files/2869955/Atelier.data.vls.autopartage.freefloating.pdf)

**Comment by Tristramg** [comment]
corrigé
