### ISSUE TITLE
Epingler un repo transport.data ?

### ISSUE THREAD

**Issue by jerbou** [etalab/transport-site#634]
Bonjour,

J'ai fait par erreur une [ticket ](https://github.com/etalab/data.gouv.fr/issues/126)

Pourriez **épingler** une **vertical transport** dans les repo, comme pour adresse ou geo ?
Cela nous aiderait pour éviter les erreurs d'affectation d'issues.

D'avance Merci,

**Comment by bboulesteix** [comment]
C’est fait. ✅ Le [ticket que vous avez créé](https://github.com/etalab/transport-site/issues/649) dans [le dépôt data.gouv.fr](https://github.com/etalab/data.gouv.fr) a par ailleurs été transférée dans ce dépôt, celui de [transport.data.gouv.fr](https://github.com/etalab/transport-site). Merci pour votre suggestion.
