### ISSUE TITLE
Lorsque la recherche est vide, tout remonter

### ISSUE THREAD

**Issue by Tristramg** [etalab/transport-site#638]
Actuellement on ne remonte rien : https://transport.data.gouv.fr/datasets?_utf8=%E2%9C%93&q=

**Comment by l-vincent-l** [comment]
Je ne comprends pas, tu veux faire une redirection vers /datasets avec un flash error ?

**Comment by Tristramg** [comment]
Je sais pas trop, juste afficher /datasets ? c’est dans le cas où on ne cherche rien, pas dans le cas où la recherche ne retourne rien
