### ISSUE TITLE
Redesigner la page d'un jeu de données

### ISSUE THREAD

**Issue by sabinesafi** [etalab/transport-site#659]

**Comment by antoine-de** [comment]
Pour rappel, l'idée est de maintenant avoir 2 pages à la place de la page `Dataset`: une pour le dataset, et 1 par ressource de ce dataset.

Pour commencer à designer les pages, je propose de lister les informations pertinentes pour les 2 pages (le découpage est sujet à discussion)

## Page Dataset
* logo
* titre
* lien datagouv
* date de création
* date de dernière mise à jour
* discussions ?
* mots clés
* liste des différentes ressources

### cartouche des ressources
la je suis encore moins sur de ce que je raconte, mais j'ai l'impression que ca serait bien d'avoir directement visible sur une ressource:
* son type (Transport théorique / transport temps réel / VLS/...)
* si c'est à jour
* date de validité
* lien de téléchargement
* modes de transport
* si la ressource est valide ?


## Page ressource
* toutes les metadatas
* descriptions
* lien mis en valeur vers la page de validation
* flag si la ressource n'est pas valide ?
* conditions d'utilisation
* date de création
* date de dernière mise à jour
* discussion ?


## je sais pas trop où ranger
* les discussions je sais pas trop où faut les mettre. J'ai l'impression que ca devrait être sur la ressource, mais que les mettre au niveau du dataset les rendraient plus visibles. ou sinon les 2 ?
* condition d'utilisation. c'est au niveau de la ressource non ?
* réutilisation. au niveau du dataset ?


Voilou, vous en pensez quoi ?

**Comment by sabinesafi** [comment]
Merci pour ce premier travail :D
La liste des items pour la page ressource m'interroge... j'ai pas l'impression que ça soit justifié d'avoir une page supplémentaire pour ces infos. Les réutilisateurs veulent juste savoir d'un coup d'oeil le format du fichier et si c'est à jour ou pas... 
D'autant qu'on est partis pour 1 GTFS = 1 page dataset, 1 GTFS = 1 page dataset, etc. non ?

**Comment by sabinesafi** [comment]
Est-ce que c'est utile ces infos-là : 
- lien datagouv
- date de création
- date de dernière mise à jour

**Comment by sabinesafi** [comment]
Questions en vrac : 

1. - Est-ce que c'est utile de renvoyer vers la page data.gouv ?
2. - "modes de transport" dans cartouche des ressources : ça serait quoi ? on a cette info actuellement ?
3. - pour les ressources communautaires, met-on aussi le rapport de validation, date de validité etc. ? Techniquement on peut le faire mais je suis partagée quant à si c'est notre rôle.

**Comment by sabinesafi** [comment]
@l-vincent-l je mets ici mes suggestions sur la version actuelle :

**Titre de la page :**
Il faudrait qu'il soit généré dynamiquement en fonction du type de données parce que là c'est la foire un cas sur 2 (on n'a pas le nom du réseau ou de l'agglo, noms fantaisistes etc.). Parfois il y a plusieurs jdd qui cohabitent ex : 1ere couronne/2ème couronne, été/hiver... mais on devrait surtout essayer de faire publier en tant que ressource d'un même dataset je pense. Penser au cas : page  TR "seul" (zenbus) et page théorique + TR --> pas le même titre.
Est-ce utile que je fasse une liste des titres de page en fonction du type de données ?

**Identifiez vous pour vous abonner au jeu de données.**
On peut le mettre dans la dernière section, sous Territoires couverts ? Là avec *Vous devez être identifié pour commencer une discussion.* ça fait beaucoup de liens sur un petit espace. Sinon on met juste "S'abonner à ce jdd" et ça demandera de se logger dans tous les cas j'imagine.

**Réutilisations**
Ils ont tendance à écrire des descriptions très longues... on pourrait soit couper brutalement à X caractères et mettre un [...] à la fin (et y'a les liens en dessous pour en savoir plus), soit mettre un "show more" comme plus haut.

**Validations GTFS**
Vu qu'on a un peu de place sur 2 lignes on pourrait expliciter en *Voir le rapport de validation GTFS*.

**Vous réutilisez ce jeu de données ?**
Il faudrait mettre un point à la fin de la ligne plz

**Display more**
S'affiche en anglais

**Absence de validation GTFS**
J'ai mis un mot là-dessus ailleurs sur GH, pour être un peu explicite quand on arrive pas à valider le fichier (à priori c'est mauvais signe... faudrait le mettre quelque part).
Et quand c'est pas validé (je crois), ça affiche *Autres ressources* au lieu de Ressources GTFS et associées. Est-ce qu'on pourrait pas mettre systématiquement que c'est du GTFS et associé à partir du moment où c'est du TC théorique?

**Comment by l-vincent-l** [comment]
> @l-vincent-l je mets ici mes suggestions sur la version actuelle :
> 
> **Titre de la page :**
> Il faudrait qu'il soit généré dynamiquement en fonction du type de données parce que là c'est la foire un cas sur 2 (on n'a pas le nom du réseau ou de l'agglo, noms fantaisistes etc.). Parfois il y a plusieurs jdd qui cohabitent ex : 1ere couronne/2ème couronne, été/hiver... mais on devrait surtout essayer de faire publier en tant que ressource d'un même dataset je pense. Penser au cas : page TR "seul" (zenbus) et page théorique + TR --> pas le même titre.
> Est-ce utile que je fasse une liste des titres de page en fonction du type de données ?
> 
Vu la longueur du commentaire je pense que ça demande une réflexion un peu plus longue.

> **Identifiez vous pour vous abonner au jeu de données.**
> On peut le mettre dans la dernière section, sous Territoires couverts ? Là avec _Vous devez être identifié pour commencer une discussion._ ça fait beaucoup de liens sur un petit espace. Sinon on met juste "S'abonner à ce jdd" et ça demandera de se logger dans tous les cas j'imagine.
> 
J'aime bien le laisser ici, ça correspond à un abonnement aux discussions. Si on le met autre part, on pourrait croire qu'on s'abonne à d'autres choses sur le jeu de données.
> **Réutilisations**
> Ils ont tendance à écrire des descriptions très longues... on pourrait soit couper brutalement à X caractères et mettre un [...] à la fin (et y'a les liens en dessous pour en savoir plus), soit mettre un "show more" comme plus haut.
> 
Fait
> **Validations GTFS**
> Vu qu'on a un peu de place sur 2 lignes on pourrait expliciter en _Voir le rapport de validation GTFS_.
> 
fait
> **Vous réutilisez ce jeu de données ?**
> Il faudrait mettre un point à la fin de la ligne plz
> 
fait
> **Display more**
> S'affiche en anglais
> 
fait
> **Absence de validation GTFS**
> J'ai mis un mot là-dessus ailleurs sur GH, pour être un peu explicite quand on arrive pas à valider le fichier (à priori c'est mauvais signe... faudrait le mettre quelque part).
> Et quand c'est pas validé (je crois), ça affiche _Autres ressources_ au lieu de Ressources GTFS et associées. Est-ce qu'on pourrait pas mettre systématiquement que c'est du GTFS et associé à partir du moment où c'est du TC théorique?

Non ça peut être d'autres choses, là ça va être une correction de bug plus importante

**Comment by sabinesafi** [comment]
> Identifiez vous pour vous abonner au jeu de données.
>> J'aime bien le laisser ici, ça correspond à un abonnement aux discussions. Si on le met autre part, on pourrait croire qu'on s'abonne à d'autres choses sur le jeu de données.

Ok j'avais pas compris que c'était pour s'abonner aux discussions (du coup ok avec toi sur la position). Je propose le wording suivant : *S'abonner aux discussions sur ce jeu de données*

> Absence de validation GTFS
>> Non ça peut être d'autres choses, là ça va être une correction de bug plus importante

D'acc, en tout cas quasi tous les 6-7 jdd que j'ai ouverts au hasard n'affichent pas les méta-données et rapport de validation donc j'ia l'impression que c'est important de régler ça (issue à part ?).

**Double message d'inscription pour commenter**
Sur https://prochainement-transport.cleverapps.io/datasets/offre-de-transport-du-reseau-tango-de-nimes-metropole-gtfs/
en bas des commentaires j'ai 2 appels à me connecter. On peut en enlever un, et/ou je raccourcirais bien la phrase en : *Commencer une discussion* 

Ça commence à être très cool :D

**Comment by sabinesafi** [comment]
https://transport.data.gouv.fr/datasets/reseau-de-bus-urbain-horizon-toutes-periodes-1/
On pourrait sortir le "autres jeux de données par ce producteur" de la poubelle ?
J'ai une préférence pour le mettre au dessus des discussions parce que ça prend peu de place, mais sous les discussions et au dessous de la poubelle m'irait aussi.

**Comment by Tristramg** [comment]
Sur les commentaires j’ai l’impression que c’est bon.

J’ai créé une issue spécifique #768 pour les autres jeux de données.

Je ferme cette issue (n’hésitez pas à rouvrir si vous pensez que c’est trop tyranique comme approche).

Créons des issues pour les milliers de petits plis à écraser au fer à repasser.
