### ISSUE TITLE
Avoir les JDD les plus à jour de ce qui existe en ligne

### ISSUE THREAD

**Issue by sabinesafi** [etalab/transport-site#661]
MyBus : "Marseille, Nice : MAJ quotidiennement voire plusieurs fois par jour --> on passe par le site de l'agglo directement"

**Comment by l-vincent-l** [comment]
Tu vas avoir l'impression que je me défausse, mais on s'appuie sur data.gouv.fr qui moissonne les jeux de données une fois par jour (ce qui ne parait pas délirant).
Je ne vois pas comme ça de solution magique pour mettre à jour plus souvent les jeux de données.

**Comment by sabinesafi** [comment]
Le sujet vient de MyBus : "Il y a des agglos où on passe direct par le site de l’agglo. c’est plus souvent MAJ sur le site que chez transport.data.gouv.fr (Marseille, Nice : MAJ quotidiennement voire plusieurs fois par jour)"

Si on ne peut rien faire sur la fréquence de moissonnage, ça règle effectivement la question.
