### ISSUE TITLE
Savoir facilement si un JDD est à jour

### ISSUE THREAD

**Issue by sabinesafi** [etalab/transport-site#662]
réut : ""actuellement on doit ouvrir les données pour voir la date indiquée dedans car elle est plus exacte que celle déclarée en méta données"

Voir l'exemple des données transgironde qui renvoie 20 résultats et impossible de savoir facilement qu'est-ce qui est à jour ou pas :
https://www.data.gouv.fr/fr/search/?q=transgironde

**Comment by Tristramg** [comment]
Qu’est-ce qui ne va pas dans le fonctionnement actuel ?

Il y a une date issue du GTFS
https://transport.data.gouv.fr/datasets/arrets-itineraires-et-horaires-theoriques-des-reseaux-de-transport-des-membres-de-nouvelle-aquitaine-mobilites/

Cette date est signalée aussi dans l’api s’ils souhaitent automatiser.

Du coup je ne vois pas trop quelle action serait de notre côté.

**Comment by l-vincent-l** [comment]
On peut peut être remonter cette information sur la page de recherche.

**Comment by sabinesafi** [comment]
Oui, la demande porte notamment sur la page de recherche, et sur la page d'un JDD.

MyBus : "les méta données divergent des infos contenues dans le GTFS. Difficile de savoir quel fichier est à jour ou pas. C'est un travail supplementaire d’ouvrir le GTFS pour voir que la validité est expirée".

Ça peut marcher avec #667.

**Comment by Tristramg** [comment]
On affiche clairement la date de validité maintenant
