### ISSUE TITLE
Site en d'autres langues

### ISSUE THREAD

**Issue by sabinesafi** [etalab/transport-site#663]
Maps.me : ne veulent pas utiliser tant que c'est pas en anglais.
transit : les gens qui vont récupérer les données ne sont pas francophones... galère

**Comment by l-vincent-l** [comment]
Pour l'instant il y a une version minimale en anglais ici https://transport.data.gouv.fr/datasets?locale=en
Aller plus loin va être compliqué, tout le texte est récupéré de data.gouv.fr.

Peut être qu'il faut afficher comme titre le nom de la commune que l'on a renseigné ?

**Comment by sabinesafi** [comment]
Je me demande si on pourrait utiliser la traduction de Google : https://translate.google.com/translate?sl=fr&tl=en&u=https%3A%2F%2Ftransport.data.gouv.fr%2F%3Flocale%3Den

C'est un peu moche mais la traduction m'a l'air pas correcte, donc en mode Quick win... ? 
Bon par contre quand on commence à utiliser le moteur de recherche ça suit plus.

Si rien n'est possible sans faire pas mal de dév, on a oublier pour le moment.

**Comment by NicolasBerthelot** [comment]
Closed because : https://github.com/etalab/transport-site/issues/1333
