### ISSUE TITLE
Afficher le nombre de téléchargements pour chaque jeu de données

### ISSUE THREAD

**Issue by sabinesafi** [etalab/transport-site#664]
- [ ] Avoir un compteur qui renvoie des résultats au minimum "crédibles"
- [ ] Afficher ce compteur sur à côté du JDD

**Comment by Tristramg** [comment]
Ça me parait compliqué.

Le comptage sur data.gouv.fr ne semble pas fiable. Dans certains cas on donne directement le lien vers la plateforme.

Il faudrait qu’on mettre un lien d’obfuscation chez nous, pour compter. C’est rajouter une fragilité potentielle.

De plus, un seul téléchargement par un gros opérateur aura un très grand impact mais donnera une impression déceptive.

**Comment by Tristramg** [comment]
Je ferme : il n’y a pas de moyen de vraiment savoir.
