### ISSUE TITLE
Signaler les nouveaux datasets pas encore intégrés par le réutilisateur

### ISSUE THREAD

**Issue by sabinesafi** [etalab/transport-site#665]
Transit : "créer un compte pour savoir quel flux on a intégré, quel flux il nous manque? les jeux qui sont déjà téléchargés, les jeux qui nous manque."
--> les nouveaux JDD
--> Les MAJ

**Comment by NicolasBerthelot** [comment]
La problématique du suivi des mises à jour et de la publication de nouveaux jeux de données sur transport.data.gouv.fr est une problématique très intéressante qui doit être développée à moyen termes. A court termes, il faut déjà comprendre le fonctionnement du flux RSS qui est un niveau minimal d'information sur la publication de nouveaux jeux de données et peut-être leur mise-à-jour : https://github.com/etalab/transport-site/issues/1498
