### ISSUE TITLE
Prévenir automatiquement le producteur de données avant expiration de ses données - Mettre un commentaire 1 semaine avant expir

### ISSUE THREAD

**Issue by sabinesafi** [etalab/transport-site#666]
- idem que ce qu'on reçoit actuellement par email, mais direct aux AOM ou par commentaire

- il faudrait pouvoir débrayer pour les AOM qui n'en ont pas besoin mais au pire on peut attendre que des AO réclament pour mettre ça en place.

**Comment by antoine-de** [comment]
fixed by #775

**Comment by Tristramg** [comment]
On en est où de cette issue ?

**Comment by antoine-de** [comment]
normalement c'est tout bon

**Comment by Tristramg** [comment]
Alors on ferme ! :tada:
