### ISSUE TITLE
[A rediscuter] Rendre la page de résultats de validation lisible

### ISSUE THREAD

**Issue by sabinesafi** [etalab/transport-site#669]
- [ ] Mieux faire comprendre la sévérité de l'erreur remontée

**Comment by Tristramg** [comment]
Je verrais bien :

* [ ] griser les tests où il n’y a pas d’erreur
* [ ] trier les erreurs par sévérité
* [ ] lien vers la documentation d’une erreur
* [ ] reformater la liste des erreurs (potentiellement un formatage spécifique pour certaines erreur)
* [ ] Pas du tout prioritaire : mini-widgets montrant ce qui ne va pas (cas des arrêts trop proches)

**Comment by antoine-de** [comment]
pour le 1er point, je ne mettrais que les erreurs du fichier, j'ai l'impression que le reste brouille le message.

**Comment by Tristramg** [comment]
Je propose de fermer l’issue. Peut-être qu’on fera une vraie passe de redesign, mais pour le reste, ça sera par petites touches.
