### ISSUE TITLE
Trouver une AOM incluse dans un jeu régional depuis la search bar

### ISSUE THREAD

**Issue by l-vincent-l** [etalab/transport-site#709]
ex : quand je cherche Limoges ou Gironde je trouve pas or c'est inclus dans le jeu Nouvelle Aquitaine

**Comment by l-vincent-l** [comment]
Je ne suis pas sur de comment gérer cette problématique.
L'information n'est pas présente en tant que telle dans le fichier GTFS. Les noms des agences ne permettent pas de deviner quelle est la ville qui y est rattachée.
Faire une couverture géographique simple et en déduire la couverture amènera des erreurs. (il y a de mauvaises coordonnées, et parfois ces jeux de données inclus des données nationales).
Il reste donc le remplissage à la main…

**Comment by l-vincent-l** [comment]
On va le faire à la main pour l'instant

**Comment by sabinesafi** [comment]
Je peux faire le manuel avec vous si c'est pas plus long de me montrer que de le faire vous-mêmes ;)
