### ISSUE TITLE
mettre un lien vers la page temps réel sur la tuile TR

### ISSUE THREAD

**Issue by antoine-de** [etalab/transport-site#749]
mettre un lien vers https://transport.data.gouv.fr/real_time sur la tuile temps réel (pour le moment la page https://transport.data.gouv.fr/datasets?filter=has_realtime)

**Comment by sabinesafi** [comment]
Voir si on parle de la page de doc TR (gitbook) ou de la page qui liste les flux non normalisés

**Comment by Tristramg** [comment]
fermé par #764
