### ISSUE TITLE
Clarifier la page Validation

### ISSUE THREAD

**Issue by sabinesafi** [etalab/transport-site#750]
Sur le premier écran sur https://transport.data.gouv.fr/validation, on peut rendre plus explicite pour des utilisateurs pas forcément avertis : 
- Titre : _Tester la conformité d'un fichier GTFS_
- Intitulé du bouton : Envoyer

Sur le 2ème écran : 
- Titre : Rapport de conformité au standard GTFS
- Coquille : _Cette validation **ne** concerne que la structure des données..._

**Comment by sabinesafi** [comment]
Le fait que la colonne de gauche commence plus haut que le titre est un peu perturbant, possible de la faire commencer au même niveau ?

**Comment by Tristramg** [comment]
Je suis pas convaincu par _tester la conformité_. Dans ma tête y’a une notion très binaire et administratif avec un gros tampon « conforme », alors qu’on étudie la qualité globale, aussi pour signaler des choses surprenantes.

Je propose : _Analyser la qualité d’un fichier GTFS_, et _Rapport de l’analyse de fichier GTFS_

**Comment by sabinesafi** [comment]
J'avais un doute sur "qualité" car ça peut aussi représenter la qualité de la donnée elle-même. Mais partons sur qualité et à l'occasion je demanderai à des AO ce qu'elles en comprennent :)
