### ISSUE TITLE
Meilleure découvrabilité GBFS

### ISSUE THREAD

**Issue by Tristramg** [etalab/transport-site#751]
Faire en sorte que transport.data.gouv.fr/gbfs/ liste tous les réseaux (et que /nantes/ redirige vers /nantes/gbfs.json)

**Comment by antoine-de** [comment]
closed by https://github.com/etalab/transport-site/pull/790, but I did not do the forwarding (`/nantes` to `/nantes/gbfs.json`) do you want me to do it ?
the `/gbfs` already gives link to `/<dataset>/gbfs.json`
