### ISSUE TITLE
Bug sur la detection du type d'une ressource

### ISSUE THREAD

**Issue by l-vincent-l** [etalab/transport-site#758]
Actuellement pour détecter si une ressource est du GTFS on le fait dans import_data (mal, on prend en compte par exemple la description du dataset), et aussi dans dataset_view.
Il faudrait recentraliser ces mécanismes dans Dataset.Resource

**Comment by antoine-de** [comment]
closed by #791 no ?

**Comment by Tristramg** [comment]
I think this is ok for know. Let’s see over time.
