### ISSUE TITLE
Refonte de la présentation des datasets

### ISSUE THREAD

**Issue by antoine-de** [etalab/transport-site#759]
Le but est d'améliorer la présentation d'un dataset dans la page https://transport.data.gouv.fr/datasets

## l'idée est d'afficher:
- non pas le format mais le type de données (transport en commun, like sharing etc.)
- territoire
- nom du réseau
- titre datagouv
- idéalement : afficher les formats de toutes les ressources (et gifs plutôt que zip)
- temporairement : le nom du dataset sur datagouv en petit (jusqu’à la fin de l’été)

### ce que ca donne en fonction des types de datasets
———
Nantes Agglo
Transports en commun - théorique et temps réel
Réseau de bus Nantes : disponibilité en temps réel
—
réseau : TAN     [GTFS] [GTFS-RT]
———

———
Nantes Agglo
Disponibilité des vélos en libre service
Vélos libre service Nantes Bicloo : disponibilité en temps réel
—
réseau : Bicloo     [GBFS]
———

———
Nantes Agglo
Disponibilité des vélos en libre service
Vélos libre service Nantes Bicloo : disponibilité en temps réel
—
réseau : Bicloo     [GBFS]
——— 

### avant
![image](https://user-images.githubusercontent.com/3987698/60198203-978d9000-9830-11e9-8a6c-d5b6aaf02a2f.png)

### aprés

(avec une bonne passe sur les styles, mais  c'est pour avoir une idée des infos affichées:
![image](https://user-images.githubusercontent.com/3987698/60198177-893f7400-9830-11e9-8a11-0f69f2f1aa38.png)

qu'est ce que vous en pensez ?

**Comment by sabinesafi** [comment]
Ok pour moi :D

Commentaires sur le style seulement : 
- Mettre *Grand Guéret - Transports en commun* sur une seule ligne
- *Réseau : Agglo'bus* en pas gras voire en plus petit
- Badge GTFS : je le ferai + ressortir par le positionnement, soit tout à droite de la ligne, soit tout à gauche, soit tout à gauche et sur la ligne du dessus (la ligne "principale")
