### ISSUE TITLE
Integrate template styles

### ISSUE THREAD

**Issue by maukoquiroga** [etalab/transport-site#76]
In order to become data.gouv.fr accepted ASAP.

- [x] Base styles #84
- [x] Fonts #86 #95 
- [x] Colours #88 #96
- [x] Header #90
- [x] Footer #90 
- [x] Grid #104

**Comment by l-vincent-l** [comment]
Thimy told me the styles aren't ready yet

**Comment by maukoquiroga** [comment]
Not an issue, we'll do incrementally not in waterfall.
