### ISSUE TITLE
Typo sur carte de déploiement Beaume ==> Baume 

### ISSUE THREAD

**Issue by margot-sanchez** [etalab/transport-site#762]
Il s'agit de la Communauté d'Agglomération Sud Sainte Baume et non B**e**aume. 
![image](https://user-images.githubusercontent.com/15428433/60445063-c46de880-9c1e-11e9-8f8b-8eca9a15073d.png)

**Comment by Tristramg** [comment]
Merci !

Corrigé avec une requêt en base de prod.
