### ISSUE TITLE
Espacements + taille logo page dataset

### ISSUE THREAD

**Issue by sabinesafi** [etalab/transport-site#778]
- [Sur cette page](https://transport.data.gouv.fr/datasets/arrets-horaires-et-parcours-theoriques-des-reseaux-naq-pau-nva-m/) le logo nouvelle Aquitaine Mobilités apparaît très petit, les AO apprécient que le logo soit un peu plus visible.
- [Sur cette page](https://transport.data.gouv.fr/datasets/agglobus-2018-2019/) le logo est plus haut mais bizarrement croppé.
- Dans le bloc de texte de description sur fond gris, est-ce qu'on pourrait enlever un peu de marge/padding pour faire remonter les fichiers à télécharger sur la page ? Idem pour l'espace sous le logo peut-être.

**Comment by l-vincent-l** [comment]
Je ferme cette issue, j'en ai créé une par problème, je préfère c'est plus simple pour discuter point par point et lier les bouts de codes aux issues
