### ISSUE TITLE
Afficher un message sur la page dataset quand le fichier GTFS est "parfait"

### ISSUE THREAD

**Issue by sabinesafi** [etalab/transport-site#785]
[edit] Par exemple ici, le rapport de validation ne s'affiche pas parce que le fichier n'a pas d'erreur.
https://transport.data.gouv.fr/datasets/agglobus-2018-2019/

On pourrait écrire "0 erreurs" (ou bien "fichier irréprochable" ?). Je me demande s'il faut mettre quand même le lien vers le rapport de validation.

**Comment by antoine-de** [comment]
c'est en fait un bug d'affichage, on n'affiche pas le lien quand il n'y a aucune erreur, et c'est un des rares jeux 'parfait' :stuck_out_tongue_winking_eye: 

Il faut qu'on corrige ca, merci !

**Comment by sabinesafi** [comment]
\o/
Je modifie l'issue en fonction ou en crée une autre ?

**Comment by antoine-de** [comment]
non non c'est bon cette issue suffit je pense (mais ca peut valoir le coup de changer le titre)
