### ISSUE TITLE
Modification des tuiles de la home

### ISSUE THREAD

**Issue by sabinesafi** [etalab/transport-site#797]
Il faudrait mettre les données aériennes et ferroviaires dans en cours et rajouter les tuiles Transport à la demande et Aménagements cyclables dans le prochainement.
(en fonction de #784)

Pour les nouveaux picto, j'ai demandé à Thimy si elle pouvait les créer.

**Comment by l-vincent-l** [comment]
J'ai splitté en deux issues #800 et #801
