### ISSUE TITLE
Ajouter tuile comptage mobilité dans les données à venir

### ISSUE THREAD

**Issue by l-vincent-l** [etalab/transport-site#801]
Ajouter les tuiles Transport à la demande et Aménagements cyclables dans le prochainement.
(en fonction de #784)

Pour les nouveaux picto, j'ai demandé à Thimy si elle pouvait les créer.

**Comment by l-vincent-l** [comment]
Split de #797

**Comment by antoine-de** [comment]
ping @NicolasBerthelot @Miryad3108 vous pensez qu’il faut qu’on rajoute la tuile TAD ?

**Comment by Miryad3108** [comment]
Dans "A venir", il manque la tuile pour le "Comptage vélo"

On a également eu plusieurs fois une remarque de la part des membres de l'Association des Acteurs de l'Autopartage concernant le picto pour les "Véhicules en free-floating" : pourquoi ne pas mettre également une voiture ? (ou remplacer la trottinette par une voiture)

Peut être retiré la tuile sur les travaux sur voirie pour la remettre quand on travaillera vraiment sur le sujet ? C'est là depuis quelques mois, ça pourrait donner l'impression qu'on avance pas

**Comment by thbar** [comment]
Je m'assigne ce point, que je dois traiter avant l'OpenLab du vendredi 23.04.

**Comment by AntoineAugusti** [comment]
@etalab/transport-bizdev Toujours d'actualité ? On pense avoir des données dans un avenir relativement proche ? Une idée d'icône ?

**Comment by Miryad3108** [comment]
Toujours d'actualité oui, les premières données sont prévues pour juin 2022 mais ça serait bien de faire apparaître la tuile dans "À venir dans les prochains mois" avant qu'elles soient publiées 

Il y avait une proposition de picto avec la nouvelle identité visuelle : https://drive.google.com/drive/folders/1A5EcHZmRfzi7OEZh5HXac3kmQ-1K5K_m
(mais je ne trouve pas l'image explicite)

**Comment by AntoineAugusti** [comment]
@thbar Souhaites-tu t'occuper de cette issue ? Tu étais assigné auparavant.

**Comment by Miryad3108** [comment]
La tuile comptage a été ajoutée : je ferme l'issue
