### ISSUE TITLE
Résultats de recherche : afficher les différents formats présents (GTFS + Netex...)

### ISSUE THREAD

**Issue by sabinesafi** [etalab/transport-site#812]
Nouvelle Aquitaine Mobilités a publié du GTFS + Netex pour toutes "ses" AOMs.
Dans la liste de résultats de recherche, pour Poitiers par ex, on affiche que Netex. On devrait afficher les 2 : Netex, GTFS 

<img width="1035" alt="Capture d’écran 2019-07-23 à 16 42 46" src="https://user-images.githubusercontent.com/16819425/61721764-4f975580-ad69-11e9-9255-46bdd6cd18bc.png">

**Comment by l-vincent-l** [comment]
C'est résolu sur https://prochainement-transport.cleverapps.io/datasets?_utf8=%E2%9C%93&q=poitiers
