### ISSUE TITLE
Impossible d'ajouter la fiche Zenbus de Quibéron (GTFS + RT)

### ISSUE THREAD

**Issue by sabinesafi** [etalab/transport-site#824]
Quand j'ajoute le dataset depuis le backoffice, j'ai un message d'erreur :
<img width="1245" alt="Capture d’écran 2019-08-21 à 15 37 01" src="https://user-images.githubusercontent.com/16819425/63436791-9c825080-c429-11e9-9a5c-d76ec483543c.png">

J'ai saisi Quibéron comme nom, 56186 comme code INSEE et public transport.

**Comment by sabinesafi** [comment]
Je n'arrive pas non plus à ajouter la nouvelle fiche de Saintes, là j'ai juste un écran blanc quand je valide le formulaire : 
<img width="964" alt="Capture d’écran 2019-08-21 à 15 59 26" src="https://user-images.githubusercontent.com/16819425/63438555-c721d880-c42c-11e9-87b9-e1073d869387.png">

**Comment by l-vincent-l** [comment]
Est-ce que tu peux mettre les valeurs des champs que tu as essayé de mettre ?

**Comment by sabinesafi** [comment]
<img width="1119" alt="Capture d’écran 2019-08-26 à 18 13 11" src="https://user-images.githubusercontent.com/16819425/63705358-37659b00-c82d-11e9-96ac-2a5b5f06932e.png">

**Comment by sabinesafi** [comment]
Up, j'ai réessayé et ça marche toujours pas :/
Alors que j'ai pu ajouter d'autres JDD TR.

**Comment by antoine-de** [comment]
ah c'est pas lié au travail en cours pour améliorer l'ajout d'un jeu de données pour trouver l'ao à partir d'un nom de ville @l-vincent-l ?
