### ISSUE TITLE
Affichage menu du haut en portable à améliorer

### ISSUE THREAD

**Issue by l-vincent-l** [etalab/transport-site#827]
Voici l'affichage du menu du haut sur un portable actuellement.
![image](https://user-images.githubusercontent.com/2757318/63586956-083bf900-c5a3-11e9-9b21-be30f519c5b8.png)
Peut être faudrait-il mettre un menu modal lorsque l'on est en portable

**Comment by antoine-de** [comment]
fixed by #833 no ?

**Comment by Tristramg** [comment]
Indeed, the menues are in a :hamburger: menu now.
