### ISSUE TITLE
Ajouter des filtres sur la liste de datasets

### ISSUE THREAD

**Issue by sabinesafi** [etalab/transport-site#829]
Filtres : 
- réseaux urbains
- réseaux interurbains
- tous les types de données qu'on a en tuiles sur la home

Use case pour interurbain/urbain : 
Tictactrip qui ne prend pas les réseaux urbains (Rome2Rio aussi il me semble), et qui doit parcourir, région par région, toute la liste pour trouver les jeux interurbains (régionaux). Situation inverse pour Mybus, transit...

Et peut-être aussi un moyen de filtrer là-dessus dans l'API ?

**Comment by l-vincent-l** [comment]
C'est une information qu'il faudra rentrer dans le backoffice si on veut la faire ressortir

**Comment by sabinesafi** [comment]
réseaux interurbains = publiés par les régions. tu penses qu'on ne peut pas utiliser cette info là, qu'on a déjà ?

**Comment by l-vincent-l** [comment]
Je peux essayer un truc comme ça, on va voir ce que ça va donner
