### ISSUE TITLE
Ajouter un lien Pour les développeurs dans le footer

### ISSUE THREAD

**Issue by sabinesafi** [etalab/transport-site#836]
Pour renvoyer vers https://doc.transport.data.gouv.fr/reutilisateurs/outils-pour-les-reutilisateurs.

**Comment by l-vincent-l** [comment]
Ça te va si je mets réutilisateurs plutôt que développeurs ?

**Comment by sabinesafi** [comment]
Alors je vais te laisser juger, mon point c'est qu'on a une API (voire plusieurs ? ainsi qu'un flux RSS) et que les personnes concernées ne le savent pas. Il me semble que c'est fréquent sur les portails OD (et autres services web d'ailleurs) d'avoir une section Développeurs. 

Qu'est-ce qui te paraîtrait logique en tant que dév ? peut-être qu'il faut une page spécifique qui liste nos APIs et autres trucs pour les dévs ?

**Comment by l-vincent-l** [comment]
C'est que je ne suis pas fan de mettre un lien avec pour texte `Développeurs` puis sur la page on parle de `Réutilisateurs`

**Comment by sabinesafi** [comment]
Sinon on met APIs ? Au moins c'est explicite.
Et si ça te gêne toujours, partons sur Pour les réutilisateurs
