### ISSUE TITLE
Ajouter le TR de St Etienne à la page non-standardisé

### ISSUE THREAD

**Issue by sabinesafi** [etalab/transport-site#840]
Leur API est accessible après authentification.
https://data.saint-etienne-metropole.fr/developper/api/f743da0e-22f1-11e8-baba-0a580af4063e

Il n'a pas su me dire si on peut obtenir l'état du réseau en une requête ou pas.

**Comment by sabinesafi** [comment]
Il y a également celui de Pau : https://getstopmonitoring.idelis.fr/GetStopMonitoring
Je demande plus d'infos sur le login, qui est obligatoire.

**Comment by antoine-de** [comment]
pour saint etienne, le portail n'offre pas de page non authentifiée pour lister l'api, je vais mettre du coup un lien vers le portail directement, je vois pas comment faire mieux :(

Pour pau, je ne trouve pas de page expliquant l'api ou comment récupérer un token. Tu en sais plus ?
