### ISSUE TITLE
Rajouter le lien vers le code source de la plateforme en footer

### ISSUE THREAD

**Issue by IshanB** [etalab/transport-site#846]
Le footer ne comprend pas le lien vers le Github, ça peut être top de le rajouter

**Comment by Tristramg** [comment]
Il y a un lien sur https://transport.data.gouv.fr/legal
Est-ce qu’on ne risque pas de faire du footer un gros fourre-tout ?

**Comment by IshanB** [comment]
Je ne le trouve pas très découvrable.
Je trouve que "jeux de données temps réel" n'a pas grand chose à faire là, et "analyser un jeu de données GTFS" devrait être dans le header à mon avis. 

Ce que je trouve plus intuitif : 
- les fonctionnalités de la plateforme sont dans le header (publier, valider, etc)
- les ressources annexes et les liens vers la doc sont en footer

**Comment by Tristramg** [comment]
Après discussions :
* suppression du lien temps réel (il y a déjà la tuile pour ça)
* passage de la validation dans le header
* code source du site en pied de page

**Comment by Tristramg** [comment]
C’est fait!
