### ISSUE TITLE
Compléter la légende de la carte de déploiement

### ISSUE THREAD

**Issue by sabinesafi** [etalab/transport-site#865]
Il manque le vert clair pour les régions où on a les données interurbaines.

**Comment by Tristramg** [comment]
Je pense qu’il faudrait renverser les couleurs et faire du shaming de ceux qui sont pas ouvert.

Ça simplifie les catégories sur la carte.

**Comment by fchabouis** [comment]
Closed by #1129 .
On a travaillé pour rendre cette carte plus lisible. Nous mettons maintenant en avant les régions partenaires du PAN. Nous n'avons pas encore la notion de jdd interurbain en base.
