### ISSUE TITLE
import more data from the dataset publisher

### ISSUE THREAD

**Issue by antoine-de** [etalab/transport-site#882]
It might be useful to import more information from the [data.gouv api](https://www.data.gouv.fr/fr/apidoc/#!/datasets/list_datasets)

We might want to import also the `owner` of the dataset (if the dataset was not created by an organization)

getting the `id` and the `url` of the `owner` and `organization` could be nice, as we would be able to return them in our own `/datasets` api

proposition of api:
```js
 {
        "aom": {
            "name": "Perpignan Méditerranée Métropole",
            "siren": "200027183"
        },
        "created_at": "2018-12-18",
        "datagouv_id": "5c18fc4b634f41320c6251e3",
        "id": "5c18fc4b634f41320c6251e3",
        "publisher": {                          // <-- new field
            "name": "Sankéo",
            "type": "organization",
            "organization": { // <---- if the type is "owner" (or "user"?), it would be a sub object with the same name
                  "id": "12",
                  "url": "http://bob.com/pouet",
            }
        },
}
```

**Comment by AntoineAugusti** [comment]
J'ai l'impression que pour le moment on ne peut qu'importer des datasets provenant d'organisations

https://github.com/etalab/transport-site/blob/a1e2d38041add1d1d9aaf21f21f218aefa62a167/apps/datagouvfr/lib/datagouvfr/client/datasets.ex#L60-L65

https://github.com/etalab/transport-site/blob/a1e2d38041add1d1d9aaf21f21f218aefa62a167/apps/transport/lib/transport_web/api/controllers/datasets_controller.ex#L163-L168

À voir si on veut faire évoluer ça un jour. En revanche stocker ID et URL parait être pertinent plutôt que d'utiliser des noms.

**Comment by thbar** [comment]
Besoin pas crucial à ce stade, on fait un gros ménage, je clôture.
