### ISSUE TITLE
Améliorer la recherche

### ISSUE THREAD

**Issue by Tristramg** [etalab/transport-site#890]
Voici le verbatim des retours qu’on a sur la recherche. Potentiellement à découper en sous-tâches selon la pertinence.

>>>
   - page d'accueil: on  tombe sur "trouvez un  jeu  de données",  mais on  ne sait pas comment faire;  ce n'est que si  l'on  fait au  hasard une recherche que l'on  commence à  découvrir,  à  partir des résultats de cette recherche,  comment cela fonctionne;  cela ne semble pas pleinement satisfaisant; ne devrait-il  pas y  avoir en  haut à  droite un  onglet supplémentaire :  chercher un  jeu  de données?

   - filtres:
          - la sélection par les régions me semble insuffisante ;  elle introduit en  outre une dissymétrie entre catégorie de territoires, qui  n'est pas satisfaisante ;  ne faut-il  pas une possibilité de tri par région, par autorité organisatrice urbaine et par opérateur de transport ( Air France, Tisseo,...);   cela permettra de repérer les AO n'ayant pas ouvert leurs données,  ce qui  commence à  nous intéresser;  en outre,  il  faut traiter correctement les cas particuliers et s'interdire un  "national" dans la liste des régions;
             en  outre rien  ne justifie que "transilien"  soit classé dans national  
     
         -  les types de données:  
                      "transport public" ne me semble pas un  type de données;  la juxtaposition  de "transport public" ( pour désigner les horaires théoriques du  transport public) et de temps réel ( pour désigner les horaires en  temps réel du  transport public) me semble prêter à  confusion;
                       ne vaut-il  pas mieux écrire:
                                  disponibilité en  temps réel  du  vélo  en  partage;
                                   horaires théoriques des services réguliers de transport  public
                                   horaires en  temps réel des services réguliers de transport public
       Certes,  il  y  a aujourd'hui  principalement des horaires sur le PAN;  il n'en  faut pas moins anticiper la présence d'autres types de données demain ( tarifs,....) 

            -  comment rechercher les "trains"  d'une d'une "région"  , sachant qu'ils se trouvent :
                               - dans le fichier de la région,  parfois ;  par exemple:  Bretagne transport public
                                - dans le "national",  fichier de l'ensemble des TER
                si  je tape,  "bretagne train", j'obtiens un  résultat,  mais "nouvelle aquitaine  train" ne donne rien;

            - si  je cherche "ferries",  équivalent de "train", je ne trouve rien;  mais "maritime" donne des résultats ;  mais comment trouver la nomenclature des modes?   
                        
 
  -  sur la mention  "jeux de données valides disponibles":  je n'ai pas trouvé d'explication  sur ce qu'était un  jeu  "valide";

**Comment by antoine-de** [comment]
modification du dataset `Transilien`, pour le rattacher à idf

**Comment by Tristramg** [comment]
Pour information :

Si on a ajouté les filtres par région, c’est parce que c’était une demande récurrente des réutilisateurs et qu’il y a assez peu de régions.

C’est pas envisageable sous cette forme-là pour les noms de réseaux ou les communes qui n’ont pas de données. Mais on fera une issue spécifique pour savoir comment on veut afficher les données de communes sans données

**Comment by antoine-de** [comment]
Vous pensez pas qu'on pourrait remplacer la liste des régions par un champs de recherche avec autocomplétion sur region/aom/(ville ?) ?

![image](https://user-images.githubusercontent.com/3987698/69823423-b984a780-1200-11ea-8c15-c983f54bf90d.png)

on perd le nombre de jdd / region, mais la page serait peut etre plus lisible, et on pourrait faire de l'autocompletion pour guider la recherche

**Comment by antoine-de** [comment]
D'une discussion en interne, il ressort que la typologie en verticale de données est peut etre trop limitée.

Un consensus à base de "tag" (donc plusieurs catégories par dataset) se dégage.

Maintenant faut qu'on trouve les bons tags :stuck_out_tongue_winking_eye:

**Comment by Tristramg** [comment]
Je ferme, car on a créé deux issues #936 et #902 pour mieux traiter les cas particuliers.
