### ISSUE TITLE
Affichage sur grand écran

### ISSUE THREAD

**Issue by taniki** [etalab/transport-site#894]
![Screenshot_2019-11-07 transport data gouv fr](https://user-images.githubusercontent.com/27315/68419883-5ec8d480-019b-11ea-8fd3-9343438519bb.png)

**Comment by fchabouis** [comment]
Salut @thimy ,
J'ai l'impression que l'on pourrait soit une image qui se "colle bien avec elle même" pour faire un truc du style :

![image](https://user-images.githubusercontent.com/15341118/73861646-99dfb000-483d-11ea-8ad0-c24d983891b8.png)

Mais ca risque de faire chargé, et puis il faudrait enlever le soleil !

Ou bien juste avoir une seconde image avec l'arche, le bitume et le ciel qui continuent plus loin que le reste et dans le css, charger ce nouveau background  extra wide à la place du précédent. J'ai essayé de le faire mais je suis vraiment naze avec inkscape :D
Mais dans l'idée :

![image](https://user-images.githubusercontent.com/15341118/73862210-8719ab00-483e-11ea-9b0e-93db020307ab.png)

Ca permettrait d'éviter que l'illustration devienne trop grande (en hauteur) sur les grands écrans. Tu en penses quoi ?

En tout cas si tu fais une nouvelle image, je peux me charger de l'intégrer sur le site :)

**Comment by thimy** [comment]
Visiblement github supporte pas l'upload de svg, je t'envoie ça sur slack :P
