### ISSUE TITLE
Améliorer la page stat

### ISSUE THREAD

**Issue by antoine-de** [etalab/transport-site#896]
je met ici la carte d' @IshanB du [github project](https://github.com/orgs/etalab/projects/1)

COMPLETER LA PAGE STATS AVEC LES AUTRES VERTICALES
- Rajouter une carte pour le temps réel
- Rajouter une carte pour les VLS
- Rajouter des statistiques pour les lieux de covoiturage lorsque la base sera publiée
- Esthétique et lisibilité

**Comment by antoine-de** [comment]
idée: on pourrait faire une carte pour présenter aussi les autres verticales.

## Temps réel TC (même si c'est pas vraiment une verticale)

### carte
Voici une idée de carte pour visualiser notre (pauvre) couverture temps réel (générée à partir des jdd en gtfs-rt et de la page [real_time](https://transport.data.gouv.fr/real_time):

![image](https://user-images.githubusercontent.com/3987698/68940567-6be95300-079b-11ea-89d2-73f4b7776a91.png)

### stats brutes
* nb jdd standard
* nb jdd non standard

## VLS
carte: on pourrait faire la même chose que le temps réel en affichant les AO avec un jdd de vls.

### stats brutes
* nb jdd GBFS
* nb jdd convertis


## Covoit

## Données routieres

## IRVE


## Questions

* Ca vaudrait pas aussi le coup de mettre en valeur le nombre de réutilisateurs ?
* Il ne faudrait pas aussi parler de format dans chaque verticale  ? genre le nombre de jdd en GTFS/Netex/gtfs-rt/siri/...
 ca pourrait aider le discours

**Comment by antoine-de** [comment]
Aprés un point, on part sur une mise en page du genre:
![image](https://user-images.githubusercontent.com/3987698/69139731-06f26d80-0ab9-11ea-9d9f-1154b6485d5a.png)

On fait une carte pour chaques verticales.
On met en valeur les réutilisations/eurs

et les formats quand c'est possible.

**Comment by IshanB** [comment]
Je me demande s'il ne faut pas mieux clarifier les différents types de modes de transport.

En réalité, il y a comme le mentionnait Antoine Martin, trois types de niveaux : 
- National (TGV, AirFrance, Lieux de covoiturage, borne de recharge, cars Macron)
- Régional (TER, lignes interurbaines, chemins de fer corse, éventuellement les cars privés comme Paris - Beauvais) 
- Agglomération ou urbaines (vélos, métros, tram, bus)

Parfois, il y a une distinction à faire entre : 
- Statique (GTFS)
- Temps réel (GTFS-RT)

Enfin, les conventions de nommage ne sont pas harmonisées, ni rigoureusement correctes. 
Pour les métros, trams, bus : on parle de "transports en commun", qui n'est pas une acception très claire (le train de banlieue est un transport en commun). Bernard propose "lignes régulières de transport", mais c'est un peu jargonneux. 

Wikipedia dit : 

> Le « transport collectif » peut être distingué du « transport en commun » car un transport collectif désigne un « ensemble des modes de transport mettant en œuvre des véhicules adaptés à l'accueil simultané de plusieurs personnes ». Parmi ces modes de transports, on retrouve les « transports en commun (bus urbains, rames de métro, tramways et trains de banlieue) et l'utilisation d'avions, de bateaux, de trains et de véhicules routiers ».
>Par ailleurs, le terme « transport public » est souvent utilisé en France pour désigner le « transport en commun » affrété par une entité publique (commune, département, etc.). Cela peut prêter à confusion car tous les types de transport en commun ne sont pas forcément confiés au pouvoir public, et le transport public peut aussi être associé au transport de marchandises. »

Suggestions : 
- Spécifier transport en commun (metro, tramways, bus urbains, trains de banlieue) avec une petite fenêtre qui s'ouvre au passage de la souris ?
- Séparer les lignes interurbaines dans une autre catégorie : notamment chemins de fer Corse
- Que faire des navettes privées type Paris-Beauvais ? Peut-être dans la catégorie interurbain ?

**Comment by IshanB** [comment]
Je remets le mail de Bernard sur le service de recherche, où certaines réflexions sont bonnes à prendre : 

bonjour Béatrice,

Pour lancer la réflexion  sur le "service de recherche approprié" ,  voici quelques remarques sur la recherche de données sur le PAN; à  cet égard,  il  faut aussi  avoir en  tête que le site doit être aussi  clair que possible pour des personnes ne parlant pas bien  le français.

   - page d'accueil: on  tombe sur "trouvez un  jeu  de données",  mais on  ne sait pas comment faire;  ce n'est que si  l'on  fait au  hasard une recherche que l'on  commence à  découvrir,  à  partir des résultats de cette recherche,  comment cela fonctionne;  cela ne semble pas pleinement satisfaisant; ne devrait-il  pas y  avoir en  haut à  droite un  onglet supplémentaire :  chercher un  jeu  de données?

   - filtres:
          - la sélection par les régions me semble insuffisante ;  elle introduit en  outre une dissymétrie entre catégorie de territoires, qui  n'est pas satisfaisante ;  ne faut-il  pas une possibilité de tri par région, par autorité organisatrice urbaine et par opérateur de transport ( Air France, Tisseo,...);   cela permettra de repérer les AO n'ayant pas ouvert leurs données,  ce qui  commence à  nous intéresser;  en outre,  il  faut traiter correctement les cas particuliers et s'interdire un  "national" dans la liste des régions;
             en  outre rien  ne justifie que "transilien"  soit classé dans national  
     
         -  les types de données:  
                      "transport public" ne me semble pas un  type de données;  la juxtaposition  de "transport public" ( pour désigner les horaires théoriques du  transport public) et de temps réel ( pour désigner les horaires en  temps réel du  transport public) me semble prêter à  confusion;
                       ne vaut-il  pas mieux écrire:
                                  disponibilité en  temps réel  du  vélo  en  partage;
                                   horaires théoriques des services réguliers de transport  public
                                   horaires en  temps réel des services réguliers de transport public
       Certes,  il  y  a aujourd'hui  principalement des horaires sur le PAN;  il n'en  faut pas moins anticiper la présence d'autres types de données demain ( tarifs,....) 

            -  comment rechercher les "trains"  d'une d'une "région"  , sachant qu'ils se trouvent :
                               - dans le fichier de la région,  parfois ;  par exemple:  Bretagne transport public
                                - dans le "national",  fichier de l'ensemble des TER
                si  je tape,  "bretagne train", j'obtiens un  résultat,  mais "nouvelle aquitaine  train" ne donne rien;

            - si  je cherche "ferries",  équivalent de "train", je ne trouve rien;  mais "maritime" donne des résultats ;  mais comment trouver la nomenclature des modes?   
                        
 
  -  sur la mention  "jeux de données valides disponibles":  je n'ai pas trouvé d'explication  sur ce qu'était un  jeu  "valide";   


Tout d'abord la nomenclature  :
     actuellement: type de réseau, régions, types de données;
                   cela me semble à  revoir;
     on peut réfléchir à  partir des  rubriques suivantes: 
                   territoires, services de mobilité ,  catégories de données
                    il  peut y  avoir des sous-catégories de territoires. 
                    il  faut aussi  bien  réfléchir à  la liste des territoires,  des services de mobilité et des catégories de données;  réfléchir aussi  à  la dénomination  de chaque élément de la liste  ;  par exemple,  parle-t-on  de "train" ou  de  "services ferroviaires",  de ferries ou  de services maritimes,  ...

**Comment by antoine-de** [comment]
hum mais tu voudrais du coup structurer la page comment ? j'ai du mal à comprendre comment pourrait être affichée ta vision en 3 niveaux.

Une réflexion en vrac, mais j'ai l'impression que la séparation en verticales pose des soucis vu que qu'il n'y a pas une association 1-1 entre les verticales et les jeux de données. On peut par exemple avoir des données maritime dans le GTFS d'une région, ou des données régionales et urbaines mixées. Est ce qu'on devrait pas du coup s'appuyer sur les meta data calculées (ou sur [Topo](https://github.com/etalab/transport-topo/)) pour ne plus associer un jdd à une seule verticale ?

**Comment by Tristramg** [comment]
Je pense qu’il y a urgence à découper en mini-stats à rajouter.

Et on ré-organisera après quand ça sera plus clair dans nos têtes.

**Comment by Tristramg** [comment]
Je ferme. On a fait une grosse passe sur /stats.

Maintenant à gérer au cas par cas.
