### ISSUE TITLE
Format du champ last_reported dans l'implementation du GBFS

### ISSUE THREAD

**Issue by nicolas-bonnel** [etalab/transport-site#898]
Bonjour,

Si j'ai bien compris, vous transformez des flux temps réel de disponibilité des vélos des différents opérateurs au format GBFS. C'est une excellente initiative pour tout uniformiser, mais j'ai relevé une incohérence :

Les statuts des stations n'ont pas tout a fait le meme format pour le champs last_reported :
 * https://transport.data.gouv.fr/gbfs/nantes/station_status.json (transformation effectuée par vos soin)
 * https://vannes-gbfs.klervi.net/gbfs/en/station_status.json (flux mis a disposition par un opérateur)

Il semblerait suivant la spécification que le bon format soit le 2e, un Integer POSIX timestamp étant en secondes et non millisecondes.

Si je me suis trompé de repository, merci de m'indiquer celui ou je dois soumettre ce genre de ticket.

**Comment by Tristramg** [comment]
Bonjour,

Merci pour ce retour, c’est le bon repository pour ce genre de bug.

Il devrait être corrigé rapidement
