### ISSUE TITLE
Référencer OSM comme source de données routieres (et autre ?)

### ISSUE THREAD

**Issue by antoine-de** [etalab/transport-site#904]
La DGITM est d'accord sur le fait de référencer directement OSM comme source de données routières.

Il faut qu'on voit comment faire ca sur la plateforme.

On pourrait peut être simplement intégrer un petit texte d'intro sur la recherche filtrée par type (donc quand on clique sur une des tuiles principales de la home), pour dire pour certains types que des données quali sont dispo sur osm ?

ou juste mettre ca sur le wiki (et on le référence mieux ?)

Après on peut aussi voir pour héberger des extrait d'osm (extrait géographique et/ou par verticales), mais j'ai l'impression qu'il n'y a pas de plus-value, et que du coup on aurait plus unicité de licence.

Je pense qu'on peut aussi l'appliquer à d'autres verticales : pietons, cyclables voir accessibilité non ?

**Comment by Tristramg** [comment]
J’ai peur que si nous faisons un extrait thématique, on va finir par passer beaucoup de temps à gérer les tags et savoir comment qualifier les choses.

Sinon il y a aussi http://professionnels.ign.fr/route500 qui permettrait de se débarasser de la question :p

**Comment by antoine-de** [comment]
oui je suis complètement d'accord, un extrait thématique me semble galère et peu utile.

pour l'ign, je crois que c'est compliqué de faire bouger les choses d'ici décembre :stuck_out_tongue_winking_eye:

**Comment by Tristramg** [comment]
pourquoi ? c’est de la licence ouverte.
Faut juste qu’on ne mette pas que les CPU s’appliquent et c’est plié

**Comment by antoine-de** [comment]
ah oui, je pensais pas.
a discuter du coup

**Comment by be-mercier** [comment]
Je viens de créer une issue pour référencer les données routières qui fait un peu doublon avec cette issue-ci, mais en effet on peut référencer en one shot les deux jdd suivants: 
https://www.data.gouv.fr/fr/datasets/route-500/ 
et https://www.data.gouv.fr/fr/datasets/reseau-de-transport-routier-route-france-metropolitaine/ du CEREMA. 

L'avantage de "référencer" OSM, même ne serait-ce que par la mise à dispo d'un lien, est que ça permet de cocher la carte aménagements cyclables aussi.

**Comment by be-mercier** [comment]
Un membre d'OSM France vient de publier: 
https://www.data.gouv.fr/fr/datasets/5df7bb6a634f410f690ae7ea/

**Comment by Tristramg** [comment]
En attendant d’avoir un extrait utilisable directement, on considère qu’on a fait le taf et route500 suffit.
