### ISSUE TITLE
Tableau des AOMs + stats (peut-être pas que) - nom et compte des régions

### ISSUE THREAD

**Issue by antoine-martin-ponts** [etalab/transport-site#911]
Il faut faire en sorte de traiter pareil les 13 régions métropolitaines + Guadeloupe, Guyane, Martinique, Mayotte, La Réunion, Saint-Martin, Nouvelle-Calédonie.

Donc :
- sur le tableau des AOMs avoir les régions écrites pour les outre-mer (ça doit venir de plus haut le problème d'information)
- avoir des stats sur 20 régions qui comptent bien les DROM (on a les données de la Réunion)

**Comment by Tristramg** [comment]
Le lien AOM<>Région pour les DROM a été réparé.

St Martin et Nouvelle Calédonie n’étant pas des régions, j’ai rien fait pour eux (ni pour les autres COM  Polynésie française, Saint-Barthélemy, Saint-Pierre-et-Miquelon et Wallis-et-Futuna pour lesquels il ne semble pas y avoir d’AOM)
