### ISSUE TITLE
Tableau des AOMs - rendre possible le tri ? 

### ISSUE THREAD

**Issue by be-mercier** [etalab/transport-site#922]
Serait-il possible de trier l'ordre selon lequel les réseaux s'affichent en cliquant l'intitulé de chaque colonne ? 
Idéalement, les AOMs pourront être triées par : 
- par département
- par Région
- Publié en propre ? Oui/Non
-  Publié dans un agrégat ? Oui/Non
- A jour ? Oui/Non
- Existence du temps réel ?

**Comment by Tristramg** [comment]
Mais ils sont déjà triables ! Ce qu’il manque c’est une petit icône histoire de marquer dans quel sens c’est et le découvrir ;)

**Comment by be-mercier** [comment]
My bad ! effectivement, j'aurais du tester le tri avant de rapporter ces demandes telles quelles.
