### ISSUE TITLE
Changer l'appelation "Région Sud" à "Provence-Alpes-Côte d’Azur" tout simplement

### ISSUE THREAD

**Issue by be-mercier** [etalab/transport-site#923]
Je suis partagée. 

D'un côté, Claudine nous remonte que le nom "Région Sud" ne correspond pas à une dénomination officielle (car la demande de changement de nom n’a pas été déposée auprès du Conseil d’Etat par le conseil régional). 

De l'autre, c'est ce qu'il y a marqué sur le logo de la Région et dans l'intitulé du JDD : https://www.data.gouv.fr/fr/datasets/lignes-autocars-interurbains-regionsud/

**Comment by Tristramg** [comment]
Que les gens puisse se faire appeler comme elles le souhaitent ;)

Plus sérieusement, je vois pas le soucis. Certains vont vouloir faire des recherches par « Région Sud », donc ça me semble nécessaire et je ne vois pas le moindre dommage que ça pourrait faire.

**Comment by be-mercier** [comment]
Agreed, Antoine a écrit un message plutôt ferme à Claudine expliquant pourquoi on maintenait les deux options.
