### ISSUE TITLE
Référencer données annexes (par ex: horaires ouvertures des gares)

### ISSUE THREAD

**Issue by be-mercier** [etalab/transport-site#930]
Aujourd'hui, on trouve sur transport.data.gouv.fr le référentiel d'arrêts publiés par Trainline (mais ne correspondant pas à une tuile spécifique). 

Avec la base topo, ne devrait-on pas réfléchir à référencer d'autres jdd de ce type, comme les horaires d'ouverture des gares : 
https://ressources.data.sncf.com/explore/dataset/horaires-des-gares1/table/?sort=nom_normal

**Comment by be-mercier** [comment]
Voir également : https://www.data.gouv.fr/fr/datasets/cartographie-openstreetmap-des-gares-sncf-transilien-en-ile-de-france-1/

**Comment by Tristramg** [comment]
Ajouté
