### ISSUE TITLE
Nom de l'AOM affiché pour des jdd comme le VLS 

### ISSUE THREAD

**Issue by be-mercier** [etalab/transport-site#931]
Les données pour les réseaux VLS affichent le nom de l'AOM et non le nom de la métropole dans leur titre (alors que ces services sont organisés par les métropoles / villes). 

ex: - VélÔToulouse (titre affiché : SMTC Tisséo Collectivité - Vélo partage )
- C.Velo (titre affiché : SMTC de Clermont-Ferrand - Vélo partage )
- vélo'v (titre affiché : SYTRAL - Vélo partage)

**Comment by antoine-de** [comment]
oui, il faut qu'on puisse attacher un jdd à une ville et et non plus seulement à une AOM/région.

Le plus c'est peut etre simplement de garder l'association faite dans data.gouv à un lieu.

par example le jdd de vls de lyon est rattaché à lyon dans datagouv:

https://www.data.gouv.fr/fr/datasets/velos-libre-service-lyon-velov-disponibilite-en-temps-reel/

ce champ a l'air de se trouver dans l'api datagouv ([example](https://www.data.gouv.fr/api/1/datasets/5defcb1c634f413ad267d96d/)) avec `.spatial.zones[]`

aprés il faut voir comment parser le champ, dans l'example il est à `"fr:commune:69123@1963-08-07"`

Ca va aussi permettre de faire une partie stats sympa sur le vls

**Comment by antoine-de** [comment]
je viens de découvrir qu'on avait la liste des communes en base.

Du coup on peut proprement stocker une association `Dataset` -> `Commune`.

* ca permettrait de gérer les données de VLS, 
* mais aussi de transport quand c'est un sous jeu de données de l'AOM (par example [les données théorique et rt de rosny](https://transport.data.gouv.fr/datasets/horaires-theoriques-et-temps-reel-du-reseau-titus-rosny-sous-bois-gtfs-gtfs-rt/), ou le jdd de l'ile de ré qu'on arrive pas à faire rentrer quelque part vu qu'il n'y a pas d'AO équivalente)

:heavy_minus_sign: par contre ca va etre un peu dégueu niveau code, on a deja pas mal de code pour checker si le dataset est rattaché à une region ou une AO, ca rajoute un 3eme lien (`region_id=? OR aom_id IN (SELECT id from aom WHERE region_id=?)`...). 

De plus est ce que c'est pas la porte ouverte à toutes les fenêtres et qu'on voudra pas ensuite rajouter un lien vers un autre découpage administratif (communauté de commune ou autre) ?

**Comment by antoine-de** [comment]
je rebondi sur le fait de simplement utiliser la géométrie des territoires attachés via datagouv, (cf l'issue #970 ) le soucis c'est qu'on : 
* a un système un peu bancal, avec des `dataset` attaché à des AO, à des Régions et à simplement une géométrie.
* on ne peut plus récupérer tous les jeux de données d'une région (à moins de changer les requêtes pour faire une jointure sur les AO rattachées à la région + une jointure sur les shapes contenues dans la région)

je sais pas à quel point le 2éme point est embêtant, je pense que c'est utilisé dans la recherche quand on filtre les jdd d'une region et dans les stats pour faire des stats par régions.

je sais pas trop comment faire du coup.
1. Récupérer les communes associées via data.gouv pour faire un lien `Dataset`->`Commune`.
   -> ca veut dire que ca ne fonctionne que pour les communes
   -> le code va pas être dingue pour les associations (cf commentaire au dessus)
2. On garde juste des géométries
   -> soit on fait des requêtes spatiales, soit on perd le lien vers la région
   -> ca permet de gérer tout type de zone

Un avis @Tristramg ?

j'ai l'impression que le 1 est plus cohérent

**Comment by antoine-de** [comment]
un autre point embêtant  est que certain dataset peuvent être attachés à plusieurs zones dans datagouv, mais dans transport on ne peut pour le moment n'être rattaché qu'à une zone.
on peut fusionner les géométries pour n'en faire qu'une, mais le soucis est qu'on se sert du territoire (le champ `spatial`) pour le titre du dataset ("Centre-Val de Loire - Horaires théoriques de transport public") par exemple). 

Si on récupère les zones de datagouv, on met un champs libre dans le backoffice pour nommer la zone ?
par exemple pour https://www.data.gouv.fr/fr/datasets/horaires-theoriques-et-temps-reel-de-la-navette-de-sel-et-vermois-gtfs-gtfs-rt/, j'ai l'impression qu'il faudrait mettre la communauté de commune non ? (dans ce cas la, il ne me semble pas que la cc soit une AO, mais je ne suis pas sur).

Ca serait aussi dommage de perdre le nom des communes composant la CC pour la recherche.

Bref j'ai l'impression qu'il faut qu'on fasse un peu attention avec cette feature a ne pas faire un truc bancal.

**Comment by antoine-de** [comment]
Aprés réflexion on va abstraire l'association geographic d'un dataset dans une [view sql](https://www.postgresql.org/docs/9.3/sql-createview.html).

Ca va nous permettre d'associer un dataset à :
* une region
* une ao
* une liste de communes

Tout en limitant les impacts sur le code.
