### ISSUE TITLE
Réfléchir à un système de tags ?

### ISSUE THREAD

**Issue by be-mercier** [etalab/transport-site#936]
Comme Antoine avait proposé lors de nos discussions sur la réponse à apporter aux demandes de Bernard pour améliorer le service de recherche, un système de tags pourrait nous permettre de mettre en avant 

Je viens de découvrir que plusieurs jeux de données publiés sur le PAN contiennent des trajets effectués en bateau (liaison maritime ou batobus) comme : 
- le jdd aggrégé de Bretagne (liaisons maritimes du Morbihan, liaisons maritimes du Finistère, Liaisons maritimes Île d'Arz et  Liaisons maritimes Île de Bréhat)
- le GTFS de Nantes (ligne Navibus vers Trentemoult)
- le GTFS de Marseille (Les îles du Frioul) 

Il faudrait réfléchir à comment mettre en avant l'existence de ces données.

**Comment by be-mercier** [comment]
pardon ma première phrase est incomplète : un système de tags pourrait nous permettre de mettre en avant ces données. 

De manière générale, ça peut nous aider à mettre en avant les infos contenues dans des jdds agrégés (expliciter qu'un GTFS contient lignes, arrêts ET horaires).

**Comment by antoine-de** [comment]
Oui je pense que c'est une bonne idée.

Un premier pas pourrait être simplement de mettre la liste des modes de transports qu'on extrait avec le validateur comme tag.

**Comment by Tristramg** [comment]
Donc si je résume les discussions, le premier cas d’usage c’est :

_Tous les jeux de données qui contiennent du bateau_, c’est ça ?

Actuellement, on extrait bien les méta-données des transports des GTFS, donc on a l’information.

On a un système de filtre qui permet de les chercher : https://transport.data.gouv.fr/datasets?tags[]=ferry

Comment/où est-ce qu’on mettrait un lien vers cette page ?

Solution 1 : sous la recherche, juste lister les tags et ça amène à la page
 * pour : facilement découvrable
 * contre : pourquoi il y aurait-il une tuile « train  » plus bas et pas « ferry » ?
Solution 2 : générer une tuile par mode de transport
 * pour : on sera plus cohérent avec le reste du site
 * contre : ça prend beaucoup de place, y’aura deux moyens d’avoir du ferré

**Comment by antoine-de** [comment]
#### Solution 1 :
pourquoi pas, ca a le mérite d'aider en effet la découvrabilité.
:question:  il faut, sur la page de recherche vers laquelle ca pointe, un rappel du tag, avec potentiellement un moyen de le changer
:heavy_minus_sign: (mineur) on ne peut pas combiner les tags (mais en vrai je pense que c'est rarement utile)

#### Solution 2 :
je suis pas trop convaincu, surtout vu la nature non rigide des tags.

#### Solution 3 :
Simplement rajouter une section "recherche par mot clé" dans la page de recherche.

:heavy_check_mark: ca peut se combiner avec la solution 1 pour aider la découvrabilité

##### Solution 3a :
Solution simple qui fonctionne tant qu'on a très peu de tags :
![image](https://user-images.githubusercontent.com/3987698/71358480-fa15dd80-2580-11ea-9175-91267e008676.png)

:heavy_minus_sign: ca tient que tant qu'on ne met que les modes dedans
:heavy_check_mark: c'est simple

##### Solution 3b :
champs libre pour ajouter des filtres sur des tags :
![image](https://user-images.githubusercontent.com/3987698/71358030-74456280-257f-11ea-91e0-823fb339fd1f.png)


:heavy_minus_sign: niveau découvrabilité, c'est pas ouf, même si on peut jouer sur le placeholder et peut être sur un moyen de récupérer la liste de tous les tags pour aider
:heavy_check_mark: on peut faire de l'autocomplétion
:heavy_minus_sign: je vois pas comment implémenter ca :stuck_out_tongue_winking_eye:

**Comment by Tristramg** [comment]
Solution 3 :

> Simplement rajouter une section "recherche par mot clé" dans la page de recherche.

La _page de recherche_ c’est quoi ? La page d’accueil où il a la barre de recherche ou la page de résultat ?

Dans le 2ème cas, ça suppose de découvrir ça que dans un 2ème temps. Pas fou pour la découvrabilité, non ? Et si je veux tous les jeux de données avec du métro, comme ça se passe ?

Si c’est sur la page d’accueil, comment je liste tous les jeux de données ? faut laisser le champ de recherche vide ? Pas très naturel, non ?

Si on considère que les tags sont des filtres [tramway], [bus] activé et que je tape « perpignan », est-ce que je n’aura rien parce il n’y a pas de tram ici ?

Point vocabulaire : _recherche par mot clef_ sous-entend que je peux taper « métro » dans la barre de recherche. Je ne crois pas que ce soit l’idée, si ?

**Comment by antoine-de** [comment]
la page de recherche pour moi c'est ce que tu appelles la page de résultats (la page avec tous les filtres).
Effectivement niveau découvrabilité c'est pas ouf. Faut voir effectivement si on peut pas faire un lien plus direct depuis la home. (mais c'est en fait peut etre 2 pb séparés).

> Et si je veux tous les jeux de données avec du métro, comme ça se passe ?

ben j'ai pas l’impression que ca pose de pb de sélectionner le tag `metro` et de devoir laisser le champs texte de recherche vide, mais je suis peut être biaisé, il faudrait faire des tests.
 
> Si on considère que les tags sont des filtres [tramway], [bus] activé et que je tape « perpignan », est-ce que je n’aura rien parce il n’y a pas de tram ici ?

ben j'ai l'impression que c'est le plus logique.

> Point vocabulaire : _recherche par mot clef_ sous-entend que je peux taper « métro » dans la barre de recherche. Je ne crois pas que ce soit l’idée, si ?

heu pour moi les tags (mots clés) sont ici une liste finie. On peut les trouver par autocomplétion (dans un champs de recherche séparé), ou, si besoin, en affichant tous les tags.

**Comment by fchabouis** [comment]
On peut faire des requêtes du style https://transport.data.gouv.fr/datasets?tags[]=ferry
et il y a les tuiles associées sur la home.
On peut fermer du coup ?

**Comment by antoine-de** [comment]
yep bien vu, j'ai l'impression qu'on peut fermer (et réouvrir une autre issue si on voit des amélios)
