### ISSUE TITLE
Modifications page stats

### ISSUE THREAD

**Issue by be-mercier** [etalab/transport-site#939]
Les retours de Claudine sur la nouvelle page stats : 

- Serait-il possible que les légendes des 3 cartes ne se superposent pas à la carte ? Ce qui m'éviterait de les masquer
Sinon je dois la décaler pour la copier coller et je perds de la précision car elle doit être plus petite.
- Serait il possible d'enlever les noms des pays voisins ?
- Pour finir ma liste de cadeaux de Noël, je souhaiterais qu'apparaissent les noms des régions si possible

**Comment by antoine-de** [comment]
* hum je ne pense pas que retirer les légendes soit vraiment la solution, c'est dommage une carte sans légende :stuck_out_tongue_winking_eye: et je ne vois pas bien comment avoir un rendu potable avec la légende à coté.
* non, ca veut dire qu'il nous faut notre fond de carte, c'est trop compliqué pour le gain
* Il y a le nom de la région quand on clique, mais sinon c'est pareil que le point d'avant, rajouter me semble trop compliqué pour le gain

**Comment by be-mercier** [comment]
Yes, j'ai expliqué à Claudine comment les cartes étaient produites pour qu'elle comprenne qu'on ne peut pas juste cliquer sur un bouton "supprimer" pour retirer les noms des pays frontaliers. 
Je prends le pari que prendre le temps d'expliquer les choses avec plus de détail sera plus facilement entendable :)
