### ISSUE TITLE
Améliorer la recherche par lieu

### ISSUE THREAD

**Issue by antoine-de** [etalab/transport-site#961]
je rebondi sur mon [commentaire](https://github.com/etalab/transport-site/issues/890#issuecomment-559561793) sur l'amélioration de la recherche par lieu (#890).

J'ai l'impression que la page de recherche serait plus clair si on virait la liste des régions 
![image](https://user-images.githubusercontent.com/3987698/69823423-b984a780-1200-11ea-8c15-c983f54bf90d.png)
pour la remplacer par un champs texte auto-complété.

On pourrait rechercher par région/AO/commune.
Note: j'ai un doute sur les villes je sais pas si c'est utile, surtout qu'on a pas de base de communes pour le moment. Dans une première version, peut etre s’arrêter aux régions/AO ?

j'ai l'impression que :
* ca rendrait plus clair le fait qu'on peut chercher par lieu (c'est déjà le cas dans la barre de recherche classique, mais la ca serait encore plus explicite)
* ca permet une recherche plus précise (QUE sur le lieu, et pas un champs composite comme avec la recherche 'globale')
* on a de l'autocomplétion pour aider à trouver la ville/région/AO, c'est cool, surtout quand on ne connaît pas précisément le nom de l'ao
* ca permet plus facilement de faire une page pour une AO qui n'aurait pas ouvert ses données (#902)

par contre, on perd le nombre de jdd par région, je sais pas si c'était une feature importante.

Ca pourrait donner :
![image](https://user-images.githubusercontent.com/3987698/71355382-d0f04f80-2576-11ea-8461-a7fbc52f9df0.png)

**Comment by Tristramg** [comment]
Hrmmm… à la base, c’était censé être un filtre, mais là c’est tout pété -_-' Sur le même mode que les autres filtres.

Si on décide de faire un recherche par territoire, il faudra le mettre ailleurs puisqu’il ne s’agira plus d’un filtre (enfin… bug aidant, ce n’est déjà pas le cas).

Je proposerais donc deux actions séparées :
* ajout d’une liste de tag « région » dans la barre de recherche actuelle pour pouvoir filtrer les jeux de données (cas d’usage assez courant si j’ai bien compris)
* ajouter une barre de recherche aussi importante que celle de jeu de données appelée « recherche par territoire » qui fonctionnerait par autocomplétion, où on préciserait « Île-de-France (Région) », « IdFM (AOM) » et qui amènerait à la page de l’aom ou de la région en fonction

(reflexion dans un coin : à force, avec les tags toute la barre de gauche devrait disparaitre je pense)

**Comment by Tristramg** [comment]
PS : sisi, on a bien une base des communes ;)

**Comment by antoine-de** [comment]
hum je suis pas certain de comprendre pourquoi ca ne serait pas un filtre, ca peut se combiner avec une recherche par mot clé, ou type non ? (même si effectivement pour le moment les filtres ne se combinent pas...).

je suis pas sur de comprendre la première action, tu voudrais rajouter en tag du dataset sa région pour qu'on puisse utiliser la recherche par tag dessus ?

**Comment by Tristramg** [comment]
J’ai compris qu’il y avait deux usages différents : filtrer une recherche et rechercher un territoire.

Actuellement (car bug) on croit filtrer mais en fait c’est une recherche par territoire.

D’où les deux actions.

Je ne crois pas qu’un filtre par AOM soit très pertinent, mais pour les régions ça l’est.
D’où la proposition de gérer les filtres sous forme de tags filtrants pour converger doucement vers un mode où tous les filtres sont des tags.

**Comment by antoine-de** [comment]
ah ok c'est parceque la liste des régions te renvoie sur `/dataset/region/<id>` ?

du coup ca serait pas plus cohérent de renvoyer vers `/dataset?where=<id de lieux>` (ou un meilleur nom de param), comme ca on peut le combiner avec les autres filtres (même si j'ai pas compris comment faire ca avec les templates `eex`)

**Comment by antoine-de** [comment]
désolé, on a posté en même temps.

Effectivement je suis pas convaincu de l’intérêt de filtrer par AOM, mais par contre de rechercher par AOM oui, tu penses pas que c'est plus cohérent de les traiter de la même façon ?

**Comment by Tristramg** [comment]
Je pense qu’il faut permettre d’accéder à `/dataset/region/pays-de-la-loire` et `/dataset/comune/nantes` et `/dataset/aom/tan` depuis le même menu de recherche en autocomplétion (mais pas de recherche en texte libre).

Ça permet de résoudre le problème des AOM qui n’ont pas de jeux de données à grands coups de chaton qui chiales là où auraient du être les jeux de données.

Ensuite, pour le besoin de filtrage (qui pour moi est un autre problème), utiliser le système de tags qu’on développe. Voilà l’idée :

![Frame 1(2)](https://user-images.githubusercontent.com/12235/71357775-13218d00-2587-11ea-929e-5fcadaa9660e.png)

**Comment by antoine-de** [comment]
tu ne penses pas que la distinction Région vs AOM/commune peut embrouiller par rapport à ne faire qu'un filtre, qui a l'avantage de traiter les types de territoires pareil et de pouvoir se combiner avec les autres filtres ?

en gros, les tags rajoutent un `tags[]=<tag>` à l'url, et la recherche par territoire rajoute un `where=<id recupéré via autocomplete` à l'url.

Et quand on a un filtre `where`, si on a pas de résultat on peut mettre un petit message.

les urls `data/{region,commune,aom}/<id> sont utilisées autre part ?

**Comment by Tristramg** [comment]
Je pense que tant qu’on mélange filtre et recherche, on ne ferra qu’embrouiller tout le monde, à commencer par nous-même tant qu’on ne met pas ça au clair.

Est-ce qu’on est d’accord ou pas pour dire qu’on a affaire à deux usages différents ou pas ?

À mon avis il vraiment trop tôt pour réfléchir à l’implem (`tag[]` / `where`) tant qu’on ne définit pas les cas d’usages (il faut probablement dégainer des outils à la con comme des personas, on s’en sort pas là, niveau discussion).

Actuellement, les urls `dataset/region` sont utilisés dans la colonne de gauche, et aussi quand on clique sur une région des cartes pour avoir tous les jeux de données d’une région.

Voici donc un cas d’usage que je trouve pertinent :

> Je veux tous les jeux de données d’une région.

J’ai du mal à imaginer un cas d’usage où je ferais une recherche « je veux les jeux de données de St Nazaire en Occitanie ». Y’a que 3 St Nazaire en France. On s’en sort très bien avec la recherche par jeux de données.

Du coup, je serais partisan de ne faire que la partie 2 de ma proposition initiale : une barre de recherche pour tous les territoire (AOM, région, Commune), en auto-complétion (qui précise comme dans le mock de la nature du territoire) qui amène à une page /commune/paris qui liste tous les jeux de données la concernant. 

Et on oublie complètement la possibilité de filtrer une recherche de jeux de données.

**Comment by antoine-de** [comment]
> Est-ce qu’on est d’accord ou pas pour dire qu’on a affaire à deux usages différents ou pas ?

Ce sont effectivement 2 usages différents, mais j'ai l'impression que les séparer crée plus de pb que de les mixer.

J'ai justement l'impression que ce qui m'embrouille avec le système actuel (je viens juste de le comprendre d'ailleurs :stuck_out_tongue_winking_eye: ) c'est qu'il est pensé pour chercher soit des datasets soit des régions/ao ce qui n'est pas super intuitif. (et ta proposition garde ce mélange un peu étrange).

> À mon avis il vraiment trop tôt pour réfléchir à l’implem (tag[] / where) tant qu’on ne définit pas les cas d’usages (il faut probablement dégainer des outils à la con comme des personas, on s’en sort pas là, niveau discussion).

oui j'ai parlé en terme d'url, je pensais que ca rendait plus clair mon propos, mais visiblement c'est pas le cas :stuck_out_tongue_winking_eye: 
:+1: pour avoir une discussion plus structurée

> J’ai du mal à imaginer un cas d’usage où je ferais une recherche « je veux les jeux de données de St Nazaire en Occitanie ». Y’a que 3 St Nazaire en France. On s’en sort très bien avec la recherche par jeux de données.

non effectivement mais la, le filtre sur région (par exemple [nouvelle aquitaine](https://transport.data.gouv.fr/datasets/region/9)) peuvent donner pas mal de résultats. J'ai l'impression que combiner les filtres peut apporter un vrai gain. Je ne vois effectivement pas ce que `filtre sur lieu` + `recherche libre` peut apporter, mais par contre `filtre sur lieu` + filtre par `tag` oui.

> Du coup, je serais partisan de ne faire que la partie 2 de ma proposition initiale : une barre de recherche pour tous les territoire (AOM, région, Commune), en auto-complétion (qui précise comme dans le mock de la nature du territoire) qui amène à une page /commune/paris qui liste tous les jeux de données la concernant.

Tu veux dire une barre de recherche depuis la home ? 
Pourquoi pas dans ce cas la, mais j'ai l'impression qu'il faut aussi reprendre cette barre de recherche dans la page de résultats, et dans ce cas la on revient au mélange recherche de jdd/recherche de lieu qui me confusionne :confounded: 

Du coup si on tire cette reflexion, j'ai l'impression que ca oblige à faire 2 pages de "recherche / résultats", une avec un champ de texte libre, et une avec des filtres. Et j'ai pas l'impression que cette séparation apporte grand chose.

Par contre si on garde 1 seule page de "recherche / résultats", j'ai l'impression que garder un système de recherche filtrée est une modélisation générique qui gère un peu tous les cas que j'ai en tête :
1. recherche super générique (mais du coup un peu foireuse) avec un texte libre
1. donne moi tous les jdd d'une région
1. donne moi les jdd d'une region avec du métro
1. donne moi les jdd d'une region avec du vls
1. donne moi les jdd avec des données temps réelle de transport public

En listant ca comme ca je suis d'accord qu'en fait il y a assez peu de gain fonctionnel à mixer ce que tu appelles 'recherche' avec des 'filtres', mais ca me semble plus logique et cohérent avec le fait qu'on cherche toujours des jdd, même si c'est effectivement à la condition que ca soit clair de laisser la barre de recherche (qui est centrale pour le moment) vide.

**Comment by Tristramg** [comment]
On peut considérer que la recherche par lieux est bien en l’état. Merci ! :heart:
