### ISSUE TITLE
Ateliers produit

### ISSUE THREAD

**Issue by Tristramg** [etalab/transport-site#962]
Actuellement, les améliorations produit ne sont pas très claires au sein de l’équipe.

Il faudrait faire des ateliers pour mettre les choses à plat, pour savoir par où aller.

Au cours de ces ateliers, il faudra pour chaque thématique identifier et documenter :
* un cas d’usage (à quel utilisateur est-ce qu’on s’adresse ?)
* pourquoi actuellement ce besoin n’est pas satisfait
* proposer une manière de traiter ce cas-là (en terme de produit, pas d’implémentation)
* séquençage technique pour l’implémentation

Parmi les sujets nécessaires à traiter :
- [x] Les données qui n’appartiennent ni à une AOM, ni à une région (par exemple les VLS d’une comunauté de commune)
- [x] Le mélange catégorie et format (VLS vs. train vs. horaires)
- [x] Les statistiques, en particulier pour les régions (complet/partiel… revoir les couleurs & légende…)
- [x] Recherche vs. filtre pour les territoires
- [x] Recherche par tag (qui peut toucher chacun des points précédents)

**Comment by antoine-de** [comment]
on s'en prévoit un demain (mardi 7 janvier) ?

Quel sujet on priorise ? j'aurais tendance à dire, soit le 1. soit le 4.

**Comment by antoine-de** [comment]
Conclusion du premier atelier:

La première phase est de faire des interviews utilisateurs centrées sur:

    Le grand public
    Les réutilisateurs connus

On met de côté:

    les territoires (on a l'impression qu'ils ont besoin de cartes)
    les réutilisateurs potentiels (on voit pas trop comment les contacter)
    les réutilisateurs inconnus (encore plus compliqué à contacter)
    Les régulateurs (on fera des dev hors produit pour répondre aux besoins de reporting)

On va aborder les interviews pour creuser les besoins de carte et d'amélioration de la barre de recherche.

**Comment by antoine-de** [comment]
Pour le point produit du 30/01 je vois les potentiels sujets :

## Page [/stats](https://transport.data.gouv.fr/stats)
Comment améliorer les stats sur les régions (mieux faire comprendre la différence complet / partiel).
lié à #865 

## AO / Région sans données
#902 

## Amélioration de la découvrabilité des données
Quelles sont les prochaines étapes ? Peut on faire des choses sans interview utilisateur ?

**Comment by fchabouis** [comment]
J'ai l'impression qu'on est bon la dessus !

revoir les stats -> #1129 
Recherche vs. filtre pour les territoires -> #1069 #1098
