### ISSUE TITLE
Utiliser les territoires de data.gouv.fr

### ISSUE THREAD

**Issue by Tristramg** [etalab/transport-site#970]
Sur data.gouv.fr, un jeu de données peut être associé à un territoire. Par exemple https://www.data.gouv.fr/fr/datasets/horaires-theoriques-et-temps-reel-de-la-navette-de-sel-et-vermois-gtfs-gtfs-rt/

Il faudrait dans le backoffice, en plus de AOM et région, il faudrait pouvoir cocher « prendre le territoire de data.gouv.fr »

**Comment by antoine-de** [comment]
duplicate with #931
