### ISSUE TITLE
Page d’accueil : faire comprendre qu’il y a plus en bas

### ISSUE THREAD

**Issue by Tristramg** [etalab/transport-site#973]
Notre landing est très belle. Mais des personnes se font avoir et pensent qu’il n’y a que la barre de recherche et ne pensent pas à scroller.

**Comment by antoine-de** [comment]
La première phase est de faire des interviews utilisateurs centrées sur:
* Le grand public
* Les réutilisateurs connus

On met de côté:
* les territoires (on a l'impression qu'ils ont besoin de cartes)
* les réutilisateurs potentiels (on voit pas trop comment les contacter)
* les réutilisateurs inconnus (encore plus compliqué à contacter)
* Les régulateurs (on fera des dev hors produit pour répondre aux besoins de reporting)

On va aborder les interviews pour creuser les besoins de carte et d'amélioration de la barre de recherche.

**Comment by antoine-de** [comment]
idée: mettre une flèche en bas (au milieu) de l'écran qui pointe vers les tuiles

On va peut etre encore avec le même problème pour montrer qu'on peut encore scroller plus bas, à voir si c'est suffisant ou si il faut une autre flèche.
